import {useState} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import {qModeConflictFixture,qModeReadyFixture,qModeResumeFixture,qModeShortageFixture} from '../../dev/coop-qmode-fixtures';
import {qModeStatusCanEnterRun,validateCoopQModeTeam,type CoopQModeTeamView} from '../../core/coop-qmode';
import {coopColors,coopSpacing,coopTypography} from '../../theme/coop-ui-theme';
import {FantasyPanel,PrimaryAction,RoleBadge,StateChip} from './CoopVisualKit';
const fixtures={ready:qModeReadyFixture,resume:qModeResumeFixture,shortage:qModeShortageFixture,conflict:qModeConflictFixture};
export function CoopQModeTeamGallery(){const [state,setState]=useState<keyof typeof fixtures>('ready'),view=fixtures[state];validateCoopQModeTeam(view);return <View style={s.stack}><Text style={s.section}>Phase 05 · Q-Mode team states</Text><Text style={s.warning}>Development gallery only · no recruitment or run is started</Text><View style={s.controls}>{(Object.keys(fixtures) as Array<keyof typeof fixtures>).map(key=><View key={key} style={s.control}><PrimaryAction label={key} tone="secondary" selected={state===key} onPress={()=>setState(key)}/></View>)}</View><Team view={view}/></View>}
function Team({view}:{view:CoopQModeTeamView}){const canEnter=qModeStatusCanEnterRun(view);return <View style={s.stack}><FantasyPanel variant={canEnter?'success':view.status==='resuming'?'selected':'danger'}><View style={s.heading}><Text style={s.title}>{view.status==='ready'?'Team ready':view.status==='resuming'?'Restoring run…':view.status==='candidate_shortage'?'Echo candidate unavailable':'Content update required'}</Text><StateChip label={view.status} tone={canEnter?'success':view.status==='resuming'?'warning':'danger'}/></View><Text style={s.copy}>{view.message??'You choose the route · no party chat · saved builds are controlled automatically.'}</Text></FantasyPanel><View style={s.grid}>{view.members.map(member=><FantasyPanel key={member.memberId} variant={member.status==='ready'?'default':'disabled'} style={s.member}><RoleBadge role={member.role} label={member.role}/><Text style={s.name}>{member.displayName}</Text><Text style={s.copy}>Effective level {member.effectiveLevel}</Text><Text style={s.echo}>{member.kind==='echo'?'Saved player build · automated ally':'Your verified character'}</Text></FantasyPanel>)}</View><PrimaryAction label={view.status==='ready'?'Open expedition map':view.status==='resuming'?'Checking server state…':'Return to loadout'} disabled={!canEnter}/></View>}
const s=StyleSheet.create({stack:{gap:coopSpacing.md},section:{...coopTypography.section,color:coopColors.gold},warning:{...coopTypography.meta,color:coopColors.gold},controls:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.xs},control:{flexGrow:1,minWidth:72},heading:{flexDirection:'row',alignItems:'center',gap:coopSpacing.sm},title:{...coopTypography.section,color:coopColors.text,flex:1},copy:{...coopTypography.body,color:coopColors.textSecondary},grid:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.sm},member:{width:'48%',flexGrow:1},name:{...coopTypography.section,color:coopColors.text},echo:{...coopTypography.meta,color:coopColors.cyan}});
