import {useMemo,useState} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import type {CoopRoomType} from '../../core/coop-dungeon-browsing';
import {buildCoopDecisionIntent,coopRouteProgress,tallyCoopVotes,validateCoopRouteGraphView,validatePersonalOffer,type CoopDecisionView,type CoopPersonalOfferView,type CoopRouteGraphView,type CoopRouteNodeView} from '../../core/coop-shared-run';
import type {CoopUiAssetId} from '../../core/coop-ui-contract';
import {boonOfferFixture,coopRouteFixture,liveDecisionFixture,qDecisionFixture} from '../../dev/coop-shared-run-fixtures';
import {coopColors,coopSpacing,coopTypography} from '../../theme/coop-ui-theme';
import {CoopImageSlot,FantasyPanel,PrimaryAction,RoleBadge,StateChip} from './CoopVisualKit';

const asset:Partial<Record<CoopRoomType|'entry',CoopUiAssetId>>={battle:'node_battle',elite:'node_elite',event:'node_event',shrine:'node_shrine',camp:'node_camp',treasure:'node_treasure',merchant:'node_merchant',echo:'node_echo',risk:'node_risk',boss:'node_boss'};
export function CoopSharedRunGallery(){
  const [view,setView]=useState<'map'|'live'|'qmode'|'boon'|'combat'>('map');
  const [notice,setNotice]=useState('');
  return <View style={s.stack}><Text style={s.section}>Phase 04 · Shared run fixtures</Text><Text style={s.warning}>Development gallery only · commands are not sent</Text><View style={s.tabs}>{(['map','live','qmode','boon','combat'] as const).map(id=><View key={id} style={s.tab}><PrimaryAction label={id==='qmode'?'Q':id[0].toUpperCase()+id.slice(1)} tone="secondary" selected={view===id} onPress={()=>{setView(id);setNotice('')}}/></View>)}</View>{notice?<Text accessibilityRole="alert" style={s.notice}>{notice}</Text>:null}{view==='map'?<RouteMap graph={coopRouteFixture} onContinue={()=>setView('live')}/>:null}{view==='live'?<DecisionPanel decision={liveDecisionFixture} onIntent={intent=>setNotice(`${intent.kind} intent ${intent.requestId} prepared; awaiting server acknowledgement.`)}/>:null}{view==='qmode'?<DecisionPanel decision={qDecisionFixture} onIntent={intent=>setNotice(`${intent.kind} intent ${intent.requestId} prepared; awaiting server acknowledgement.`)}/>:null}{view==='boon'?<PersonalOffer offer={boonOfferFixture} onSelect={()=>setNotice('Personal offer intent prepared; no outcome or claim was simulated.')}/>:null}{view==='combat'?<CombatFixture/>:null}</View>;
}
function RouteMap({graph,onContinue}:{graph:CoopRouteGraphView;onContinue:()=>void}){validateCoopRouteGraphView(graph);const progress=coopRouteProgress(graph),depths=Array.from({length:graph.preBossNodeCount+2},(_,i)=>i);return <View style={s.stack}><FantasyPanel variant={graph.stale?'danger':'selected'}><Text style={s.title}>Rootbound Vault</Text><Text style={s.copy}>Rooms completed: {progress.completed} of {progress.total} · Boss follows</Text>{graph.stale?<StateChip label="Stale projection" tone="danger"/>:<StateChip label="Current decision available" tone="success"/>}</FantasyPanel>{depths.map(depth=><View key={depth} style={s.layer}><Text style={s.depth}>{depth===0?'ENTRY':depth===graph.preBossNodeCount+1?'BOSS':`ROOM ${depth}`}</Text><View style={s.nodes}>{graph.nodes.filter(node=>node.depth===depth).map(node=><MapNode key={node.nodeId} node={node}/>)}</View>{depth<graph.preBossNodeCount+1?<Text accessibilityLabel="Forward route edges" style={s.edge}>│  │  │</Text>:null}</View>)}<Text style={s.copy}>Accessible list: {graph.nodes.filter(node=>node.status==='available').map(node=>node.title).join(' · ')}</Text><PrimaryAction label="Continue to current decision" onPress={onContinue}/></View>}
function MapNode({node}:{node:CoopRouteNodeView}){const tone=node.status==='completed'?'success':node.status==='available'?'selected':node.status==='hidden'?'warning':'neutral';return <View style={[s.mapNode,node.status==='locked'&&s.locked]}><CoopImageSlot assetId={asset[node.kind]} size="node" fallbackLabel="◇" accessibilityLabel={node.title}/><StateChip label={node.status==='completed'?'✓ Complete':node.status} tone={tone}/><Text numberOfLines={2} style={s.nodeName}>{node.status==='hidden'?'Hidden route':node.title}</Text></View>}
function DecisionPanel({decision,onIntent}:{decision:CoopDecisionView;onIntent:(value:ReturnType<typeof buildCoopDecisionIntent>)=>void}){const counts=useMemo(()=>tallyCoopVotes(decision),[decision]),voted=decision.votes?.length??0;return <View style={s.stack}><FantasyPanel variant={decision.status==='resolving'?'selected':'default'}><Text style={s.title}>{decision.mode==='live'?'Vote for the next route':'Choose your route'}</Text>{decision.mode==='live'?<Text style={s.copy}>Server deadline · {voted}/{decision.eligibleVoterIds?.length??0} voted</Text>:<Text style={s.copy}>You choose the route · no countdown · no votes · no party chat</Text>}</FantasyPanel>{decision.options.map((option,index)=><FantasyPanel key={option.nodeId} variant={decision.localOptionId===option.nodeId?'selected':'default'}><View style={s.option}><CoopImageSlot assetId={asset[option.kind]} size="room" accessibilityLabel={option.title}/><View style={s.optionCopy}><Text style={s.title}>{option.title}</Text><Text style={s.copy}>{option.summary}</Text><Text style={s.meta}>Risk: {option.riskLabel} · Likely: {option.rewardLabel}</Text>{decision.mode==='live'?<><Text style={s.vote}>{counts[option.nodeId]} vote{counts[option.nodeId]===1?'':'s'}{decision.localOptionId===option.nodeId?' · ✓ Your vote':''}</Text><Text style={s.meta}>{decision.votes?.filter(vote=>vote.optionId===option.nodeId).map(vote=>vote.displayName).join(' · ')||'No votes yet'}</Text></>:null}<PrimaryAction label={decision.mode==='live'?'Vote':'Choose'} disabled={decision.status!=='open'} selected={decision.localOptionId===option.nodeId} onPress={()=>onIntent(buildCoopDecisionIntent(decision,option.nodeId,`gallery-${decision.mode}-${index}`))}/></View></View></FantasyPanel>)}</View>}
function PersonalOffer({offer,onSelect}:{offer:CoopPersonalOfferView;onSelect:(id:string)=>void}){validatePersonalOffer(offer);return <View style={s.stack}><FantasyPanel><Text style={s.title}>Choose a personal boon</Text><StateChip label="Personal · this run" tone="selected"/><Text style={s.copy}>Owned effects: {offer.ownedEffects.join(' · ')}</Text></FantasyPanel>{offer.options.map(option=><FantasyPanel key={option.id}><View style={s.option}><CoopImageSlot assetId={option.artId} size="boon" accessibilityLabel={option.name}/><View style={s.optionCopy}><Text style={s.title}>{option.name}</Text><Text style={s.meta}>{option.rarity}</Text><Text style={s.copy}>{option.effectText}</Text><PrimaryAction label="Select boon" onPress={()=>onSelect(option.id)}/></View></View></FantasyPanel>)}</View>}
function CombatFixture(){const members=[['Tank','tank',82],['Damage','damage',64],['Damage','damage',0],['Support','support',91]] as const;return <View style={s.stack}><FantasyPanel variant="danger"><Text style={s.title}>Rootbound Warden · Phase 2</Text><Text style={s.copy}>Boss mechanic: Crushing Roots · authoritative snapshot</Text><View style={s.hp}><View style={[s.hpFill,{width:'58%'}]}/></View></FantasyPanel><View style={s.party}>{members.map(([name,role,hp],index)=><FantasyPanel key={`${role}-${index}`} variant={hp===0?'danger':'default'} style={s.member}><RoleBadge role={role} label={name}/><Text style={s.copy}>{hp===0?'Downed':`${hp}% health`}</Text></FantasyPanel>)}</View><FantasyPanel><Text style={s.title}>Presentation event log</Text><Text style={s.copy}>#142 Warden begins Crushing Roots{`\n`}#143 Ironwarden guards the party{`\n`}#144 Wayfinder is downed</Text></FantasyPanel><Text style={s.warning}>No manual combat, pause, speed, or chat command is exposed by this fixture.</Text></View>}
const s=StyleSheet.create({stack:{gap:coopSpacing.md},section:{...coopTypography.section,color:coopColors.gold},title:{...coopTypography.section,color:coopColors.text},copy:{...coopTypography.body,color:coopColors.textSecondary},meta:{...coopTypography.meta,color:coopColors.textMuted},warning:{...coopTypography.meta,color:coopColors.gold},notice:{...coopTypography.meta,color:coopColors.cyan},tabs:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.xs},tab:{minWidth:58,flexGrow:1},layer:{alignItems:'center',gap:coopSpacing.xs},depth:{...coopTypography.meta,color:coopColors.gold,fontWeight:'900'},nodes:{width:'100%',flexDirection:'row',justifyContent:'space-between',gap:coopSpacing.xs},mapNode:{flex:1,minWidth:0,alignItems:'center',gap:coopSpacing.xs},locked:{opacity:.42},nodeName:{fontSize:11,lineHeight:14,color:coopColors.textSecondary,textAlign:'center'},edge:{color:coopColors.goldDim,letterSpacing:28},option:{flexDirection:'row',gap:coopSpacing.md},optionCopy:{flex:1,minWidth:0,gap:coopSpacing.xs},vote:{...coopTypography.meta,color:coopColors.cyan,fontWeight:'900'},party:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.sm},member:{width:'48%',flexGrow:1},hp:{height:12,backgroundColor:coopColors.surfaceRaised,borderWidth:1,borderColor:coopColors.goldDim},hpFill:{height:'100%',backgroundColor:coopColors.danger}});
