import {useEffect,useRef} from 'react';
import {Animated,StyleSheet,Text,View} from 'react-native';
import type {CoopRunView} from '../../core/coop-presentation';
import {validateCoopRunView} from '../../core/coop-presentation';
import type {CoopUiAssetId} from '../../core/coop-ui-contract';
import {ct,t,type Language} from '../../i18n';
import {coopColors,coopSpacing,coopTypography} from '../../theme/coop-ui-theme';
import {CoopImageSlot,ExpeditionScreenShell,FantasyPanel,RoleBadge,StateChip} from './CoopVisualKit';
import {GameButton} from '../GameButton';
import {SeasonalBossTelegraphPanel} from './SeasonalBossTelegraphPanel';
import {dungeonCombatAvatar} from '../../core/dungeon-combat-avatars';
import {DungeonCombatStage} from './DungeonCombatStage';

const roomAssets:Record<string,CoopUiAssetId>={battle:'node_battle',elite:'node_elite',event:'node_event',forge:'node_event',shrine:'node_shrine',camp:'node_camp',treasure:'node_treasure',merchant:'node_merchant',echo:'node_echo',risk:'node_risk',secret:'node_treasure',boss:'node_boss'};

function TerminalRunMoment({phase,rewardsReady,rewardsSecured,reduceMotion}:{phase:CoopRunView['phase'];rewardsReady:boolean;rewardsSecured:boolean;reduceMotion:boolean}){
  const scale=useRef(new Animated.Value(1)).current,completed=phase==='completed';
  useEffect(()=>{scale.stopAnimation();scale.setValue(1);if(reduceMotion||!completed)return;Animated.sequence([Animated.spring(scale,{toValue:1.025,damping:9,stiffness:220,mass:.65,useNativeDriver:true}),Animated.spring(scale,{toValue:1,damping:16,stiffness:200,mass:.75,useNativeDriver:true})]).start();return()=>scale.stopAnimation()},[phase,rewardsSecured,reduceMotion,scale,completed]);
  const body=completed
    ?rewardsSecured?'Your expedition rewards are secured. Return when you are ready.':rewardsReady?'Final encounter cleared. Collect the expedition reward below.':'Final encounter cleared. Your reward entitlement is being prepared.'
    :'This expedition has ended. Review any available rewards before returning.';
  return <Animated.View accessibilityLiveRegion="polite" style={[s.terminal,{transform:[{scale}]}]}>
    <View style={s.terminalHead}><View style={s.grow}><Text style={[s.terminalEyebrow,completed?s.terminalSuccess:s.terminalDanger]}>{completed?'✦ EXPEDITION CLEARED':'EXPEDITION ENDED'}</Text><Text style={s.terminalTitle}>{completed?'Victory secured':'Run complete'}</Text></View><StateChip label={completed?(rewardsSecured?'REWARDS SECURED':'VICTORY'):'ENDED'} tone={completed?'success':'danger'}/></View>
    <Text style={s.copy}>{body}</Text>
  </Animated.View>;
}

export function CoopRunOverview({language,run,onBack,onChoose,onRefresh,onClaim,busy=false,notice,rewards=[],terminalAction,reduceMotion=false}:{language:Language;run:CoopRunView;onBack:()=>void;onChoose?:(nodeId:string)=>void;onRefresh?:()=>void;onClaim?:(id:string)=>void;busy?:boolean;notice?:string;rewards?:Array<{id:string;claimed_at:string|null;reward_json:{marks?:number}}>;terminalAction?:{label:string;claimed?:boolean;completeText?:string;onPress:()=>void};reduceMotion?:boolean}){
  validateCoopRunView(run);
  const modeLabel=run.modeLabel??(run.mode==='qmode'?ct(language,'details.qmode'):ct(language,'details.live')),bossNext=run.options.some(option=>option.kind==='boss');
  const terminal=run.phase==='completed'||run.phase==='failed',unclaimedRewards=rewards.filter(reward=>!reward.claimed_at),rewardSurfaceReady=rewards.length>0||Boolean(terminalAction),rewardsSecured=terminal&&rewardSurfaceReady&&!unclaimedRewards.length&&(!terminalAction||terminalAction.claimed===true);
  return <ExpeditionScreenShell eyebrow={ct(language,'browse.resumeTitle')} title={ct(language,'browse.resume')} onBack={onBack} backLabel={ct(language,'details.backList')} banner={<View style={s.banner}><StateChip label={modeLabel} tone="selected"/><Text style={s.phase}>{run.phase.replaceAll('_',' ')}</Text></View>}>
    <FantasyPanel variant="selected"><View style={s.summary}><View style={s.grow}><Text style={s.title}>{ct(language,'details.party')}</Text><Text style={s.copy}>{ct(language,'details.partyValue')}</Text></View><StateChip label={`Lv. ${run.syncedLevel}`} tone="success"/></View></FantasyPanel>
    <Text style={s.section}>{ct(language,'details.party')}</Text>
    <View style={s.party}>{run.roleSlots.map((slot,index)=>{const avatar=dungeonCombatAvatar(slot.classId);return <FantasyPanel key={`${slot.role}-${index}`} variant={slot.ready===false?'danger':'default'} style={s.member}><RoleBadge role={slot.role} label={t(language,`coopUi.${slot.role}`)}/><Text numberOfLines={2} style={s.name}>{slot.name}</Text>{avatar?<Text style={s.className}>{avatar.label}</Text>:null}<View style={s.memberMeta}><StateChip label={slot.echo?'Echo':modeLabel} tone={slot.echo?'selected':'neutral'}/>{slot.ready!==undefined?<StateChip label={slot.ready?t(language,'coopUi.ready'):t(language,'coopUi.searching')} tone={slot.ready?'success':'warning'}/>:null}</View></FantasyPanel>})}</View>
    {run.mechanic?<FantasyPanel variant={run.mechanic.status==='critical'?'danger':run.mechanic.status==='strong'?'success':'selected'}><View style={s.mechanicHead}><View style={s.grow}><Text style={s.title}>{run.mechanic.label}</Text><Text style={s.copy}>{run.mechanic.description}</Text></View><StateChip label={`${Math.round(run.mechanic.value)}/${Math.round(run.mechanic.maxValue)}`} tone={run.mechanic.status==='critical'?'danger':run.mechanic.status==='strong'?'success':'warning'}/></View><View style={s.meterTrack}><View style={[s.meterFill,{width:`${Math.round((run.mechanic.value/run.mechanic.maxValue)*100)}%` as `${number}%`}]} /></View><Text style={s.copy}>{run.mechanic.bossEffect}</Text></FantasyPanel>:null}
    {run.objective?<FantasyPanel variant={run.objective.completed?'success':'selected'}><View style={s.mechanicHead}><View style={s.grow}><Text style={s.title}>{run.objective.label}</Text><Text style={s.copy}>{run.objective.description}</Text></View><StateChip label={`${run.objective.count}/${run.objective.maxCount}`} tone={run.objective.completed?'success':'selected'}/></View><Text style={s.copy}>{run.objective.effectText}</Text></FantasyPanel>:null}
    {run.bossMechanic?<FantasyPanel variant={run.bossMechanic.tone==='danger'?'danger':run.bossMechanic.tone==='benefit'?'success':'selected'}><View style={s.mechanicHead}><View style={s.grow}><Text style={s.title}>Final Boss Reaction · {run.bossMechanic.label}</Text><Text style={s.copy}>{run.bossMechanic.summary}</Text></View><StateChip label={run.bossMechanic.tone==='danger'?'DANGER':run.bossMechanic.tone==='benefit'?'ADVANTAGE':'MIXED'} tone={run.bossMechanic.tone==='danger'?'danger':run.bossMechanic.tone==='benefit'?'success':'warning'}/></View></FantasyPanel>:null}
    <SeasonalBossTelegraphPanel mechanic={run.bossMechanic} recap={run.bossRecap} showPlan={bossNext}/>
    {(run.phase==='resolving_node'||bossNext||Boolean(run.lastCombat))?<DungeonCombatStage run={run} boss={bossNext||run.lastCombat?.nodeId==='boss'} enemyLabel={(bossNext||run.lastCombat?.nodeId==='boss')?run.bossMechanic?.telegraph?.bossName:undefined}/>:null}
    {terminal?<TerminalRunMoment phase={run.phase} rewardsReady={rewardSurfaceReady} rewardsSecured={rewardsSecured} reduceMotion={reduceMotion}/>:null}
    <Text style={s.section}>{ct(language,'details.rooms')}</Text>
    {!!notice&&<Text accessibilityRole="alert" style={s.copy}>{notice}</Text>}
    {run.phase==='resolving_node'&&<FantasyPanel><Text style={s.copy}>Your party is resolving this room. Progress is saved online.</Text></FantasyPanel>}
    {run.options.length?run.options.map(option=><FantasyPanel key={option.nodeId}><View style={s.option}><CoopImageSlot assetId={roomAssets[option.kind]} size="node" accessibilityLabel={option.title}/><View style={s.grow}><Text style={s.title}>{option.title}</Text><Text style={s.copy}>{option.risk} · {option.reward}</Text></View>{option.votes!==undefined?<StateChip label={`${option.votes}`} tone="selected"/>:null}</View>{onChoose&&<GameButton title={run.mode==='qmode'?'Choose this room':'Vote for this room'} disabled={busy||run.phase!=='awaiting_choice'} onPress={()=>onChoose(option.nodeId)}/>}</FantasyPanel>):run.phase!=='resolving_node'?<FantasyPanel><Text style={s.copy}>{ct(language,'browse.resumeBody')}</Text></FantasyPanel>:null}
    {onRefresh&&<GameButton title="Refresh saved progress" tone="secondary" disabled={busy} onPress={onRefresh}/>}
    {rewards.map(reward=><FantasyPanel key={reward.id} variant="success">{reward.claimed_at?<Text style={s.copy}>{reward.reward_json.marks??0} Expedition Marks collected.</Text>:<GameButton title="Collect expedition reward" disabled={busy} onPress={()=>onClaim?.(reward.id)}/>}</FantasyPanel>)}
    {terminalAction?<FantasyPanel variant="success">{terminalAction.claimed?<View style={s.claimedReward}><StateChip label="SECURED" tone="success"/><Text style={s.copy}>{terminalAction.completeText??'Seasonal expedition reward collected.'}</Text></View>:<GameButton title={terminalAction.label} disabled={busy} onPress={terminalAction.onPress}/>}</FantasyPanel>:null}
    {run.rewardText?<FantasyPanel variant="success"><Text style={s.title}>{ct(language,'details.reward')}</Text><Text style={s.copy}>{run.rewardText}</Text></FantasyPanel>:null}
    {terminal?<GameButton title={rewardsSecured?'Return to dungeon list':'Leave expedition'} tone="secondary" disabled={busy} onPress={onBack}/>:null}
  </ExpeditionScreenShell>;
}

const s=StyleSheet.create({terminal:{gap:coopSpacing.sm,padding:coopSpacing.md,borderWidth:1,borderColor:coopColors.gold,backgroundColor:coopColors.surfaceRaised},terminalHead:{flexDirection:'row',alignItems:'center',gap:coopSpacing.sm},terminalEyebrow:{...coopTypography.meta,fontWeight:'900',letterSpacing:.8},terminalSuccess:{color:coopColors.success},terminalDanger:{color:coopColors.danger},terminalTitle:{...coopTypography.section,color:coopColors.text,fontWeight:'900'},claimedReward:{flexDirection:'row',alignItems:'center',gap:coopSpacing.sm},banner:{flexDirection:'row',alignItems:'center',gap:coopSpacing.sm},phase:{...coopTypography.meta,color:coopColors.textSecondary,textTransform:'capitalize',flex:1},summary:{flexDirection:'row',alignItems:'center',gap:coopSpacing.sm},grow:{flex:1,minWidth:0},section:{...coopTypography.section,color:coopColors.gold,marginTop:coopSpacing.xs},title:{...coopTypography.section,color:coopColors.text},copy:{...coopTypography.body,color:coopColors.textSecondary},party:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.sm},member:{width:'48%',flexGrow:1},name:{...coopTypography.body,color:coopColors.text,fontWeight:'800'},className:{...coopTypography.meta,color:coopColors.cyan},memberMeta:{flexDirection:'row',flexWrap:'wrap',gap:coopSpacing.xs},option:{minHeight:64,flexDirection:'row',alignItems:'center',gap:coopSpacing.md},mechanicHead:{flexDirection:'row',alignItems:'flex-start',gap:coopSpacing.sm},meterTrack:{height:6,borderRadius:999,overflow:'hidden',backgroundColor:coopColors.surfaceRaised},meterFill:{height:'100%',borderRadius:999,backgroundColor:coopColors.cyan}});
