export function renderRewardGifts({data,preview,h,attr,owner}){
 const catalog=data?.catalog??[],campaigns=data?.campaigns??[];
 return `<div class="page-head"><div><div class="eyebrow">Rewards inbox</div><h2>Send a little something.</h2><p>Deliver a gift to one account or everyone. Recipients keep it until they claim it.</p></div></div>
 ${!owner?'<div class="card">Only an Owner can send reward gifts.</div>':preview?`<div class="card"><div class="eyebrow">Review before sending</div><h3>${h(preview.title)}</h3><p>${h(preview.body)}</p><div class="stat-grid"><div class="stat"><strong>${Number(preview.recipient_count).toLocaleString()}</strong><span>accounts in this delivery</span></div></div><p>${preview.attachments.map(a=>`${h(a.name)} × ${Number(a.quantity).toLocaleString()} per account`).join(', ')}</p><p class="muted">Audience: ${h(preview.audience)}${preview.target_account_id?' · '+h(preview.target_account_id):''}. This recipient list is frozen. Sending again will not duplicate rewards.</p><p class="small muted">Reason: ${h(preview.reason)}</p>${preview.sent_at?'<span class="pill">Delivered</span><button class="btn" data-action="cancel-inbox-preview">New gift</button>':`<label>Type SEND GIFT to confirm<input id="gift-confirmation" autocomplete="off" placeholder="SEND GIFT"></label><div class="actions"><button class="btn btn-primary" data-action="send-inbox-gift" data-id="${attr(preview.id)}">Send gift</button><button class="btn" data-action="cancel-inbox-preview">Back</button></div>`}</div>`:`<form id="inbox-gift-form" class="card"><div class="form-grid"><label>Recipients<select name="audience"><option value="account">One account</option><option value="all">Everyone currently registered</option></select></label><label>Account UUID (for one account)<input name="accountId" placeholder="Account ID from Player Support"></label><label>Gift<select name="catalogId">${catalog.map(c=>`<option value="${attr(c.id)}">${h(c.kind+' · '+c.name)}</option>`).join('')}</select></label><label>Quantity per account<input name="quantity" type="number" min="1" max="100000" value="1" required></label><label>Title<input name="title" maxlength="100" minlength="3" placeholder="A gift from Veldryn" required></label><label>Message<textarea name="body" maxlength="1000" placeholder="Thank you for adventuring with us."></textarea></label><label>Internal reason<input name="reason" minlength="10" maxlength="1000" placeholder="Why are you sending this gift?" required></label></div><p class="muted">Candy is added as account charges and is used during its festival. Items stay in the inbox until there is inventory space. Preview does not send anything.</p><button type="button" class="btn btn-primary" data-action="preview-inbox-gift">Preview recipients & gift</button></form>`}
 <div class="card"><div class="card-head"><h3>Gift history</h3><span class="pill">${campaigns.length}</span></div><div class="table-wrap"><table><thead><tr><th>Gift</th><th>Recipients</th><th>Status</th><th></th></tr></thead><tbody>${campaigns.map(c=>`<tr><td><strong>${h(c.title)}</strong><div class="small muted">${c.attachments.map(a=>h(a.name)+' × '+Number(a.quantity).toLocaleString()).join(', ')}</div></td><td>${Number(c.recipient_count).toLocaleString()} · ${h(c.audience)}</td><td>${c.sent_at?'Delivered':'Draft · not sent'}</td><td>${!c.sent_at?`<button class="btn btn-sm" data-action="resume-inbox-preview" data-id="${attr(c.id)}">Review</button>`:''}</td></tr>`).join('')||'<tr><td colspan="4">No gifts yet.</td></tr>'}</tbody></table></div></div>`;
}
export function collectRewardGift(form,requestId){
 const data=Object.fromEntries(new FormData(form));
 return {...data,requestId,quantity:Number(data.quantity),accountId:data.audience==='account'?data.accountId:null};
}
