import {strict as assert} from 'node:assert';
import {launchPlayer} from '../../combat/content/launch-combat';
import {initialPersistentRunState} from '../../expeditions/node-resolution';
import {generateCoopRouteGraph} from '../../expeditions/route-generation';
import type {QModeRun} from '../qmode';
import {projectQModeRun} from '../qmode-public-projection';
const players=['Ironwarden','Wayfinder','Ravager','Stonecaller'].map((classId,index)=>({...launchPlayer(classId,25),id:`character-${index}`}));
players[1].tags=['companion:UNIT_001','body:female'];players[3].tags=['companion:UNIT_005','body:male'];
const graph=generateCoopRouteGraph('projection-secret','EXP_001','projection-run','content-v1','balance-v1');
const run:QModeRun={id:'projection-run',requestId:'projection-request',controllerAccountId:'private-controller',expeditionId:'EXP_001',tier:1,graph,currentNodeId:'entry',phase:'awaiting_choice',players,persistentState:initialPersistentRunState(players),echoSourceAccountIds:['private-a','private-b','private-c']};
const projection=projectQModeRun(run),json=JSON.stringify(projection);
assert.equal(projection.team.length,4);assert.equal(projection.team.filter(member=>member.kind==='echo').length,3);assert.equal(projection.options.length,3);
assert.equal(projection.team[1].companionId,'UNIT_001');assert.equal(projection.team[1].bodyPresentation,'female');assert.equal(projection.team[3].companionId,'UNIT_005');assert.equal(projection.team[3].bodyPresentation,'male');assert.equal(projection.team.filter(member=>member.companionId).length,2,'companion assists must stay attached to the four projected party members');
assert.equal(projection.graph.nodes.length,4,'only entry and first decision may be revealed');assert.equal(json.includes('private-controller'),false);assert.equal(json.includes('private-a'),false);assert.equal('rewardMarks' in projection,false);
run.lastResolution={nodeId:'d1-c0',result:{success:true,state:run.persistentState,summary:{kind:'combat',reason:'victory',durationMs:4200,eventDigest:'private-digest',privateSeed:'private-seed',replayCues:[{atMs:1200,type:'assist',actorId:'character-1',actorName:'Wayfinder',targetId:'enemy-1',targetName:'Rootbound Brute',abilityId:'character-1:UNIT_001:assist',abilityName:'Ironwood Hound: Hamstring Pounce',privateRoll:.42},{atMs:4200,type:'victory'}]}}};
const replayProjection=projectQModeRun(run),replayJson=JSON.stringify(replayProjection);
assert.equal(replayProjection.lastCombat?.nodeId,'d1-c0');assert.equal(replayProjection.lastCombat?.reason,'victory');assert.equal(replayProjection.lastCombat?.cues.length,2);assert.equal(replayProjection.lastCombat?.cues[0].type,'assist');
assert.equal(replayJson.includes('private-digest'),false);assert.equal(replayJson.includes('private-seed'),false);assert.equal(replayJson.includes('privateRoll'),false,'raw combat trace metadata must not reach the client');
run.phase='completed';run.rewardMarks=74;const completed=projectQModeRun(run);assert.equal(completed.settlement.status,'pending_entitlement');assert.equal(JSON.stringify(completed).includes('74'),false,'calculated reward is not a released entitlement');
assert.equal(completed.options.length,0,'a completed run offers no further commands');
run.phase='failed';const failed=projectQModeRun(run);assert.equal(failed.options.length,0);assert.equal(failed.settlement.status,'pending_entitlement');
console.log('coop phase6 public projection OK');
