import { strict as assert } from 'node:assert';
import { LiveDecisionService, MemoryDecisionRepository, progressionAfterDecision } from '../decisions';
const accounts=['a','b','c','d'],options=['A','B','C'];
function setup(id:string){const repository=new MemoryDecisionRepository();const service=new LiveDecisionService(repository,'vote-secret');const decision=service.open({id,revision:1,optionIds:options,eligibleAccountIds:accounts,openedAtMs:0,balancedFallbackOptionId:'B',tieKey:`tie-${id}`});return{service,decision};}
let x=setup('unanimous');let row=x.decision;for(const accountId of accounts)row=x.service.vote({decisionId:row.id,revision:1,accountId,optionId:'A',requestId:`r-${accountId}`,nowMs:1});assert.equal(row.status,'resolved');assert.equal(row.selectedOptionId,'A');assert.equal(row.resolutionReason,'unanimous');
x=setup('three');row=x.decision;for(const accountId of accounts.slice(0,3))row=x.service.vote({decisionId:row.id,revision:1,accountId,optionId:'A',requestId:`r-${accountId}`,nowMs:1});assert.equal(row.status,'open');row=x.service.resolveDeadline(row.id,8_000);assert.equal(row.selectedOptionId,'A');
x=setup('split');row=x.decision;for(const [index,vote] of ['A','A','B','C'].entries())row=x.service.vote({decisionId:row.id,revision:1,accountId:accounts[index],optionId:vote,requestId:`r${index}`,nowMs:1});assert.equal(row.status,'open');row=x.service.resolveDeadline(row.id,8_000);assert.equal(row.selectedOptionId,'A');
x=setup('tie');row=x.decision;for(const [index,vote] of ['A','A','B','B'].entries())row=x.service.vote({decisionId:row.id,revision:1,accountId:accounts[index],optionId:vote,requestId:`r${index}`,nowMs:1});row=x.service.resolveDeadline(row.id,8_000);assert.ok(row.selectedOptionId==='A'||row.selectedOptionId==='B');assert.equal(row.resolutionReason,'tie');
x=setup('abstain-tie');row=x.decision;for(const [index,vote] of ['A','B'].entries())row=x.service.vote({decisionId:row.id,revision:1,accountId:accounts[index],optionId:vote,requestId:`r${index}`,nowMs:1});row=x.service.resolveDeadline(row.id,8_000);assert.ok(row.selectedOptionId==='A'||row.selectedOptionId==='B');
x=setup('none');row=x.service.resolveDeadline(x.decision.id,8_000);assert.equal(row.selectedOptionId,'B');assert.equal(row.resolutionReason,'no_votes');assert.equal(progressionAfterDecision(1,row).pause,true);
x=setup('change');row=x.service.vote({decisionId:x.decision.id,revision:1,accountId:'a',optionId:'A',requestId:'first',nowMs:1});row=x.service.vote({decisionId:row.id,revision:1,accountId:'a',optionId:'B',requestId:'second',nowMs:2});assert.equal(Object.keys(row.votes).length,1);assert.equal(row.votes.a,'B');row=x.service.vote({decisionId:row.id,revision:1,accountId:'a',optionId:'B',requestId:'second',nowMs:3});assert.equal(Object.keys(row.votes).length,1);
let conflict='';try{x.service.vote({decisionId:row.id,revision:1,accountId:'a',optionId:'C',requestId:'second',nowMs:4});}catch(error){conflict=error instanceof Error?error.message:String(error);}assert.equal(conflict,'idempotency_conflict');
x=setup('late');row=x.service.resolveDeadline(x.decision.id,8_000);let late='';try{x.service.vote({decisionId:row.id,revision:1,accountId:'a',optionId:'A',requestId:'late',nowMs:8_000});}catch(error){late=error instanceof Error?error.message:String(error);}assert.equal(late,'vote_closed');assert.equal(x.service.resolveDeadline(row.id,8_001).selectedOptionId,row.selectedOptionId);
console.log('coop phase9 voting OK');
