import { strict as assert } from 'node:assert';
import { chooseBoundedCoopMatch, chooseQuickMatchExpedition, MemoryQueueRepository, readyRosterFromReservedTickets, resolvedAutoTier, type CoopQueueTicket } from '../queue-service';
const now=100_000;
const defaultClass=(id:string,role:'tank'|'damage'|'support')=>role==='tank'?'IRONWARDEN':role==='support'?'DAWNKEEPER':id.endsWith('2')||id.endsWith('4')?'RAVAGER':'WAYFINDER';
const ticket=(id:string,role:'tank'|'damage'|'support',accountId=id,classId=defaultClass(id,role)):CoopQueueTicket=>({id,accountId,characterId:`char-${id}`,role,classId,normalizedReadiness:1,loadoutId:`load-${id}`,loadoutRevision:1,loadoutSnapshotHash:`hash-${id}`,expeditionId:'EXP_001',tier:1,contentVersion:'v1',balanceVersion:'b1',serviceRegion:'eu',enqueuedAtMs:0,heartbeatExpiresAtMs:now+10_000,status:'queued'});
assert.equal(chooseBoundedCoopMatch([ticket('d1','damage'),ticket('d2','damage'),ticket('d3','damage'),ticket('d4','damage')],now),null);
assert.equal(chooseBoundedCoopMatch([ticket('t','tank'),ticket('d1','damage'),ticket('d2','damage')],now),null);
assert.equal(chooseQuickMatchExpedition([{expeditionId:'EXP_001',tank:0,damage:2,support:1,oldestQueuedAtMs:0},{expeditionId:'EXP_002',tank:0,damage:0,support:0}],['EXP_002','EXP_001'],'tank',now),'EXP_001','Quick Match should fill the role-short dungeon first');
assert.equal(chooseQuickMatchExpedition([],['EXP_004','EXP_003'],'damage',now),'EXP_004','empty pools should preserve the server-provided progression preference');
const valid=[{...ticket('t','tank'),tier:5},{...ticket('d1','damage'),tier:3},{...ticket('d2','damage'),tier:4},{...ticket('s','support'),tier:3}];
const candidate=chooseBoundedCoopMatch(valid,now);assert.ok(candidate);assert.equal(candidate!.ticketIds.length,4);assert.equal(resolvedAutoTier(valid),3,'live roster should resolve to the highest tier shared by all four players');
const duplicateDamage=[ticket('td','tank'),ticket('same-dps-1','damage','dps-a','WAYFINDER'),ticket('same-dps-2','damage','dps-b','WAYFINDER'),ticket('sd','support')];
assert.equal(chooseBoundedCoopMatch(duplicateDamage,now),null,'Live matchmaking must never pair two copies of the same Damage class');
const alternateDamage=[...duplicateDamage,ticket('different-dps','damage','dps-c','RAVAGER')];
const alternateCandidate=chooseBoundedCoopMatch(alternateDamage,now);assert.ok(alternateCandidate);assert.ok(alternateCandidate!.ticketIds.includes('different-dps'),'matcher should use another Damage class when one is available');
const repository=new MemoryQueueRepository();valid.forEach(row=>repository.add(row));
const first=repository.reserve(candidate!,'reservation-a',now,now+20_000);assert.equal(first.every(row=>row.status==='reserved'),true);
const readyRoster=readyRosterFromReservedTickets(first);assert.equal(readyRoster[0].loadoutRevision,1);assert.equal(readyRoster.every(row=>row.loadoutSnapshotHash.startsWith('hash-')),true);
let race='';try{repository.reserve(candidate!,'reservation-b',now,now+20_000);}catch(error){race=error instanceof Error?error.message:String(error);}assert.equal(race,'reservation_conflict');
repository.releaseExpired(now+20_001);assert.equal(repository.list().every(row=>row.status==='queued'),true);
const duplicateAccount=[ticket('t2','tank','same'),ticket('d3','damage','same'),ticket('d4','damage'),ticket('s2','support')];assert.equal(chooseBoundedCoopMatch(duplicateAccount,now),null);
console.log('coop phase7 matchmaking OK');
