import React from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {projectFocusLabel,projectProgressPercent,type GuildHubView} from '../core/guild-projects-v18';
export function GuildProjectsPanel({guild,onVote,onStart,onOpenProject,onClaim}:{guild:GuildHubView;onVote?:Function;onStart?:Function;onOpenProject?:Function;onClaim?:Function}){
 return <View style={s.panel}>
  <Text style={s.title}>Active Projects</Text>
  {guild.activeProjects.length===0&&<Text style={s.copy}>Your guild has no active project.</Text>}
  {guild.activeProjects.map(p=><Pressable key={p.id} onPress={()=>onOpenProject?.(p.id)} style={s.project}><View style={s.row}><View style={{flex:1}}><Text style={s.projectTitle}>{p.name}</Text><Text style={s.meta}>{projectFocusLabel(p.focus)} · Slot {p.slotIndex}</Text></View><Text style={s.percent}>{projectProgressPercent(p)}%</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,projectProgressPercent(p))}%`}]} /></View>{p.status==='completed'&&p.canClaimCompletionReward&&!p.completionRewardClaimed&&<Pressable style={s.claim} onPress={()=>onClaim?.(p.id)}><Text style={s.claimText}>Claim completion reward</Text></Pressable>}</Pressable>)}
  <Text style={s.title}>Weekly Project Board</Text><Text style={s.copy}>Members recommend a project. An authorized guild role can start one; the server may auto-start the top-voted option if leadership is inactive.</Text>
  {guild.boardCandidates.map(c=><View key={c.id} style={s.candidate}><View style={s.row}><View style={{flex:1}}><Text style={s.projectTitle}>{c.name}</Text><Text style={s.meta}>{projectFocusLabel(c.focus)} · {c.rewardTier}</Text></View><Text style={s.votes}>{c.votes} vote{c.votes===1?'':'s'}</Text></View><Text style={s.copy}>{c.description}</Text><View style={s.actions}><Pressable style={[s.secondary,c.myVote&&s.selected]} onPress={()=>onVote?.(c.id)}><Text style={s.secondaryText}>{c.myVote?'Recommended':'Recommend'}</Text></Pressable><Pressable style={s.primary} onPress={()=>onStart?.(c.id)}><Text style={s.primaryText}>Start</Text></Pressable></View></View>)}
 </View>
}
const s=StyleSheet.create({panel:{gap:9,backgroundColor:'#0f1822',borderWidth:1,borderColor:'#394d5f',borderRadius:12,padding:12},title:{color:'#c9b574',fontSize:12,fontWeight:'900',marginTop:2},copy:{color:'#9cabb5',fontSize:10,lineHeight:14},project:{backgroundColor:'#15232e',borderWidth:1,borderColor:'#304656',borderRadius:8,padding:9,gap:6},candidate:{backgroundColor:'#162530',borderWidth:1,borderColor:'#31495a',borderRadius:8,padding:9,gap:7},row:{flexDirection:'row',alignItems:'center',gap:8},projectTitle:{color:'#e7ecef',fontWeight:'900',fontSize:12},meta:{color:'#8499a7',fontSize:9},percent:{color:'#ead79d',fontWeight:'900'},votes:{color:'#d8c07e',fontWeight:'900',fontSize:10},track:{height:7,backgroundColor:'#22313d',borderRadius:4,overflow:'hidden'},fill:{height:'100%',backgroundColor:'#9b7b3c'},actions:{flexDirection:'row',gap:7},primary:{flex:1,backgroundColor:'#8f6d2d',borderWidth:1,borderColor:'#cfab55',borderRadius:7,paddingVertical:8,alignItems:'center'},primaryText:{color:'#fff1c3',fontWeight:'900',fontSize:10},secondary:{flex:1,backgroundColor:'#1b3446',borderWidth:1,borderColor:'#4f7993',borderRadius:7,paddingVertical:8,alignItems:'center'},selected:{backgroundColor:'#294331',borderColor:'#57805f'},secondaryText:{color:'#d8edf8',fontWeight:'900',fontSize:10},claim:{backgroundColor:'#294331',borderWidth:1,borderColor:'#57805f',borderRadius:6,padding:7,alignItems:'center'},claimText:{color:'#d8efdc',fontWeight:'900',fontSize:10}})
