"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const region_gameplay_v21_1 = require("./region-gameplay-v21");
const sunscar_depth_v21_1 = require("./sunscar-depth-v21");
const frostmarch_region_v21_1 = require("./frostmarch-region-v21");
const frostmarch_dungeons_v21_1 = require("./frostmarch-dungeons-v21");
const frostmarch_gameplay_v21_1 = require("./frostmarch-gameplay-v21");
const region_content_publisher_v21_1 = require("./region-content-publisher-v21");
const region_content_admin_v21_1 = require("./region-content-admin-v21");
const eq = (a, b, m) => { if (a !== b)
    throw new Error(`${m}: ${String(a)} !== ${String(b)}`); };
const ok = (v, m) => { if (!v)
    throw new Error(m); };
const sunErr = (0, region_gameplay_v21_1.validateRegionalGameplayV21)({ sideQuests: sunscar_depth_v21_1.SUNSCAR_SIDE_QUESTS_V21, activities: sunscar_depth_v21_1.SUNSCAR_ACTIVITIES_V21, achievements: sunscar_depth_v21_1.SUNSCAR_ACHIEVEMENTS_V21, collectionBooks: sunscar_depth_v21_1.SUNSCAR_COLLECTION_BOOKS_V21, weatherRules: sunscar_depth_v21_1.SUNSCAR_WEATHER_RULES_V21, contracts: sunscar_depth_v21_1.SUNSCAR_CONTRACTS_V21, bossMasteries: sunscar_depth_v21_1.SUNSCAR_BOSS_MASTERY_V21 });
eq(sunErr.length, 0, 'sun gameplay validation');
const froErr = (0, region_gameplay_v21_1.validateRegionalGameplayV21)({ sideQuests: frostmarch_gameplay_v21_1.FROSTMARCH_SIDE_QUESTS_V21, activities: frostmarch_gameplay_v21_1.FROSTMARCH_ACTIVITIES_V21, achievements: frostmarch_gameplay_v21_1.FROSTMARCH_ACHIEVEMENTS_V21, collectionBooks: frostmarch_gameplay_v21_1.FROSTMARCH_COLLECTION_BOOKS_V21, weatherRules: frostmarch_gameplay_v21_1.FROSTMARCH_WEATHER_RULES_V21, contracts: frostmarch_gameplay_v21_1.FROSTMARCH_CONTRACTS_V21, bossMasteries: frostmarch_gameplay_v21_1.FROSTMARCH_BOSS_MASTERY_V21 });
eq(froErr.length, 0, 'frost gameplay validation');
eq(frostmarch_region_v21_1.FROSTMARCH_ZONES_V21.length, 5, 'zones');
eq(frostmarch_region_v21_1.FROSTMARCH_ENEMIES_V21.length, 16, 'monsters');
eq(frostmarch_region_v21_1.FROSTMARCH_BOSSES_V21.length, 4, 'bosses');
eq(frostmarch_region_v21_1.FROSTMARCH_RESOURCES_V21.length, 10, 'resources');
eq(frostmarch_region_v21_1.FROSTMARCH_QUESTLINE_V21.length, 10, 'quests');
eq(frostmarch_region_v21_1.FROSTMARCH_COLLECTIBLES_V21.length, 9, 'collectibles');
eq(frostmarch_dungeons_v21_1.FROSTMARCH_DUNGEONS_V21.length, 3, 'dungeons');
eq((0, frostmarch_dungeons_v21_1.validateFrostmarchDungeonsV21)().length, 0, 'dungeon validation');
eq(frostmarch_gameplay_v21_1.FROSTMARCH_ACTIVITIES_V21.length, 5, 'activities');
ok(frostmarch_gameplay_v21_1.FROSTMARCH_ACTIVITIES_V21.every(v => v.contributionEligible), 'activities are contribution eligible');
eq(frostmarch_dungeons_v21_1.FROSTMARCH_DUNGEONS_V21.map(v => v.id).join(','), 'COP_007,COP_008,COP_009', 'canonical dungeon ids');
ok(frostmarch_region_v21_1.FROSTMARCH_EQUIPMENT_POLICY_V21.equipmentSetsAuthored === false, 'frost equipment must remain deferred');
ok(frostmarch_region_v21_1.FROSTMARCH_EQUIPMENT_POLICY_V21.regionalWeaponsAuthored === false, 'frost weapons must remain deferred');
const sun = (0, region_content_publisher_v21_1.buildSunscarRegionContentBundleV21)();
const sun2 = (0, region_content_publisher_v21_1.buildSunscarRegionContentBundleV21)();
const fro = (0, region_content_publisher_v21_1.buildFrostmarchRegionContentBundleV21)();
eq(sun.contentHash, sun2.contentHash, 'deterministic hash');
eq(sun.schemaVersion, 2, 'sun schema');
eq(fro.schemaVersion, 2, 'frost schema');
ok(fro.records.some(v => v.recordType === 'weather_rule'), 'weather records');
ok(fro.records.some(v => v.recordType === 'boss_mastery'), 'mastery records');
ok(fro.records.every(v => !JSON.stringify(v).toLowerCase().includes('player market')), 'no market content');
eq(fro.records.filter(v => v.recordType === 'activity').length, 5, 'activity records');
eq(fro.records.filter(v => v.recordType === 'live_dungeon').map(v => v.recordId).join(','), 'COP_007,COP_008,COP_009', 'dungeon records');
(async () => {
    let active = 'sunscar-v20.0.0';
    const published = 'frostmarch-v21.0.0';
    const activationStore = { getActive: async () => active, activate: async (_regionId, version) => { active = version; }, isPublishedForRegion: async (_regionId, version) => version === published };
    const activated = await (0, region_content_admin_v21_1.activateRegionContentVersionV21)(activationStore, { regionId: 'REG_003', contentVersion: published });
    eq(activated.previous, 'sunscar-v20.0.0', 'activation previous version');
    eq(activated.active, published, 'activation active version');
    console.log('v21 region tests passed');
})();
