import React from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {RegionDungeonCardV21,RegionProgressV21,RegionWeatherV21,RegionZoneCardV21} from '../core/region-content-v21';
import {completionPercentV21,formatRegionTimerV21,nextRegionalGoalV21} from '../core/region-content-v21';
export function FrostmarchRegionPanel({zones,progress,weather,dungeons,onZone,onDungeon}:{zones:readonly RegionZoneCardV21[];progress:RegionProgressV21;weather?:RegionWeatherV21;dungeons:readonly RegionDungeonCardV21[];onZone?:(id:string)=>void;onDungeon?:(id:string)=>void}){
 const pct=completionPercentV21(progress);
 return <ScrollView contentContainerStyle={s.wrap}><View style={s.hero}><Text style={s.eyebrow}>REGION III · LEVEL 45–70</Text><Text style={s.title}>Frostmarch</Text><Text style={s.copy}>Thawgate, false trails, memories under Shiverlake, the Hollow Choir and Wyrmspine lead toward the Frost Wyrm.</Text><Text style={s.note}>Regional armor/weapons remain deferred until the richer-stat equipment rework.</Text><View style={s.progressRow}><Text style={s.progress}>{pct}% REGION</Text><Text style={s.goal}>{nextRegionalGoalV21(progress)}</Text></View>{weather&&<View style={s.weather}><Text style={s.weatherTitle}>{weather.name} · {formatRegionTimerV21(weather.endsInSeconds)}</Text><Text style={s.weatherCopy}>{weather.summary}</Text></View>}</View>
 {zones.map(z=><Pressable key={z.id} disabled={z.locked} onPress={()=>onZone?.(z.id)} style={[s.card,z.locked&&s.locked]}><View style={{flex:1}}><Text style={s.cardTitle}>{z.name}</Text><Text style={s.level}>{z.levelRange}</Text><Text style={s.identity}>{z.identity}</Text><Text style={s.tags}>{z.activities.join(' · ')}</Text></View><Text style={s.arrow}>{z.locked?'LOCKED':'›'}</Text></Pressable>)}
 <Text style={s.section}>CO-OP</Text>{dungeons.map(d=><Pressable key={d.id} disabled={d.locked} onPress={()=>onDungeon?.(d.id)} style={[s.dungeon,d.locked&&s.locked]}><View><Text style={s.cardTitle}>{d.name}</Text><Text style={s.level}>Lv {d.minLevel}+ · Live + Q-Mode</Text></View><Text style={s.arrow}>{d.locked?'LOCKED':'›'}</Text></Pressable>)}</ScrollView>;
}
const s=StyleSheet.create({wrap:{padding:12,gap:8},hero:{padding:14,borderRadius:11,borderWidth:1,borderColor:'#5d7890',backgroundColor:'#151d26'},eyebrow:{fontSize:8,fontWeight:'900',color:'#8fc4dd',letterSpacing:1},title:{fontSize:24,fontWeight:'900',color:'#e6f5ff'},copy:{fontSize:11,lineHeight:16,color:'#b9c9d5',marginTop:5},note:{fontSize:9.5,lineHeight:14,color:'#92b4c7',marginTop:7},progressRow:{marginTop:10},progress:{fontSize:10,fontWeight:'900',color:'#d9f3ff'},goal:{fontSize:9,color:'#93aebe',marginTop:2},weather:{marginTop:9,padding:9,borderRadius:8,borderWidth:1,borderColor:'#40596e',backgroundColor:'#111820'},weatherTitle:{fontSize:10,fontWeight:'900',color:'#c6e9fb'},weatherCopy:{fontSize:9,color:'#9fb5c1',marginTop:2},card:{flexDirection:'row',alignItems:'center',padding:12,borderRadius:9,borderWidth:1,borderColor:'#425566',backgroundColor:'#171d23'},dungeon:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:12,borderRadius:9,borderWidth:1,borderColor:'#52697c',backgroundColor:'#18222b'},locked:{opacity:.45},cardTitle:{fontSize:14,fontWeight:'900',color:'#e4f3fb'},level:{fontSize:9,fontWeight:'900',color:'#8fc4dd',marginTop:1},identity:{fontSize:10,lineHeight:14,color:'#a8bbc7',marginTop:4},tags:{fontSize:9,color:'#7f9cab',marginTop:5},arrow:{fontSize:18,fontWeight:'900',color:'#9bd1e7'},section:{fontSize:9,fontWeight:'900',color:'#91b9cd',letterSpacing:1,marginTop:7}});
