"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_assert_1 = require("node:assert");
const regional_crises_1 = require("./regional-crises");
const world_bosses_1 = require("./world-bosses");
const crisis = regional_crises_1.REGIONAL_CRISIS_TEMPLATE_POOL[0];
const scale = (0, regional_crises_1.deriveRegionalCrisisScale)({ eligibleActiveAccounts7d: 1000, durationHours: 48 });
node_assert_1.strict.ok(scale.targetPoints >= 6000);
node_assert_1.strict.equal(scale.expectedParticipationFraction, 0.45);
const eval1 = (0, regional_crises_1.evaluateRegionalCrisis)(crisis, { targetPoints: 10000, creditedPoints: 6500, combatPoints: 3000, skillingPoints: 3000 });
node_assert_1.strict.equal(eval1.secured, false);
node_assert_1.strict.ok(eval1.reachedStageIds.includes('turning_point'));
const eval2 = (0, regional_crises_1.evaluateRegionalCrisis)(crisis, { targetPoints: 10000, creditedPoints: 10000, combatPoints: 3000, skillingPoints: 3000 });
node_assert_1.strict.equal(eval2.secured, true);
const event = { sourceEventId: 'evt-1', accountId: 'a', occurredAtMs: 1, dateKey: '2026-09-14', profile: { id: 'crisis.test', category: 'combat', challenge: 'elite', expectedSecondsPerUnit: 60, difficultyMultiplier: 1, offline: false }, units: 10, activityKind: 'combat', contentId: 'enemy', regionId: 'rift' };
const score = (0, regional_crises_1.scoreRegionalCrisisContribution)(event, crisis, 0);
node_assert_1.strict.equal(score.eligible, true);
node_assert_1.strict.ok(score.creditedPoints > 0);
node_assert_1.strict.ok(score.creditedPoints <= crisis.contributionRules.dailyAccountCreditCap);
const boss = world_bosses_1.WORLD_BOSS_TEMPLATE_POOL[0];
const bossScale = (0, world_bosses_1.deriveWorldBossScale)({ eligibleCombatAccounts7d: 1000, medianImpactPerAttempt: 1200 });
node_assert_1.strict.ok(bossScale.maxHp >= 50000);
node_assert_1.strict.equal((0, world_bosses_1.phaseForHp)(boss, 100000, 100000).id, 'phase_1');
node_assert_1.strict.equal((0, world_bosses_1.phaseForHp)(boss, 60000, 100000).id, 'phase_2');
node_assert_1.strict.equal((0, world_bosses_1.phaseForHp)(boss, 20000, 100000).id, 'phase_3');
const damageImpact = (0, world_bosses_1.computeWorldBossImpact)(boss, { encounterId: 'e', accountId: 'a', characterId: 'c', roleProfile: 'damage', durationSeconds: 90, directDamage: 1000, damagePrevented: 0, effectiveHealing: 0, utilityUptimeSeconds: 0, survived: true, defeatedPlayer: false });
const tankImpact = (0, world_bosses_1.computeWorldBossImpact)(boss, { encounterId: 'e2', accountId: 'b', characterId: 'c2', roleProfile: 'tank', durationSeconds: 90, directDamage: 650, damagePrevented: 800, effectiveHealing: 0, utilityUptimeSeconds: 10, survived: true, defeatedPlayer: false });
const supportImpact = (0, world_bosses_1.computeWorldBossImpact)(boss, { encounterId: 'e3', accountId: 'c', characterId: 'c3', roleProfile: 'support', durationSeconds: 90, directDamage: 550, damagePrevented: 100, effectiveHealing: 650, utilityUptimeSeconds: 30, survived: true, defeatedPlayer: false });
node_assert_1.strict.ok(damageImpact.raidImpact > 0 && tankImpact.raidImpact > 0 && supportImpact.raidImpact > 0);
node_assert_1.strict.ok(tankImpact.raidImpact >= Math.round(damageImpact.raidImpact * 0.65));
node_assert_1.strict.ok(supportImpact.raidImpact >= Math.round(damageImpact.raidImpact * 0.65));
node_assert_1.strict.deepEqual((0, world_bosses_1.applyWorldBossDamage)(1000, 250), { previousHp: 1000, remainingHp: 750, requestedDamage: 250, appliedDamage: 250, defeated: false });
node_assert_1.strict.equal((0, world_bosses_1.applyWorldBossDamage)(100, 250).appliedDamage, 100);
node_assert_1.strict.equal((0, world_bosses_1.applyWorldBossDamage)(100, 250).remainingHp, 0);
node_assert_1.strict.equal((0, world_bosses_1.canStartScoredBossAttempt)({ state: 'active', attemptsToday: 3, definition: boss, nowMs: 1000, endsAtMs: 2000 }).allowed, true);
node_assert_1.strict.equal((0, world_bosses_1.canStartScoredBossAttempt)({ state: 'active', attemptsToday: 4, definition: boss, nowMs: 1000, endsAtMs: 2000 }).allowed, false);
node_assert_1.strict.equal((0, world_bosses_1.canStartScoredBossAttempt)({ state: 'defeated', attemptsToday: 4, validAttemptsTotal: 0, echoAttemptsTotal: 0, definition: boss, nowMs: 1000, endsAtMs: 100000, defeatedAtMs: 500 }).echoOnly, true);
node_assert_1.strict.equal((0, world_bosses_1.canStartScoredBossAttempt)({ state: 'defeated', attemptsToday: 0, validAttemptsTotal: 1, echoAttemptsTotal: 0, definition: boss, nowMs: 1000, endsAtMs: 100000, defeatedAtMs: 500 }).allowed, false);
node_assert_1.strict.equal((0, world_bosses_1.canStartScoredBossAttempt)({ state: 'defeated', attemptsToday: 0, validAttemptsTotal: 0, echoAttemptsTotal: 1, definition: boss, nowMs: 1000, endsAtMs: 100000, defeatedAtMs: 500 }).allowed, false);
console.log('v19 shared-world balance tests passed');
const world_boss_ranking_1 = require("./world-boss-ranking");
const shared_world_rewards_1 = require("./shared-world-rewards");
const shared_world_finalization_1 = require("./shared-world-finalization");
const crisis_world_boss_chain_1 = require("./crisis-world-boss-chain");
const ranks = (0, world_boss_ranking_1.rankWorldBossCandidates)([
    { accountId: 'b', raidImpact: 1000, appliedGlobalDamage: 900, validAttempts: 2, bestAttemptImpact: 600, lastScoredAttemptAtMs: 20 },
    { accountId: 'a', raidImpact: 1000, appliedGlobalDamage: 900, validAttempts: 2, bestAttemptImpact: 600, lastScoredAttemptAtMs: 10 },
    { accountId: 'c', raidImpact: 900, appliedGlobalDamage: 900, validAttempts: 1, bestAttemptImpact: 900, lastScoredAttemptAtMs: 5 },
]);
node_assert_1.strict.equal(ranks[0].accountId, 'a');
node_assert_1.strict.equal(ranks[0].finalRank, 1);
node_assert_1.strict.equal((0, world_boss_ranking_1.worldBossPrestigeTier)(1, 1000), 'top10');
node_assert_1.strict.equal((0, world_boss_ranking_1.worldBossPrestigeTier)(80, 1000), 'top100');
const fin = (0, shared_world_finalization_1.finalizeWorldBossRanks)({ nowMs: 700000, endsAtMs: 999999, defeatedAtMs: 0, inFlightScoredAttempts: 0, definition: boss, rankCandidates: ranks });
node_assert_1.strict.equal(fin.ready, true);
node_assert_1.strict.equal(fin.finalRanks.length, 3);
const crisisRewards = (0, shared_world_rewards_1.crisisRewardIntents)({ state: 'secured', totalPersonalPoints: 800, claimedRewardKeys: [], definition: crisis });
node_assert_1.strict.ok(crisisRewards.some(x => x.rewardKey === 'participation'));
node_assert_1.strict.ok(crisisRewards.some(x => x.rewardKey === 'success'));
const bossRewards = (0, shared_world_rewards_1.worldBossRewardIntents)({ state: 'defeated', validAttempts: 1, echoAttempts: 0, scoredRaidImpact: 2100, finalRank: 5, qualifyingPopulation: 500, claimedRewardKeys: [], definition: boss });
node_assert_1.strict.ok(bossRewards.some(x => x.rewardKey === 'victory'));
node_assert_1.strict.ok(bossRewards.some(x => x.rewardKey === 'prestige'));
node_assert_1.strict.equal((0, crisis_world_boss_chain_1.bossUnlockForReachedStages)('crisis-1', crisis, ['response', 'turning_point', 'secured'])?.worldBossTemplateId, 'world_boss_rift_colossus');
console.log('v19 finalization/reward/ranking tests passed');
