import type {Language} from './languages';
import {COMPANION_TOUR_STEPS} from '../core/companion-tutorial';

const steps:Partial<Record<Language,readonly (readonly [string,string,string,string])[]>>={
 de:[
  ['Lerne deine Begleiter kennen','Begleiter sind dauerhafte Rekruten mit Schaden-, Tank- oder Unterstützungsrollen. Öffne ein Porträt, um Rekrutierung und Kampfrolle zu sehen.','Rüste einen passenden Begleiter als Kampfhelfer aus. Für Teams brauchst du alle drei Rollen.','Kader öffnen'],
  ['Stärke dein Team','Training erhöht Begleiterlevel. Aufstieg erhöht die Levelgrenze; Bindung bringt zusätzliche Belohnungen und Fortschritt.','Unter Bindung, Fähigkeiten und Materialien findest du Meilensteine, Techniken und Materialquellen.','Training öffnen'],
  ['Ein Zuhause für deine Begleiter','Hole tägliche Trainings-EP und wöchentliche Essenz ab. Einrichtungen verbessern Training, Bindung und Expeditionskapazität.','Unterkünfte erhöhen die Levelgrenze einzelner Begleiter. Prüfe vor Upgrades Kosten und Materialquellen.','Zuflucht öffnen'],
  ['Ein ausgewogenes Team','Prüfungen brauchen drei Begleiter: Tank, Schaden und Unterstützung. Erklimme Etagen, prüfe Bosse und hole Herausforderungsbelohnungen ab.','Die Saison wechselt monatlich. Prüfe Regeln, Team und Kontrollpunkte vor dem Start.','Prüfungen öffnen'],
  ['Schicke Begleiter auf Reisen','Wähle einen Auftrag und erfülle die Teamanforderungen. Expeditionen verbrauchen nahrungsbasierte Ausdauer und binden Begleiter bis zur Rückkehr.','Prüfe Dauer, Belohnungen und Verfügbarkeit. Hole abgeschlossene Aufträge ab; Expeditionsgehege schaffen Kapazität.','Expeditionen öffnen'],
  ['Plane deinen nächsten Rekruten','Der Kodex zeigt Entdeckungen, Sammlung und Meilensteinbelohnungen. Rekrutierungsanforderungen helfen bei der Planung.','Bereit! Rekrutiere einen verfügbaren Begleiter, rüste einen passenden Helfer aus und baue dein Dreierteam auf.','Kodex öffnen'],
 ],
 es:[
  ['Conoce a tus compañeros','Los compañeros son reclutas permanentes de Daño, Tanque o Apoyo. Abre un retrato para ver sus requisitos y función de combate.','Equipa un compañero compatible para ayudar a tu personaje. Reúne las tres funciones para formar equipos.','Abrir plantilla'],
  ['Fortalece tu equipo','El entrenamiento sube el nivel. La ascensión aumenta el límite de nivel; el vínculo aporta recompensas y progresión.','Abre Vínculo, Habilidades o Materiales para consultar hitos, técnicas y fuentes de materiales.','Abrir entrenamiento'],
  ['Un hogar para tu plantilla','Recoge EXP de entrenamiento diaria y Esencia semanal. Las instalaciones mejoran entrenamiento, vínculo y capacidad de expedición.','El alojamiento aumenta el límite de cada compañero. Revisa costes y fuentes antes de mejorar.','Abrir santuario'],
  ['Forma un equipo equilibrado','Las pruebas requieren tres compañeros: Tanque, Daño y Apoyo. Sube pisos, examina jefes y reclama recompensas.','La temporada cambia cada mes. Revisa reglas, preparación y puntos de control antes de empezar.','Abrir pruebas'],
  ['Envía compañeros a misiones','Elige una misión y cumple sus requisitos. Las expediciones consumen aguante basado en comida y ocupan a los compañeros hasta su regreso.','Revisa duración, recompensas y disponibilidad. Reclama misiones completadas; amplía capacidad con corrales de expedición.','Abrir expediciones'],
  ['Planea tu próximo recluta','El códice registra descubrimientos, colección y recompensas por hitos. Los requisitos indican tu próximo objetivo.','¡Listo! Recluta un compañero disponible, equipa un ayudante compatible y forma tu equipo de tres funciones.','Abrir códice'],
 ],
 nl:[
  ['Ontmoet je metgezellen','Metgezellen zijn permanente rekruten met de rol Schade, Tank of Ondersteuning. Open een portret voor de wervingsvereisten en gevechtsrol.','Rust een passende metgezel uit om je personage te helpen. Verzamel alle drie de rollen voor teamactiviteiten.','Team openen'],
  ['Maak je team sterker','Training verhoogt metgezelniveaus. Ascensie verhoogt de niveaulimiet; Band levert beloningen en voortgang op.','Open Band, Vaardigheden of Materialen voor mijlpalen, technieken en bronnen van upgradematerialen.','Training openen'],
  ['Een thuis voor je team','Haal dagelijks trainings-XP en wekelijks Essentie op. Faciliteiten verbeteren training, Band en expeditiecapaciteit.','Huisvesting verhoogt de niveaulimiet per metgezel. Bekijk kosten en materiaalbronnen voordat je verbetert.','Heiligdom openen'],
  ['Stel een evenwichtig team samen','Beproevingen vereisen drie metgezellen: Tank, Schade en Ondersteuning. Beklim verdiepingen, bekijk bazen en claim beloningen.','Het seizoen wisselt maandelijks. Controleer regels, je team en controlepunten voordat je begint.','Beproevingen openen'],
  ['Stuur metgezellen op pad','Kies een opdracht en voldoe aan de teamvereisten. Expedities gebruiken voedselgebaseerd uithoudingsvermogen en houden metgezellen bezet tot hun terugkeer.','Bekijk duur, beloningen en beschikbaarheid. Claim voltooide opdrachten; bouw expeditieverblijven voor capaciteit.','Expedities openen'],
  ['Plan je volgende rekruut','De codex volgt ontdekkingen, je verzameling en mijlpaalbeloningen. Wervingsvereisten laten zien waar je naartoe werkt.','Je bent klaar! Werf een beschikbare metgezel, rust een passende helper uit en bouw je team met drie rollen.','Codex openen'],
 ],
 it:[
  ['Conosci i tuoi compagni','I compagni sono reclute permanenti con ruoli Danno, Tank o Supporto. Apri un ritratto per vedere requisiti e ruolo in battaglia.','Equipaggia un compagno compatibile come aiutante. Riunisci tutti e tre i ruoli per le attività di squadra.','Apri squadra'],
  ['Rafforza la squadra','L’allenamento aumenta il livello. L’ascensione alza il limite; il legame offre ricompense e progressione.','Apri Legame, Abilità o Materiali per consultare traguardi, tecniche e fonti dei materiali.','Apri allenamento'],
  ['Una casa per i compagni','Raccogli PE di allenamento giornalieri ed Essenza settimanale. Le strutture migliorano allenamento, legame e capacità delle spedizioni.','Gli alloggi aumentano il limite di livello individuale. Controlla costi e fonti prima di migliorare.','Apri santuario'],
  ['Una squadra equilibrata','Le prove richiedono tre compagni: Tank, Danno e Supporto. Sali i piani, esamina i boss e riscuoti le ricompense.','La stagione cambia ogni mese. Controlla regole, squadra e punti di controllo prima di iniziare.','Apri prove'],
  ['Invia compagni in missione','Scegli una missione e soddisfa i requisiti. Le spedizioni usano vigore basato sul cibo e impegnano i compagni fino al ritorno.','Controlla durata, ricompense e disponibilità. Riscuoti le missioni concluse; amplia la capacità con recinti per spedizioni.','Apri spedizioni'],
  ['Pianifica la prossima recluta','Il codice registra scoperte, collezione e ricompense dei traguardi. I requisiti di reclutamento indicano i prossimi obiettivi.','Sei pronto! Recluta un compagno disponibile, equipaggia un aiutante compatibile e forma una squadra con tre ruoli.','Apri codice'],
 ],
 fr:[
  ['Découvrez vos compagnons','Les compagnons sont des recrues permanentes de rôle Dégâts, Tank ou Soutien. Ouvrez un portrait pour voir les conditions et le rôle au combat.','Équipez un compagnon compatible pour aider votre personnage. Réunissez les trois rôles pour les équipes.','Ouvrir l’effectif'],
  ['Renforcez votre équipe','L’entraînement augmente le niveau. L’ascension relève la limite ; le lien apporte récompenses et progression.','Ouvrez Lien, Compétences ou Matériaux pour consulter paliers, techniques et sources de matériaux.','Ouvrir l’entraînement'],
  ['Un foyer pour vos compagnons','Récupérez l’EXP quotidienne et l’Essence hebdomadaire. Les installations améliorent entraînement, lien et capacité d’expédition.','Les logements augmentent la limite de niveau individuelle. Vérifiez les coûts et les sources avant toute amélioration.','Ouvrir le sanctuaire'],
  ['Une équipe équilibrée','Les épreuves exigent trois compagnons : Tank, Dégâts et Soutien. Gravissez les étages, examinez les boss et réclamez les récompenses.','La saison change chaque mois. Vérifiez règles, équipe et points de contrôle avant de commencer.','Ouvrir les épreuves'],
  ['Envoyez des compagnons en mission','Choisissez une mission et respectez ses conditions. Les expéditions utilisent de l’endurance issue de nourriture et occupent les compagnons jusqu’au retour.','Vérifiez durée, récompenses et disponibilité. Réclamez les missions terminées ; construisez des enclos pour augmenter la capacité.','Ouvrir les expéditions'],
  ['Préparez votre prochaine recrue','Le codex suit découvertes, collection et récompenses de paliers. Les conditions de recrutement indiquent vos prochains objectifs.','Vous êtes prêt ! Recrutez un compagnon disponible, équipez un allié compatible et formez une équipe de trois rôles.','Ouvrir le codex'],
 ],
};
const ui:Record<string,readonly string[]>={
 'Next: {area}':['Weiter: {area}','Siguiente: {area}','Volgende: {area}','Avanti: {area}','Suivant : {area}'],
 'Previous tip':['Voriger Tipp','Consejo anterior','Vorige tip','Consiglio precedente','Conseil précédent'],
 'Finish guide':['Guide beenden','Terminar guía','Gids afronden','Termina guida','Terminer le guide'],
 'More detail':['Mehr Details','Más detalles','Meer uitleg','Altri dettagli','Plus de détails'],
 'Less detail':['Weniger Details','Menos detalles','Minder uitleg','Meno dettagli','Moins de détails'],
 'SCREEN PREVIEW':['BILDSCHIRMVORSCHAU','VISTA PREVIA','SCHERMVOORBEELD','ANTEPRIMA','APERÇU'],
 'Scroll to look around. Buttons are disabled during the guide.':['Scrolle zum Erkunden. Tasten sind während des Guides deaktiviert.','Desplázate para explorar. Los botones están desactivados durante la guía.','Scrol om rond te kijken. Knoppen zijn tijdens de gids uitgeschakeld.','Scorri per esplorare. I pulsanti sono disattivati durante la guida.','Faites défiler pour explorer. Les boutons sont désactivés pendant le guide.'],
 'Finish to open your roster and equip a helper.':['Beende den Guide, um deinen Kader zu öffnen und einen Helfer auszurüsten.','Termina para abrir tu plantilla y equipar un ayudante.','Rond af om je team te openen en een helper uit te rusten.','Termina per aprire la squadra ed equipaggiare un aiutante.','Terminez pour ouvrir votre effectif et équiper un allié.'],
 '{name} is already equipped and helps in combat.':['{name} ist bereits ausgerüstet und hilft im Kampf.','{name} ya está equipado y ayuda en combate.','{name} is al uitgerust en helpt in gevechten.','{name} è già equipaggiato e aiuta in battaglia.','{name} est déjà équipé et vous aide au combat.'],
 '{name} has joined you. After this guide, open its portrait and choose Equip companion.':['{name} ist dir beigetreten. Öffne nach dem Guide das Porträt und wähle Begleiter ausrüsten.','{name} se ha unido. Tras la guía, abre su retrato y elige Equipar compañero.','{name} heeft zich aangesloten. Open na de gids het portret en kies Metgezel uitrusten.','{name} si è unito a te. Dopo la guida, apri il ritratto e scegli Equipaggia compagno.','{name} vous a rejoint. Après le guide, ouvrez son portrait et choisissez Équiper le compagnon.'],
 'Your companion shares your character’s role. Recruit a different role to equip a helper.':['Dein Begleiter hat dieselbe Rolle wie dein Charakter. Rekrutiere eine andere Rolle als Helfer.','Tu compañero tiene el mismo rol que tu personaje. Recluta otro rol para equipar un ayudante.','Je metgezel heeft dezelfde rol als je personage. Werf een andere rol om een helper uit te rusten.','Il compagno ha il tuo stesso ruolo. Recluta un ruolo diverso per equipaggiare un aiutante.','Votre compagnon a le même rôle que vous. Recrutez un rôle différent pour équiper un allié.'],
 'Companions join automatically when you meet their requirements. Check the Codex for your next recruit.':['Begleiter treten automatisch bei erfüllten Anforderungen bei. Suche im Kodex nach deinem nächsten Rekruten.','Los compañeros se unen automáticamente al cumplir sus requisitos. Consulta el códice para tu próximo recluta.','Metgezellen sluiten zich automatisch aan zodra je aan hun eisen voldoet. Bekijk de codex voor je volgende rekruut.','I compagni si uniscono automaticamente quando soddisfi i requisiti. Consulta il codice per la prossima recluta.','Les compagnons vous rejoignent automatiquement quand leurs conditions sont remplies. Consultez le codex pour la prochaine recrue.'],
 'No Essence yet? Leave training for later. You do not need to spend anything during this guide.':['Noch keine Essenz? Trainiere später. Während dieses Guides musst du nichts ausgeben.','¿Aún sin Esencia? Deja el entrenamiento de pago para después. No necesitas gastar nada durante esta guía.','Nog geen Essentie? Bewaar betaalde training voor later. Tijdens deze gids hoef je niets uit te geven.','Non hai Essenza? Rimanda l’allenamento a pagamento. Non devi spendere nulla durante questa guida.','Pas encore d’Essence ? Gardez l’entraînement payant pour plus tard. Ce guide ne demande aucune dépense.'],
 'Check the Gold and Essence costs before training. Upgrades are optional during this guide.':['Prüfe vor dem Training Gold- und Essenzkosten. Upgrades sind während des Guides optional.','Revisa los costes de Oro y Esencia antes de entrenar. Las mejoras son opcionales durante la guía.','Bekijk de kosten in Goud en Essentie voor je traint. Upgrades zijn optioneel tijdens de gids.','Controlla i costi in Oro ed Essenza prima di allenare. Gli upgrade sono facoltativi durante la guida.','Vérifiez les coûts en Or et Essence avant l’entraînement. Les améliorations sont facultatives pendant le guide.'],
 'Your reward facilities are not built yet. Build them before expecting daily XP or weekly Essence.':['Deine Belohnungseinrichtungen sind noch nicht gebaut. Baue sie für tägliche EP oder wöchentliche Essenz.','Aún no has construido instalaciones de recompensas. Constrúyelas para obtener EXP diaria o Esencia semanal.','Je beloningsfaciliteiten zijn nog niet gebouwd. Bouw ze voor dagelijkse XP of wekelijkse Essentie.','Le strutture ricompense non sono ancora costruite. Costruiscile per PE giornalieri o Essenza settimanale.','Vos installations de récompenses ne sont pas construites. Construisez-les pour obtenir EXP quotidienne ou Essence hebdomadaire.'],
 'Only built facilities generate rewards. Wait for their timers, then claim here.':['Nur gebaute Einrichtungen erzeugen Belohnungen. Warte auf ihre Timer und hole sie hier ab.','Solo las instalaciones construidas generan recompensas. Espera sus temporizadores y recógelas aquí.','Alleen gebouwde faciliteiten leveren beloningen op. Wacht op de timers en claim ze hier.','Solo le strutture costruite generano ricompense. Attendi i timer e riscuoti qui.','Seules les installations construites produisent des récompenses. Attendez leurs délais, puis réclamez ici.'],
 'You do not own all three roles yet. Keep recruiting; Trials can wait.':['Du besitzt noch nicht alle drei Rollen. Rekrutiere weiter; Prüfungen können warten.','Aún no tienes los tres roles. Sigue reclutando; las pruebas pueden esperar.','Je hebt nog niet alle drie de rollen. Blijf rekruteren; beproevingen kunnen wachten.','Non possiedi ancora tutti e tre i ruoli. Continua a reclutare; le prove possono aspettare.','Vous ne possédez pas encore les trois rôles. Continuez à recruter ; les épreuves peuvent attendre.'],
 'You own all three roles. Check companion availability and recommended power before starting.':['Du besitzt alle drei Rollen. Prüfe vor dem Start Verfügbarkeit und empfohlene Stärke.','Tienes los tres roles. Revisa disponibilidad y poder recomendado antes de empezar.','Je hebt alle drie de rollen. Bekijk beschikbaarheid en aanbevolen kracht voordat je begint.','Possiedi tutti e tre i ruoli. Controlla disponibilità e potenza consigliata prima di iniziare.','Vous possédez les trois rôles. Vérifiez disponibilité et puissance recommandée avant de commencer.'],
 'Build Expedition Pens first, then prepare spare companions and food.':['Baue zuerst Expeditionsgehege und bereite freie Begleiter und Nahrung vor.','Construye primero corrales de expedición y prepara compañeros libres y comida.','Bouw eerst expeditieverblijven en bereid vrije metgezellen en voedsel voor.','Costruisci prima i recinti per spedizioni, poi prepara compagni liberi e cibo.','Construisez d’abord les enclos, puis préparez compagnons libres et nourriture.'],
 'Your combat helper cannot go on an Expedition while equipped. Choose a spare companion or unequip it first.':['Dein ausgerüsteter Kampfhelfer kann nicht auf Expedition gehen. Wähle einen freien Begleiter oder lege ihn ab.','Tu ayudante no puede ir de expedición mientras esté equipado. Elige otro compañero o desequípalo.','Je uitgeruste helper kan niet op expeditie. Kies een vrije metgezel of haal de helper eerst uit je uitrusting.','L’aiutante equipaggiato non può partire in spedizione. Scegli un compagno libero o rimuovilo prima.','Votre allié équipé ne peut pas partir en expédition. Choisissez un autre compagnon ou déséquipez-le.'],
 'Start small: equip a compatible helper, then use recruitment requirements to plan your next companion.':['Beginne klein: Rüste einen passenden Helfer aus und plane mit den Anforderungen deinen nächsten Begleiter.','Empieza poco a poco: equipa un ayudante compatible y usa los requisitos para planear tu próximo compañero.','Begin klein: rust een passende helper uit en gebruik de wervingsvereisten voor je volgende metgezel.','Inizia in piccolo: equipaggia un aiutante compatibile e consulta i requisiti per il prossimo compagno.','Commencez simplement : équipez un allié compatible, puis consultez les conditions de votre prochain compagnon.'],
 'COMPANION GUIDE':['BEGLEITER-GUIDE','GUÍA DE COMPAÑEROS','METGEZELLENGIDS','GUIDA AI COMPAGNI','GUIDE DES COMPAGNONS'],
 'Companion guide progress':['Guide-Fortschritt','Progreso de la guía','Voortgang van de gids','Avanzamento della guida','Progression du guide'],
 'Explore the screen below. Actions become available after this short guide.':['Sieh dir den Bildschirm an. Aktionen sind nach diesem kurzen Guide verfügbar.','Explora la pantalla. Las acciones estarán disponibles al terminar esta breve guía.','Bekijk het scherm hieronder. Acties zijn na deze korte gids beschikbaar.','Esplora la schermata. Le azioni saranno disponibili dopo questa breve guida.','Explorez cet écran. Les actions seront disponibles après ce court guide.'],
 'Tap the highlighted button to explore the next area.':['Tippe auf die hervorgehobene Taste für den nächsten Bereich.','Toca el botón resaltado para explorar la siguiente área.','Tik op de gemarkeerde knop voor het volgende onderdeel.','Tocca il pulsante evidenziato per esplorare la prossima area.','Touchez le bouton surligné pour explorer la zone suivante.'],
 'Guide complete. Your Companion Sanctuary is ready.':['Guide abgeschlossen. Deine Begleiterzuflucht ist bereit.','Guía completada. Tu santuario está listo.','Gids voltooid. Je metgezellenheiligdom is klaar.','Guida completata. Il santuario è pronto.','Guide terminé. Votre sanctuaire est prêt.'],
 'Enter Companion Sanctuary':['Begleiterzuflucht betreten','Entrar al santuario','Metgezellenheiligdom betreden','Entra nel santuario','Entrer dans le sanctuaire'],
};
export function companionTutorialText(language:Language,source:string){
 const languageIndex=['de','es','nl','it','fr'].indexOf(language);
 if(languageIndex<0)return source;
 if(ui[source])return ui[source][languageIndex];
 for(let i=0;i<COMPANION_TOUR_STEPS.length;i++){
  const step=COMPANION_TOUR_STEPS[i],field=[step.title,step.body,step.hint,step.action].indexOf(source);
  if(field>=0)return steps[language]?.[i]?.[field]??source;
 }
 return source;
}
