import type {Language} from './languages';
import {GUILD_TUTORIAL_STEPS} from '../core/guild-tutorial';
const steps:Partial<Record<Language,readonly (readonly [string,string,string,string])[]>>={
 de:[
  ['Willkommen in deiner Gilde','Lies am Schwarzen Brett, was deine Gilde plant. Ist es leer, schau im Gildenchat nach Prioritäten.','Erkunde jeden Bereich. Du kannst den Guide pausieren und später fortsetzen.','Gildenstartseite zeigen'],
  ['Lerne deine Gilde kennen','Im Gildenchat planen und reden Mitglieder. Mehr → Mitglieder zeigt die Mitglieder und ihre Rollen.','Anführer und Offiziere helfen bei Fragen.','Gildenchat öffnen'],
  ['Dein Alltag zählt','Muster erfasst tägliche Beiträge und die wöchentliche Rallye. Qualifizierte Tage bringen Rallye-Marken; sie müssen nicht aufeinanderfolgen.','Spiele, wann es dir passt. Ein verpasster Tag löscht deine qualifizierten Tage nicht.','Muster zeigen'],
  ['Wähle ein gemeinsames Ziel','Gildenquests sind gemeinsame Wochenziele. Prüfe Aufgabe und Restzeit und wähle eine passende Aktivität.','Du musst nicht das ganze Ziel allein erfüllen.','Gildenquests zeigen'],
  ['Baut gemeinsam etwas auf','Projekte fördern die Gilde. Lies die Anforderungen eines aktiven Projekts und prüfe, was du beitragen kannst.','Prüfe Anforderungen vor Spenden. Manche Aktionen sind der Führung vorbehalten; fertige Projekte können Belohnungen bieten.','Gildenprojekte zeigen'],
  ['Hilf bei Gildenbossen','Geeignete Kämpfe helfen gegen Gildenbosse. Prüfe Teilnahmeberechtigung, Beitrag und Frist vor möglichen Belohnungen.','Neue Mitglieder können erst beim nächsten fest besetzten Kampf teilnehmen. Hole berechtigte Belohnungen fristgerecht ab.','Gildenbosse zeigen'],
  ['Bereit zum Mitmachen','Die Halle zeigt Einrichtungen und dauerhafte Boni. Lies den Aushang, spiele eine passende Aktivität und prüfe den Fortschritt.','Mehr → Laden nutzt Gildenmarken. Auf der Startseite kannst du diesen Guide wiederholen.','Gildenhalle erkunden'],
 ],
 es:[
  ['Bienvenido a tu gremio','Lee el tablón para conocer los planes del gremio. Si está vacío, consulta las prioridades en el chat.','Explora cada sección. Puedes pausar la guía y retomarla después.','Mostrar inicio del gremio'],
  ['Conoce a tus compañeros','Los miembros coordinan y conversan en el chat. Más → Miembros muestra quién pertenece al gremio y su rol.','Los líderes y oficiales pueden ayudarte con tus dudas.','Abrir chat del gremio'],
  ['Tu actividad cuenta','Muster registra la contribución diaria y el Rally semanal. Los días válidos dan marcas de Rally; no tienen que ser consecutivos.','Juega a tu ritmo. Faltar un día no borra los días válidos de la semana.','Mostrar Muster diario'],
  ['Elige un objetivo compartido','Las misiones del gremio son objetivos semanales compartidos. Revisa la tarea y el tiempo restante y elige una actividad útil.','No tienes que completar todo el objetivo por tu cuenta.','Mostrar misiones del gremio'],
  ['Construye junto al gremio','Los proyectos hacen progresar al gremio. Lee los requisitos de uno activo y comprueba cómo puedes contribuir.','Revisa los requisitos antes de donar. Algunas acciones requieren liderazgo; comprueba las recompensas al terminar.','Mostrar proyectos del gremio'],
  ['Participa contra los jefes','El combate apto ayuda contra los jefes del gremio. Revisa elegibilidad, contribución y plazo antes de esperar recompensas.','Los recién llegados pueden tener que esperar al próximo encuentro. Reclama recompensas aptas antes del plazo.','Mostrar jefes del gremio'],
  ['Listo para participar','El salón muestra instalaciones y bonos duraderos. Lee el aviso, realiza una actividad útil y comprueba tu progreso.','Más → Tienda usa marcas del gremio. Puedes repetir esta guía desde el inicio.','Explorar salón del gremio'],
 ],
 nl:[
  ['Welkom bij je gilde','Lees het prikbord voor de plannen van je gilde. Is het leeg, bekijk dan de prioriteiten in de gildechat.','Verken elk onderdeel. Je kunt de gids pauzeren en later hervatten.','Gildestartpagina tonen'],
  ['Leer je gildegenoten kennen','In de gildechat overleggen en praten leden. Meer → Leden toont wie er in je gilde zit en hun rol.','Leiders en officieren kunnen je helpen met vragen.','Gildechat openen'],
  ['Je dagelijkse spel telt mee','Muster volgt dagelijkse bijdragen en wekelijkse Rally-voortgang. Geldige dagen leveren Rally-munten op en hoeven niet opeenvolgend te zijn.','Speel wanneer het jou past. Een gemiste dag wist je geldige dagen niet.','Dagelijkse Muster tonen'],
  ['Kies een gezamenlijk doel','Gildequests zijn gedeelde weekdoelen. Bekijk de opdracht en resterende tijd en kies een nuttige activiteit.','Je hoeft niet het hele doel alleen af te ronden.','Gildequests tonen'],
  ['Bouw samen iets op','Projecten helpen je gilde vooruit. Lees de eisen van een actief project en bekijk wat je kunt bijdragen.','Controleer eisen voordat je doneert. Sommige acties zijn voor leiders; bekijk beloningen na voltooiing.','Gildeprojecten tonen'],
  ['Help tegen gildebazen','Geschikte gevechten helpen tegen gildebazen. Bekijk deelname, bijdragevereisten en deadlines voordat je beloningen verwacht.','Nieuwe leden moeten soms wachten op de volgende ontmoeting. Claim beschikbare beloningen op tijd.','Gildebazen tonen'],
  ['Klaar om mee te doen','De hal toont faciliteiten en blijvende bonussen. Lees het bericht, speel een nuttige activiteit en bekijk je voortgang.','Meer → Winkel gebruikt gildemunten. Je kunt deze gids herhalen vanaf de startpagina.','Gildehal verkennen'],
 ],
 it:[
  ['Benvenuto nella gilda','Leggi la bacheca per i piani della gilda. Se è vuota, controlla le priorità nella chat.','Esplora ogni sezione. Puoi mettere in pausa la guida e riprenderla dopo.','Mostra pagina della gilda'],
  ['Conosci i compagni di gilda','Nella chat i membri parlano e si coordinano. Altro → Membri mostra chi appartiene alla gilda e il suo ruolo.','Leader e ufficiali possono aiutarti con le domande.','Apri chat della gilda'],
  ['Le tue attività contano','Muster segue contributi giornalieri e Rally settimanale. I giorni validi danno marchi Rally e non devono essere consecutivi.','Gioca quando vuoi. Saltare un giorno non cancella quelli validi della settimana.','Mostra Muster giornaliero'],
  ['Scegli un obiettivo comune','Le missioni della gilda sono obiettivi settimanali condivisi. Controlla compito e tempo rimasto e scegli un’attività utile.','Non devi completare tutto l’obiettivo da solo.','Mostra missioni della gilda'],
  ['Costruite insieme','I progetti fanno crescere la gilda. Leggi i requisiti di un progetto attivo e controlla come contribuire.','Controlla i requisiti prima di donare. Alcune azioni richiedono un leader; verifica le ricompense al termine.','Mostra progetti della gilda'],
  ['Partecipa contro i boss','I combattimenti idonei aiutano contro i boss. Controlla idoneità, contributi e scadenze prima di aspettarti ricompense.','I nuovi membri potrebbero dover attendere il prossimo incontro. Riscuoti le ricompense disponibili in tempo.','Mostra boss della gilda'],
  ['Pronto a partecipare','La sala mostra strutture e bonus permanenti. Leggi l’avviso, svolgi un’attività utile e controlla i progressi.','Altro → Negozio usa marchi gilda. Puoi ripetere la guida dalla pagina iniziale.','Esplora sala della gilda'],
 ],
 fr:[
  ['Bienvenue dans votre guilde','Lisez le tableau d’affichage pour connaître les projets de la guilde. S’il est vide, consultez les priorités dans le chat.','Explorez chaque section. Vous pouvez mettre le guide en pause et le reprendre plus tard.','Afficher l’accueil de guilde'],
  ['Rencontrez vos compagnons','Les membres discutent et se coordonnent dans le chat. Plus → Membres affiche les membres et leurs rôles.','Les chefs et officiers peuvent répondre à vos questions.','Ouvrir le chat de guilde'],
  ['Vos activités comptent','Muster suit les contributions quotidiennes et le Rally hebdomadaire. Les jours valides rapportent des marques Rally sans devoir être consécutifs.','Jouez à votre rythme. Une absence n’efface pas vos jours valides de la semaine.','Afficher Muster quotidien'],
  ['Choisissez un objectif commun','Les quêtes de guilde sont des objectifs hebdomadaires partagés. Vérifiez tâche et temps restant, puis choisissez une activité utile.','Vous n’avez pas à terminer tout l’objectif seul.','Afficher les quêtes de guilde'],
  ['Construisez ensemble','Les projets font progresser la guilde. Lisez les conditions d’un projet actif et voyez comment contribuer.','Vérifiez les conditions avant tout don. Certaines actions exigent un dirigeant ; consultez les récompenses à la fin.','Afficher les projets de guilde'],
  ['Participez contre les boss','Les combats éligibles aident contre les boss. Vérifiez participation, contribution requise et échéance avant d’attendre des récompenses.','Les nouveaux membres devront parfois attendre la prochaine rencontre. Réclamez les récompenses éligibles à temps.','Afficher les boss de guilde'],
  ['Prêt à participer','Le hall montre installations et bonus durables. Lisez l’annonce, pratiquez une activité utile, puis vérifiez vos progrès.','Plus → Boutique utilise les marques de guilde. Vous pouvez relancer ce guide depuis l’accueil.','Explorer le hall de guilde'],
 ],
};
const rows:Record<string,readonly string[]>={
 'YOUR GUILD GUIDE':['DEIN GILDEN-GUIDE','TU GUÍA DEL GREMIO','JE GILDEGIDS','LA GUIDA DELLA GILDA','VOTRE GUIDE DE GUILDE'],
 'Guild guide progress':['Guide-Fortschritt','Progreso de la guía','Voortgang van de gids','Avanzamento della guida','Progression du guide'],
 'Previous tip':['Voriger Tipp','Consejo anterior','Vorige tip','Consiglio precedente','Conseil précédent'],
 'More detail':['Mehr Details','Más detalles','Meer uitleg','Altri dettagli','Plus de détails'],
 'Less detail':['Weniger Details','Menos detalles','Minder uitleg','Meno dettagli','Moins de détails'],
 'Pause guide':['Guide pausieren','Pausar guía','Gids pauzeren','Pausa guida','Mettre en pause'],
 'Resume guild guide':['Gilden-Guide fortsetzen','Reanudar guía','Gildegids hervatten','Riprendi guida','Reprendre le guide'],
 'Replay guild guide':['Gilden-Guide wiederholen','Repetir guía','Gildegids herhalen','Ripeti guida','Revoir le guide'],
 'Continue guide':['Guide fortsetzen','Continuar guía','Verder met gids','Continua guida','Continuer le guide'],
 'Finish guide':['Guide beenden','Terminar guía','Gids afronden','Termina guida','Terminer le guide'],
 'Read tip again':['Tipp erneut lesen','Leer consejo otra vez','Tip opnieuw lezen','Rileggi consiglio','Relire le conseil'],
 'Return to this section before continuing the guide.':['Kehre vor dem Fortsetzen zu diesem Bereich zurück.','Vuelve a esta sección antes de continuar.','Keer terug naar dit onderdeel voordat je doorgaat.','Torna a questa sezione prima di continuare.','Revenez à cette section avant de continuer.'],
 'Look around below. No message, contribution or purchase is required.':['Schau dich unten um. Nachricht, Beitrag oder Kauf sind nicht nötig.','Explora abajo. No se requiere enviar mensajes, contribuir ni comprar.','Kijk hieronder rond. Een bericht, bijdrage of aankoop is niet nodig.','Esplora qui sotto. Non servono messaggi, contributi o acquisti.','Explorez ci-dessous. Aucun message, contribution ou achat n’est requis.'],
 'You can read the notice. Leaders and officers manage guild announcements.':['Du kannst den Aushang lesen. Anführer und Offiziere verwalten Mitteilungen.','Puedes leer el aviso. Líderes y oficiales gestionan los anuncios.','Je kunt het bericht lezen. Leiders en officieren beheren aankondigingen.','Puoi leggere l’avviso. Leader e ufficiali gestiscono gli annunci.','Vous pouvez lire l’annonce. Les chefs et officiers gèrent les annonces.'],
 'Your role can manage announcements. Start by checking the current guild priority.':['Deine Rolle kann Mitteilungen verwalten. Prüfe zuerst die aktuelle Priorität.','Tu rol puede gestionar anuncios. Revisa primero la prioridad actual.','Jouw rol kan aankondigingen beheren. Bekijk eerst de huidige prioriteit.','Il tuo ruolo può gestire annunci. Controlla prima la priorità attuale.','Votre rôle peut gérer les annonces. Vérifiez d’abord la priorité actuelle.'],
 'Reading is enough for this step. Introduce yourself only when you want to.':['Lesen reicht hier aus. Stelle dich nur vor, wenn du möchtest.','Basta con leer. Preséntate solo cuando quieras.','Lezen is genoeg. Stel jezelf alleen voor als je dat wilt.','Basta leggere. Presentati solo quando vuoi.','Lire suffit. Présentez-vous seulement si vous le souhaitez.'],
 'Starting at zero is normal. Everyday combat and skilling build your contribution.':['Bei null zu beginnen ist normal. Kämpfe und Fertigkeiten erhöhen deinen Beitrag.','Empezar en cero es normal. Combatir y entrenar habilidades aumenta tu contribución.','Beginnen bij nul is normaal. Gevechten en vaardigheden bouwen je bijdrage op.','Partire da zero è normale. Combattimenti e abilità aumentano il contributo.','Commencer à zéro est normal. Combats et compétences augmentent votre contribution.'],
 'Pick a goal that fits your level. You do not need to finish a quest to continue this guide.':['Wähle ein Ziel passend zu deinem Level. Du musst keine Quest für diesen Guide abschließen.','Elige un objetivo de tu nivel. No necesitas completar una misión para seguir.','Kies een doel dat bij je niveau past. Je hoeft geen quest af te ronden voor deze gids.','Scegli un obiettivo adatto al livello. Non devi completare una missione per continuare.','Choisissez un objectif de votre niveau. Terminer une quête n’est pas requis pour continuer.'],
 'As a member, help with active projects. Leadership manages project selection and upgrades.':['Als Mitglied hilfst du bei aktiven Projekten. Die Führung verwaltet Auswahl und Upgrades.','Como miembro, ayuda en proyectos activos. Los dirigentes eligen proyectos y mejoras.','Als lid help je met actieve projecten. De leiding beheert projectkeuzes en upgrades.','Come membro aiuti i progetti attivi. La dirigenza gestisce scelte e miglioramenti.','Comme membre, aidez les projets actifs. Les dirigeants gèrent choix et améliorations.'],
 'Coordinate project choices with your guild. Check costs before committing shared resources.':['Stimme Projekte mit der Gilde ab. Prüfe Kosten vor gemeinsamen Ausgaben.','Coordina los proyectos con tu gremio. Revisa costes antes de gastar recursos comunes.','Overleg projectkeuzes met je gilde. Bekijk kosten voordat je gedeelde middelen inzet.','Coordina i progetti con la gilda. Controlla i costi prima di spendere risorse comuni.','Coordonnez les projets avec la guilde. Vérifiez les coûts avant de dépenser les ressources communes.'],
 'Joined recently? If the current boss excludes you, wait for the next encounter. No claim is required now.':['Neu dabei? Falls du nicht am aktuellen Boss teilnehmen kannst, warte auf den nächsten. Abholen ist jetzt nicht nötig.','¿Acabas de unirte? Si no puedes participar contra este jefe, espera al siguiente. No necesitas reclamar nada ahora.','Net lid? Als je niet bij de huidige baas mag meedoen, wacht op de volgende. Nu claimen is niet nodig.','Sei appena entrato? Se non sei idoneo al boss attuale, attendi il prossimo. Non devi riscuotere ora.','Nouveau membre ? Si le boss actuel vous exclut, attendez la prochaine rencontre. Aucune récompense à réclamer maintenant.'],
 'You benefit from unlocked facilities without managing them. Guild Marks shopping can wait until you earn some.':['Du profitierst von Einrichtungen, ohne sie zu verwalten. Einkäufe warten, bis du Gildenmarken verdient hast.','Te beneficias de las instalaciones sin gestionarlas. Compra cuando hayas ganado marcas del gremio.','Je profiteert van vrijgespeelde faciliteiten zonder ze te beheren. Winkelen kan wachten tot je gildemunten hebt.','Benefici delle strutture senza gestirle. Gli acquisti possono aspettare finché guadagni marchi gilda.','Vous profitez des installations sans les gérer. Les achats peuvent attendre vos premières marques de guilde.'],
 'Review facilities and available funds before upgrading. Purchases are not part of this guide.':['Prüfe Einrichtungen und Mittel vor Upgrades. Käufe gehören nicht zu diesem Guide.','Revisa instalaciones y fondos antes de mejorar. La guía no requiere compras.','Bekijk faciliteiten en beschikbare middelen vóór upgrades. Aankopen horen niet bij deze gids.','Controlla strutture e fondi prima di migliorare. La guida non richiede acquisti.','Vérifiez installations et fonds avant les améliorations. Ce guide ne demande aucun achat.'],
};
export function guildTutorialText(language:Language,source:string){
 const index=['de','es','nl','it','fr'].indexOf(language);if(index<0)return source;
 if(rows[source])return rows[source][index];
 for(let i=0;i<GUILD_TUTORIAL_STEPS.length;i++){
  const step=GUILD_TUTORIAL_STEPS[i],field=[step.title,step.body,step.tip,step.action].indexOf(source);
  if(field>=0)return steps[language]?.[i]?.[field]??source;
 }
 return source;
}
