begin;
do $$
declare a uuid:=gen_random_uuid();b uuid:=gen_random_uuid();c uuid:=gen_random_uuid();s jsonb;r jsonb;ready jsonb;first_result jsonb;again jsonb;pool jsonb;
begin
 insert into auth.users(id,email) values(a,'coop-publish-'||a||'@example.invalid'),(b,'coop-publish-'||b||'@example.invalid');
 insert into public.characters(id,account_id,name,class_id,level) values(c,a,'Published Tank','IRONWARDEN',25);
 s:=jsonb_build_object('character',jsonb_build_object('id',c,'classId','IRONWARDEN','level',25));
 insert into public.online_game_states(account_id,character_id,state,revision) values(a,c,s,1);
 r:=jsonb_build_object('accountId',a,'characterId',c,'classId','IRONWARDEN','characterLevel',25,'loadoutId','current','revision',1,'dungeonUnlocked',true,'legalEquipment',true,'capabilities',jsonb_build_array('threat','defense'),'abilities','[]'::jsonb,'stats',jsonb_build_object('characterId',c,'classId','IRONWARDEN','level',25,'maxHp',5200,'attackPower',420,'defense',1500,'healingPower',180,'accuracy',680,'evasion',180,'critChance',0.05,'haste',0.03));
 ready:='{"role":"tank","ready":true,"normalizedScore":1,"failures":[]}';
 begin perform public.publish_online_coop_loadout_server_v1(a,2,r,repeat('a',64),ready);raise exception 'stale source accepted';exception when raise_exception then if sqlerrm<>'stale_game_version' then raise;end if;end;
 begin perform public.publish_online_coop_loadout_server_v1(a,1,jsonb_set(r,'{accountId}',to_jsonb(b)),repeat('a',64),ready);raise exception 'foreign owner accepted';exception when raise_exception then if sqlerrm<>'invalid_loadout_evidence' then raise;end if;end;
 first_result:=public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready);
 if first_result->>'sharing'<>'false' or exists(select 1 from public.echo_profiles where character_id=c) then raise exception 'implicit Echo sharing';end if;
 first_result:=public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready,true,'publish-echo-one');
 again:=public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready,true,'publish-echo-one');
 if again<>first_result or (select count(*) from public.echo_profiles where character_id=c)<>1 then raise exception 'Echo share replay duplicated';end if;
 begin perform public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready,false,'publish-echo-one');raise exception 'changed share intent accepted';exception when raise_exception then if sqlerrm<>'idempotency_key_conflict' then raise;end if;end;
 pool:=public.eligible_online_coop_echoes_server_v1(b,15);
 if not exists(select 1 from jsonb_array_elements(pool) e where e->>'sourceAccountId'=a::text) then raise exception 'published Echo missing';end if;
 if exists(select 1 from jsonb_array_elements(public.eligible_online_coop_echoes_server_v1(a,15)) e where e->>'sourceAccountId'=a::text) then raise exception 'own Echo eligible';end if;
 insert into public.player_blocks(blocker_id,blocked_id) values(b,a);
 if exists(select 1 from jsonb_array_elements(public.eligible_online_coop_echoes_server_v1(b,15)) e where e->>'sourceAccountId'=a::text) then raise exception 'blocked Echo eligible';end if;
 delete from public.player_blocks where blocker_id=b and blocked_id=a;
 insert into public.player_blocks(blocker_id,blocked_id) values(a,b);
 if exists(select 1 from jsonb_array_elements(public.eligible_online_coop_echoes_server_v1(b,15)) e where e->>'sourceAccountId'=a::text) then raise exception 'reverse blocked Echo eligible';end if;
 delete from public.player_blocks where blocker_id=a and blocked_id=b;
 update public.echo_profiles set expires_at=clock_timestamp()-interval '1 second' where character_id=c;
 if exists(select 1 from jsonb_array_elements(public.eligible_online_coop_echoes_server_v1(b,15)) e where e->>'sourceAccountId'=a::text) then raise exception 'expired Echo eligible';end if;
 again:=public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready,true,'republish-expired');
 if again->>'sharing'<>'true' or again->>'echoProfileId'=first_result->>'echoProfileId' then raise exception 'expired snapshot did not republish';end if;
 perform public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready,false,'stop-echo-sharing');
 if exists(select 1 from public.echo_profiles where character_id=c and opted_in) then raise exception 'opt out failed';end if;
 perform set_config('request.jwt.claim.sub',a::text,true);set local role authenticated;
 begin perform public.publish_online_coop_loadout_server_v1(a,1,r,repeat('a',64),ready);raise exception 'client can publish stats';exception when insufficient_privilege then null;end;
 begin perform public.eligible_online_coop_echoes_server_v1(a,15);raise exception 'client sees donor private records';exception when insufficient_privilege then null;end;
 reset role;
end $$;
select 'PASS: source revision/ownership, explicit Echo consent, replay/conflict, expiry, republish, bidirectional blocks and RPC grants' as result;
rollback;
