"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const equipment_catalog_v23_1 = require("./equipment-catalog-v23");
const equipment_stat_budget_v24_1 = require("./equipment-stat-budget-v24");
const equipment_balance_v24_1 = require("./equipment-balance-v24");
const equipment_recipes_v24_1 = require("./equipment-recipes-v24");
const equipment_item_instance_v24_1 = require("./equipment-item-instance-v24");
const equipment_equip_v24_1 = require("./equipment-equip-v24");
const equipment_customization_v24_1 = require("./equipment-customization-v24");
const equipment_legacy_migration_v24_1 = require("./equipment-legacy-migration-v24");
const equipment_skin_progress_v24_1 = require("./equipment-skin-progress-v24");
const equipment_upgrades_v24_1 = require("./equipment-upgrades-v24");
const eq = (a, b, m = 'assert') => { if (a !== b)
    throw new Error(`${m}:${String(a)}!=${String(b)}`); };
const ok = (v, m = 'assert') => { if (!v)
    throw new Error(m); };
eq(equipment_catalog_v23_1.EQUIPMENT_SETS_V23.length, 243);
eq(equipment_catalog_v23_1.EQUIPMENT_PIECES_V23.length, 1701);
eq((0, equipment_balance_v24_1.exactUpgradeStatMultiplierV24)(10), 1.35);
eq((0, equipment_balance_v24_1.finalCraftMinutesV24)('T9', 'Weapon'), 45);
eq((0, equipment_balance_v24_1.finalCraftMinutesV24)('T9', 'Gloves'), 30);
eq((0, equipment_customization_v24_1.statGemSocketUnlockedV24)('T1'), false);
eq((0, equipment_customization_v24_1.statGemSocketUnlockedV24)('T2'), true);
eq((0, equipment_customization_v24_1.effectGemSocketUnlockedV24)('T2'), false);
eq((0, equipment_customization_v24_1.effectGemSocketUnlockedV24)('T3'), true);
eq((0, equipment_customization_v24_1.maxGemRankV24)('T9'), 5);
const t9 = equipment_catalog_v23_1.EQUIPMENT_SETS_V23.find(s => s.tier === 'T9' && s.className === 'Wayfinder' && s.path === 'Foundation');
const weapon = equipment_catalog_v23_1.EQUIPMENT_PIECES_V23.find(p => p.setId === t9.id && p.slot === 'Weapon');
const budget = (0, equipment_stat_budget_v24_1.baseStatsForPieceV24)(weapon, 10);
ok(budget.lines.every(l => l.upgradedValue > 0), 'budget');
const recipe = (0, equipment_recipes_v24_1.recipeForPieceV24)(weapon);
eq(recipe.craftMinutes, 45);
ok(recipe.requirements.some(r => r.role === 'dungeonBoss' && r.guaranteedSource), 'boss_required');
ok((recipe.estimatedBossClears?.[0] ?? 0) >= 1, 'clears');
ok((0, equipment_recipes_v24_1.fullSetStorySupportGrantV24)('T9', 'Wayfinder').length >= 1, 'story_grant');
const inst = { id: 'i1', characterId: 'c', pieceId: weapon.id, upgradeRank: 0, acquireSource: 'craft', createdAt: 'now' };
ok((0, equipment_item_instance_v24_1.deriveInstanceV24)(inst).stats.power >= 0, 'derive');
const currentPiece = equipment_catalog_v23_1.EQUIPMENT_PIECES_V23.find(p => p.tier === 'T8' && p.className === 'Wayfinder' && p.slot === 'Weapon');
const old = { id: 'old', characterId: 'c', pieceId: currentPiece.id, upgradeRank: 0, acquireSource: 'craft', createdAt: 'now' };
const ctx = { characterId: 'c', className: 'Wayfinder', level: 70, instances: [old, inst], loadout: { Weapon: 'old' } };
eq((0, equipment_equip_v24_1.equipItemV24)(ctx, 'i1').Weapon, 'i1');
ok((0, equipment_equip_v24_1.compareEquipV24)(ctx, 'i1').candidateItemId === 'i1', 'compare');
ok((0, equipment_equip_v24_1.loadoutSummaryV24)({ ...ctx, loadout: { Weapon: 'i1' } }).stats.power >= 0, 'summary');
const legacy = { legacyInstanceId: 'l1', characterId: 'c', className: 'Wayfinder', slot: 'Weapon', requiredLevel: 18, upgradeRank: 5, statGemId: 'GSTAT_006', statGemRank: 2, effectGemId: 'GEFF_001', effectGemRank: 1 };
eq((0, equipment_legacy_migration_v24_1.legacyConversionOptionsV24)(legacy).length, 3);
const cv = (0, equipment_legacy_migration_v24_1.buildLegacyConversionV24)(legacy, 'Foundation');
eq(cv.preservedUpgradeRank, 5);
eq(cv.grantsFirstCraftCredit, true);
const setPieces = equipment_catalog_v23_1.EQUIPMENT_PIECES_V23.filter(p => p.setId === t9.id);
const prog6 = (0, equipment_skin_progress_v24_1.setSkinProgressV24)('Wayfinder', setPieces.slice(0, 6).map(p => p.id), []).find(v => v.setId === t9.id);
eq(prog6.unlocked, false);
eq(prog6.crafted, 6);
const up1 = (0, equipment_upgrades_v24_1.upgradeCostV24)('T9', 1), up10 = (0, equipment_upgrades_v24_1.upgradeCostV24)('T9', 10);
ok(up10.gold > up1.gold, 'upgrade_gold');
ok(up10.materialQuantity > up1.materialQuantity, 'upgrade_material');
console.log('equipment-v24 tests passed');
