import {hashRegionContentV20,buildSunscarRegionContentBundleV20,type RegionContentRecordV20} from './region-content-publisher-v20';
import {SUNSCAR_ACHIEVEMENTS_V21,SUNSCAR_ACTIVITIES_V21,SUNSCAR_BOSS_MASTERY_V21,SUNSCAR_COLLECTION_BOOKS_V21,SUNSCAR_CONTRACTS_V21,SUNSCAR_SIDE_QUESTS_V21,SUNSCAR_WEATHER_RULES_V21} from './sunscar-depth-v21';
import {FROSTMARCH_BOSSES_V21,FROSTMARCH_COLLECTIBLES_V21,FROSTMARCH_ECHOES_V21,FROSTMARCH_ENEMIES_V21,FROSTMARCH_EQUIPMENT_POLICY_V21,FROSTMARCH_QUESTLINE_V21,FROSTMARCH_RELICS_V21,FROSTMARCH_RESOURCES_V21,FROSTMARCH_ZONES_V21} from './frostmarch-region-v21';
import {FROSTMARCH_DUNGEONS_V21,FROSTMARCH_DUNGEON_NODES_V21} from './frostmarch-dungeons-v21';
import {FROSTMARCH_ACHIEVEMENTS_V21,FROSTMARCH_ACTIVITIES_V21,FROSTMARCH_BOSS_MASTERY_V21,FROSTMARCH_COLLECTION_BOOKS_V21,FROSTMARCH_CONTRACTS_V21,FROSTMARCH_SIDE_QUESTS_V21,FROSTMARCH_WEATHER_RULES_V21} from './frostmarch-gameplay-v21';
export type RegionContentRecordTypeV21=RegionContentRecordV20['recordType']|'side_quest'|'activity'|'achievement'|'collection_book'|'weather_rule'|'region_contract'|'boss_mastery';
export interface RegionContentRecordV21{recordType:RegionContentRecordTypeV21;recordId:string;sortOrder:number;payload:unknown;}
export interface RegionContentBundleV21{contentVersion:string;regionId:'REG_002'|'REG_003';schemaVersion:2;records:readonly RegionContentRecordV21[];contentHash:string;}
const extra=(type:RegionContentRecordTypeV21,list:readonly {id:string}[],start:number):RegionContentRecordV21[]=>list.map((payload,i)=>({recordType:type,recordId:payload.id,sortOrder:start+i,payload}));
export function buildSunscarRegionContentBundleV21(contentVersion='sunscar-v21.0.0'):RegionContentBundleV21{
 const base=buildSunscarRegionContentBundleV20(contentVersion).records;
 const records:RegionContentRecordV21[]=[...base,...extra('side_quest',SUNSCAR_SIDE_QUESTS_V21,800),...extra('activity',SUNSCAR_ACTIVITIES_V21,850),...extra('achievement',SUNSCAR_ACHIEVEMENTS_V21,900),...extra('collection_book',SUNSCAR_COLLECTION_BOOKS_V21,930),...extra('weather_rule',SUNSCAR_WEATHER_RULES_V21,940),...extra('region_contract',SUNSCAR_CONTRACTS_V21,950),...extra('boss_mastery',SUNSCAR_BOSS_MASTERY_V21,960)];
 return {contentVersion,regionId:'REG_002',schemaVersion:2,records,contentHash:hashRegionContentV20({contentVersion,regionId:'REG_002',schemaVersion:2,records})};
}
export function buildFrostmarchRegionContentBundleV21(contentVersion='frostmarch-v21.0.0'):RegionContentBundleV21{
 const records:RegionContentRecordV21[]=[
  {recordType:'region',recordId:'REG_003',sortOrder:0,payload:{id:'REG_003',name:'Frostmarch',levelMin:45,levelMax:70,unlockBossId:'BOSS_002',finalBossId:'BOSS_003',nextRegionId:'REG_004',equipmentPolicy:FROSTMARCH_EQUIPMENT_POLICY_V21}},
  ...extra('zone',FROSTMARCH_ZONES_V21,100),...extra('monster',FROSTMARCH_ENEMIES_V21,200),...extra('boss',FROSTMARCH_BOSSES_V21,300),...extra('resource',FROSTMARCH_RESOURCES_V21,400),...extra('quest',FROSTMARCH_QUESTLINE_V21,500),...extra('echo_condition',FROSTMARCH_ECHOES_V21,550),...extra('relic',FROSTMARCH_RELICS_V21,560),...extra('collectible_unlock',FROSTMARCH_COLLECTIBLES_V21,570),...extra('live_dungeon',FROSTMARCH_DUNGEONS_V21,600),...extra('dungeon_node',FROSTMARCH_DUNGEON_NODES_V21,700),...extra('side_quest',FROSTMARCH_SIDE_QUESTS_V21,800),...extra('activity',FROSTMARCH_ACTIVITIES_V21,850),...extra('achievement',FROSTMARCH_ACHIEVEMENTS_V21,900),...extra('collection_book',FROSTMARCH_COLLECTION_BOOKS_V21,930),...extra('weather_rule',FROSTMARCH_WEATHER_RULES_V21,940),...extra('region_contract',FROSTMARCH_CONTRACTS_V21,950),...extra('boss_mastery',FROSTMARCH_BOSS_MASTERY_V21,960),
 ];
 return {contentVersion,regionId:'REG_003',schemaVersion:2,records,contentHash:hashRegionContentV20({contentVersion,regionId:'REG_003',schemaVersion:2,records})};
}
export interface RegionContentStoreV21{stageManifest(i:{contentVersion:string;regionId:string;schemaVersion:number;contentHash:string;minimumClientBuild:number}):Promise<void>;replaceDraftRecords(v:string,r:readonly RegionContentRecordV21[]):Promise<void>;publishManifest(v:string,h:string):Promise<void>;activateRegion(regionId:string,contentVersion:string):Promise<void>;}
export async function stagePublishActivateRegionV21(store:RegionContentStoreV21,bundle:RegionContentBundleV21,input:{minimumClientBuild:number;publish:boolean;activate:boolean}):Promise<void>{await store.stageManifest({contentVersion:bundle.contentVersion,regionId:bundle.regionId,schemaVersion:bundle.schemaVersion,contentHash:bundle.contentHash,minimumClientBuild:input.minimumClientBuild});await store.replaceDraftRecords(bundle.contentVersion,bundle.records);if(input.publish)await store.publishManifest(bundle.contentVersion,bundle.contentHash);if(input.activate){if(!input.publish)throw new Error('activate_requires_publish');await store.activateRegion(bundle.regionId,bundle.contentVersion);}}
