import {validateRegionalGameplayV21} from './region-gameplay-v21';
import {SUNSCAR_ACHIEVEMENTS_V21,SUNSCAR_ACTIVITIES_V21,SUNSCAR_BOSS_MASTERY_V21,SUNSCAR_COLLECTION_BOOKS_V21,SUNSCAR_CONTRACTS_V21,SUNSCAR_SIDE_QUESTS_V21,SUNSCAR_WEATHER_RULES_V21} from './sunscar-depth-v21';
import {FROSTMARCH_BOSSES_V21,FROSTMARCH_COLLECTIBLES_V21,FROSTMARCH_ENEMIES_V21,FROSTMARCH_EQUIPMENT_POLICY_V21,FROSTMARCH_QUESTLINE_V21,FROSTMARCH_RESOURCES_V21,FROSTMARCH_ZONES_V21} from './frostmarch-region-v21';
import {FROSTMARCH_DUNGEONS_V21,validateFrostmarchDungeonsV21} from './frostmarch-dungeons-v21';
import {FROSTMARCH_ACHIEVEMENTS_V21,FROSTMARCH_ACTIVITIES_V21,FROSTMARCH_BOSS_MASTERY_V21,FROSTMARCH_COLLECTION_BOOKS_V21,FROSTMARCH_CONTRACTS_V21,FROSTMARCH_SIDE_QUESTS_V21,FROSTMARCH_WEATHER_RULES_V21} from './frostmarch-gameplay-v21';
import {buildFrostmarchRegionContentBundleV21,buildSunscarRegionContentBundleV21} from './region-content-publisher-v21';
import {activateRegionContentVersionV21} from './region-content-admin-v21';
const eq=(a:unknown,b:unknown,m:string)=>{if(a!==b)throw new Error(`${m}: ${String(a)} !== ${String(b)}`);}; const ok=(v:boolean,m:string)=>{if(!v)throw new Error(m);};
const sunErr=validateRegionalGameplayV21({sideQuests:SUNSCAR_SIDE_QUESTS_V21,activities:SUNSCAR_ACTIVITIES_V21,achievements:SUNSCAR_ACHIEVEMENTS_V21,collectionBooks:SUNSCAR_COLLECTION_BOOKS_V21,weatherRules:SUNSCAR_WEATHER_RULES_V21,contracts:SUNSCAR_CONTRACTS_V21,bossMasteries:SUNSCAR_BOSS_MASTERY_V21});eq(sunErr.length,0,'sun gameplay validation');
const froErr=validateRegionalGameplayV21({sideQuests:FROSTMARCH_SIDE_QUESTS_V21,activities:FROSTMARCH_ACTIVITIES_V21,achievements:FROSTMARCH_ACHIEVEMENTS_V21,collectionBooks:FROSTMARCH_COLLECTION_BOOKS_V21,weatherRules:FROSTMARCH_WEATHER_RULES_V21,contracts:FROSTMARCH_CONTRACTS_V21,bossMasteries:FROSTMARCH_BOSS_MASTERY_V21});eq(froErr.length,0,'frost gameplay validation');
eq(FROSTMARCH_ZONES_V21.length,5,'zones');eq(FROSTMARCH_ENEMIES_V21.length,16,'monsters');eq(FROSTMARCH_BOSSES_V21.length,4,'bosses');eq(FROSTMARCH_RESOURCES_V21.length,10,'resources');eq(FROSTMARCH_QUESTLINE_V21.length,10,'quests');eq(FROSTMARCH_COLLECTIBLES_V21.length,9,'collectibles');eq(FROSTMARCH_DUNGEONS_V21.length,3,'dungeons');eq(validateFrostmarchDungeonsV21().length,0,'dungeon validation');
eq(FROSTMARCH_ACTIVITIES_V21.length,5,'activities');ok(FROSTMARCH_ACTIVITIES_V21.every(v=>v.contributionEligible),'activities are contribution eligible');eq(FROSTMARCH_DUNGEONS_V21.map(v=>v.id).join(','),'COP_007,COP_008,COP_009','canonical dungeon ids');
ok(FROSTMARCH_EQUIPMENT_POLICY_V21.equipmentSetsAuthored===false,'frost equipment must remain deferred');ok(FROSTMARCH_EQUIPMENT_POLICY_V21.regionalWeaponsAuthored===false,'frost weapons must remain deferred');
const sun=buildSunscarRegionContentBundleV21();const sun2=buildSunscarRegionContentBundleV21();const fro=buildFrostmarchRegionContentBundleV21();
eq(sun.contentHash,sun2.contentHash,'deterministic hash');eq(sun.schemaVersion,2,'sun schema');eq(fro.schemaVersion,2,'frost schema');ok(fro.records.some(v=>v.recordType==='weather_rule'),'weather records');ok(fro.records.some(v=>v.recordType==='boss_mastery'),'mastery records');ok(fro.records.every(v=>!JSON.stringify(v).toLowerCase().includes('player market')),'no market content');
eq(fro.records.filter(v=>v.recordType==='activity').length,5,'activity records');eq(fro.records.filter(v=>v.recordType==='live_dungeon').map(v=>v.recordId).join(','),'COP_007,COP_008,COP_009','dungeon records');
(async()=>{let active='sunscar-v20.0.0';const published='frostmarch-v21.0.0';
const activationStore={getActive:async()=>active,activate:async(_regionId:string,version:string)=>{active=version;},isPublishedForRegion:async(_regionId:string,version:string)=>version===published};
const activated=await activateRegionContentVersionV21(activationStore,{regionId:'REG_003',contentVersion:published});
eq(activated.previous,'sunscar-v20.0.0','activation previous version');eq(activated.active,published,'activation active version');
console.log('v21 region tests passed');})();
