import {useEffect,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {achievementsClient,achievementsOnlineConfigured} from '../online/achievements-client';
import type {AchievementSnapshotProjection} from '../core/achievement-types';
import {C,equipmentColors,spacing,typography} from '../theme/theme';
let requestSequence=0;const requestId=(kind:string)=>`${kind}-${Date.now()}-${++requestSequence}`;

export function AchievementsScreen(){
  const [snapshot,setSnapshot]=useState<AchievementSnapshotProjection|null>(null);
  const [showcase,setShowcase]=useState<string[]>([]);
  const [filter,setFilter]=useState<'all'|'ready'|'claimed'>('all');
  const [loading,setLoading]=useState(false);
  const [error,setError]=useState('');
  async function load(){if(!achievementsOnlineConfigured){setError('Achievements require the authenticated online server.');return}setLoading(true);setError('');try{const next=await achievementsClient.snapshot();setSnapshot(next);setShowcase(next.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not load Achievements.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  function toggle(id:string){setShowcase(current=>current.includes(id)?current.filter(value=>value!==id):current.length<3?[...current,id]:current)}
  async function saveShowcase(){setLoading(true);try{const result=await achievementsClient.showcase(showcase,requestId('showcase'));setSnapshot(result.snapshot);setShowcase(result.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not save showcase.')}finally{setLoading(false)}}
  async function claim(id:string){setLoading(true);try{const result=await achievementsClient.claim(id,requestId(`claim-${id}`));setSnapshot(result.snapshot);setShowcase(result.snapshot.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not claim achievement.')}finally{setLoading(false)}}
  const entries=snapshot?.entries??[],visibleEntries=entries.filter(entry=>filter==='all'||(filter==='ready'?entry.completed&&!entry.claimed:entry.claimed));
  return <ScrollView contentContainerStyle={s.root}><Text style={s.heading}>Achievements</Text><Panel><Text style={s.title}>Prestige, not power</Text><Text style={s.copy}>Progress, score, Gold, and titles are calculated by the <Text style={s.accent}>authenticated server</Text>. Achievements do not grant <Text style={s.good}>combat power</Text> or multipliers.</Text><Text style={s.score}>Score: {snapshot?.score??'—'}</Text><Text style={s.copy}>Claimed: <Text style={s.accent}>{snapshot?.claimedCount??'—'}</Text> · Showcase slots: {showcase.length}/3</Text><View style={s.button}><GameButton title="Save showcase" tone="secondary" disabled={loading||!snapshot} onPress={()=>void saveShowcase()}/></View></Panel><View accessibilityRole="tablist" style={s.filters}>{([['all','All',entries.length],['ready','Ready',entries.filter(entry=>entry.completed&&!entry.claimed).length],['claimed','Claimed',entries.filter(entry=>entry.claimed).length]] as const).map(([value,label,count])=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:filter===value}} onPress={()=>setFilter(value)} style={({pressed})=>[s.filter,filter===value&&s.filterSelected,pressed&&s.pressed]}><Text style={[s.filterText,filter===value&&s.filterTextSelected]}>{label} · {count}</Text></Pressable>)}</View>{loading&&<ActivityIndicator/>}{error&&<Panel><Text style={s.warning}>{error}</Text><GameButton title="Retry" tone="secondary" onPress={()=>void load()}/></Panel>}{visibleEntries.map(entry=><Panel key={entry.id}><View style={s.row}><View style={s.flex}><Text style={s.title}>{entry.name}</Text><Text style={s.copy}>{entry.category} · {entry.description}</Text><Text style={s.copy}>Progress <Text style={s.accent}>{entry.progress}/{entry.required}</Text> · {entry.points} points</Text></View><View style={s.actions}><GameButton title={entry.claimed?'Claimed':entry.completed?'Claim':'Locked'} disabled={!entry.completed||entry.claimed||loading} onPress={()=>void claim(entry.id)}/>{entry.claimed&&<GameButton title={showcase.includes(entry.id)?'Shown':'Show'} tone="secondary" disabled={loading||(!showcase.includes(entry.id)&&showcase.length>=3)} onPress={()=>toggle(entry.id)}/>}</View></View></Panel>)}{snapshot&&!loading&&!visibleEntries.length&&<Panel><Text style={s.copy}>No achievements match this filter.</Text></Panel>}</ScrollView>
}
const s=StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},copy:{...typography.body,color:C.muted,lineHeight:21},accent:{color:C.accent,fontWeight:'800'},good:{color:C.good,fontWeight:'800'},score:{...typography.hero,color:C.accent,marginTop:spacing.md},warning:{...typography.bodyStrong,color:C.warning},filters:{flexDirection:'row',flexWrap:'wrap',gap:6},filter:{minHeight:38,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},filterSelected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},filterText:{fontSize:12,color:C.muted,fontWeight:'700'},filterTextSelected:{color:'#d9f3ff'},pressed:{opacity:.76},row:{flexDirection:'row',gap:spacing.md,alignItems:'center'},flex:{flex:1,minWidth:0},actions:{gap:spacing.xs},button:{marginTop:spacing.md}});
