import {useEffect,useState,useMemo} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {ActionFeedback} from '../components/ActionFeedback';
import {EmptyState} from '../components/EmptyState';
import {LoadingState} from '../components/LoadingState';
import {achievementsClient,achievementsOnlineConfigured} from '../online/achievements-client';
import type {AchievementSnapshotProjection} from '../core/achievement-types';
import {spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
let requestSequence=0;const requestId=(kind:string)=>`${kind}-${Date.now()}-${++requestSequence}`;

export function AchievementsScreen(){
  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
  const [snapshot,setSnapshot]=useState<AchievementSnapshotProjection|null>(null);
  const [showcase,setShowcase]=useState<string[]>([]);
  const [filter,setFilter]=useState<'all'|'ready'|'claimed'>('all');
  const [busy,setBusy]=useState<string|null>(null);
  const [error,setError]=useState('');
  const loading=busy!==null;
  async function load(){if(!achievementsOnlineConfigured){setError('Achievements require the authenticated online server.');return}setBusy('load');setError('');try{const next=await achievementsClient.snapshot();setSnapshot(next);setShowcase(next.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not load Achievements.')}finally{setBusy(null)}}
  useEffect(()=>{void load()},[]);
  function toggle(id:string){setShowcase(current=>current.includes(id)?current.filter(value=>value!==id):current.length<3?[...current,id]:current)}
  async function saveShowcase(){setBusy('showcase');setError('');try{const result=await achievementsClient.showcase(showcase,requestId('showcase'));setSnapshot(result.snapshot);setShowcase(result.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not save showcase.')}finally{setBusy(null)}}
  async function claim(id:string){setBusy(`claim:${id}`);setError('');try{const result=await achievementsClient.claim(id,requestId(`claim-${id}`));setSnapshot(result.snapshot);setShowcase(result.snapshot.showcaseIds)}catch(e){setError(e instanceof Error?e.message:'Could not claim achievement.')}finally{setBusy(null)}}
  const entries=snapshot?.entries??[],visibleEntries=entries.filter(entry=>filter==='all'||(filter==='ready'?entry.completed&&!entry.claimed:entry.claimed));
  return <ScrollView contentContainerStyle={s.root}><Text style={s.heading}>Achievements</Text><Panel><Text style={s.title}>Prestige, not power</Text><Text style={s.copy}>Progress, score, Gold, and titles are calculated by the <Text style={s.accent}>authenticated server</Text>. Achievements do not grant <Text style={s.good}>combat power</Text> or multipliers.</Text><Text style={s.score}>Score: {snapshot?.score??'—'}</Text><Text style={s.copy}>Claimed: <Text style={s.accent}>{snapshot?.claimedCount??'—'}</Text> · Showcase slots: {showcase.length}/3</Text><View style={s.button}><GameButton compact title="Save showcase" tone="secondary" loading={busy==='showcase'} disabled={busy!==null||!snapshot} onPress={()=>void saveShowcase()}/></View></Panel><View accessibilityRole="tablist" style={s.filters}>{([['all','All',entries.length],['ready','Ready',entries.filter(entry=>entry.completed&&!entry.claimed).length],['claimed','Claimed',entries.filter(entry=>entry.claimed).length]] as const).map(([value,label,count])=><Pressable key={value} accessibilityRole="tab" accessibilityState={{selected:filter===value}} onPress={()=>setFilter(value)} style={({pressed})=>[s.filter,filter===value&&s.filterSelected,pressed&&s.pressed]}><Text style={[s.filterText,filter===value&&s.filterTextSelected]}>{label} · {count}</Text></Pressable>)}</View>{busy==='load'&&!snapshot&&<LoadingState label="Loading achievements" detail="Syncing server-calculated progress and showcase status."/>}{error&&<View style={s.feedbackBlock}><ActionFeedback message={error} tone="error" reduceMotion/><GameButton compact title="Retry" tone="secondary" disabled={busy!==null} onPress={()=>void load()}/></View>}{visibleEntries.map(entry=><Panel key={entry.id}><View style={s.row}><View style={s.flex}><Text style={s.title}>{entry.name}</Text><Text style={s.copy}>{entry.category} · {entry.description}</Text><Text style={s.copy}>Progress <Text style={s.accent}>{entry.progress}/{entry.required}</Text> · {entry.points} points</Text></View><View style={s.actions}><GameButton compact title={entry.claimed?'Claimed':entry.completed?'Claim':'Locked'} loading={busy===`claim:${entry.id}`} disabled={!entry.completed||entry.claimed||busy!==null} onPress={()=>void claim(entry.id)}/>{entry.claimed&&<GameButton compact title={showcase.includes(entry.id)?'Shown':'Show'} selected={showcase.includes(entry.id)} tone="secondary" disabled={busy!==null||(!showcase.includes(entry.id)&&showcase.length>=3)} onPress={()=>toggle(entry.id)}/>}</View></View></Panel>)}{snapshot&&!loading&&!visibleEntries.length&&<EmptyState compact title="No achievements here" message="Try another filter, or keep progressing to unlock more achievement entries." icon="quests"/>}</ScrollView>
}
function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},copy:{...typography.body,color:C.muted,lineHeight:21},accent:{color:C.accent,fontWeight:'800'},good:{color:C.good,fontWeight:'800'},score:{...typography.hero,color:C.accent,marginTop:spacing.md},warning:{...typography.bodyStrong,color:C.warning},feedbackBlock:{gap:spacing.sm},filters:{flexDirection:'row',flexWrap:'wrap',gap:6},filter:{minHeight:44,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},filterSelected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},filterText:{fontSize:12,color:C.muted,fontWeight:'700'},filterTextSelected:{color:C.text},pressed:{opacity:.76},row:{flexDirection:'row',gap:spacing.md,alignItems:'center'},flex:{flex:1,minWidth:0},actions:{gap:spacing.xs},button:{marginTop:spacing.md}});}
