import {useMemo} from 'react';
import {ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {GATHERING} from '../content/skills';
import {MONSTERS} from '../content/monsters';
import {accountCharacters} from '../core/account-roster';
import type {ActiveActivity,GameState} from '../core/types';
import {spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';

function elapsed(startedAtMs:number,nowMs:number){const total=Math.max(0,Math.floor((nowMs-startedAtMs)/1000)),hours=Math.floor(total/3600),minutes=Math.floor((total%3600)/60),seconds=total%60;return hours?`${hours}h ${minutes}m`:`${minutes}m ${seconds}s`}
function activityName(activity:ActiveActivity){if(activity.kind==='combat')return MONSTERS.find(item=>item.id===activity.targetId)?.name??activity.targetId.replaceAll('_',' ');return GATHERING.find(item=>item.id===activity.targetId)?.name??activity.targetId.replaceAll('_',' ')}
function activityLabel(activity:ActiveActivity|null){if(!activity)return 'Idle';return activity.kind==='combat'?'Combat':activity.kind==='training'?'Training':activity.kind==='faith'?'Faith practice':activity.kind.charAt(0).toUpperCase()+activity.kind.slice(1)}

export function ActivityOverviewScreen({state,now,onSwitch,onCreate}:{state:GameState;now:number;onSwitch:(id:string)=>void;onCreate?:()=>void}){
  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const entries=accountCharacters(state).map(entry=>({character:entry.character,activity:entry.character.id===state.character?.id?state.activity:(state.otherCharacters??[]).find(other=>other.character.id===entry.character.id)?.activity??null})).sort((a,b)=>Number(Boolean(b.activity))-Number(Boolean(a.activity)));
 return <ScrollView contentContainerStyle={s.root}><Text accessibilityRole="header" style={s.heading}>Character activity</Text><Text style={s.intro}>See what every character is doing, how long they have been doing it, and switch directly to manage another character.</Text><Panel><View style={s.summary}><View><Text style={s.summaryLabel}>ROSTER</Text><Text style={s.summaryValue}>{entries.length} character{entries.length===1?'':'s'}</Text></View><View><Text style={s.summaryLabel}>ACTIVE</Text><Text style={s.summaryValue}>{entries.filter(entry=>entry.activity).length}</Text></View></View></Panel>{entries.map(({character,activity})=>{const active=character.id===state.character?.id;return <Panel key={character.id} accentColor={active?equipmentColors.selectedLine:undefined}><View style={s.row}><View style={s.copy}><View style={s.nameRow}><Text style={s.name}>{character.name}</Text>{active&&<Text style={s.active}>ACTIVE CHARACTER</Text>}</View><Text style={s.meta}>{character.classId} · Level {character.level}</Text></View>{!active&&<GameButton compact title="Switch" tone="secondary" onPress={()=>onSwitch(character.id)}/>}</View><View style={s.activityRow}><View style={[s.dot,activity?s.dotOn:s.dotIdle]}/><View style={s.copy}><Text style={activity?[s.activity,activityTone(activity.kind,s)]:s.idle}>{activity?activityLabel(activity):'Idle'}</Text>{activity?<><Text style={s.target}>{activityName(activity)}</Text><Text style={s.meta}>Running for {elapsed(activity.startedAtMs,now)}</Text></>:<Text style={s.meta}>No activity is currently running.</Text>}</View></View></Panel>})}{onCreate&&<GameButton title="Create another character" tone="secondary" onPress={onCreate}/>}</ScrollView>;
}

function activityTone(kind:ActiveActivity['kind'],s:ReturnType<typeof makeStyles>){return kind==='combat'?s.combatTone:kind==='training'?s.trainingTone:kind==='faith'?s.faithTone:s.gatheringTone}

function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},heading:{...typography.hero,color:C.text},intro:{...typography.body,color:C.muted,lineHeight:21},summary:{flexDirection:'row',gap:spacing.xl},summaryLabel:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:1},summaryValue:{...typography.title,color:C.text},activePanel:{borderColor:equipmentColors.selectedLine},row:{flexDirection:'row',alignItems:'center',gap:spacing.sm},nameRow:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:spacing.sm},copy:{flex:1,minWidth:0},name:{...typography.title,color:C.text},active:{...typography.caption,color:equipmentColors.selectedLine,fontWeight:'900',letterSpacing:.7},meta:{...typography.caption,color:C.muted,marginTop:2},activityRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm,marginTop:spacing.md,paddingTop:spacing.md,borderTopWidth:1,borderColor:C.line},dot:{width:10,height:10,borderRadius:5},dotOn:{backgroundColor:C.good},dotIdle:{backgroundColor:C.disabled},activity:{...typography.bodyStrong,color:C.good},combatTone:{color:C.bad},gatheringTone:{color:equipmentColors.goldSoft},trainingTone:{color:C.info},faithTone:{color:C.special},idle:{...typography.bodyStrong,color:C.muted},target:{...typography.bodyStrong,color:equipmentColors.goldSoft,marginTop:2}});}
