import {useGameLanguage} from '../i18n/GameLanguageProvider';
import {companionContent,companionMessage,companionTranslator,companionLabel,companionError} from '../i18n/companions';
import {useMemo,useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import {bestiaryProjection,type BestiaryStatus} from '../core/bestiary-v40';
import {SearchField} from '../components/SearchField';
import {GameButton} from '../components/GameButton';
import {radii,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {monsterMasteryGuidance} from '../core/monster-mastery-presentation';
import {ItemArtwork} from '../components/ItemArtwork';
import {itemDef} from '../content/items';
import {v33EquipmentMaterialLabel} from '../core/equipment-loot-v33';

export function BestiaryScreen({state}:{state:GameState}){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
 const language=useGameLanguage(),t=companionTranslator(language),label=(value:string)=>companionLabel(language,value);

 const projection=bestiaryProjection(state),zones=['all',...projection.zones.map(row=>row.zone)] as const;
 const [query,setQuery]=useState(''),[zone,setZone]=useState<string>('all'),[status,setStatus]=useState<'all'|BestiaryStatus>('all'),[filtersOpen,setFiltersOpen]=useState(false);
 const active=(zone==='all'?0:1)+(status==='all'?0:1);
 const rows=useMemo(()=>projection.entries.filter(entry=>(zone==='all'||entry.zone===zone)&&(status==='all'||entry.status===status)&&(!query.trim()||(entry.name+' '+entry.zone).toLowerCase().includes(query.trim().toLowerCase()))),[projection.entries,zone,status,query]);
 return <><ScrollView contentContainerStyle={s.root} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}>
  <Text style={s.kicker}>{t("ADVENTURER'S JOURNAL")}</Text><Text accessibilityRole="header" style={s.heading}>{t("Bestiary")}</Text><Text style={s.sub}>{t("{value0}/{value1} discovered · {value2}% discovery completion. Bestiary progress is projected from canonical monster/mastery data.", {value0: projection.discovered, value1: projection.total, value2: projection.completionPercent})}</Text>
  <SearchField value={query} onChangeText={setQuery} placeholder={t("Search creatures or regions…")} placeholderTextColor={C.muted}/>
  <View style={s.controls}><View style={s.flex}><GameButton title={t("Filters{value0} ▾", {value0: active ? t(" · {value0}", {value0: active}) : ''})} tone={active?'primary':'secondary'} onPress={()=>setFiltersOpen(true)}/></View><Text style={s.count}>{t("{value0} shown", {value0: rows.length})}</Text></View>
  {rows.map(entry=>{const mastery=!entry.boss&&entry.status!=='unknown'?monsterMasteryGuidance(state,entry.id):undefined;return <View key={entry.id} style={s.card}><View style={s.cardHead}><View style={s.flex}><Text style={s.name}>{entry.status==='unknown' ? t("Unknown Creature") : entry.name}</Text><Text style={s.meta}>{t("{value0} · Lv {value1}{value2}", {value0: entry.zone, value1: entry.level, value2: entry.boss ? t(" · Boss") : ''})}</Text></View><Text style={[s.status,entry.status==='unknown'?s.unknown:entry.status==='defeated'?s.defeated:s.discovered]}>{label(entry.status).toLocaleUpperCase(language)}</Text></View>{entry.status!=='unknown'?<><Text style={s.sub}>{entry.boss ? t("Boss entry") : t("Rank {value0}/30 · {value1} mastery points", {value0: mastery?.rank ?? 0, value1: entry.masteryPoints})}</Text>{mastery&&<Text style={s.next}>{mastery.next ? t("Next: Rank {value0} · {value1} · {value2} kills", {value0: mastery.next.rank, value1: companionContent(language,mastery.next.label), value2: mastery.killsToNextMilestone}) : t("All mastery milestones complete")}</Text>}{entry.drops.length?<View style={s.dropStrip}>{entry.drops.slice(0,4).map(drop=>{const item=itemDef(drop.itemId),gearMaterial=v33EquipmentMaterialLabel(drop.itemId);return <View key={drop.itemId} style={s.dropChip}><ItemArtwork itemId={drop.itemId} size={30}/><Text numberOfLines={1} style={s.dropName}>{item.name}</Text>{gearMaterial?<Text numberOfLines={2} style={s.dropUse}>{label(gearMaterial)}</Text>:null}</View>})}</View>:<Text style={s.drops}>{t("No known drops")}</Text>}</>:<Text style={s.sub}>{t("Encounter this creature through normal progression to reveal its entry.")}</Text>}</View>})}
  {!rows.length?<Text style={s.empty}>{t("No Bestiary entries match these filters.")}</Text>:null}
 </ScrollView>
 <Modal visible={filtersOpen} transparent animationType="slide" onRequestClose={()=>setFiltersOpen(false)}><View style={s.backdrop}><Pressable accessibilityRole="button" accessibilityLabel={t("Close filters")} style={StyleSheet.absoluteFill} onPress={()=>setFiltersOpen(false)}/><View style={s.sheet}><Text style={s.sheetTitle}>{t("Bestiary Filters")}</Text><Text style={s.label}>{t("Region")}</Text><ScrollView style={s.optionList} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}>{zones.map(value=><Pressable key={value} onPress={()=>setZone(value)} style={[s.option,zone===value&&s.optionActive]}><Text style={s.optionText}>{zone===value ? '✓ ' : ''}{value==='all' ? t("Any region") : value}</Text></Pressable>)}</ScrollView><Text style={s.label}>{t("Status")}</Text>{(['all','unknown','discovered','defeated'] as const).map(value=><Pressable key={value} onPress={()=>setStatus(value)} style={[s.option,status===value&&s.optionActive]}><Text style={s.optionText}>{status===value ? '✓ ' : ''}{value==='all' ? t("Any status") : label(value)}</Text></Pressable>)}<View style={s.actions}><View style={s.flex}><GameButton title={t("Reset")} tone="secondary" onPress={()=>{setZone('all');setStatus('all')}}/></View><View style={s.flex}><GameButton title={t("Apply Filters")} onPress={()=>setFiltersOpen(false)}/></View></View></View></View></Modal>
 </>;
}
function makeStyles(C:ThemeColors){return StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md,paddingBottom:110},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:1},heading:{...typography.hero,color:C.text},sub:{...typography.body,color:C.muted},controls:{flexDirection:'row',alignItems:'center',gap:10},flex:{flex:1},count:{color:C.muted,fontSize:12},card:{borderWidth:1,borderColor:C.line,borderRadius:radii.lg,backgroundColor:C.panel,padding:spacing.md,gap:6},cardHead:{flexDirection:'row',gap:8,alignItems:'center'},name:{...typography.title,color:C.text},meta:{...typography.caption,color:C.muted},status:{fontSize:9,fontWeight:'900'},unknown:{color:C.muted},discovered:{color:C.info},defeated:{color:C.good},drops:{color:C.accent,fontSize:11},dropStrip:{flexDirection:'row',flexWrap:'wrap',gap:6,marginTop:2},dropChip:{width:82,alignItems:'center',gap:3,padding:5,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},dropName:{fontSize:9,lineHeight:11,color:C.text,textAlign:'center',maxWidth:74},dropUse:{fontSize:7,lineHeight:9,color:C.info,textAlign:'center',fontWeight:'900',letterSpacing:.25,maxWidth:74},next:{fontSize:10,lineHeight:14,color:C.info,fontWeight:'700'},empty:{color:C.muted,textAlign:'center',padding:20},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:C.overlay},sheet:{maxHeight:'82%',backgroundColor:C.bg,borderTopLeftRadius:20,borderTopRightRadius:20,borderWidth:1,borderColor:C.line,padding:spacing.md,gap:8},sheetTitle:{...typography.title,color:C.text},label:{color:C.muted,fontSize:10,fontWeight:'900',letterSpacing:.8,marginTop:5},optionList:{maxHeight:220},option:{minHeight:44,justifyContent:'center',paddingHorizontal:12,borderBottomWidth:1,borderBottomColor:C.line},optionActive:{backgroundColor:C.panel2},optionText:{color:C.text,fontWeight:'700',textTransform:'capitalize'},actions:{flexDirection:'row',gap:8,marginTop:8}});}
