import {useGameLanguage} from '../i18n/GameLanguageProvider';
import {companionUnlockRequirement,companionAttentionText,companionContent,companionMessage,companionTranslator,companionLabel,companionError} from '../i18n/companions';
import {useMemo,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import type {GameCommand} from '../core/game-commands';
import type {CompanionMaterialSourceTarget} from '../core/companion-presentation';
import {companionAttentionSummary} from '../core/companion-attention';
import {CombatCompanionPanel} from '../components/CombatCompanionPanel';
import {MonsterMasteryPanel} from '../components/MonsterMasteryPanel';
import {ExplorationPanel} from '../components/ExplorationPanel';
import {AccountRosterPanel} from '../components/AccountRosterPanel';
import {spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import type {Language} from '../i18n';
import {earlyFeatureUnlockProgress} from '../core/feature-unlocks';

export function CompanionsScreen({state,language: _language,now,onCommand,onCreate,onNavigateSource}:{state:GameState;language:Language;now:number;onCommand:(command:GameCommand)=>Promise<void>;onCreate:()=>void;onNavigateSource?:(source:CompanionMaterialSourceTarget)=>void}){
 const language=useGameLanguage(),t=companionTranslator(language),label=(value:string)=>companionLabel(language,value);

  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const [showOtherProgression,setShowOtherProgression]=useState(false);
 const attention=companionAttentionSummary(state,now),labels=companionAttentionText(language,attention),unlock=earlyFeatureUnlockProgress(state,'companions');
 if(!unlock.unlocked)return <ScrollView contentContainerStyle={s.root} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}><Text style={s.kicker}>{t("COMPANION SANCTUARY")}</Text><Text accessibilityRole="header" style={s.heading}>{t("Companions")}</Text><View style={s.locked}><Text style={s.lockIcon}>◆</Text><Text style={s.lockTitle}>{t("Sanctuary locked")}</Text><Text style={s.intro}>{t("Companions are introduced after the core combat, equipment and gathering loop.")}</Text><Text style={s.lockRequirement}>{t("UNLOCK · {value0}", {value0: companionUnlockRequirement(language,unlock.requirement)})}</Text><Text style={s.lockCopy}>{companionContent(language,unlock.description)}</Text></View><View style={s.other}><Text style={s.otherKicker}>{t("KEEP PROGRESSING")}</Text><Text style={s.otherCopy}>{t("Your normal character progression remains available below while the Sanctuary stays hidden.")}</Text></View><AccountRosterPanel state={state} language={language} onCommand={onCommand} onCreate={onCreate}/><ExplorationPanel state={state} onCommand={onCommand}/><MonsterMasteryPanel state={state}/></ScrollView>;
 return <ScrollView contentContainerStyle={s.root} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}><Text style={s.kicker}>{t("COMPANION SANCTUARY")}</Text><Text accessibilityRole="header" style={s.heading}>{t("Companions")}</Text>{attention.hasAttention?<View style={s.attention}><Text style={s.attentionTitle}>{t("✦ COMPANION ACTIONS READY")}</Text><Text style={s.attentionText}>{labels.slice(0,4).join(' · ')}{labels.length>4 ? t(" · +{value0} more", {value0: (labels.length-4)}) : ''}</Text></View>:null}<CombatCompanionPanel state={state} now={now} onCommand={onCommand} onNavigateSource={onNavigateSource}/><Pressable accessibilityRole="button" accessibilityState={{expanded:showOtherProgression}} accessibilityLabel={t("OTHER CHARACTER PROGRESSION")} onPress={()=>setShowOtherProgression(value=>!value)} style={[s.other,s.otherToggle]}><View style={s.otherCopyBlock}><Text style={s.otherKicker}>{t("OTHER CHARACTER PROGRESSION")}</Text><Text style={s.otherCopy}>{t("Account roster, exploration, class skills and monster mastery remain available below without crowding the Companion tabs.")}</Text></View><Text style={s.otherMark}>{showOtherProgression?'−':'+'}</Text></Pressable>{showOtherProgression?<><AccountRosterPanel state={state} language={language} onCommand={onCommand} onCreate={onCreate}/><ExplorationPanel state={state} onCommand={onCommand}/><MonsterMasteryPanel state={state}/></>:null}</ScrollView>;
}
function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({root:{padding:spacing.md,gap:spacing.md,paddingBottom:spacing.xl},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:1.4},heading:{...typography.hero,color:C.text,marginTop:-6},intro:{...typography.body,color:C.muted,maxWidth:460,marginBottom:spacing.xs},attention:{paddingVertical:spacing.sm,borderBottomWidth:1,borderBottomColor:C.line,gap:2},attentionTitle:{...typography.caption,color:C.good,fontWeight:'700',letterSpacing:.8},attentionText:{...typography.caption,color:C.text},other:{marginTop:spacing.sm,paddingTop:spacing.md,borderTopWidth:1,borderTopColor:C.line,gap:2},otherKicker:{...typography.caption,color:C.muted,fontWeight:'900',letterSpacing:1},otherCopy:{...typography.caption,color:C.muted},otherToggle:{minHeight:58,flexDirection:'row',alignItems:'center',gap:10},otherCopyBlock:{flex:1,minWidth:0,gap:2},otherMark:{fontSize:24,color:C.info,fontWeight:'700'},locked:{alignItems:'center',gap:6,padding:18,borderWidth:1,borderColor:C.line,borderRadius:12,backgroundColor:C.panel2},lockIcon:{fontSize:28,color:C.muted},lockTitle:{...typography.title,color:C.text},lockRequirement:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:.8},lockCopy:{...typography.caption,color:C.muted,textAlign:'center',maxWidth:420}});}
