import {useMemo,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import type {GameCommand} from '../core/game-commands';
import {accountCharacters} from '../core/account-roster';
import {DAILY_SUPPLY_BONUS,DAILY_SUPPLY_BOOST_TYPES,dailySuppliesStatus,dailySupplyActiveLabel,dailySupplyBank,dailySupplyBoostLabel,type DailySupplyBoostType} from '../core/daily-supplies';
import {Panel} from '../components/Panel';
import {GameButton} from '../components/GameButton';
import {ActionFeedback,type FeedbackTone} from '../components/ActionFeedback';
import {StatusPill} from '../components/StatusPill';
import {GameModalHeader,GameModalSurface} from '../components/GameModalSurface';
import {radii,spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';

const milestonePremium:Record<number,number>={7:10,14:20,21:30,28:40};
function duration(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return h?(m?h+'h '+m+'m':h+'h'):Math.max(1,m)+'m';}
function boostShort(type:DailySupplyBoostType){return type==='gathering_yield'?'Gather':type==='crafting_output'?'Craft':type==='skill_xp'?'Skill XP':'Combat XP';}

export function DailySuppliesScreen({state,nowMs=Date.now(),onCommand}:{state:GameState;nowMs?:number;onCommand:(command:GameCommand)=>Promise<void>}){
  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const status=dailySuppliesStatus(state,nowMs),characters=accountCharacters(state),activeCharacter=state.character!,active=dailySupplyActiveLabel(activeCharacter),bank=dailySupplyBank(activeCharacter);
 const claimedInCycle=(state.account.dailySupplies?.totalClaims??0)%28;
 const [selectedId,setSelectedId]=useState(activeCharacter.id),[pickerOpen,setPickerOpen]=useState(false),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState<{message:string;tone:FeedbackTone}|null>(null);
 const selected=characters.find(entry=>entry.character.id===selectedId)?.character??activeCharacter;
 const cells=useMemo(()=>Array.from({length:28},(_,i)=>i+1),[]);
 async function run(command:GameCommand,success:string){setBusy(true);setFeedback(null);try{await onCommand(command);setFeedback({message:success,tone:'success'})}catch(error){setFeedback({message:error instanceof Error?error.message:'Daily Supplies action failed.',tone:'error'})}finally{setBusy(false)}}
 const rewardText=status.reward.kind==='premium'
  ?'Milestone reward · +'+status.reward.amount+' premium currency'
  :'+2h banked · +'+Math.round(DAILY_SUPPLY_BONUS*100)+'% '+dailySupplyBoostLabel(status.reward.type);
 return <><ScrollView contentContainerStyle={s.root}>
  <Text style={s.kicker}>ACCOUNT-WIDE DAILY TRACK</Text><Text accessibilityRole="header" style={s.heading}>Daily Supplies</Text>
  <Text style={s.copy}>One claim per UTC day. Missing a day simply pauses the track—your progress never resets. Normal claims bank two hours of qualifying +10% activity time; milestone claims award account-wide premium currency.</Text>
  <Panel>
   <View style={s.between}><View style={s.flex}><Text style={s.title}>Cycle {status.cycle}</Text><Text style={s.copy}>{claimedInCycle}/28 claims completed</Text></View><StatusPill label={status.canClaim?'READY':'CLAIMED TODAY'} tone={status.canClaim?'good':'muted'}/></View>
   <View style={s.track}>{cells.map(day=>{const claimed=day<=claimedInCycle,milestone=!!milestonePremium[day],today=day===status.dayInTrack;return <View key={day} accessibilityLabel={'Daily Supplies claim '+day+(claimed?', claimed':'')+(milestone?', '+milestonePremium[day]+' premium currency milestone':'')} style={[s.cell,claimed&&s.cellClaimed,milestone&&s.cellMilestone,today&&status.canClaim&&s.cellToday]}><Text style={[s.cellText,claimed&&s.cellTextClaimed]}>{milestone?'◆'+day:day}</Text></View>})}</View>
   <Text style={s.reward}>{rewardText}</Text>
   {status.reward.kind==='boost'?<><Text style={s.label}>RECEIVING CHARACTER</Text><Pressable accessibilityRole="button" accessibilityState={{expanded:pickerOpen}} disabled={busy} onPress={()=>setPickerOpen(true)} style={s.selector}><View style={s.flex}><Text style={s.selectorName}>{selected.name}</Text><Text style={s.selectorMeta}>{selected.classId} · boost charge stays with this character</Text></View><Text style={s.chevron}>⌄</Text></Pressable></>:<Text style={s.copy}>Premium currency is granted to the account; no character selection is needed.</Text>}
   <GameButton title={status.canClaim?'Claim Daily Supplies':'Already claimed today'} disabled={!status.canClaim||busy} onPress={()=>void run({type:'daily_supplies_claim',args:{characterId:selected.id}},status.reward.kind==='premium'?'Claimed +'+status.reward.amount+' premium currency.':'Banked +2h '+dailySupplyBoostLabel(status.reward.type)+' on '+selected.name+'.')}/>
  </Panel>
  <Panel>
   <Text style={s.title}>Current character boosts</Text><Text style={s.copy}>{activeCharacter.name} · activate one banked boost at a time. Its timer runs only while matching activity is being completed, including eligible offline settlement.</Text>
   {active?<View style={s.active}><View style={s.flex}><Text style={s.activeTitle}>+10% {active.label}</Text><Text style={s.copy}>{duration(active.remainingSeconds)} qualifying time remaining</Text></View><StatusPill label="ACTIVE" tone="good"/></View>:<Text style={s.empty}>No Daily Supplies boost is active.</Text>}
   {DAILY_SUPPLY_BOOST_TYPES.map(type=>{const count=bank[type]??0,isActive=active?.type===type;return <View key={type} style={s.boostRow}><View style={s.flex}><Text style={s.boostName}>+10% {dailySupplyBoostLabel(type)}</Text><Text style={s.meta}>{count} banked charge{count===1?'':'s'} · 2h each · {boostShort(type)}</Text></View><View style={s.activate}><GameButton compact selected={isActive} title={isActive?'Active':count?'Activate':'None'} tone={isActive?'primary':'secondary'} disabled={busy||!!active||count<1} onPress={()=>void run({type:'daily_supplies_activate',args:{type}},'+10% '+dailySupplyBoostLabel(type)+' activated.')}/></View></View>})}
  </Panel>
  <Panel><Text style={s.title}>What counts</Text><Text style={s.rule}>• Gathering Yield: stackable resources from gathering actions.</Text><Text style={s.rule}>• Crafting / Processing Output: stackable crafted/processed output; equipment and tools are never duplicated.</Text><Text style={s.rule}>• Skill XP: qualifying skilling, crafting, Alchemy and Faith XP.</Text><Text style={s.rule}>• Combat XP: character XP from normal and Challenge Hunts; it does not boost Gold, drops, pet chances or event/ranking rewards.</Text><Text style={s.rule}>• Daily Supplies do not extend Offline Reserve.</Text></Panel>
  {feedback&&<ActionFeedback message={feedback.message} tone={feedback.tone} reduceMotion={state.settings.reduceMotion}/>}
 </ScrollView>
 <GameModalSurface visible={pickerOpen} reduceMotion={state.settings.reduceMotion} onClose={()=>setPickerOpen(false)} backdropLabel="Close character picker"><GameModalHeader eyebrow="DAILY SUPPLIES" title="Choose receiving character" onClose={()=>setPickerOpen(false)}/><View style={s.characterList}>{characters.map(entry=>{const character=entry.character,selectedRow=character.id===selected.id;return <Pressable key={character.id} accessibilityRole="radio" accessibilityState={{selected:selectedRow}} onPress={()=>{setSelectedId(character.id);setPickerOpen(false)}} style={({pressed})=>[s.characterRow,selectedRow&&s.characterSelected,pressed&&s.pressed]}><View style={s.flex}><Text style={s.selectorName}>{character.name}</Text><Text style={s.selectorMeta}>{character.classId}{character.id===activeCharacter.id?' · current character':''}</Text></View><Text style={selectedRow?s.check:s.meta}>{selectedRow?'✓':'○'}</Text></Pressable>})}</View></GameModalSurface></>;
}

function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md,paddingBottom:110},kicker:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:1},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},copy:{...typography.body,color:C.muted,lineHeight:20},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},flex:{flex:1,minWidth:0},ready:{...typography.caption,color:C.good,fontWeight:'900'},done:{...typography.caption,color:C.muted,fontWeight:'900'},track:{flexDirection:'row',flexWrap:'wrap',gap:5,marginVertical:6},cell:{width:'12.5%',minWidth:31,maxWidth:40,height:32,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:7,backgroundColor:C.bg},cellClaimed:{borderColor:C.good,backgroundColor:C.goodSurface},cellMilestone:{borderColor:equipmentColors.gold},cellToday:{borderWidth:2,borderColor:C.info},cellText:{fontSize:9,color:C.muted,fontWeight:'900'},cellTextClaimed:{color:C.good},reward:{...typography.bodyStrong,color:C.accent},label:{...typography.caption,color:C.muted,fontWeight:'900',letterSpacing:.7},selector:{minHeight:52,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2},selectorName:{...typography.bodyStrong,color:C.text},selectorMeta:{...typography.caption,color:C.muted},chevron:{fontSize:20,color:C.accent},active:{flexDirection:'row',alignItems:'center',gap:8,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:C.good,backgroundColor:C.goodSurface},activeTitle:{...typography.bodyStrong,color:C.good},activeBadge:{...typography.caption,color:C.good,fontWeight:'900'},empty:{...typography.body,color:C.muted,paddingVertical:6},boostRow:{minHeight:56,flexDirection:'row',alignItems:'center',gap:8,paddingVertical:6,borderTopWidth:1,borderTopColor:C.line},boostName:{...typography.bodyStrong,color:C.text},meta:{...typography.caption,color:C.muted},activate:{width:92},rule:{...typography.body,color:C.muted,lineHeight:20},message:{...typography.bodyStrong,color:C.info,textAlign:'center'},characterList:{gap:6,paddingBottom:spacing.sm},characterRow:{minHeight:52,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:10,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel},characterSelected:{borderColor:C.selectionLine,backgroundColor:C.selection},pressed:{opacity:.72},check:{fontSize:18,color:C.good,fontWeight:'900'}});}
