import {IdentityArtwork,GuildCrest} from '../components/SocialIdentity';
import {useState,type ReactNode,useMemo} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {GameState} from '../core/types';
import {spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {formatGameNumber} from '../core/number-format';

const ROSTER=[['Elowen','Dawnkeeper',28,'Leader'],['Brann','Ironwarden',24,'Officer'],['Mira','Wayfinder',21,'Member'],['Tovan','Ravager',19,'Member'],['Sera','Hexweaver',17,'Member']];
type GuildSection='Overview'|'PvE'|'Roster';
type OnlineGuildSection='Directory'|'My Guild'|'Board'|'Projects'|'PvE'|'Hall'|'Chat'|'Customize';

export function GuildScreen({state,onChange,onlineDirectory,onlineManagement,onlineBoard,onlineProjects,onlinePve,onlineHall,onlineChat,onlineCustomize,onlineChatUnread=0,onlineChatMentions=0,online=false}:{online?:boolean;state:GameState;onChange:(next:GameState)=>void;onlineDirectory?:ReactNode;onlineManagement?:ReactNode;onlineBoard?:ReactNode;onlineProjects?:ReactNode;onlinePve?:ReactNode;onlineHall?:ReactNode;onlineChat?:ReactNode;onlineCustomize?:ReactNode;onlineChatUnread?:number;onlineChatMentions?:number}){
  const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
  const [section,setSection]=useState<GuildSection>('Overview'),[onlineSection,setOnlineSection]=useState<OnlineGuildSection>('My Guild');
  if(online)return <ScrollView contentContainerStyle={s.root}><View style={s.onlineHead}><View style={s.flex}><Text style={s.kicker}>GUILD NETWORK</Text><Text accessibilityRole="header" style={s.h}>Guild</Text><Text style={s.sub}>Manage membership, the member Notice Board, Projects, PvE, Chat, Hall progression and Guild identity from one place.</Text></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.onlineTabs}>{(['My Guild','Board','Projects','PvE','Chat','Hall','Directory','Customize'] as const).map(value=><TabChip key={value} label={value} badge={value==='Chat'?Math.max(onlineChatUnread,onlineChatMentions):0} warningBadge={value==='Chat'&&onlineChatMentions>0} selected={onlineSection===value} onPress={()=>setOnlineSection(value)}/>)}</ScrollView>{onlineSection==='Directory'?onlineDirectory:null}{onlineSection==='My Guild'?onlineManagement:null}{onlineSection==='Board'?onlineBoard:null}{onlineSection==='Projects'?onlineProjects:null}{onlineSection==='PvE'?onlinePve:null}{onlineSection==='Chat'?onlineChat:null}{onlineSection==='Hall'?onlineHall:null}{onlineSection==='Customize'?onlineCustomize:null}</ScrollView>;
  const joined=state.account.guildMember,contribution=state.account.guildContribution??0,project=state.account.guildProjectProgress??0,bossHp=state.account.guildBossHp??100000;
  const contribute=()=>onChange({...state,account:{...state.account,guildContribution:contribution+100,guildProjectProgress:Math.min(1000,project+100)}});
  const attack=()=>onChange({...state,account:{...state.account,guildContribution:contribution+50,guildBossHp:Math.max(0,bossHp-5000)}});
  return <ScrollView contentContainerStyle={s.root}>
    <Text accessibilityRole="header" style={s.h}>Guild</Text>
    <View accessibilityRole="tablist" style={s.tabs}>{(['Overview','PvE','Roster'] as const).map(value=><TabChip key={value} label={value==='Roster'?`Roster · ${joined?ROSTER.length:0}`:value} selected={section===value} onPress={()=>setSection(value)}/>)}</View>
    {section==='Overview'&&<><Panel><GuildCrest/><Text style={s.title}>{joined?'The Bloomwardens':'Find your guild'}</Text><Text style={s.sub}>{joined?'A friendly expedition guild focused on steady PvE progress.':'Join a guild to unlock shared projects, guild PvE, and the AFK reserve bonus.'}</Text><GameButton title={joined?'Leave guild':'Join The Bloomwardens'} tone={joined?'danger':'primary'} onPress={()=>onChange({...state,account:{...state.account,guildMember:!joined}})}/></Panel>{onlineDirectory}{onlineManagement}</>}
    {section==='PvE'&&<>{onlinePve}{joined?<><Panel><Text style={s.title}>Weekly PvE project</Text><Text style={s.sub}>{formatGameNumber(project,state.settings.numberMode)}/1,000 restored · You contributed {formatGameNumber(contribution,state.settings.numberMode)}</Text><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,project/10)}%`}]}/></View><GameButton title="Contribute 100" onPress={contribute}/></Panel><Panel><Text style={s.title}>Rootbound Colossus</Text><Text style={s.sub}>{formatGameNumber(bossHp,state.settings.numberMode)} HP remaining</Text><View style={s.track}><View style={[s.bossFill,{width:`${Math.max(0,bossHp/1000)}%`}]}/></View><GameButton title="Attack · 5,000 damage" onPress={attack} disabled={bossHp===0}/></Panel></>:<Panel><Text style={s.title}>Guild membership required</Text><Text style={s.sub}>Join a guild from Overview to participate in weekly projects and bosses.</Text></Panel>}</>}
    {section==='Roster'&&<Panel><Text style={s.title}>Roster · {joined?ROSTER.length:0}</Text>{joined?ROSTER.map(([name,role,level,status])=><View style={s.member} key={name}><IdentityArtwork name={String(name)} className={String(role)}/><View style={s.flex}><Text style={s.memberName}>{name}</Text><Text style={s.sub}>{role} · Level {level}</Text></View><Text style={[s.status,status==='Leader'?s.statusLeader:status==='Officer'?s.statusOfficer:s.statusMember]}>{status}</Text></View>):<Text style={s.sub}>Join a guild to view its members.</Text>}</Panel>}
  </ScrollView>;
}

function TabChip({label,selected,badge=0,warningBadge=false,onPress}:{label:string;selected:boolean;badge?:number;warningBadge?:boolean;onPress:()=>void}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);return <Pressable accessibilityRole="tab" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.tabChip,selected&&s.tabChipSelected,warningBadge&&s.tabChipWarning,pressed&&s.pressed]}><View style={s.tabLabel}><Text style={[s.tabText,selected&&s.tabTextSelected]}>{label}</Text>{badge>0?<View style={[s.tabBadge,warningBadge&&s.tabBadgeWarning]}><Text style={s.tabBadgeText}>{badge>99?'99+':badge}</Text></View>:null}</View></Pressable>}
function makeStyles(C:ThemeColors){return StyleSheet.create({root:{padding:spacing.md,gap:10,paddingBottom:100},onlineHead:{flexDirection:'row',alignItems:'flex-start',gap:8},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:.9},onlineTabs:{gap:5,paddingVertical:2,paddingRight:8},h:{...typography.hero,color:C.text},tabs:{flexDirection:'row',flexWrap:'wrap',gap:6},tabChip:{minHeight:40,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.panel2},tabChipSelected:{borderColor:C.selectionLine,backgroundColor:C.selection},tabChipWarning:{borderColor:C.warning},tabLabel:{flexDirection:'row',alignItems:'center',gap:5},tabText:{fontSize:10.5,fontWeight:'800',color:C.muted},tabTextSelected:{color:C.text},tabBadge:{minWidth:17,height:17,paddingHorizontal:4,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:C.notification},tabBadgeWarning:{backgroundColor:C.warning},tabBadgeText:{fontSize:7.5,color:C.notificationText,fontWeight:'900'},pressed:{opacity:.76},title:{...typography.title,color:C.text},sub:{...typography.body,color:C.muted},track:{height:10,backgroundColor:C.panel2,borderRadius:5,overflow:'hidden',marginVertical:10},fill:{height:10,backgroundColor:C.accent},bossFill:{height:10,backgroundColor:C.bad},member:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:8,borderBottomWidth:1,borderBottomColor:C.line},avatar:{width:38,height:38,borderRadius:19,backgroundColor:C.panel2,borderWidth:1,borderColor:C.accent,alignItems:'center',justifyContent:'center'},avatarText:{color:C.accent,fontWeight:'900',fontSize:18},flex:{flex:1},memberName:{color:C.text,fontWeight:'900'},status:{fontSize:12,fontWeight:'700'},statusLeader:{color:C.accent},statusOfficer:{color:C.info},statusMember:{color:C.good}});}
