import {SearchField} from '../components/SearchField';
import {useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameState,ItemStack} from '../core/types';
import {ItemDef,itemDef} from '../content/items';
import {InventoryFilter,InventorySort,recoveryAmount,transferAmount,transferError,visibleStacks} from '../core/inventory-view';
import {claimOverflowToBank,effectiveStats,StorageLocation,storageUpgradePreview,usedSlots} from '../core/game';
import {ItemCard} from '../components/ItemCard';
import {ConfirmModal} from '../components/ConfirmModal';
import {EmptyState} from '../components/EmptyState';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {C,equipmentColors,spacing,typography} from '../theme/theme';
import {EquipmentPreview} from '../components/EquipmentPreview';
import {previewEquipment} from '../core/equipment-preview';
import {GEAR_RARITIES} from '../core/item-rarity';
import {formatGameNumber} from '../core/number-format';
import {ot} from '../i18n';
import {enhancedGearStats,gearEnhancement,gemSocketCapacity,hasEnhancement} from '../core/equipment-enhancement';

type Pending={kind:'sell'|'salvage'|'deposit';item:ItemDef;quantity:number}|null;
export function InventoryScreen({state,onEquip,onFood,onEat,onSell,onSalvage,onDeposit,onDepositMaterials,onUpgradeStorage,onWithdraw,onOverflow}:{state:GameState;onEquip:(id:string)=>void;onFood:(id:string)=>void;onEat:(id:string)=>void;onSell:(id:string)=>void;onSalvage:(id:string)=>void;onDeposit:(id:string,quantity:number)=>void;onDepositMaterials:()=>void;onUpgradeStorage:(location:StorageLocation)=>void;onWithdraw:(id:string,quantity:number)=>void;onOverflow:()=>void}){
  const [pending,setPending]=useState<Pending>(null),[location,setLocation]=useState<'inventory'|'bank'>('inventory');
  const [query,setQuery]=useState(''),[filter,setFilter]=useState<InventoryFilter>('all'),[sort,setSort]=useState<InventorySort>('name');
  const [quantity,setQuantity]=useState<1|10|'all'>(1);
  const [error,setError]=useState('');
  const [expandedItem,setExpandedItem]=useState<string|null>(null);
  const [previewId,setPreviewId]=useState<string|null>(null);
  const [showStorage,setShowStorage]=useState(false),[showFilters,setShowFilters]=useState(false);
  const run=(action:()=>void)=>{try{action();setError('')}catch(e){setError(e instanceof Error?e.message:'Action failed. Please try again.')}};
  const confirm=()=>{if(!pending)return;run(()=>pending.kind==='deposit'?onDeposit(pending.item.id,pending.quantity):pending.kind==='sell'?onSell(pending.item.id):onSalvage(pending.item.id));setPending(null)};
  const stacks=visibleStacks(state[location].stacks,query,filter,sort);
  const renderStack=(stack:ItemStack)=>{
    const item=itemDef(stack.itemId),equippedId=item.slot?state.character?.equipment[item.slot]:undefined,carried=location==='inventory';
    const amount=transferAmount(stack.quantity,quantity),selectedFood=state.character?.equippedFoodId===item.id,enhancement=item.type==='gear'?gearEnhancement(state,item.id):undefined,enhancementProtected=item.type==='gear'&&hasEnhancement(state,item.id);
    return <ItemCard expanded={expandedItem===location+':'+item.id} onToggle={()=>setExpandedItem(value=>value===location+':'+item.id?null:location+':'+item.id)} key={`${location}:${item.id}`} item={item} quantity={stack.quantity} equipped={equippedId?itemDef(equippedId):undefined} upgradeRank={enhancement?.rank} socketed={enhancement?.gemIds.length} socketCapacity={item.type==='gear'?gemSocketCapacity(item.id):0} enhancementProtected={enhancementProtected} displayStats={item.type==='gear'?enhancedGearStats(state,item.id):undefined} equippedDisplayStats={equippedId?enhancedGearStats(state,equippedId):undefined} selectedFood={selectedFood} healAmount={recoveryAmount(state,item.id)} transferQuantity={amount} transferIssue={transferError(state,item.id,amount,location)} numberMode={state.settings.numberMode}
      onPreview={item.type==='gear'?()=>run(()=>{previewEquipment(state,item.id);setPreviewId(item.id)}):undefined}
      onEquip={carried&&item.type==='gear'?()=>run(()=>onEquip(item.id)):undefined} onSelectFood={carried&&item.type==='food'?()=>run(()=>onFood(item.id)):undefined} onEat={carried&&item.type==='food'?()=>run(()=>onEat(item.id)):undefined}
      onSell={carried&&item.value>0&&!enhancementProtected?()=>setPending({kind:'sell',item,quantity:1}):undefined} onSalvage={carried&&item.salvage&&!enhancementProtected?()=>setPending({kind:'salvage',item,quantity:1}):undefined}
      onDeposit={carried?()=>selectedFood?setPending({kind:'deposit',item,quantity:amount}):run(()=>onDeposit(item.id,amount)):undefined} onWithdraw={!carried?()=>run(()=>onWithdraw(item.id,amount)):undefined}/>;
  };
  const foodWarning=pending?.item.id===state.character?.equippedFoodId?' This is your selected auto-eat food. Only food carried in Inventory can be consumed in combat.':'';
  const message=pending?.kind==='sell'?`Sell 1 for ${pending.item.value} gold. This cannot be undone.${foodWarning}`:pending?.kind==='deposit'?`Move ${pending.quantity}× ${pending.item.name} to Bank?${foodWarning}`:pending?.item.salvage?`Destroy 1 item for ${pending.item.salvage.quantity}× ${itemDef(pending.item.salvage.itemId).name}.`:'';
  const remaining=claimOverflowToBank(state).overflow.stacks.reduce((sum,item)=>sum+item.quantity,0);
  const overflowCount=state.overflow.stacks.reduce((sum,item)=>sum+item.quantity,0);
  const inventoryUpgrade=storageUpgradePreview(state,'inventory'),bankUpgrade=storageUpgradePreview(state,'bank');
  return <><EquipmentPreview state={state} itemId={previewId} onClose={()=>setPreviewId(null)}/><ScrollView contentContainerStyle={s.root} keyboardShouldPersistTaps="handled">
    <Text accessibilityRole="header" style={s.h}>Inventory</Text>
    <View style={s.recovery}><Text style={s.label}>RECOVERY</Text><Text style={s.sub}>Health {state.character!.currentHp}/{effectiveStats(state).hp} · Auto-eat: {state.character?.equippedFoodId?itemDef(state.character.equippedFoodId).name:'None'}</Text><Text style={s.sub}>Carried auto-eat portions: {state.inventory.stacks.find(item=>item.itemId===state.character?.equippedFoodId)?.quantity??0}</Text></View>
    <View style={s.chipRow}>{(['inventory','bank'] as const).map(value=><ChoiceChip key={value} label={`${value==='inventory'?'Inventory':'Bank'} · ${usedSlots(state[value].stacks)}/${state[value].capacity}`} selected={location===value} onPress={()=>setLocation(value)}/>)}</View>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:showStorage}} onPress={()=>setShowStorage(value=>!value)} style={s.disclosure}><View style={s.flex}><Text style={s.disclosureTitle}>STORAGE MANAGEMENT</Text><Text style={s.sub}>Bulk deposit and capacity upgrades</Text></View><Text style={s.disclosureMark}>{showStorage?'−':'+'}</Text></Pressable>
    {showStorage&&<Panel><Text style={s.sub}>Inventory travels with this character. Bank storage is shared by every character on the account.</Text>{location==='inventory'&&<GameButton title="Deposit all materials" tone="secondary" disabled={!state.inventory.stacks.some(entry=>itemDef(entry.itemId).type==='material')} onPress={()=>run(onDepositMaterials)}/>}<View style={s.row}><View style={s.flex}><Text style={s.upgradeLabel}>INVENTORY · {state.inventory.capacity} SLOTS</Text><GameButton title={inventoryUpgrade?`Upgrade to ${inventoryUpgrade.capacity} · ${formatGameNumber(inventoryUpgrade.cost,state.settings.numberMode)}g`:'Inventory maxed'} disabled={!inventoryUpgrade} tone="secondary" onPress={()=>run(()=>onUpgradeStorage('inventory'))}/></View><View style={s.flex}><Text style={s.upgradeLabel}>BANK · {state.bank.capacity} SLOTS</Text><GameButton title={bankUpgrade?`Upgrade to ${bankUpgrade.capacity} · ${formatGameNumber(bankUpgrade.cost,state.settings.numberMode)}g`:'Bank maxed'} disabled={!bankUpgrade} tone="secondary" onPress={()=>run(()=>onUpgradeStorage('bank'))}/></View></View></Panel>}
    <Text style={s.sub}>{location==='inventory'?'Carried items available during adventures.':'Bank materials are available for crafting, but food must be withdrawn for combat.'}</Text>
    <SearchField accessibilityLabel="Search stored items" placeholder="Search items…" placeholderTextColor={C.muted} value={query} onChangeText={setQuery}/>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:showFilters}} onPress={()=>setShowFilters(value=>!value)} style={s.disclosure}><View style={s.flex}><Text style={s.disclosureTitle}>FILTERS & DISPLAY</Text><Text style={s.sub}>{filter==='all'?'All items':filter} · sorted by {sort} · transfer {quantity}</Text></View><Text style={s.disclosureMark}>{showFilters?'−':'+'}</Text></Pressable>
    {showFilters&&<Panel><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rarityLegend}>{GEAR_RARITIES.map(rarity=><View key={rarity.id} style={[s.rarityKey,{borderColor:rarity.color,backgroundColor:rarity.surface}]}><Text style={[s.rarityKeyText,{color:rarity.color}]}>{rarity.symbol} {rarity.label}</Text></View>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chipRow}>{(['all','gear','tool','food','material'] as const).map(value=><ChoiceChip key={value} label={value} selected={filter===value} onPress={()=>setFilter(value)}/>)}</ScrollView><Text style={s.label}>SORT BY</Text><View style={s.chipRow}>{(['name','quantity','value'] as const).map(value=><ChoiceChip key={value} label={value==='value'?'Unit value':value} selected={sort===value} onPress={()=>setSort(value)}/>)}</View><Text style={s.label}>TRANSFER QUANTITY</Text><View style={s.chipRow}>{([1,10,'all'] as const).map(value=><ChoiceChip key={value} label={String(value)} selected={quantity===value} onPress={()=>setQuantity(value)}/>)}</View></Panel>}
    {!!error&&<Text accessibilityRole="alert" style={s.errorText}>{error}</Text>}
    <Text style={s.sub}>{stacks.length} matching stacks · {Math.max(0,state[location].capacity-usedSlots(state[location].stacks))} free slots</Text>
    {stacks.length?stacks.map(renderStack):<><EmptyState title="No items to show" message="Try another storage tab or clear the search and category filter."/><GameButton title="Clear filters" tone="secondary" onPress={()=>{setQuery('');setFilter('all')}}/></>}
    {overflowCount>0&&<Panel><Text style={s.title}>{ot(state.settings.language,'overflow.title')} · {overflowCount}</Text><Text style={s.warning}>{ot(state.settings.language,'overflow.body')}</Text>{state.overflow.stacks.map((stack,index)=><Text key={`${stack.itemId}:${index}`} style={s.sub}>{stack.quantity}× {itemDef(stack.itemId).name}</Text>)}{state.overflow.expiresAtMs!==null&&<Text style={s.warning}>Recorded expiry: {new Date(state.overflow.expiresAtMs).toLocaleString()}</Text>}<GameButton title={ot(state.settings.language,'overflow.move',{count:overflowCount-remaining})} disabled={remaining===overflowCount} onPress={()=>run(onOverflow)}/>{remaining>0&&<Text style={s.sub}>{ot(state.settings.language,'overflow.remain',{count:remaining})}</Text>}</Panel>}
  </ScrollView><ConfirmModal visible={pending!==null} title={`${pending?.kind==='deposit'?'Bank':pending?.kind==='sell'?'Sell':'Salvage'} ${pending?.item.name??'item'}?`} message={message} confirmLabel={pending?.kind==='deposit'?'Deposit':pending?.kind==='sell'?'Sell 1':'Salvage 1'} danger={pending?.kind!=='deposit'} onConfirm={confirm} onCancel={()=>setPending(null)}/></>;
}
function ChoiceChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.chip,selected&&s.chipSelected,pressed&&s.pressed]}><Text style={[s.chipText,selected&&s.chipTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
const s=StyleSheet.create({recovery:{gap:4,padding:spacing.md,borderWidth:1,borderColor:C.line,borderRadius:10,backgroundColor:C.panel},root:{padding:spacing.lg,gap:spacing.md},h:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},sub:{...typography.body,color:C.muted},warning:{...typography.body,color:C.warning},errorText:{...typography.body,color:C.bad,padding:spacing.sm,borderWidth:1,borderColor:C.bad,borderRadius:8,backgroundColor:'#2a1b20'},label:{...typography.caption,color:C.accent,fontWeight:'700'},upgradeLabel:{...typography.caption,color:C.muted,fontWeight:'700',marginBottom:spacing.xs},disclosure:{minHeight:60,flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingHorizontal:spacing.md,borderWidth:1,borderColor:C.line,borderRadius:10,backgroundColor:C.panel},disclosureTitle:{...typography.caption,color:C.accent,fontWeight:'700',letterSpacing:.8},disclosureMark:{width:28,color:C.accent,fontSize:25,textAlign:'center'},rarityLegend:{gap:spacing.sm,paddingRight:spacing.md},rarityKey:{minHeight:32,justifyContent:'center',borderWidth:1,borderRadius:99,paddingHorizontal:spacing.sm},rarityKeyText:{...typography.caption,fontWeight:'700'},row:{flexDirection:'row',gap:spacing.sm},chipRow:{flexDirection:'row',flexWrap:'wrap',gap:6},chip:{minHeight:38,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},chipSelected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},chipText:{fontSize:12,color:C.muted,fontWeight:'700'},chipTextSelected:{color:'#d9f3ff'},pressed:{opacity:.76},flex:{flex:1},input:{minHeight:48,paddingHorizontal:spacing.md,borderRadius:10,borderWidth:1,borderColor:C.line,color:C.text,backgroundColor:C.panel,fontSize:16}});
