import {useMemo,useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import type {GameState} from '../core/types';
import {COLLECTIBLES,COLLECTIBLE_TARGET_LABELS} from '../content/collectibles';
import {collectibleJournal,collectionBonusBreakdown,selectCollectible} from '../core/collectibles';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {radii,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {GameModalHeader,GameModalSurface} from '../components/GameModalSurface';
import {petArtSource} from '../theme/pet-art';

const PETS=COLLECTIBLES.filter(row=>row.kind==='pet');
const pct=(bps:number)=>(bps/100).toFixed(2)+'%';
const viewOptions=['All','Owned','Locked','Core','Event','Legacy'] as const;
const regionOptions=['All regions','Asterfall','Sunscar','Frostmarch','Ashlands'] as const;
type ViewFilter=typeof viewOptions[number];
type RegionFilter=typeof regionOptions[number];

export function PetBonusOverviewScreen({state,onChange}:{state:GameState;onChange:(next:GameState)=>void}){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]),{width,fontScale}=useWindowDimensions(),singleColumn=width<360||fontScale>=1.25;
 const [pickerOpen,setPickerOpen]=useState(false),[viewFilter,setViewFilter]=useState<ViewFilter>('All'),[regionFilter,setRegionFilter]=useState<RegionFilter>('All regions'),[filterOpen,setFilterOpen]=useState<'view'|'region'|null>(null),[showBonusHelp,setShowBonusHelp]=useState(false);
 const journal=collectibleJournal(state,PETS),owned=journal.filter(row=>row.owned),active=journal.find(row=>row.selected),breakdown=collectionBonusBreakdown(state,PETS);
 const corePets=journal.filter(row=>row.collectionGroup==='core'),eventPets=journal.filter(row=>row.collectionGroup==='event'),legacyPets=journal.filter(row=>row.collectionGroup==='legacy');
 const visiblePets=journal.filter(row=>{
  if(viewFilter==='Owned'&&!row.owned)return false;if(viewFilter==='Locked'&&row.owned)return false;
  if(viewFilter==='Core'&&row.collectionGroup!=='core')return false;if(viewFilter==='Event'&&row.collectionGroup!=='event')return false;if(viewFilter==='Legacy'&&row.collectionGroup!=='legacy')return false;
  if(regionFilter!=='All regions'&&row.region!==regionFilter)return false;return true;
 });
 const choose=(id?:string)=>{onChange(selectCollectible(state,'pet',id));setPickerOpen(false)};
 return <><ScrollView contentContainerStyle={s.root}>
  <Text style={s.kicker}>ACCOUNT BONUSES</Text><Text accessibilityRole="header" style={s.heading}>Pet Bonus Overview</Text><Text style={s.sub}>Every owned pet contributes its small account-wide passive bonus. Your selected pet also contributes its stronger active bonus.</Text>
  <View style={[s.columns,singleColumn&&s.columnsStack]}>
   <Panel><Text style={s.title}>Account-Wide Pet Bonus</Text><Text style={s.sub}>Passive bonus from all owned pets</Text>{breakdown.length?breakdown.map(row=><View key={row.target} style={s.bonusRow}><Text style={s.bonusLabel}>{COLLECTIBLE_TARGET_LABELS[row.target]}</Text><Text style={s.passive}>+{pct(row.ownedAppliedBps)}</Text></View>):<Text style={s.empty}>Collect your first pet to begin building passive bonuses.</Text>}</Panel>
  <Panel><Text style={s.title}>Active Pet Bonus</Text>{active?<><View style={s.activeCard}><View style={s.petGlyph}>{petArtSource(active.id)?<Image source={petArtSource(active.id)} resizeMode="contain" style={s.petArt}/>:<Text style={s.petGlyphText}>◆</Text>}</View><View style={s.flex}><Text style={s.activeName}>{active.name}</Text><Text style={s.sub}>{COLLECTIBLE_TARGET_LABELS[active.target]}</Text><Text style={s.activeBonus}>+{pct(active.activeBps)} active</Text><Text style={s.passive}>+{pct(active.ownedBps)} owned passive</Text></View></View></>:<Text style={s.empty}>No active pet selected.</Text>}<GameButton title="Change Active Pet ▾" disabled={!owned.length} onPress={()=>setPickerOpen(true)}/></Panel>
  </View>
  <Panel><Text style={s.title}>Bonus Categories</Text><View style={s.grid}>{breakdown.map(row=><View key={row.target} style={s.category}><Text style={s.categoryTitle}>{COLLECTIBLE_TARGET_LABELS[row.target]}</Text><Text style={s.categoryValue}>+{pct(row.appliedBps)}</Text><Text style={s.categoryMeta}>{pct(row.ownedAppliedBps)} passive{row.activeAppliedBps?' · '+pct(row.activeAppliedBps)+' active':''}</Text>{row.suppressedBps>0?<Text style={s.cap}>Cap applied: {pct(row.suppressedBps)} suppressed</Text>:null}</View>)}</View></Panel>
  <Pressable accessibilityRole="button" accessibilityState={{expanded:showBonusHelp}} accessibilityLabel="How pet bonuses work" onPress={()=>setShowBonusHelp(value=>!value)} style={[s.helpDisclosure,showBonusHelp&&s.helpDisclosureOpen]}><View style={s.flex}><Text style={s.helpDisclosureTitle}>HOW PET BONUSES WORK</Text><Text style={s.helpDisclosureText}>Passive + active bonuses, duplicate-family rules and caps</Text></View><Text style={s.helpDisclosureMark}>{showBonusHelp?'−':'+'}</Text></Pressable>{showBonusHelp?<Panel><Text style={s.sub}>Owned pets contribute +0.50% in their authored bonus family. Selecting one pet adds its active bonus of at least +2.00%. Duplicate-family and category caps prevent collection bonuses from growing without limit.</Text></Panel>:null}
  <View style={s.progressRow}><View style={s.progressCard}><Text style={s.progressTitle}>Core Pets</Text><Text style={s.progressValue}>{corePets.filter(row=>row.owned).length} / {corePets.length}</Text></View><View style={s.progressCard}><Text style={s.progressTitle}>Event Pets</Text><Text style={s.progressValue}>{eventPets.filter(row=>row.owned).length} / {eventPets.length}</Text></View><View style={s.progressCard}><Text style={s.progressTitle}>Legacy</Text><Text style={s.progressValue}>{legacyPets.filter(row=>row.owned).length} / {legacyPets.length}</Text></View></View>
  <Panel><Text style={s.title}>Pet Collection · {owned.length}/{journal.length}</Text><Text style={s.sub}>{visiblePets.length} shown</Text><View style={[s.filterRow,singleColumn&&s.filterRowStack]}><View style={[s.filterWrap,singleColumn&&s.filterWrapStack,filterOpen==='view'&&s.filterWrapOpen]}><Pressable accessibilityRole="button" accessibilityState={{expanded:filterOpen==='view'}} onPress={()=>setFilterOpen(filterOpen==='view'?null:'view')} style={s.filterButton}><Text style={s.filterText}>View: {viewFilter}</Text><Text style={s.filterArrow}>{filterOpen==='view'?'▴':'▾'}</Text></Pressable>{filterOpen==='view'?<View style={s.filterMenu}>{viewOptions.map(option=><Pressable key={option} onPress={()=>{setViewFilter(option);setFilterOpen(null)}} style={[s.filterOption,option===viewFilter&&s.filterOptionActive]}><Text style={[s.filterText,option===viewFilter&&s.filterTextActive]}>{option}</Text></Pressable>)}</View>:null}</View><View style={[s.filterWrap,singleColumn&&s.filterWrapStack,filterOpen==='region'&&s.filterWrapOpen]}><Pressable accessibilityRole="button" accessibilityState={{expanded:filterOpen==='region'}} onPress={()=>setFilterOpen(filterOpen==='region'?null:'region')} style={s.filterButton}><Text style={s.filterText}>Region: {regionFilter}</Text><Text style={s.filterArrow}>{filterOpen==='region'?'▴':'▾'}</Text></Pressable>{filterOpen==='region'?<View style={s.filterMenu}>{regionOptions.map(option=><Pressable key={option} onPress={()=>{setRegionFilter(option);setFilterOpen(null)}} style={[s.filterOption,option===regionFilter&&s.filterOptionActive]}><Text style={[s.filterText,option===regionFilter&&s.filterTextActive]}>{option}</Text></Pressable>)}</View>:null}</View></View>{visiblePets.length?<View style={s.petGrid}>{visiblePets.map(row=><Pressable key={row.id} disabled={!row.owned} accessibilityRole="button" accessibilityState={{disabled:!row.owned,selected:row.selected}} onPress={()=>row.owned&&choose(row.id)} style={[s.petCard,singleColumn&&s.petCardStack,row.selected&&s.petSelected,!row.owned&&s.locked]}><View style={s.petMini}>{petArtSource(row.id)?<Image source={petArtSource(row.id)} resizeMode="contain" style={s.petArt}/>:<Text style={s.petGlyphText}>{row.owned?'◆':'?'}</Text>}</View><View style={s.petTagRow}><Text style={s.petTag}>{(row.collectionGroup??'legacy').toUpperCase()}</Text>{row.selected?<Text style={s.activeTag}>ACTIVE</Text>:null}</View><Text numberOfLines={1} style={s.petName}>{row.name}</Text>{row.region||row.rarity?<Text numberOfLines={1} style={s.petContext}>{[row.region,row.rarity].filter(Boolean).join(' · ')}</Text>:null}<Text numberOfLines={2} style={s.petSource}>{row.source}</Text><Text numberOfLines={2} style={s.petBonus}>{COLLECTIBLE_TARGET_LABELS[row.target]} · +{pct(row.activeBps)} active</Text><Text style={s.petMeta}>{row.owned?'+'+pct(row.ownedBps)+' passive':'LOCKED'}</Text></Pressable>)}</View>:<Text style={s.empty}>No pets match these filters.</Text>}</Panel>
 </ScrollView>
 <GameModalSurface visible={pickerOpen} reduceMotion={state.settings.reduceMotion} onClose={()=>setPickerOpen(false)} backdropLabel="Close active pet picker">
  <GameModalHeader eyebrow="PET COLLECTION" title="Choose Active Pet" onClose={()=>setPickerOpen(false)}/>
  <Text style={s.sub}>The pet remains owned account-wide; this only changes the stronger active bonus.</Text>
  <ScrollView style={s.pickerList} contentContainerStyle={s.pickerContent} keyboardShouldPersistTaps="handled">{owned.map(row=><Pressable key={row.id} accessibilityRole="radio" accessibilityState={{selected:row.selected}} onPress={()=>choose(row.id)} style={[s.option,row.selected&&s.optionActive]}><View style={s.petMini}>{petArtSource(row.id)?<Image source={petArtSource(row.id)} resizeMode="contain" style={s.petArt}/>:<Text style={s.petGlyphText}>◆</Text>}</View><View style={s.flex}><Text style={s.petName}>{row.name}</Text><Text style={s.petMeta}>{COLLECTIBLE_TARGET_LABELS[row.target]} · +{pct(row.activeBps)} active</Text></View><Text style={s.check}>{row.selected?'✓':''}</Text></Pressable>)}</ScrollView>
  <GameButton title="Clear Active Pet" tone="secondary" onPress={()=>choose(undefined)}/>
 </GameModalSurface>
 </>;
}
function makeStyles(C:ThemeColors){return StyleSheet.create({
 root:{padding:spacing.lg,gap:spacing.md,paddingBottom:110},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:1.1},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},sub:{...typography.body,color:C.muted},
 columns:{gap:spacing.md},columnsStack:{gap:spacing.sm},
 helpDisclosure:{minHeight:52,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel},helpDisclosureOpen:{borderColor:C.info,backgroundColor:C.infoSurface},helpDisclosureTitle:{...typography.caption,color:C.info,fontWeight:'900',letterSpacing:.8},helpDisclosureText:{...typography.caption,color:C.muted},helpDisclosureMark:{width:28,color:C.info,fontSize:24,textAlign:'center',fontWeight:'700'},
 bonusRow:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.line},bonusLabel:{color:C.text,fontWeight:'800'},passive:{color:C.info,fontWeight:'900'},
 activeCard:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:8},petGlyph:{width:72,height:72,borderWidth:2,borderColor:C.accent,borderRadius:14,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},petGlyphText:{color:C.accent,fontSize:28,fontWeight:'900'},petArt:{width:'100%',height:'100%'},activeName:{color:C.text,fontSize:19,fontWeight:'900'},activeBonus:{color:C.good,fontSize:16,fontWeight:'900'},flex:{flex:1,minWidth:0},empty:{color:C.muted,paddingVertical:14},
 grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},category:{flexGrow:1,flexBasis:140,minWidth:140,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2,padding:10},categoryTitle:{color:C.text,fontWeight:'800'},categoryValue:{color:C.accent,fontSize:20,fontWeight:'900',marginTop:4},categoryMeta:{color:C.muted,fontSize:10,marginTop:3},cap:{color:C.warning,fontSize:9,marginTop:3},
 progressRow:{flexDirection:'row',flexWrap:'wrap',gap:8},progressCard:{flexGrow:1,flexBasis:'30%',minWidth:100,borderWidth:1,borderColor:C.line,borderRadius:radii.lg,backgroundColor:C.panel,padding:12},progressTitle:{color:C.text,fontWeight:'800'},progressValue:{color:C.accent,fontSize:20,fontWeight:'900',marginTop:4},
 filterRow:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8,zIndex:10},filterRowStack:{flexDirection:'column'},filterWrap:{width:'48%',minWidth:128,position:'relative',zIndex:2},filterWrapStack:{width:'100%',minWidth:0},filterWrapOpen:{zIndex:20},filterButton:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:6,paddingHorizontal:10,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.bg},filterText:{fontSize:10,color:C.text,fontWeight:'800'},filterTextActive:{color:C.accent},filterArrow:{fontSize:11,color:C.accent},filterMenu:{position:'absolute',top:46,left:0,right:0,padding:4,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel,zIndex:50},filterOption:{minHeight:44,justifyContent:'center',paddingHorizontal:8,borderRadius:6},filterOptionActive:{backgroundColor:C.selection},
 petGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10,zIndex:1},petCard:{width:'48%',minWidth:142,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2,padding:8},petCardStack:{width:'100%',minWidth:0},petSelected:{borderColor:C.accent,backgroundColor:C.accentSurface},locked:{opacity:.45},petMini:{height:70,borderRadius:8,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'},petTagRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:4,marginTop:6},petTag:{fontSize:8,color:C.muted,fontWeight:'900',letterSpacing:.6},activeTag:{fontSize:8,color:C.good,fontWeight:'900',letterSpacing:.6},petName:{color:C.text,fontSize:10,fontWeight:'800',marginTop:5},petContext:{color:C.info,fontSize:9,fontWeight:'700',marginTop:2},petSource:{color:C.muted,fontSize:9,lineHeight:12,marginTop:4},petBonus:{color:C.accent,fontSize:9,fontWeight:'800',marginTop:5},petMeta:{color:C.muted,fontSize:9,marginTop:2},
 pickerList:{maxHeight:460},pickerContent:{gap:6,paddingVertical:4},option:{minHeight:64,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:C.line,borderRadius:radii.md,padding:8,backgroundColor:C.panel},optionActive:{borderColor:C.accent,backgroundColor:C.selection},check:{color:C.good,fontSize:20,fontWeight:'900'}
});}
