import {useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import {COLLECTIBLES,COLLECTIBLE_TARGET_LABELS} from '../content/collectibles';
import {collectibleJournal,collectionBonusBreakdown,selectCollectible} from '../core/collectibles';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {C,radii,spacing,typography} from '../theme/theme';

const PETS=COLLECTIBLES.filter(row=>row.kind==='pet');
const pct=(bps:number)=>(bps/100).toFixed(2)+'%';

export function PetBonusOverviewScreen({state,onChange}:{state:GameState;onChange:(next:GameState)=>void}){
 const [pickerOpen,setPickerOpen]=useState(false);
 const journal=collectibleJournal(state,PETS),owned=journal.filter(row=>row.owned),active=journal.find(row=>row.selected),breakdown=collectionBonusBreakdown(state,PETS);
 const eventPets=journal.filter(row=>/Harvestwake|event|festival/i.test(row.source)),corePets=journal.filter(row=>!eventPets.some(event=>event.id===row.id));
 const choose=(id?:string)=>{onChange(selectCollectible(state,'pet',id));setPickerOpen(false)};
 return <><ScrollView contentContainerStyle={s.root}>
  <Text style={s.kicker}>ACCOUNT BONUSES</Text><Text accessibilityRole="header" style={s.heading}>Pet Bonus Overview</Text><Text style={s.sub}>Every owned pet contributes its small account-wide passive bonus. Your selected pet also contributes its stronger active bonus.</Text>
  <View style={s.columns}>
   <Panel><Text style={s.title}>Account-Wide Pet Bonus</Text><Text style={s.sub}>Passive bonus from all owned pets</Text>{breakdown.length?breakdown.map(row=><View key={row.target} style={s.bonusRow}><Text style={s.bonusLabel}>{COLLECTIBLE_TARGET_LABELS[row.target]}</Text><Text style={s.passive}>+{pct(row.ownedAppliedBps)}</Text></View>):<Text style={s.empty}>Collect your first pet to begin building passive bonuses.</Text>}</Panel>
   <Panel><Text style={s.title}>Active Pet Bonus</Text>{active?<><View style={s.activeCard}><View style={s.petGlyph}><Text style={s.petGlyphText}>◆</Text></View><View style={s.flex}><Text style={s.activeName}>{active.name}</Text><Text style={s.sub}>{COLLECTIBLE_TARGET_LABELS[active.target]}</Text><Text style={s.activeBonus}>+{pct(active.activeBps)} active</Text><Text style={s.passive}>+{pct(active.ownedBps)} owned passive</Text></View></View></>:<Text style={s.empty}>No active pet selected.</Text>}<GameButton title="Change Active Pet ▾" disabled={!owned.length} onPress={()=>setPickerOpen(true)}/></Panel>
  </View>
  <Panel><Text style={s.title}>Bonus Categories</Text><View style={s.grid}>{breakdown.map(row=><View key={row.target} style={s.category}><Text style={s.categoryTitle}>{COLLECTIBLE_TARGET_LABELS[row.target]}</Text><Text style={s.categoryValue}>+{pct(row.appliedBps)}</Text><Text style={s.categoryMeta}>{pct(row.ownedAppliedBps)} passive{row.activeAppliedBps?' · '+pct(row.activeAppliedBps)+' active':''}</Text>{row.suppressedBps>0?<Text style={s.cap}>Cap applied: {pct(row.suppressedBps)} suppressed</Text>:null}</View>)}</View></Panel>
  <Panel><Text style={s.title}>How Pet Bonuses Work</Text><Text style={s.sub}>Owned pets contribute +0.50% in their authored bonus family. Selecting one pet adds its active bonus of at least +2.00%. Duplicate-family and category caps prevent collection bonuses from growing without limit.</Text></Panel>
  <View style={s.progressRow}><View style={s.progressCard}><Text style={s.progressTitle}>Core Pets</Text><Text style={s.progressValue}>{corePets.filter(row=>row.owned).length} / {corePets.length}</Text></View><View style={s.progressCard}><Text style={s.progressTitle}>Event Pets</Text><Text style={s.progressValue}>{eventPets.filter(row=>row.owned).length} / {eventPets.length}</Text></View></View>
  <Panel><Text style={s.title}>Your Pets · {owned.length}/{journal.length}</Text><View style={s.petGrid}>{journal.map(row=><Pressable key={row.id} disabled={!row.owned} onPress={()=>row.owned&&choose(row.id)} style={[s.petCard,row.selected&&s.petSelected,!row.owned&&s.locked]}><View style={s.petMini}><Text style={s.petGlyphText}>{row.owned?'◆':'?'}</Text></View><Text numberOfLines={1} style={s.petName}>{row.name}</Text><Text style={s.petMeta}>{row.owned?row.selected?'ACTIVE':'+'+pct(row.ownedBps):'LOCKED'}</Text></Pressable>)}</View></Panel>
 </ScrollView>
 <Modal visible={pickerOpen} transparent animationType="slide" onRequestClose={()=>setPickerOpen(false)}><View style={s.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setPickerOpen(false)}/><View style={s.sheet}><Text style={s.title}>Choose Active Pet</Text><Text style={s.sub}>The pet remains owned account-wide; this only changes the stronger active bonus.</Text>{owned.map(row=><Pressable key={row.id} onPress={()=>choose(row.id)} style={[s.option,row.selected&&s.optionActive]}><View style={s.petMini}><Text style={s.petGlyphText}>◆</Text></View><View style={s.flex}><Text style={s.petName}>{row.name}</Text><Text style={s.petMeta}>{COLLECTIBLE_TARGET_LABELS[row.target]} · +{pct(row.activeBps)} active</Text></View><Text style={s.check}>{row.selected?'✓':''}</Text></Pressable>)}<GameButton title="Clear Active Pet" tone="secondary" onPress={()=>choose(undefined)}/></View></View></Modal>
 </>;
}
const s=StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md,paddingBottom:110},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:1.1},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},sub:{...typography.body,color:C.muted},columns:{gap:spacing.md},bonusRow:{minHeight:42,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:C.line},bonusLabel:{color:C.text,fontWeight:'800'},passive:{color:C.info,fontWeight:'900'},activeCard:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:8},petGlyph:{width:72,height:72,borderWidth:2,borderColor:C.accent,borderRadius:14,backgroundColor:C.panel2,alignItems:'center',justifyContent:'center'},petGlyphText:{color:C.accent,fontSize:28,fontWeight:'900'},activeName:{color:C.text,fontSize:19,fontWeight:'900'},activeBonus:{color:C.good,fontSize:16,fontWeight:'900'},flex:{flex:1,minWidth:0},empty:{color:C.muted,paddingVertical:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},category:{width:'48%',minWidth:140,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2,padding:10},categoryTitle:{color:C.text,fontWeight:'800'},categoryValue:{color:C.accent,fontSize:20,fontWeight:'900',marginTop:4},categoryMeta:{color:C.muted,fontSize:10,marginTop:3},cap:{color:C.warning,fontSize:9,marginTop:3},progressRow:{flexDirection:'row',gap:8},progressCard:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:radii.lg,backgroundColor:C.panel,padding:12},progressTitle:{color:C.text,fontWeight:'800'},progressValue:{color:C.accent,fontSize:20,fontWeight:'900',marginTop:4},petGrid:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:8},petCard:{width:'31%',minWidth:92,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2,padding:7},petSelected:{borderColor:C.accent,backgroundColor:'#272417'},locked:{opacity:.45},petMini:{height:52,borderRadius:8,backgroundColor:'#101923',alignItems:'center',justifyContent:'center'},petName:{color:C.text,fontSize:10,fontWeight:'800',marginTop:5},petMeta:{color:C.muted,fontSize:9,marginTop:2},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'#0008'},sheet:{maxHeight:'82%',backgroundColor:C.bg,borderTopWidth:1,borderColor:C.line,borderTopLeftRadius:20,borderTopRightRadius:20,padding:spacing.lg,gap:8},option:{minHeight:64,flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:C.line,borderRadius:radii.md,padding:8,backgroundColor:C.panel},optionActive:{borderColor:C.accent,backgroundColor:C.panel2},check:{color:C.good,fontSize:20,fontWeight:'900'}});
