import {useMemo} from 'react';
import {QuestReward} from '../components/QuestReward';
import {UiIcon} from '../components/UiIcon';
import {ActionFeedback} from '../components/ActionFeedback';
import {newlyConfirmedIds} from '../core/visual-feedback';
import {SearchField} from '../components/SearchField';
import {useEffect,useRef,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameState} from '../core/types';
import {QUESTS,QUEST_ACTS,type QuestAct} from '../content/quests';
import {JournalFilter,QuestDestination,journalEntries,questDestination} from '../core/quest-journal';
import {Panel} from '../components/Panel';
import {GameButton} from '../components/GameButton';
import {StatBar} from '../components/StatBar';
import {C,equipmentColors,spacing,typography} from '../theme/theme';
import {useGameTheme,type ThemePalette} from '../theme/app-theme';
import {QUEST_RARITIES,SeasonalPeriod,SeasonalQuest,seasonalQuestBoard} from '../core/seasonal-quests';
import {weeklyOrderBoardForState} from '../core/long-term-progression-runtime';
import type {WeeklyOrder} from '../core/weekly-orders-v41';
import {WORLD_ZONES} from '../content/world-map';

export function QuestScreen({state,onClaim,onClaimContract,onNavigate}:{state:GameState;onClaim:(id:string)=>void;onClaimContract:(period:SeasonalPeriod,id:string)=>void;onNavigate:(destination:QuestDestination)=>void}){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);
  const [filter,setFilter]=useState<JournalFilter>('current'),[query,setQuery]=useState('');
  const [notice,setNotice]=useState(''),[error,setError]=useState('');
  const [showBoard,setShowBoard]=useState(true),[showContracts,setShowContracts]=useState(false);
  const confirmed=useRef({characterId:state.character?.id,quests:state.quests.filter(q=>q.status==='claimed').map(q=>q.questId),contracts:state.account.seasonalContractClaimIds??[]});
  useEffect(()=>{
    const next={characterId:state.character?.id,quests:state.quests.filter(q=>q.status==='claimed').map(q=>q.questId),contracts:state.account.seasonalContractClaimIds??[]};
    const previous=confirmed.current;confirmed.current=next;
    if(previous.characterId!==next.characterId){setNotice('');setError('');return;}
    const chapters=newlyConfirmedIds(previous.quests,next.quests),contracts=newlyConfirmedIds(previous.contracts,next.contracts);
    if(chapters.length){setNotice(chapters.map(id=>'Rewards received: '+(QUESTS.find(q=>q.id===id)?.name??'chapter')+'.').join(' '));setError('');}
    else if(contracts.length){setNotice('Contract rewards received.');setError('');}
  },[state.quests,state.account.seasonalContractClaimIds,state.character?.id]);
  const entries=journalEntries(state,filter,query);
  const daily=seasonalQuestBoard(state,'daily'),weekly=seasonalQuestBoard(state,'weekly'),monthly=seasonalQuestBoard(state,'monthly'),contractBoard=weeklyOrderBoardForState(state),pendingBoardRewards=(state.account.weeklyOrderPendingRewards??[]).filter(row=>row.weekKey===contractBoard.weekKey);
  const claimed=QUESTS.filter(def=>state.quests.some(q=>q.questId===def.id&&q.status==='claimed')).length;
  const ready=state.quests.filter(q=>q.status==='complete').length;
  const currentDef=QUESTS.find(def=>state.quests.find(q=>q.questId===def.id)?.status!=='claimed')??QUESTS[QUESTS.length-1],currentAct=QUEST_ACTS[currentDef.act];
  function claim(id:string){
    try{setNotice('');setError('');onClaim(id)}
    catch(e){setError(e instanceof Error?e.message:'Unable to claim this quest.');setNotice('')}
  }
  return <ScrollView contentContainerStyle={s.root} keyboardShouldPersistTaps="handled">
    <View style={s.journalHeading}><UiIcon name="quests" size={40}/><Text accessibilityRole="header" style={[s.h,s.flex]}>Asterfall Journal</Text></View>
    <Panel><Text style={s.actEyebrow}>ACT {roman(currentAct.act)} · {currentAct.name.toUpperCase()}</Text><Text style={s.title}>{claimed===QUESTS.length?'Asterfall campaign complete':currentAct.subtitle}</Text><StatBar reduceMotion={state.settings.reduceMotion} label="Chapters claimed" current={claimed} max={QUESTS.length}/><Text style={s.sub}>{claimed===QUESTS.length?'Every chapter reward has been claimed. You can revisit the story, hunts, crafting, and equipment upgrades.':`${ready} reward${ready===1?'':'s'} ready to claim. Claim each chapter to unlock the next story beat.`}</Text></Panel>
    <ScrollView accessibilityRole="tablist" horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{(['current','all','claimed','locked'] as const).map(value=><FilterChip key={value} label={`${value==='current'?'Current':value==='all'?'All':value==='claimed'?'Completed':'Locked'} · ${value==='current'?entries.length:value==='all'?QUESTS.length:value==='claimed'?claimed:state.quests.filter(quest=>quest.status==='locked').length}`} selected={filter===value} onPress={()=>setFilter(value)}/>)}</ScrollView>
    <SearchField accessibilityLabel="Search quests" placeholder="Search story, locations or objectives…" placeholderTextColor={T.muted} value={query} onChangeText={setQuery}/>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:showBoard}} onPress={()=>setShowBoard(value=>!value)} style={s.disclosure}><View style={s.flex}><Text style={s.chapter}>CONTRACT BOARD · {contractBoard.weekKey}</Text><Text style={s.title}>{contractBoard.orders.length} Hunt, Work, Regional & Threat jobs</Text></View><Text style={s.disclosureMark}>{showBoard?'−':'+'}</Text></Pressable>
    {showBoard&&<Panel><Text style={s.sub}>These jobs track exact activities during the current UTC week. Hunt named monsters, fill profession orders, stabilize a region, and unlock mastery-based Threat Bounties.</Text><Text style={s.contractHint}>Resets {new Date(contractBoard.endsAtMs).toISOString().slice(0,10)} at 00:00 UTC · {pendingBoardRewards.length} reward grant{pendingBoardRewards.length===1?'':'s'} queued</Text><WeeklyOrderRows orders={contractBoard.orders} reduceMotion={state.settings.reduceMotion} onNavigate={onNavigate}/>{contractBoard.completionClaimed?<Text style={s.claimed}>✓ Full Contract Board completion reward queued</Text>:<Text style={s.contractHint}>{contractBoard.orders.filter(order=>order.progress>=order.target).length}/{contractBoard.orders.length} weekly jobs complete</Text>}</Panel>}
    <Pressable accessibilityRole="button" accessibilityState={{expanded:showContracts}} onPress={()=>setShowContracts(value=>!value)} style={s.disclosure}><View style={s.flex}><Text style={s.chapter}>CLASS CHALLENGES</Text><Text style={s.title}>{daily.length+weekly.length+monthly.length} personal daily, weekly & monthly objectives</Text></View><Text style={s.disclosureMark}>{showContracts?'−':'+'}</Text></Pressable>
    {showContracts&&<Panel><Text style={s.sub}>Class-aligned personal challenges award progressively stronger rarity caches.</Text><ContractRows state={state} label={`DAILY · ${daily[0]?.className??''}`} quests={daily} onClaim={onClaimContract}/><ContractRows state={state} label="WEEKLY" quests={weekly} onClaim={onClaimContract}/><ContractRows state={state} label="MONTHLY" quests={monthly} onClaim={onClaimContract}/></Panel>}
    {!!notice&&<ActionFeedback message={notice} reduceMotion={state.settings.reduceMotion}/>}{!!error&&<ActionFeedback message={error} tone="error" reduceMotion={state.settings.reduceMotion}/>}
    {entries.length===0&&<Panel><Text style={s.title}>No matching chapters</Text><Text style={s.sub}>{filter==='current'&&claimed===QUESTS.length?'You have completed this journal. View Completed to revisit it.':'Try another search or view all chapters.'}</Text><GameButton title="Show all chapters" onPress={()=>{setQuery('');setFilter('all')}}/></Panel>}
    {entries.map(({def,quest,chapter,remaining,previous})=>{
      const destination=questDestination(def);
      return <Panel key={def.id} accentColor={quest.status==='complete'?T.good:undefined} accentSurface={quest.status==='complete'?'#14272A':undefined}>
        <Text style={s.chapter}>ACT {roman(def.act)} · CHAPTER {chapter} · {quest.status==='complete'?'REWARD READY':quest.status==='claimed'?'CLAIMED':quest.status.toUpperCase()}</Text>
        <View style={s.locationRow}><Text style={s.title}>{def.name}</Text><Text style={s.location}>{def.location}</Text></View>
        <View style={s.storyBlock}><Text style={s.storyLabel}>STORY</Text><Text style={s.storyText}>{def.story}</Text></View>
        <Text style={s.objectiveLabel}>OBJECTIVE</Text><Text style={s.sub}>{def.description}</Text>
        {quest.status==='locked'?<Text style={s.hint}>Claim “{previous??'the previous chapter'}” to unlock this objective. Progress is not tracked while locked.</Text>:<><StatBar reduceMotion={state.settings.reduceMotion} label="Objective progress" current={Math.min(def.required,quest.progress)} max={def.required}/><Text style={s.hint}>{quest.status==='claimed'?'Reward already collected':quest.status==='complete'?'Objective complete — claim your reward':`${remaining} remaining`}</Text></>}
        <QuestReward gold={def.rewardGold} itemId={def.rewardItemId} quantity={def.rewardItemQty??1} label={quest.status==='claimed'?'Rewards collected':'Chapter rewards'}/>
        {quest.status==='active'&&<><Text style={s.sub}>{destination.hint}</Text><GameButton title={destination.label} tone="secondary" onPress={()=>onNavigate(destination)}/></>}
        {quest.status==='complete'&&<GameButton title="Claim chapter rewards" onPress={()=>claim(def.id)}/>}
      </Panel>;
    })}
  </ScrollView>;
}
function roman(act:QuestAct){return act===1?'I':act===2?'II':'III'}
function FilterChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.filterChip,selected&&s.filterChipSelected,pressed&&s.pressed]}><Text style={[s.filterText,selected&&s.filterTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
function WeeklyOrderRows({orders,reduceMotion,onNavigate}:{orders:WeeklyOrder[];reduceMotion:boolean;onNavigate:(destination:QuestDestination)=>void}){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);
 const kindLabel={hunt:'HUNT ORDER',profession:'WORK ORDER',regional:'REGIONAL PROBLEM',threat:'THREAT BOUNTY'} as const;
 return <>{orders.map(order=>{const region=WORLD_ZONES.find(zone=>zone.id===order.regionId),ready=order.progress>=order.target,remaining=Math.max(0,order.target-order.progress),destination:QuestDestination=order.kind==='profession'?{tab:'Skills',label:'Open skills & crafting',hint:`Complete ${order.source.label} to advance this Work Order.`}:{tab:'World',zoneId:order.regionId,label:order.kind==='threat'?'Open Challenge Hunts':order.kind==='hunt'?'Open hunt region':'Open region',hint:order.kind==='threat'?`Use the exact ${order.challengeId??'required'} Challenge Hunt against ${order.source.label}; normal hunts do not count.`:order.kind==='hunt'?`Hunt ${order.source.label} in ${region?.name??'its region'}.`:`Combat and gathering in ${region?.name??'this region'} advance this Regional Problem.`},tone=order.kind==='regional'?T.warning:order.kind==='hunt'?T.bad:order.kind==='threat'?'#b88ae3':T.info;return <View key={order.id} style={s.seasonQuest}><View style={s.contractHead}><Text style={s.seasonName}>{order.title}</Text><View style={[s.rarity,{borderColor:tone}]}><Text style={[s.rarityText,{color:tone}]}>{kindLabel[order.kind]}</Text></View></View><Text style={s.sub}>{order.brief??(order.kind==='regional'?`Resolve mounting trouble across ${region?.name??order.source.label} through normal regional activity.`:order.kind==='threat'?`Complete the ${order.challengeId??'required'} Challenge Hunt against ${order.source.label}.`:order.kind==='hunt'?`Bring down ${order.source.label} for the posted hunt.`:`Fulfil the posted ${order.professionKind??'profession'} order: ${order.source.label}.`)}</Text><StatBar reduceMotion={reduceMotion} label={`${order.progress}/${order.target} progress`} current={order.progress} max={order.target}/><Text style={order.claimed?s.claimed:s.contractHint}>{order.claimed?'✓ Complete · reward queued':ready?'Complete · reward processing':`${remaining} remaining · ${order.reward.label}`}</Text>{!ready&&<GameButton title={destination.label} tone="secondary" onPress={()=>onNavigate(destination)}/>}</View>})}</>;
}
function ContractRows({state,label,quests,onClaim}:{state:GameState;label:string;quests:SeasonalQuest[];onClaim:(period:SeasonalPeriod,id:string)=>void}){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);return <><Text style={s.seasonLabel}>{label}</Text>{quests.map(quest=>{const rarity=QUEST_RARITIES[quest.rarity],claimed=(state.account.seasonalContractClaimIds??[]).includes(quest.id),ready=quest.progress>=quest.required;return <View key={quest.id} style={s.seasonQuest}><View style={s.contractHead}><Text style={s.seasonName}>{quest.name}</Text><View style={[s.rarity,{borderColor:rarity.color}]}><Text style={[s.rarityText,{color:rarity.color}]}>{rarity.label.toUpperCase()}</Text></View></View><Text style={s.sub}>{quest.description}</Text><StatBar reduceMotion={state.settings.reduceMotion} label={`${quest.progress}/${quest.required} progress · ${quest.tag.toUpperCase()}`} current={quest.progress} max={quest.required}/><QuestReward gold={quest.rewardGold} xp={quest.rewardXp} itemId={quest.rewardItemId} quantity={quest.rewardItemQty} label={rarity.cache}/>{claimed?<Text style={s.claimed}>✓ Cache claimed</Text>:ready?<GameButton title={`Claim ${rarity.label} cache`} onPress={()=>onClaim(quest.period,quest.id)}/>:<Text style={s.contractHint}>{quest.required-quest.progress} progress remaining</Text>}</View>})}</>}
const makeStyles=(T:ThemePalette)=>StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},journalHeading:{flexDirection:'row',alignItems:'center',gap:12},h:{...typography.hero,color:T.text},title:{...typography.title,color:T.text},sub:{...typography.body,color:T.muted},chapter:{...typography.caption,color:T.accent,fontWeight:'900'},actEyebrow:{...typography.caption,color:T.accentSoft,fontWeight:'900',letterSpacing:1},locationRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'baseline',justifyContent:'space-between',gap:spacing.sm},location:{...typography.caption,color:T.accentSoft,fontWeight:'900'},storyBlock:{gap:4,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:T.info,backgroundColor:T.panel2,borderRadius:6},storyLabel:{...typography.caption,color:T.info,fontWeight:'900',letterSpacing:.8},storyText:{...typography.body,color:T.text,lineHeight:20},objectiveLabel:{...typography.caption,color:T.muted,fontWeight:'900',letterSpacing:.7},hint:{...typography.body,color:T.info},reward:{...typography.bodyStrong,color:T.accent},notice:{...typography.bodyStrong,color:T.good},error:{...typography.body,color:T.bad},disclosure:{minHeight:68,flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.md,borderWidth:1,borderColor:T.line,borderRadius:10,backgroundColor:T.panel},disclosureMark:{width:28,color:T.accent,fontSize:25,textAlign:'center'},flex:{flex:1,minWidth:0},filterChip:{minHeight:38,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:T.line,borderRadius:99,backgroundColor:T.bg},filterChipSelected:{borderColor:T.action,backgroundColor:T.actionSurface},filterText:{fontSize:12,color:T.muted,fontWeight:'700'},filterTextSelected:{color:T.actionText},pressed:{opacity:.76},seasonLabel:{...typography.caption,color:T.accent,fontWeight:'900',letterSpacing:1,marginTop:spacing.sm},seasonQuest:{gap:spacing.xs,borderTopWidth:1,borderColor:T.line,paddingTop:spacing.sm},contractHead:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:spacing.sm},seasonName:{...typography.bodyStrong,color:T.text,flexGrow:1,flexBasis:180},rarity:{borderWidth:1,borderRadius:99,paddingHorizontal:spacing.sm,paddingVertical:2},rarityText:{fontSize:10,fontWeight:'900'},cache:{...typography.caption,fontWeight:'800'},claimed:{...typography.caption,color:T.good,fontWeight:'900'},contractHint:{...typography.caption,color:T.muted},row:{flexDirection:'row',gap:spacing.sm},input:{minHeight:48,borderWidth:1,borderColor:T.line,borderRadius:10,paddingHorizontal:spacing.md,color:T.text,backgroundColor:T.panel,fontSize:16}});
