import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {GuildTaggedPlayerName} from '../components/GuildTaggedPlayerName';
import {RANKING_BOARDS,RANKING_GROUPS,rankingValueLabel,type RankingBoardId,type RankingBoardSnapshot,type RankingGroup} from '../core/rankings';
import {rankingsClient,rankingsOnlineConfigured} from '../online/rankings-client';
import {C,equipmentColors,spacing,typography} from '../theme/theme';
import {useGameTheme,type ThemePalette} from '../theme/app-theme';
export function RankingsScreen(){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);const[group,setGroup]=useState<RankingGroup>('Account'),[board,setBoard]=useState<RankingBoardId>('profession_total'),[snapshot,setSnapshot]=useState<RankingBoardSnapshot|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const boards=useMemo(()=>RANKING_BOARDS.filter(row=>row.group===group),[group]);useEffect(()=>{if(!boards.some(row=>row.id===board))setBoard(boards[0].id)},[group]);
 async function load(){if(!rankingsOnlineConfigured){setSnapshot(null);setError('Rankings require the authenticated online server.');return}setLoading(true);setError('');try{setSnapshot(await rankingsClient.board(board))}catch(e){setSnapshot(null);setError(e instanceof Error?e.message:'Could not load Rankings.')}finally{setLoading(false)}}useEffect(()=>{void load()},[board]);const definition=RANKING_BOARDS.find(row=>row.id===board)!;
 return <ScrollView contentContainerStyle={s.root}><Text style={s.kicker}>RANKINGS</Text><Text style={s.heading}>VELDRYN Rankings</Text><Panel><Text style={s.title}>Prestige, not power</Text><Text style={s.copy}>Rankings are read-only, server-calculated, and provide no exclusive combat power. Account boards respect <Text style={s.accentWord}>Public Profile</Text> visibility and block relationships.</Text></Panel><Text style={s.filterLabel}>SCOPE</Text><View style={s.wrap}>{RANKING_GROUPS.map(value=><ChoiceChip key={value} label={`${value} · ${RANKING_BOARDS.filter(row=>row.group===value).length}`} selected={group===value} onPress={()=>setGroup(value)}/>)}</View><Text style={s.filterLabel}>BOARD</Text><View style={s.wrap}>{boards.map(value=><ChoiceChip key={value.id} label={value.name} selected={board===value.id} onPress={()=>setBoard(value.id)}/>)}</View><Panel><View style={s.header}><View style={s.flex}><Text style={s.title}>{snapshot?.title??definition.name}</Text><Text style={s.copy}>{snapshot?.description??definition.description}</Text></View><GameButton title="Refresh" tone="secondary" disabled={loading} onPress={()=>void load()}/></View>{loading&&<ActivityIndicator/>}{error&&<Text style={s.warning}>{error}</Text>}{snapshot?.self&&<View style={s.self}><Text style={s.kicker}>YOUR STANDING</Text><Text style={s.value}>{snapshot.self.listed&&snapshot.self.rank?`#${snapshot.self.rank} · `:''}{rankingValueLabel(board,snapshot.self.value)}</Text>{snapshot.self.reason&&<Text style={s.warning}>{snapshot.self.reason}</Text>}</View>}</Panel>{snapshot?.entries.map(entry=><Panel key={`${entry.rank}-${entry.displayName}-${entry.value}`}><View style={s.row}><Text style={s.rank}>#{entry.rank}</Text><View style={s.flex}><GuildTaggedPlayerName name={`${entry.displayName}${entry.isSelf?' · YOU':''}`} guildTag={entry.guildTag} tagColorId={entry.guildTagColorId} style={s.name}/>{entry.subtitle&&<Text style={s.copy}>{entry.subtitle}</Text>}{entry.detail&&<Text style={s.detail}>{entry.detail}</Text>}</View><Text style={s.gold}>{rankingValueLabel(board,entry.value)}</Text></View></Panel>)}{snapshot&&!loading&&!snapshot.entries.length&&<Panel><Text style={s.copy}>No eligible ranked entries yet.</Text></Panel>}</ScrollView>}
function ChoiceChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){
 const T=useGameTheme(),s=useMemo(()=>makeStyles(T),[T]);return <Pressable accessibilityRole="tab" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.chip,selected&&s.chipSelected,pressed&&s.pressed]}><Text style={[s.chipText,selected&&s.chipTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
const makeStyles=(T:ThemePalette)=>StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},kicker:{...typography.caption,color:T.accentSoft,fontWeight:'900',letterSpacing:1.2},heading:{...typography.hero,color:T.text},title:{...typography.title,color:T.text},copy:{...typography.body,color:T.muted,lineHeight:21},filterLabel:{...typography.caption,color:T.accentSoft,fontWeight:'900',letterSpacing:1},wrap:{flexDirection:'row',flexWrap:'wrap',gap:6},chip:{minHeight:38,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:T.line,borderRadius:99,backgroundColor:T.bg},chipSelected:{borderColor:T.action,backgroundColor:T.actionSurface},chipText:{fontSize:12,color:T.muted,fontWeight:'700'},chipTextSelected:{color:T.actionText},pressed:{opacity:.76},accentWord:{color:T.accentSoft,fontWeight:'900'},header:{flexDirection:'row',gap:spacing.sm,alignItems:'flex-start'},flex:{flex:1,minWidth:0},warning:{...typography.bodyStrong,color:T.warning},self:{marginTop:spacing.md,padding:spacing.md,borderWidth:1,borderColor:T.accent},value:{...typography.title,color:T.text},row:{flexDirection:'row',alignItems:'center',gap:spacing.md},rank:{...typography.title,color:T.accent,width:52},name:{...typography.bodyStrong,color:T.text},detail:{...typography.caption,color:T.good},gold:{...typography.bodyStrong,color:T.accentSoft,textAlign:'right'}});
