import {useEffect,useMemo,useState} from 'react';
import {ActivityIndicator,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {RANKING_BOARDS,RANKING_GROUPS,rankingValueLabel,type RankingBoardId,type RankingBoardSnapshot,type RankingGroup} from '../core/rankings';
import {rankingsClient,rankingsOnlineConfigured} from '../online/rankings-client';
import {C,equipmentColors,spacing,typography} from '../theme/theme';
export function RankingsScreen(){const[group,setGroup]=useState<RankingGroup>('Account'),[board,setBoard]=useState<RankingBoardId>('profession_total'),[snapshot,setSnapshot]=useState<RankingBoardSnapshot|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const boards=useMemo(()=>RANKING_BOARDS.filter(row=>row.group===group),[group]);useEffect(()=>{if(!boards.some(row=>row.id===board))setBoard(boards[0].id)},[group]);
 async function load(){if(!rankingsOnlineConfigured){setSnapshot(null);setError('Rankings require the authenticated online server.');return}setLoading(true);setError('');try{setSnapshot(await rankingsClient.board(board))}catch(e){setSnapshot(null);setError(e instanceof Error?e.message:'Could not load Rankings.')}finally{setLoading(false)}}useEffect(()=>{void load()},[board]);const definition=RANKING_BOARDS.find(row=>row.id===board)!;
 return <ScrollView contentContainerStyle={s.root}><Text style={s.kicker}>RANKINGS</Text><Text style={s.heading}>VELDRYN Rankings</Text><Panel><Text style={s.title}>Prestige, not power</Text><Text style={s.copy}>Rankings are read-only, server-calculated, and provide no exclusive combat power. Account boards respect Public Profile visibility and block relationships.</Text></Panel><View style={s.wrap}>{RANKING_GROUPS.map(value=><View key={value} style={s.button}><GameButton title={value} tone={group===value?'primary':'secondary'} onPress={()=>setGroup(value)}/></View>)}</View><View style={s.wrap}>{boards.map(value=><View key={value.id} style={s.button}><GameButton title={value.name} tone={board===value.id?'primary':'secondary'} onPress={()=>setBoard(value.id)}/></View>)}</View><Panel><View style={s.header}><View style={s.flex}><Text style={s.title}>{snapshot?.title??definition.name}</Text><Text style={s.copy}>{snapshot?.description??definition.description}</Text></View><GameButton title="Refresh" tone="secondary" disabled={loading} onPress={()=>void load()}/></View>{loading&&<ActivityIndicator/>}{error&&<Text style={s.warning}>{error}</Text>}{snapshot?.self&&<View style={s.self}><Text style={s.kicker}>YOUR STANDING</Text><Text style={s.value}>{snapshot.self.listed&&snapshot.self.rank?`#${snapshot.self.rank} · `:''}{rankingValueLabel(board,snapshot.self.value)}</Text>{snapshot.self.reason&&<Text style={s.warning}>{snapshot.self.reason}</Text>}</View>}</Panel>{snapshot?.entries.map(entry=><Panel key={`${entry.rank}-${entry.displayName}-${entry.value}`}><View style={s.row}><Text style={s.rank}>#{entry.rank}</Text><View style={s.flex}><Text style={s.name}>{entry.displayName}{entry.isSelf?' · YOU':''}</Text>{entry.subtitle&&<Text style={s.copy}>{entry.subtitle}</Text>}{entry.detail&&<Text style={s.detail}>{entry.detail}</Text>}</View><Text style={s.gold}>{rankingValueLabel(board,entry.value)}</Text></View></Panel>)}{snapshot&&!loading&&!snapshot.entries.length&&<Panel><Text style={s.copy}>No eligible ranked entries yet.</Text></Panel>}</ScrollView>}
const s=StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},kicker:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:1.2},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},copy:{...typography.body,color:C.muted,lineHeight:21},wrap:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs},button:{minWidth:120,flexGrow:1},header:{flexDirection:'row',gap:spacing.sm,alignItems:'flex-start'},flex:{flex:1,minWidth:0},warning:{...typography.bodyStrong,color:C.warning},self:{marginTop:spacing.md,padding:spacing.md,borderWidth:1,borderColor:C.accent},value:{...typography.title,color:C.text},row:{flexDirection:'row',alignItems:'center',gap:spacing.md},rank:{...typography.title,color:C.accent,width:52},name:{...typography.bodyStrong,color:C.text},detail:{...typography.caption,color:C.good},gold:{...typography.bodyStrong,color:equipmentColors.goldSoft,textAlign:'right'}});
