import {useSocialText} from '../i18n/social';
import {useGameLanguage} from '../i18n/GameLanguageProvider';
import {socialLabel,socialText} from '../i18n/social';
import {formatLocalizedNumber} from '../i18n/translator';
import {useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,View,useWindowDimensions} from 'react-native';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {ActionFeedback} from '../components/ActionFeedback';
import {EmptyState} from '../components/EmptyState';
import {LoadingState} from '../components/LoadingState';
import {CompactPlayerIdentity} from '../components/CompactPlayerIdentity';
import {RANKING_BOARDS,RANKING_GROUPS,type RankingBoardId,type RankingBoardSnapshot,type RankingGroup} from '../core/rankings';
import {rankingsClient,rankingsOnlineConfigured} from '../online/rankings-client';
import {radii,spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {rankingPositionPresentation} from '../core/social-identity';
export function RankingsScreen(){
 const st=useSocialText();
 const language=useGameLanguage();
 const rankingValueLabel=(id:RankingBoardId,value:number)=>{const unit=RANKING_BOARDS.find(row=>row.id===id)!.unit;const number=formatLocalizedNumber(language,Math.max(0,Math.floor(value)));return socialText(language,id==="dungeon_tier"?"Tier {value}":unit==="levels"?"{value} levels":unit==="points"?"{value} points":unit==="rating"?"{value} rating":unit==="wins"?"{value} wins":unit==="clears"?"{value} clears":"{value} level",{value:number});};
  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]),{width,fontScale}=useWindowDimensions(),stackRows=width<360||fontScale>=1.25;const[group,setGroup]=useState<RankingGroup>('Account'),[board,setBoard]=useState<RankingBoardId>('profession_total'),[snapshot,setSnapshot]=useState<RankingBoardSnapshot|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const boards=useMemo(()=>RANKING_BOARDS.filter(row=>row.group===group),[group]);useEffect(()=>{if(!boards.some(row=>row.id===board))setBoard(boards[0].id)},[group]);
 const request=useRef(0);
 async function load(){const version=++request.current;if(!rankingsOnlineConfigured){setSnapshot(null);setError(st("Rankings require the authenticated online server."));return;}setLoading(true);setError('');try{const next=await rankingsClient.board(board);if(version===request.current)setSnapshot(next);}catch(e){if(version===request.current){setSnapshot(null);setError(e instanceof Error?e.message:st("Could not load Rankings."));}}finally{if(version===request.current)setLoading(false);}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(AppState.currentState==='active')void load();},60000);const foreground=AppState.addEventListener('change',next=>{if(next==='active')void load();});return()=>{request.current++;clearInterval(timer);foreground.remove();};},[board]);const definition=RANKING_BOARDS.find(row=>row.id===board)!,activeSnapshot=snapshot?.board===board&&boards.some(row=>row.id===board)?snapshot:null;
 return <ScrollView contentContainerStyle={s.root} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}>
  <Text style={s.kicker}>{st("RANKINGS")}</Text><Text accessibilityRole="header" style={s.heading}>{st("VELDRYN Rankings")}</Text>
  {activeSnapshot?.self?<Panel><Text style={s.kicker}>{st("YOUR STANDING")}</Text><Text style={s.title}>{socialLabel(language,definition.name)}</Text><Text style={s.value}>{activeSnapshot.self.listed&&activeSnapshot.self.rank?`#${activeSnapshot.self.rank} · `:''}{rankingValueLabel(board,activeSnapshot.self.value)}</Text>{activeSnapshot.self.reason&&<Text style={s.warning}>{activeSnapshot.self.reason}</Text>}</Panel>:null}
  <Panel><Text style={s.title}>{st("Prestige, not power")}</Text><Text style={s.copy}>{st('Rankings are read-only, server-calculated, and provide no exclusive combat power. Account boards respect Public Profile visibility and block relationships.')}</Text></Panel>
  <Text style={s.filterLabel}>{st("SCOPE")}</Text><View style={s.wrap}>{RANKING_GROUPS.map(value=><ChoiceChip key={value} label={`${socialLabel(language,value)} · ${RANKING_BOARDS.filter(row=>row.group===value).length}`} selected={group===value} onPress={()=>setGroup(value)}/>)}</View>
  <Text style={s.filterLabel}>{st("BOARD")}</Text><View style={s.wrap}>{boards.map(value=><ChoiceChip key={value.id} label={socialLabel(language,value.name)} selected={board===value.id} onPress={()=>setBoard(value.id)}/>)}</View>
  <Panel><View style={s.header}><View style={s.flex}><Text style={s.title}>{socialLabel(language,definition.name)}</Text><Text style={s.copy}>{definition.group==='Professions'?st('Highest {profession} level on one account character.',{profession:socialLabel(language,definition.name)}):socialLabel(language,definition.description)}</Text></View><GameButton compact title={st("Refresh")} tone="secondary" loading={loading} onPress={()=>void load()}/></View>{loading&&!activeSnapshot&&<LoadingState compact label={st("Loading rankings")} detail={st("Fetching the latest server-calculated board.")}/>}{error&&<ActionFeedback message={error} tone="error" reduceMotion/>}</Panel>
  {activeSnapshot?.entries.map(entry=>{const position=rankingPositionPresentation(entry.rank),podium=position.tone==='podium_gold'?s.rankGold:position.tone==='podium_silver'?s.rankSilver:position.tone==='podium_bronze'?s.rankBronze:undefined;return <Panel key={`${entry.rank}-${entry.displayName}-${entry.value}`}><View style={[s.row,stackRows&&s.rowStack]}><View style={[s.rankBadge,podium]}><Text style={[s.rank,position.tone==='podium_gold'&&s.rankGoldText]}>{position.label}</Text></View><View style={s.flex}><CompactPlayerIdentity badges={entry.playerBadges} name={entry.displayName} guildTag={entry.guildTag} guildTagColorId={entry.guildTagColorId} guild={entry.entityType==='guild'} avatarSize={38} status={entry.isSelf?st("YOU"):entry.entityType==='guild'?st("GUILD"):st("PLAYER")} statusTone={entry.isSelf?'good':'muted'}/>{entry.subtitle&&<Text style={s.rankMeta}>{entry.subtitle}</Text>}{entry.detail&&<Text style={s.detail}>{entry.detail}</Text>}</View><Text style={[s.scoreValue,stackRows&&s.scoreValueStack]}>{rankingValueLabel(board,entry.value)}</Text></View></Panel>})}
  {activeSnapshot&&!loading&&!activeSnapshot.entries.length&&<EmptyState compact title={st("No ranked entries yet")} message={st("This board will populate when eligible public results are available.")} icon="world"/>}
 </ScrollView>;
}
function ChoiceChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);return <Pressable accessibilityRole="tab" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.chip,selected&&s.chipSelected,pressed&&s.pressed]}><Text style={[s.chipText,selected&&s.chipTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({root:{padding:spacing.md,gap:10},kicker:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:1.2},heading:{...typography.hero,color:C.text},title:{...typography.title,color:C.text},copy:{...typography.body,color:C.muted,lineHeight:21},filterLabel:{...typography.caption,color:C.muted,fontWeight:'900',letterSpacing:1},wrap:{flexDirection:'row',flexWrap:'wrap',gap:6},chip:{minHeight:44,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},chipSelected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},chipText:{fontSize:12,color:C.muted,fontWeight:'700'},chipTextSelected:{color:C.text},pressed:{opacity:.76},accentWord:{color:C.accent,fontWeight:'900'},header:{flexDirection:'row',gap:spacing.sm,alignItems:'flex-start'},flex:{flex:1,minWidth:0},warning:{...typography.bodyStrong,color:C.warning},self:{marginTop:spacing.md,padding:spacing.md,borderWidth:1,borderColor:C.accent},value:{...typography.title,color:C.text},row:{flexDirection:'row',alignItems:'center',gap:8},rowStack:{flexWrap:'wrap',alignItems:'flex-start'},rankBadge:{width:46,height:34,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},rankGold:{borderColor:equipmentColors.goldSoft,backgroundColor:C.accentSurface},rankSilver:{borderColor:C.muted,backgroundColor:C.panel2},rankBronze:{borderColor:'#b77844',backgroundColor:C.panel2},rank:{...typography.bodyStrong,color:C.accent},rankGoldText:{color:equipmentColors.goldSoft},rankMeta:{fontSize:9,lineHeight:12,color:C.muted,marginTop:2,marginLeft:46},detail:{...typography.caption,color:C.good,marginLeft:46},scoreValue:{...typography.bodyStrong,color:C.text,textAlign:'right'},scoreValueStack:{width:'100%',marginLeft:54,textAlign:'left'}});}
