import {RecipeCard} from '../components/RecipeCard';
import {SearchField} from '../components/SearchField';
import {ActivityArtwork} from '../components/ActivityArtwork';
import {useState} from 'react';
import {Image,Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameState,GatheringSkillId,SkillId} from '../core/types';
import {GATHERING,RECIPES} from '../content/skills';
import {HERB_NODES} from '../content/herbalism';
import {itemDef} from '../content/items';
import {recipeAvailability} from '../core/playability';
import {GATHER_TIME_SCALE,offlineCapBreakdown} from '../core/game';
import {environmentEffect,environmentForZone} from '../core/world-weather';
import {Panel} from '../components/Panel';
import {GameButton} from '../components/GameButton';
import {C,spacing,typography} from '../theme/theme';
import {NoviceWorkshop} from '../components/NoviceWorkshop';
import {formatGameNumber} from '../core/number-format';
import {ot} from '../i18n';
import {gatheringToolsFor} from '../content/gathering-tools';
import {equippedGatheringTool,gatheringPacing} from '../core/gathering-tools';
import {characterPermanentMultipliers} from '../core/permanent-boosts';
import {GatheringToolArtwork} from '../components/GatheringToolArtwork';
import {WORLD_ZONES} from '../content/world-map';
import {currentRegionId} from '../core/combat-region';
import {ResourceArtwork} from '../components/ResourceArtwork';
import {FaithPanel} from '../components/FaithPanel';
import {classSkillsFor} from '../content/class-skills';
import {characterClassSkills} from '../core/class-skills';
import {classEmblemIconArtwork} from '../theme/class-emblem-assets';
import {uiIcons} from '../theme/ui-icons';
import {CrossSkillDiscoveriesPanel} from '../components/CrossSkillDiscoveriesPanel';

export function SkillsScreen({state,onGather,onCraft,onEquipTool,onCharacter,onInventory,onViewToolRecipes,onSelectSkill,onCommand=async()=>{},initialMode='gathering',initialSkill}:{state:GameState;onGather:(id:string)=>void;onCraft:(id:string)=>void;onEquipTool:(id:string)=>void;onCharacter:()=>void;onInventory:()=>void;onViewToolRecipes:()=>void;onSelectSkill?:(id:string)=>void;onCommand?:(command:import('../core/game-commands').GameCommand)=>Promise<void>;initialMode?:'gathering'|'crafting'|'novice'|'faith';initialSkill?:SkillId}){
  const gatheringDefs=[...GATHERING,...HERB_NODES];
  const [mode,setMode]=useState<'gathering'|'crafting'|'novice'|'faith'>(initialMode);
  const [readyOnly,setReadyOnly]=useState(false),[recipeQuery,setRecipeQuery]=useState(''),[recipeLimits,setRecipeLimits]=useState<Record<string,number>>({}),[recipeFilterOpen,setRecipeFilterOpen]=useState(false),[recipeSort,setRecipeSort]=useState<'level'|'name'>('level');
  const [openTools,setOpenTools]=useState<Record<string,boolean>>({});
  const offlineCap=offlineCapBreakdown(state);
  const region=WORLD_ZONES.find(zone=>zone.id===currentRegionId(state))??WORLD_ZONES[0];
  if(!initialSkill)return <SkillHub state={state} onSelect={onSelectSkill??(()=>{})}/>;
  return <><ScrollView contentContainerStyle={s.root}>
    <Text style={s.h}>{initialSkill?initialSkill.charAt(0).toUpperCase()+initialSkill.slice(1):ot(state.settings.language,'craft.screen')}</Text>
    {mode==='gathering'&&<View style={[s.region,{borderColor:region.accent}]}><View style={s.flex}><Text style={s.regionLabel}>CURRENT REGION</Text><Text style={s.regionName}>{region.symbol} {region.name}</Text><Text style={s.sub}>Only gathering nodes in this region are shown.</Text></View></View>}
    {!initialSkill&&<View style={s.row}>{(['gathering','crafting','novice','faith'] as const).map(value=><View style={s.flex} key={value}><GameButton title={value==='faith'?'Faith':ot(state.settings.language,value==='gathering'?'craft.gathering':value==='novice'?'craft.novice':'craft.crafting')} selected={mode===value} tone={mode===value?'primary':'secondary'} onPress={()=>setMode(value)}/></View>)}</View>}
    {(mode==='faith'||initialSkill==='faith')&&<FaithPanel state={state} onCommand={onCommand}/>}
    {mode==='novice'&&<NoviceWorkshop state={state} onCraft={onCraft} onCharacter={onCharacter}/>}
    {mode==='crafting'&&<><Text style={s.sub}>Materials are taken from Inventory first, then Bank. Expand a recipe to inspect ingredients and craft.</Text><SearchField accessibilityLabel="Search recipes" value={recipeQuery} onChangeText={value=>{setRecipeQuery(value);setRecipeLimits({});}} placeholder="Search recipes…"/><View style={s.filterToolbar}><View style={s.flex}><GameButton title={`Filters${readyOnly?' · 1':''} ▾`} tone={readyOnly?'primary':'secondary'} onPress={()=>setRecipeFilterOpen(true)}/></View><View style={s.flex}><GameButton title={`Sort: ${recipeSort==='level'?'Level':'Name'} ▾`} tone="secondary" onPress={()=>setRecipeFilterOpen(true)}/></View></View></>}
    {mode!=='novice'&&mode!=='faith'&&initialSkill!=='faith'&&state.skills.filter(sk=>(!initialSkill||sk.skillId===initialSkill)&&(mode==='gathering'?gatheringDefs.some(g=>g.skillId===sk.skillId):RECIPES.some(r=>r.skillId===sk.skillId&&!r.noviceSetId))).map(sk=>{
      const recipes=RECIPES.filter(r=>r.skillId===sk.skillId&&!r.noviceSetId).sort((a,b)=>recipeSort==='name'?a.name.localeCompare(b.name):a.level-b.level||a.name.localeCompare(b.name)).map(recipe=>({recipe,status:recipeAvailability(state,recipe.id)})).filter(({recipe,status})=>(!readyOnly||status.ready)&&(!recipeQuery.trim()||(recipe.name+' '+itemDef(recipe.output.itemId).name).toLowerCase().includes(recipeQuery.trim().toLowerCase())));
      const gatheringSkill=sk.skillId as GatheringSkillId,equippedTool=mode==='gathering'?equippedGatheringTool(state,gatheringSkill):undefined;
      return <View key={sk.skillId} style={s.group}><View style={s.toolHeading}><ActivityArtwork id={sk.skillId}/><View style={s.flex}><Text style={s.name}>{sk.skillId.charAt(0).toUpperCase()+sk.skillId.slice(1)} · Level {sk.level}</Text><Text style={s.sub}>{formatGameNumber(sk.xp,state.settings.numberMode)} XP</Text></View></View>
        {mode==='gathering'&&<Panel><Pressable accessibilityRole="button" accessibilityState={{expanded:!!openTools[sk.skillId]}} onPress={()=>setOpenTools(value=>({...value,[sk.skillId]:!value[sk.skillId]}))} style={s.toolHeading}>{equippedTool?<GatheringToolArtwork itemId={equippedTool.id} size={64}/>:<View style={s.emptyTool}><ActivityArtwork id={gatheringSkill}/></View>}<View style={s.flex}><Text style={s.name}>{equippedTool?.name??'No tool equipped'}</Text><Text style={s.sub}>{equippedTool?`Tier ${equippedTool.tier} · ${Math.round((1-equippedTool.actionTimeMultiplier)*100)}% shorter action time`:'No tool · 15% slower gathering'}</Text><Text style={s.manageHint}>Tap to {openTools[sk.skillId]?'hide':'manage'} tool tiers</Text></View><Text style={s.disclosureMark}>{openTools[sk.skillId]?'−':'+'}</Text></Pressable>{openTools[sk.skillId]&&gatheringToolsFor(gatheringSkill).map(tool=>{const equipped=equippedTool?.id===tool.id,carried=state.inventory.stacks.some(stack=>stack.itemId===tool.id&&stack.quantity>0),banked=state.bank.stacks.some(stack=>stack.itemId===tool.id&&stack.quantity>0),levelReady=sk.level>=tool.unlockLevel;const title=equipped?'Equipped':carried&&!levelReady?`Lv ${tool.unlockLevel}`:carried?'Equip':banked?'Withdraw':'Recipe';const disabled=equipped||(carried&&!levelReady);const action=carried?()=>onEquipTool(tool.id):banked?onInventory:onViewToolRecipes;return <View key={tool.id} style={s.toolRow}><GatheringToolArtwork itemId={tool.id} size={48}/><View style={s.flex}><Text style={s.toolName}>T{tool.tier} · {tool.name}</Text><Text style={s.toolEffect}>{Math.round((1-tool.actionTimeMultiplier)*100)}% faster · skill level {tool.unlockLevel}{banked?' · in Bank':carried?' · ready':''}</Text></View><View style={s.toolButton}><GameButton title={title} disabled={disabled} selected={equipped} tone={equipped?'primary':'secondary'} onPress={action}/></View></View>})}</Panel>}
        {mode==='gathering'&&gatheringDefs.filter(g=>g.skillId===sk.skillId&&g.zoneId===region.id).map(g=>{const active=state.activity?.targetId===g.id;const environment=environmentForZone(g.zoneId);const effect=environmentEffect(g.skillId,environment);const pacing=gatheringPacing(state,g);const permanent=characterPermanentMultipliers(state);const cycle=g.seconds*GATHER_TIME_SCALE*pacing.timeMultiplier*effect.actionTimeMultiplier/permanent.gatheringSpeedMultiplier;const capActions=Math.floor(offlineCap.hours*3600/cycle);const baselineItems=Math.floor(capActions*g.min*effect.itemMultiplier);const capXp=Math.floor(capActions*g.xp*effect.xpMultiplier*permanent.skillXpMultiplier);return <Panel key={g.id}><View style={s.toolHeading}><ResourceArtwork itemId={g.itemId} size={64}/><View style={s.flex}><Text style={s.name}>{g.name}</Text><Text style={s.sub}>{itemDef(g.itemId).name} · every {cycle.toFixed(1)}s · {g.xp} base skill XP/action</Text></View><View style={[s.tierBadge,pacing.atRecommendedTier?s.tierReady:s.tierSlow]}><Text style={s.tierText}>T{g.recommendedToolTier}</Text></View></View><Text style={pacing.atRecommendedTier?s.readyText:s.slowText}>{pacing.atRecommendedTier?`${pacing.tool?.name} offsets this resource's ×${g.difficultyMultiplier.toFixed(2)} difficulty.`:`Recommended: ${pacing.recommended?.name}. Current pace is ×${pacing.timeMultiplier.toFixed(2)} before weather.`}</Text><Text style={s.pacing}>At your {offlineCap.hours}h AFK cap: {formatGameNumber(capActions,state.settings.numberMode)} actions · {formatGameNumber(baselineItems,state.settings.numberMode)}+ {itemDef(g.itemId).name} · {formatGameNumber(capXp,state.settings.numberMode)} XP</Text><GameButton disabled={sk.level<g.unlockLevel||active} title={active?'Currently gathering':sk.level<g.unlockLevel?`Requires ${g.skillId} level ${g.unlockLevel}`:`Gather ${g.name}`} onPress={()=>onGather(g.id)}/></Panel>})}
        {mode==='gathering'&&gatheringDefs.every(g=>g.skillId!==sk.skillId||g.zoneId!==region.id)&&<Text style={s.unavailable}>No {sk.skillId} activity is available in {region.name}. Travel to another region from World.</Text>}
        {mode==='crafting'&&recipes.slice(0,recipeLimits[sk.skillId]??12).map(({recipe,status})=><RecipeCard key={recipe.id} state={state} recipe={recipe} status={status} onCraft={onCraft}/>)}
        {mode==='crafting'&&recipes.length>(recipeLimits[sk.skillId]??12)&&<GameButton title={`Show more recipes (${recipes.length-(recipeLimits[sk.skillId]??12)} remaining)`} tone="secondary" onPress={()=>setRecipeLimits(value=>({...value,[sk.skillId]:(value[sk.skillId]??12)+12}))}/>}
        {mode==='crafting'&&recipes.length===0&&<Text style={s.sub}>{recipeQuery.trim()?'No recipes match your search.':readyOnly?'No recipes are ready. Show all to see requirements.':'No recipes available.'}</Text>}
      </View>;
    })}
  </ScrollView><Modal visible={recipeFilterOpen} transparent animationType="slide" onRequestClose={()=>setRecipeFilterOpen(false)}><View style={s.filterBackdrop}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setRecipeFilterOpen(false)}/><View style={s.filterSheet}><Text style={s.name}>Recipe Filters</Text><Text style={s.filterLabel}>Visibility</Text><Pressable onPress={()=>setReadyOnly(false)} style={[s.filterOption,!readyOnly&&s.filterOptionActive]}><Text style={s.filterOptionText}>{!readyOnly?'✓ ':''}All recipes</Text></Pressable><Pressable onPress={()=>setReadyOnly(true)} style={[s.filterOption,readyOnly&&s.filterOptionActive]}><Text style={s.filterOptionText}>{readyOnly?'✓ ':''}Craftable now</Text></Pressable><Text style={s.filterLabel}>Sort by</Text>{(['level','name'] as const).map(value=><Pressable key={value} onPress={()=>setRecipeSort(value)} style={[s.filterOption,recipeSort===value&&s.filterOptionActive]}><Text style={s.filterOptionText}>{recipeSort===value?'✓ ':''}{value==='level'?'Required level':'Name'}</Text></Pressable>)}<View style={s.filterToolbar}><View style={s.flex}><GameButton title="Reset" tone="secondary" onPress={()=>{setReadyOnly(false);setRecipeSort('level')}}/></View><View style={s.flex}><GameButton title="Apply" onPress={()=>setRecipeFilterOpen(false)}/></View></View></View></View></Modal></>;
}
const s=StyleSheet.create({root:{padding:spacing.lg,gap:spacing.md},h:{...typography.hero,color:C.text},name:{...typography.title,color:C.text},sub:{...typography.body,color:C.muted},weather:{...typography.caption,fontWeight:'900'},pacing:{...typography.caption,color:C.info},row:{flexDirection:'row',gap:spacing.sm},filterToolbar:{flexDirection:'row',gap:spacing.sm,alignItems:'center'},flex:{flex:1},filterBackdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'#0008'},filterSheet:{backgroundColor:C.bg,borderTopWidth:1,borderColor:C.line,borderTopLeftRadius:20,borderTopRightRadius:20,padding:spacing.lg,gap:8},filterLabel:{...typography.caption,color:C.muted,fontWeight:'900',letterSpacing:.8,marginTop:8},filterOption:{minHeight:48,justifyContent:'center',paddingHorizontal:12,borderWidth:1,borderColor:C.line,borderRadius:8,backgroundColor:C.panel},filterOptionActive:{borderColor:C.accent,backgroundColor:C.panel2},filterOptionText:{color:C.text,fontWeight:'800'},group:{gap:spacing.md},output:{...typography.bodyStrong,color:C.accent},met:{...typography.caption,color:C.good},missing:{...typography.caption,color:C.warning},toolHeading:{minHeight:68,flexDirection:'row',alignItems:'center',gap:spacing.sm},manageHint:{...typography.caption,color:C.accent},disclosureMark:{width:28,color:C.accent,fontSize:25,textAlign:'center'},emptyTool:{width:64,height:64,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:8,backgroundColor:'#09121a'},emptyToolText:{fontSize:28,color:C.muted},toolRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm,paddingTop:spacing.sm,borderTopWidth:1,borderTopColor:C.line},toolName:{...typography.bodyStrong,color:C.text},toolEffect:{...typography.caption,color:C.info},toolButton:{width:96},tierBadge:{minWidth:42,height:38,alignItems:'center',justifyContent:'center',borderWidth:1,borderRadius:8},tierReady:{borderColor:C.good,backgroundColor:'#172b24'},tierSlow:{borderColor:C.warning,backgroundColor:'#332515'},tierText:{...typography.bodyStrong,color:C.text},readyText:{...typography.caption,color:C.good,fontWeight:'800'},slowText:{...typography.caption,color:C.warning,fontWeight:'800'},region:{minHeight:86,flexDirection:'row',alignItems:'center',padding:spacing.md,backgroundColor:'#0c1d2e',borderWidth:1,borderRadius:10},regionLabel:{...typography.caption,color:C.muted,fontWeight:'900',letterSpacing:.8},regionName:{...typography.title,color:C.accent},unavailable:{...typography.body,color:C.muted,padding:spacing.md,borderWidth:1,borderColor:C.line,borderRadius:8,backgroundColor:C.panel}});

const hubStyles=StyleSheet.create({hub:{padding:spacing.lg,gap:spacing.md},hubTitle:{...typography.hero,color:C.text},hubSub:{...typography.body,color:C.muted},hubTabs:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},hubTab:{width:'48%',minWidth:140},sectionLabel:{...typography.caption,color:C.muted,fontWeight:'900'},cardGrid:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},skillCard:{width:'48%',minWidth:145,minHeight:154,padding:spacing.md,borderWidth:1,borderColor:C.line,borderRadius:12,backgroundColor:C.panel,gap:5},skillIcon:{width:44,height:44,alignSelf:'center',marginBottom:2},cardPressed:{opacity:.72},skillName:{...typography.bodyStrong,color:C.text},skillKind:{...typography.caption,color:C.info},skillLevel:{...typography.title,color:C.accent},skillTrack:{height:6,backgroundColor:C.bg,borderRadius:3,overflow:'hidden',marginTop:'auto'},skillFill:{height:'100%',backgroundColor:C.good},skillHint:{...typography.caption,color:C.muted}});
function SkillHub({state,onSelect}:{state:GameState;onSelect:(id:string)=>void}){
 const classRows=state.character?characterClassSkills(state.character):[];
 const cards=(rows:ReadonlyArray<{id:string;name:string;level:number;kind:string}>)=><View style={hubStyles.cardGrid}>{rows.map(card=>{const icon=card.id==='companion'?uiIcons.party:card.id.startsWith('class:')?classEmblemIconArtwork[state.character!.classId]:null;return <Pressable key={card.id} accessibilityRole="button" onPress={()=>onSelect(card.id)} style={({pressed})=>[hubStyles.skillCard,pressed&&hubStyles.cardPressed]}>{icon?<Image source={icon} resizeMode="contain" style={hubStyles.skillIcon}/>:<ActivityArtwork id={card.id as any} size={42}/>}<Text style={hubStyles.skillName}>{card.name}</Text><Text style={hubStyles.skillKind}>{card.kind}</Text><Text style={hubStyles.skillLevel}>Level {card.level}</Text><View style={hubStyles.skillTrack}><View style={[hubStyles.skillFill,{width:`${Math.max(4,Math.min(100,card.level))}%`}]}/></View><Text style={hubStyles.skillHint}>Tap to open</Text></Pressable>})}</View>;
 const combat=[...classRows.map((row,i)=>({id:`class:${row.skillId}`,name:classSkillsFor(state.character!.classId)[i]?.name??row.skillId,level:row.level,kind:'Class skill'})),{id:'companion',name:'Companions',level:state.account.companionSanctuary?.trainingGroundLevel??1,kind:'Companion skill'}];
 const skilling=state.skills.filter(sk=>['mining','woodcutting','fishing','herbalism','hunting','exploration'].includes(sk.skillId)).map(sk=>({id:sk.skillId,name:sk.skillId.charAt(0).toUpperCase()+sk.skillId.slice(1),level:sk.level,kind:'Skilling'}));
 const crafting=state.skills.filter(sk=>['smithing','cooking','alchemy','tailoring','enchanting','faith'].includes(sk.skillId)).map(sk=>({id:sk.skillId,name:sk.skillId.charAt(0).toUpperCase()+sk.skillId.slice(1),level:sk.level,kind:'Crafting'}));
 return <ScrollView contentContainerStyle={hubStyles.hub}><Text style={hubStyles.hubTitle}>Skills</Text><Text style={hubStyles.hubSub}>Choose a skill to train or inspect.</Text><Text style={hubStyles.sectionLabel}>COMBAT SKILLS</Text>{cards(combat)}<Text style={hubStyles.sectionLabel}>SKILLING</Text>{cards(skilling)}<Text style={hubStyles.sectionLabel}>CRAFTING &amp; OTHER SKILLS</Text>{cards(crafting)}<CrossSkillDiscoveriesPanel state={state}/></ScrollView>;
}
