import {useSocialText} from '../i18n/social';
import {useGameLanguage} from '../i18n/GameLanguageProvider';
import {socialLabel,socialExpiry} from '../i18n/social';
import {useCallback,useEffect,useRef,useState,useMemo} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {PartyHubPanel} from '../components/PartyHubPanel';
import {PartyEventHubPanel} from '../components/PartyEventHubPanel';
import {SocialHubPanel,type SocialHubTab} from '../components/SocialHubPanel';
import {GuildSeekerPanel} from '../components/GuildSeekerPanel';
import {RecruitmentComposer} from '../components/RecruitmentComposer';
import {RecruitmentFiltersPanel} from '../components/RecruitmentFiltersPanel';
import {RecruitmentListing} from '../components/RecruitmentListing';
import {SocialInvitationCard} from '../components/SocialInvitationCard';
import {OnlinePartyChat} from '../components/OnlinePartyChat';
import {GameButton} from '../components/GameButton';
import {Panel} from '../components/Panel';
import {ChatPlayerSheet,type ChatPlayerIdentity} from '../components/ChatPlayerSheet';
import {usePartySocial} from '../online/PartySocialProvider';
import {partySocialRepository as repository,ownRecruitmentPosts,partyRankings,partyCommandKey,claimPartyContractReward,activePartyEvent,transferPartyLeadership,removePartyMember,cancelPartyInvitation,disbandParty,recruitmentMatchAlerts,setRecruitmentAlertSubscription,ackRecruitmentMatchAlerts,type PublishRecruitmentInput,type PartyRanking,type RecruitmentMatchAlert} from '../online/party-social';
import {myGuild,requestGuildMembership,respondPartyInvitation,sendPartyInvitation,socialInvitations,socialOutgoingInvitations,type OutgoingInvitationView,type PartyInvitationView} from '../online/social';
import {EMPTY_RECRUITMENT_FILTERS,PARTY_SOCIAL_TUTORIAL_STEPS,recruitmentContextLabels,recruitmentPostTypePresentation,recruitmentTimeLabel,type PartyFocus,type PartyRole,type RecruitmentCardView,type RecruitmentPostType} from '../core/party-social';
import {spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
export function SocialScreen({onGuild,onFriends,onAccount,onInvitationsChanged}:{onGuild:()=>void;onFriends:()=>void;onAccount:()=>void;onInvitationsChanged?:()=>void}){
 const st=useSocialText();
  const language=useGameLanguage();
  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const social=usePartySocial();const [tab,setTab]=useState<SocialHubTab>('party');const [filters,setFilters]=useState({...EMPTY_RECRUITMENT_FILTERS});
 const [cards,setCards]=useState<RecruitmentCardView[]>([]),[own,setOwn]=useState<RecruitmentCardView[]>([]),[rankings,setRankings]=useState<PartyRanking[]>([]),[partyInvites,setPartyInvites]=useState<PartyInvitationView[]>([]),[outgoingPartyInvites,setOutgoingPartyInvites]=useState<OutgoingInvitationView[]>([]),[liveEvent,setLiveEvent]=useState<import('../core/party-social').PartyEventView|null>(null);
 const [draft,setDraft]=useState<PublishRecruitmentInput|null>(null),[selected,setSelected]=useState<RecruitmentCardView|null>(null),[selectedProfile,setSelectedProfile]=useState<ChatPlayerIdentity|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[matchAlerts,setMatchAlerts]=useState<RecruitmentMatchAlert[]>([]),[alertsEnabled,setAlertsEnabled]=useState(false);
 const [focus,setFocus]=useState<PartyFocus>('mixed'),[role,setRole]=useState<PartyRole>('damage'),[help,setHelp]=useState(false),[now,setNow]=useState(Date.now());
 const requestGeneration=useRef(0);const command=useRef<{signature:string;key:string}|null>(null);
 const key=(signature:string)=>{if(command.current?.signature!==signature)command.current={signature,key:partyCommandKey()};return command.current.key;};
 const load=useCallback(async()=>{const generation=++requestGeneration.current;if(!social.accountId){setCards([]);setOwn([]);setRankings([]);setPartyInvites([]);setOutgoingPartyInvites([]);return;}
  try{const browse=tab==='guild'?{...filters,postTypes:['looking_for_guild'] as RecruitmentPostType[]}:filters;const [next,mine,board,invites,outgoing,alerts]=await Promise.all([repository.browseRecruitment(browse),ownRecruitmentPosts(),partyRankings(),socialInvitations().catch(()=>({party:[],guild:[],serverTime:''})),socialOutgoingInvitations().catch(()=>({party:[],guild:[],serverTime:''})),recruitmentMatchAlerts().catch(()=>[])]);if(generation===requestGeneration.current){setCards(next);setOwn(mine);setRankings(board);setPartyInvites(invites.party);setOutgoingPartyInvites(outgoing.party);setMatchAlerts(alerts);setError('');}}
  catch(e){if(generation===requestGeneration.current){setCards([]);setError(e instanceof Error?e.message:st("Social service unavailable."));}}
 },[filters,tab,social.accountId]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>{clearTimeout(timer);requestGeneration.current++;};},[load,social.party?.id]);
 useEffect(()=>{const timer=setInterval(()=>{setNow(Date.now());void load();},30000);return()=>clearInterval(timer);},[load]);
 useEffect(()=>{if(tab!=='events'||!social.accountId)return;void activePartyEvent().then(setLiveEvent).catch(e=>setError(e instanceof Error?e.message:st("Live event unavailable.")));},[tab,social.accountId,social.party?.id]);
 const run=async(action:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await action();command.current=null;await social.refresh();await load();}catch(e){setError(e instanceof Error?e.message:st("Please try again."));await social.refresh();}finally{setBusy(false);}};
 const character=()=>{if(!social.characterId)throw new Error(st("Sync your character in Account settings first."));return social.characterId;};
 const post=(postType:RecruitmentPostType)=>void run(async()=>{const guild=postType==='guild_recruiting'?await myGuild():null;setDraft({postType,title:'',body:'',focus,roles:[role],ownerCharacterId:character(),durationDays:postType.includes('guild')?3:1,...(postType==='party_recruiting'?{partyId:social.party?.id,openSpots:Math.max(0,4-(social.party?.members.length??0))}:{}),...(guild?{guildId:guild.guild_id}:{})});});
 // Local countdown advances between snapshots; expiry is also enforced by the database query.
 const clock=useRef({server:now,local:now});useEffect(()=>{if(social.serverTime)clock.current={server:Date.parse(social.serverTime),local:Date.now()};},[social.serverTime]);
 const at=clock.current.server+(now-clock.current.local);
 return <SocialHubPanel active={tab} badges={{party:partyInvites.length}} onChange={next=>{setTab(next);setSelected(null);setDraft(null);}}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}>
  <View style={s.row}><GameButton title={st("Friends")} tone="secondary" onPress={onFriends}/><GameButton title={st("Social help")} tone="secondary" onPress={()=>setHelp(!help)}/><GameButton title={busy?st("Working…"):st("Refresh")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{})}/><GameButton title={alertsEnabled?st("Stop match alerts"):st("Alert me about matches")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{const next=!alertsEnabled;await setRecruitmentAlertSubscription(filters,next);setAlertsEnabled(next);})}/></View>
  {matchAlerts.length>0?<Panel><View style={s.sectionHead}><Text style={s.selectedLabel}>{st("MATCHES FOUND")}</Text><Text style={s.sectionMeta}>{matchAlerts.length}</Text></View>{matchAlerts.slice(0,5).map(alert=><Pressable key={alert.id} onPress={()=>{const card=cards.find(item=>item.id===alert.id);if(card)setSelected(card);}}><Text style={s.text}>{alert.title} · {alert.focus.toUpperCase()} · {alert.owner_name??st("Adventurer")}</Text></Pressable>)}<GameButton compact title={st("Dismiss matches")} tone="secondary" onPress={()=>void run(async()=>{await ackRecruitmentMatchAlerts();setMatchAlerts([]);})}/></Panel>:null}
  {help&&<Panel>{PARTY_SOCIAL_TUTORIAL_STEPS.map(step=><Text key={step} style={s.text}>{socialLabel(language,step)}</Text>)}</Panel>}
  {!!(error||social.error)&&<View accessibilityRole="alert" style={s.errorCard}><Text style={s.errorLabel}>{st("SOCIAL UNAVAILABLE")}</Text><Text style={s.error}>{error||social.error}</Text></View>}
  {!social.accountId?<Panel><Text style={s.text}>{social.loading?st("Loading account…"):st("Sign in and sync a character to use Parties and Recruitment.")}</Text><GameButton title={st("Account settings")} onPress={onAccount}/></Panel>:<>
   <View style={s.chipRow}><Text style={s.chipLabel}>{st("ROLE")}</Text>{(['damage','tank','support'] as const).map(value=><QuickChip key={value} label={socialLabel(language,value)} selected={role===value} onPress={()=>setRole(value)}/>)}</View>
   {!social.party&&<View style={s.chipRow}><Text style={s.chipLabel}>{st("FOCUS")}</Text>{(['combat','skilling','mixed'] as const).map(value=><QuickChip key={value} label={socialLabel(language,value)} selected={focus===value} onPress={()=>setFocus(value)}/>)}</View>}
   {draft&&<RecruitmentComposer key={draft.postType} initial={draft} busy={busy} onCancel={()=>setDraft(null)} onPublish={input=>void run(async()=>{await repository.publishRecruitment(input);setDraft(null);})}/>}
   {selected&&(()=>{const presentation=recruitmentPostTypePresentation(selected.postType),context=[...(selected.activityLevel?[socialLabel(language,selected.activityLevel.charAt(0).toUpperCase()+selected.activityLevel.slice(1))]:[]),...(selected.language?[selected.language]:[]),...(selected.region?[selected.region.toUpperCase()]:[]),...(selected.minCombatLevel!==undefined?[st('Combat {level}+',{level:Math.max(0,Math.floor(selected.minCombatLevel))})]:[]),...(selected.minTotalLevel!==undefined?[st('Total {level}+',{level:Math.max(0,Math.floor(selected.minTotalLevel))})]:[])],expiry=socialExpiry(language,selected.expiresAtMs,at);return <Panel accentColor={C.info} accentSurface={C.infoSurface}>
    <View style={s.selectedHead}><View style={s.flex}><Text style={s.selectedLabel}>{socialLabel(language,presentation.shortLabel)} · {socialLabel(language,selected.focus).toLocaleUpperCase()}</Text><Text style={s.title}>{selected.title}</Text></View><Text style={[s.expiry,expiry.urgency==='soon'&&s.expirySoon]}>{expiry.text}</Text></View>
    <Text style={s.text}>{selected.body}</Text>
    {(context.length||selected.currentObjective)?<View style={s.detailMeta}>{context.map(item=><View key={item} style={s.detailPill}><Text style={s.detailPillText}>{item}</Text></View>)}{selected.currentObjective?<View style={[s.detailPill,s.objectivePill]}><Text style={s.objectivePillText}>{st('Current · {objective}',{objective:selected.currentObjective})}</Text></View>:null}</View>:null}
    <View style={s.detailActions}>
     {selected.partyId&&!social.party?<View style={s.flex}><GameButton title={st("Join Party")} disabled={busy||selected.expiresAtMs<=at} onPress={()=>void run(async()=>{await repository.joinParty({partyId:selected.partyId!,characterId:character(),role,idempotencyKey:key(`join:${selected.partyId}`)});setSelected(null);})}/></View>:null}
     {selected.postType==='looking_for_party'&&selected.ownerAccountId&&selected.ownerAccountId!==social.accountId&&social.party?.members.some(member=>member.accountId===social.accountId&&member.isLeader)&&social.party.members.length<4?<View style={s.flex}><GameButton title={st("Invite to Party")} disabled={busy||selected.expiresAtMs<=at} onPress={()=>void run(async()=>{await sendPartyInvitation(selected.ownerAccountId!);setSelected(null);})}/></View>:null}
     {selected.guildId?<View style={s.flex}><GameButton title={st("Join / apply to Guild")} disabled={busy} onPress={()=>void run(async()=>{const result=await requestGuildMembership(selected.guildId!);Alert.alert(st("Guild"),result);})}/></View>:null}
     {selected.ownerAccountId&&selected.ownerAccountId!==social.accountId?<View style={s.flex}><GameButton title={st("Player Profile")} tone="secondary" disabled={busy} onPress={()=>setSelectedProfile({account_id:selected.ownerAccountId!,sender_name:selected.ownerName,guild_tag:selected.guildTag,guild_tag_color_id:selected.guildTagColorId})}/></View>:null}
    </View>
    <GameButton compact title={st("Close details")} tone="secondary" onPress={()=>setSelected(null)}/>
   </Panel>})()}
   {tab==='party'&&partyInvites.length>0?<Panel><View style={s.sectionHead}><Text style={s.selectedLabel}>{st("PARTY INVITES")}</Text><Text style={s.sectionMeta}>{st('{count} pending',{count:partyInvites.length})}</Text></View>{partyInvites.map(invite=>{const expiry=socialExpiry(language,Date.parse(invite.expiresAt),at),warning=social.party?'Leave your current Party before accepting another invitation.':invite.openSpots<1?'This Party is currently full.':undefined;return <SocialInvitationCard key={invite.id} accountId={invite.inviterAccountId} name={invite.inviterName} status={st("PARTY INVITE")} statusTone="info" detail={st('{focus} Party · {members}/4 members · {open} open',{focus:socialLabel(language,invite.focus),members:invite.memberCount,open:invite.openSpots})} expiry={expiry.text} warning={warning} actions={<><GameButton compact title={st("Accept")} disabled={busy||!!social.party||invite.openSpots<1||!social.characterId} onPress={()=>void run(async()=>{await respondPartyInvitation(invite.id,true,character());onInvitationsChanged?.()})}/><GameButton compact title={st("Decline")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await respondPartyInvitation(invite.id,false);onInvitationsChanged?.()})}/></>}/>} )}</Panel>:null}
   {tab==='party'&&outgoingPartyInvites.length>0?<Panel><View style={s.sectionHead}><Text style={s.selectedLabel}>{st("OUTGOING PARTY INVITES")}</Text><Text style={s.sectionMeta}>{st('{count} pending',{count:outgoingPartyInvites.length})}</Text></View>{outgoingPartyInvites.map(invite=>{const expiry=socialExpiry(language,Date.parse(invite.expiresAt),at);return <SocialInvitationCard key={invite.id} accountId={invite.recipientAccountId} name={invite.recipientName} status={st("INVITE SENT")} statusTone="muted" detail={st("Waiting for this player to respond.")} expiry={expiry.text} actions={<GameButton compact title={st("Cancel invite")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await cancelPartyInvitation(invite.id);onInvitationsChanged?.()})}/>}/>})}</Panel>:null}
   {tab==='party'&&<PartyHubPanel accountId={social.accountId} party={social.party} contracts={social.contracts} recruitment={cards} nowMs={at} filters={filters} onFiltersChange={setFilters}
    onCreateParty={busy?undefined:()=>void run(()=>repository.createParty({characterId:character(),role,focus,idempotencyKey:key(`create:${focus}:${role}`)}))}
    onLeaveParty={busy?undefined:()=>{const party=social.party!;const self=party.members.find(member=>member.accountId===social.accountId),successor=party.members.find(member=>member.accountId!==social.accountId);Alert.alert(self?.isLeader?(successor?st("Leave Party and hand over leadership?"):st("Leave and disband Party?")):st("Leave Party?"),self?.isLeader?(successor?st('Leadership will pass to {name}, the oldest remaining Party member.',{name:successor.characterName}):st("You are the only Party member, so leaving will disband it.")):st("You will leave this persistent Party."),[{text:st("Cancel"),style:'cancel'},{text:st("Leave"),style:'destructive',onPress:()=>void run(async()=>{await repository.leaveParty({partyId:party.id,idempotencyKey:key(`leave:${party.id}`)});await social.refresh();})}])}}
    onDisbandParty={busy?undefined:()=>{const party=social.party!;Alert.alert(st("Disband Party?"),st("This removes every member and cancels all pending Party invitations."),[{text:st("Cancel"),style:'cancel'},{text:st("Disband"),style:'destructive',onPress:()=>void run(()=>disbandParty(party.id))}])}}
    onOpenPartyChat={()=>setTab('chat')} onOpenMemberProfile={member=>setSelectedProfile({account_id:member.accountId,sender_name:member.characterName})}
    onTransferLeadership={member=>Alert.alert(st("Transfer Party leadership?"),st('{name} will become Party leader.',{name:member.characterName}),[{text:st("Cancel"),style:'cancel'},{text:st("Transfer"),onPress:()=>void run(()=>transferPartyLeadership(social.party!.id,member.accountId))}])}
    onRemoveMember={member=>Alert.alert(st('Remove {name}?',{name:member.characterName}),st("They will leave the Party immediately."),[{text:st("Cancel"),style:'cancel'},{text:st("Remove"),style:'destructive',onPress:()=>void run(()=>removePartyMember(social.party!.id,member.accountId))}])}
    onOpenRecruitmentPost={id=>setSelected(cards.find(card=>card.id===id)??null)} onCreateRecruitmentPost={post}
    onClaimReward={busy?undefined:id=>void run(()=>claimPartyContractReward(id,character()))}/>}
   {tab==='events'&&<PartyEventHubPanel event={liveEvent} onFindParty={()=>setTab('party')} />}
   {tab==='guild'&&<><GameButton title={st("Open Guild directory and management")} onPress={onGuild}/><GameButton title={st("Post Guild recruiting advert")} tone="secondary" disabled={busy} onPress={()=>post('guild_recruiting')}/><RecruitmentFiltersPanel value={filters} onChange={setFilters}/><GuildSeekerPanel seekers={cards} nowMs={at} onOpen={id=>setSelected(cards.find(card=>card.id===id)??null)} onPostMyAd={()=>post('looking_for_guild')}/></>}
   {tab==='chat'&&(social.party?<OnlinePartyChat/>:<Text style={s.text}>{st("Join a Party to use Party Chat. World and Guild chat remain available in the chat overlay.")}</Text>)}
   {tab==='rankings'&&<Panel><Text style={s.title}>{st("Ranked Party events")}</Text><Text style={s.text}>{st("Normalized points, then completion time. Ties use a stable Party ID order.")}</Text>{rankings.map(row=><Text style={s.text} key={`${row.event_key}:${row.party_id}`}>#{row.rank} · {row.name} · {row.party_id.slice(0,8)} · {st('{count} pts',{count:row.normalized_points})}</Text>)}{!rankings.length&&<Text style={s.text}>{st("No ranked contributions yet.")}</Text>}</Panel>}
   {(tab==='party'||tab==='guild')&&<Panel><View style={s.sectionHead}><Text style={s.title}>{st("Your adverts")}</Text><Text style={s.sectionMeta}>{st('{count} active / saved',{count:own.length})}</Text></View>{own.map(item=><View style={s.ad} key={item.id}><RecruitmentListing card={item} nowMs={at} onPress={()=>setSelected(item)}/>{item.status!=='closed'?<View style={s.adActions}><View style={s.flex}><GameButton compact title={st("Refresh")} tone="secondary" disabled={busy} onPress={()=>void run(()=>repository.refreshRecruitment(item.id))}/></View><View style={s.flex}><GameButton compact title={st("Close advert")} tone="secondary" disabled={busy} onPress={()=>void run(()=>repository.closeRecruitment(item.id))}/></View></View>:<Text style={s.closedLabel}>{st("CLOSED")}</Text>}</View>)}{!own.length&&<Text style={s.text}>{st("No adverts published yet.")}</Text>}</Panel>}
  </>}
  <ChatPlayerSheet message={selectedProfile} onClose={()=>setSelectedProfile(null)} onBlocked={()=>setSelectedProfile(null)}/>
 </ScrollView></SocialHubPanel>;
}
function QuickChip({label,selected,onPress}:{label:string;selected:boolean;onPress:()=>void}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);return <Pressable accessibilityRole="button" accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[s.chip,selected&&s.chipSelected,pressed&&s.pressed]}><Text style={[s.chipText,selected&&s.chipTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({content:{padding:spacing.md,gap:spacing.md,paddingBottom:32},row:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},flex:{flex:1,minWidth:0},chipRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:6},chipLabel:{fontSize:10,fontWeight:'900',letterSpacing:1,color:C.accentSoft,marginRight:2},chip:{minHeight:38,paddingHorizontal:12,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},chipSelected:{borderColor:C.selectionLine,backgroundColor:C.selection},chipText:{fontSize:12,color:C.muted,fontWeight:'800'},chipTextSelected:{color:C.text},pressed:{opacity:.76},title:{color:C.accent,fontSize:18,fontWeight:'800'},selectedLabel:{...typography.caption,color:C.info,fontWeight:'900',letterSpacing:1},selectedHead:{flexDirection:'row',alignItems:'flex-start',gap:8},expiry:{fontSize:9,color:C.muted,fontWeight:'800',paddingTop:2},expirySoon:{color:C.warning},detailMeta:{flexDirection:'row',flexWrap:'wrap',gap:5},detailPill:{maxWidth:130,paddingHorizontal:6,paddingVertical:3,borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.panel2},detailPillText:{fontSize:8,color:C.muted,fontWeight:'800'},objectivePill:{maxWidth:'100%',borderColor:C.info,backgroundColor:C.infoSurface},objectivePillText:{fontSize:8,color:C.info,fontWeight:'800'},detailActions:{flexDirection:'row',flexWrap:'wrap',gap:6},text:{color:C.text,lineHeight:21},errorCard:{gap:4,padding:spacing.md,borderWidth:1,borderColor:C.bad,borderRadius:10,backgroundColor:C.badSurface},errorLabel:{...typography.caption,color:C.bad,fontWeight:'900',letterSpacing:1},error:{color:C.text,lineHeight:21},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},sectionMeta:{fontSize:9,color:C.muted,fontWeight:'800'},ad:{gap:6,paddingVertical:6},adActions:{flexDirection:'row',gap:6},closedLabel:{fontSize:8,color:C.muted,fontWeight:'900',letterSpacing:.7,textAlign:'right'}});}
