import {createHash,createHmac} from 'node:crypto';
import {ratingDelta} from '../endgame/pvp-raids';
import {rankedBonusEligible,seasonRewardTier,chooseArenaOpponents,defenseRewardEligible} from './seasons';
import {arenaDivision,resolveArena3v3} from './arena';
import {arenaPowerBand,freezeArenaSquad,type ArenaCharacterSelection,ArenaLoadoutRepository} from './arena-snapshots';
import type {ArenaMatchRecord,ArenaRewardEntitlement,ArenaRuntimeRepository} from './arena-persistence';

export interface ArenaEntryProjection{season:{id:string;startsAtMs:number;endsAtMs:number;rating:number;division:string;wins:number;losses:number;defenseWins:number;rewardTier:number};defense:{published:boolean;updatedAtMs?:number;powerBand?:number;classes:string[]};pendingRewards:Array<{id:string;kind:string;rewardTier:number;catalogVersion:string;claimed:boolean}>;history:Array<{id:string;createdAtMs:number;result:'win'|'loss';opponentLabel:string;ratingDelta:number;score:string}>}
export interface ArenaApplicationOptions{runtime:ArenaRuntimeRepository;loadouts:ArenaLoadoutRepository;serverSecret:string;}
const cleanLabel=(value?:string)=>{const label=(value??'Adventurer').trim().slice(0,24);return label||'Adventurer'};
const validRequest=(value:string)=>{const clean=typeof value==='string'?value.trim():'';if(clean.length<8||clean.length>128)throw new Error('invalid_requestId');return clean};
const reward=(row:ArenaRewardEntitlement)=>({id:row.id,kind:row.kind,rewardTier:row.rewardTier,catalogVersion:row.catalogVersion,claimed:Boolean(row.claimedAtMs)});
export class ArenaApplicationService{
 private readonly runtime:ArenaRuntimeRepository;private readonly loadouts:ArenaLoadoutRepository;private readonly serverSecret:string;
 constructor(options:ArenaApplicationOptions){if(typeof options.serverSecret!=='string'||options.serverSecret.length<16)throw new Error('arena_server_secret_required');this.runtime=options.runtime;this.loadouts=options.loadouts;this.serverSecret=options.serverSecret}
 private key(seasonId:string,accountId:string){return Buffer.from(createHmac('sha256',this.serverSecret).update(`arena-opponent:${seasonId}:${accountId}`).digest()).toString('hex').slice(0,32)}
 private async freeze(accountId:string,rating:number,formation:readonly ArenaCharacterSelection[]){return freezeArenaSquad({accountId,rating,selections:formation,squadVersion:1,formationVersion:1,repository:this.loadouts})}
 async entry(accountId:string,nowMs:number):Promise<ArenaEntryProjection>{const season=await this.runtime.season(nowMs),state=await this.runtime.accountState(season.id,accountId,nowMs),defense=await this.runtime.defense(season.id,accountId),rewards=await this.runtime.pendingRewards(accountId),history=await this.runtime.history(accountId,10);return{season:{id:season.id,startsAtMs:season.startsAtMs,endsAtMs:season.endsAtMs,rating:state.rating,division:arenaDivision(state.rating),wins:state.wins,losses:state.losses,defenseWins:state.defenseWins,rewardTier:seasonRewardTier(state.rating)},defense:defense?{published:true,updatedAtMs:defense.updatedAtMs,powerBand:defense.powerBand,classes:defense.snapshot.fighters.map(f=>f.classId)}:{published:false,classes:[]},pendingRewards:rewards.map(reward),history:history.map(row=>this.historyProjection(accountId,row))}}
 private historyProjection(accountId:string,row:ArenaMatchRecord){const attacking=row.attackerAccountId===accountId,won=row.result.winnerAccountId===accountId;return{id:row.id,createdAtMs:row.createdAtMs,result:won?'win':'loss' as 'win'|'loss',opponentLabel:attacking?row.defenderLabel:row.attackerLabel,ratingDelta:attacking?row.attackerRatingDelta:row.defenderRatingDelta,score:attacking?`${row.result.scoreA}-${row.result.scoreB}`:`${row.result.scoreB}-${row.result.scoreA}`}}
 async publishDefense(accountId:string,input:{requestId:string;formation:readonly ArenaCharacterSelection[];label?:string;nowMs:number}){input={...input,requestId:validRequest(input.requestId)};const season=await this.runtime.season(input.nowMs),state=await this.runtime.accountState(season.id,accountId,input.nowMs),prior=await this.runtime.defense(season.id,accountId),snapshot=await this.freeze(accountId,state.rating,input.formation),row=await this.runtime.publishDefense({requestId:input.requestId,record:{seasonId:season.id,accountId,label:cleanLabel(input.label),snapshot,powerBand:arenaPowerBand(snapshot),rating:state.rating,updatedAtMs:input.nowMs}});return{published:true,updatedAtMs:row.updatedAtMs,powerBand:row.powerBand,classes:row.snapshot.fighters.map(f=>f.classId),previousVersion:prior?.snapshot.formationVersion??0}}
 async opponents(accountId:string,input:{formation:readonly ArenaCharacterSelection[];limit?:number;nowMs:number}){const season=await this.runtime.season(input.nowMs),state=await this.runtime.accountState(season.id,accountId,input.nowMs),self=await this.freeze(accountId,state.rating,input.formation),recent=await this.runtime.recentOpponents(season.id,accountId,8),rows=await this.runtime.defenses(season.id),picks=chooseArenaOpponents({accountId,rating:state.rating,recentOpponents:recent,powerBand:arenaPowerBand(self)},rows.map(row=>({accountId:row.accountId,rating:row.rating,recentOpponents:[],powerBand:row.powerBand})),input.limit??3);return picks.map(p=>{const row=rows.find(candidate=>candidate.accountId===p.accountId)!;return{opponentKey:this.key(season.id,row.accountId),label:row.label,rating:row.rating,division:arenaDivision(row.rating),powerBand:row.powerBand,formation:row.snapshot.fighters.map(f=>({position:f.position,classId:f.classId,role:f.role}))}})}
 async startMatch(accountId:string,input:{requestId:string;opponentKey:string;formation:readonly ArenaCharacterSelection[];label?:string;nowMs:number}){validRequest(input.requestId);const season=await this.runtime.season(input.nowMs),replay=await this.runtime.matchByRequest(season.id,accountId,input.requestId);if(replay)return this.project(accountId,replay,await this.runtime.accountState(season.id,accountId,input.nowMs));const defender=(await this.runtime.defenses(season.id)).find(row=>this.key(season.id,row.accountId)===input.opponentKey);if(!defender||defender.accountId===accountId)throw new Error('arena_opponent_not_found');const a=await this.runtime.accountState(season.id,accountId,input.nowMs),d=await this.runtime.accountState(season.id,defender.accountId,input.nowMs),attacker=await this.freeze(accountId,a.rating,input.formation),seed=Buffer.from(createHmac('sha256',this.serverSecret).update(`arena-match:${season.id}:${accountId}:${defender.accountId}:${input.requestId}:${attacker.snapshotHash}:${defender.snapshot.snapshotHash}`).digest()).toString('hex'),result=resolveArena3v3(attacker,{...structuredClone(defender.snapshot),rating:d.rating},seed),won=result.winnerAccountId===accountId,magnitude=Math.min(Math.abs(ratingDelta(a.rating,d.rating,won?1:0)),won?d.rating:a.rating),aDelta=won?magnitude:-magnitude,record={id:`arena-${createHash('sha256').update(`${season.id}:${accountId}:${input.requestId}`).digest().toString().slice(0,24)}`,seasonId:season.id,requestId:input.requestId,attackerAccountId:accountId,defenderAccountId:defender.accountId,attackerLabel:cleanLabel(input.label),defenderLabel:defender.label,attackerSnapshotHash:attacker.snapshotHash??'',defenderSnapshotHash:defender.snapshot.snapshotHash??'',result,attackerRatingBefore:a.rating,defenderRatingBefore:d.rating,attackerRatingDelta:aDelta,defenderRatingDelta:-aDelta,createdAtMs:input.nowMs};const committed=await this.runtime.commitMatch({record,attackerBonusEligible:won&&rankedBonusEligible(a.bonusWinsDay,a.bonusWinsWeek),defenderBonusEligible:!won&&defenseRewardEligible(d.defenseRewardsDay)});return this.project(accountId,committed.match,committed.attackerState)}
 private async project(accountId:string,row:ArenaMatchRecord,state:{rating:number}){const attacking=row.attackerAccountId===accountId,won=row.result.winnerAccountId===accountId,delta=attacking?row.attackerRatingDelta:row.defenderRatingDelta;return{id:row.id,createdAtMs:row.createdAtMs,result:won?'win':'loss',opponentLabel:attacking?row.defenderLabel:row.attackerLabel,ratingBefore:attacking?row.attackerRatingBefore:row.defenderRatingBefore,ratingAfter:state.rating,ratingDelta:delta,division:arenaDivision(state.rating),score:attacking?`${row.result.scoreA}-${row.result.scoreB}`:`${row.result.scoreB}-${row.result.scoreA}`,rounds:row.result.rounds,reward:undefined}}
 async claimReward(accountId:string,entitlementId:string,requestId:string,nowMs:number){validRequest(requestId);return reward(await this.runtime.claimReward(accountId,entitlementId,requestId,nowMs))}
 async history(accountId:string,limit=20){return(await this.runtime.history(accountId,Math.max(1,Math.min(50,limit)))).map(row=>this.historyProjection(accountId,row))}
}
