import type {ArenaResult,ArenaSquadSnapshot} from './arena';
import {arenaSeasonWindow,defenseRewardEligible,rankedBonusEligible,seasonRewardTier,type ArenaSeasonWindow} from './seasons';
export interface ArenaAccountState{seasonId:string;accountId:string;rating:number;wins:number;losses:number;defenseWins:number;bonusWinsDay:number;bonusWinsWeek:number;defenseRewardsDay:number;dayKey:string;weekKey:string;rewardClaimed:boolean;updatedAtMs:number;}
export interface ArenaDefenseRecord{seasonId:string;accountId:string;label:string;snapshot:ArenaSquadSnapshot;powerBand:number;rating:number;updatedAtMs:number;}
export interface ArenaMatchRecord{id:string;seasonId:string;requestId:string;attackerAccountId:string;defenderAccountId:string;attackerLabel:string;defenderLabel:string;attackerSnapshotHash:string;defenderSnapshotHash:string;result:ArenaResult;attackerRatingBefore:number;defenderRatingBefore:number;attackerRatingDelta:number;defenderRatingDelta:number;createdAtMs:number;attackerRewardEntitlementId?:string;defenderRewardEntitlementId?:string;}
export type ArenaRewardKind='ranked_win'|'defense_win'|'season';
export interface ArenaRewardEntitlement{id:string;seasonId:string;accountId:string;kind:ArenaRewardKind;rewardTier:number;catalogVersion:'arena-rewards-v1';sourceId:string;claimedAtMs?:number;claimRequestId?:string;createdAtMs:number;}
export interface ArenaRuntimeRepository{season(nowMs:number):Promise<ArenaSeasonWindow>;accountState(seasonId:string,accountId:string,nowMs:number):Promise<ArenaAccountState>;publishDefense(input:{record:ArenaDefenseRecord;requestId:string}):Promise<ArenaDefenseRecord>;defense(seasonId:string,accountId:string):Promise<ArenaDefenseRecord|undefined>;defenses(seasonId:string):Promise<ArenaDefenseRecord[]>;recentOpponents(seasonId:string,accountId:string,limit:number):Promise<string[]>;matchByRequest(seasonId:string,accountId:string,requestId:string):Promise<ArenaMatchRecord|undefined>;commitMatch(input:{record:Omit<ArenaMatchRecord,'attackerRewardEntitlementId'|'defenderRewardEntitlementId'>;attackerBonusEligible:boolean;defenderBonusEligible:boolean}):Promise<{match:ArenaMatchRecord;attackerState:ArenaAccountState;defenderState:ArenaAccountState}>;history(accountId:string,limit:number):Promise<ArenaMatchRecord[]>;pendingRewards(accountId:string):Promise<ArenaRewardEntitlement[]>;ensureSeasonReward(input:{seasonId:string;accountId:string;rating:number;sourceId:string;nowMs:number}):Promise<ArenaRewardEntitlement>;claimReward(accountId:string,id:string,requestId:string,nowMs:number):Promise<ArenaRewardEntitlement>;}
const day=(ms:number)=>new Date(ms).toISOString().slice(0,10);const week=(ms:number)=>{const d=new Date(ms),n=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-n+1);return d.toISOString().slice(0,10)};
const fresh=(seasonId:string,accountId:string,nowMs:number):ArenaAccountState=>({seasonId,accountId,rating:1000,wins:0,losses:0,defenseWins:0,bonusWinsDay:0,bonusWinsWeek:0,defenseRewardsDay:0,dayKey:day(nowMs),weekKey:week(nowMs),rewardClaimed:false,updatedAtMs:nowMs});
function reset(state:ArenaAccountState,nowMs:number){const next={...state};if(next.dayKey!==day(nowMs)){next.dayKey=day(nowMs);next.bonusWinsDay=0;next.defenseRewardsDay=0}if(next.weekKey!==week(nowMs)){next.weekKey=week(nowMs);next.bonusWinsWeek=0}return next}
export class MemoryArenaRuntimeRepository implements ArenaRuntimeRepository{
 states=new Map<string,ArenaAccountState>();defenseRows=new Map<string,ArenaDefenseRecord>();matches=new Map<string,ArenaMatchRecord>();rewards=new Map<string,ArenaRewardEntitlement>();receipts=new Map<string,string>();claimReceipts=new Map<string,string>();
 async season(nowMs:number){return arenaSeasonWindow(nowMs)}
 async accountState(seasonId:string,accountId:string,nowMs:number){const key=`${seasonId}:${accountId}`,state=reset(this.states.get(key)??fresh(seasonId,accountId,nowMs),nowMs);this.states.set(key,state);return structuredClone(state)}
 async publishDefense(input:{record:ArenaDefenseRecord;requestId:string}){const receipt=`${input.record.accountId}:${input.requestId}`,prior=this.receipts.get(receipt);if(prior){const row=this.defenseRows.get(prior);if(!row||row.snapshot.snapshotHash!==input.record.snapshot.snapshotHash)throw new Error('idempotency_conflict');return structuredClone(row)}const key=`${input.record.seasonId}:${input.record.accountId}`;this.defenseRows.set(key,structuredClone(input.record));this.receipts.set(receipt,key);return structuredClone(input.record)}
 async defense(seasonId:string,accountId:string){const row=this.defenseRows.get(`${seasonId}:${accountId}`);if(!row)return undefined;const state=this.states.get(`${seasonId}:${accountId}`);return structuredClone({...row,rating:state?.rating??row.rating})}
 async defenses(seasonId:string){return[...this.defenseRows.values()].filter(row=>row.seasonId===seasonId).map(row=>structuredClone({...row,rating:this.states.get(`${seasonId}:${row.accountId}`)?.rating??row.rating}))}
 async recentOpponents(seasonId:string,accountId:string,limit:number){return[...this.matches.values()].filter(row=>row.seasonId===seasonId&&(row.attackerAccountId===accountId||row.defenderAccountId===accountId)).sort((a,b)=>b.createdAtMs-a.createdAtMs).slice(0,limit).map(row=>row.attackerAccountId===accountId?row.defenderAccountId:row.attackerAccountId)}
 async matchByRequest(seasonId:string,accountId:string,requestId:string){const row=[...this.matches.values()].find(item=>item.seasonId===seasonId&&item.attackerAccountId===accountId&&item.requestId===requestId);return row?structuredClone(row):undefined}
 async commitMatch(input:{record:Omit<ArenaMatchRecord,'attackerRewardEntitlementId'|'defenderRewardEntitlementId'>;attackerBonusEligible:boolean;defenderBonusEligible:boolean}){const prior=await this.matchByRequest(input.record.seasonId,input.record.attackerAccountId,input.record.requestId);if(prior){if(prior.result.digest!==input.record.result.digest)throw new Error('idempotency_conflict');return{match:prior,attackerState:await this.accountState(prior.seasonId,prior.attackerAccountId,prior.createdAtMs),defenderState:await this.accountState(prior.seasonId,prior.defenderAccountId,prior.createdAtMs)}};if(input.record.attackerAccountId===input.record.defenderAccountId||input.record.attackerRatingDelta+input.record.defenderRatingDelta!==0)throw new Error('arena_rating_not_zero_sum');const a=reset(this.states.get(`${input.record.seasonId}:${input.record.attackerAccountId}`)??fresh(input.record.seasonId,input.record.attackerAccountId,input.record.createdAtMs),input.record.createdAtMs),d=reset(this.states.get(`${input.record.seasonId}:${input.record.defenderAccountId}`)??fresh(input.record.seasonId,input.record.defenderAccountId,input.record.createdAtMs),input.record.createdAtMs);if(a.rating!==input.record.attackerRatingBefore||d.rating!==input.record.defenderRatingBefore)throw new Error('arena_rating_changed');const won=input.record.result.winnerAccountId===a.accountId;if((won&&input.record.attackerRatingDelta<0)||(!won&&input.record.attackerRatingDelta>0))throw new Error('arena_rating_direction_invalid');if(a.rating+input.record.attackerRatingDelta<0||d.rating+input.record.defenderRatingDelta<0)throw new Error('arena_rating_floor_invalid');a.rating+=input.record.attackerRatingDelta;d.rating+=input.record.defenderRatingDelta;won?a.wins++:a.losses++;if(!won)d.defenseWins++;let ar:string|undefined,dr:string|undefined;if(won&&input.attackerBonusEligible&&rankedBonusEligible(a.bonusWinsDay,a.bonusWinsWeek)){a.bonusWinsDay++;a.bonusWinsWeek++;ar=this.reward(a,'ranked_win',input.record.id)}if(!won&&input.defenderBonusEligible&&defenseRewardEligible(d.defenseRewardsDay)){d.defenseRewardsDay++;dr=this.reward(d,'defense_win',input.record.id)}a.updatedAtMs=d.updatedAtMs=input.record.createdAtMs;this.states.set(`${a.seasonId}:${a.accountId}`,a);this.states.set(`${d.seasonId}:${d.accountId}`,d);const match={...structuredClone(input.record),...(ar?{attackerRewardEntitlementId:ar}:{}),...(dr?{defenderRewardEntitlementId:dr}:{})};this.matches.set(match.id,match);return{match:structuredClone(match),attackerState:structuredClone(a),defenderState:structuredClone(d)}}
 private reward(state:ArenaAccountState,kind:ArenaRewardKind,sourceId:string){const id=`arena-ent-${kind}-${state.seasonId}-${state.accountId}-${sourceId}`,prior=this.rewards.get(id);if(prior)return prior.id;const row:ArenaRewardEntitlement={id,seasonId:state.seasonId,accountId:state.accountId,kind,rewardTier:seasonRewardTier(state.rating),catalogVersion:'arena-rewards-v1',sourceId,createdAtMs:state.updatedAtMs};this.rewards.set(id,row);return id}
 async history(accountId:string,limit:number){return[...this.matches.values()].filter(row=>row.attackerAccountId===accountId||row.defenderAccountId===accountId).sort((a,b)=>b.createdAtMs-a.createdAtMs).slice(0,limit).map(row=>structuredClone(row))}
 async pendingRewards(accountId:string){return[...this.rewards.values()].filter(row=>row.accountId===accountId&&!row.claimedAtMs).sort((a,b)=>a.createdAtMs-b.createdAtMs).map(row=>structuredClone(row))}
 async ensureSeasonReward(input:{seasonId:string;accountId:string;rating:number;sourceId:string;nowMs:number}){const state=await this.accountState(input.seasonId,input.accountId,input.nowMs),id=`arena-ent-season-${input.seasonId}-${input.accountId}-${input.sourceId}`,prior=this.rewards.get(id);if(prior)return structuredClone(prior);const row:ArenaRewardEntitlement={id,seasonId:input.seasonId,accountId:input.accountId,kind:'season',rewardTier:seasonRewardTier(input.rating),catalogVersion:'arena-rewards-v1',sourceId:input.sourceId,createdAtMs:input.nowMs};this.rewards.set(id,row);return structuredClone(row)}
 async claimReward(accountId:string,id:string,requestId:string,nowMs:number){const receiptKey=`${accountId}:${requestId}`,priorId=this.claimReceipts.get(receiptKey);if(priorId&&priorId!==id)throw new Error('idempotency_conflict');const row=this.rewards.get(id);if(!row)throw new Error('arena_reward_not_found');if(row.accountId!==accountId)throw new Error('not_reward_recipient');if(row.claimedAtMs&&row.claimRequestId!==requestId)throw new Error('arena_reward_already_claimed');row.claimedAtMs??=nowMs;row.claimRequestId??=requestId;this.claimReceipts.set(receiptKey,id);return structuredClone(row)}
}
