"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PERMANENT_BOOSTS_BASE = exports.BUYABLE_PERMANENT_BOOSTS = exports.PET_PERMANENT_BOOSTS = exports.SKIN_PERMANENT_BOOSTS = void 0;
// V33 skins start as fresh full-character renders. No equipment skin is
// gameplay-active until its male and female mannequin variants are approved.
exports.SKIN_PERMANENT_BOOSTS = {
    starting: {
        id: 'starting', name: 'Campaign skin', combatSpeedMultiplier: 1,
        combatPowerMultiplier: 1, gatheringSpeedMultiplier: 1, characterXpMultiplier: 1,
        skillXpMultiplier: 1, goldMultiplier: 1, dropChanceMultiplier: 1, incomingDamageMultiplier: 1,
    },
};
exports.PET_PERMANENT_BOOSTS = {
    'pet_harvest_fox': {
        id: 'pet_harvest_fox',
        name: 'Harvest Fox',
        combatSpeedMultiplier: 1.025,
        combatPowerMultiplier: 1.02,
        gatheringSpeedMultiplier: 1.045,
        incomingDamageMultiplier: 0.985,
        skillXpMultiplier: 1.02,
        characterXpMultiplier: 1.015,
        goldMultiplier: 1.02,
        dropChanceMultiplier: 1.025,
    },
    'pet_field_mouse': {
        id: 'pet_field_mouse',
        name: 'Field Mouse',
        combatSpeedMultiplier: 1.02,
        combatPowerMultiplier: 1.01,
        gatheringSpeedMultiplier: 1.05,
        incomingDamageMultiplier: 1,
        skillXpMultiplier: 1.025,
        characterXpMultiplier: 1.02,
        goldMultiplier: 1,
        dropChanceMultiplier: 1.02,
    },
    'pet_amber_owl': {
        id: 'pet_amber_owl',
        name: 'Amber Owl',
        combatSpeedMultiplier: 1.035,
        combatPowerMultiplier: 1.03,
        incomingDamageMultiplier: 0.98,
        skillXpMultiplier: 1.02,
        characterXpMultiplier: 1.015,
        gatheringSpeedMultiplier: 1.02,
        goldMultiplier: 1.035,
        dropChanceMultiplier: 1.04,
    },
    'pet:feral_rat': {
        id: 'pet:feral_rat',
        name: 'Feral Rat',
        combatSpeedMultiplier: 1.03,
        combatPowerMultiplier: 1.02,
        gatheringSpeedMultiplier: 1.06,
        incomingDamageMultiplier: 0.985,
        skillXpMultiplier: 1.02,
        characterXpMultiplier: 1.02,
        goldMultiplier: 1,
        dropChanceMultiplier: 1.015,
    },
    'pet:emberhound': {
        id: 'pet:emberhound',
        name: 'Emberhound',
        combatSpeedMultiplier: 1.04,
        combatPowerMultiplier: 1.03,
        incomingDamageMultiplier: 0.98,
        skillXpMultiplier: 1,
        characterXpMultiplier: 1,
        gatheringSpeedMultiplier: 1.01,
        goldMultiplier: 1,
        dropChanceMultiplier: 1.03,
    },
    'pet:forgebound_mooncat': {
        id: 'pet:forgebound_mooncat',
        name: 'Forgebound Mooncat',
        combatPowerMultiplier: 1.05,
        incomingDamageMultiplier: 0.98,
        skillXpMultiplier: 1.015,
        gatheringSpeedMultiplier: 1.02,
        characterXpMultiplier: 1.015,
        goldMultiplier: 1.02,
        dropChanceMultiplier: 1.02,
    },
};
exports.BUYABLE_PERMANENT_BOOSTS = {
    'boost:combat_focus': {
        id: 'boost:combat_focus',
        name: 'Combat Focus Sigil',
        combatSpeedMultiplier: 1.08,
        combatPowerMultiplier: 1.06,
        incomingDamageMultiplier: 0.99,
        skillXpMultiplier: 1,
        characterXpMultiplier: 1,
        goldMultiplier: 1.02,
        dropChanceMultiplier: 1.02,
    },
    'boost:craftsman_charm': {
        id: 'boost:craftsman_charm',
        name: 'Craftsman Charm',
        combatSpeedMultiplier: 1,
        combatPowerMultiplier: 1,
        gatheringSpeedMultiplier: 1.06,
        skillXpMultiplier: 1.08,
        characterXpMultiplier: 1,
        goldMultiplier: 1.03,
        dropChanceMultiplier: 1.01,
        incomingDamageMultiplier: 1,
    },
    'boost:prospector_ledger': {
        id: 'boost:prospector_ledger',
        name: 'Prospector Ledger',
        gatheringSpeedMultiplier: 1.08,
        characterXpMultiplier: 1,
        skillXpMultiplier: 1.04,
        goldMultiplier: 1.06,
        dropChanceMultiplier: 1.05,
        combatSpeedMultiplier: 1,
        combatPowerMultiplier: 1,
        incomingDamageMultiplier: 1,
    },
    'boost:wardcaller_banner': {
        id: 'boost:wardcaller_banner',
        name: 'Wardcaller Banner',
        characterXpMultiplier: 1.06,
        combatSpeedMultiplier: 1.02,
        combatPowerMultiplier: 1.02,
        incomingDamageMultiplier: 0.985,
        gatheringSpeedMultiplier: 1.03,
        skillXpMultiplier: 1.02,
        goldMultiplier: 1.025,
        dropChanceMultiplier: 1.02,
    },
};
exports.PERMANENT_BOOSTS_BASE = {
    none: { id: 'none', name: 'No permanent boosts' },
    ...exports.SKIN_PERMANENT_BOOSTS,
    ...exports.PET_PERMANENT_BOOSTS,
    ...exports.BUYABLE_PERMANENT_BOOSTS,
};
