import React,{useEffect,useMemo,useState} from 'react'; import {SafeAreaView,StyleSheet,Text,Pressable,View,ActivityIndicator,Alert} from 'react-native'; import {StatusBar} from 'expo-status-bar';
import {AsyncStorageGameRepository} from './src/storage/async-storage-repository'; import {GameState,ClassId} from './src/core/types'; import {claimActivity,createCharacter,newGame,previewActivityReward,startCombat,stopActivity,startGathering,craftRecipe,claimQuest,challengeFallenKnight,equipItem,unequipItem,sellItem,salvageItem} from './src/core/game'; import {ClassSelectScreen} from './src/screens/ClassSelectScreen'; import {HomeScreen} from './src/screens/HomeScreen'; import {WorldScreen} from './src/screens/WorldScreen'; import {InventoryScreen} from './src/screens/InventoryScreen'; import {CharacterScreen} from './src/screens/CharacterScreen'; import {QuestScreen} from './src/screens/QuestScreen'; import {SkillsScreen} from './src/screens/SkillsScreen'; import {SettingsScreen} from './src/screens/SettingsScreen'; import {C} from './src/theme/theme';
type Tab='Home'|'World'|'Quests'|'Skills'|'Inventory'|'Character'|'Settings'; const repo=new AsyncStorageGameRepository();
export default function App(){const [state,setState]=useState<GameState|null>(null);const [ready,setReady]=useState(false);const [tab,setTab]=useState<Tab>('Home');const [now,setNow]=useState(Date.now());
useEffect(()=>{repo.load().then(s=>{setState(s??newGame(Date.now()));setReady(true)})},[]); useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
async function commit(next:GameState){setState(next);await repo.save(next)}
if(!ready||!state)return <SafeAreaView style={s.center}><ActivityIndicator/><Text style={s.txt}>Loading local save…</Text></SafeAreaView>;
if(!state.character)return <SafeAreaView style={s.safe}><StatusBar style="light"/><ClassSelectScreen onSelect={(id:ClassId)=>commit(createCharacter(state,id))}/></SafeAreaView>;
const preview=previewActivityReward(state,now);
return <SafeAreaView style={s.safe}><StatusBar style="light"/><View style={s.body}>{tab==='Home'&&<HomeScreen state={state} preview={preview} onClaim={()=>commit(claimActivity(state,Date.now()).state)} onStop={()=>commit(stopActivity(state))}/>} {tab==='World'&&<WorldScreen state={state} onStart={id=>{commit(startCombat(state,id,Date.now()));setTab('Home')}} onBoss={()=>{const r=challengeFallenKnight(state);commit(r.state);Alert.alert(r.won?'Victory':'Not ready',r.message)}}/>} {tab==='Quests'&&<QuestScreen state={state} onClaim={id=>commit(claimQuest(state,id))}/>} {tab==='Skills'&&<SkillsScreen state={state} onGather={id=>{commit(startGathering(state,id,Date.now()));setTab('Home')}} onCraft={id=>commit(craftRecipe(state,id))}/>} {tab==='Inventory'&&<InventoryScreen state={state} onEquip={id=>commit(equipItem(state,id))} onSell={id=>commit(sellItem(state,id))} onSalvage={id=>commit(salvageItem(state,id))}/>} {tab==='Character'&&<CharacterScreen state={state} onUnequip={slot=>commit(unequipItem(state,slot))}/>} {tab==='Settings'&&<SettingsScreen onReset={()=>Alert.alert('Reset local save?','This deletes prototype progress only.',[{text:'Cancel'},{text:'Reset',style:'destructive',onPress:async()=>{await repo.reset();setState(newGame(Date.now()));setTab('Home')}}])}/>}</View><View style={s.nav}>{(['Home','World','Quests','Skills','Inventory','Character','Settings'] as Tab[]).map(t=><Pressable accessibilityRole="tab" key={t} onPress={()=>setTab(t)} style={[s.navItem,tab===t&&s.active]}><Text style={[s.navText,tab===t&&s.activeText]}>{t}</Text></Pressable>)}</View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},center:{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center',gap:10},txt:{color:C.text},body:{flex:1},nav:{minHeight:64,flexDirection:'row',borderTopWidth:1,borderColor:C.line,backgroundColor:'#0d141e'},navItem:{flex:1,minHeight:58,alignItems:'center',justifyContent:'center',paddingHorizontal:3},active:{backgroundColor:C.panel},navText:{fontSize:11,color:C.muted,fontWeight:'700'},activeText:{color:C.accent}});
