import {strict as assert} from 'node:assert';
import {RankingApplicationService} from '../ranking-application';
import {RankingHttpApplication} from '../ranking-http-application';
import {parseRankingBoard,parseRankingLimit,parseRankingOffset} from '../ranking-api-contracts';
import type {RankingRepository} from '../ranking-persistence';
import type {RankingBoardId,RankingBoardProjection} from '../ranking-types';
class Memory implements RankingRepository{last?:{accountId:string;board:RankingBoardId;limit:number;offset:number;nowMs:number};async board(accountId:string,board:RankingBoardId,limit:number,offset:number,nowMs:number){this.last={accountId,board,limit,offset,nowMs};return{board,title:'Arena Rating',description:'Seasonal rating',unit:'rating',prestigeOnly:true,generatedAtMs:nowMs,entries:[{rank:1,entityType:'account',displayName:'Aster',value:1420,isSelf:true}],self:{listed:true,rank:1,value:1420}} as RankingBoardProjection}}
const expectThrow=(fn:()=>unknown)=>{let threw=false;try{fn()}catch{threw=true}assert.equal(threw,true)};
const main=async()=>{assert.equal(parseRankingBoard('guild'),'guild');assert.equal(parseRankingLimit('50'),50);assert.equal(parseRankingOffset('12'),12);expectThrow(()=>parseRankingBoard('combat_level'));expectThrow(()=>parseRankingLimit(101));expectThrow(()=>parseRankingOffset(-1));const repo=new Memory(),http=new RankingHttpApplication(new RankingApplicationService(repo)),board=await http.board(' account-a ',{board:'arena_rating',limit:50,offset:12},1234);assert.equal(board.entries[0].displayName,'Aster');assert.equal(repo.last?.accountId,'account-a');assert.equal(repo.last?.limit,50);assert.equal(repo.last?.offset,12);assert.equal(repo.last?.nowMs,1234);expectThrow(()=>http.board('a',{board:'arena_rating'},Number.NaN));console.log('ranking application PASS')};void main();
