import {useMemo} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import {activityQueueHandoffStatus,activityQueueLabel,MAX_ACTIVITY_QUEUE,normalizeActivityQueue,queuedActivityReadiness} from '../core/activity-queue';
import {GameButton} from './GameButton';
import {radii,spacing,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';

export function ActionQueuePanel({state,onRemove,onMove,onClear,onStartNext}:{state:GameState;onRemove:(index:number)=>void;onMove:(index:number,direction:'up'|'down')=>void;onClear:()=>void;onStartNext:()=>void}){
 const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const queue=normalizeActivityQueue(state.character?.activityQueue),paused=state.character?.activityQueuePausedReason,handoff=activityQueueHandoffStatus(state);
 if(!queue.length)return null;
 return <View style={s.panel}>
  <View style={s.header}><View style={s.flex}><Text style={s.kicker}>ACTION QUEUE · {queue.length}/{MAX_ACTIVITY_QUEUE}</Text><Text style={s.sub}>Planned stops advance automatically. Safety stops pause the queue.</Text></View>{queue.length>1&&<View style={s.clear}><GameButton compact title="Clear" tone="secondary" onPress={onClear}/></View>}</View>
  {paused&&<View style={s.pause}><Text style={s.pauseTitle}>QUEUE PAUSED</Text><Text style={s.pauseText}>{paused}</Text></View>}
  {!paused&&state.activity&&<View style={handoff.armed?(handoff.nextReady?s.handoff:s.blocked):s.waiting}><Text style={handoff.armed?(handoff.nextReady?s.handoffTitle:s.blockedTitle):s.waitingTitle}>{handoff.armed?(handoff.nextReady?'HANDOFF ARMED':'HANDOFF WILL PAUSE'):'QUEUE WAITING'}</Text><Text style={s.pauseText}>{handoff.armed?(handoff.nextReady?`${handoff.sourceLabel} → ${handoff.nextLabel}`:`${handoff.sourceLabel} can stop this activity, but ${handoff.nextLabel} cannot start yet.`):'The current activity keeps running until a Hunt Goal or non-safety Idle Rule stops it.'}</Text>{handoff.armed&&!handoff.nextReady&&handoff.nextBlocker?<Text style={s.blocker}>{handoff.nextBlocker}</Text>:null}{handoff.armed&&handoff.safetyEnabled?<Text style={s.safety}>Food/storage safety still pauses instead of advancing.</Text>:null}</View>}
  {queue.map((entry,index)=>{const readiness=queuedActivityReadiness(state,entry),label=activityQueueLabel(entry);return <View key={`${index}:${entry.kind}:${entry.targetId}`} style={s.row}><View style={s.index}><Text style={s.indexText}>{index+1}</Text></View><View style={s.flex}><Text numberOfLines={1} style={s.name}>{label}</Text><Text numberOfLines={1} style={readiness.ready?s.readyMeta:s.blockedMeta}>{entry.kind==='combat'?'Hunt':'Gathering'}{index===0?' · next':''} · {readiness.ready?'ready':readiness.blocker??'blocked'}</Text></View><View style={s.controls}><Pressable accessibilityRole="button" accessibilityLabel={`Move ${label} up`} disabled={index===0} onPress={()=>onMove(index,'up')} style={({pressed})=>[s.arrow,index===0&&s.arrowDisabled,pressed&&index>0&&s.arrowPressed]}><Text style={s.arrowText}>↑</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={`Move ${label} down`} disabled={index===queue.length-1} onPress={()=>onMove(index,'down')} style={({pressed})=>[s.arrow,index===queue.length-1&&s.arrowDisabled,pressed&&index<queue.length-1&&s.arrowPressed]}><Text style={s.arrowText}>↓</Text></Pressable><View style={s.remove}><GameButton compact title="Remove" tone="secondary" onPress={()=>onRemove(index)}/></View></View></View>})}
  {!state.activity&&!handoff.nextReady&&handoff.nextBlocker?<View style={s.blocked}><Text style={s.blockedTitle}>NEXT ACTION BLOCKED</Text><Text style={s.blocker}>{handoff.nextBlocker}</Text></View>:null}
  {!state.activity&&<GameButton title={handoff.nextReady?"Start next queued action":"Next action unavailable"} disabled={!handoff.nextReady} onPress={onStartNext}/>}
 </View>;
}

function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({
 panel:{gap:spacing.sm,padding:spacing.sm,borderWidth:1,borderColor:equipmentColors.selectedLine,borderRadius:radii.md,backgroundColor:C.panel},
 header:{flexDirection:'row',alignItems:'center',gap:spacing.sm},flex:{flex:1,minWidth:0},clear:{width:78},controls:{flexDirection:'row',alignItems:'center',gap:4},arrow:{width:36,height:36,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.bg},arrowDisabled:{opacity:.28},arrowPressed:{opacity:.65},arrowText:{color:C.accent,fontSize:18,fontWeight:'900'},remove:{width:72},
 kicker:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:.8},sub:{...typography.caption,color:C.muted},
 row:{minHeight:52,flexDirection:'row',alignItems:'center',gap:spacing.sm,padding:spacing.sm,borderRadius:radii.sm,backgroundColor:C.panel2},
 index:{width:28,height:28,alignItems:'center',justifyContent:'center',borderRadius:14,borderWidth:1,borderColor:C.info},indexText:{...typography.caption,color:C.info,fontWeight:'900'},
 name:{...typography.bodyStrong,color:C.text},meta:{...typography.caption,color:C.muted},readyMeta:{...typography.caption,color:C.good},blockedMeta:{...typography.caption,color:C.warning},
 pause:{gap:2,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:C.warning,backgroundColor:'#332515'},pauseTitle:{...typography.caption,color:C.warning,fontWeight:'900',letterSpacing:.7},pauseText:{...typography.caption,color:C.text},handoff:{gap:2,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:C.good,backgroundColor:'#172b24'},handoffTitle:{...typography.caption,color:C.good,fontWeight:'900',letterSpacing:.7},waiting:{gap:2,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:C.info,backgroundColor:C.panel2},waitingTitle:{...typography.caption,color:C.info,fontWeight:'900',letterSpacing:.7},blocked:{gap:2,padding:spacing.sm,borderLeftWidth:3,borderLeftColor:C.warning,backgroundColor:'#332515'},blockedTitle:{...typography.caption,color:C.warning,fontWeight:'900',letterSpacing:.7},blocker:{...typography.caption,color:C.warning,fontWeight:'800'},safety:{...typography.caption,color:C.muted}
});}
