import {useEffect,useState} from 'react';
import {ActivityIndicator,Alert,Modal,Pressable,StyleSheet,Text,View} from 'react-native';
import {sendFriendRequest,setPlayerBlocked,searchPlayers,type FriendProfile} from '../online/social';
import {C,equipmentColors,radii,spacing,typography} from '../theme/theme';
import {IdentityArtwork} from './SocialIdentity';

export type ChatPlayerIdentity={id?:string;account_id:string;sender_name:string};
export function ChatPlayerSheet({message,onClose,onBlocked}:{message:ChatPlayerIdentity|null;onClose:()=>void;onBlocked:(accountId:string)=>void}){
 const [profile,setProfile]=useState<FriendProfile|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;if(!message){setProfile(null);return;}setLoading(true);void searchPlayers(message.sender_name).then(rows=>{if(active)setProfile(rows.find(row=>row.account_id===message.account_id)??null);}).catch(()=>{if(active)setProfile(null);}).finally(()=>{if(active)setLoading(false)});return()=>{active=false};},[message?.id,message?.account_id]);
 if(!message)return null;
 async function addFriend(){if(busy)return;setBusy(true);try{const result=await sendFriendRequest(message!.account_id);Alert.alert('Friend request',result==='sent'?`Request sent to ${message!.sender_name}.`:result==='already_friends'?'You are already friends.':result==='already_pending'?'Your request is already pending.':'This player has already sent you a request. Open Friends to respond.');}catch(error){Alert.alert('Friend request',error instanceof Error?error.message:'Unable to send request.');}finally{setBusy(false)}}
 function confirmBlock(){Alert.alert(`Block ${message!.sender_name}?`,'Their messages will be hidden and they will be removed from your social lists.',[{text:'Cancel',style:'cancel'},{text:'Block',style:'destructive',onPress:async()=>{setBusy(true);try{await setPlayerBlocked(message!.account_id,true);onBlocked(message!.account_id);onClose();}catch(error){Alert.alert('Block player',error instanceof Error?error.message:'Unable to block player.');}finally{setBusy(false)}}}]);}
 const name=profile?.character_name??profile?.display_name??message.sender_name;
 return <Modal visible transparent animationType="fade" onRequestClose={onClose}><View style={s.scrim}><Pressable accessibilityLabel="Close player profile" onPress={onClose} style={StyleSheet.absoluteFill}/><View accessibilityViewIsModal style={s.sheet}>
  <View style={s.handle}/><View style={s.head}><IdentityArtwork name={name} className={profile?.class_id} size={58}/><View style={s.copy}><Text accessibilityRole="header" numberOfLines={1} style={s.name}>{name}</Text>{loading?<ActivityIndicator color={C.accent} size="small"/>:<><Text style={s.meta}>{profile?.level?`Level ${profile.level}`:'Adventurer'}{profile?.class_id?` · ${profile.class_id.replace(/_/g,' ')}`:''}</Text>{profile?.profile_title&&<Text style={s.title}>“{profile.profile_title}”</Text>}</>}</View><Pressable accessibilityRole="button" accessibilityLabel="Close player profile" onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View>
  <Text style={s.hint}>Player actions</Text><View style={s.actions}><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void addFriend()} style={({pressed})=>[s.primary,(pressed||busy)&&s.pressed]}><Text style={s.primaryText}>Add friend</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={confirmBlock} style={({pressed})=>[s.secondary,(pressed||busy)&&s.pressed]}><Text style={s.blockText}>Block</Text></Pressable></View>
 </View></View></Modal>;
}
const s=StyleSheet.create({scrim:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.48)'},sheet:{paddingHorizontal:spacing.lg,paddingTop:8,paddingBottom:24,backgroundColor:'#101923',borderTopWidth:StyleSheet.hairlineWidth,borderColor:C.line,borderTopLeftRadius:22,borderTopRightRadius:22},handle:{width:38,height:4,alignSelf:'center',borderRadius:2,backgroundColor:'#526174',marginBottom:14},head:{flexDirection:'row',alignItems:'center',gap:spacing.md},copy:{flex:1,minWidth:0},name:{...typography.title,color:C.text},meta:{...typography.body,color:C.muted,textTransform:'capitalize'},title:{...typography.body,color:equipmentColors.goldSoft,fontStyle:'italic'},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},closeText:{fontSize:28,lineHeight:31,color:C.muted},hint:{...typography.caption,color:C.muted,marginTop:spacing.lg,marginBottom:spacing.sm,textTransform:'uppercase',letterSpacing:.8},actions:{flexDirection:'row',gap:spacing.sm},primary:{flex:1,minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:radii.md,backgroundColor:'#23658a'},secondary:{minWidth:100,minHeight:48,alignItems:'center',justifyContent:'center',borderRadius:radii.md,backgroundColor:'#1a2430',borderWidth:StyleSheet.hairlineWidth,borderColor:C.line},primaryText:{...typography.bodyStrong,color:'#f4fbff'},blockText:{...typography.bodyStrong,color:C.bad},pressed:{opacity:.62}});
