import React,{useRef,useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {GameState} from '../core/types';
import type {GameCommand} from '../core/game-commands';
import type {CompanionSanctuaryUpgrade} from '../core/combat-companion-types';
import {COMBAT_COMPANIONS,COMPANION_RARITY_CONFIG,COMPANION_SANCTUARY_CONFIG} from '../content/combat-companions';
import {combatCompanionUiModel,companionXpToNextLevel,companionSanctuaryUpgradeCost,companionCombatContribution} from '../core/combat-companions';
import {companionView,companionEconomy,assertCompanionIdle,companionUnlockFacts} from '../core/companion-runtime';
import {COMPANION_MISSIONS,COMPANION_SPECIAL_CHALLENGES,COMPANION_WEEKLY_CHALLENGES,companionTrialSeasonDefinition,companionTechniques,companionTrialRecommendedPower} from '../../../../backend/src/server/companions/content';
import {companionMaterialName,companionMaterialSources,companionRequirementProgress,companionRecoverySeconds} from '../core/companion-presentation';
import {companionTeamPower} from '../../../../backend/src/server/companions/team';
import {techniqueUnlocked} from '../../../../backend/src/server/companions/progression-v2';
import {validateCompanionMissionTeam} from '../../../../backend/src/server/companions/assignments';
import {validateSpecialCompanionChallenge} from '../../../../backend/src/server/companions/special-challenges';
import {Panel} from './Panel';
import {MonsterPortraitFrame} from './MonsterPortraitFrame';
import {MONSTERS} from '../content/monsters';
import {GameButton} from './GameButton';
import {eventCompanionSourceById} from '../theme/event-collectible-assets';
import {C,equipmentColors,radii,spacing,typography} from '../theme/theme';

const sections=['Collection','Sanctuary','Trials','Expeditions','Codex'] as const;
const roleGlyph={damage:'⚔',tank:'◆',support:'✦'};
const collectionFilters=['All','Owned','Damage','Tank','Support','Event'] as const;
type CollectionFilter=typeof collectionFilters[number];
const rarityLine={standard:'#52616d',rare:'#4d9de0',elite:'#a86bea',prestige:'#e5a737'} as const;
const portraitIds=['IRONWOOD_WOLF','OATHBOUND_SQUIRE','FIELD_WISP','VENOM_WEAVER','FOREST_TROLL','ECHO_BAT','MIRE_HERON','THORNLING','CAVE_SKITTER','LANTERN_WRETCH'];
const named=(id:string)=>COMBAT_COMPANIONS.find(c=>c.id===id)?.name??companionMaterialName(id);
const amount=(value:number)=>value.toLocaleString('en');
export function CombatCompanionPanel({state,now,onCommand}:{state:GameState;now:number;onCommand:(command:GameCommand)=>Promise<void>}){
  const [section,setSection]=useState<typeof sections[number]>('Collection'),[selection,setSelection]=useState('UNIT_001'),[collectionFilter,setCollectionFilter]=useState<CollectionFilter>('All'),[filterOpen,setFilterOpen]=useState(false),[team,setTeam]=useState<string[]>([]),[mission,setMission]=useState(COMPANION_MISSIONS[0].id),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const lock=useRef(false),view=companionView(state,now),model=combatCompanionUiModel(state,selection),e=companionEconomy(state),progress=model?.progress;
  const equipped=state.character?.equippedCombatCompanionId,contribution=companionCombatContribution(state),run=view.trial.progress.season.activeRun;
  const recovery=companionRecoverySeconds(state,now),season=companionTrialSeasonDefinition(view.trial.progress.season.seasonKey);
  const safeTeam=team.filter(id=>!!view.owned[id]);
  const act=async(type:string,args?:Record<string,unknown>)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await onCommand({type,args});setMessage('Saved.');}catch(error){setMessage(error instanceof Error?error.message:'Unable to complete action.');}finally{lock.current=false;setBusy(false);}};
  const btn=(title:string,type:string,args?:Record<string,unknown>,disabled=false)=> <GameButton title={title} disabled={busy||disabled} onPress={()=>void act(type,args)}/>;
  const idle=(id:string)=>{try{assertCompanionIdle(state,id);return true;}catch{return false;}};
  const ownedIds=Object.keys(view.owned),visibleCompanions=COMBAT_COMPANIONS.filter(def=>collectionFilter==='All'||collectionFilter==='Owned'&&!!view.owned[def.id]||collectionFilter==='Event'&&def.origin.type==='event'||collectionFilter==='Damage'&&def.role==='damage'||collectionFilter==='Tank'&&def.role==='tank'||collectionFilter==='Support'&&def.role==='support'),teamRoles=new Set(safeTeam.map(id=>COMBAT_COMPANIONS.find(c=>c.id===id)?.role)),trialTeamValid=safeTeam.length===3&&teamRoles.size===3&&safeTeam.every(idle);
  const selectedIndex=Math.max(0,COMBAT_COMPANIONS.findIndex(def=>def.id===selection)),selectedMonster=MONSTERS.find(monster=>monster.id===portraitIds[selectedIndex%portraitIds.length]),selectedEventPortrait=eventCompanionSourceById.get(selection);
  const assistPct=Math.round(contribution.contributionPct*1000)/10;
  const teamSelector=<View style={s.group}><Text style={s.body}>Choose up to three companions. Trials require one Tank, one Damage and one Support.</Text>{ownedIds.length?ownedIds.map(id=>{const def=COMBAT_COMPANIONS.find(c=>c.id===id)!;const selected=safeTeam.includes(id),available=idle(id);return <Pressable key={id} accessibilityRole="checkbox" accessibilityState={{checked:selected,disabled:busy||!available}} disabled={busy||!available} style={[s.choice,selected&&s.selected]} onPress={()=>setTeam(selected?safeTeam.filter(x=>x!==id):[...safeTeam.slice(-2),id])}><Text style={s.name}>{selected?'✓ ':''}{roleGlyph[def.role]} {def.name}</Text><Text style={s.body}>{def.role} · Lv. {view.owned[id].level} · {available?'Available':'Busy'}</Text></Pressable>}):<Text style={s.body}>Unlock companions through the Collection requirements.</Text>}<Text style={s.name}>Team Power {amount(companionTeamPower(safeTeam,view.owned))}</Text></View>;
  const affordability=(cost:{gold:number;companionEssence:number;bondstones?:number;materialId?:string;materialQuantity?:number}|undefined)=>!!cost&&e.gold>=cost.gold&&e.companionEssence>=cost.companionEssence&&e.bondstones>=(cost.bondstones??0)&&(!cost.materialId||(e.materials[cost.materialId]??0)>=(cost.materialQuantity??0));
  const costText=(cost:{gold:number;companionEssence:number;bondstones?:number;materialId?:string;materialQuantity?:number})=>`${amount(cost.gold)} Gold · ${amount(cost.companionEssence)} Essence${cost.bondstones?` · ${cost.bondstones} Bondstones`:''}${cost.materialId?` · ${cost.materialQuantity} ${named(cost.materialId)}`:''}`;
  return <Panel><Text accessibilityRole="header" style={s.heading}>Combat Companions</Text><Text style={s.body}>{equipped?(idle(equipped)?`${named(equipped)} is assisting you.`:`${named(equipped)} is busy and cannot assist you until its activity ends.`):'One tactical companion can assist your character.'}</Text><Text style={s.body}>Choose a different role from your character. Passive pets keep their separate collection bonuses.</Text>
    <Text style={s.resources}>{amount(e.companionEssence)} <Text style={{color:'#b9dff0'}}>Essence</Text> · {amount(e.bondstones)} <Text style={{color:equipmentColors.goldSoft}}>Bondstones</Text> · {amount(e.gold)} <Text style={{color:'#f2c14e'}}>Gold</Text></Text>
    <View style={s.rosterSummary}><View style={s.summaryCell}><Text style={s.summaryLabel}>ROSTER</Text><Text style={s.summaryValue}>{ownedIds.length}/{COMBAT_COMPANIONS.length}</Text></View><View style={s.summaryCell}><Text style={s.summaryLabel}>EQUIPPED</Text><Text numberOfLines={1} style={s.summaryValue}>{equipped?named(equipped):'None'}</Text></View><View style={s.summaryCell}><Text style={s.summaryLabel}>ASSIST</Text><Text style={s.summaryValue}>{assistPct?`+${assistPct}%`:'—'}</Text></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{sections.map(tab=><Pressable key={tab} accessibilityRole="tab" accessibilityState={{selected:section===tab}} onPress={()=>setSection(tab)} style={({pressed})=>[s.tab,section===tab&&s.selected,pressed&&s.pressed]}><Text style={[s.tabText,section===tab&&s.tabTextSelected]}>{tab}</Text></Pressable>)}</ScrollView>
    {message?<View accessibilityLiveRegion="polite" style={s.messageCard}><Text style={s.messageLabel}>COMPANION UPDATE</Text><Text style={s.message}>{message.replace(/_/g,' ')}</Text></View>:null}
    {section==='Sanctuary'&&<View style={s.group}><Text style={s.name}>Expedition supplies · {e.materials.SUPPLIES??0} owned</Text><Text style={s.body}>Five supplies cost 250 Gold. Expedition Pens required.</Text>{btn('Buy 5 supplies · 250 Gold','companion_supplies',undefined,e.gold<250||!(state.account.companionSanctuary?.expeditionPensLevel))}</View>}
    {section==='Trials'&&<View style={s.group}><Text style={s.name}>Fallen Knight rematch</Text><Text style={s.body}>One attempt per UTC day after the story victory. Winning grants 40 Essence, 1 Bondstone, and boss progression. Story loot is not repeated.</Text><Text style={s.body}>Victories: {Math.max(state.defeatedBossIds.includes('FALLEN_KNIGHT')?1:0,state.account.companionBossClears?.FALLEN_KNIGHT??0)}</Text>{btn(now<(state.account.companionBossRematchReadyAtMs??0)?'Next attempt at 00:00 UTC':'Challenge the Fallen Knight','companion_boss_rematch',undefined,!state.defeatedBossIds.includes('FALLEN_KNIGHT')||now<(state.account.companionBossRematchReadyAtMs??0))}</View>}
    {section==='Collection'&&<>
    <ScrollView horizontal contentContainerStyle={s.tabs}>{COMBAT_COMPANIONS.map((def,index)=>{const portrait=MONSTERS.find(monster=>monster.id===portraitIds[index%portraitIds.length]),eventPortrait=eventCompanionSourceById.get(def.id);return <Pressable key={def.id} accessibilityRole="button" accessibilityState={{selected:selection===def.id}} style={[s.card,selection===def.id&&s.selected]} onPress={()=>setSelection(def.id)}>{eventPortrait?<Image source={eventPortrait} resizeMode="contain" style={s.eventPortrait}/>:portrait?<MonsterPortraitFrame monster={portrait} size={62} framed={false}/>:<Text style={s.glyph}>{roleGlyph[def.role]}</Text>}<Text style={s.name}>{def.name}</Text><Text style={s.body}>{COMPANION_RARITY_CONFIG[def.rarity].label} · {def.role}</Text><Text style={s.body}>{view.owned[def.id]?`Lv. ${view.owned[def.id].level}${equipped===def.id?' · Equipped':''}`:'Locked'}</Text></Pressable>})}</ScrollView>
      {model&&<View style={s.group}><Text style={s.heading}>{model.def.name}</Text><Text style={s.body}>{model.def.origin.name} · {model.def.description}</Text><Text style={s.name}>{model.def.activeAbility.name}</Text><Text style={s.body}>{model.def.activeAbility.description} · {model.def.activeAbility.cooldownSeconds}s cooldown</Text><Text style={s.body}>{model.def.passiveAbility.description}</Text><Text style={s.body}>Bond 10: {model.def.bondTrait.description}</Text>
        {!model.owned?<><Text style={s.name}>Unlock requirements</Text>{model.def.unlockRequirements.map((req,i)=>{const p=companionRequirementProgress(state,req);return <Text key={i} style={s.body}>{p.complete?'✓':'•'} {req.description} · {p.current}/{p.total}</Text>})}<Text style={s.body}>Unlocks when all requirements are met. Requirements tied to unreleased game content remain locked.</Text></>:progress&&<>
          <Text style={s.body}>Ascension material: {named(model.def.ascensionMaterialId??'')} · {companionMaterialSources(model.def.ascensionMaterialId??'').slice(0,3).join(' / ')}</Text>
          {btn(state.account.companionBondRewardClaims?.includes(`${selection}:2`)?'Bond 2 reward claimed':'Bond 2 reward · 20 Essence','companion_bond_reward',{id:selection},progress.bondLevel<2||!!state.account.companionBondRewardClaims?.includes(`${selection}:2`))}
          <Text style={s.resources}>Level {progress.level}/{model.maxLevel} · Cap {model.levelCap} · Ascension {progress.ascensionTier}</Text><Text style={s.body}>XP {progress.xp}/{progress.level>=model.maxLevel?'Maximum level':progress.level>=model.levelCap?'Ascension required':companionXpToNextLevel(model.def.rarity,progress.level)} · Bond {progress.bondLevel}/10 ({progress.bondXp} total XP)</Text>
          {model.equipped?btn('Unequip','companion_unequip'):btn(model.compatible?'Equip companion':'Same role as your character','companion_equip',{id:selection},!model.compatible||!idle(selection))}
          {model.nextLevelCost&&<><Text style={s.body}>{costText(model.nextLevelCost)}</Text>{btn('Train one level','companion_level',{id:selection},!idle(selection)||!affordability(model.nextLevelCost))}</>}
          {model.nextAscensionCost&&<><Text style={s.body}>{costText(model.nextAscensionCost)}</Text>{btn(`Ascend to tier ${model.nextAscensionTier}`,'companion_ascend',{id:selection},!idle(selection)||!affordability(model.nextAscensionCost))}</>}
          {model.def.rarity==='prestige'&&progress.level===35&&!progress.mastered&&btn('Complete Prestige Mastery','companion_master',{id:selection},!idle(selection))}
          <Text style={s.name}>Techniques</Text>{companionTechniques(selection).map(t=><View key={t.id} style={s.choice}><Text style={s.name}>{t.name}</Text><Text style={s.body}>{t.description}</Text>{btn(progress.selectedTechniqueId===t.id?'Selected':!progress.selectedTechniqueId?'Choose technique (first choice free)':'Switch technique · 2,500 Gold + 80 Essence','companion_technique',{id:selection,technique:t.id},!idle(selection)||!techniqueUnlocked(view.owned[selection],t.id)||progress.selectedTechniqueId===t.id||!!progress.selectedTechniqueId&&(e.gold<2500||e.companionEssence<80))}</View>)}<Text style={s.body}>Techniques require both Ascension II and Bond 7.</Text>
        </>}
      </View>}
    </>}
    {section==='Sanctuary'&&<View style={s.group}>{(Object.entries(COMPANION_SANCTUARY_CONFIG) as [CompanionSanctuaryUpgrade,typeof COMPANION_SANCTUARY_CONFIG[CompanionSanctuaryUpgrade]][]).map(([id,cfg])=>{const cost=companionSanctuaryUpgradeCost(state,id),level=state.account.companionSanctuary?.[`${id}Level`]??0;return <View key={id} style={s.choice}><Text style={s.name}>{id.replace(/([A-Z])/g,' $1')} · {level}/{cfg.maxLevel}</Text><Text style={s.body}>{cfg.description}</Text>{cost&&<Text style={s.body}>{costText(cost)}</Text>}{btn(cost?'Upgrade':'Maximum level','companion_upgrade',{id},!cost||!affordability(cost))}</View>})}{btn('Claim daily training XP','companion_training',undefined,!(state.account.companionSanctuary?.trainingGroundLevel))}{btn('Claim weekly Essence','companion_essence',undefined,!(state.account.companionSanctuary?.essenceBasinLevel))}<Text style={s.body}>Training claims cap at 7 days; Essence claims cap at 2 weeks. Training excludes busy companions.</Text><Text style={s.name}>Companion materials</Text>{Object.entries(state.account.companionMaterials??{}).filter(([,n])=>n>0).map(([id,n])=><Text key={id} style={s.body}>{named(id)} ×{n}</Text>)}</View>}
    {section==='Trials'&&<View style={s.group}><Text style={s.name}>{view.trial.projection.title}</Text><Text style={s.body}>Monthly best {view.trial.projection.currentSeasonHighestFloor}/30 · Lifetime best {view.trial.projection.lifetimeHighestFloor}/30</Text><Text style={s.body}>Resets {view.trial.projection.endsAt.slice(0,10)} at 00:00 UTC. Companion progression is permanent.</Text>
      {recovery>0&&<View accessibilityLiveRegion="polite" style={s.messageCard}><Text style={s.messageLabel}>RECOVERY</Text><Text style={s.message}>Recovering from battle · {recovery}s before the next fight.</Text></View>}
      {season.specialChallenges.map(id=>{const c=COMPANION_WEEKLY_CHALLENGES.find(c=>c.id===id)!;const claimed=view.trial.progress.season.monthlyChallengeClaims?.includes(id);return <View key={id} style={s.choice}><Text style={s.name}>Monthly challenge: {c.name}</Text><Text style={s.body}>{c.description}</Text><Text style={s.body}>{c.rewards.gold} Gold · {c.rewards.companionEssence} Essence · {c.rewards.bondstones} Bondstones</Text>{btn(claimed?'Claimed':'Claim monthly reward','companion_monthly',{id},claimed||!view.trial.progress.season.monthlyChallengeCompletion[id])}</View>})}
      {run?<><Text style={s.name}>Floor {run.currentFloor} · Recommended Power {companionTrialRecommendedPower(run.currentFloor)}</Text><Text style={s.body}>{run.teamCompanionIds.map(named).join(' · ')}</Text>{btn('Fight next floor','companion_trial_floor',{id:run.runId,floor:run.currentFloor},recovery>0)}{btn('Abandon run','companion_trial_abandon',{id:run.runId})}</>:<>{teamSelector}{btn(`Start at checkpoint ${view.trial.projection.checkpointFloor}`,'companion_trial_start',{ids:safeTeam},!trialTeamValid)}{view.trial.projection.checkpointFloor>1&&btn('Replay from Floor 1','companion_trial_start',{ids:safeTeam,floor:1},!trialTeamValid)}</>}
      {state.account.companionLastBattle&&<View style={s.choice}><Text style={s.name}>{state.account.companionLastBattle.title}: {state.account.companionLastBattle.won?'Victory':'Defeat'}</Text><Text style={s.body}>{(state.account.companionLastBattle.durationMs/1000).toFixed(1)} seconds · +{state.account.companionLastBattle.essence} Essence · +{state.account.companionLastBattle.gold} Gold · +{state.account.companionLastBattle.bondstones} Bondstones</Text></View>}
      <Text style={s.heading}>Weekly Proving Grounds</Text>{view.weekly.definitions.map(d=><View key={d.id} style={s.choice}><Text style={s.name}>{d.name}</Text><Text style={s.body}>{d.description} · {view.proving.state.progress[d.id]??0}/{d.targetCount}</Text>{btn(view.proving.state.claimedIds.includes(d.id)?'Claimed':'Claim reward','companion_weekly',{id:d.id},!view.proving.state.completedIds.includes(d.id)||view.proving.state.claimedIds.includes(d.id))}</View>)}
      <Text style={s.heading}>Special challenges</Text>{COMPANION_SPECIAL_CHALLENGES.filter(c=>!!COMBAT_COMPANIONS.find(d=>d.id===c.rewardCompanionId)).map(c=>{const valid=validateSpecialCompanionChallenge({challengeId:c.id,facts:companionUnlockFacts(state),teamIds:safeTeam,owned:view.owned,busyCompanionIds:new Set(ownedIds.filter(id=>!idle(id)))});return <View key={c.id} style={s.choice}><Text style={s.name}>{c.name}</Text>{c.requirements.map((r,i)=><Text key={i} style={s.body}>• {r.description}</Text>)}{btn('Challenge','companion_special',{id:c.id,ids:safeTeam},!valid.ok||!!state.account.companionSpecialClears?.includes(c.id))}</View>})}
    </View>}
    {section==='Expeditions'&&<View style={s.group}>{teamSelector}<Text style={s.name}>Sanctuary assignments</Text>{COMPANION_MISSIONS.map(m=><Pressable key={m.id} accessibilityRole="radio" accessibilityState={{selected:mission===m.id}} style={[s.choice,mission===m.id&&s.selected]} onPress={()=>setMission(m.id)}><Text style={s.name}>{m.name}</Text><Text style={s.body}>{m.durationMs/3600000}h · {m.minCompanions}–{m.maxCompanions} companions · Pen {m.minimumPenLevel??1} · {m.costs.gold} Gold</Text><Text style={s.body}>Recommended Power {m.recommendedPower} · Base reward {m.baseRewards.companionEssence} Essence</Text></Pressable>)}{(()=>{const check=validateCompanionMissionTeam({missionId:mission,companionIds:safeTeam,owned:view.owned,assignments:view.assignments,equippedCompanionIds:new Set(equipped?[equipped]:[]),lockedTrialCompanionIds:new Set(run?.teamCompanionIds??[]),expeditionPensLevel:state.account.companionSanctuary?.expeditionPensLevel??0});return <>{!check.ok&&<Text style={s.body}>{check.reason.replace(/_/g,' ')}</Text>}{btn('Send assignment','companion_assignment_start',{id:mission,ids:safeTeam},!check.ok)}</>})()}{view.assignments.map(a=><View key={a.assignmentId} style={s.choice}><Text style={s.name}>{COMPANION_MISSIONS.find(m=>m.id===a.missionId)?.name}</Text><Text style={s.body}>{a.companionIds.map(named).join(' · ')} · {a.status}</Text><Text style={s.body}>{a.endsAt.replace('T',' ').slice(0,16)} UTC</Text>{btn(a.status==='claimed'?'Claimed':'Claim assignment','companion_assignment_claim',{id:a.assignmentId},a.status!=='completed')}</View>)}</View>}
    {section==='Codex'&&<View style={s.group}><Text style={s.name}>{view.codex.summary.totalOwned}/{COMBAT_COMPANIONS.length} companions collected</Text><Text style={s.body}>Favorite: {view.codex.favoriteCompanionId?named(view.codex.favoriteCompanionId):'None'} · Showcase slots {view.codex.showcaseSlotsUnlocked}</Text>{ownedIds.map(id=><View key={id} style={s.choice}><Text style={s.name}>{named(id)}</Text>{btn(view.codex.favoriteCompanionId===id?'Favorite':'Make favorite','companion_showcase',{id,ids:view.codex.showcaseCompanionIds},view.codex.favoriteCompanionId===id)}{btn(view.codex.showcaseCompanionIds.includes(id)?'Remove from showcase':'Add to showcase','companion_showcase',{id:view.codex.favoriteCompanionId,ids:view.codex.showcaseCompanionIds.includes(id)?view.codex.showcaseCompanionIds.filter(x=>x!==id):[...view.codex.showcaseCompanionIds,id]},!view.codex.showcaseCompanionIds.includes(id)&&view.codex.showcaseCompanionIds.length>=view.codex.showcaseSlotsUnlocked)}</View>)}{view.codex.milestones.map(m=><View key={m.id} style={s.choice}><Text style={s.name}>{m.name}</Text>{btn(m.claimed?'Claimed':'Claim milestone','companion_codex',{id:m.id},m.claimed||!m.complete)}</View>)}</View>}
  </Panel>;
}
const s=StyleSheet.create({heading:{...typography.title,color:C.text},name:{...typography.bodyStrong,color:C.text},body:{...typography.body,color:C.muted},resources:{...typography.bodyStrong,color:C.accent},messageCard:{gap:3,padding:spacing.sm,borderWidth:1,borderColor:C.info,borderRadius:8,backgroundColor:'#102536'},messageLabel:{...typography.caption,color:C.info,fontWeight:'900',letterSpacing:1},message:{...typography.body,color:C.text},tabs:{gap:6,paddingVertical:6},tab:{minHeight:38,paddingHorizontal:12,borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg,justifyContent:'center'},selected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},tabText:{fontSize:12,fontWeight:'700',color:C.muted},tabTextSelected:{color:'#d9f3ff'},pressed:{opacity:.76},card:{width:176,padding:12,gap:6,borderWidth:1,borderColor:C.line,borderRadius:radii.md},eventPortrait:{width:62,height:62,alignSelf:'center'},glyph:{fontSize:28,color:C.accent},group:{gap:12},choice:{padding:12,gap:8,borderWidth:1,borderColor:C.line,borderRadius:radii.md}});
