import React from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {CharacterCustomization,DEFAULT_CUSTOMIZATION,HAIR_COLORS,HAIR_STYLES,SKIN_TONES} from '../core/customization';
import {BodyPresentation} from '../core/types';
import {hairAppearance,READY_HAIR_STYLES,skinAppearance} from '../theme/customization-assets';
import {C,radii,spacing,typography} from '../theme/theme';

const colorOf=(value:CharacterCustomization)=>HAIR_COLORS.find(x=>x.id===value.hairColor)?.color;
export function CustomizationSummary({value}:{value:CharacterCustomization}){return <Text style={s.summary}>{SKIN_TONES.find(x=>x.id===value.skinTone)?.name} skin  ·  {HAIR_STYLES.find(x=>x.id===value.hairStyle)?.name}{value.hairStyle!=='bald'?`  ·  ${HAIR_COLORS.find(x=>x.id===value.hairColor)?.name}`:''}</Text>}
export function CharacterAvatar({body,view,value,compact=false}:{body:BodyPresentation;view:'front'|'back';value:CharacterCustomization;compact?:boolean}){const hair=hairAppearance(value.hairStyle,body,view);return <View accessible accessibilityLabel={`${body}, ${value.skinTone} skin, ${value.hairStyle} ${value.hairStyle==='bald'?'':value.hairColor+' hair'}, ${view} view`} style={compact?s.avatarCompact:s.avatarBox}><Image source={skinAppearance(value.skinTone,body,view)} resizeMode="contain" style={s.avatarFill}/>{!!hair&&<Image source={hair} resizeMode="contain" style={[s.avatarFill,s.overlay,{tintColor:colorOf(value)}]}/>}</View>}
function Section({title,hint,children}:{title:string;hint:string;children:React.ReactNode}){return <View style={s.section}><View style={s.headingRow}><Text style={s.title}>{title}</Text><Text style={s.hint}>{hint}</Text></View>{children}</View>}

export function CustomizationControls({body,view,value,onChange}:{body:BodyPresentation;view:'front'|'back';value:CharacterCustomization;onChange:(value:CharacterCustomization)=>void}){
  return <View style={s.root}>
    <View style={s.stage}><View style={s.glow}/><View style={s.cornerTL}/><View style={s.cornerBR}/><Text style={s.stageTitle}>APPEARANCE</Text><Text style={s.viewBadge}>{view.toUpperCase()}</Text><CharacterAvatar body={body} view={view} value={value}/><View style={s.pedestal}/><View style={s.stageSummary}><CustomizationSummary value={value}/></View></View>
    <Section title="Skin tone" hint="Choose your complexion"><View style={s.swatches}>{SKIN_TONES.map(tone=><Pressable key={tone.id} accessibilityRole="radio" accessibilityLabel={`${tone.name} skin tone`} accessibilityState={{selected:value.skinTone===tone.id}} onPress={()=>onChange({...value,skinTone:tone.id})} style={[s.colorChoice,value.skinTone===tone.id&&s.colorActive]}><View style={[s.swatch,{backgroundColor:tone.color}]}/>{value.skinTone===tone.id&&<Text style={s.check}>✓</Text>}</Pressable>)}</View><Text style={s.selection}>{SKIN_TONES.find(x=>x.id===value.skinTone)?.name}</Text></Section>
    <Section title="Hairstyle" hint="Swipe to browse"><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.hairRow}>{HAIR_STYLES.map(style=>{const ready=READY_HAIR_STYLES.has(style.id),source=hairAppearance(style.id,body,'front');return <Pressable key={style.id} disabled={!ready} accessibilityRole="radio" accessibilityState={{selected:value.hairStyle===style.id,disabled:!ready}} onPress={()=>onChange({...value,hairStyle:style.id})} style={[s.hairCard,value.hairStyle===style.id&&s.hairActive,!ready&&s.locked]}><View style={s.hairPreview}>{style.id==='bald'?<Text style={s.bald}>◯</Text>:source?<Image source={source} resizeMode="contain" style={[s.hairImage,{tintColor:colorOf(value)}]}/>:<Text style={s.lock}>◆</Text>}</View><Text numberOfLines={2} style={[s.hairName,value.hairStyle===style.id&&s.selected]}>{style.name}</Text>{!ready&&<Text style={s.soon}>COMING SOON</Text>}</Pressable>})}</ScrollView></Section>
    <Section title="Hair color" hint={value.hairStyle==='bald'?'Choose hair first':'Palette color'}><View style={s.swatches}>{HAIR_COLORS.map(color=><Pressable key={color.id} disabled={value.hairStyle==='bald'} accessibilityRole="radio" accessibilityLabel={`${color.name} hair`} accessibilityState={{selected:value.hairColor===color.id,disabled:value.hairStyle==='bald'}} onPress={()=>onChange({...value,hairColor:color.id})} style={[s.colorChoice,value.hairColor===color.id&&s.colorActive,value.hairStyle==='bald'&&s.locked]}><View style={[s.swatch,{backgroundColor:color.color}]}/>{value.hairColor===color.id&&value.hairStyle!=='bald'&&<Text style={s.check}>✓</Text>}</Pressable>)}</View><Text style={s.selection}>{value.hairStyle==='bald'?'Not applied':HAIR_COLORS.find(x=>x.id===value.hairColor)?.name}</Text></Section>
    <Pressable accessibilityRole="button" onPress={()=>onChange({...DEFAULT_CUSTOMIZATION})} style={s.reset}><Text style={s.resetText}>↺  Reset appearance</Text></Pressable>
  </View>;
}

const s=StyleSheet.create({root:{gap:spacing.md},stage:{height:342,overflow:'hidden',alignItems:'center',backgroundColor:'#111c29',borderRadius:18,borderWidth:1,borderColor:'#765e2f',paddingTop:spacing.sm},glow:{position:'absolute',top:62,width:210,height:210,borderRadius:105,backgroundColor:'#1c3040'},cornerTL:{position:'absolute',left:10,top:10,width:28,height:28,borderLeftWidth:2,borderTopWidth:2,borderColor:C.accent},cornerBR:{position:'absolute',right:10,bottom:10,width:28,height:28,borderRightWidth:2,borderBottomWidth:2,borderColor:C.accent},stageTitle:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:2},viewBadge:{position:'absolute',right:spacing.md,top:spacing.md,...typography.caption,color:C.muted,borderWidth:1,borderColor:C.line,borderRadius:99,paddingHorizontal:spacing.sm,paddingVertical:spacing.xs},avatarBox:{position:'absolute',top:28,width:244,height:305},avatarCompact:{width:116,height:154},avatarFill:{width:'100%',height:'100%'},overlay:{position:'absolute'},pedestal:{position:'absolute',bottom:34,width:138,height:12,borderRadius:99,backgroundColor:'rgba(0,0,0,.35)'},stageSummary:{position:'absolute',bottom:10},summary:{...typography.caption,color:C.text,fontWeight:'800'},section:{gap:spacing.sm,backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:radii.lg,padding:spacing.md},headingRow:{flexDirection:'row',alignItems:'baseline',justifyContent:'space-between',gap:spacing.sm},title:{...typography.title,color:C.text},hint:{...typography.caption,color:C.muted,textAlign:'right'},swatches:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm},colorChoice:{width:46,height:46,borderRadius:23,borderWidth:2,borderColor:'transparent',alignItems:'center',justifyContent:'center'},colorActive:{borderColor:C.accent,backgroundColor:C.panel2},swatch:{width:32,height:32,borderRadius:16,borderWidth:1,borderColor:'#05080c'},check:{position:'absolute',color:'#fff',fontSize:16,fontWeight:'900'},selection:{...typography.caption,color:C.accent,fontWeight:'800'},hairRow:{gap:spacing.sm,paddingRight:spacing.sm},hairCard:{width:92,minHeight:126,alignItems:'center',padding:spacing.sm,gap:spacing.xs,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.bg},hairActive:{borderColor:C.accent,borderWidth:2,backgroundColor:C.panel2},hairPreview:{height:70,width:74,alignItems:'center',justifyContent:'center',overflow:'hidden'},hairImage:{width:74,height:92},bald:{fontSize:46,color:C.muted},lock:{fontSize:24,color:C.disabled},hairName:{...typography.caption,color:C.text,fontWeight:'800',textAlign:'center'},selected:{color:C.accent},soon:{fontSize:8,color:C.disabled,fontWeight:'900'},locked:{opacity:.4},reset:{minHeight:48,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:radii.md},resetText:{...typography.bodyStrong,color:C.muted}});
