import {useGameLanguage} from '../i18n/GameLanguageProvider';
import {progressionT,progressionText,progressionEnvironmentText,type ProgressionKey} from '../i18n/progression';
import {useMemo} from 'react';
import {ScrollView,StyleSheet,Text,View} from 'react-native';
import type {ActivityKind} from '../core/types';
import {EnvironmentEffect,environmentEffect,seasonEffect,SEASON_DEFINITIONS,weatherChancesForSeason,weatherEffect,WEATHER_DEFINITIONS,WorldEnvironment} from '../core/world-weather';
import {equipmentTheme,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {GameModalHeader,GameModalSurface} from './GameModalSurface';
import {EnvironmentArtwork} from './EnvironmentArtwork';

const activities:Array<{kind:ActivityKind;label:string}>=[{kind:'combat',label:'Combat'},{kind:'mining',label:'Mining'},{kind:'woodcutting',label:'Woodcutting'},{kind:'fishing',label:'Fishing'}];
function remaining(changesAtMs:number,nowMs:number,t:(key:ProgressionKey,params?:Record<string,string|number>)=>string){const minutes=Math.max(0,Math.ceil((changesAtMs-nowMs)/60000)),hours=Math.floor(minutes/60),rest=minutes%60;return hours?t("{hours}h {minutes}m",{hours,minutes:rest}):t("{minutes}m",{minutes:rest});}
function seasonRemaining(changesAtMs:number,nowMs:number,t:(key:ProgressionKey,params?:Record<string,string|number>)=>string){const hours=Math.max(0,Math.ceil((changesAtMs-nowMs)/3600000)),days=Math.floor(hours/24),rest=hours%24;return days?t("{days}d {hours}h",{days,hours:rest}):t("{hours}h",{hours:rest});}
function notes(value:string[]){return value.length?value.join(' · '):'No modifier';}
function exactMetrics(effect:EnvironmentEffect){
  const values=[{label:'Cycle time',delta:effect.actionTimeMultiplier-1,lowerIsBetter:true},{label:'XP',delta:effect.xpMultiplier-1},{label:'Gold',delta:effect.goldMultiplier-1},{label:'Yield',delta:effect.itemMultiplier-1},{label:'Drop chance',delta:effect.dropChanceMultiplier-1}];
  return values.filter(value=>Math.abs(value.delta)>.0001).map(value=>({...value,beneficial:value.lowerIsBetter?value.delta<0:value.delta>0,text:`${value.delta>0?'+':''}${Math.round(value.delta*100)}%`}));
}

export function EnvironmentDetailsModal({visible,environment,nowMs,locked,activityKind,reduceMotion=false,onClose}:{visible:boolean;environment:WorldEnvironment;nowMs:number;locked:boolean;activityKind?:ActivityKind;reduceMotion?:boolean;onClose:()=>void}){
  const contextLanguage=useGameLanguage(),language=contextLanguage;
  const t=(key:ProgressionKey,params?:Record<string,string|number>)=>progressionT(language,key,params);
  const p=(text:string)=>progressionText(language,text);

  const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
  const season=SEASON_DEFINITIONS[environment.seasonId],weather=WEATHER_DEFINITIONS[environment.weatherId];
  const orderedActivities=activityKind?[...activities.filter(entry=>entry.kind===activityKind),...activities.filter(entry=>entry.kind!==activityKind)]:activities;
  return <GameModalSurface visible={visible} reduceMotion={reduceMotion} onClose={onClose} backdropLabel={t("Close season and weather details")}>
      <GameModalHeader eyebrow={t("REGIONAL CONDITIONS")} title={environment.zoneName} onClose={onClose}/>
      <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false}>
        <View style={s.hero}><EnvironmentArtwork type="season" id={environment.seasonId} size={54}/><View style={s.iconDivider}/><EnvironmentArtwork type="weather" id={environment.weatherId} size={54}/><View style={s.heroCopy}><Text style={s.heroTitle}>{progressionEnvironmentText(language,season.name)} · {progressionEnvironmentText(language,weather.name)}</Text><Text style={s.timer}>{locked?t("These conditions are locked to your active task"):t("Weather changes in {time}",{time:remaining(environment.changesAtMs,nowMs,t)})}</Text><Text style={s.seasonTimer}>{t("Next season in {time}",{time:seasonRemaining(environment.seasonChangesAtMs,nowMs,t)})}</Text></View></View>
        <View style={[s.ruleCard,{borderColor:season.color}]}><Text style={[s.ruleTitle,{color:season.color}]}>{progressionEnvironmentText(language,season.name).toUpperCase()} · {progressionEnvironmentText(language,season.months)}</Text><Text style={s.description}>{progressionEnvironmentText(language,season.description)}</Text>{activities.map(({kind,label})=><View key={kind} style={s.effectRow}><Text style={s.effectLabel}>{p(label)}</Text><Text style={s.effectValue}>{progressionEnvironmentText(language,notes(seasonEffect(kind,environment.seasonId).notes))}</Text></View>)}</View>
        <View style={[s.ruleCard,{borderColor:weather.color}]}><Text style={[s.ruleTitle,{color:weather.color}]}>{progressionEnvironmentText(language,weather.name).toUpperCase()} · {t("TODAY")}</Text><Text style={s.description}>{progressionEnvironmentText(language,weather.description)}</Text>{activities.map(({kind,label})=><View key={kind} style={s.effectRow}><Text style={s.effectLabel}>{p(label)}</Text><Text style={s.effectValue}>{progressionEnvironmentText(language,notes(weatherEffect(kind,environment.weatherId).notes))}</Text></View>)}</View>
        <View style={s.combined}><Text style={s.combinedTitle}>{t("CURRENT COMBINED EFFECTS")}</Text><Text style={s.combinedHint}>{t("Exact totals after season and weather stack. Lower cycle time means faster actions.")}</Text>{orderedActivities.map(({kind,label})=>{const effect=environmentEffect(kind,environment),metrics=exactMetrics(effect),active=kind===activityKind;return <View key={kind} style={[s.combinedRow,active&&s.combinedRowActive]}><View style={s.combinedRowHead}><Text style={[s.effectLabel,active&&s.activeLabel]}>{p(label)}</Text>{active&&<Text style={s.activeBadge}>{t("ACTIVE")}</Text>}</View><Text style={s.combinedValue}>{progressionEnvironmentText(language,notes(effect.notes))}</Text><View style={s.metricList}>{metrics.length?metrics.map(metric=><View key={metric.label} style={[s.metric,{borderColor:metric.beneficial?C.good:C.bad}]}><Text style={s.metricLabel}>{p(metric.label)}</Text><Text style={[s.metricValue,{color:metric.beneficial?C.good:C.bad}]}>{metric.text}</Text></View>):<Text style={s.noMetric}>{t("No numeric change")}</Text>}</View></View>})}</View>
        <View style={s.pool}><Text style={s.poolTitle}>{t("Possible {season} weather",{season:progressionEnvironmentText(language,season.name)})}</Text><View style={s.poolList}>{weatherChancesForSeason(environment.seasonId).map(entry=>{const def=WEATHER_DEFINITIONS[entry.weatherId],current=entry.weatherId===environment.weatherId;return <View key={entry.weatherId} style={[s.poolItem,current&&{borderColor:def.color,backgroundColor:C.infoSurface}]}><EnvironmentArtwork type="weather" id={entry.weatherId} size={25}/><Text numberOfLines={1} style={s.poolName}>{progressionEnvironmentText(language,def.name)}</Text><Text style={s.poolChance}>{Math.round(entry.chance*100)}%</Text></View>})}</View></View>
        <Text style={s.footnote}>{t("Weather is rolled deterministically for each region at 00:00 UTC from that season’s weighted weather pool. Season and weather modifiers stack multiplicatively. Starting an activity snapshots its conditions until rewards are collected or the activity changes.")}</Text>
      </ScrollView>
  </GameModalSurface>;
}

function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({content:{gap:spacing.md,paddingBottom:spacing.md},hero:{minHeight:76,flexDirection:'row',alignItems:'center',gap:spacing.sm,backgroundColor:equipmentColors.panelRaised,borderWidth:1,borderColor:equipmentColors.line,padding:spacing.sm,borderRadius:10},iconDivider:{width:1,height:38,backgroundColor:equipmentColors.line},heroCopy:{flex:1,minWidth:0},heroTitle:{...typography.title,color:C.text},timer:{...typography.caption,color:C.info},seasonTimer:{fontSize:10,color:C.muted,marginTop:2},ruleCard:{gap:spacing.xs,backgroundColor:equipmentColors.panel,borderWidth:1,borderRadius:10,padding:spacing.md},ruleTitle:{...typography.bodyStrong,fontWeight:'900',letterSpacing:.7},description:{...typography.body,color:C.muted,marginBottom:spacing.xs},effectRow:{minHeight:32,flexDirection:'row',alignItems:'center',gap:spacing.sm,borderTopWidth:1,borderTopColor:C.line,paddingTop:spacing.xs},effectLabel:{...typography.caption,color:C.muted,fontWeight:'900',width:82},effectValue:{...typography.caption,color:C.text,flex:1},combined:{gap:spacing.sm,backgroundColor:C.accentSurface,borderWidth:1,borderColor:equipmentColors.gold,padding:spacing.md,borderRadius:10},combinedTitle:{...typography.bodyStrong,color:equipmentColors.goldSoft,fontWeight:'900'},combinedHint:{...typography.caption,color:C.muted},combinedRow:{gap:spacing.xs,borderTopWidth:1,borderTopColor:C.line,paddingTop:spacing.sm},combinedRowActive:{marginHorizontal:-spacing.xs,paddingHorizontal:spacing.xs,paddingBottom:spacing.xs,borderWidth:1,borderColor:equipmentColors.selectedLine,borderRadius:8,backgroundColor:equipmentColors.selected},combinedRowHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},activeLabel:{color:C.text},activeBadge:{fontSize:9,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:.8},combinedValue:{...typography.caption,color:C.text,fontWeight:'700'},metricList:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs},metric:{flexDirection:'row',alignItems:'center',gap:4,borderWidth:1,borderRadius:99,paddingHorizontal:7,paddingVertical:3,backgroundColor:C.panel2},metricLabel:{fontSize:9,color:C.muted,fontWeight:'800'},metricValue:{fontSize:10,fontWeight:'900'},noMetric:{...typography.caption,color:C.muted},pool:{gap:spacing.sm},poolTitle:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',letterSpacing:.7},poolList:{flexDirection:'row',flexWrap:'wrap',gap:spacing.xs},poolItem:{width:'48%',minHeight:42,flexDirection:'row',alignItems:'center',gap:spacing.xs,padding:spacing.xs,borderWidth:1,borderColor:C.line,borderRadius:8,backgroundColor:equipmentColors.panel},poolName:{flex:1,fontSize:10,color:C.text,fontWeight:'800'},poolChance:{fontSize:10,color:C.muted,fontWeight:'900'},footnote:{...typography.caption,color:C.muted,lineHeight:18}});}
