import React,{useMemo} from 'react';
import {StyleSheet,Text,View} from 'react-native';
import {equipmentTheme,radii,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';

export interface EquipmentSetProgressV33{setName:string;crafted:number;required:number;complete:boolean;thresholds:readonly {pieces:number;active:boolean}[];}
export function EquipmentSetProgressPanel({progress}:{progress:EquipmentSetProgressV33}){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
 return <View style={s.card}><Text style={s.eyebrow}>SET COLLECTION · V33</Text><View style={s.head}><View style={s.flex}><Text style={s.title}>{progress.setName}</Text><Text style={s.count}>{progress.crafted}/{progress.required} pieces · {progress.complete?'Complete':'In progress'}</Text></View><Text style={[s.complete,progress.complete?s.completeOn:s.completeOff]}>{progress.complete?'10/10':'BUILDING'}</Text></View><View style={s.thresholds}>{progress.thresholds.map(t=><View key={t.pieces} style={[s.threshold,t.active&&s.thresholdReached]}><Text style={[s.pieces,t.active&&s.piecesReached]}>{t.pieces}</Text><Text style={[s.state,t.active&&s.stateReached]}>{t.active?'REACHED':'LOCKED'}</Text></View>)}</View><Text style={s.note}>All ten V33 slots count toward set collection progress. Runtime combat effects are handled separately from this collection view.</Text></View>
}
function makeStyles(C:ThemeColors){const E=equipmentTheme(C);return StyleSheet.create({card:{padding:spacing.md,borderRadius:radii.md,borderWidth:1,borderColor:E.line,backgroundColor:E.panel,gap:spacing.sm},head:{flexDirection:'row',alignItems:'center',gap:spacing.sm},flex:{flex:1,minWidth:0},eyebrow:{...typography.caption,fontWeight:'900',color:E.goldSoft,letterSpacing:.8},title:{...typography.title,color:C.text},count:{...typography.caption,color:C.muted},complete:{fontSize:8,lineHeight:11,fontWeight:'900',letterSpacing:.5,paddingHorizontal:7,paddingVertical:4,borderWidth:1,borderRadius:99},completeOn:{color:C.good,borderColor:C.good,backgroundColor:C.goodSurface},completeOff:{color:C.muted,borderColor:C.line,backgroundColor:C.panel2},thresholds:{flexDirection:'row',gap:5},threshold:{flex:1,minWidth:0,alignItems:'center',gap:2,paddingVertical:7,paddingHorizontal:3,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2,opacity:.68},thresholdReached:{opacity:1,borderColor:C.good,backgroundColor:C.goodSurface},pieces:{fontSize:11,color:C.muted,fontWeight:'900'},piecesReached:{color:C.good},state:{fontSize:6.5,lineHeight:9,color:C.muted,fontWeight:'900',letterSpacing:.3},stateReached:{color:C.good},note:{fontSize:8.5,lineHeight:12,color:C.muted}});}
