import {memo} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {ItemDef} from '../content/items';
import type {GearSlot} from '../core/types';
import {itemRarity,rarityMeta} from '../core/item-rarity';
import {C,equipmentColors,radii,spacing,touchTargetPreferred,typography} from '../theme/theme';
import {EquipmentArtwork,hasEquipmentArtwork} from './EquipmentArtwork';

const SLOT_MARKS:Record<GearSlot,string>={helmet:'◠',amulet:'◇',chest:'⛨',ring:'○',gloves:'✦',weapon:'⚔',legs:'║',offhand:'◈',boots:'⌑',cape:'▾'};

export const EquipmentSlot=memo(function EquipmentSlot({slot,label,item,rank=0,socketed=0,socketCapacity=0,selected,disabled=false,onPress}:{slot:GearSlot;label:string;item?:ItemDef;rank?:number;socketed?:number;socketCapacity?:number;selected:boolean;disabled?:boolean;onPress:()=>void}){
  const meta=item?rarityMeta(itemRarity(item)):undefined,hasArt=!!item&&hasEquipmentArtwork(item);
  return <Pressable accessibilityRole="button" accessibilityLabel={item?`${label}: ${item.name}, ${meta?.label}`:`${label}: empty`} accessibilityState={{selected,disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.root,meta&&{borderColor:meta.color,backgroundColor:meta.surface},selected&&s.selected,pressed&&!disabled&&s.pressed,disabled&&s.disabled]}>
    <Text style={s.slotLabel}>{label}</Text><View style={s.art}>{item&&hasArt?<EquipmentArtwork item={item}/>:<View style={[s.placeholder,item&&s.placeholderPending]}><Text style={[s.placeholderMark,item&&s.placeholderMarkPending]}>{SLOT_MARKS[slot]}</Text><Text numberOfLines={1} style={s.placeholderText}>{item?'ART PENDING':'EMPTY'}</Text></View>}</View>
    <Text numberOfLines={2} style={[s.itemName,!item&&s.empty]}>{item?.name??'Empty slot'}</Text>{meta&&<Text style={[s.rarity,{color:meta.color}]}>{meta.symbol} {meta.label}</Text>}{item&&rank>0&&<View pointerEvents="none" style={s.rankBadge}><Text style={s.rankText}>+{rank}</Text></View>}{item&&socketCapacity>0&&<View pointerEvents="none" style={s.socketBadge}><Text style={s.socketText}>◆ {socketed}/{socketCapacity}</Text></View>}{selected&&<View pointerEvents="none" style={s.selectedCorner}><Text style={s.selectedMark}>✓</Text></View>}
  </Pressable>;
});
const s=StyleSheet.create({rankBadge:{position:'absolute',left:4,top:28,minWidth:27,paddingHorizontal:4,paddingVertical:2,borderWidth:1,borderColor:equipmentColors.gold,backgroundColor:'#07111c',borderRadius:radii.sm},rankText:{fontSize:10,color:equipmentColors.goldSoft,fontWeight:'900'},socketBadge:{position:'absolute',left:4,bottom:4,paddingHorizontal:4,paddingVertical:2,backgroundColor:'#07111c',borderWidth:1,borderColor:'#7455b8',borderRadius:radii.sm},socketText:{fontSize:9,color:'#c9a7ff',fontWeight:'900'},root:{position:'relative',width:'48.5%',minHeight:148,minWidth:touchTargetPreferred,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:equipmentColors.stage,padding:spacing.sm,alignItems:'center',gap:spacing.xs,overflow:'hidden'},selected:{borderWidth:2,borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},pressed:{opacity:.78,transform:[{translateY:1}]},disabled:{opacity:.45},slotLabel:{...typography.caption,color:equipmentColors.goldSoft,fontWeight:'900',textTransform:'uppercase',letterSpacing:.7},art:{height:66,justifyContent:'center'},placeholder:{width:64,height:64,borderWidth:1,borderColor:C.line,backgroundColor:'rgba(4,10,17,.55)',alignItems:'center',justifyContent:'center'},placeholderPending:{borderColor:equipmentColors.lineStrong,backgroundColor:'rgba(114,90,43,.12)'},placeholderMark:{fontSize:24,color:C.muted,lineHeight:28},placeholderMarkPending:{color:equipmentColors.goldSoft},placeholderText:{fontSize:8,color:C.muted,fontWeight:'900',letterSpacing:.4},itemName:{...typography.caption,color:C.text,textAlign:'center',fontWeight:'800',minHeight:32},empty:{color:C.muted,fontWeight:'600'},rarity:{fontSize:10,fontWeight:'900'},selectedCorner:{position:'absolute',right:3,top:3,width:22,height:22,borderLeftWidth:1,borderBottomWidth:1,borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.stage,alignItems:'center',justifyContent:'center'},selectedMark:{fontSize:11,color:equipmentColors.selectedLine,fontWeight:'900'}});
