import {useMemo} from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import type {GameState,GatheringSkillId} from '../core/types';
import {GATHERING} from '../content/skills';
import {HERB_NODES} from '../content/herbalism';
import {itemDef} from '../content/items';
import {currentRegionId} from '../core/combat-region';
import {WORLD_ZONES} from '../content/world-map';
import {formatGameNumber} from '../core/number-format';
import {Panel} from './Panel';
import {ResourceArtwork} from './ResourceArtwork';
import {GameButton} from './GameButton';
import {spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {bestGatheringTrainingDestination,gatheringProgressionAction} from '../core/skill-progression-navigation';
import type {WorkingTowardDestination} from '../core/working-toward';
import {formatBalanceDuration,gatheringBalanceProjection,skillTargetEta} from '../core/balance-projection';

export function GatheringActivityList({state,skillId,skillLevel,offlineHours,queueFull,preferredActionId,onGather,onQueueGather,onNavigate}:{state:GameState;skillId:GatheringSkillId;skillLevel:number;offlineHours:number;queueFull:boolean;preferredActionId?:string;onGather:(id:string)=>void;onQueueGather:(id:string)=>void;onNavigate?:(destination:WorkingTowardDestination)=>void}){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
 const all=[...GATHERING,...HERB_NODES].filter(row=>row.skillId===skillId);
 const regionId=currentRegionId(state),region=WORLD_ZONES.find(row=>row.id===regionId)??WORLD_ZONES[0];
 const regional=all.filter(row=>row.zoneId===region.id).sort((a,b)=>Number(b.id===preferredActionId)-Number(a.id===preferredActionId)||a.unlockLevel-b.unlockLevel).map(activity=>({activity,view:gatheringBalanceProjection(state,activity,offlineHours)}));
 const fastest=[...regional].filter(row=>skillLevel>=row.activity.unlockLevel).sort((a,b)=>b.view.xpPerHour-a.view.xpPerHour)[0];
 const next=[...all].filter(row=>row.unlockLevel>skillLevel).sort((a,b)=>a.unlockLevel-b.unlockLevel)[0];
 const nextZone=next?WORLD_ZONES.find(row=>row.id===next.zoneId):undefined,nextAction=next?gatheringProgressionAction(state,next):undefined,trainingDestination=bestGatheringTrainingDestination(state,skillId),nextEta=next&&fastest?skillTargetEta(state,skillId,next.unlockLevel,fastest.view.xpPerHour):undefined;
 return <>
  <View style={s.guidanceRow}>
   <View style={[s.guidanceCard,s.fastCard]}><Text style={s.guidanceLabel}>FASTEST XP HERE</Text><Text numberOfLines={1} style={s.guidanceValue}>{fastest?.activity.name??'No unlocked node'}</Text><Text style={s.guidanceHint}>{fastest?formatGameNumber(Math.round(fastest.view.xpPerHour),state.settings.numberMode)+' XP/hr · next level ~'+formatBalanceDuration(fastest.view.levelPace.etaSeconds):'Travel or level up to continue.'}</Text></View>
   {next&&nextAction&&onNavigate?<Pressable accessibilityRole="button" accessibilityLabel={nextAction.label+' for '+next.name} onPress={()=>onNavigate(nextAction.destination)} style={({pressed})=>[s.guidanceCard,s.nextCard,pressed&&s.pressed]}><Text style={s.guidanceLabel}>NEXT SKILL UNLOCK</Text><Text numberOfLines={1} style={s.guidanceValue}>Lv {next.unlockLevel} · {next.name}</Text><Text style={s.guidanceHint}>{nextZone?.name??next.zoneId}{nextEta?.etaSeconds!==undefined?' · ~'+formatBalanceDuration(nextEta.etaSeconds)+' at fastest here':''} · {nextAction.label} ›</Text></Pressable>:<View style={s.guidanceCard}><Text style={s.guidanceLabel}>NEXT SKILL UNLOCK</Text><Text numberOfLines={1} style={s.guidanceValue}>{next?'Lv '+next.unlockLevel+' · '+next.name:'Skill path complete'}</Text><Text style={s.guidanceHint}>{next?(nextZone?.name??next.zoneId):'No higher-level node configured.'}</Text></View>}
  </View>
  {regional.map(({activity,view})=>{
   const active=state.activity?.targetId===activity.id,target=preferredActionId===activity.id,unlocked=skillLevel>=activity.unlockLevel,fastestXp=fastest?.activity.id===activity.id,resource=itemDef(activity.itemId),pacing=view.pacing;
   return <Panel key={activity.id} accentColor={active?C.good:target?C.accent:fastestXp?C.info:undefined}>
    <View style={s.heading}><ResourceArtwork itemId={activity.itemId} size={58}/><View style={s.flex}><View style={s.nameRow}><Text style={s.name}>{activity.name}</Text>{target?<Text style={s.targetTag}>TARGET</Text>:null}{fastestXp?<Text style={s.fastTag}>FASTEST XP</Text>:null}{!unlocked?<Text style={s.lockTag}>LV {activity.unlockLevel}</Text>:null}</View><Text style={s.sub}>{resource.name} · {activity.min===activity.max?activity.min:activity.min+'–'+activity.max}/action · every {view.cycleSeconds.toFixed(1)}s</Text></View>{activity.recommendedToolTier>0?<View style={[s.tierBadge,pacing.atRecommendedTier?s.tierReady:s.tierSlow]}><Text style={s.tierText}>T{activity.recommendedToolTier}</Text></View>:<View style={[s.tierBadge,s.handBadge]}><Text style={s.handText}>HAND</Text></View>}</View>
    <View style={s.rateStrip}><View style={s.rateCell}><Text style={s.rateLabel}>EST. YIELD / HR</Text><Text numberOfLines={1} style={s.rateValue}>~{formatGameNumber(Math.round(view.runtimeItemsPerHour),state.settings.numberMode)} {resource.name}</Text></View><View style={s.rateCell}><Text style={s.rateLabel}>SKILL XP / HR</Text><Text style={s.rateValue}>{formatGameNumber(Math.round(view.xpPerHour),state.settings.numberMode)}</Text></View><View style={s.rateCell}><Text style={s.rateLabel}>MASTERY</Text><Text numberOfLines={1} style={s.rateValue}>R{view.rank.rank} · {view.rank.mastered?'MAX':Math.round(view.rank.progress*100)+'%'}</Text><Text numberOfLines={1} style={s.masteryBonus}>{view.masteryBonus}</Text></View></View>
    <View style={s.levelProgress}><View style={s.levelProgressHead}><Text style={s.levelProgressLabel}>{view.levelPace.level>=100?'LEVEL 100 · MAX':view.levelPace.label.toUpperCase()+' · LV '+view.levelPace.level+' → '+view.levelPace.nextLevel}</Text><Text style={s.levelProgressEta}>{view.levelPace.level>=100?'MAX':'~'+formatBalanceDuration(view.levelPace.etaSeconds)}</Text></View><View style={s.levelTrack}><View style={[s.levelFill,{width:((view.levelPace.level>=100?100:Math.max(2,view.levelPace.progress*100))+'%') as `${number}%`}]}/></View><Text style={s.levelProgressMeta}>{view.levelPace.level>=100?'Maximum skill level reached':formatGameNumber(Math.ceil(view.levelPace.remainingXp),state.settings.numberMode)+' XP remaining at current pace'}</Text></View>
    <Text style={pacing.atRecommendedTier?s.readyText:s.slowText}>{pacing.atRecommendedTier?(pacing.tool?pacing.tool.name+' meets the recommended pace for this node.':'No tool tier is required for this node.'):'Recommended: '+(pacing.recommended?.name??'higher-tier tool')+'. Current pace is ×'+pacing.timeMultiplier.toFixed(2)+' before weather.'}</Text>
    <Text style={s.pacing}>{offlineHours}h AFK estimate: {formatGameNumber(view.capActions,state.settings.numberMode)} actions · {formatGameNumber(view.capItems,state.settings.numberMode)}+ items · {formatGameNumber(view.capXp,state.settings.numberMode)} XP</Text>
    <View style={s.actions}><View style={s.queue}><GameButton disabled={!unlocked||queueFull} title={queueFull?'Queue full':'Queue'} tone="secondary" onPress={()=>onQueueGather(activity.id)}/></View><View style={s.start}>{!unlocked&&onNavigate?<GameButton title={'Train to Lv '+activity.unlockLevel} tone="secondary" onPress={()=>onNavigate(gatheringProgressionAction(state,activity).destination)}/>:<GameButton disabled={!unlocked||active} title={active?'Currently gathering':!unlocked?'Requires '+skillId+' level '+activity.unlockLevel:'Gather '+activity.name} onPress={()=>onGather(activity.id)}/>}</View></View>
   </Panel>;
  })}
  {regional.length===0?<View style={s.unavailableBox}><Text style={s.unavailable}>No {skillId} activity is available in {region.name}.</Text>{trainingDestination&&onNavigate?<GameButton compact title={'regionId' in trainingDestination&&trainingDestination.regionId&&trainingDestination.regionId!==region.id?'Go to training region':'Open training'} tone="secondary" onPress={()=>onNavigate(trainingDestination)}/>:null}</View>:null}
 </>;
}

function makeStyles(C:ThemeColors){return StyleSheet.create({
 flex:{flex:1,minWidth:0},guidanceRow:{flexDirection:'row',gap:8},guidanceCard:{flex:1,minWidth:0,padding:9,borderWidth:1,borderColor:C.line,borderRadius:10,backgroundColor:C.panel},nextCard:{borderColor:C.accent},fastCard:{borderColor:C.info,backgroundColor:C.infoSurface},guidanceLabel:{fontSize:9,color:C.muted,fontWeight:'900',letterSpacing:.7},guidanceValue:{...typography.bodyStrong,color:C.text},guidanceHint:{...typography.caption,color:C.muted},
 heading:{minHeight:62,flexDirection:'row',alignItems:'center',gap:spacing.sm},nameRow:{flexDirection:'row',alignItems:'center',flexWrap:'wrap',gap:6},name:{...typography.title,color:C.text},sub:{...typography.caption,color:C.muted},targetTag:{fontSize:9,color:C.accent,fontWeight:'900',letterSpacing:.6},fastTag:{fontSize:9,color:C.info,fontWeight:'900',letterSpacing:.6},lockTag:{fontSize:9,color:C.warning,fontWeight:'900',letterSpacing:.6},
 tierBadge:{minWidth:42,height:36,alignItems:'center',justifyContent:'center',borderWidth:1,borderRadius:8},handBadge:{borderColor:C.special,backgroundColor:C.specialSurface},handText:{fontSize:9,color:C.special,fontWeight:'900',letterSpacing:.5},tierReady:{borderColor:C.good,backgroundColor:C.goodSurface},tierSlow:{borderColor:C.warning,backgroundColor:C.warningSurface},tierText:{...typography.bodyStrong,color:C.text},
 rateStrip:{flexDirection:'row',gap:6,paddingVertical:2},rateCell:{flex:1,minWidth:0},rateLabel:{fontSize:8.5,color:C.muted,fontWeight:'900',letterSpacing:.65},rateValue:{...typography.caption,color:C.text,fontWeight:'800'},masteryBonus:{fontSize:8.5,lineHeight:11,color:C.info,fontWeight:'800'},levelProgress:{gap:4,padding:7,borderWidth:1,borderColor:C.info,borderRadius:8,backgroundColor:C.infoSurface},levelProgressHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},levelProgressLabel:{fontSize:8.5,color:C.info,fontWeight:'900',letterSpacing:.55},levelProgressEta:{...typography.caption,color:C.text,fontWeight:'900'},levelTrack:{height:6,borderRadius:3,overflow:'hidden',backgroundColor:C.bg},levelFill:{height:'100%',backgroundColor:C.info},levelProgressMeta:{fontSize:9,lineHeight:12,color:C.muted,fontWeight:'700'},
 readyText:{...typography.caption,color:C.good,fontWeight:'800',paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderWidth:1,borderColor:C.good,borderRadius:8,backgroundColor:C.goodSurface},slowText:{...typography.caption,color:C.warning,fontWeight:'800',paddingHorizontal:spacing.sm,paddingVertical:spacing.xs,borderWidth:1,borderColor:C.warning,borderRadius:8,backgroundColor:C.warningSurface},pacing:{...typography.caption,color:C.info},
 actions:{flexDirection:'row',gap:8},queue:{flex:1},start:{flex:2},unavailableBox:{gap:8,padding:spacing.md,borderWidth:1,borderColor:C.line,borderRadius:8,backgroundColor:C.panel},unavailable:{...typography.body,color:C.muted},pressed:{opacity:.72}
});}
