import React from 'react';
import {Pressable,StyleSheet,Text,View} from 'react-native';
import {projectFocusLabel,projectProgressPercent,type GuildProjectView} from '../core/guild-projects-v18';
export function GuildProjectDetailPanel({project,onDonate,onClaim}:{project:GuildProjectView;onDonate?:Function;onClaim?:Function}){
 return <View style={s.panel}><Text style={s.eyebrow}>GUILD PROJECT · {projectFocusLabel(project.focus).toUpperCase()}</Text><Text style={s.title}>{project.name}</Text><Text style={s.copy}>{project.description}</Text><View style={s.row}><Text style={s.stat}>{projectProgressPercent(project)}%</Text><Text style={s.meta}>{project.meaningfulContributors}/{project.minimumMeaningfulContributors} meaningful contributors</Text></View>
 {project.kind!=='development'&&<><View style={s.track}><View style={[s.fill,{width:`${Math.min(100,projectProgressPercent(project))}%`}]} /></View><View style={s.split}><Text style={s.combat}>Combat {project.combatPoints.toLocaleString()}</Text><Text style={s.skill}>Skilling {project.skillingPoints.toLocaleString()}</Text></View><Text style={s.meta}>You: {project.personalPoints.toLocaleString()} · Today {project.dailyPoints.toLocaleString()}/{project.dailyCap.toLocaleString()}</Text></>}
 {project.resourceGoals.map(g=><View key={`${g.resourceKind}:${g.resourceId}`} style={s.goal}><View style={{flex:1}}><Text style={s.goalTitle}>{g.label}</Text><Text style={s.meta}>{g.current.toLocaleString()} / {g.target.toLocaleString()}</Text></View><Pressable style={s.button} onPress={()=>onDonate?.(project.id,g)}><Text style={s.buttonText}>Donate</Text></Pressable></View>)}
 <Text style={s.section}>Contributors</Text>{project.members.slice(0,12).map(m=><View key={m.accountId} style={s.member}><View style={{flex:1}}><Text style={s.memberName}>{m.displayName}</Text><Text style={s.meta}>{m.role}{m.rewardEligible?' · reward eligible':''}</Text></View><Text style={s.points}>{m.points.toLocaleString()}</Text></View>)}
 {project.status==='completed'&&project.canClaimCompletionReward&&!project.completionRewardClaimed&&<Pressable style={s.claim} onPress={()=>onClaim?.(project.id)}><Text style={s.claimText}>Claim completion reward</Text></Pressable>}
 </View>
}
const s=StyleSheet.create({panel:{backgroundColor:'#0f1822',borderWidth:1,borderColor:'#394d5f',borderRadius:12,padding:13,gap:8},eyebrow:{color:'#88a8bd',fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:'#f1dfa8',fontSize:20,fontWeight:'900'},copy:{color:'#b9c6cf',fontSize:11,lineHeight:16},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},stat:{color:'#ead79d',fontWeight:'900',fontSize:20},meta:{color:'#8498a6',fontSize:9},track:{height:8,backgroundColor:'#22313d',borderRadius:4,overflow:'hidden'},fill:{height:'100%',backgroundColor:'#9b7b3c'},split:{flexDirection:'row',justifyContent:'space-between'},combat:{color:'#d89278',fontSize:10,fontWeight:'900'},skill:{color:'#8dc2ad',fontSize:10,fontWeight:'900'},goal:{flexDirection:'row',alignItems:'center',gap:8,backgroundColor:'#15232e',borderRadius:8,padding:8},goalTitle:{color:'#e4eaee',fontWeight:'900'},button:{backgroundColor:'#1b3446',borderColor:'#4f7993',borderWidth:1,borderRadius:6,paddingHorizontal:10,paddingVertical:6},buttonText:{color:'#d8edf8',fontSize:10,fontWeight:'900'},section:{color:'#c9b574',fontSize:11,fontWeight:'900',marginTop:2},member:{flexDirection:'row',alignItems:'center',paddingVertical:6,borderBottomWidth:1,borderBottomColor:'#243440'},memberName:{color:'#e6edf0',fontWeight:'900'},points:{color:'#ead79d',fontWeight:'900'},claim:{backgroundColor:'#294331',borderColor:'#57805f',borderWidth:1,borderRadius:7,padding:9,alignItems:'center'},claimText:{color:'#d8efdc',fontWeight:'900'}})
