
import {useMemo} from 'react';
import type {ReactNode} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameState} from '../core/types';
import {itemInspectModel} from '../core/item-inspect';
import {rarityNameColor} from '../core/item-rarity';
import {formatGameNumber} from '../core/number-format';
import {equipmentCraftingPath} from '../core/equipment-crafting-path';
import {radii,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {EquipmentArtwork,hasEquipmentArtwork} from './EquipmentArtwork';
import {GatheringToolArtwork} from './GatheringToolArtwork';
import {ResourceArtwork} from './ResourceArtwork';
import {hasResourceArtwork} from '../theme/resource-assets';
import {GemArtwork} from './GemArtwork';
import {hasGemArtworkV1} from '../theme/gem-assets';
import type {WorkingTowardDestination} from '../core/working-toward';

function InspectArt({state,itemId}:{state:GameState;itemId:string}){
  const C=useGameTheme(),model=itemInspectModel(state,itemId),item=model.item;
  if(item.type==='gear'&&hasEquipmentArtwork(item))return <EquipmentArtwork item={item} framed={false}/>;
  if(item.type==='tool')return <GatheringToolArtwork itemId={item.id} size={72} framed={false}/>;
  if(hasGemArtworkV1(item.id))return <GemArtwork itemId={item.id} size={72} framed={false}/>;
  if(hasResourceArtwork(item.id))return <ResourceArtwork itemId={item.id} size={72} framed={false}/>;
  return <View style={[art.fallback,{borderColor:model.rarity.color,backgroundColor:model.rarity.surface}]}><Text style={[art.symbol,{color:model.rarity.color}]}>{model.rarity.symbol}</Text><Text style={[art.fallbackText,{color:C.muted}]}>{item.type.toUpperCase()}</Text></View>;
}

export function ItemQuickInspect({state,itemId,onClose,onNavigate}:{state:GameState;itemId:string|null;onClose:()=>void;onNavigate?:(destination:WorkingTowardDestination)=>void}){
  const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
  if(!itemId)return null;
  const model=itemInspectModel(state,itemId),item=model.item,rarity=model.rarity,upgrade=model.upgrade,sockets=model.sockets,gearDecision=model.gearDecision,nameColor=rarityNameColor(model.rarityId,C.dark,C.text);
  const sourceRows=model.sources.slice(0,4),useRows=model.usedIn.slice(0,4),craftPath=item.type==='gear'?equipmentCraftingPath(state,item.id):undefined;
  const upgradeChance=upgrade?Math.round(upgrade.successChance*100):0;
  const upgradeColor=upgrade?.maxed?C.good:upgradeChance>=70?C.good:upgradeChance>=30?C.warning:C.bad;
  return <Modal visible transparent statusBarTranslucent animationType={state.settings.reduceMotion?'none':'fade'} onRequestClose={onClose}>
    <View style={s.overlay}>
      <Pressable accessibilityRole="button" accessibilityLabel="Close item quick inspect" onPress={onClose} style={StyleSheet.absoluteFill}/>
      <View style={s.sheet}>
        <View style={s.grabber}/>
        <View style={s.hero}>
          <View style={[s.artBox,{borderColor:rarity.color,backgroundColor:rarity.surface}]}><InspectArt state={state} itemId={itemId}/></View>
          <View style={s.heroCopy}>
            <Text style={[s.rarity,{color:rarity.color}]}>{rarity.symbol+' '+rarity.label.toUpperCase()+' · '+item.type.toUpperCase()}</Text>
            <Text numberOfLines={2} style={[s.name,{color:nameColor}]}>{item.name+(upgrade?.rank?' +'+upgrade.rank:'')}</Text>
            <Text style={s.owned}>{'Owned · '+formatGameNumber(model.totalQuantity,state.settings.numberMode)+' total · '+formatGameNumber(model.inventoryQuantity,state.settings.numberMode)+' carried · '+formatGameNumber(model.bankQuantity,state.settings.numberMode)+' banked'}</Text>
          </View>
          <Pressable accessibilityRole="button" accessibilityLabel="Close item quick inspect" onPress={onClose} style={({pressed})=>[s.close,pressed&&s.pressed]}><Text style={s.closeText}>×</Text></Pressable>
        </View>

        <ScrollView style={s.scroll} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
          {(model.stats||model.effectLines.length>0)&&<Section title="WHAT IT DOES"><View style={s.statRow}>{model.stats&&<><Stat label="ATK" value={model.stats.attack}/><Stat label="DEF" value={model.stats.defense}/><Stat label="HP" value={model.stats.hp}/></>}</View>{model.effectLines.map((line,index)=><Text key={index} style={s.body}>{'• '+line}</Text>)}</Section>}
          {gearDecision&&<Section title="GEAR CHECK">{!gearDecision.compatible?<Text style={s.warningText}>This item belongs to another class, so loadout impact cannot be previewed on this character.</Text>:<><View style={s.compareLine}><Text style={s.note}>REPLACES</Text><Text style={s.bodyStrong}>{gearDecision.replaces?gearDecision.replaces.name+(gearDecision.replaces.rank?' +'+gearDecision.replaces.rank:''):'Empty '+(item.slot??'slot')}</Text></View><Text style={s.note}>{gearDecision.alreadyEquipped?'Currently equipped · loadout change is zero.':'Whole-loadout change if equipped now.'}</Text><View style={s.deltaRow}><DeltaStat label="ATK" value={gearDecision.loadoutDelta.attack}/><DeltaStat label="DEF" value={gearDecision.loadoutDelta.defense}/><DeltaStat label="HP" value={gearDecision.loadoutDelta.hp}/><DeltaStat label="PWR" value={gearDecision.loadoutDelta.power}/></View><Text style={s.totalLine}>{'After equip · ATK '+gearDecision.loadoutAfter.attack+' · DEF '+gearDecision.loadoutAfter.defense+' · HP '+gearDecision.loadoutAfter.hp+' · PWR '+gearDecision.loadoutAfter.power}</Text>{upgrade&&!upgrade.maxed&&<><View style={s.compareLine}><Text style={s.note}>{'TO +'+gearDecision.maxRank+' FROM CURRENT RANK'}</Text><Text style={s.potentialLabel}>POTENTIAL</Text></View><View style={s.deltaRow}><DeltaStat label="ATK" value={gearDecision.maxLoadoutGain.attack} potential/><DeltaStat label="DEF" value={gearDecision.maxLoadoutGain.defense} potential/><DeltaStat label="HP" value={gearDecision.maxLoadoutGain.hp} potential/><DeltaStat label="PWR" value={gearDecision.maxLoadoutGain.power} potential/></View><Text style={s.note}>Potential keeps this copy's current socketed gems and only raises its upgrade rank.</Text></>}{gearDecision.set&&<View style={s.setDecision}><View style={s.compareLine}><Text style={s.setName}>{gearDecision.set.name}</Text><Text style={s.setCount}>{gearDecision.set.currentPieces+' → '+gearDecision.set.previewPieces+' / '+gearDecision.set.required}</Text></View>{gearDecision.set.active.map(row=><View key={row.pieces} style={s.setRuntimeRow}><Text style={[s.setRuntimePill,row.runtime==='live'?s.setRuntimeLive:s.setRuntimePending]}>{row.runtime==='live'?'LIVE':'HOOK'}</Text><Text style={s.note}>{row.pieces+'pc · '+row.bonus}</Text></View>)}{gearDecision.set.next&&<Text style={s.setNext}>{'Next · '+gearDecision.set.next.pieces+'pc · '+gearDecision.set.next.bonus}</Text>}<Text style={s.catalogNote}>2/4/8/10 always-on V33 bonuses are live in stats/combat. 6pc conditional text is preserved as a trigger hook until its exact skill/ally/barrier event exists.</Text></View>}</>}</Section>}

          {craftPath&&<Section title="CRAFTING PATH"><View style={s.compareLine}><View style={s.flex}><Text style={s.bodyStrong}>{craftPath.tier?craftPath.tier+' · ':''}{craftPath.recipe.name}</Text><Text style={s.note}>{craftPath.skillLabel+' · Character Lv '+craftPath.characterLevel+' · '+formatGameNumber(craftPath.gold,state.settings.numberMode)+' gold'}</Text>{craftPath.region&&<Text style={s.note}>{craftPath.region+(craftPath.path?' · '+craftPath.path:'')}</Text>}</View><Text style={[s.craftState,craftPath.canCraftNow?s.craftReady:s.craftBlocked]}>{craftPath.canCraftNow?'READY':craftPath.blockers.length+' BLOCK'}</Text></View>{craftPath.blockers.filter(blocker=>blocker.kind!=='material').map((blocker,index)=>blocker.destination&&onNavigate&&blocker.availability?.canNavigate?<Pressable key={blocker.kind+index} accessibilityRole="button" accessibilityLabel={blocker.label} onPress={()=>onNavigate(blocker.destination!)} style={({pressed})=>[s.actionRow,pressed&&s.pressed]}><View style={s.flex}><Text style={s.bodyStrong}>{blocker.label}</Text><Text style={s.note}>{blocker.detail}</Text></View><View style={s.actionMeta}>{blocker.availability&&<AvailabilityPill status={blocker.availability.status} label={blocker.availability.label}/>}<Text style={s.openMark}>OPEN ›</Text></View></Pressable>:<View key={blocker.kind+index} style={s.blockerRow}><Text style={s.bodyStrong}>{blocker.label}</Text><Text style={s.note}>{blocker.detail}</Text></View>)}<Text style={s.sectionMini}>MATERIALS</Text>{craftPath.ingredients.map(ingredient=>{const missing=ingredient.missing>0;return missing&&onNavigate&&ingredient.availability.canNavigate?<Pressable key={ingredient.itemId} accessibilityRole="button" accessibilityLabel={'Find '+ingredient.name} onPress={()=>onNavigate(ingredient.source)} style={({pressed})=>[s.actionRow,pressed&&s.pressed]}><View style={s.flex}><Text style={s.bodyStrong}>{ingredient.name+' · '+ingredient.owned+'/'+ingredient.required}</Text><Text style={s.note}>{ingredient.missing+' missing · '+ingredient.source.detail}</Text></View><View style={s.actionMeta}><AvailabilityPill status={ingredient.availability.status} label={ingredient.availability.label}/><Text style={s.openMark}>OPEN ›</Text></View></Pressable>:<View key={ingredient.itemId} style={s.materialReadyRow}><View style={s.flex}><Text style={s.bodyStrong}>{ingredient.name}</Text><Text style={s.note}>{ingredient.owned+'/'+ingredient.required+' owned'}</Text></View><Text style={missing?s.materialMissing:s.materialReady}>{missing?'MISSING':'READY'}</Text></View>})}</Section>}

          {upgrade&&<Section title="UPGRADE"><View style={s.upgradeTop}><Text style={s.bodyStrong}>{'Current +'+upgrade.rank}</Text><Text style={[s.chance,{color:upgradeColor}]}>{upgrade.maxed?'MAXED':upgradeChance+'% → +'+upgrade.nextRank}</Text></View>{upgrade.maxed?<Text style={s.body}>This item has reached the maximum upgrade rank.</Text>:<><Text style={s.body}>{'Next attempt · '+formatGameNumber(upgrade.gold,state.settings.numberMode)+' gold · '+upgrade.dust+' Tempering Dust'+(upgrade.cores?' · '+upgrade.cores+' Tempering Core'+(upgrade.cores===1?'':'s'):'')}</Text>{upgrade.failures>0&&<Text style={s.note}>{'Pity bonus active after '+upgrade.failures+' failed attempt'+(upgrade.failures===1?'':'s')+'.'}</Text>}{!upgrade.equipped&&<Text style={s.note}>Equip this item before attempting an upgrade.</Text>}</>}</Section>}

          {sockets&&<Section title="SOCKETS"><Text style={s.body}>{sockets.filled+'/'+sockets.capacity+' filled · 1 Stat + 1 Effect'}</Text>{gearDecision?.gems.length?gearDecision.gems.map(gem=><Text key={gem.id} style={s.body}>{(gem.kind==='stat'?'S ◆ ':'FX ✦ ')+gem.name+' · '+gem.detail}</Text>):<><Text style={s.note}>{'Stat · '+(sockets.statGemName??'Empty')}</Text><Text style={s.note}>{'Effect · '+(sockets.effectGemName??'Empty')}</Text></>}</Section>}

          <Section title="HOW TO GET">{sourceRows.length?sourceRows.map((source,index)=>source.navigation&&onNavigate?<Pressable key={source.kind+':'+source.title+':'+index} accessibilityRole="button" accessibilityLabel={`Open ${source.title}`} accessibilityHint={source.navigation.detail} onPress={()=>onNavigate(source.navigation!)} style={({pressed})=>[s.sourceRow,s.actionRow,pressed&&s.pressed]}><View style={[s.sourceDot,{backgroundColor:source.kind==='combat'?C.bad:source.kind==='crafting'?C.accent:source.kind==='gathering'?C.good:C.info}]}/><View style={s.flex}><Text style={s.bodyStrong}>{source.title}</Text><Text style={s.note}>{source.detail}</Text>{source.availability&&source.availability.status!=='ready'&&<Text style={s.availabilityDetail}>{source.availability.detail}</Text>}</View><View style={s.actionMeta}>{source.availability&&<AvailabilityPill status={source.availability.status} label={source.availability.label}/>}<Text style={s.openMark}>OPEN ›</Text></View></Pressable>:<View key={source.kind+':'+source.title+':'+index} style={s.sourceRow}><View style={[s.sourceDot,{backgroundColor:source.kind==='combat'?C.bad:source.kind==='crafting'?C.accent:source.kind==='gathering'?C.good:C.info}]}/><View style={s.flex}><Text style={s.bodyStrong}>{source.title}</Text><Text style={s.note}>{source.detail}</Text></View></View>):<Text style={s.note}>No repeatable source is catalogued for this item yet. It may come from a quest, event, one-time reward, or future content.</Text>}{model.sources.length>sourceRows.length&&<Text style={s.note}>{'+'+(model.sources.length-sourceRows.length)+' more known source'+(model.sources.length-sourceRows.length===1?'':'s')}</Text>}</Section>

          <Section title={'USED IN CRAFTING'+(model.usedIn.length?' · '+model.usedIn.length:'')}>{useRows.length?useRows.map((recipe,index)=>onNavigate?<Pressable key={recipe.name+':'+index} accessibilityRole="button" accessibilityLabel={`Open ${recipe.name}`} accessibilityHint={recipe.navigation.detail} onPress={()=>onNavigate(recipe.navigation)} style={({pressed})=>[s.recipeRow,s.actionRow,pressed&&s.pressed]}><View style={s.flex}><Text style={s.bodyStrong}>{recipe.name}</Text><Text style={s.note}>{recipe.skill+' Lv '+recipe.level+' · needs '+recipe.quantity}</Text>{recipe.availability.status!=='ready'&&<Text style={s.availabilityDetail}>{recipe.availability.detail}</Text>}</View><View style={s.actionMeta}><AvailabilityPill status={recipe.availability.status} label={recipe.availability.label}/><Text style={s.openMark}>OPEN ›</Text></View></Pressable>:<View key={recipe.name+':'+index} style={s.recipeRow}><View style={s.flex}><Text style={s.bodyStrong}>{recipe.name}</Text><Text style={s.note}>{recipe.skill+' Lv '+recipe.level+' · needs '+recipe.quantity}</Text></View></View>):<Text style={s.note}>Not currently used as a crafting ingredient.</Text>}{model.usedIn.length>useRows.length&&<Text style={s.note}>{'+'+(model.usedIn.length-useRows.length)+' more recipe'+(model.usedIn.length-useRows.length===1?'':'s')}</Text>}</Section>

          <View style={s.footerRow}><Text style={s.sell}>{'Sell value · '+formatGameNumber(item.value,state.settings.numberMode)+' gold each'}</Text>{item.classRestriction&&<Text style={s.classText}>{item.classRestriction.replaceAll('_',' ')}</Text>}</View>
        </ScrollView>
      </View>
    </View>
  </Modal>;
}
function Section({title,children}:{title:string;children:ReactNode}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function Stat({label,value}:{label:string;value:number}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);return <View style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>}
function DeltaStat({label,value,potential=false}:{label:string;value:number;potential?:boolean}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]),tone=value>0?C.good:value<0?C.bad:C.muted;return <View style={[s.deltaStat,potential&&s.deltaPotential]}><Text style={s.statLabel}>{label}</Text><Text style={[s.deltaValue,{color:tone}]}>{value===0?'—':(value>0?'+':'')+value}</Text></View>}
function AvailabilityPill({status,label}:{status:'ready'|'travel'|'locked'|'info';label:string}){const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]),tone=status==='ready'?C.good:status==='travel'?C.info:status==='locked'?C.warning:C.muted,surface=status==='ready'?C.goodSurface:status==='travel'?C.infoSurface:status==='locked'?C.warningSurface:C.panel2;return <View style={[s.availabilityPill,{borderColor:tone,backgroundColor:surface}]}><Text style={[s.availabilityLabel,{color:tone}]}>{label}</Text></View>}
const art=StyleSheet.create({fallback:{width:72,height:72,borderWidth:1,borderRadius:radii.sm,alignItems:'center',justifyContent:'center'},symbol:{fontSize:30,fontWeight:'900'},fallbackText:{fontSize:8,fontWeight:'800'}});
function makeStyles(C:ThemeColors){return StyleSheet.create({
  overlay:{flex:1,justifyContent:'flex-end',backgroundColor:C.overlay,paddingHorizontal:spacing.sm,paddingBottom:spacing.sm},
  sheet:{maxHeight:'84%',width:'100%',maxWidth:520,alignSelf:'center',overflow:'hidden',borderWidth:1,borderColor:C.lineStrong,borderRadius:radii.lg,backgroundColor:C.panelRaised},
  grabber:{width:42,height:4,borderRadius:99,backgroundColor:C.line,alignSelf:'center',marginTop:8},
  hero:{minHeight:104,flexDirection:'row',alignItems:'center',gap:spacing.md,padding:spacing.md,borderBottomWidth:1,borderBottomColor:C.line},
  artBox:{width:84,height:84,borderWidth:1,borderRadius:radii.md,alignItems:'center',justifyContent:'center'},
  heroCopy:{flex:1,minWidth:0,gap:3},rarity:{...typography.caption,fontWeight:'900',letterSpacing:.7},name:{...typography.title,fontWeight:'800'},owned:{...typography.caption,color:C.muted},
  close:{width:40,height:40,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.panel2},closeText:{fontSize:24,lineHeight:27,color:C.text,fontWeight:'700'},
  scroll:{maxHeight:520},content:{padding:spacing.md,gap:spacing.md,paddingBottom:spacing.lg},
  section:{gap:6,paddingBottom:spacing.sm,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:C.line},sectionTitle:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:.8},
  statRow:{flexDirection:'row',gap:spacing.sm},stat:{flex:1,minWidth:0,padding:spacing.sm,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},statLabel:{...typography.caption,color:C.muted},statValue:{...typography.bodyStrong,color:C.text,fontWeight:'800'},
  compareLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},deltaRow:{flexDirection:'row',gap:6},deltaStat:{flex:1,minWidth:0,paddingVertical:6,paddingHorizontal:7,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},deltaPotential:{borderColor:C.info},deltaValue:{...typography.bodyStrong,fontWeight:'900'},totalLine:{...typography.caption,color:C.text,fontWeight:'700'},potentialLabel:{...typography.caption,color:C.info,fontWeight:'900'},warningText:{...typography.body,color:C.warning,fontWeight:'700'},setDecision:{gap:5,padding:8,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},setName:{...typography.bodyStrong,color:C.text},setCount:{...typography.caption,color:C.accent,fontWeight:'900'},setRuntimeRow:{flexDirection:'row',alignItems:'flex-start',gap:6},setRuntimePill:{minWidth:34,textAlign:'center',fontSize:7,lineHeight:10,fontWeight:'900',borderWidth:1,borderRadius:99,paddingHorizontal:4,paddingVertical:2},setRuntimeLive:{color:C.good,borderColor:C.good,backgroundColor:C.goodSurface},setRuntimePending:{color:C.warning,borderColor:C.warning,backgroundColor:C.warningSurface},setNext:{...typography.caption,color:C.info,fontWeight:'700'},catalogNote:{fontSize:9,lineHeight:12,color:C.muted},
  body:{...typography.body,color:C.text},bodyStrong:{...typography.bodyStrong,color:C.text},note:{...typography.caption,color:C.muted},
  upgradeTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},chance:{...typography.bodyStrong,fontWeight:'900'},craftState:{fontSize:8,lineHeight:11,fontWeight:'900',letterSpacing:.5,paddingHorizontal:6,paddingVertical:4,borderWidth:1,borderRadius:99},craftReady:{color:C.good,borderColor:C.good,backgroundColor:C.goodSurface},craftBlocked:{color:C.warning,borderColor:C.warning,backgroundColor:C.warningSurface},sectionMini:{fontSize:8,lineHeight:11,color:C.muted,fontWeight:'900',letterSpacing:.7,marginTop:4},blockerRow:{gap:2,paddingVertical:4},materialReadyRow:{minHeight:38,flexDirection:'row',alignItems:'center',gap:8,paddingVertical:4},materialReady:{...typography.caption,color:C.good,fontWeight:'900'},materialMissing:{...typography.caption,color:C.warning,fontWeight:'900'},
  sourceRow:{flexDirection:'row',alignItems:'flex-start',gap:8},sourceDot:{width:8,height:8,borderRadius:99,marginTop:6},recipeRow:{paddingVertical:2},actionRow:{minHeight:44,alignItems:'center',paddingHorizontal:8,paddingVertical:6,borderWidth:1,borderColor:C.line,borderRadius:radii.sm,backgroundColor:C.panel2},actionMeta:{alignItems:'flex-end',justifyContent:'center',gap:4},openMark:{...typography.caption,color:C.info,fontWeight:'900'},availabilityPill:{minHeight:20,justifyContent:'center',paddingHorizontal:6,borderWidth:1,borderRadius:99},availabilityLabel:{fontSize:9,lineHeight:12,fontWeight:'900',letterSpacing:.5},availabilityDetail:{...typography.caption,color:C.warning,fontWeight:'700'},
  footerRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',justifyContent:'space-between',gap:8},sell:{...typography.caption,color:C.muted},classText:{...typography.caption,color:C.info,fontWeight:'800'},
  flex:{flex:1,minWidth:0},pressed:{opacity:.72},
});}
