import {Pressable,StyleSheet,Text,View} from 'react-native';
import {ItemDef,itemDef} from '../content/items';
import {C,radii,spacing,typography} from '../theme/theme';
import {GameButton} from './GameButton';
import {Panel} from './Panel';
import {itemRarity,rarityLabel,rarityMeta} from '../core/item-rarity';
import {EquipmentArtwork} from './EquipmentArtwork';
import {equipmentSetDef} from '../content/equipment-sets';
import {formatGameNumber} from '../core/number-format';
import {GatheringToolArtwork} from './GatheringToolArtwork';
import {ResourceArtwork} from './ResourceArtwork';
import {hasResourceArtwork} from '../theme/resource-assets';

type StatKey='attack'|'defense'|'hp';
const stats:{key:StatKey;label:string}[]=[{key:'attack',label:'ATK'},{key:'defense',label:'DEF'},{key:'hp',label:'HP'}];
function delta(next:number,current:number){const value=next-current;return value===0?'—':`${value>0?'+':''}${value}`}

export function ItemCard({item,quantity,equipped,upgradeRank=0,socketed=0,socketCapacity=0,enhancementProtected=false,displayStats,equippedDisplayStats,selectedFood=false,onEquip,onSelectFood,onEat,onSell,onSalvage,onDeposit,onWithdraw,transferQuantity=1,transferIssue='',healAmount,onPreview,numberMode='abbreviated',expanded=true,onToggle}:{item:ItemDef;quantity:number;equipped?:ItemDef;upgradeRank?:number;socketed?:number;socketCapacity?:number;enhancementProtected?:boolean;displayStats?:Partial<Record<StatKey,number>>;equippedDisplayStats?:Partial<Record<StatKey,number>>;selectedFood?:boolean;onEquip?:()=>void;onSelectFood?:()=>void;onEat?:()=>void;onSell?:()=>void;onSalvage?:()=>void;onDeposit?:()=>void;onWithdraw?:()=>void;transferQuantity?:number;transferIssue?:string;healAmount?:number;onPreview?:()=>void;numberMode?:'abbreviated'|'exact';expanded?:boolean;onToggle?:()=>void}){
  const gear=item.type==='gear',tool=item.type==='tool',resource=hasResourceArtwork(item.id),visualItem=gear||tool||resource,rarity=itemRarity(item),meta=rarityMeta(rarity);
  const set=equipmentSetDef(item.equipmentSetId);
  return <Panel>
    <Pressable disabled={!onToggle} accessibilityRole="button" accessibilityLabel={item.name} accessibilityState={{expanded:onToggle?expanded:undefined}} onPress={onToggle} style={s.heading}>{gear?<EquipmentArtwork item={item} compact framed={false}/>:tool?<GatheringToolArtwork itemId={item.id} framed={false}/>:resource?<ResourceArtwork itemId={item.id} framed={false}/>:null}<View style={s.copy}><Text style={s.name}>{item.name}{gear&&upgradeRank>0?` +${upgradeRank}`:''}</Text><View style={[s.rarityBadge,{borderColor:meta.color,backgroundColor:meta.surface}]}><Text style={[s.rarity,{color:meta.color}]}>{meta.symbol} {rarityLabel(item)} · {item.type.toUpperCase()}{item.slot?` · ${item.slot.toUpperCase()}`:''}{gear&&socketCapacity?` · ◆ ${socketed}/${socketCapacity}`:''}</Text></View></View><Text style={[s.qty,visualItem&&{color:meta.color}]}>×{formatGameNumber(quantity,numberMode)}</Text></Pressable>
    {expanded&&<>
    {onPreview&&<GameButton title="Compare stats" tone="secondary" onPress={onPreview}/>}
    {gear&&<><View style={s.stats}>{stats.map(({key,label})=>{const value=displayStats?.[key]??item[key]??0,current=equippedDisplayStats?.[key]??equipped?.[key]??0,d=value-current;return <View key={key} style={s.stat}><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text><Text style={[s.delta,d>0?s.better:d<0?s.worse:s.same]}>{delta(value,current)}</Text></View>})}</View><Text style={s.compare}>{equipped?`Compared with ${equipped.name}`:`Changes versus an empty ${item.slot} slot`}</Text>{set&&<View style={[s.setInfo,{borderColor:set.accent,backgroundColor:set.surface}]}><Text style={[s.setName,{color:set.accent}]}>{set.name} · 4-piece set</Text><Text style={s.setBonus}>2 pieces · {set.twoPiece}</Text><Text style={s.setBonus}>4 pieces · {set.fourPiece}</Text></View>}{(rarity==='legendary'||rarity==='mythic')&&<Text style={s.passive}>◆ Passive: {item.passive||'Class-aligned bonus is active while equipped.'}</Text>}</>}
    {item.type==='food'?<Text style={s.food}>Restores {item.heal} HP · readiness {item.readiness||0}{selectedFood?' · AUTO-EAT SELECTED':''}</Text>:item.type==='tool'?<Text style={s.food}>{item.toolSkillId?.toUpperCase()} TOOL · Tier {item.toolTier} · {Math.round((1-(item.actionTimeMultiplier??1))*100)}% shorter base action time</Text>:!gear&&<Text style={s.value}>Sell value · {item.value} gold each</Text>}
    {enhancementProtected&&<Text style={s.protected}>◆ Enhanced gear protected from selling and salvage</Text>}{item.salvage&&<Text style={s.salvage}>Salvage yields {formatGameNumber(item.salvage.quantity,numberMode)}× {itemDef(item.salvage.itemId).name}</Text>}
    {onEquip&&<GameButton title={`Equip ${item.slot}`} onPress={onEquip}/>}{onSelectFood&&<GameButton title={selectedFood?'Auto-eat selected':'Use for auto-eat'} disabled={selectedFood} onPress={onSelectFood}/>}{onEat&&<GameButton title={healAmount===0?'Health full':`Eat 1 · +${formatGameNumber(healAmount??item.heal??0,numberMode)} HP`} disabled={healAmount===0} tone="secondary" onPress={onEat}/>}{onSell&&<GameButton title={`Sell 1 · ${formatGameNumber(item.value,numberMode)} gold`} tone="secondary" onPress={onSell}/>}{onSalvage&&<GameButton title="Salvage 1" tone="danger" onPress={onSalvage}/>}{onDeposit&&<GameButton title={`Deposit ${formatGameNumber(transferQuantity,numberMode)} to Bank`} disabled={!!transferIssue} tone="secondary" onPress={onDeposit}/>}{onWithdraw&&<GameButton title={`Withdraw ${formatGameNumber(transferQuantity,numberMode)}`} disabled={!!transferIssue} tone="secondary" onPress={onWithdraw}/>}
    {!!transferIssue&&<View accessibilityRole="alert" style={s.transferCallout}><Text style={s.transferLabel}>TRANSFER UNAVAILABLE</Text><Text style={s.transferText}>{transferIssue}. Try a smaller quantity or free space.</Text></View>}
    </>}
    {onToggle&&<Pressable accessibilityRole="button" accessibilityLabel={expanded?"Hide item actions":"Show item actions"} onPress={onToggle} style={s.detailToggle}><Text style={s.compare}>{expanded?"Hide details":"Details & actions"}</Text></Pressable>}
  </Panel>;
}
const s=StyleSheet.create({detailToggle:{minHeight:44,justifyContent:'center'},heading:{minHeight:64,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:spacing.md},copy:{flex:1,minWidth:0,gap:spacing.xs},name:{...typography.bodyStrong,fontSize:16,lineHeight:23,color:C.text},rarityBadge:{alignSelf:'flex-start',borderLeftWidth:2,paddingLeft:6,paddingVertical:2},rarity:{...typography.caption,fontWeight:'700'},qty:{fontSize:18,color:C.accent,fontWeight:'700'},stats:{flexDirection:'row',gap:spacing.sm},stat:{flex:1,backgroundColor:C.panel2,borderRadius:radii.sm,padding:spacing.sm},statLabel:{...typography.caption,color:C.muted},statValue:{...typography.bodyStrong,color:C.text},delta:{...typography.caption,fontWeight:'700'},better:{color:C.good},worse:{color:C.bad},same:{color:C.muted},compare:{...typography.caption,color:C.info},setInfo:{gap:spacing.xs,borderWidth:1,borderRadius:radii.sm,padding:spacing.sm},setName:{...typography.bodyStrong},setBonus:{...typography.caption,color:C.text},passive:{...typography.bodyStrong,color:'#f0a24b'},value:{...typography.body,color:C.muted},food:{...typography.bodyStrong,color:C.good},protected:{...typography.caption,color:C.info,fontWeight:'600'},salvage:{...typography.body,color:C.warning},transferCallout:{gap:4,padding:spacing.sm,borderWidth:1,borderColor:C.warning,borderRadius:8,backgroundColor:'#332515'},transferLabel:{...typography.caption,color:C.warning,fontWeight:'900',letterSpacing:1},transferText:{...typography.body,color:C.text}});
