import {useEffect,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';
import {GuildCrest} from './SocialIdentity';
import {GameTextInput as TextInput} from './GameTextInput';
import {GameButton} from './GameButton';
import {Panel} from './Panel';
import {C,equipmentColors,typography} from '../theme/theme';
import {guildTagAvailabilityMessage,normalizeGuildTag,type GuildTagAvailability} from '../core/guild-tags';
import {onlineConfigured} from '../online/supabase';
import {browseGuilds,createOnlineGuild,guildTagAvailability,requestGuildMembership,type OnlineGuild} from '../online/social';
import {GuildTaggedPlayerName} from './GuildTaggedPlayerName';

export function OnlineGuildBrowser(){
 const [guilds,setGuilds]=useState<OnlineGuild[]>([]),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[name,setName]=useState(''),[tag,setTag]=useState(''),[tagStatus,setTagStatus]=useState<GuildTagAvailability|null>(null),[showCreate,setShowCreate]=useState(false),[policy,setPolicy]=useState<'open'|'apply'>('open');
 const load=async()=>{if(!onlineConfigured)return;setBusy(true);try{setGuilds(await browseGuilds());setLoaded(true)}catch(error){Alert.alert('Guilds',error instanceof Error?error.message:'Unable to load guilds.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);useEffect(()=>setTagStatus(null),[tag]);if(!onlineConfigured)return null;
 const checkTag=async()=>{setBusy(true);try{const result=await guildTagAvailability(tag);setTagStatus(result);return result}catch(error){Alert.alert('Guild tag',error instanceof Error?error.message:'Unable to check that tag.');return null}finally{setBusy(false)}};
 const join=async(guild:OnlineGuild)=>{setBusy(true);try{const result=await requestGuildMembership(guild.id);Alert.alert(result==='joined'?'Guild joined':'Application sent',result==='joined'?`You joined ${guild.name}.`:`${guild.name} will review your application.`);await load()}catch(error){Alert.alert('Guilds',error instanceof Error?error.message:'Unable to join guild.')}finally{setBusy(false)}};
 const create=async()=>{setBusy(true);try{const status=tagStatus?.normalizedTag===normalizeGuildTag(tag)?tagStatus:await guildTagAvailability(tag);setTagStatus(status);if(!status.available)throw new Error(guildTagAvailabilityMessage(status));await createOnlineGuild(name,status.normalizedTag!,policy,1);setName('');setTag('');setTagStatus(null);Alert.alert('Guild created','Your guild tag is permanently reserved and visible with your guild identity.');await load()}catch(error){Alert.alert('Create guild',error instanceof Error?error.message:'Unable to create guild.')}finally{setBusy(false)}};
 return <Panel><Text style={s.title}>Guild directory · online</Text><Text style={s.sub}>Every guild has a permanent, globally unique three-letter tag.</Text><GameButton title={showCreate?'Hide guild creation':'Create a guild'} tone="secondary" onPress={()=>setShowCreate(v=>!v)}/>{showCreate&&<><TextInput accessibilityLabel="New guild name" value={name} onChangeText={setName} maxLength={24} placeholder="New guild name" placeholderTextColor={C.muted} style={s.input}/><View style={s.tagRow}><TextInput accessibilityLabel="Guild tag" autoCapitalize="characters" value={tag} onChangeText={value=>setTag(normalizeGuildTag(value).slice(0,3))} maxLength={3} placeholder="TAG" placeholderTextColor={C.muted} style={[s.input,s.tagInput]}/><GameButton title="Check" tone="secondary" disabled={busy||tag.length!==3} onPress={()=>void checkTag()}/></View>{tagStatus?<Text style={[s.tagStatus,tagStatus.available&&s.available]}>{guildTagAvailabilityMessage(tagStatus)}</Text>:<Text style={s.tagStatus}>Exactly three letters. A claimed tag can never be reused.</Text>}<View style={s.actions}><PolicyChip label="Open" selected={policy==='open'} disabled={busy} onPress={()=>setPolicy('open')}/><PolicyChip label="Applications" selected={policy==='apply'} disabled={busy} onPress={()=>setPolicy('apply')}/></View><GameButton title="Create guild" disabled={busy||name.trim().length<3||tag.length!==3||!tagStatus?.available} onPress={()=>void create()}/></>}<GameButton title={busy?'Loading…':'Refresh directory'} tone="secondary" disabled={busy} onPress={()=>void load()}/>{loaded&&!guilds.length&&<Text style={s.empty}>No online guilds have been created yet.</Text>}{guilds.map(guild=><View key={guild.id} style={s.row}><GuildCrest size={40} bannerId={guild.banner_id}/><View style={s.copy}><GuildTaggedPlayerName name={guild.name} guildTag={guild.tag} tagColorId={guild.tag_color_id} style={s.name}/><Text style={s.meta}>Level {guild.level}/10 · {guild.member_cap} slots · {guild.join_policy==='open'?'Open':guild.join_policy==='apply'?'Application':'Invite only'}</Text></View><GameButton title={guild.join_policy==='open'?'Join':guild.join_policy==='apply'?'Apply':'Invite'} tone="secondary" disabled={busy||guild.join_policy==='invite'} onPress={()=>void join(guild)}/></View>)}</Panel>;
}
function PolicyChip({label,selected,disabled,onPress}:{label:string;selected:boolean;disabled:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected,disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[s.policyChip,selected&&s.policyChipSelected,pressed&&s.pressed,disabled&&s.disabled]}><Text style={[s.policyText,selected&&s.policyTextSelected]}>{selected?'✓ ':''}{label}</Text></Pressable>}
const s=StyleSheet.create({title:{color:C.text,...typography.title,marginBottom:5},sub:{color:C.muted,lineHeight:19,marginBottom:8},input:{minHeight:44,borderWidth:1,borderColor:C.line,borderRadius:8,color:C.text,paddingHorizontal:10,marginBottom:8},tagRow:{flexDirection:'row',gap:8,alignItems:'flex-start'},tagInput:{flex:1,fontWeight:'900',letterSpacing:3},tagStatus:{color:C.muted,fontSize:11,marginTop:-3,marginBottom:8},available:{color:C.good},actions:{flexDirection:'row',gap:8,marginBottom:8},policyChip:{flex:1,minHeight:40,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},policyChipSelected:{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},policyText:{fontSize:12,fontWeight:'700',color:C.muted},policyTextSelected:{color:'#d9f3ff'},pressed:{opacity:.76},disabled:{opacity:.45},empty:{color:C.muted,fontSize:12,marginTop:8},row:{flexDirection:'row',gap:8,alignItems:'center',paddingVertical:10,borderTopWidth:1,borderColor:C.line},copy:{flex:1,minWidth:0},name:{color:C.text,fontWeight:'900'},meta:{color:C.muted,fontSize:12,marginTop:2}});
