import {GameTextInput as TextInput} from './GameTextInput';
import {useMemo,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,View} from 'react-native';
import {GameButton} from './GameButton';
import {Panel} from './Panel';
import type {GameState} from '../core/types';
import {createOnlineAccount,requestPasswordRecovery,resendAccountConfirmation,sendMagicLink,signInAsGuest,signInWithPassword,signOut,updateAccountPassword,upgradeGuestAccount} from '../online/account';
import {onlineConfigured} from '../online/supabase';
import {useAuthSession} from '../online/AuthSessionProvider';
import {serverGameplayEnabled} from '../online/gameplay';
import {passwordRequirements} from '../core/auth-callback';
import {spacing,touchTargetMin,typography,equipmentTheme,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
function AuthModeChip({label,selected,disabled,onPress}:{label:string;selected:boolean;disabled:boolean;onPress:()=>void}){const C=useGameTheme(),equipmentColors=equipmentTheme(C);return <Pressable accessibilityRole="button" accessibilityState={{selected,disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[{minHeight:40,alignSelf:'center',paddingHorizontal:14,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},selected&&{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},disabled&&{opacity:.45},pressed&&{opacity:.76}]}><Text style={[{fontSize:12,color:C.muted,fontWeight:'700'},selected&&{color:'#d9f3ff'}]}>{selected?'✓ ':''}{label}</Text></Pressable>}
export function OnlineAccountPanel({state}:{state:GameState}){
 const C=useGameTheme(),equipmentColors=equipmentTheme(C),s=useMemo(()=>makeStyles(C),[C]);
 const auth=useAuthSession();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(state.character?.name??''),[creating,setCreating]=useState(false),[showHelp,setShowHelp]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[noticeTone,setNoticeTone]=useState<'error'|'success'>('error');
 const requirements=passwordRequirements(password),showPasswordRules=creating||auth.recovering||Boolean(auth.session?.user.is_anonymous);
 const success=(message:string)=>{setNoticeTone('success');setNotice(message);};
 const run=async(action:()=>Promise<void>)=>{if(busy)return;setBusy(true);setNoticeTone('error');setNotice('');try{await action();setPassword('');}catch(e){setNotice(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 const emailInput=<><Text style={s.label}>Email address</Text><TextInput accessibilityLabel="Email address" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none" autoComplete="email" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={C.muted} style={s.input}/></>;
 const passwordInput=<><Text style={s.label}>{auth.recovering?'New password':'Password'}</Text><TextInput accessibilityLabel="Password" value={password} onChangeText={setPassword} secureTextEntry autoCorrect={false} autoCapitalize="none" autoComplete={showPasswordRules?'new-password':'current-password'} placeholder={showPasswordRules?'Create a strong password':'Password'} placeholderTextColor={C.muted} style={s.input}/>{showPasswordRules&&<View accessibilityLabel="Password requirements" style={s.passwordRules}><Text style={s.passwordRulesTitle}>Password requirements</Text>{([['8–128 characters',requirements.length],['One uppercase letter',requirements.uppercase],['One lowercase letter',requirements.lowercase],['One number',requirements.number],['One special character',requirements.symbol]] as const).map(([label,met])=><Text key={label} style={[s.passwordRule,met&&s.passwordRuleMet]}>{met?'✓':'○'} {label}</Text>)}</View>}</>;
 if(!onlineConfigured)return <Panel><Text style={s.title}>Online account unavailable</Text><Text style={s.text}>This build has no online connection configured.</Text></Panel>;
 return <Panel><Text accessibilityRole="header" style={s.title}>{auth.recovering?'Reset your password':auth.session?'Your account':creating?'Create your VELDRYN account':'Welcome to VELDRYN'}</Text>
  {!!(notice||auth.error)&&<View accessibilityRole="alert" style={[s.noticeCard,noticeTone==='success'&&s.noticeSuccessCard]}><Text style={noticeTone==='success'?s.noticeLabelSuccess:s.noticeLabel}>{noticeTone==='success'?'ACCOUNT UPDATED':'ACCOUNT NOTICE'}</Text><Text style={[s.notice,noticeTone==='success'&&s.noticeSuccess]}>{notice||auth.error}</Text></View>}
  {auth.recovering?<>{passwordInput}<GameButton title="Save new password" disabled={busy} onPress={()=>void run(async()=>{await updateAccountPassword(password);auth.clearRecovery();setNotice('Password updated.');})}/></>:!auth.session?<>
   {creating&&<><Text style={s.label}>Username</Text><TextInput accessibilityLabel="Username" value={username} onChangeText={setUsername} maxLength={20} placeholder="Username" placeholderTextColor={C.muted} style={s.input}/></>}
   {emailInput}{passwordInput}
   <GameButton title={busy?'Connecting…':creating?'Create account':'Sign in'} disabled={busy} onPress={()=>void run(async()=>{if(creating){const result=await createOnlineAccount(email,password,username);if(!result.confirmed){success('Confirmation email sent. Check your inbox before signing in.');Alert.alert('Check your email','Your VELDRYN account was created. Open the confirmation link in your email, then return here to sign in.',[{text:'Back to sign in',onPress:()=>{setCreating(false);setShowHelp(false)}}]);}}else await signInWithPassword(email,password);})}/>
   <AuthModeChip label={creating?'Sign in instead':'Create a new account'} selected={creating} disabled={busy} onPress={()=>{setCreating(!creating);setNotice('');}}/>
   {!creating&&<><Text style={s.guestHint}>Want to try the game first? A guest account can be secured with email later.</Text><GameButton title="Continue as guest" tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await signInAsGuest();success('Guest account ready. Create your character to enter Asterfall.');})}/></>}
   <Pressable accessibilityRole="button" accessibilityState={{expanded:showHelp}} onPress={()=>setShowHelp(value=>!value)} style={s.helpToggle}><Text style={s.helpText}>{showHelp?'Hide sign-in help':'Need help signing in?'}</Text></Pressable>
   {showHelp&&<View style={s.help}><Text style={s.text}>Enter your email above to request a link.</Text><View style={s.row}><GameButton title="Resend confirmation" tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await resendAccountConfirmation(email);success('If confirmation is needed, an email has been requested.');})}/><GameButton title="Forgot password" tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await requestPasswordRecovery(email);success('If this email has an account, a recovery link has been requested.');})}/></View>
   <GameButton title="Email a sign-in link" tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await sendMagicLink(email);success('Check your email and open the link on this device.');})}/></View>}
   <Text style={s.text}>{serverGameplayEnabled?'Online characters and progress are saved on the server. Your existing local save is kept separately.':'Your local game remains on this device. Online social features use your account.'}</Text>
  </>:<>
   <Text style={s.text}>Signed in as {auth.session.user.email??'guest'}.</Text>
   {auth.session.user.is_anonymous&&<><Text style={s.text}>Add an email and password to recover this account on another device.</Text><TextInput accessibilityLabel="Username" value={username} onChangeText={setUsername} placeholder="Username" placeholderTextColor={C.muted} style={s.input}/>{emailInput}{passwordInput}<GameButton title="Secure guest account" disabled={busy} onPress={()=>void run(async()=>{await upgradeGuestAccount(email,password,username);success('Confirm your email to finish securing this account.');})}/></>}
   <Text style={s.text}>{serverGameplayEnabled?'Every successful gameplay action is saved online. Sign in on another device to continue.':'Local save uploads do not grant online progression.'}</Text>
   <GameButton title="Sign out" tone="secondary" disabled={busy} onPress={()=>{if(auth.session?.user.is_anonymous)Alert.alert('Sign out of guest account?','Add an email first so you can recover this account.',[{text:'Stay signed in'},{text:'Sign out',style:'destructive',onPress:()=>void run(signOut)}]);else void run(signOut);}}/>
  </>}
 </Panel>;
}
function makeStyles(C:ThemeColors){const equipmentColors=equipmentTheme(C);return StyleSheet.create({title:{color:C.text,...typography.title},label:{color:C.text,...typography.bodyStrong,marginTop:spacing.sm},helpToggle:{minHeight:48,justifyContent:'center',alignItems:'center'},helpText:{...typography.body,color:C.info},help:{gap:spacing.sm,paddingTop:spacing.sm,borderTopWidth:1,borderColor:C.line},text:{color:C.muted,lineHeight:21,marginVertical:spacing.sm},guestHint:{color:C.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:spacing.sm},passwordRules:{paddingHorizontal:spacing.sm,paddingBottom:spacing.sm,gap:3},passwordRulesTitle:{color:C.text,fontSize:12,fontWeight:'700',marginBottom:2},passwordRule:{color:C.muted,fontSize:12,lineHeight:18},passwordRuleMet:{color:C.good},noticeCard:{gap:4,padding:spacing.sm,borderWidth:1,borderColor:C.bad,borderRadius:8,backgroundColor:'#2a1b20',marginVertical:spacing.sm},noticeSuccessCard:{borderColor:C.good,backgroundColor:'#172b24'},noticeLabel:{...typography.caption,color:C.bad,fontWeight:'900',letterSpacing:1},noticeLabelSuccess:{...typography.caption,color:C.good,fontWeight:'900',letterSpacing:1},notice:{color:C.text,lineHeight:21},noticeSuccess:{color:C.text},input:{minHeight:touchTargetMin,borderWidth:1,borderColor:C.line,color:C.text,padding:spacing.sm,marginVertical:spacing.sm},row:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm}});}
