import {useEffect,useMemo,useState} from 'react';
import {Alert,Image,Pressable,StyleSheet,Text,View} from 'react-native';
import {GameButton} from './GameButton';
import {GameTextInput} from './GameTextInput';
import {GuildCrest} from './SocialIdentity';
import {Panel} from './Panel';
import {GUILD_BANNERS,GUILD_FRAMES,GUILD_NAME_COLORS,GUILD_NAMEPLATES,guildCosmeticUnlockLabel,isGuildCosmeticUnlocked,normalizeGuildBannerId,normalizeGuildFrameId,normalizeGuildMotto,normalizeGuildNameColorId,normalizeGuildNameplateId,type GuildAppearanceEntitlements,type GuildBannerId,type GuildFrameId,type GuildNameColorId,type GuildNameplateId} from '../core/guild-customization';
import {GUILD_TAG_COLORS,guildTagColor,normalizeGuildTag,type GuildTagColorId} from '../core/guild-tags';
import {guildAppearanceEntitlements,guildDetails,myGuild,updateGuildAppearance,updateOnlineGuildTag,type OnlineGuild} from '../online/social';
import {radii,spacing,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
import {guildBorderSourceByKey,guildNameplateSourceByKey} from '../theme/guild-customization-assets';

export function OnlineGuildCustomizationPanel(){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
 const [guild,setGuild]=useState<OnlineGuild|null>(null),[role,setRole]=useState<'leader'|'officer'|'member'|null>(null),[bannerId,setBannerId]=useState<GuildBannerId>('world_tree_green'),[frameId,setFrameId]=useState<GuildFrameId>('classic'),[nameColorId,setNameColorId]=useState<GuildNameColorId>('name_ivory'),[nameplateId,setNameplateId]=useState<GuildNameplateId>('classic'),[motto,setMotto]=useState('Stronger together.'),[tag,setTag]=useState(''),[tagColorId,setTagColorId]=useState<GuildTagColorId>('tag_silver'),[entitlements,setEntitlements]=useState<GuildAppearanceEntitlements>({guildLevel:1,bannerGalleryTier:0,pveAchievementIds:[]}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
 const editable=role==='leader'||role==='officer';
 const apply=(next:OnlineGuild)=>{setGuild(next);setBannerId(normalizeGuildBannerId(next.banner_id));setFrameId(normalizeGuildFrameId(next.profile_frame_id));setNameColorId(normalizeGuildNameColorId(next.name_color_id));setNameplateId(normalizeGuildNameplateId(next.nameplate_id));setMotto(normalizeGuildMotto(next.motto));setTag(next.tag??'');setTagColorId(next.tag_color_id??'tag_silver');};
 const load=async()=>{setBusy(true);try{const membership=await myGuild();setRole(membership?.role??null);if(membership){const [details,unlocks]=await Promise.all([guildDetails(membership.guild_id),guildAppearanceEntitlements()]);apply(details);setEntitlements(unlocks)}else setGuild(null);setLoaded(true);}catch(error){Alert.alert('Guild customization',error instanceof Error?error.message:'Unable to load guild customization.')}finally{setBusy(false)}};
 useEffect(()=>{void load()},[]);
 const save=async()=>{if(!editable||busy)return;setBusy(true);try{const cleanMotto=normalizeGuildMotto(motto);const result=await updateGuildAppearance({bannerId,borderId:frameId,nameColorId,tagColorId,nameplateId,motto:cleanMotto});if(result&&guild)apply({...guild,banner_id:result.banner_id,profile_frame_id:result.border_id,name_color_id:result.name_color_id,tag_color_id:result.tag_color_id,nameplate_id:result.nameplate_id,motto:result.motto});Alert.alert('Guild updated','Your entitlement-validated guild visuals are now visible across social surfaces.');}catch(error){Alert.alert('Guild customization',error instanceof Error?error.message:'Unable to save guild customization.')}finally{setBusy(false)}};
 const saveTag=async()=>{if(!editable||busy||normalizeGuildTag(tag)===guild?.tag)return;Alert.alert('Change guild tag?','The old tag is permanently retired and can never be claimed again.',[{text:'Cancel',style:'cancel'},{text:'Change tag',style:'destructive',onPress:async()=>{setBusy(true);try{const result=await updateOnlineGuildTag(tag);if(result&&guild)apply({...guild,tag:result.tag});Alert.alert('Guild tag updated',`[${result?.tag??normalizeGuildTag(tag)}] is now active.`)}catch(error){Alert.alert('Guild tag',error instanceof Error?error.message:'Unable to change the guild tag.')}finally{setBusy(false)}}}])};
 if(!loaded)return <Panel><Text style={s.title}>Guild customization</Text><Text style={s.help}>{busy?'Loading…':'Open this panel to load your guild.'}</Text></Panel>;
 if(!guild)return <Panel><Text style={s.title}>Guild customization</Text><Text style={s.help}>Join or create a guild before choosing guild visuals.</Text></Panel>;
 const banner=GUILD_BANNERS.find(entry=>entry.id===bannerId)??GUILD_BANNERS[0];
 const selectedFrame=GUILD_FRAMES.find(entry=>entry.id===frameId),selectedFrameSource=selectedFrame?.assetKey?guildBorderSourceByKey.get(selectedFrame.assetKey):undefined;
 const appearanceDirty=bannerId!==normalizeGuildBannerId(guild.banner_id)||frameId!==normalizeGuildFrameId(guild.profile_frame_id)||nameColorId!==normalizeGuildNameColorId(guild.name_color_id)||nameplateId!==normalizeGuildNameplateId(guild.nameplate_id)||tagColorId!==(guild.tag_color_id??'tag_silver')||normalizeGuildMotto(motto)!==normalizeGuildMotto(guild.motto);
 const tagDirty=normalizeGuildTag(tag)!==(guild.tag??'');
 return <Panel>
  <View style={s.heading}><GuildCrest size={54} bannerId={bannerId} frameId={frameId}/><View style={s.flex}><Text style={s.eyebrow}>GUILD APPEARANCE</Text><Text style={s.title}>{guild.name}</Text><Text style={s.help}>{editable?'Leader / Officer access':'Read-only · Leader or Officer required'}</Text></View><View style={[s.saveState,appearanceDirty&&s.saveStateDirty]}><Text style={[s.saveStateText,appearanceDirty&&s.saveStateTextDirty]}>{appearanceDirty?'UNSAVED':'SAVED'}</Text></View></View>
  <View style={[s.preview,{borderColor:selectedFrame?.accent??C.accent}]}><View style={s.crestPreview}><GuildCrest size={62} bannerId={bannerId}/>{selectedFrameSource?<Image accessible={false} source={selectedFrameSource} resizeMode="contain" style={s.crestFrame}/>:null}</View><View style={s.flex}><Text style={[s.previewName,{color:GUILD_NAME_COLORS.find(entry=>entry.id===nameColorId)?.color??C.text}]}><Text style={{color:guildTagColor(tagColorId)}}>[{guild.tag}] </Text>{guild.name}</Text><Text style={s.motto}>{normalizeGuildMotto(motto)}</Text><Text style={s.meta}>{banner.name} · {selectedFrame?.name} · {GUILD_NAMEPLATES.find(entry=>entry.id===nameplateId)?.name}</Text></View></View>

  <View style={s.sectionHead}><Text style={s.section}>GUILD TAG</Text><Text style={s.sectionMeta}>{tagDirty?'Change pending':'Permanent identity'}</Text></View><View style={s.warningCard}><Text style={s.warning}>Changing a tag permanently retires the old one. It will never return to the available pool.</Text></View><View style={s.tagRow}><GameTextInput editable={editable&&!busy} autoCapitalize="characters" value={tag} onChangeText={value=>setTag(normalizeGuildTag(value).slice(0,3))} maxLength={3} placeholder="TAG" placeholderTextColor={C.muted} style={[s.input,s.tagInput]}/><GameButton title="Change tag" tone="danger" disabled={!editable||busy||tag.length!==3||!tagDirty} onPress={()=>void saveTag()}/></View>
  <Text style={s.section}>Tag color</Text><View style={s.row}>{GUILD_TAG_COLORS.map(entry=>{const unlocked=entry.minimumGuildLevel?entitlements.guildLevel>=entry.minimumGuildLevel:entry.achievementId?entitlements.pveAchievementIds.includes(entry.achievementId):true;return <Pressable key={entry.id} disabled={!editable||busy||!unlocked} onPress={()=>setTagColorId(entry.id)} style={[s.option,entry.id===tagColorId&&s.selected,!unlocked&&s.locked]}><View style={[s.colorDot,{backgroundColor:entry.color}]}/><Text style={s.optionText}>{entry.name}</Text><Text style={s.meta}>{unlocked?'Available':entry.minimumGuildLevel?`Guild Level ${entry.minimumGuildLevel}`:'Guild achievement required'}</Text></Pressable>})}</View>

  <Text style={s.section}>Banner / emblem</Text><View style={s.grid}>{GUILD_BANNERS.map(entry=><Pressable key={entry.id} disabled={!editable||busy} onPress={()=>setBannerId(entry.id)} style={[s.bannerCard,entry.id===bannerId&&s.selected]}><View style={[s.swatch,{backgroundColor:entry.primary,borderColor:entry.secondary}]}><Text style={[s.emblem,{color:entry.secondary}]}>{entry.emblem}</Text></View><Text style={s.cardName}>{entry.name}</Text></Pressable>)}</View>
  <Text style={s.section}>Profile border</Text><View style={s.row}>{GUILD_FRAMES.map(entry=>{const unlocked=isGuildCosmeticUnlocked(entry.unlock,entitlements),source=entry.assetKey?guildBorderSourceByKey.get(entry.assetKey):undefined;return <Pressable key={entry.id} disabled={!editable||busy||!unlocked} onPress={()=>setFrameId(entry.id)} style={[s.option,entry.id===frameId&&{borderColor:entry.accent,backgroundColor:C.selection},!unlocked&&s.locked]}><View style={[s.frameSample,{borderColor:entry.accent}]}>{source?<Image accessible={false} source={source} resizeMode="contain" style={StyleSheet.absoluteFill}/>:null}</View><Text style={s.optionText}>{entry.name}</Text><Text style={s.meta}>{unlocked?'Available':guildCosmeticUnlockLabel(entry.unlock)}</Text></Pressable>})}</View>
  <Text style={s.section}>Guild name color</Text><View style={s.row}>{GUILD_NAME_COLORS.map(entry=>{const unlocked=isGuildCosmeticUnlocked(entry.unlock,entitlements);return <Pressable key={entry.id} disabled={!editable||busy||!unlocked} onPress={()=>setNameColorId(entry.id)} style={[s.option,entry.id===nameColorId&&s.selected,!unlocked&&s.locked]}><View style={[s.colorDot,{backgroundColor:entry.color}]}/><Text style={s.optionText}>{entry.name}</Text><Text style={s.meta}>{unlocked?'Available':guildCosmeticUnlockLabel(entry.unlock)}</Text></Pressable>})}</View>
  <Text style={s.section}>Nameplate</Text><View style={s.row}>{GUILD_NAMEPLATES.map(entry=>{const unlocked=isGuildCosmeticUnlocked(entry.unlock,entitlements),source=entry.assetKey?guildNameplateSourceByKey.get(entry.assetKey):undefined;return <Pressable key={entry.id} disabled={!editable||busy||!unlocked} onPress={()=>setNameplateId(entry.id)} style={[s.option,entry.id===nameplateId&&{borderColor:entry.accent,backgroundColor:'#272417'},!unlocked&&s.locked]}><View style={[s.nameplate,{borderColor:entry.accent}]}>{source?<Image accessible={false} source={source} resizeMode="contain" style={StyleSheet.absoluteFill}/>:<View style={[s.gem,{backgroundColor:entry.accent}]}/>}</View><Text style={s.optionText}>{entry.name}</Text><Text style={s.meta}>{unlocked?'Available':guildCosmeticUnlockLabel(entry.unlock)}</Text></Pressable>})}</View>
  <Text style={s.section}>Guild motto</Text><GameTextInput editable={editable&&!busy} value={motto} onChangeText={value=>setMotto(value.slice(0,80))} maxLength={80} placeholder="Stronger together." placeholderTextColor={C.muted} style={s.input}/><Text style={s.counter}>{motto.length}/80</Text>
  {editable?<GameButton title={busy?'Saving…':appearanceDirty?'Save Guild Appearance':'Appearance Saved'} disabled={busy||!appearanceDirty} onPress={()=>void save()}/>:null}
 </Panel>;
}
function makeStyles(C:ThemeColors){return StyleSheet.create({heading:{flexDirection:'row',alignItems:'center',gap:spacing.sm},flex:{flex:1,minWidth:0},eyebrow:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:.8},title:{...typography.title,color:C.text},help:{...typography.caption,color:C.muted},saveState:{paddingHorizontal:7,paddingVertical:4,borderWidth:1,borderColor:C.good,borderRadius:99,backgroundColor:C.goodSurface},saveStateDirty:{borderColor:C.warning,backgroundColor:C.warningSurface},saveStateText:{fontSize:8,color:C.good,fontWeight:'900',letterSpacing:.6},saveStateTextDirty:{color:C.warning},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8,marginTop:12},sectionMeta:{fontSize:8.5,color:C.muted,fontWeight:'800'},warningCard:{padding:7,borderWidth:1,borderColor:C.warning,borderRadius:radii.sm,backgroundColor:C.warningSurface,marginBottom:6},warning:{...typography.caption,color:C.warning},preview:{marginTop:10,padding:10,borderWidth:2,borderRadius:radii.lg,backgroundColor:C.panel2,flexDirection:'row',gap:10,alignItems:'center'},crestPreview:{width:82,height:82,alignItems:'center',justifyContent:'center'},crestFrame:{position:'absolute',width:82,height:82},previewName:{fontSize:18,fontWeight:'900'},motto:{color:C.accent,fontStyle:'italic',marginTop:2},meta:{color:C.muted,fontSize:10,marginTop:5},section:{...typography.caption,color:C.accent,fontWeight:'900',letterSpacing:.75,marginTop:12,marginBottom:6},grid:{flexDirection:'row',flexWrap:'wrap',gap:7},bannerCard:{width:'31%',minWidth:88,padding:6,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2},selected:{borderColor:C.accent,backgroundColor:'#272417'},locked:{opacity:.42},swatch:{height:62,borderWidth:2,borderRadius:7,alignItems:'center',justifyContent:'center'},emblem:{fontSize:26,fontWeight:'900'},cardName:{color:C.text,fontSize:10,fontWeight:'800',marginTop:5},row:{flexDirection:'row',flexWrap:'wrap',gap:7},tagRow:{flexDirection:'row',gap:8,alignItems:'flex-start'},tagInput:{flex:1,fontWeight:'900',letterSpacing:3},option:{minWidth:120,flexGrow:1,padding:8,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.panel2},optionText:{color:C.text,fontSize:11,fontWeight:'800',marginTop:5},colorDot:{width:24,height:24,borderRadius:12,borderWidth:1,borderColor:C.line},frameSample:{width:56,height:56,borderWidth:1,borderRadius:10,backgroundColor:C.stage,overflow:'hidden'},nameplate:{height:48,borderWidth:1,borderRadius:7,backgroundColor:C.panel,justifyContent:'center',overflow:'hidden'},gem:{width:10,height:10,alignSelf:'center',transform:[{rotate:'45deg'}]},input:{minHeight:44,borderWidth:1,borderColor:C.line,borderRadius:radii.md,backgroundColor:C.inputBg,color:C.text,paddingHorizontal:12},counter:{color:C.muted,textAlign:'right',fontSize:10,marginTop:3}});}
