import {accountText,accountError} from '../i18n/account';
import {GameTextInput as TextInput} from './GameTextInput';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Alert,AppState,Keyboard,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {GameButton} from './GameButton';
import {GameModalHeader,GameModalSurface} from './GameModalSurface';
import {Panel} from './Panel';
import type {GameState} from '../core/types';
import {createOnlineAccount,finishGuestAccount,requestPasswordRecovery,resendAccountConfirmation,resendGuestAccountConfirmation,sendMagicLink,signInAsGuest,signInWithPassword,signOut,updateAccountPassword,upgradeGuestAccount} from '../online/account';
import {onlineConfigured} from '../online/supabase';
import {useAuthSession} from '../online/AuthSessionProvider';
import {serverGameplayEnabled} from '../online/gameplay';
import {passwordRequirements} from '../core/auth-callback';
import {accountLinkStep,pendingAccountEmail} from '../core/auth-account-link';
import {equipmentTheme,spacing,touchTargetMin,typography,type ThemeColors} from '../theme/theme';
import {useGameTheme} from '../theme/ThemeContext';
type VerificationPrompt={email:string;kind:'signup'|'guest';accountId:string};
function AuthModeChip({label,selected,disabled,onPress}:{label:string;selected:boolean;disabled:boolean;onPress:()=>void}){const C=useGameTheme(),equipmentColors=equipmentTheme(C);return <Pressable accessibilityRole="button" accessibilityState={{selected,disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[{minHeight:40,alignSelf:'center',paddingHorizontal:14,justifyContent:'center',borderWidth:1,borderColor:C.line,borderRadius:99,backgroundColor:C.bg},selected&&{borderColor:equipmentColors.selectedLine,backgroundColor:equipmentColors.selected},disabled&&{opacity:.45},pressed&&{opacity:.76}]}><Text style={[{fontSize:12,color:C.muted,fontWeight:'700'},selected&&{color:C.primaryButtonText}]}>{selected?'✓ ':''}{label}</Text></Pressable>}
export function OnlineAccountPanel({state}:{state:GameState}){
 const C=useGameTheme(),s=useMemo(()=>makeStyles(C),[C]);
 const language=state.settings.language;
 const a=(text:string,params?:Record<string,string|number>)=>accountText(language,text,params);

 const auth=useAuthSession();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(state.character?.name??''),[creating,setCreating]=useState(false),[showHelp,setShowHelp]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[noticeTone,setNoticeTone]=useState<'error'|'success'|'info'>('error'),[editingLink,setEditingLink]=useState(false);
 const [passwordVisible,setPasswordVisible]=useState(false),[changingPassword,setChangingPassword]=useState(false),[verificationPrompt,setVerificationPrompt]=useState<VerificationPrompt|null>(null),[verificationFeedback,setVerificationFeedback]=useState<{message:string;error:boolean}|null>(null);
 const accountId=auth.session?.user.id??'',linkStep=auth.session?accountLinkStep(auth.session.user):null;
 const active=useRef(true),currentAccount=useRef(accountId),accountGeneration=useRef(0),running=useRef<object|null>(null),currentRecovery=useRef(auth.clearRecovery);
 if(currentAccount.current!==accountId){currentAccount.current=accountId;accountGeneration.current++;running.current=null;}
 currentRecovery.current=auth.clearRecovery;const generation=accountGeneration.current;
 const ownsView=()=>active.current&&currentAccount.current===accountId&&accountGeneration.current===generation;
 const editingPassword=auth.recovering||changingPassword;
 const requirements=passwordRequirements(password),showPasswordRules=creating||editingPassword||linkStep==='set_password';
 const displayedNotice=auth.error||notice,displayedTone=auth.error?'error':noticeTone;
 useEffect(()=>{active.current=true;const subscription=AppState.addEventListener('change',next=>{if(next!=='active')setPasswordVisible(false);});return()=>{active.current=false;subscription.remove();};},[]);
 useEffect(()=>{setPassword('');setPasswordVisible(false);setChangingPassword(false);setBusy(false);setNotice('');setEditingLink(false);setVerificationPrompt(null);setVerificationFeedback(null);setEmail(auth.session?pendingAccountEmail(auth.session.user):'');},[accountId]);
 useEffect(()=>{setPasswordVisible(false);},[creating,editingPassword,linkStep]);
 useEffect(()=>{if(auth.recovering){setChangingPassword(false);setPassword('');setPasswordVisible(false);setNotice('');}},[auth.recovering,auth.clearRecovery]);
 useEffect(()=>{if(linkStep==='set_password'){setNotice('');setEditingLink(false);}},[linkStep]);
 useEffect(()=>{if(verificationPrompt&&(verificationPrompt.accountId!==accountId||auth.recovering||(verificationPrompt.kind==='guest'&&linkStep!=='guest'&&linkStep!=='verify_email')))setVerificationPrompt(null);},[verificationPrompt,accountId,auth.recovering,linkStep]);
 const success=(message:string)=>{if(!ownsView())return;setNoticeTone('success');setNotice(message);if(verificationPrompt)setVerificationFeedback({message,error:false});};
 const information=(message:string)=>{if(!ownsView())return;setNoticeTone('info');setNotice(message);if(verificationPrompt)setVerificationFeedback({message,error:false});};
 const run=async(action:()=>Promise<void>)=>{const ownsRequest=()=>ownsView()&&(!editingPassword||currentRecovery.current===auth.clearRecovery);if(running.current||!ownsRequest())return;const operation={};running.current=operation;setBusy(true);setPasswordVisible(false);setNoticeTone('error');setNotice('');setVerificationFeedback(null);try{await action();if(ownsRequest())setPassword('');}catch(e){if(ownsRequest()){const message=e instanceof Error?e.message:"Please try again.";setNotice(message);if(verificationPrompt)setVerificationFeedback({message,error:true});}}finally{if(running.current===operation){running.current=null;if(ownsView())setBusy(false);}}};
 const savePassword=async()=>{await updateAccountPassword(password,accountId);if(!ownsView()||currentRecovery.current!==auth.clearRecovery)return;if(auth.recovering)auth.clearRecovery(accountId);setChangingPassword(false);success('Password updated.');};
 const cancelPassword=()=>{if(running.current||!ownsView())return;setPassword('');setPasswordVisible(false);setChangingPassword(false);setNotice('');if(auth.recovering)auth.clearRecovery(accountId);};
 const showVerification=(recipient:string,kind:VerificationPrompt['kind'],message?:string)=>{if(!ownsView())return;Keyboard.dismiss();setPasswordVisible(false);setVerificationFeedback(message?{message,error:false}:null);setVerificationPrompt({email:recipient.trim().toLowerCase(),kind,accountId});};
 const closeVerification=()=>{if(verificationPrompt?.kind==='signup'){setCreating(false);setShowHelp(false);}setPasswordVisible(false);setVerificationPrompt(null);setVerificationFeedback(null);};
 const checkVerification=async()=>{const next=await auth.refreshAccount();if(!next)throw new Error('Sign in first.');const step=accountLinkStep(next.user);if(step==='linked')success('Account linked. Your characters and progress are kept.');else if(step==='set_password')success('Your email is verified. Set a password to finish securing this account.');else information('Email is not verified yet. Open the latest confirmation email, then check again.');};
 const emailInput=<><Text style={s.label}>{a("Email address")}</Text><TextInput accessibilityLabel={a("Email address")} value={email} onChangeText={setEmail} editable={!busy} keyboardType="email-address" autoCapitalize="none" autoComplete="email" autoCorrect={false} placeholder="you@example.com" placeholderTextColor={C.muted} style={s.input}/></>;
 const passwordLabel=editingPassword?a("New password"):a("Password");
 const passwordInput=<><View style={s.passwordLabelRow}><Text style={s.passwordLabel}>{passwordLabel}</Text><Pressable accessibilityRole="button" accessibilityLabel={a(passwordVisible?"Hide password":"Show password")} accessibilityState={{selected:passwordVisible,disabled:busy}} disabled={busy} onPress={()=>setPasswordVisible(value=>!value)} style={({pressed})=>[s.passwordToggle,pressed&&{opacity:.76},busy&&{opacity:.45}]}><Text style={s.passwordToggleText}>{a(passwordVisible?"Hide password":"Show password")}</Text></Pressable></View><TextInput accessibilityLabel={passwordLabel} value={password} onChangeText={setPassword} editable={!busy} secureTextEntry={!passwordVisible} autoCorrect={false} autoCapitalize="none" autoComplete={showPasswordRules?'new-password':'current-password'} placeholder={showPasswordRules?a("Create a strong password"):a("Password")} placeholderTextColor={C.muted} style={[s.input,s.passwordInput]}/>{showPasswordRules&&<View accessibilityLabel={a("Password requirements")} style={s.passwordRules}><Text style={s.passwordRulesTitle}>{a("Password requirements")}</Text>{([[a("8–128 characters"),requirements.length],[a("One uppercase letter"),requirements.uppercase],[a("One lowercase letter"),requirements.lowercase],[a("One number"),requirements.number],[a("One special character"),requirements.symbol]] as const).map(([label,met])=><Text key={label} style={[s.passwordRule,met&&s.passwordRuleMet]}>{met?'✓':'○'} {a(label)}</Text>)}</View>}</>;
 if(!onlineConfigured)return <Panel><Text style={s.title}>{a("Online account unavailable")}</Text><Text style={s.text}>{a("This build has no online connection configured.")}</Text></Panel>;
 return <Panel><Text accessibilityRole="header" style={s.title}>{auth.recovering?a("Reset your password"):changingPassword?a("Change password"):auth.session?a("Your account"):creating?a("Create your VELDRYN account"):a("Welcome to VELDRYN")}</Text>
  {!!displayedNotice&&<View accessibilityRole="alert" style={[s.noticeCard,displayedTone==='success'&&s.noticeSuccessCard,displayedTone==='info'&&s.noticeInfoCard]}><Text style={displayedTone==='success'?s.noticeLabelSuccess:displayedTone==='info'?s.noticeLabelInfo:s.noticeLabel}>{displayedTone==='success'?a("ACCOUNT UPDATED"):displayedTone==='info'?a("ACCOUNT STATUS"):a("ACCOUNT NOTICE")}</Text><Text style={s.notice}>{displayedTone==='error'?accountError(language,displayedNotice):a(displayedNotice)}</Text></View>}
  {editingPassword?<>{passwordInput}<GameButton title={a("Save new password")} disabled={busy} onPress={()=>void run(savePassword)}/><GameButton title={a("Cancel")} tone="secondary" disabled={busy} onPress={cancelPassword}/></>:!auth.session?<>
   {creating&&<><Text style={s.label}>{a("Username")}</Text><TextInput accessibilityLabel={a("Username")} value={username} onChangeText={setUsername} maxLength={20} placeholder={a("Username")} placeholderTextColor={C.muted} style={s.input}/></>}
   {emailInput}{passwordInput}
   <GameButton title={busy?a("Connecting…"):creating?a("Create account"):a("Sign in")} disabled={busy} onPress={()=>void run(async()=>{if(creating){const result=await createOnlineAccount(email,password,username);if(!result.confirmed){success('Confirmation email sent. Check your inbox before signing in.');showVerification(email,'signup');}}else await signInWithPassword(email,password);})}/>
   <AuthModeChip label={creating?a("Sign in instead"):a("Create a new account")} selected={creating} disabled={busy} onPress={()=>{setCreating(!creating);setNotice('');}}/>
   {!creating&&<><Text style={s.guestHint}>{a("Want to try the game first? A guest account can be secured with email later.")}</Text><GameButton title={a("Continue as guest")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await signInAsGuest();success('Guest account ready. Create your character to enter Asterfall.');})}/></>}
   <Pressable accessibilityRole="button" accessibilityState={{expanded:showHelp}} onPress={()=>setShowHelp(value=>!value)} style={s.helpToggle}><Text style={s.helpText}>{showHelp?a("Hide sign-in help"):a("Need help signing in?")}</Text></Pressable>
   {showHelp&&<View style={s.help}><Text style={s.text}>{a("Enter your email above to request a link.")}</Text><View style={s.row}><GameButton title={a("Resend confirmation")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await resendAccountConfirmation(email);success('If confirmation is needed, an email has been requested.');showVerification(email,'signup','If confirmation is needed, an email has been requested.');})}/><GameButton title={a("Forgot password")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await requestPasswordRecovery(email);success('If this email has an account, a recovery link has been requested.');})}/></View>
   <GameButton title={a("Email a sign-in link")} tone="secondary" disabled={busy} onPress={()=>void run(async()=>{await sendMagicLink(email);success('Check your email and open the link on this device.');})}/></View>}
   <Text style={s.text}>{serverGameplayEnabled?a("Online characters and progress are saved on the server. Your existing local save is kept separately."):a("Your local game remains on this device. Online social features use your account.")}</Text>
  </>:<>
   <Text style={[s.label,(linkStep==='linked'||linkStep==='set_password')&&{color:C.good}]}>{a(linkStep==='linked'?'Linked account':linkStep==='set_password'?'Email linked':linkStep==='verify_email'?'Waiting for email verification':'Guest account')}</Text>
   <Text style={s.text}>{a('Signed in as {identity}.',{identity:auth.session.user.email||a('guest')})}</Text>
   {(linkStep==='guest'||(linkStep==='verify_email'&&editingLink))&&<>
    <Text style={s.text}>{a("Add an email first. After verification, choose a password. Your characters and progress stay with this account.")}</Text>
    <Text style={s.label}>{a("Username")}</Text><TextInput accessibilityLabel={a("Username")} value={username} onChangeText={setUsername} maxLength={20} placeholder={a("Username")} placeholderTextColor={C.muted} style={s.input}/>{emailInput}
    <GameButton title={a("Secure guest account")} disabled={busy||auth.refreshing} onPress={()=>void run(async()=>{await upgradeGuestAccount(email,username,accountId);if(!ownsView())return;setEditingLink(false);information('Confirmation email sent. Open the latest email, then return here.');showVerification(email,'guest');})}/>
   </>}
   {linkStep==='verify_email'&&!editingLink&&<>
    <Text style={s.text}>{a('Confirm the email sent to {email}.',{email:pendingAccountEmail(auth.session.user)})}</Text>
    <Text style={s.text}>{a("Open the latest confirmation email, then return here. You can keep playing while you wait.")}</Text>
    <GameButton title={a("Resend confirmation")} tone="secondary" disabled={busy||auth.refreshing} onPress={()=>void run(async()=>{await resendGuestAccountConfirmation(accountId);const next=await auth.refreshAccount();information('If confirmation is needed, an email has been requested.');if(next&&accountLinkStep(next.user)==='verify_email')showVerification(pendingAccountEmail(next.user),'guest','If confirmation is needed, an email has been requested.');})}/>
    {auth.session.user.is_anonymous&&<GameButton title={a("Use a different email")} tone="secondary" disabled={busy||auth.refreshing} onPress={()=>{setEmail(pendingAccountEmail(auth.session!.user));setEditingLink(true);setNotice('');}}/>}
   </>}
   {(linkStep==='guest'||linkStep==='verify_email')&&<GameButton title={auth.refreshing?a("Checking verification…"):a("Check verification")} tone="secondary" disabled={busy||auth.refreshing} onPress={()=>void run(checkVerification)}/>}
   {linkStep==='set_password'&&<>
    <Text style={s.text}>{a("Your email is verified. Set a password to finish securing this account.")}</Text>{passwordInput}
    <GameButton title={a("Save account password")} disabled={busy||auth.refreshing} onPress={()=>void run(async()=>{await finishGuestAccount(password,accountId);success('Account linked. Your characters and progress are kept.');})}/>
   </>}
   {linkStep==='linked'&&<GameButton title={a("Change password")} tone="secondary" disabled={busy||auth.refreshing} onPress={()=>{if(running.current||!ownsView())return;setPassword('');setPasswordVisible(false);setNotice('');setChangingPassword(true);}}/>}
   <Text style={s.text}>{serverGameplayEnabled?a("Every successful gameplay action is saved online. Sign in on another device to continue."):a("Local save uploads do not grant online progression.")}</Text>
   <GameButton title={a("Sign out")} tone="secondary" disabled={busy} onPress={()=>{if(auth.session?.user.is_anonymous)Alert.alert(a("Sign out of guest account?"),a("Add an email first so you can recover this account."),[{text:a("Stay signed in")},{text:a("Sign out"),style:'destructive',onPress:()=>void run(signOut)}]);else void run(signOut);}}/>
  </>}
  {verificationPrompt&&verificationPrompt.accountId===accountId&&<GameModalSurface visible onClose={closeVerification} presentation="dialog" reduceMotion={state.settings.reduceMotion} dismissOnBackdrop={false}>
   <GameModalHeader title={a("Verify your email")} onClose={closeVerification}/>
   <ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} style={s.verificationScroll} contentContainerStyle={s.verificationContent}>
    <View style={[s.noticeCard,s.noticeSuccessCard]}><Text style={s.noticeLabelSuccess}>{a("Check your email")}</Text><Text style={s.notice}>{a("Check the inbox for this email address:")}</Text><Text selectable style={s.verificationEmail}>{verificationPrompt.email}</Text></View>
    <Text style={s.text}>{a("Open your inbox and tap the latest verification link. Check your spam or junk folder if you do not see it.")}</Text>
    <Text style={s.text}>{a(verificationPrompt.kind==='guest'?"Return to VELDRYN after verifying to finish securing your account. Your characters and progress stay with you.":"After verifying your email, return to VELDRYN and sign in.")}</Text>
    {(verificationFeedback||auth.error)&&<View accessibilityRole="alert" accessibilityLiveRegion="polite" style={[s.noticeCard,!(auth.error||verificationFeedback?.error)&&s.noticeInfoCard]}><Text style={s.notice}>{auth.error?accountError(language,auth.error):verificationFeedback?.error?accountError(language,verificationFeedback.message):a(verificationFeedback?.message??'')}</Text></View>}
    {verificationPrompt.kind==='guest'?<GameButton title={auth.refreshing?a("Checking verification…"):a("Check verification")} disabled={busy||auth.refreshing} onPress={()=>void run(checkVerification)}/>:<GameButton title={a("Back to sign in")} onPress={closeVerification}/>}
    <GameButton title={a("Resend confirmation")} tone="secondary" disabled={busy||auth.refreshing} onPress={()=>void run(async()=>{if(verificationPrompt.kind==='guest'){await resendGuestAccountConfirmation(accountId);await auth.refreshAccount();}else await resendAccountConfirmation(verificationPrompt.email);success('If confirmation is needed, an email has been requested.');})}/>
    {verificationPrompt.kind==='guest'&&<GameButton title={a("Continue playing")} tone="secondary" onPress={closeVerification}/>}
   </ScrollView>
  </GameModalSurface>}
 </Panel>;
}
function makeStyles(C:ThemeColors){return StyleSheet.create({title:{color:C.text,...typography.title},label:{color:C.text,...typography.bodyStrong,marginTop:spacing.sm},helpToggle:{minHeight:48,justifyContent:'center',alignItems:'center'},helpText:{...typography.body,color:C.info},help:{gap:spacing.sm,paddingTop:spacing.sm,borderTopWidth:1,borderColor:C.line},text:{color:C.muted,lineHeight:21,marginVertical:spacing.sm},guestHint:{color:C.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:spacing.sm},passwordLabelRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:spacing.sm},passwordLabel:{color:C.text,...typography.bodyStrong,flexShrink:1},passwordToggle:{minHeight:48,minWidth:48,maxWidth:'70%',paddingHorizontal:spacing.sm,justifyContent:'center',borderRadius:8},passwordToggleText:{color:C.info,...typography.bodyStrong,textAlign:'center',flexShrink:1},passwordInput:{marginTop:0},verificationScroll:{flexShrink:1},verificationContent:{gap:spacing.sm,paddingBottom:spacing.sm},verificationEmail:{color:C.text,...typography.bodyStrong,lineHeight:22,flexShrink:1},passwordRules:{paddingHorizontal:spacing.sm,paddingBottom:spacing.sm,gap:3},passwordRulesTitle:{color:C.text,fontSize:12,fontWeight:'700',marginBottom:2},passwordRule:{color:C.muted,fontSize:12,lineHeight:18},passwordRuleMet:{color:C.good},noticeCard:{gap:4,padding:spacing.sm,borderWidth:1,borderColor:C.bad,borderRadius:8,backgroundColor:C.badSurface,marginVertical:spacing.sm},noticeSuccessCard:{borderColor:C.good,backgroundColor:C.goodSurface},noticeInfoCard:{borderColor:C.info,backgroundColor:C.infoSurface},noticeLabel:{...typography.caption,color:C.bad,fontWeight:'900',letterSpacing:1},noticeLabelSuccess:{...typography.caption,color:C.good,fontWeight:'900',letterSpacing:1},noticeLabelInfo:{...typography.caption,color:C.info,fontWeight:'900',letterSpacing:1},notice:{color:C.text,lineHeight:21},noticeSuccess:{color:C.text},input:{minHeight:touchTargetMin,borderWidth:1,borderColor:C.line,color:C.text,padding:spacing.sm,marginVertical:spacing.sm},row:{flexDirection:'row',flexWrap:'wrap',gap:spacing.sm}});}
