import {ITEMS,itemDef} from '../content/items';
import {COMBAT_COMPANIONS} from '../content/combat-companions';
import type {CharacterLoadoutPreset,GameState,GearSlot} from './types';
import {effectiveStats} from './game';
import {equipCombatCompanion,unequipCombatCompanion} from './combat-companions';
import {planLoadoutStorage} from './loadout-storage';

export const CHARACTER_LOADOUT_SLOT_COUNT=3;
const slots:GearSlot[]=['weapon','offhand','helmet','chest','legs','boots','gloves','cape','amulet','ring'];
const cleanName=(value:unknown,fallback:string)=>typeof value==='string'&&value.trim()?value.trim().slice(0,28):fallback;
export function normalizeCharacterLoadouts(value:any,classId:string):CharacterLoadoutPreset[]{if(!Array.isArray(value))return [];const bySlot=new Map<number,CharacterLoadoutPreset>();value.slice(0,12).forEach((raw:any,index)=>{if(!raw||typeof raw!=='object'||raw.classId!==classId)return;const slotIndex=Number.isInteger(raw.slotIndex)&&raw.slotIndex>=0&&raw.slotIndex<CHARACTER_LOADOUT_SLOT_COUNT?raw.slotIndex:index;if(slotIndex<0||slotIndex>=CHARACTER_LOADOUT_SLOT_COUNT||bySlot.has(slotIndex))return;const equipment:Partial<Record<GearSlot,string>>={};for(const slot of slots){const id=raw.equipment?.[slot];const def=typeof id==='string'?ITEMS.find(item=>item.id===id):undefined;if(def?.type==='gear'&&def.slot===slot&&(!def.classRestriction||def.classRestriction===classId))equipment[slot]=id;}const foodId=typeof raw.foodId==='string'&&ITEMS.some(item=>item.id===raw.foodId&&item.type==='food')?raw.foodId:undefined;const companionId=typeof raw.companionId==='string'&&COMBAT_COMPANIONS.some(def=>def.id===raw.companionId)?raw.companionId:undefined;bySlot.set(slotIndex,{id:typeof raw.id==='string'&&raw.id?raw.id:`loadout-${slotIndex+1}`,slotIndex,name:cleanName(raw.name,`Loadout ${slotIndex+1}`),classId:classId as any,equipment,foodId,companionId,createdAtMs:Number.isFinite(raw.createdAtMs)?raw.createdAtMs:0,updatedAtMs:Number.isFinite(raw.updatedAtMs)?raw.updatedAtMs:0});});return [...bySlot.values()].sort((a,b)=>a.slotIndex-b.slotIndex);}
export function saveCharacterLoadout(state:GameState,index:number,name?:string,nowMs=Date.now()):GameState{if(!state.character)throw new Error('Create a character first.');if(index<0||index>=CHARACTER_LOADOUT_SLOT_COUNT)throw new Error('Invalid loadout slot.');const current=normalizeCharacterLoadouts(state.character.savedLoadouts,state.character.classId),existing=current.find(entry=>entry.slotIndex===index),preset:CharacterLoadoutPreset={id:existing?.id??`loadout-${index+1}`,slotIndex:index,name:cleanName(name,existing?.name??`Loadout ${index+1}`),classId:state.character.classId,equipment:{...state.character.equipment},foodId:state.character.equippedFoodId,companionId:state.character.equippedCombatCompanionId,createdAtMs:existing?.createdAtMs??nowMs,updatedAtMs:nowMs};return {...state,character:{...state.character,savedLoadouts:[...current.filter(entry=>entry.slotIndex!==index),preset].sort((a,b)=>a.slotIndex-b.slotIndex)}};}
export function renameCharacterLoadout(state:GameState,id:string,name:string,nowMs=Date.now()):GameState{if(!state.character)throw new Error('Create a character first.');const list=normalizeCharacterLoadouts(state.character.savedLoadouts,state.character.classId),index=list.findIndex(entry=>entry.id===id);if(index<0)throw new Error('Loadout not found.');const next=[...list];next[index]={...next[index],name:cleanName(name,next[index].name),updatedAtMs:nowMs};return {...state,character:{...state.character,savedLoadouts:next}};}
export function deleteCharacterLoadout(state:GameState,id:string):GameState{return !state.character?state:{...state,character:{...state.character,savedLoadouts:normalizeCharacterLoadouts(state.character.savedLoadouts,state.character.classId).filter(entry=>entry.id!==id)}};}
export function applyCharacterLoadout(state:GameState,id:string):GameState{if(!state.character)throw new Error('Create a character first.');if(state.activity?.kind==='combat')throw new Error('Stop combat before changing loadouts.');const preset=normalizeCharacterLoadouts(state.character.savedLoadouts,state.character.classId).find(entry=>entry.id===id);if(!preset)throw new Error('Loadout not found.');for(const slot of slots){const wanted=preset.equipment[slot];if(!wanted)continue;const def=itemDef(wanted);if(def.type!=='gear'||def.slot!==slot||def.classRestriction&&def.classRestriction!==state.character.classId)throw new Error(`${def.name} is not valid for this loadout.`);}let planned;try{planned=planLoadoutStorage({inventory:state.inventory.stacks,bank:state.bank.stacks,inventoryCapacity:state.inventory.capacity,bankCapacity:state.bank.capacity,currentEquipment:state.character.equipment,desiredEquipment:preset.equipment});}catch(error){if(error instanceof Error&&error.message.startsWith('MISSING:'))throw new Error(`${itemDef(error.message.slice(8)).name} is not equipped, in Inventory, or in Bank.`);throw error;}if(preset.foodId&&!planned.inventory.some(entry=>entry.itemId===preset.foodId&&entry.quantity>0))throw new Error(`${itemDef(preset.foodId).name} must be carried in Inventory before this loadout can use it.`);let next={...state,inventory:{...state.inventory,stacks:planned.inventory},bank:{...state.bank,stacks:planned.bank},character:{...state.character,equipment:preset.equipment,equippedFoodId:preset.foodId}} as GameState;next=preset.companionId?equipCombatCompanion(next,preset.companionId):unequipCombatCompanion(next);next.character!.currentHp=Math.min(next.character!.currentHp,effectiveStats(next).hp);return next;}
