export type GuildCosmeticUnlock={type:'default'}|{type:'guild_level';level:number}|{type:'banner_gallery_tier';tier:number}|{type:'guild_pve';achievementId:string;label:string}|{type:'event';cosmeticId:string;label:string};
export interface GuildAppearanceEntitlements{guildLevel:number;bannerGalleryTier:number;pveAchievementIds:readonly string[];eventCosmeticIds?:readonly string[];revealedEventColorIds?:readonly string[]}
export type GuildBannerId='swordwing_blue'|'world_tree_green'|'phoenix_crimson'|'moon_star_indigo'|'wolf_peak_charcoal'|'arcane_eye_purple'|'sun_lion_ivory'|'forge_anvil_teal'|'halloween_pumpkin_lantern'|'halloween_bat_moon';
export type GuildFrameId='classic'|'bronze_fellowship'|'silver_fellowship'|'grand_gold'|'emerald_vine'|'sapphire_dungeon'|'crimson_bossbreaker'|'amethyst_raidforged'|'mythic_conqueror'|'border_halloween_veil';
export type GuildNameplateId='classic'|'sapphire_royal';
export type GuildBackgroundId='plain'|'guild_plaza'|'forest_sanctum';
export const GUILD_BACKGROUNDS:readonly {id:GuildBackgroundId;name:'Plain'|'Guild Plaza'|'Forest Sanctum';unlock:GuildCosmeticUnlock}[]=[
 {id:'plain',name:'Plain',unlock:{type:'default'}},
 {id:'guild_plaza',name:'Guild Plaza',unlock:{type:'default'}},
 {id:'forest_sanctum',name:'Forest Sanctum',unlock:{type:'guild_level',level:10}},
];
export function normalizeGuildBackgroundId(value:unknown):GuildBackgroundId{return GUILD_BACKGROUNDS.some(row=>row.id===value)?value as GuildBackgroundId:'plain'}
export type GuildNameColorId='name_ivory'|'name_halloween_orange';
export interface GuildBannerDefinition{id:GuildBannerId;name:string;emblem:string;primary:string;secondary:string;assetKey:string;unlock:GuildCosmeticUnlock}
export interface GuildFrameDefinition{id:GuildFrameId;name:string;accent:string;assetKey:string;unlock:GuildCosmeticUnlock}
export interface GuildNameplateDefinition{id:GuildNameplateId;name:string;accent:string;assetKey?:string;unlock:GuildCosmeticUnlock}
export interface GuildNameColorDefinition{id:GuildNameColorId;name:string;color:string;unlock:GuildCosmeticUnlock}
const DEFAULT={type:'default'} as const;
export const GUILD_BANNERS:GuildBannerDefinition[]=[
 {id:'swordwing_blue',name:'Swordwing',emblem:'⚔',primary:'#174f9f',secondary:'#d8e5f3',assetKey:'banner_swordwing_blue',unlock:DEFAULT},{id:'world_tree_green',name:'Worldtree',emblem:'♧',primary:'#155438',secondary:'#caa55d',assetKey:'banner_worldtree_green',unlock:DEFAULT},{id:'phoenix_crimson',name:'Crimson Phoenix',emblem:'✦',primary:'#8f1f2b',secondary:'#e9bb4f',assetKey:'banner_phoenix_crimson',unlock:DEFAULT},{id:'moon_star_indigo',name:'Moonstar',emblem:'☾',primary:'#253f91',secondary:'#e4cf91',assetKey:'banner_moonstar_indigo',unlock:DEFAULT},{id:'wolf_peak_charcoal',name:'Wolf of the Peaks',emblem:'▲',primary:'#252b33',secondary:'#b8d7ed',assetKey:'banner_wolf_mountain',unlock:DEFAULT},{id:'arcane_eye_purple',name:'Arcane Eye',emblem:'◉',primary:'#54278b',secondary:'#dab35d',assetKey:'banner_arcane_eye',unlock:DEFAULT},{id:'sun_lion_ivory',name:'Sun-Crowned Lion',emblem:'☀',primary:'#f0e6cf',secondary:'#bc842d',assetKey:'banner_lion_sun',unlock:DEFAULT},{id:'forge_anvil_teal',name:'Emerald Forge',emblem:'◆',primary:'#155c59',secondary:'#a9804d',assetKey:'banner_forge_emerald',unlock:DEFAULT},
 {id:'halloween_pumpkin_lantern',name:'Pumpkin Lantern',emblem:'🎃',primary:'#7a2f12',secondary:'#ff9a35',assetKey:'banner_halloween_pumpkin_lantern',unlock:{type:'event',cosmeticId:'halloween_pumpkin_lantern',label:'Veilbreak milestone'}},{id:'halloween_bat_moon',name:'Bat Moon',emblem:'☾',primary:'#24183f',secondary:'#f08b32',assetKey:'banner_halloween_bat_moon',unlock:{type:'event',cosmeticId:'halloween_bat_moon',label:'Veilbreak milestone'}},
];
export const GUILD_FRAMES:GuildFrameDefinition[]=[
 {id:'classic',name:'Founder Iron',accent:'#8f9aaa',assetKey:'border_founder_iron',unlock:DEFAULT},{id:'bronze_fellowship',name:'Bronze Fellowship',accent:'#b77844',assetKey:'border_bronze_fellowship',unlock:{type:'guild_level',level:5}},{id:'silver_fellowship',name:'Silver Fellowship',accent:'#c4d0dc',assetKey:'border_silver_fellowship',unlock:{type:'guild_level',level:10}},{id:'grand_gold',name:'Grand Guild',accent:'#e6c36a',assetKey:'border_grand_gold',unlock:{type:'guild_level',level:20}},{id:'emerald_vine',name:'Banner Gallery Vanguard',accent:'#38b77a',assetKey:'border_emerald_vanguard',unlock:{type:'banner_gallery_tier',tier:3}},{id:'sapphire_dungeon',name:'Dungeon Vanguard',accent:'#72b9ff',assetKey:'border_sapphire_dungeon',unlock:{type:'guild_pve',achievementId:'guild_pve_dungeon_25',label:'Complete 25 qualifying guild dungeon runs'}},{id:'crimson_bossbreaker',name:'Bossbreaker',accent:'#ff7b76',assetKey:'border_crimson_bossbreaker',unlock:{type:'guild_pve',achievementId:'guild_pve_bossbreaker',label:'Earn Guild Bossbreaker'}},{id:'amethyst_raidforged',name:'Raidforged',accent:'#c996ff',assetKey:'border_amethyst_raidforged',unlock:{type:'guild_pve',achievementId:'guild_pve_raid_first_clear',label:'Complete a qualifying Guild Raid'}},{id:'mythic_conqueror',name:'Mythic Conqueror',accent:'#fff1a0',assetKey:'border_mythic_conqueror',unlock:{type:'guild_pve',achievementId:'guild_pve_raid_hard_clear',label:'Complete a qualifying hard-mode Guild Raid'}},
 {id:'border_halloween_veil',name:'Veil Masquerade',accent:'#f08b32',assetKey:'border_halloween_veil',unlock:{type:'event',cosmeticId:'border_halloween_veil',label:'Veilbreak milestone'}},
];
export const GUILD_NAME_COLORS:GuildNameColorDefinition[]=[
 {id:'name_ivory',name:'Ivory',color:'#F1E7D0',unlock:DEFAULT},
 {id:'name_halloween_orange',name:'Halloworange',color:'#F08B32',unlock:{type:'event',cosmeticId:'name_halloween_orange',label:'Reach 25% in the Veilbreak guild event'}},
];
/** A released event color stays visible; ownership still controls selection. */
export function visibleGuildNameColors(entitlements:GuildAppearanceEntitlements){return GUILD_NAME_COLORS.filter(entry=>isGuildCosmeticUnlocked(entry.unlock,entitlements)||(entry.unlock.type==='event'&&entitlements.revealedEventColorIds?.includes(entry.id)));}
export const GUILD_NAMEPLATES:GuildNameplateDefinition[]=[{id:'classic',name:'No Nameplate',accent:'#c19b4d',unlock:DEFAULT},{id:'sapphire_royal',name:'Royal Sapphire',accent:'#4979d5',assetKey:'nameplate_royal_sapphire',unlock:{type:'banner_gallery_tier',tier:4}}];
export const DEFAULT_GUILD_BANNER_ID:GuildBannerId='world_tree_green',DEFAULT_GUILD_FRAME_ID:GuildFrameId='classic',DEFAULT_GUILD_NAMEPLATE_ID:GuildNameplateId='classic',DEFAULT_GUILD_NAME_COLOR_ID:GuildNameColorId='name_ivory';
export function isGuildCosmeticUnlocked(unlock:GuildCosmeticUnlock,s:GuildAppearanceEntitlements){switch(unlock.type){case'default':return true;case'guild_level':return s.guildLevel>=unlock.level;case'banner_gallery_tier':return s.bannerGalleryTier>=unlock.tier;case'guild_pve':return s.pveAchievementIds.includes(unlock.achievementId);case'event':return s.eventCosmeticIds?.includes(unlock.cosmeticId)??false}}
export function guildCosmeticUnlockLabel(unlock:GuildCosmeticUnlock){switch(unlock.type){case'default':return'Available';case'guild_level':return`Guild Level ${unlock.level}`;case'banner_gallery_tier':return`Banner Gallery Tier ${unlock.tier}`;case'guild_pve':return unlock.label;case'event':return unlock.label}}
export function normalizeGuildBannerId(value:unknown):GuildBannerId{return GUILD_BANNERS.some(x=>x.id===value)?value as GuildBannerId:DEFAULT_GUILD_BANNER_ID}
export function normalizeGuildFrameId(value:unknown):GuildFrameId{return GUILD_FRAMES.some(x=>x.id===value)?value as GuildFrameId:DEFAULT_GUILD_FRAME_ID}
export function normalizeGuildNameplateId(value:unknown):GuildNameplateId{return GUILD_NAMEPLATES.some(x=>x.id===value)?value as GuildNameplateId:DEFAULT_GUILD_NAMEPLATE_ID}
export function normalizeGuildNameColorId(value:unknown):GuildNameColorId{return GUILD_NAME_COLORS.some(x=>x.id===value)?value as GuildNameColorId:DEFAULT_GUILD_NAME_COLOR_ID}
export function normalizeGuildMotto(value:unknown){if(typeof value!=='string')return'Stronger together.';const clean=value.trim().replace(/\s+/g,' ');return clean.slice(0,80)||'Stronger together.'}
