import {DUNGEON_UNLOCK_LEVEL,EARLY_FEATURE_UNLOCKS,type EarlyFeatureId} from './feature-unlocks';

export type GameGuideId='getting_started'|'seasons_weather'|'working_toward'|'daily_supplies'|'live_events'|'pets'|'account_bonuses'|'chat_social'|'gathering_crafting'|'faith_blessings'|'combat_companions'|'contract_board'|'mastery_hall'|'guilds'|'rankings'|'coop_dungeons'|'companion_trials'|'additional_characters';
export type GameGuideDestination='Home'|'World'|'Skills'|'Inventory'|'Character'|'Companions'|'Guild'|'Coop'|'Faith'|'Events'|'Settings'|'DailySupplies'|'Collections'|'AccountBonuses'|'Quests'|'MasteryHall'|'Rankings'|'Friends';
export interface OnboardingGuideState{seenGuideIds:GameGuideId[];acknowledgedGuideIds:GameGuideId[];}
export interface GameGuideDefinition{id:GameGuideId;title:string;summary:string;unlockHint:string;destination:GameGuideDestination;unlock:(state:OnboardingGuideHost)=>boolean;}
export interface OnboardingGuideHost{character?:{level?:number}|null;quests?:readonly {questId:string;status:string}[];defeatedBossIds?:readonly string[];account:{guildMember?:boolean;unlockedCombatCompanionIds?:readonly string[];companionTrialProgress?:unknown;liveEvent?:{enabled?:boolean}|null;unlockedCharacterSlots?:number;guideState?:Partial<OnboardingGuideState>;}}
const level=(state:OnboardingGuideHost)=>Math.max(0,Math.floor(Number(state.character?.level)||0));
const questClaimed=(state:OnboardingGuideHost,questId:string)=>state.quests?.some(row=>row.questId===questId&&row.status==='claimed')===true;
const stagedFeatureUnlocked=(state:OnboardingGuideHost,id:EarlyFeatureId)=>questClaimed(state,EARLY_FEATURE_UNLOCKS[id].questId);
const stagedFeatureHint=(id:EarlyFeatureId)=>EARLY_FEATURE_UNLOCKS[id].requirement+'.';

export const GAME_GUIDE:readonly GameGuideDefinition[]=[
 {id:'getting_started',title:'Your first steps',summary:'Choose activities, collect progress, improve gear and follow your current goal.',unlockHint:'Create your first character.',destination:'Home',unlock:s=>!!s.character},
 {id:'seasons_weather',title:'Seasons & Weather',summary:'World conditions shape activity bonuses without changing reward authority.',unlockHint:'Reach character level 2.',destination:'World',unlock:s=>!!s.character&&level(s)>=2},
 {id:'working_toward',title:'Working Toward',summary:'Pick a personal target and get concrete next steps without exposing later systems too early.',unlockHint:stagedFeatureHint('workingToward'),destination:'Home',unlock:s=>stagedFeatureUnlocked(s,'workingToward')},
 {id:'daily_supplies',title:'Daily Supplies',summary:'Claim the account-wide daily track and activate its temporary activity bonus after the basic skill loop is introduced.',unlockHint:stagedFeatureHint('dailySupplies'),destination:'DailySupplies',unlock:s=>stagedFeatureUnlocked(s,'dailySupplies')},
 {id:'live_events',title:'Live Events',summary:'Time-limited events add activities, rewards and cosmetics once the event system has been introduced.',unlockHint:stagedFeatureHint('events'),destination:'Events',unlock:s=>stagedFeatureUnlocked(s,'events')},
 {id:'pets',title:'Pets',summary:'Rare pets can drop from eligible activities. Owned pets add a passive account bonus and one selected pet grants a stronger active bonus.',unlockHint:stagedFeatureHint('pets'),destination:'Collections',unlock:s=>stagedFeatureUnlocked(s,'pets')},
 {id:'account_bonuses',title:'Account Bonuses',summary:'Review permanent collection bonuses and temporary account modifiers after your first collectible systems arrive.',unlockHint:stagedFeatureHint('accountBonuses'),destination:'AccountBonuses',unlock:s=>stagedFeatureUnlocked(s,'accountBonuses')},
 {id:'chat_social',title:'Chat, Friends & player profiles',summary:'Use World chat, inspect player profiles and add Friends after the first regional combat loop.',unlockHint:stagedFeatureHint('friends'),destination:'Friends',unlock:s=>stagedFeatureUnlocked(s,'friends')},
 {id:'gathering_crafting',title:'Gathering & Crafting',summary:'Gather regional resources, process them and craft upgrades over time.',unlockHint:'Reach character level 4.',destination:'Skills',unlock:s=>!!s.character&&level(s)>=4},
 {id:'faith_blessings',title:'Faith & Blessings',summary:'Recover Holy Water, train Faith and choose one active blessing.',unlockHint:'Reach character level 5.',destination:'Faith',unlock:s=>!!s.character&&level(s)>=5},
 {id:'combat_companions',title:'Companion Sanctuary',summary:'Build a Tank, Damage and Support roster with Affinities, Housing, Bond progression, Expeditions and monthly Trials.',unlockHint:stagedFeatureHint('companions'),destination:'Companions',unlock:s=>stagedFeatureUnlocked(s,'companions')},
 {id:'contract_board',title:'Contract Board',summary:'Take regional, weekly and cooperative jobs after the core solo loop is established.',unlockHint:stagedFeatureHint('contracts'),destination:'Quests',unlock:s=>stagedFeatureUnlocked(s,'contracts')},
 {id:'mastery_hall',title:'Mastery Hall',summary:'Track long-term account-wide profession records once enough skilling actions exist to make mastery meaningful.',unlockHint:stagedFeatureHint('masteryHall'),destination:'MasteryHall',unlock:s=>stagedFeatureUnlocked(s,'masteryHall')},
 {id:'guilds',title:'Guilds',summary:'Join a persistent social group for chat, projects and asynchronous PvE.',unlockHint:stagedFeatureHint('guild'),destination:'Guild',unlock:s=>stagedFeatureUnlocked(s,'guild')},
 {id:'rankings',title:'Rankings',summary:'View server-calculated prestige boards after the campaign recognizes you among Asterfall guilds.',unlockHint:stagedFeatureHint('rankings'),destination:'Rankings',unlock:s=>stagedFeatureUnlocked(s,'rankings')},
 {id:'coop_dungeons',title:'Co-op Dungeons',summary:'Build a 1 Tank / 2 Damage / 1 Support party and make route choices through live co-op dungeons.',unlockHint:`Reach character level ${DUNGEON_UNLOCK_LEVEL}.`,destination:'Coop',unlock:s=>!!s.character&&level(s)>=DUNGEON_UNLOCK_LEVEL},
 {id:'companion_trials',title:'Companion Trials',summary:'Build a Companion-only Tank / Damage / Support trio for the globally rotating monthly Trial.',unlockHint:'Unlock the Companion Sanctuary and reach the Trial system.',destination:'Companions',unlock:s=>stagedFeatureUnlocked(s,'companions')&&!!s.account.companionTrialProgress},
 {id:'additional_characters',title:'Additional Characters',summary:'Unlock up to five characters while sharing account-wide systems.',unlockHint:'Unlock your second character slot.',destination:'Character',unlock:s=>Math.max(1,Math.floor(Number(s.account.unlockedCharacterSlots)||1))>=2},
];
const ids=new Set<GameGuideId>(GAME_GUIDE.map(item=>item.id));
export const DEFAULT_ONBOARDING_GUIDE_STATE:OnboardingGuideState={seenGuideIds:[],acknowledgedGuideIds:[]};
export function normalizeOnboardingGuideState(value:unknown):OnboardingGuideState{const raw=value&&typeof value==='object'?value as Partial<OnboardingGuideState>:{};const clean=(input:unknown)=>Array.isArray(input)?[...new Set(input.filter((id):id is GameGuideId=>typeof id==='string'&&ids.has(id as GameGuideId)))]:[];return{seenGuideIds:clean(raw.seenGuideIds),acknowledgedGuideIds:clean(raw.acknowledgedGuideIds)};}
export function guideDefinition(id:GameGuideId){const definition=GAME_GUIDE.find(item=>item.id===id);if(!definition)throw new Error('Unknown Game Guide topic.');return definition;}
export function unlockedGameGuide(state:OnboardingGuideHost){return GAME_GUIDE.filter(item=>item.unlock(state));}
export function newlyUnlockedGameGuide(state:OnboardingGuideHost){const saved=normalizeOnboardingGuideState(state.account.guideState);return unlockedGameGuide(state).filter(item=>!saved.acknowledgedGuideIds.includes(item.id));}
export function acknowledgeGameGuide<T extends OnboardingGuideHost>(state:T,id:GameGuideId,markSeen=false):T{const definition=guideDefinition(id);if(!definition.unlock(state))throw new Error('This Game Guide topic is not unlocked yet.');const saved=normalizeOnboardingGuideState(state.account.guideState);return {...state,account:{...state.account,guideState:{seenGuideIds:markSeen?[...new Set([...saved.seenGuideIds,id])]:saved.seenGuideIds,acknowledgedGuideIds:[...new Set([...saved.acknowledgedGuideIds,id])]}}} as T;}
export function markGameGuideSeen<T extends OnboardingGuideHost>(state:T,id:GameGuideId):T{return acknowledgeGameGuide(state,id,true);}
export function acknowledgeAllUnlockedGameGuide<T extends OnboardingGuideHost>(state:T):T{const saved=normalizeOnboardingGuideState(state.account.guideState);return {...state,account:{...state.account,guideState:{seenGuideIds:saved.seenGuideIds,acknowledgedGuideIds:[...new Set([...saved.acknowledgedGuideIds,...unlockedGameGuide(state).map(item=>item.id)])]}}} as T;}
