export const RANKING_PROFESSIONS=['mining','woodcutting','fishing','smithing','cooking','herbalism','alchemy','hunting','exploration','tailoring','enchanting','faith'] as const;
export type RankingProfessionBoard=typeof RANKING_PROFESSIONS[number];
export type RankingBoardId='profession_total'|RankingProfessionBoard|'dungeon_tier'|'dungeon_clears'|'achievement_score'|'guild'|'arena_rating'|'arena_wins';
export type RankingGroup='Account'|'Professions'|'Competitive'|'Dungeons'|'Guilds';
export interface RankingBoardDefinition{id:RankingBoardId;name:string;group:RankingGroup;description:string;unit:string;}
export interface RankingEntry{rank:number;entityType:'account'|'guild';displayName:string;guildTag?:string|null;guildTagColorId?:string|null;subtitle?:string;value:number;secondaryValue?:number;detail?:string;isSelf:boolean;}
export interface RankingSelf{listed:boolean;rank?:number;value:number;secondaryValue?:number;detail?:string;reason?:string;}
export interface RankingBoardSnapshot{board:RankingBoardId;title:string;description:string;unit:string;prestigeOnly:true;seasonId?:string;generatedAtMs:number;entries:RankingEntry[];self?:RankingSelf;}
const skillName=(id:string)=>id==='faith'?'Faith':id.charAt(0).toUpperCase()+id.slice(1);
export const RANKING_BOARDS:readonly RankingBoardDefinition[]=Object.freeze([{id:'profession_total',name:'Profession Total',group:'Account',description:'Combined server-tracked profession levels across all account characters.',unit:'levels'},{id:'achievement_score',name:'Achievement Score',group:'Account',description:'Prestige points from claimed account achievements.',unit:'points'},...RANKING_PROFESSIONS.map(id=>({id,name:skillName(id),group:'Professions' as const,description:`Highest ${skillName(id)} level on one account character.`,unit:'level'})),{id:'arena_rating',name:'Arena Rating',group:'Competitive',description:'Current Arena-season rating.',unit:'rating'},{id:'arena_wins',name:'Arena Wins',group:'Competitive',description:'Current Arena-season wins.',unit:'wins'},{id:'dungeon_tier',name:'Dungeon Tier',group:'Dungeons',description:'Highest cleared co-op tier, then clears at that tier.',unit:'tier'},{id:'dungeon_clears',name:'Dungeon Clears',group:'Dungeons',description:'Lifetime participant clear entitlements from co-op Dungeons.',unit:'clears'},{id:'guild',name:'Guild Prestige',group:'Guilds',description:'Guild level, then Guild XP. Prestige-only.',unit:'level'}]);
export const RANKING_GROUPS:readonly RankingGroup[]=['Account','Professions','Competitive','Dungeons','Guilds'];
export function rankingBoardDefinition(id:RankingBoardId){const row=RANKING_BOARDS.find(board=>board.id===id);if(!row)throw new Error(`Unknown ranking board ${id}`);return row;}
export function rankingValueLabel(board:RankingBoardId,value:number){const def=rankingBoardDefinition(board);return board==='dungeon_tier'?`Tier ${Math.max(0,Math.floor(value))}`:`${Math.floor(value).toLocaleString()} ${def.unit}`;}
