import rawCatalog from '../../../data/equipment_catalog_t1_t9_v23.json';
import type {EquipmentPieceV22,EquipmentSetV22,EquipmentSlot,EquipmentTierId,TierPacingV22,SlotPacingV22} from './equipment-types-v22';
const b=(v:unknown)=>String(v??'').toLowerCase()==='yes';
const slot=(v:unknown)=>String(v) as EquipmentSlot;
export const EQUIPMENT_SETS_V23:readonly EquipmentSetV22[]=rawCatalog.sets.map((r:any)=>({id:r['Set ID'],tier:r.Tier as EquipmentTierId,tierName:r['Tier Name'],region:r.Region,levelMin:Number(r['Level Min']),levelMax:Number(r['Level Max']),unlockLevel:Number(r['Set Unlock Level']),className:r.Class,role:r.Role,path:r.Path,name:r['Set Name'],focus:r['Build Focus'],primaryStat:r['Primary Stat'],secondaryStat:r['Secondary Stat'],tertiaryStat:r['Tertiary Stat'],thresholds:[{pieces:2,description:r['2pc Bonus']},{pieces:3,description:r['3pc Bonus']},{pieces:5,description:r['5pc Bonus']}],collectibleBonus:r['Collectible Bonus']}));
export const EQUIPMENT_PIECES_V23:readonly EquipmentPieceV22[]=rawCatalog.pieces.map((r:any)=>({id:r['Piece ID'],setId:r['Set ID'],tier:r.Tier as EquipmentTierId,className:r.Class,role:r.Role,path:r.Path,setName:r['Set Name'],slot:slot(r.Slot),name:r['Item Name'],requiredLevel:Number(r['Req Level']),countsForSetBonus:b(r['Counts for 2/3/5 Set Bonus?']),requiredForSkin:b(r['Required for Skin Unlock?']),weaponOffhandType:r['Weapon/Off-hand Type']||undefined,primaryStat:r['Primary Stat Emphasis'],secondaryStat:r['Secondary Stat Emphasis']}));
export const TIER_PACING_V23:readonly TierPacingV22[]=rawCatalog.tierPacing.map((r:any)=>({tier:r.Tier as EquipmentTierId,levelRange:r.Levels,effectiveHoursPerPiece:r['Avg Effective Hours / Piece'],fullSetHours:r['Target Hours / Full 7-Piece Set'],craftTimer:r['Final Craft Timer / Piece'],realWorldCompletion:r['Typical Real-World Completion'],firstSetAcceleration:r['First-Set Story Acceleration'],oldTierCatchup:r['Old-Tier Catch-up']}));
export const SLOT_PACING_V23:readonly SlotPacingV22[]=rawCatalog.slotPacing.map((r:any)=>({slot:slot(r.Slot),costMultiplier:Number(r['Cost Multiplier'])}));
export const EVENT_SKIN_POLICY_V23=rawCatalog.eventSkinPolicy;
export const SKIN_MILESTONES_V23=rawCatalog.skinMilestones;
export function validateCatalogV23():string[]{const e:string[]=[];const setIds=new Set(EQUIPMENT_SETS_V23.map(v=>v.id));const pieceIds=new Set<string>();for(const p of EQUIPMENT_PIECES_V23){if(pieceIds.has(p.id))e.push(`duplicate_piece:${p.id}`);pieceIds.add(p.id);if(!setIds.has(p.setId))e.push(`unknown_set:${p.id}`);}for(const s of EQUIPMENT_SETS_V23){const ps=EQUIPMENT_PIECES_V23.filter(p=>p.setId===s.id);const slots=new Set(ps.map(p=>p.slot));if(ps.length!==7)e.push(`piece_count:${s.id}:${ps.length}`);for(const req of ['Helmet','Chest','Gloves','Legs','Boots','Weapon','Off-hand'])if(!slots.has(req as EquipmentSlot))e.push(`missing_slot:${s.id}:${req}`);}return e;}
