import {EQUIPMENT_PIECES_V23,EQUIPMENT_SETS_V23,TIER_PACING_V23} from './equipment-catalog-v23';
import {recipeForPieceV23} from './equipment-recipes-v23';
export interface CraftJobV23{id:string;characterId:string;pieceId:string;startedAt:string;completesAt:string;status:'running'|'completed'|'cancelled';idempotencyKey:string;}
export interface CraftStartRepoV23{reserveMaterials(characterId:string,pieceId:string,requirements:readonly {role:string;quantity:number}[],idempotencyKey:string):Promise<boolean>;insertCraftJob(job:CraftJobV23):Promise<void>;findByIdempotency(characterId:string,idempotencyKey:string):Promise<CraftJobV23|undefined>;}
const minutes=(tier:string)=>{const p=TIER_PACING_V23.find(v=>v.tier===tier);if(!p)throw new Error('unknown_tier');const nums=(p.craftTimer.match(/\d+/g)??[]).map(Number);return nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length):5;};
export async function startCraftJobV23(repo:CraftStartRepoV23,input:{id:string;characterId:string;className:string;characterLevel:number;pieceId:string;now:Date;idempotencyKey:string}):Promise<CraftJobV23>{
 const existing=await repo.findByIdempotency(input.characterId,input.idempotencyKey);if(existing)return existing;const piece=EQUIPMENT_PIECES_V23.find(p=>p.id===input.pieceId);if(!piece)throw new Error('unknown_piece');if(piece.className!==input.className)throw new Error('wrong_class');if(input.characterLevel<piece.requiredLevel)throw new Error('level_too_low');
 const set=EQUIPMENT_SETS_V23.find(s=>s.id===piece.setId);if(!set)throw new Error('unknown_set');const recipe=recipeForPieceV23(piece);if(!(await repo.reserveMaterials(input.characterId,piece.id,recipe.requirements,input.idempotencyKey)))throw new Error('materials_unavailable');const done=new Date(input.now.getTime()+minutes(piece.tier)*60000);const job:CraftJobV23={id:input.id,characterId:input.characterId,pieceId:piece.id,startedAt:input.now.toISOString(),completesAt:done.toISOString(),status:'running',idempotencyKey:input.idempotencyKey};await repo.insertCraftJob(job);return job;
}
