"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoopLoadoutSelection = CoopLoadoutSelection;
const react_1 = require("react");
const react_native_1 = require("react-native");
const CharacterVisual_1 = require("../CharacterVisual");
const coop_loadout_presentation_1 = require("../../core/coop-loadout-presentation");
const i18n_1 = require("../../i18n");
const coop_ui_theme_1 = require("../../theme/coop-ui-theme");
const CoopVisualKit_1 = require("./CoopVisualKit");
const statRows = [['maxHp', 'hp'], ['attackPower', 'attack'], ['healingPower', 'healing'], ['defense', 'defense']];
function status(loadout, language) {
    if (loadout.status === 'pending')
        return { label: (0, i18n_1.clt)(language, 'pending'), tone: 'warning' };
    if (loadout.status === 'stale')
        return { label: (0, i18n_1.clt)(language, 'stale'), tone: 'warning' };
    if (loadout.status === 'failed')
        return { label: (0, i18n_1.clt)(language, 'failed'), tone: 'danger' };
    if (loadout.selectable)
        return { label: (0, i18n_1.clt)(language, 'ready'), tone: 'success' };
    return { label: (0, i18n_1.clt)(language, 'ineligible'), tone: 'danger' };
}
function CoopLoadoutSelection({ state, language, dungeonId, dungeonName, tier, mode, loadouts, onBack, onIntent, onRefresh, refreshing = false, notice }) {
    const views = (0, react_1.useMemo)(() => loadouts.map(loadout => (0, coop_loadout_presentation_1.presentCoopLoadout)(loadout, state.character.id)), [loadouts, state.character]);
    const [selectedId, setSelectedId] = (0, react_1.useState)(views.find(loadout => loadout.selectable)?.id ?? views[0]?.id);
    const [showDetails, setShowDetails] = (0, react_1.useState)(false);
    const selected = views.find(loadout => loadout.id === selectedId) ?? views[0];
    const cta = mode === 'live' ? (0, i18n_1.clt)(language, 'liveCta') : (0, i18n_1.clt)(language, 'qmodeCta');
    return <CoopVisualKit_1.ExpeditionScreenShell eyebrow={(0, i18n_1.clt)(language, 'kicker')} title={(0, i18n_1.clt)(language, 'title')} onBack={onBack} backLabel={(0, i18n_1.clt)(language, 'back')} banner={<react_native_1.Text style={s.copy}>{(0, i18n_1.clt)(language, 'intro')}</react_native_1.Text>} stickyAction={<react_native_1.View style={s.sticky}>{notice ? <react_native_1.Text accessibilityRole="alert" style={s.notice}>{notice}</react_native_1.Text> : null}<CoopVisualKit_1.PrimaryAction label={cta} disabled={!selected?.selectable} onPress={() => selected && onIntent((0, coop_loadout_presentation_1.buildCoopLoadoutIntent)({ mode, dungeonId, tier, loadout: selected }))}/></react_native_1.View>}>
    <CoopVisualKit_1.FantasyPanel variant="selected"><react_native_1.View style={s.hero}><CharacterVisual_1.CharacterPortrait state={state} compact style={s.portrait}/><react_native_1.View style={s.heroCopy}><react_native_1.Text style={s.character}>{state.character.name}</react_native_1.Text><react_native_1.Text style={s.copy}>{dungeonName} · {(0, i18n_1.clt)(language, 'level')} {tier}</react_native_1.Text>{selected ? <CoopVisualKit_1.RoleBadge role={selected.role} label={(0, i18n_1.t)(language, `coopUi.${selected.role}`)}/> : null}</react_native_1.View></react_native_1.View></CoopVisualKit_1.FantasyPanel>
    {!views.length ? <CoopVisualKit_1.FantasyPanel variant="danger"><react_native_1.Text style={s.copy}>{(0, i18n_1.clt)(language, 'empty')}</react_native_1.Text><CoopVisualKit_1.PrimaryAction label={(0, i18n_1.clt)(language, 'refresh')} tone="secondary" loading={refreshing} onPress={onRefresh}/></CoopVisualKit_1.FantasyPanel> : null}
    {views.map(loadout => { const stateLabel = status(loadout, language), wrongCharacter = loadout.characterId !== state.character.id; return <react_native_1.Pressable key={loadout.id} accessibilityRole="button" accessibilityState={{ selected: selected?.id === loadout.id, disabled: wrongCharacter }} disabled={wrongCharacter} onPress={() => { setSelectedId(loadout.id); setShowDetails(false); }} style={({ pressed }) => pressed && s.pressed}><CoopVisualKit_1.FantasyPanel variant={selected?.id === loadout.id ? 'selected' : loadout.selectable ? 'default' : 'disabled'}><react_native_1.View style={s.cardHead}><react_native_1.View style={s.grow}><react_native_1.Text style={s.loadout}>{loadout.name}</react_native_1.Text><react_native_1.Text style={s.copy}>{loadout.className} · {loadout.characterName}</react_native_1.Text></react_native_1.View><CoopVisualKit_1.StateChip label={stateLabel.label} tone={stateLabel.tone}/></react_native_1.View></CoopVisualKit_1.FantasyPanel></react_native_1.Pressable>; })}
    {selected ? <>
      <CoopVisualKit_1.FantasyPanel variant={selected.selectable ? 'success' : 'danger'}><react_native_1.View style={s.cardHead}><react_native_1.View style={s.grow}><react_native_1.Text style={s.section}>{selected.name}</react_native_1.Text><react_native_1.Text style={s.copy}>{(0, i18n_1.clt)(language, 'effectiveLevel')} {selected.effectiveLevel ?? '—'}</react_native_1.Text></react_native_1.View><CoopVisualKit_1.StateChip {...status(selected, language)}/></react_native_1.View>{selected.blockingReasons.map(reason => <react_native_1.Text key={reason} style={s.failure}>• {(0, i18n_1.clt)(language, (reason in ({ different_character: 1, stale_revision: 1, verification_pending: 1, verification_failed: 1, not_eligible: 1, missing_server_snapshot: 1, below_role_readiness_floor: 1, missing_tank_capability: 1, missing_support_capability: 1, missing_damage_capability: 1, character_below_min_level: 1, invalid_loadout_revision: 1 }) ? reason : 'not_eligible'))}</react_native_1.Text>)}</CoopVisualKit_1.FantasyPanel>
      {(selected.effectiveStats && selected.beforeStats) || selected.skills.length || selected.equipment.length ? <CoopVisualKit_1.PrimaryAction label={`${showDetails ? '▾' : '›'} ${(0, i18n_1.clt)(language, 'stats')}`} tone="secondary" selected={showDetails} onPress={() => setShowDetails(value => !value)}/> : null}
      {showDetails && selected.effectiveStats && selected.beforeStats ? <CoopVisualKit_1.FantasyPanel><react_native_1.View style={s.statHeader}><react_native_1.Text style={s.statLabel}/><react_native_1.Text style={s.statValue}>{(0, i18n_1.clt)(language, 'before')}</react_native_1.Text><react_native_1.Text style={s.statValue}>{(0, i18n_1.clt)(language, 'effective')}</react_native_1.Text></react_native_1.View><react_native_1.View style={s.statHeader}><react_native_1.Text style={s.statLabel}>{(0, i18n_1.clt)(language, 'level')}</react_native_1.Text><react_native_1.Text style={s.statValue}>{selected.level}</react_native_1.Text><react_native_1.Text style={s.statValue}>{selected.effectiveLevel}</react_native_1.Text></react_native_1.View>{statRows.map(([key, label]) => <react_native_1.View key={key} style={s.statHeader}><react_native_1.Text style={s.statLabel}>{(0, i18n_1.clt)(language, label)}</react_native_1.Text><react_native_1.Text style={s.statValue}>{Math.round(selected.beforeStats[key])}</react_native_1.Text><react_native_1.Text style={s.statValue}>{Math.round(selected.effectiveStats[key])}</react_native_1.Text></react_native_1.View>)}</CoopVisualKit_1.FantasyPanel> : null}
      {showDetails ? <><Summary title={(0, i18n_1.clt)(language, 'skills')} values={selected.skills} empty={(0, i18n_1.clt)(language, 'noSummary')}/><Summary title={(0, i18n_1.clt)(language, 'equipment')} values={selected.equipment} empty={(0, i18n_1.clt)(language, 'noSummary')}/></> : null}
      {!selected.selectable ? <CoopVisualKit_1.PrimaryAction label={(0, i18n_1.clt)(language, 'refresh')} tone="secondary" loading={refreshing} onPress={onRefresh}/> : null}
    </> : null}
  </CoopVisualKit_1.ExpeditionScreenShell>;
}
function Summary({ title, values, empty }) { return <CoopVisualKit_1.FantasyPanel><react_native_1.Text style={s.section}>{title}</react_native_1.Text><react_native_1.Text style={s.copy}>{values.length ? values.join(' · ') : empty}</react_native_1.Text></CoopVisualKit_1.FantasyPanel>; }
const s = react_native_1.StyleSheet.create({ copy: { ...coop_ui_theme_1.coopTypography.body, color: coop_ui_theme_1.coopColors.textSecondary }, hero: { flexDirection: 'row', gap: coop_ui_theme_1.coopSpacing.md, alignItems: 'center' }, portrait: { width: 88, height: 110 }, heroCopy: { flex: 1, minWidth: 0, gap: coop_ui_theme_1.coopSpacing.xs }, character: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.text }, section: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.gold, flex: 1 }, loadout: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.text }, cardHead: { flexDirection: 'row', gap: coop_ui_theme_1.coopSpacing.sm, alignItems: 'center' }, grow: { flex: 1, minWidth: 0 }, failure: { ...coop_ui_theme_1.coopTypography.body, color: coop_ui_theme_1.coopColors.danger }, statHeader: { flexDirection: 'row', gap: coop_ui_theme_1.coopSpacing.sm, paddingVertical: coop_ui_theme_1.coopSpacing.xs, borderBottomWidth: 1, borderColor: coop_ui_theme_1.coopColors.goldDim }, statLabel: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.textSecondary, flex: 1 }, statValue: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.text, textAlign: 'right', width: 76, fontWeight: '800' }, sticky: { gap: coop_ui_theme_1.coopSpacing.xs }, notice: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.gold, textAlign: 'center' }, pressed: { opacity: .72 } });
