"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoopRunOverview = CoopRunOverview;
const react_native_1 = require("react-native");
const coop_presentation_1 = require("../../core/coop-presentation");
const i18n_1 = require("../../i18n");
const coop_ui_theme_1 = require("../../theme/coop-ui-theme");
const CoopVisualKit_1 = require("./CoopVisualKit");
const GameButton_1 = require("../GameButton");
const roomAssets = { battle: 'node_battle', elite: 'node_elite', event: 'node_event', shrine: 'node_shrine', camp: 'node_camp', treasure: 'node_treasure', merchant: 'node_merchant', echo: 'node_echo', risk: 'node_risk', boss: 'node_boss' };
function CoopRunOverview({ language, run, onBack, onChoose, onRefresh, onClaim, busy = false, notice, rewards = [] }) {
    (0, coop_presentation_1.validateCoopRunView)(run);
    const modeLabel = run.mode === 'qmode' ? (0, i18n_1.ct)(language, 'details.qmode') : (0, i18n_1.ct)(language, 'details.live');
    return <CoopVisualKit_1.ExpeditionScreenShell eyebrow={(0, i18n_1.ct)(language, 'browse.resumeTitle')} title={(0, i18n_1.ct)(language, 'browse.resume')} onBack={onBack} backLabel={(0, i18n_1.ct)(language, 'details.backList')} banner={<react_native_1.View style={s.banner}><CoopVisualKit_1.StateChip label={modeLabel} tone="selected"/><react_native_1.Text style={s.phase}>{run.phase.replaceAll('_', ' ')}</react_native_1.Text></react_native_1.View>}>
    <CoopVisualKit_1.FantasyPanel variant="selected"><react_native_1.View style={s.summary}><react_native_1.View style={s.grow}><react_native_1.Text style={s.title}>{(0, i18n_1.ct)(language, 'details.party')}</react_native_1.Text><react_native_1.Text style={s.copy}>{(0, i18n_1.ct)(language, 'details.partyValue')}</react_native_1.Text></react_native_1.View><CoopVisualKit_1.StateChip label={`Lv. ${run.syncedLevel}`} tone="success"/></react_native_1.View></CoopVisualKit_1.FantasyPanel>
    <react_native_1.Text style={s.section}>{(0, i18n_1.ct)(language, 'details.party')}</react_native_1.Text>
    <react_native_1.View style={s.party}>{run.roleSlots.map((slot, index) => <CoopVisualKit_1.FantasyPanel key={`${slot.role}-${index}`} variant={slot.ready === false ? 'danger' : 'default'} style={s.member}><CoopVisualKit_1.RoleBadge role={slot.role} label={(0, i18n_1.t)(language, `coopUi.${slot.role}`)}/><react_native_1.Text numberOfLines={2} style={s.name}>{slot.name}</react_native_1.Text><react_native_1.View style={s.memberMeta}><CoopVisualKit_1.StateChip label={slot.echo ? 'Echo' : modeLabel} tone={slot.echo ? 'selected' : 'neutral'}/>{slot.ready !== undefined ? <CoopVisualKit_1.StateChip label={slot.ready ? (0, i18n_1.t)(language, 'coopUi.ready') : (0, i18n_1.t)(language, 'coopUi.searching')} tone={slot.ready ? 'success' : 'warning'}/> : null}</react_native_1.View></CoopVisualKit_1.FantasyPanel>)}</react_native_1.View>
    <react_native_1.Text style={s.section}>{(0, i18n_1.ct)(language, 'details.rooms')}</react_native_1.Text>
    {!!notice && <react_native_1.Text accessibilityRole="alert" style={s.copy}>{notice}</react_native_1.Text>}
    {run.phase === 'resolving_node' && <CoopVisualKit_1.FantasyPanel><react_native_1.Text style={s.copy}>Your party is resolving this room. Progress is saved online.</react_native_1.Text></CoopVisualKit_1.FantasyPanel>}
    {run.options.length ? run.options.map(option => <CoopVisualKit_1.FantasyPanel key={option.nodeId}><react_native_1.View style={s.option}><CoopVisualKit_1.CoopImageSlot assetId={roomAssets[option.kind]} size="node" accessibilityLabel={option.title}/><react_native_1.View style={s.grow}><react_native_1.Text style={s.title}>{option.title}</react_native_1.Text><react_native_1.Text style={s.copy}>{option.risk} · {option.reward}</react_native_1.Text></react_native_1.View>{option.votes !== undefined ? <CoopVisualKit_1.StateChip label={`${option.votes}`} tone="selected"/> : null}</react_native_1.View>{onChoose && <GameButton_1.GameButton title={run.mode === 'qmode' ? 'Choose this room' : 'Vote for this room'} disabled={busy || run.phase !== 'awaiting_choice'} onPress={() => onChoose(option.nodeId)}/>}</CoopVisualKit_1.FantasyPanel>) : run.phase !== 'resolving_node' ? <CoopVisualKit_1.FantasyPanel><react_native_1.Text style={s.copy}>{(0, i18n_1.ct)(language, 'browse.resumeBody')}</react_native_1.Text></CoopVisualKit_1.FantasyPanel> : null}
    {onRefresh && <GameButton_1.GameButton title="Refresh saved progress" tone="secondary" disabled={busy} onPress={onRefresh}/>}
    {rewards.map(reward => <CoopVisualKit_1.FantasyPanel key={reward.id} variant="success">{reward.claimed_at ? <react_native_1.Text style={s.copy}>{reward.reward_json.marks ?? 0} Expedition Marks collected.</react_native_1.Text> : <GameButton_1.GameButton title="Collect expedition reward" disabled={busy} onPress={() => onClaim?.(reward.id)}/>}</CoopVisualKit_1.FantasyPanel>)}
    {run.rewardText ? <CoopVisualKit_1.FantasyPanel variant="success"><react_native_1.Text style={s.title}>{(0, i18n_1.ct)(language, 'details.reward')}</react_native_1.Text><react_native_1.Text style={s.copy}>{run.rewardText}</react_native_1.Text></CoopVisualKit_1.FantasyPanel> : null}
  </CoopVisualKit_1.ExpeditionScreenShell>;
}
const s = react_native_1.StyleSheet.create({ banner: { flexDirection: 'row', alignItems: 'center', gap: coop_ui_theme_1.coopSpacing.sm }, phase: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.textSecondary, textTransform: 'capitalize', flex: 1 }, summary: { flexDirection: 'row', alignItems: 'center', gap: coop_ui_theme_1.coopSpacing.sm }, grow: { flex: 1, minWidth: 0 }, section: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.gold, marginTop: coop_ui_theme_1.coopSpacing.xs }, title: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.text }, copy: { ...coop_ui_theme_1.coopTypography.body, color: coop_ui_theme_1.coopColors.textSecondary }, party: { flexDirection: 'row', flexWrap: 'wrap', gap: coop_ui_theme_1.coopSpacing.sm }, member: { width: '48%', flexGrow: 1 }, name: { ...coop_ui_theme_1.coopTypography.body, color: coop_ui_theme_1.coopColors.text, fontWeight: '800' }, memberMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: coop_ui_theme_1.coopSpacing.xs }, option: { minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: coop_ui_theme_1.coopSpacing.md } });
