"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CoopQModeTeamGallery = CoopQModeTeamGallery;
const react_1 = require("react");
const react_native_1 = require("react-native");
const coop_qmode_fixtures_1 = require("../../dev/coop-qmode-fixtures");
const coop_qmode_1 = require("../../core/coop-qmode");
const coop_ui_theme_1 = require("../../theme/coop-ui-theme");
const CoopVisualKit_1 = require("./CoopVisualKit");
const fixtures = { ready: coop_qmode_fixtures_1.qModeReadyFixture, resume: coop_qmode_fixtures_1.qModeResumeFixture, shortage: coop_qmode_fixtures_1.qModeShortageFixture, conflict: coop_qmode_fixtures_1.qModeConflictFixture };
function CoopQModeTeamGallery() { const [state, setState] = (0, react_1.useState)('ready'), view = fixtures[state]; (0, coop_qmode_1.validateCoopQModeTeam)(view); return <react_native_1.View style={s.stack}><react_native_1.Text style={s.section}>Phase 05 · Q-Mode team states</react_native_1.Text><react_native_1.Text style={s.warning}>Development gallery only · no recruitment or run is started</react_native_1.Text><react_native_1.View style={s.controls}>{Object.keys(fixtures).map(key => <react_native_1.View key={key} style={s.control}><CoopVisualKit_1.PrimaryAction label={key} tone="secondary" selected={state === key} onPress={() => setState(key)}/></react_native_1.View>)}</react_native_1.View><Team view={view}/></react_native_1.View>; }
function Team({ view }) { const canEnter = (0, coop_qmode_1.qModeStatusCanEnterRun)(view); return <react_native_1.View style={s.stack}><CoopVisualKit_1.FantasyPanel variant={canEnter ? 'success' : view.status === 'resuming' ? 'selected' : 'danger'}><react_native_1.View style={s.heading}><react_native_1.Text style={s.title}>{view.status === 'ready' ? 'Team ready' : view.status === 'resuming' ? 'Restoring run…' : view.status === 'candidate_shortage' ? 'Echo candidate unavailable' : 'Content update required'}</react_native_1.Text><CoopVisualKit_1.StateChip label={view.status} tone={canEnter ? 'success' : view.status === 'resuming' ? 'warning' : 'danger'}/></react_native_1.View><react_native_1.Text style={s.copy}>{view.message ?? 'You choose the route · no party chat · saved builds are controlled automatically.'}</react_native_1.Text></CoopVisualKit_1.FantasyPanel><react_native_1.View style={s.grid}>{view.members.map(member => <CoopVisualKit_1.FantasyPanel key={member.memberId} variant={member.status === 'ready' ? 'default' : 'disabled'} style={s.member}><CoopVisualKit_1.RoleBadge role={member.role} label={member.role}/><react_native_1.Text style={s.name}>{member.displayName}</react_native_1.Text><react_native_1.Text style={s.copy}>Effective level {member.effectiveLevel}</react_native_1.Text><react_native_1.Text style={s.echo}>{member.kind === 'echo' ? 'Saved player build · automated ally' : 'Your verified character'}</react_native_1.Text></CoopVisualKit_1.FantasyPanel>)}</react_native_1.View><CoopVisualKit_1.PrimaryAction label={view.status === 'ready' ? 'Open expedition map' : view.status === 'resuming' ? 'Checking server state…' : 'Return to loadout'} disabled={!canEnter}/></react_native_1.View>; }
const s = react_native_1.StyleSheet.create({ stack: { gap: coop_ui_theme_1.coopSpacing.md }, section: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.gold }, warning: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.gold }, controls: { flexDirection: 'row', flexWrap: 'wrap', gap: coop_ui_theme_1.coopSpacing.xs }, control: { flexGrow: 1, minWidth: 72 }, heading: { flexDirection: 'row', alignItems: 'center', gap: coop_ui_theme_1.coopSpacing.sm }, title: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.text, flex: 1 }, copy: { ...coop_ui_theme_1.coopTypography.body, color: coop_ui_theme_1.coopColors.textSecondary }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: coop_ui_theme_1.coopSpacing.sm }, member: { width: '48%', flexGrow: 1 }, name: { ...coop_ui_theme_1.coopTypography.section, color: coop_ui_theme_1.coopColors.text }, echo: { ...coop_ui_theme_1.coopTypography.meta, color: coop_ui_theme_1.coopColors.cyan } });
