import {COMPANION_RARITY_MAX_LEVEL,COMPANION_SERVER_DEFINITIONS} from '../content';
import {projectCompanionCodex} from '../projection';
import {availableCompanionCodexMilestones,claimCompanionCodexMilestone,companionCodexEntryV2,companionCodexState,companionCodexSummary,isCompanionMastered,resolveCompanionVisualPresentation,sanitizeCompanionShowcase} from '../codex';
import type {CompanionCodexProfileState,CompanionEconomyState,OwnedCompanionSnapshot} from '../domain';
const ok=(v:unknown,m:string)=>{if(!v)throw new Error(m)};const eq=(a:unknown,b:unknown,m:string)=>{if(a!==b)throw new Error(`${m}: expected ${String(b)}, got ${String(a)}`)};const throws=(f:()=>unknown,m:string)=>{let did=false;try{f()}catch{did=true}if(!did)throw new Error(m)};
const max=(id:string,bond=10,mastered=false,year?:number):OwnedCompanionSnapshot=>{const d=COMPANION_SERVER_DEFINITIONS.find(x=>x.id===id)!;return {companionId:id,level:COMPANION_RARITY_MAX_LEVEL[d.rarity],xp:0,ascensionTier:d.rarity==='standard'||d.rarity==='rare'?2:3,bondLevel:bond,bondXp:0,bondTraitUnlocked:bond>=10,mastered,selectedTechniqueId:undefined,originalEventReleaseYear:year};};
const owned:Record<string,OwnedCompanionSnapshot>={};for(const id of ['UNIT_001','UNIT_002','UNIT_003','UNIT_004','UNIT_005'])owned[id]=max(id);
let profile:CompanionCodexProfileState={showcaseCompanionIds:[],showcaseSlotsUnlocked:1,discoveredCompanionIds:['UNIT_012']};
const economy:CompanionEconomyState={gold:0,companionEssence:10,bondstones:0,materials:{}};
// Codex projection tracks every static Combat Companion definition, not only owned entries.
const projection=projectCompanionCodex(owned,profile);eq(projection.entries.length,COMPANION_SERVER_DEFINITIONS.length,'Codex projection omitted locked/unknown definitions');
// 39-40 owned and locked/discovered state.
eq(companionCodexState('UNIT_001',owned.UNIT_001,profile),'mastered','Owned fully progressed Standard should be Mastered');eq(companionCodexState('UNIT_012',undefined,profile),'discovered','Explicitly discovered Prestige should use discovered Codex state');eq(companionCodexState('UNIT_004',undefined,{showcaseCompanionIds:[]}), 'locked','Known non-Prestige companion should remain locked until owned');eq(companionCodexState('UNIT_016',undefined,{showcaseCompanionIds:[]}), 'unknown','Undiscovered Prestige should be hidden');
// 41-45 completion counts for Bond, max level, mastery, origin, rarity.
let summary=companionCodexSummary(owned);eq(summary.bond10Count,5,'Bond 10 count wrong');eq(summary.maxLevelCount,5,'Max-level count wrong');ok(summary.masteredCount>=3,'Mastered count wrong');eq(summary.byOrigin.REG_001,5,'Origin collection wrong');eq(summary.byRarity.standard,3,'Standard rarity collection wrong');eq(summary.byRarity.rare,2,'Rare rarity collection wrong');
// 46 milestone once; Collector I grants Essence/reward once.
const collector=availableCompanionCodexMilestones(owned,profile).find(x=>x.definition.id==='CODEX_COLLECTOR_I')!;ok(collector.complete&&!collector.claimed,'Collector milestone unavailable');const grant=claimCompanionCodexMilestone({milestoneId:'CODEX_COLLECTOR_I',owned,profile,economy});ok(grant.economy.companionEssence>economy.companionEssence,'Codex Essence reward missing');throws(()=>claimCompanionCodexMilestone({milestoneId:'CODEX_COLLECTOR_I',owned,profile:grant.profile,economy:grant.economy}),'Codex reward granted twice');profile=grant.profile;
// 47-48 showcase only owned, and invalid/removed is sanitized. One basic slot is always available.
let showcase=sanitizeCompanionShowcase({...profile,favoriteCompanionId:'UNIT_001',showcaseCompanionIds:['UNIT_001','UNIT_012']},owned);eq(showcase.showcaseCompanionIds.length,1,'Locked companion remained showcased');eq(showcase.favoriteCompanionId,'UNIT_001','Owned favorite removed');const withoutOne={...owned};delete withoutOne.UNIT_001;showcase=sanitizeCompanionShowcase(showcase,withoutOne);ok(!showcase.favoriteCompanionId&&!showcase.showcaseCompanionIds.includes('UNIT_001'),'Removed companion remained showcased');
// 49 event-year metadata persists in Codex projection.
const eventOwned=max('UNIT_004',10,false,2026);eq(companionCodexEntryV2(eventOwned,'UNIT_004',profile).originalEventReleaseYear,2026,'Event year metadata lost');
const annualOwned:Record<string,OwnedCompanionSnapshot>={};for(const id of ['EVT_UNIT_001','EVT_UNIT_002','EVT_UNIT_003','EVT_UNIT_004','EVT_UNIT_005'])annualOwned[id]=max(id,10,id==='EVT_UNIT_002',2026);const annualSummary=companionCodexSummary(annualOwned);eq(annualSummary.eventCompanionCount,5,'Event companion summary count wrong');ok(availableCompanionCodexMilestones(annualOwned,{showcaseCompanionIds:[],showcaseSlotsUnlocked:1}).find(x=>x.definition.id==='CODEX_EVENT_HISTORIAN')?.complete,'Event Historian milestone unavailable');
const challengeOwned:Record<string,OwnedCompanionSnapshot>={};for(const id of ['UNIT_012','UNIT_016','UNIT_020'])challengeOwned[id]=max(id,10,true);const challengeSummary=companionCodexSummary(challengeOwned);eq(challengeSummary.trialBossCompanionCount,3,'Special challenge companion count wrong');ok(availableCompanionCodexMilestones(challengeOwned,{showcaseCompanionIds:[],showcaseSlotsUnlocked:1}).find(x=>x.definition.id==='CODEX_TRIALBOUND')?.complete,'Trialbound milestone unavailable');
// 50-54 rarity visuals, optional asset safety, mastery marker correctness, non-color accessibility, showcase projection data.
for(const id of ['UNIT_001','UNIT_004','UNIT_007','UNIT_012']){const visual=resolveCompanionVisualPresentation(id,undefined);ok(!!visual.rarityFrame&&!!visual.rarityIcon&&!!visual.rarityLabel,`${id} rarity visual metadata incomplete`);ok(visual.accessibilityLabel.toLowerCase().includes('companion'),`${id} accessibility metadata missing`);}
const optional={...COMPANION_SERVER_DEFINITIONS.find(x=>x.id==='UNIT_007')!.visual};delete (optional as any).summonEffect;ok(!!resolveCompanionVisualPresentation('UNIT_007',undefined),'Missing optional visual asset broke resolution');
const prestige=max('UNIT_012',10,false);ok(!isCompanionMastered(prestige),'Prestige without final Mastery marked Mastered');ok(!resolveCompanionVisualPresentation('UNIT_012',prestige).masteryMarker,'Mastery marker appeared too early');const masteredPrestige={...prestige,mastered:true};ok(isCompanionMastered(masteredPrestige),'Valid Prestige Mastery not recognized');ok(!!resolveCompanionVisualPresentation('UNIT_012',masteredPrestige).masteryMarker,'Mastery marker missing');const entry=companionCodexEntryV2(masteredPrestige,'UNIT_012',{...profile,discoveredCompanionIds:['UNIT_012']});eq(entry.rarity,'prestige','Showcase/Codex rarity missing');ok(entry.mastered,'Showcase/Codex Mastery missing');
console.log('companion-phase3-codex-prestige: PASS');
