import {activeCompanionMissions,claimCompanionAssignment,COMPANION_EXPEDITION_WEEKLY_COUNT,companionMissionRequirementSatisfied,predictedCompanionMissionGrade,rolloverCompanionAssignmentStatuses,startCompanionAssignment,validateCompanionMissionTeam} from '../assignments';
import {COMPANION_EXPEDITION_BOND_RATE,COMPANION_EXPEDITION_PEN_DURATION_REDUCTION,COMPANION_MISSIONS,companionMission} from '../content';
import {companionAvailabilityStatus} from '../status';
import type {CompanionAssignment,CompanionEconomyState,OwnedCompanionSnapshot} from '../domain';
const ok=(v:unknown,m:string)=>{if(!v)throw new Error(m)};const eq=(a:unknown,b:unknown,m:string)=>{if(a!==b)throw new Error(`${m}: expected ${String(b)}, got ${String(a)}`)};const throws=(f:()=>unknown,m:string)=>{let did=false;try{f()}catch{did=true}if(!did)throw new Error(m)};
const p=(id:string,level=30,bondLevel=8,ascensionTier:0|1|2|3=3):OwnedCompanionSnapshot=>({companionId:id,level,xp:0,ascensionTier,bondLevel,bondXp:0,bondTraitUnlocked:bondLevel>=10});
const owned:Record<string,OwnedCompanionSnapshot>={UNIT_001:p('UNIT_001',20,8,2),UNIT_002:p('UNIT_002',20,8,2),UNIT_003:p('UNIT_003',20,8,2),UNIT_004:p('UNIT_004',25,8,2),UNIT_006:p('UNIT_006',25,8,2),UNIT_007:p('UNIT_007',30),UNIT_013:p('UNIT_013',25),UNIT_014:p('UNIT_014',30),UNIT_015:p('UNIT_015',30),UNIT_017:p('UNIT_017',25),UNIT_018:p('UNIT_018',30),UNIT_021:p('UNIT_021',25),UNIT_022:p('UNIT_022',30),UNIT_024:p('UNIT_024',35)};
const economy:CompanionEconomyState={gold:100000,companionEssence:500,bondstones:5,materials:{SUPPLIES:99,IRONWOOD_FANG:99}};const now=Date.UTC(2026,8,11,12);
// Weekly server-authoritative mission rotation.
const rotation=activeCompanionMissions(now),rotationAgain=activeCompanionMissions(now+60_000);
eq(rotation.definitions.length,COMPANION_EXPEDITION_WEEKLY_COUNT,'Weekly Sanctuary rotation size');
eq(rotation.definitions.map(x=>x.id).join(','),rotationAgain.definitions.map(x=>x.id).join(','),'Mission rotation must remain deterministic inside the same UTC week');
ok(rotation.definitions.some(x=>x.id==='MISSION_SCOUT_2H'),'Starter patrol must always remain active');
for(const origin of ['REG_001','REG_SUNSCAR','REG_FROSTMARCH','REG_ASHLANDS'])ok(rotation.definitions.some(x=>x.originId===origin),`Weekly mission rotation missing ${origin}`);
const inactive=COMPANION_MISSIONS.find(x=>!rotation.definitions.some(active=>active.id===x.id));
ok(!!inactive,'Rotation fixture needs at least one inactive authored mission');
if(inactive){const ids=inactive.minCompanions===1?['UNIT_001']:inactive.originId==='REG_SUNSCAR'?['UNIT_013','UNIT_014','UNIT_015'].slice(0,inactive.minCompanions):inactive.originId==='REG_FROSTMARCH'?['UNIT_017','UNIT_018','UNIT_002'].slice(0,inactive.minCompanions):inactive.originId==='REG_ASHLANDS'?['UNIT_021','UNIT_022','UNIT_024'].slice(0,inactive.minCompanions):['UNIT_001','UNIT_002','UNIT_003'].slice(0,inactive.minCompanions);ok(!validateCompanionMissionTeam({missionId:inactive.id,companionIds:ids,owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:3,serverNowMs:now}).ok,'Rotated-out mission should be rejected by authoritative validation');}

// Mission-pool variety: preserve the existing ten and add seven specialist assignments.
eq(COMPANION_MISSIONS.length,17,'Sanctuary mission pool should contain seventeen authored assignments');
for(const id of ['MISSION_GREENFIELDS_FORAGE_2H','MISSION_IRONWOOD_TRACK_4H','MISSION_SUNSCAR_RELIC_6H','MISSION_FROST_RESONANCE_6H','MISSION_ASHLANDS_SALVAGE_8H','MISSION_OLD_FRIENDS_8H','MISSION_PRESTIGE_VIGIL_12H'])ok(!!companionMission(id),`Missing specialist Sanctuary mission ${id}`);
for(const id of ['MISSION_APPRENTICE_3H','MISSION_SILVERBROOK_4H','MISSION_FROST_SCOUT_4H','MISSION_SUNSCAR_RUINS_8H','MISSION_ASH_RESCUE_8H'])ok(!!companionMission(id),`Missing expanded Sanctuary mission ${id}`);
ok(validateCompanionMissionTeam({missionId:'MISSION_APPRENTICE_3H',companionIds:['UNIT_001','UNIT_003'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Lower-rarity Apprentice Survey should accept Standard companions');
ok(!validateCompanionMissionTeam({missionId:'MISSION_APPRENTICE_3H',companionIds:['UNIT_007','UNIT_004'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Apprentice Survey should reject Elite companions');
ok(validateCompanionMissionTeam({missionId:'MISSION_FROST_SCOUT_4H',companionIds:['UNIT_017','UNIT_018'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Frostmarch short expedition should be reachable');
ok(validateCompanionMissionTeam({missionId:'MISSION_SUNSCAR_RUINS_8H',companionIds:['UNIT_013','UNIT_014','UNIT_015'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:2}).ok,'Sunscar long expedition should be reachable');
ok(validateCompanionMissionTeam({missionId:'MISSION_ASH_RESCUE_8H',companionIds:['UNIT_021','UNIT_022','UNIT_024'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:2}).ok,'Ashlands rescue expedition should be reachable');

// 1: 1-3 companions may be sent when the mission permits.
ok(validateCompanionMissionTeam({missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_001'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'One-companion mission rejected');
ok(validateCompanionMissionTeam({missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_015','UNIT_014'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Two-companion mission rejected');
ok(validateCompanionMissionTeam({missionId:'MISSION_ASTERFALL_SHRINE_8H',companionIds:['UNIT_006','UNIT_007','UNIT_004'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:2}).ok,'Three-companion mission rejected');
// 2 role requirements.
ok(!validateCompanionMissionTeam({missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_013','UNIT_014'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Role requirement ignored');
// 3 level requirements.
const low={...owned,UNIT_015:p('UNIT_015',14)};ok(!validateCompanionMissionTeam({missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_015','UNIT_014'],owned:low,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Level requirement ignored');
// 4 rarity requirements: Forgotten Shrine needs at least one Rare+.
const standards={...owned,UNIT_001:p('UNIT_001',20,8,2),UNIT_002:p('UNIT_002',20,8,2),UNIT_003:p('UNIT_003',20,8,2)};ok(!validateCompanionMissionTeam({missionId:'MISSION_ASTERFALL_SHRINE_8H',companionIds:['UNIT_001','UNIT_002','UNIT_003'],owned:standards,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:2}).ok,'Rarity requirement ignored');
// 5 origin requirement.
ok(!validateCompanionMissionTeam({missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_006','UNIT_003'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1}).ok,'Sunscar origin requirement ignored');
// 6 Team Power requirement primitive exists and is authoritative.
ok(companionMissionRequirementSatisfied({type:'min_team_power',value:100},['UNIT_006','UNIT_007','UNIT_004'],owned),'Valid Team Power requirement failed');ok(!companionMissionRequirementSatisfied({type:'min_team_power',value:999999},['UNIT_006','UNIT_007','UNIT_004'],owned),'Impossible Team Power requirement passed');
// Additional requirement primitives: ascension, tag, exact ID, maximum rarity.
ok(companionMissionRequirementSatisfied({type:'min_ascension',tier:2,count:2},['UNIT_006','UNIT_007','UNIT_004'],owned),'Ascension requirement failed');ok(companionMissionRequirementSatisfied({type:'tag_count',tag:'damage',count:2},['UNIT_006','UNIT_007','UNIT_004'],owned),'Tag requirement failed');ok(companionMissionRequirementSatisfied({type:'companion_id',companionId:'UNIT_006'},['UNIT_006','UNIT_007','UNIT_004'],owned),'Specific companion requirement failed');ok(companionMissionRequirementSatisfied({type:'max_rarity',rarity:'elite'},['UNIT_006','UNIT_007','UNIT_004'],owned),'Maximum rarity requirement failed');
// 7 equipped cannot be sent.
throws(()=>startCompanionAssignment({accountId:'A1',missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_015','UNIT_014'],owned,assignments:[],equippedCompanionIds:new Set(['UNIT_015']),expeditionPensLevel:1,economy,serverNowMs:now,requestId:'EQUIPPED'}),'Equipped companion assigned');
// 8 busy cannot be sent twice.
const first=startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_001'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:2,economy,serverNowMs:now,requestId:'FIRST'});throws(()=>startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_001'],owned,assignments:[first.assignment],equippedCompanionIds:new Set(),expeditionPensLevel:2,economy:first.economy,serverNowMs:now,requestId:'SECOND'}),'Busy companion assigned twice');
// Trial-locked and explicit unavailable status also reject.
throws(()=>startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_002'],owned,assignments:[],equippedCompanionIds:new Set(),lockedTrialCompanionIds:new Set(['UNIT_002']),expeditionPensLevel:1,economy,serverNowMs:now,requestId:'TRIAL'}),'Active Trial companion assigned');throws(()=>startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_002'],owned,assignments:[],equippedCompanionIds:new Set(),unavailableCompanionIds:new Set(['UNIT_002']),expeditionPensLevel:1,economy,serverNowMs:now,requestId:'UNAVAILABLE'}),'Unavailable companion assigned');
// 9 claim before completion fails; 10 after works; 11 cannot claim twice.
throws(()=>claimCompanionAssignment({assignment:first.assignment,owned,serverNowMs:Date.parse(first.assignment.endsAt)-1,bondstonesClaimedThisWeek:0}),'Early claim succeeded');const claimed=claimCompanionAssignment({assignment:first.assignment,owned,serverNowMs:Date.parse(first.assignment.endsAt)+1,bondstonesClaimedThisWeek:0});eq(claimed.assignment.status,'claimed','Completed assignment did not claim');throws(()=>claimCompanionAssignment({assignment:claimed.assignment,owned,serverNowMs:Date.parse(first.assignment.endsAt)+2,bondstonesClaimedThisWeek:0}),'Claimed twice');
// Explicit lazy completion state is server-time derived.
const completed=rolloverCompanionAssignmentStatuses([first.assignment],Date.parse(first.assignment.endsAt)+1)[0];eq(completed.status,'completed','Lazy completion state did not resolve');eq(companionAvailabilityStatus('UNIT_001',{owned,assignments:[completed],equippedCompanionIds:new Set(),serverNowMs:Date.parse(first.assignment.endsAt)+1}),'available','Finished unclaimed Expedition should release the companion');
// 12 costs deduct once; 13 failed start deducts nothing.
const again=startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_003'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1,economy,serverNowMs:now,requestId:'COST'});eq(again.economy.gold,economy.gold-companionMission('MISSION_SCOUT_2H')!.costs.gold,'Mission cost wrong');eq(economy.gold,100000,'Caller economy mutated');const snapshot=JSON.stringify(economy);throws(()=>startCompanionAssignment({accountId:'A1',missionId:'MISSION_SUNSCAR_4H',companionIds:['UNIT_013'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:1,economy,serverNowMs:now,requestId:'FAIL'}),'Invalid start succeeded');eq(JSON.stringify(economy),snapshot,'Failed start deducted resources');
// 14 grade calculation; 15 bonus requirement affects S eligibility/reward path.
const shrineIds=['UNIT_006','UNIT_007','UNIT_004'];const grade=predictedCompanionMissionGrade('MISSION_ASTERFALL_SHRINE_8H',shrineIds,owned);ok(['C','B','A','S'].includes(grade),'Invalid grade');const mixedOwned={...owned,UNIT_013:p('UNIT_013',25)};const mixedGrade=predictedCompanionMissionGrade('MISSION_ASTERFALL_SHRINE_8H',['UNIT_006','UNIT_007','UNIT_013'],mixedOwned);if(grade==='S')ok(mixedGrade!=='S','S grade ignored bonus requirement');
// 16 Bond XP uses reduced configured rate.
const scout=companionMission('MISSION_SCOUT_2H')!,mult=claimed.assignment.performanceGrade==='S'?1.5:claimed.assignment.performanceGrade==='A'?1.25:claimed.assignment.performanceGrade==='B'?1.1:1;eq(claimed.reward.bondXp,Math.max(1,Math.round(scout.baseRewards.bondXp*COMPANION_EXPEDITION_BOND_RATE*mult)),'Expedition Bond rate wrong');
// 17 server time determines completion, 18 there is no client/device time input to bypass it.
const fakeClientTomorrow=Date.parse(first.assignment.endsAt)+86400000;ok(fakeClientTomorrow>Date.parse(first.assignment.endsAt),'Test fixture invalid');throws(()=>claimCompanionAssignment({assignment:first.assignment,owned,serverNowMs:now,bondstonesClaimedThisWeek:0}),'Client-clock-like early claim bypassed serverNow');
// Pens influence capacity/timer modestly, never extreme.
const pen3=startCompanionAssignment({accountId:'A1',missionId:'MISSION_SCOUT_2H',companionIds:['UNIT_003'],owned,assignments:[],equippedCompanionIds:new Set(),expeditionPensLevel:3,economy,serverNowMs:now,requestId:'PEN3'});eq(pen3.durationMs,Math.round(scout.durationMs*(1-COMPANION_EXPEDITION_PEN_DURATION_REDUCTION[3])),'Pen duration reduction wrong');ok(pen3.durationMs>scout.durationMs*.9,'Pen reduction became extreme');
// Specialist mission bonuses reward deliberate roster choices without creating a new currency.
const oldFriends=companionMission('MISSION_OLD_FRIENDS_8H')!;ok(oldFriends.specialtyBonus?.bondXpMultiplier===1.35,'Old Friends Bond specialty missing');
const oldAssignment:CompanionAssignment={assignmentId:'CA_OLD_FRIENDS_TEST',missionId:oldFriends.id,companionIds:['UNIT_001','UNIT_002','UNIT_003'],startedAt:new Date(now-oldFriends.durationMs).toISOString(),endsAt:new Date(now-1).toISOString(),missionVersion:oldFriends.missionVersion,seed:'OLD_FRIENDS',status:'completed'};
const oldClaim=claimCompanionAssignment({assignment:oldAssignment,owned,serverNowMs:now,bondstonesClaimedThisWeek:0}),oldGrade=oldClaim.assignment.performanceGrade!,oldMult=oldGrade==='S'?1.5:oldGrade==='A'?1.25:oldGrade==='B'?1.1:1;
eq(oldClaim.reward.bondXp,Math.max(1,Math.round(oldFriends.baseRewards.bondXp*COMPANION_EXPEDITION_BOND_RATE*oldMult*1.35)),'Old Friends specialty Bond XP not applied');
const relic=companionMission('MISSION_SUNSCAR_RELIC_6H')!;ok(relic.specialtyBonus?.materialMultiplier===1.25,'Sunscar Relic material specialty missing');
const prestige=companionMission('MISSION_PRESTIGE_VIGIL_12H')!;ok(prestige.specialtyBonus?.companionXpMultiplier===1.20&&prestige.specialtyBonus?.essenceMultiplier===1.10,'Prestige Vigil specialty missing');

// Unified status vocabulary derives state from authority, never client booleans.
eq(companionAvailabilityStatus('UNIT_001',{owned,assignments:[first.assignment],equippedCompanionIds:new Set(),serverNowMs:now}),'expedition','Expedition status not derived');eq(companionAvailabilityStatus('UNIT_002',{owned,assignments:[],equippedCompanionIds:new Set(['UNIT_002']),serverNowMs:now}),'equipped','Equipped status not derived');eq(companionAvailabilityStatus('UNIT_999',{owned,assignments:[],equippedCompanionIds:new Set(),serverNowMs:now}),'unavailable','Invalid companion status wrong');
console.log('companion-phase3-expeditions: PASS');
