import {buildOwnedCompanionCombatant} from '../combat-adapter';
import {COMPANION_DUPLICATE_ESSENCE,COMPANION_MAX_XP_WEEKLY_ESSENCE_CAP,companionServerDefinition} from '../content';
import {awardCompanionBondXpServer,awardCompanionXpServer,grantCombatCompanionOrConvertDuplicate,selectCompanionTechnique} from '../progression-v2';
import {runCompanionCommand,type CompanionIdempotentTransactionRepository} from '../idempotency';
import type {CompanionEconomyState,OwnedCompanionSnapshot} from '../domain';
const ok=(v:unknown,m:string)=>{if(!v)throw new Error(m)};const eq=(a:unknown,b:unknown,m:string)=>{if(a!==b)throw new Error(`${m}: expected ${String(b)}, got ${String(a)}`)};const throws=(f:()=>unknown,m:string)=>{let did=false;try{f()}catch{did=true}if(!did)throw new Error(m)};
const p=(id:string,level=20,ascensionTier:0|1|2|3=1,bondLevel=6):OwnedCompanionSnapshot=>({companionId:id,level,xp:0,ascensionTier,bondLevel,bondXp:0,bondTraitUnlocked:bondLevel>=10});
const economy:CompanionEconomyState={gold:10000,companionEssence:1000,bondstones:0,materials:{}};
// 33 locked before requirement.
let prog=p('UNIT_004',20,1,6);throws(()=>selectCompanionTechnique(prog,'UNIT_004_EXECUTIONER',economy),'Locked Technique selected');
// 34 first valid choice is free, 35 only one selected.
prog=p('UNIT_004',20,2,7);const first=selectCompanionTechnique(prog,'UNIT_004_EXECUTIONER',economy);eq(first.cost.gold,0,'First Technique was not free');eq(first.cost.companionEssence,0,'First Technique Essence cost');eq(first.progress.selectedTechniqueId,'UNIT_004_EXECUTIONER','First Technique not selected');
// 36-39 switch replaces old, costs resources, failed switch atomic, combat snapshot reflects effect.
const beforeSwitch=buildOwnedCompanionCombatant(first.progress,{mode:'companion_trial'});const switched=selectCompanionTechnique(first.progress,'UNIT_004_RELENTLESS',first.economy);eq(switched.progress.selectedTechniqueId,'UNIT_004_RELENTLESS','Technique switch did not replace old selection');eq(switched.economy.gold,first.economy.gold,'Technique switch should not cost Gold');ok(switched.economy.companionEssence<first.economy.companionEssence,'Technique switch did not deduct Companion Essence');const afterSwitch=buildOwnedCompanionCombatant(switched.progress,{mode:'companion_trial'});ok(afterSwitch.abilities[0].cooldownMs<beforeSwitch.abilities[0].cooldownMs,'Technique cooldown effect missing from combat snapshot');ok(afterSwitch.abilities[0].tags?.some(x=>x.startsWith('technique:cooldown')),'Technique effect metadata missing');const poor={...first.economy,gold:0,companionEssence:0},poorJson=JSON.stringify(poor);throws(()=>selectCompanionTechnique(first.progress,'UNIT_004_RELENTLESS',poor),'Technique switched without resources');eq(JSON.stringify(poor),poorJson,'Failed Technique switch mutated resources');
// 40-44 duplicate conversion by rarity, always Companion Essence and never Pet Essence.
const ids:[string,'standard'|'rare'|'elite'|'prestige'][]=[['UNIT_001','standard'],['UNIT_004','rare'],['UNIT_007','elite'],['UNIT_012','prestige']];for(const [id,rarity] of ids){const owned={[id]:p(id)};const r=grantCombatCompanionOrConvertDuplicate({companionId:id,owned,companionEssence:10});ok(r.duplicate,`${rarity} duplicate not detected`);eq(r.convertedEssence,COMPANION_DUPLICATE_ESSENCE[rarity],`${rarity} duplicate conversion wrong`);ok(!('petEssence' in (r as any)),'Duplicate used Pet Essence');}
// 45 max-level XP overflow converts at 10%.
const max=p('UNIT_001',20,1,10),now=Date.UTC(2026,8,11);const overflow=awardCompanionXpServer({progress:max,amount:1000,companionEssence:0,serverNowMs:now});eq(overflow.convertedEssence,100,'Max XP overflow rate wrong');
// 46 weekly cap.
const capped=awardCompanionXpServer({progress:max,amount:100000,companionEssence:0,serverNowMs:now});eq(capped.convertedEssence,COMPANION_MAX_XP_WEEKLY_ESSENCE_CAP,'Overflow cap wrong');const cappedAgain=awardCompanionXpServer({progress:max,amount:1000,companionEssence:capped.companionEssence,overflow:capped.overflow,serverNowMs:now});eq(cappedAgain.convertedEssence,0,'Overflow exceeded weekly cap');
// Max Bond caps; no economic conversion created.
const maxBond=awardCompanionBondXpServer(max,999999);eq(maxBond.bondLevel,10,'Max Bond exceeded');ok(!('companionEssence' in (maxBond as any)),'Bond overflow created currency');
// 47 application idempotency: same request returns cached result without a second mutation.
class MemoryRepo implements CompanionIdempotentTransactionRepository<{essence:number}>{state={essence:0};receipts=new Map<string,{fp:string,result:any}>();async transact<T>(i:{accountId:string;action:string;requestId:string;fingerprint:string},work:(s:{essence:number})=>Promise<{state:{essence:number};result:T}>|{state:{essence:number};result:T}){const key=`${i.accountId}|${i.action}|${i.requestId}`,old=this.receipts.get(key);if(old){if(old.fp!==i.fingerprint)throw new Error('request_id_conflict');return old.result as T;}const done=await work(this.state);this.state=done.state;this.receipts.set(key,{fp:i.fingerprint,result:done.result});return done.result;}}
async function idem(){const repo=new MemoryRepo();const run=()=>runCompanionCommand(repo,'A1','overflow','REQ1',{xp:100},s=>({state:{essence:s.essence+10},result:s.essence+10}));eq(await run(),10,'First idempotent mutation result');eq(await run(),10,'Replay did not return stable result');eq(repo.state.essence,10,'Replay duplicated economic effect');let conflict=false;try{await runCompanionCommand(repo,'A1','overflow','REQ1',{xp:101},s=>({state:s,result:0}))}catch(e){conflict=(e as Error).message==='request_id_conflict'}ok(conflict,'Conflicting request ID reuse accepted');console.log('companion-phase2-techniques-economy: PASS');}
void idem();
