"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.CombatCompanionPanel = CombatCompanionPanel;
const react_1 = __importStar(require("react"));
const react_native_1 = require("react-native");
const combat_companions_1 = require("../content/combat-companions");
const combat_companions_2 = require("../core/combat-companions");
const companion_runtime_1 = require("../core/companion-runtime");
const content_1 = require("../../../../backend/src/server/companions/content");
const companion_presentation_1 = require("../core/companion-presentation");
const team_1 = require("../../../../backend/src/server/companions/team");
const progression_v2_1 = require("../../../../backend/src/server/companions/progression-v2");
const assignments_1 = require("../../../../backend/src/server/companions/assignments");
const special_challenges_1 = require("../../../../backend/src/server/companions/special-challenges");
const Panel_1 = require("./Panel");
const MonsterPortraitFrame_1 = require("./MonsterPortraitFrame");
const monsters_1 = require("../content/monsters");
const GameButton_1 = require("./GameButton");
const theme_1 = require("../theme/theme");
const sections = ['Collection', 'Sanctuary', 'Trials', 'Expeditions', 'Codex'];
const roleGlyph = { damage: '⚔', tank: '◆', support: '✦' };
const portraitIds = ['IRONWOOD_WOLF', 'OATHBOUND_SQUIRE', 'FIELD_WISP', 'VENOM_WEAVER', 'FOREST_TROLL', 'ECHO_BAT', 'MIRE_HERON', 'THORNLING', 'CAVE_SKITTER', 'LANTERN_WRETCH'];
const named = (id) => combat_companions_1.COMBAT_COMPANIONS.find(c => c.id === id)?.name ?? (0, companion_presentation_1.companionMaterialName)(id);
const amount = (value) => value.toLocaleString('en');
function CombatCompanionPanel({ state, now, onCommand }) {
    const [section, setSection] = (0, react_1.useState)('Collection'), [selection, setSelection] = (0, react_1.useState)('UNIT_001'), [team, setTeam] = (0, react_1.useState)([]), [mission, setMission] = (0, react_1.useState)(content_1.COMPANION_MISSIONS[0].id), [busy, setBusy] = (0, react_1.useState)(false), [message, setMessage] = (0, react_1.useState)('');
    const lock = (0, react_1.useRef)(false), view = (0, companion_runtime_1.companionView)(state, now), model = (0, combat_companions_2.combatCompanionUiModel)(state, selection), e = (0, companion_runtime_1.companionEconomy)(state), progress = model?.progress;
    const equipped = state.character?.equippedCombatCompanionId, contribution = (0, combat_companions_2.companionCombatContribution)(state), run = view.trial.progress.season.activeRun;
    const recovery = (0, companion_presentation_1.companionRecoverySeconds)(state, now), season = (0, content_1.companionTrialSeasonDefinition)(view.trial.progress.season.seasonKey);
    const safeTeam = team.filter(id => !!view.owned[id]);
    const act = async (type, args) => { if (lock.current)
        return; lock.current = true; setBusy(true); setMessage(''); try {
        await onCommand({ type, args });
        setMessage('Saved.');
    }
    catch (error) {
        setMessage(error instanceof Error ? error.message : 'Unable to complete action.');
    }
    finally {
        lock.current = false;
        setBusy(false);
    } };
    const btn = (title, type, args, disabled = false) => <GameButton_1.GameButton title={title} disabled={busy || disabled} onPress={() => void act(type, args)}/>;
    const idle = (id) => { try {
        (0, companion_runtime_1.assertCompanionIdle)(state, id);
        return true;
    }
    catch {
        return false;
    } };
    const ownedIds = Object.keys(view.owned), teamRoles = new Set(safeTeam.map(id => combat_companions_1.COMBAT_COMPANIONS.find(c => c.id === id)?.role)), trialTeamValid = safeTeam.length === 3 && teamRoles.size === 3 && safeTeam.every(idle);
    const teamSelector = <react_native_1.View style={s.group}><react_native_1.Text style={s.body}>Choose up to three companions. Trials require one Tank, one Damage and one Support.</react_native_1.Text>{ownedIds.length ? ownedIds.map(id => { const def = combat_companions_1.COMBAT_COMPANIONS.find(c => c.id === id); const selected = safeTeam.includes(id), available = idle(id); return <react_native_1.Pressable key={id} accessibilityRole="checkbox" accessibilityState={{ checked: selected, disabled: busy || !available }} disabled={busy || !available} style={[s.choice, selected && s.selected]} onPress={() => setTeam(selected ? safeTeam.filter(x => x !== id) : [...safeTeam.slice(-2), id])}><react_native_1.Text style={s.name}>{selected ? '✓ ' : ''}{roleGlyph[def.role]} {def.name}</react_native_1.Text><react_native_1.Text style={s.body}>{def.role} · Lv. {view.owned[id].level} · {available ? 'Available' : 'Busy'}</react_native_1.Text></react_native_1.Pressable>; }) : <react_native_1.Text style={s.body}>Unlock companions through the Collection requirements.</react_native_1.Text>}<react_native_1.Text style={s.name}>Team Power {amount((0, team_1.companionTeamPower)(safeTeam, view.owned))}</react_native_1.Text></react_native_1.View>;
    const affordability = (cost) => !!cost && e.gold >= cost.gold && e.companionEssence >= cost.companionEssence && e.bondstones >= (cost.bondstones ?? 0) && (!cost.materialId || (e.materials[cost.materialId] ?? 0) >= (cost.materialQuantity ?? 0));
    const costText = (cost) => `${amount(cost.gold)} Gold · ${amount(cost.companionEssence)} Essence${cost.bondstones ? ` · ${cost.bondstones} Bondstones` : ''}${cost.materialId ? ` · ${cost.materialQuantity} ${named(cost.materialId)}` : ''}`;
    return <Panel_1.Panel><react_native_1.Text accessibilityRole="header" style={s.heading}>Combat Companions</react_native_1.Text><react_native_1.Text style={s.body}>{equipped ? (idle(equipped) ? `${named(equipped)} is assisting you.` : `${named(equipped)} is busy and cannot assist you until its activity ends.`) : 'One tactical companion can assist your character.'}</react_native_1.Text><react_native_1.Text style={s.body}>Choose a different role from your character. Passive pets keep their separate collection bonuses.</react_native_1.Text>
    <react_native_1.Text style={s.resources}>{amount(e.companionEssence)} Essence · {amount(e.bondstones)} Bondstones · {amount(e.gold)} Gold</react_native_1.Text>
    <react_native_1.ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{sections.map(tab => <react_native_1.Pressable key={tab} accessibilityRole="tab" accessibilityState={{ selected: section === tab }} onPress={() => setSection(tab)} style={[s.tab, section === tab && s.selected]}><react_native_1.Text style={s.name}>{tab}</react_native_1.Text></react_native_1.Pressable>)}</react_native_1.ScrollView>
    {message ? <react_native_1.Text accessibilityLiveRegion="polite" style={s.message}>{message.replace(/_/g, ' ')}</react_native_1.Text> : null}
    {section === 'Sanctuary' && <react_native_1.View style={s.group}><react_native_1.Text style={s.name}>Expedition supplies · {e.materials.SUPPLIES ?? 0} owned</react_native_1.Text><react_native_1.Text style={s.body}>Five supplies cost 250 Gold. Expedition Pens required.</react_native_1.Text>{btn('Buy 5 supplies · 250 Gold', 'companion_supplies', undefined, e.gold < 250 || !(state.account.companionSanctuary?.expeditionPensLevel))}</react_native_1.View>}
    {section === 'Trials' && <react_native_1.View style={s.group}><react_native_1.Text style={s.name}>Fallen Knight rematch</react_native_1.Text><react_native_1.Text style={s.body}>One attempt per UTC day after the story victory. Winning grants 40 Essence, 1 Bondstone, and boss progression. Story loot is not repeated.</react_native_1.Text><react_native_1.Text style={s.body}>Victories: {Math.max(state.defeatedBossIds.includes('FALLEN_KNIGHT') ? 1 : 0, state.account.companionBossClears?.FALLEN_KNIGHT ?? 0)}</react_native_1.Text>{btn(now < (state.account.companionBossRematchReadyAtMs ?? 0) ? 'Next attempt at 00:00 UTC' : 'Challenge the Fallen Knight', 'companion_boss_rematch', undefined, !state.defeatedBossIds.includes('FALLEN_KNIGHT') || now < (state.account.companionBossRematchReadyAtMs ?? 0))}</react_native_1.View>}
    {section === 'Collection' && <>
      <react_native_1.ScrollView horizontal contentContainerStyle={s.tabs}>{combat_companions_1.COMBAT_COMPANIONS.map((def, index) => { const portrait = monsters_1.MONSTERS.find(monster => monster.id === portraitIds[index % portraitIds.length]); return <react_native_1.Pressable key={def.id} accessibilityRole="button" accessibilityState={{ selected: selection === def.id }} style={[s.card, selection === def.id && s.selected]} onPress={() => setSelection(def.id)}>{portrait ? <MonsterPortraitFrame_1.MonsterPortraitFrame monster={portrait} size={62} framed={false}/> : <react_native_1.Text style={s.glyph}>{roleGlyph[def.role]}</react_native_1.Text>}<react_native_1.Text style={s.name}>{def.name}</react_native_1.Text><react_native_1.Text style={s.body}>{combat_companions_1.COMPANION_RARITY_CONFIG[def.rarity].label} · {def.role}</react_native_1.Text><react_native_1.Text style={s.body}>{view.owned[def.id] ? `Lv. ${view.owned[def.id].level}${equipped === def.id ? ' · Equipped' : ''}` : 'Locked'}</react_native_1.Text></react_native_1.Pressable>; })}</react_native_1.ScrollView>
      {model && <react_native_1.View style={s.group}><react_native_1.Text style={s.heading}>{model.def.name}</react_native_1.Text><react_native_1.Text style={s.body}>{model.def.origin.name} · {model.def.description}</react_native_1.Text><react_native_1.Text style={s.name}>{model.def.activeAbility.name}</react_native_1.Text><react_native_1.Text style={s.body}>{model.def.activeAbility.description} · {model.def.activeAbility.cooldownSeconds}s cooldown</react_native_1.Text><react_native_1.Text style={s.body}>{model.def.passiveAbility.description}</react_native_1.Text><react_native_1.Text style={s.body}>Bond 10: {model.def.bondTrait.description}</react_native_1.Text>
        {!model.owned ? <><react_native_1.Text style={s.name}>Unlock requirements</react_native_1.Text>{model.def.unlockRequirements.map((req, i) => { const p = (0, companion_presentation_1.companionRequirementProgress)(state, req); return <react_native_1.Text key={i} style={s.body}>{p.complete ? '✓' : '•'} {req.description} · {p.current}/{p.total}</react_native_1.Text>; })}<react_native_1.Text style={s.body}>Unlocks when all requirements are met. Requirements tied to unreleased game content remain locked.</react_native_1.Text></> : progress && <>
          <react_native_1.Text style={s.body}>Ascension material: {named(model.def.ascensionMaterialId ?? '')} · {(0, companion_presentation_1.companionMaterialSources)(model.def.ascensionMaterialId ?? '').slice(0, 3).join(' / ')}</react_native_1.Text>
          {btn(state.account.companionBondRewardClaims?.includes(`${selection}:2`) ? 'Bond 2 reward claimed' : 'Bond 2 reward · 20 Essence', 'companion_bond_reward', { id: selection }, progress.bondLevel < 2 || !!state.account.companionBondRewardClaims?.includes(`${selection}:2`))}
          <react_native_1.Text style={s.resources}>Level {progress.level}/{model.maxLevel} · Cap {model.levelCap} · Ascension {progress.ascensionTier}</react_native_1.Text><react_native_1.Text style={s.body}>XP {progress.xp}/{progress.level >= model.maxLevel ? 'Maximum level' : progress.level >= model.levelCap ? 'Ascension required' : (0, combat_companions_2.companionXpToNextLevel)(model.def.rarity, progress.level)} · Bond {progress.bondLevel}/10 ({progress.bondXp} total XP)</react_native_1.Text>
          {model.equipped ? btn('Unequip', 'companion_unequip') : btn(model.compatible ? 'Equip companion' : 'Same role as your character', 'companion_equip', { id: selection }, !model.compatible || !idle(selection))}
          {model.nextLevelCost && <><react_native_1.Text style={s.body}>{costText(model.nextLevelCost)}</react_native_1.Text>{btn('Train one level', 'companion_level', { id: selection }, !idle(selection) || !affordability(model.nextLevelCost))}</>}
          {model.nextAscensionCost && <><react_native_1.Text style={s.body}>{costText(model.nextAscensionCost)}</react_native_1.Text>{btn(`Ascend to tier ${model.nextAscensionTier}`, 'companion_ascend', { id: selection }, !idle(selection) || !affordability(model.nextAscensionCost))}</>}
          {model.def.rarity === 'prestige' && progress.level === 35 && !progress.mastered && btn('Complete Prestige Mastery', 'companion_master', { id: selection }, !idle(selection))}
          <react_native_1.Text style={s.name}>Techniques</react_native_1.Text>{(0, content_1.companionTechniques)(selection).map(t => <react_native_1.View key={t.id} style={s.choice}><react_native_1.Text style={s.name}>{t.name}</react_native_1.Text><react_native_1.Text style={s.body}>{t.description}</react_native_1.Text>{btn(progress.selectedTechniqueId === t.id ? 'Selected' : !progress.selectedTechniqueId ? 'Choose technique (first choice free)' : 'Switch technique · 2,500 Gold + 80 Essence', 'companion_technique', { id: selection, technique: t.id }, !idle(selection) || !(0, progression_v2_1.techniqueUnlocked)(view.owned[selection], t.id) || progress.selectedTechniqueId === t.id || !!progress.selectedTechniqueId && (e.gold < 2500 || e.companionEssence < 80))}</react_native_1.View>)}<react_native_1.Text style={s.body}>Techniques require both Ascension II and Bond 7.</react_native_1.Text>
        </>}
      </react_native_1.View>}
    </>}
    {section === 'Sanctuary' && <react_native_1.View style={s.group}>{Object.entries(combat_companions_1.COMPANION_SANCTUARY_CONFIG).map(([id, cfg]) => { const cost = (0, combat_companions_2.companionSanctuaryUpgradeCost)(state, id), level = state.account.companionSanctuary?.[`${id}Level`] ?? 0; return <react_native_1.View key={id} style={s.choice}><react_native_1.Text style={s.name}>{id.replace(/([A-Z])/g, ' $1')} · {level}/{cfg.maxLevel}</react_native_1.Text><react_native_1.Text style={s.body}>{cfg.description}</react_native_1.Text>{cost && <react_native_1.Text style={s.body}>{costText(cost)}</react_native_1.Text>}{btn(cost ? 'Upgrade' : 'Maximum level', 'companion_upgrade', { id }, !cost || !affordability(cost))}</react_native_1.View>; })}{btn('Claim daily training XP', 'companion_training', undefined, !(state.account.companionSanctuary?.trainingGroundLevel))}{btn('Claim weekly Essence', 'companion_essence', undefined, !(state.account.companionSanctuary?.essenceBasinLevel))}<react_native_1.Text style={s.body}>Training claims cap at 7 days; Essence claims cap at 2 weeks. Training excludes busy companions.</react_native_1.Text><react_native_1.Text style={s.name}>Companion materials</react_native_1.Text>{Object.entries(state.account.companionMaterials ?? {}).filter(([, n]) => n > 0).map(([id, n]) => <react_native_1.Text key={id} style={s.body}>{named(id)} ×{n}</react_native_1.Text>)}</react_native_1.View>}
    {section === 'Trials' && <react_native_1.View style={s.group}><react_native_1.Text style={s.name}>{view.trial.projection.title}</react_native_1.Text><react_native_1.Text style={s.body}>Monthly best {view.trial.projection.currentSeasonHighestFloor}/30 · Lifetime best {view.trial.projection.lifetimeHighestFloor}/30</react_native_1.Text><react_native_1.Text style={s.body}>Resets {view.trial.projection.endsAt.slice(0, 10)} at 00:00 UTC. Companion progression is permanent.</react_native_1.Text>
      {recovery > 0 && <react_native_1.Text accessibilityLiveRegion="polite" style={s.message}>Recovering from battle · {recovery}s before the next fight.</react_native_1.Text>}
      {season.specialChallenges.map(id => { const c = content_1.COMPANION_WEEKLY_CHALLENGES.find(c => c.id === id); const claimed = view.trial.progress.season.monthlyChallengeClaims?.includes(id); return <react_native_1.View key={id} style={s.choice}><react_native_1.Text style={s.name}>Monthly challenge: {c.name}</react_native_1.Text><react_native_1.Text style={s.body}>{c.description}</react_native_1.Text><react_native_1.Text style={s.body}>{c.rewards.gold} Gold · {c.rewards.companionEssence} Essence · {c.rewards.bondstones} Bondstones</react_native_1.Text>{btn(claimed ? 'Claimed' : 'Claim monthly reward', 'companion_monthly', { id }, claimed || !view.trial.progress.season.monthlyChallengeCompletion[id])}</react_native_1.View>; })}
      {run ? <><react_native_1.Text style={s.name}>Floor {run.currentFloor} · Recommended Power {(0, content_1.companionTrialRecommendedPower)(run.currentFloor)}</react_native_1.Text><react_native_1.Text style={s.body}>{run.teamCompanionIds.map(named).join(' · ')}</react_native_1.Text>{btn('Fight next floor', 'companion_trial_floor', { id: run.runId, floor: run.currentFloor }, recovery > 0)}{btn('Abandon run', 'companion_trial_abandon', { id: run.runId })}</> : <>{teamSelector}{btn(`Start at checkpoint ${view.trial.projection.checkpointFloor}`, 'companion_trial_start', { ids: safeTeam }, !trialTeamValid)}{view.trial.projection.checkpointFloor > 1 && btn('Replay from Floor 1', 'companion_trial_start', { ids: safeTeam, floor: 1 }, !trialTeamValid)}</>}
      {state.account.companionLastBattle && <react_native_1.View style={s.choice}><react_native_1.Text style={s.name}>{state.account.companionLastBattle.title}: {state.account.companionLastBattle.won ? 'Victory' : 'Defeat'}</react_native_1.Text><react_native_1.Text style={s.body}>{(state.account.companionLastBattle.durationMs / 1000).toFixed(1)} seconds · +{state.account.companionLastBattle.essence} Essence · +{state.account.companionLastBattle.gold} Gold · +{state.account.companionLastBattle.bondstones} Bondstones</react_native_1.Text></react_native_1.View>}
      <react_native_1.Text style={s.heading}>Weekly Proving Grounds</react_native_1.Text>{view.weekly.definitions.map(d => <react_native_1.View key={d.id} style={s.choice}><react_native_1.Text style={s.name}>{d.name}</react_native_1.Text><react_native_1.Text style={s.body}>{d.description} · {view.proving.state.progress[d.id] ?? 0}/{d.targetCount}</react_native_1.Text>{btn(view.proving.state.claimedIds.includes(d.id) ? 'Claimed' : 'Claim reward', 'companion_weekly', { id: d.id }, !view.proving.state.completedIds.includes(d.id) || view.proving.state.claimedIds.includes(d.id))}</react_native_1.View>)}
      <react_native_1.Text style={s.heading}>Special challenges</react_native_1.Text>{content_1.COMPANION_SPECIAL_CHALLENGES.filter(c => !!combat_companions_1.COMBAT_COMPANIONS.find(d => d.id === c.rewardCompanionId)).map(c => { const valid = (0, special_challenges_1.validateSpecialCompanionChallenge)({ challengeId: c.id, facts: (0, companion_runtime_1.companionUnlockFacts)(state), teamIds: safeTeam, owned: view.owned, busyCompanionIds: new Set(ownedIds.filter(id => !idle(id))) }); return <react_native_1.View key={c.id} style={s.choice}><react_native_1.Text style={s.name}>{c.name}</react_native_1.Text>{c.requirements.map((r, i) => <react_native_1.Text key={i} style={s.body}>• {r.description}</react_native_1.Text>)}{btn('Challenge', 'companion_special', { id: c.id, ids: safeTeam }, !valid.ok || !!state.account.companionSpecialClears?.includes(c.id))}</react_native_1.View>; })}
    </react_native_1.View>}
    {section === 'Expeditions' && <react_native_1.View style={s.group}>{teamSelector}<react_native_1.Text style={s.name}>Sanctuary assignments</react_native_1.Text>{content_1.COMPANION_MISSIONS.map(m => <react_native_1.Pressable key={m.id} accessibilityRole="radio" accessibilityState={{ selected: mission === m.id }} style={[s.choice, mission === m.id && s.selected]} onPress={() => setMission(m.id)}><react_native_1.Text style={s.name}>{m.name}</react_native_1.Text><react_native_1.Text style={s.body}>{m.durationMs / 3600000}h · {m.minCompanions}–{m.maxCompanions} companions · Pen {m.minimumPenLevel ?? 1} · {m.costs.gold} Gold</react_native_1.Text><react_native_1.Text style={s.body}>Recommended Power {m.recommendedPower} · Base reward {m.baseRewards.companionEssence} Essence</react_native_1.Text></react_native_1.Pressable>)}{(() => { const check = (0, assignments_1.validateCompanionMissionTeam)({ missionId: mission, companionIds: safeTeam, owned: view.owned, assignments: view.assignments, equippedCompanionIds: new Set(equipped ? [equipped] : []), lockedTrialCompanionIds: new Set(run?.teamCompanionIds ?? []), expeditionPensLevel: state.account.companionSanctuary?.expeditionPensLevel ?? 0 }); return <>{!check.ok && <react_native_1.Text style={s.body}>{check.reason.replace(/_/g, ' ')}</react_native_1.Text>}{btn('Send assignment', 'companion_assignment_start', { id: mission, ids: safeTeam }, !check.ok)}</>; })()}{view.assignments.map(a => <react_native_1.View key={a.assignmentId} style={s.choice}><react_native_1.Text style={s.name}>{content_1.COMPANION_MISSIONS.find(m => m.id === a.missionId)?.name}</react_native_1.Text><react_native_1.Text style={s.body}>{a.companionIds.map(named).join(' · ')} · {a.status}</react_native_1.Text><react_native_1.Text style={s.body}>{a.endsAt.replace('T', ' ').slice(0, 16)} UTC</react_native_1.Text>{btn(a.status === 'claimed' ? 'Claimed' : 'Claim assignment', 'companion_assignment_claim', { id: a.assignmentId }, a.status !== 'completed')}</react_native_1.View>)}</react_native_1.View>}
    {section === 'Codex' && <react_native_1.View style={s.group}><react_native_1.Text style={s.name}>{view.codex.summary.totalOwned}/{combat_companions_1.COMBAT_COMPANIONS.length} companions collected</react_native_1.Text><react_native_1.Text style={s.body}>Favorite: {view.codex.favoriteCompanionId ? named(view.codex.favoriteCompanionId) : 'None'} · Showcase slots {view.codex.showcaseSlotsUnlocked}</react_native_1.Text>{ownedIds.map(id => <react_native_1.View key={id} style={s.choice}><react_native_1.Text style={s.name}>{named(id)}</react_native_1.Text>{btn(view.codex.favoriteCompanionId === id ? 'Favorite' : 'Make favorite', 'companion_showcase', { id, ids: view.codex.showcaseCompanionIds }, view.codex.favoriteCompanionId === id)}{btn(view.codex.showcaseCompanionIds.includes(id) ? 'Remove from showcase' : 'Add to showcase', 'companion_showcase', { id: view.codex.favoriteCompanionId, ids: view.codex.showcaseCompanionIds.includes(id) ? view.codex.showcaseCompanionIds.filter(x => x !== id) : [...view.codex.showcaseCompanionIds, id] }, !view.codex.showcaseCompanionIds.includes(id) && view.codex.showcaseCompanionIds.length >= view.codex.showcaseSlotsUnlocked)}</react_native_1.View>)}{view.codex.milestones.map(m => <react_native_1.View key={m.id} style={s.choice}><react_native_1.Text style={s.name}>{m.name}</react_native_1.Text>{btn(m.claimed ? 'Claimed' : 'Claim milestone', 'companion_codex', { id: m.id }, m.claimed || !m.complete)}</react_native_1.View>)}</react_native_1.View>}
  </Panel_1.Panel>;
}
const s = react_native_1.StyleSheet.create({ heading: { ...theme_1.typography.title, color: theme_1.C.text }, name: { ...theme_1.typography.bodyStrong, color: theme_1.C.text }, body: { ...theme_1.typography.body, color: theme_1.C.muted }, resources: { ...theme_1.typography.bodyStrong, color: theme_1.C.accent }, message: { ...theme_1.typography.body, color: theme_1.C.info }, tabs: { gap: 8, paddingVertical: 6 }, tab: { minHeight: 48, padding: 12, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: theme_1.radii.sm, justifyContent: 'center' }, selected: { borderColor: theme_1.C.info, backgroundColor: '#172c3c' }, card: { width: 176, padding: 12, gap: 6, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: theme_1.radii.md }, glyph: { fontSize: 28, color: theme_1.C.accent }, group: { gap: 12 }, choice: { padding: 12, gap: 8, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: theme_1.radii.md } });
