"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EquipmentSlot = void 0;
const react_1 = require("react");
const react_native_1 = require("react-native");
const item_rarity_1 = require("../core/item-rarity");
const theme_1 = require("../theme/theme");
const EquipmentArtwork_1 = require("./EquipmentArtwork");
exports.EquipmentSlot = (0, react_1.memo)(function EquipmentSlot({ slot, label, item, rank = 0, socketed = 0, socketCapacity = 0, selected, disabled = false, compact = false, onPress }) {
    const { width, fontScale } = (0, react_native_1.useWindowDimensions)();
    const compactWidth = width < 360 || fontScale > 1.2 ? '30%' : '22%';
    const meta = item ? (0, item_rarity_1.rarityMeta)((0, item_rarity_1.itemRarity)(item)) : undefined, hasArt = !!item && (0, EquipmentArtwork_1.hasEquipmentArtwork)(item);
    return <react_native_1.Pressable accessibilityRole="button" accessibilityLabel={item ? `${label}: ${item.name}, ${meta?.label}` : `${label}: empty`} accessibilityState={{ selected, disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [s.root, compact && [s.compact, { width: compactWidth }], meta && { borderColor: meta.color, backgroundColor: meta.surface }, selected && s.selected, pressed && !disabled && s.pressed, disabled && s.disabled]}>
    <react_native_1.Text style={s.slotLabel}>{label}</react_native_1.Text><react_native_1.View style={[s.art, compact && s.compactArt]}>{item && hasArt ? <EquipmentArtwork_1.EquipmentArtwork item={item} compact={compact} framed={false}/> : <react_native_1.View style={{ opacity: .3 }}><EquipmentArtwork_1.EquipmentArtwork framed={false} compact={compact} item={{ id: 'empty-slot', name: label, type: 'gear', slot, value: 0, noviceSetId: 'ironwarden_recruit' }}/></react_native_1.View>}</react_native_1.View>
    {!compact && <react_native_1.Text numberOfLines={2} style={[s.itemName, !item && s.empty]}>{item?.name ?? 'Empty slot'}</react_native_1.Text>}{!compact && meta && <react_native_1.Text style={[s.rarity, { color: meta.color }]}>{meta.symbol} {meta.label}</react_native_1.Text>}{item && rank > 0 && <react_native_1.View pointerEvents="none" style={s.rankBadge}><react_native_1.Text style={s.rankText}>+{rank}</react_native_1.Text></react_native_1.View>}{item && socketCapacity > 0 && <react_native_1.View pointerEvents="none" style={s.socketBadge}><react_native_1.Text style={s.socketText}>◆ {socketed}/{socketCapacity}</react_native_1.Text></react_native_1.View>}{selected && !compact && <react_native_1.View pointerEvents="none" style={s.selectedCorner}><react_native_1.Text style={s.selectedMark}>✓</react_native_1.Text></react_native_1.View>}
  </react_native_1.Pressable>;
});
const s = react_native_1.StyleSheet.create({ compact: { width: '22%', minHeight: 102, padding: 4 }, compactArt: { height: 52 }, rankBadge: { position: 'absolute', left: 4, top: 28, minWidth: 27, paddingHorizontal: 4, paddingVertical: 2, borderWidth: 1, borderColor: theme_1.equipmentColors.gold, backgroundColor: '#07111c', borderRadius: theme_1.radii.sm }, rankText: { fontSize: 10, color: theme_1.equipmentColors.goldSoft, fontWeight: '700' }, socketBadge: { position: 'absolute', left: 4, bottom: 4, paddingHorizontal: 4, paddingVertical: 2, backgroundColor: '#07111c', borderWidth: 1, borderColor: '#7455b8', borderRadius: theme_1.radii.sm }, socketText: { fontSize: 9, color: '#c9a7ff', fontWeight: '700' }, root: { position: 'relative', width: '48.5%', minHeight: 148, minWidth: theme_1.touchTargetPreferred, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: theme_1.radii.sm, backgroundColor: theme_1.equipmentColors.stage, padding: theme_1.spacing.sm, alignItems: 'center', gap: theme_1.spacing.xs, overflow: 'hidden' }, selected: { borderWidth: 2, borderColor: theme_1.equipmentColors.selectedLine, backgroundColor: theme_1.equipmentColors.selected }, pressed: { opacity: .78, transform: [{ translateY: 1 }] }, disabled: { opacity: .45 }, slotLabel: { ...theme_1.typography.caption, color: theme_1.equipmentColors.goldSoft, fontWeight: '600', letterSpacing: 0, textAlign: 'center' }, art: { height: 66, justifyContent: 'center' }, placeholder: { width: 64, height: 64, borderWidth: 1, borderColor: theme_1.C.line, backgroundColor: 'rgba(4,10,17,.55)', alignItems: 'center', justifyContent: 'center' }, placeholderPending: { borderColor: theme_1.equipmentColors.lineStrong, backgroundColor: 'rgba(114,90,43,.12)' }, placeholderMark: { fontSize: 24, color: theme_1.C.muted, lineHeight: 28 }, placeholderMarkPending: { color: theme_1.equipmentColors.goldSoft }, placeholderText: { fontSize: 8, color: theme_1.C.muted, fontWeight: '700', letterSpacing: .4 }, itemName: { ...theme_1.typography.caption, color: theme_1.C.text, textAlign: 'center', fontWeight: '600', minHeight: 32 }, empty: { color: theme_1.C.muted, fontWeight: '600' }, rarity: { fontSize: 10, fontWeight: '700' }, selectedCorner: { position: 'absolute', right: 3, top: 3, width: 22, height: 22, borderLeftWidth: 1, borderBottomWidth: 1, borderColor: theme_1.equipmentColors.selectedLine, backgroundColor: theme_1.equipmentColors.stage, alignItems: 'center', justifyContent: 'center' }, selectedMark: { fontSize: 11, color: theme_1.equipmentColors.selectedLine, fontWeight: '700' } });
