"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ItemCard = ItemCard;
const react_native_1 = require("react-native");
const items_1 = require("../content/items");
const theme_1 = require("../theme/theme");
const GameButton_1 = require("./GameButton");
const Panel_1 = require("./Panel");
const item_rarity_1 = require("../core/item-rarity");
const EquipmentArtwork_1 = require("./EquipmentArtwork");
const equipment_sets_1 = require("../content/equipment-sets");
const number_format_1 = require("../core/number-format");
const GatheringToolArtwork_1 = require("./GatheringToolArtwork");
const ResourceArtwork_1 = require("./ResourceArtwork");
const resource_assets_1 = require("../theme/resource-assets");
const stats = [{ key: 'attack', label: 'ATK' }, { key: 'defense', label: 'DEF' }, { key: 'hp', label: 'HP' }];
function delta(next, current) { const value = next - current; return value === 0 ? '—' : `${value > 0 ? '+' : ''}${value}`; }
function ItemCard({ item, quantity, equipped, upgradeRank = 0, socketed = 0, socketCapacity = 0, enhancementProtected = false, displayStats, equippedDisplayStats, selectedFood = false, onEquip, onSelectFood, onEat, onSell, onSalvage, onDeposit, onWithdraw, transferQuantity = 1, transferIssue = '', healAmount, onPreview, numberMode = 'abbreviated', expanded = true, onToggle }) {
    const gear = item.type === 'gear', tool = item.type === 'tool', resource = (0, resource_assets_1.hasResourceArtwork)(item.id), visualItem = gear || tool || resource, rarity = (0, item_rarity_1.itemRarity)(item), meta = (0, item_rarity_1.rarityMeta)(rarity);
    const set = (0, equipment_sets_1.equipmentSetDef)(item.equipmentSetId);
    return <Panel_1.Panel>
    <react_native_1.Pressable disabled={!onToggle} accessibilityRole="button" accessibilityLabel={item.name} accessibilityState={{ expanded: onToggle ? expanded : undefined }} onPress={onToggle} style={s.heading}>{gear ? <EquipmentArtwork_1.EquipmentArtwork item={item} compact framed={false}/> : tool ? <GatheringToolArtwork_1.GatheringToolArtwork itemId={item.id} framed={false}/> : resource ? <ResourceArtwork_1.ResourceArtwork itemId={item.id} framed={false}/> : null}<react_native_1.View style={s.copy}><react_native_1.Text style={s.name}>{item.name}{gear && upgradeRank > 0 ? ` +${upgradeRank}` : ''}</react_native_1.Text><react_native_1.View style={[s.rarityBadge, { borderColor: meta.color, backgroundColor: meta.surface }]}><react_native_1.Text style={[s.rarity, { color: meta.color }]}>{meta.symbol} {(0, item_rarity_1.rarityLabel)(item)} · {item.type.toUpperCase()}{item.slot ? ` · ${item.slot.toUpperCase()}` : ''}{gear && socketCapacity ? ` · ◆ ${socketed}/${socketCapacity}` : ''}</react_native_1.Text></react_native_1.View></react_native_1.View><react_native_1.Text style={[s.qty, visualItem && { color: meta.color }]}>×{(0, number_format_1.formatGameNumber)(quantity, numberMode)}</react_native_1.Text></react_native_1.Pressable>
    {expanded && <>
    {onPreview && <GameButton_1.GameButton title="Compare stats" tone="secondary" onPress={onPreview}/>}
    {gear && <><react_native_1.View style={s.stats}>{stats.map(({ key, label }) => { const value = displayStats?.[key] ?? item[key] ?? 0, current = equippedDisplayStats?.[key] ?? equipped?.[key] ?? 0, d = value - current; return <react_native_1.View key={key} style={s.stat}><react_native_1.Text style={s.statLabel}>{label}</react_native_1.Text><react_native_1.Text style={s.statValue}>{value}</react_native_1.Text><react_native_1.Text style={[s.delta, d > 0 ? s.better : d < 0 ? s.worse : s.same]}>{delta(value, current)}</react_native_1.Text></react_native_1.View>; })}</react_native_1.View><react_native_1.Text style={s.compare}>{equipped ? `Compared with ${equipped.name}` : `Changes versus an empty ${item.slot} slot`}</react_native_1.Text>{set && <react_native_1.View style={[s.setInfo, { borderColor: set.accent, backgroundColor: set.surface }]}><react_native_1.Text style={[s.setName, { color: set.accent }]}>{set.name} · 4-piece set</react_native_1.Text><react_native_1.Text style={s.setBonus}>2 pieces · {set.twoPiece}</react_native_1.Text><react_native_1.Text style={s.setBonus}>4 pieces · {set.fourPiece}</react_native_1.Text></react_native_1.View>}{(rarity === 'legendary' || rarity === 'mythic') && <react_native_1.Text style={s.passive}>◆ Passive: {item.passive || 'Class-aligned bonus is active while equipped.'}</react_native_1.Text>}</>}
    {item.type === 'food' ? <react_native_1.Text style={s.food}>Restores {item.heal} HP · readiness {item.readiness || 0}{selectedFood ? ' · AUTO-EAT SELECTED' : ''}</react_native_1.Text> : item.type === 'tool' ? <react_native_1.Text style={s.food}>{item.toolSkillId?.toUpperCase()} TOOL · Tier {item.toolTier} · {Math.round((1 - (item.actionTimeMultiplier ?? 1)) * 100)}% shorter base action time</react_native_1.Text> : !gear && <react_native_1.Text style={s.value}>Sell value · {item.value} gold each</react_native_1.Text>}
    {enhancementProtected && <react_native_1.Text style={s.protected}>◆ Enhanced gear protected from selling and salvage</react_native_1.Text>}{item.salvage && <react_native_1.Text style={s.salvage}>Salvage yields {(0, number_format_1.formatGameNumber)(item.salvage.quantity, numberMode)}× {(0, items_1.itemDef)(item.salvage.itemId).name}</react_native_1.Text>}
    {onEquip && <GameButton_1.GameButton title={`Equip ${item.slot}`} onPress={onEquip}/>}{onSelectFood && <GameButton_1.GameButton title={selectedFood ? 'Auto-eat selected' : 'Use for auto-eat'} disabled={selectedFood} onPress={onSelectFood}/>}{onEat && <GameButton_1.GameButton title={healAmount === 0 ? 'Health full' : `Eat 1 · +${(0, number_format_1.formatGameNumber)(healAmount ?? item.heal ?? 0, numberMode)} HP`} disabled={healAmount === 0} tone="secondary" onPress={onEat}/>}{onSell && <GameButton_1.GameButton title={`Sell 1 · ${(0, number_format_1.formatGameNumber)(item.value, numberMode)} gold`} tone="secondary" onPress={onSell}/>}{onSalvage && <GameButton_1.GameButton title="Salvage 1" tone="danger" onPress={onSalvage}/>}{onDeposit && <GameButton_1.GameButton title={`Deposit ${(0, number_format_1.formatGameNumber)(transferQuantity, numberMode)} to Bank`} disabled={!!transferIssue} tone="secondary" onPress={onDeposit}/>}{onWithdraw && <GameButton_1.GameButton title={`Withdraw ${(0, number_format_1.formatGameNumber)(transferQuantity, numberMode)}`} disabled={!!transferIssue} tone="secondary" onPress={onWithdraw}/>}
    {!!transferIssue && <react_native_1.Text style={s.salvage}>Transfer unavailable: {transferIssue}. Try a smaller quantity or free space.</react_native_1.Text>}
    </>}
    {onToggle && <react_native_1.Pressable accessibilityRole="button" accessibilityLabel={expanded ? "Hide item actions" : "Show item actions"} onPress={onToggle} style={s.detailToggle}><react_native_1.Text style={s.compare}>{expanded ? "Hide details" : "Details & actions"}</react_native_1.Text></react_native_1.Pressable>}
  </Panel_1.Panel>;
}
const s = react_native_1.StyleSheet.create({ detailToggle: { minHeight: 44, justifyContent: 'center' }, heading: { minHeight: 64, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: theme_1.spacing.md }, copy: { flex: 1, minWidth: 0, gap: theme_1.spacing.xs }, name: { ...theme_1.typography.bodyStrong, fontSize: 16, lineHeight: 23, color: theme_1.C.text }, rarityBadge: { alignSelf: 'flex-start', borderLeftWidth: 2, paddingLeft: 6, paddingVertical: 2 }, rarity: { ...theme_1.typography.caption, fontWeight: '700' }, qty: { fontSize: 18, color: theme_1.C.accent, fontWeight: '700' }, stats: { flexDirection: 'row', gap: theme_1.spacing.sm }, stat: { flex: 1, backgroundColor: theme_1.C.panel2, borderRadius: theme_1.radii.sm, padding: theme_1.spacing.sm }, statLabel: { ...theme_1.typography.caption, color: theme_1.C.muted }, statValue: { ...theme_1.typography.bodyStrong, color: theme_1.C.text }, delta: { ...theme_1.typography.caption, fontWeight: '700' }, better: { color: theme_1.C.good }, worse: { color: theme_1.C.bad }, same: { color: theme_1.C.muted }, compare: { ...theme_1.typography.caption, color: theme_1.C.info }, setInfo: { gap: theme_1.spacing.xs, borderWidth: 1, borderRadius: theme_1.radii.sm, padding: theme_1.spacing.sm }, setName: { ...theme_1.typography.bodyStrong }, setBonus: { ...theme_1.typography.caption, color: theme_1.C.text }, passive: { ...theme_1.typography.bodyStrong, color: '#f0a24b' }, value: { ...theme_1.typography.body, color: theme_1.C.muted }, food: { ...theme_1.typography.bodyStrong, color: theme_1.C.good }, protected: { ...theme_1.typography.caption, color: theme_1.C.info, fontWeight: '600' }, salvage: { ...theme_1.typography.body, color: theme_1.C.warning } });
