"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlayerProfileCard = PlayerProfileCard;
const react_native_1 = require("react-native");
const GameButton_1 = require("./GameButton");
const CharacterVisual_1 = require("./CharacterVisual");
const theme_1 = require("../theme/theme");
const live_events_1 = require("../content/live-events");
const event_pet_assets_1 = require("../theme/event-pet-assets");
function PlayerProfileCard({ visible, onClose, state, name, title = 'Bloomwarden', showModerationActions = true, onBlock, onReport }) { const c = state.character, eventRewards = c ? live_events_1.LIVE_EVENT_CATALOG.flatMap(event => event.milestones(c.classId).map(milestone => milestone.reward).concat(event.shop.map(offer => offer.reward))) : [], pet = eventRewards.find(reward => reward.id === c?.selectedCosmeticPetId), petSource = event_pet_assets_1.eventPetSourceById.get(c?.selectedCosmeticPetId ?? ''); return <react_native_1.Modal visible={visible} transparent animationType={state.settings.reduceMotion ? 'none' : 'fade'} onRequestClose={onClose}><react_native_1.View style={s.scrim}><react_native_1.View style={[s.card, c?.profileBorderId && s.eventCard]}><react_native_1.Text style={s.heading}>{name}</react_native_1.Text><react_native_1.Text style={s.title}>“{title}”</react_native_1.Text><react_native_1.View style={s.background}><CharacterVisual_1.CharacterVisual state={state} compact/></react_native_1.View><react_native_1.Text style={s.meta}>Level {c?.level ?? 1} · {c?.classId ?? 'Adventurer'}</react_native_1.Text>{pet ? <react_native_1.View style={s.pet}><>{petSource ? <react_native_1.Image source={petSource} resizeMode="contain" style={s.petImage}/> : null}</><react_native_1.Text style={s.petName}>Companion · {pet.name}</react_native_1.Text></react_native_1.View> : null}<react_native_1.Text style={s.meta}>Selected character skin; equipped items affect stats only.</react_native_1.Text>{showModerationActions && <react_native_1.View style={s.row}><GameButton_1.GameButton title={onBlock ? 'Block' : 'Block unavailable'} tone="secondary" disabled={!onBlock} onPress={() => onBlock?.()}/><GameButton_1.GameButton title={onReport ? 'Report' : 'Report unavailable'} tone="danger" disabled={!onReport} onPress={() => onReport?.()}/></react_native_1.View>}<GameButton_1.GameButton title="Close" onPress={onClose}/></react_native_1.View></react_native_1.View></react_native_1.Modal>; }
const s = react_native_1.StyleSheet.create({ scrim: { flex: 1, backgroundColor: 'rgba(0,0,0,.72)', justifyContent: 'center', padding: 18 }, card: { backgroundColor: theme_1.C.panel, borderWidth: 1, borderColor: theme_1.C.accent, borderRadius: 12, padding: 16, gap: 8 }, eventCard: { borderWidth: 3, borderColor: '#d9953f', shadowColor: '#e7ae55', shadowOpacity: .6, shadowRadius: 10, shadowOffset: { width: 0, height: 0 } }, heading: { color: theme_1.C.text, fontSize: 24, fontWeight: '900', textAlign: 'center' }, title: { color: theme_1.C.accent, fontSize: 16, fontStyle: 'italic', textAlign: 'center' }, background: { backgroundColor: '#101d2b', borderWidth: 1, borderColor: theme_1.C.line, borderRadius: 8, alignItems: 'center', padding: 8 }, meta: { color: theme_1.C.muted, textAlign: 'center' }, pet: { alignSelf: 'center', alignItems: 'center', padding: 6, borderWidth: 1, borderColor: '#d9953f', borderRadius: 8, backgroundColor: '#1c140d' }, petImage: { width: 64, height: 64 }, petName: { color: '#e7ae55', fontWeight: '900', textAlign: 'center' }, row: { flexDirection: 'row', gap: 8 } });
