import {COMPANION_CODEX_MILESTONES,COMPANION_RARITY_MAX_LEVEL,COMPANION_SERVER_DEFINITIONS,COMPANION_SPECIAL_CHALLENGES,companionServerDefinition,companionTechniques} from './content';
import type {CompanionRarity} from './policy';
import {techniqueUnlocked} from './progression-v2';
import type {CompanionCodexEntryState,CompanionCodexMilestoneDefinition,CompanionCodexProfileState,CompanionCodexSummary,CompanionEconomyState,OwnedCompanionSnapshot} from './domain';

export function companionMasteryRequiredAscension(companionId:string){const def=companionServerDefinition(companionId);if(!def)throw new Error('unknown_companion');return def.rarity==='standard'||def.rarity==='rare'?2:3;}
export function isCompanionMastered(progress:OwnedCompanionSnapshot){const def=companionServerDefinition(progress.companionId);if(!def)return false;const maxLevel=COMPANION_RARITY_MAX_LEVEL[def.rarity],techniques=companionTechniques(def.id),techniqueSystemUnlocked=techniques.length===2&&techniques.every(t=>techniqueUnlocked(progress,t.id));const common=progress.level>=maxLevel&&progress.ascensionTier>=companionMasteryRequiredAscension(def.id)&&progress.bondLevel>=10&&progress.bondTraitUnlocked&&techniqueSystemUnlocked;return common&&(def.rarity!=='prestige'||progress.mastered===true);}
export function companionCodexState(companionId:string,progress:OwnedCompanionSnapshot|undefined,profile?:CompanionCodexProfileState):CompanionCodexEntryState{const def=companionServerDefinition(companionId);if(!def)return 'unknown';if(progress)return isCompanionMastered(progress)?'mastered':'owned';if(profile?.discoveredCompanionIds?.includes(companionId))return 'discovered';return def.rarity==='prestige'?'unknown':'locked';}
export function companionCodexEntryV2(progress:OwnedCompanionSnapshot|undefined,companionId:string,profile?:CompanionCodexProfileState){const def=companionServerDefinition(companionId);if(!def)throw new Error('unknown_companion');const state=companionCodexState(companionId,progress,profile),hidden=state==='unknown';return {companionId,state,name:hidden?'Unknown Companion':def.name,owned:!!progress,discovered:state!=='unknown',rarity:hidden?undefined:def.rarity,originId:hidden?undefined:def.originId,role:hidden?undefined:def.role,level:progress?.level??0,maxLevel:hidden?undefined:COMPANION_RARITY_MAX_LEVEL[def.rarity],ascensionTier:progress?.ascensionTier??0,bondLevel:progress?.bondLevel??0,selectedTechniqueId:progress?.selectedTechniqueId,bondTraitUnlocked:progress?.bondTraitUnlocked??false,mastered:progress?isCompanionMastered(progress):false,originalEventReleaseYear:progress?.originalEventReleaseYear,veteranCosmeticEligible:progress?.veteranCosmeticEligible??false,techniques:hidden?[]:companionTechniques(companionId).map(x=>({id:x.id,name:x.name,unlocked:progress?techniqueUnlocked(progress,x.id):false})),visual:hidden?undefined:resolveCompanionVisualPresentation(companionId,progress)};}
export function companionCodexSummary(owned:Record<string,OwnedCompanionSnapshot>):CompanionCodexSummary{const byRarity:Record<CompanionRarity,number>={standard:0,rare:0,elite:0,prestige:0},byOrigin:Record<string,number>={};let maxLevelCount=0,bond10Count=0,masteredCount=0,eventCompanionCount=0,trialBossCompanionCount=0;const trialBossRewards=new Set(COMPANION_SPECIAL_CHALLENGES.map(x=>x.rewardCompanionId));for(const p of Object.values(owned)){const def=companionServerDefinition(p.companionId);if(!def)continue;byRarity[def.rarity]++;byOrigin[def.originId]=(byOrigin[def.originId]??0)+1;if(p.level>=COMPANION_RARITY_MAX_LEVEL[def.rarity])maxLevelCount++;if(p.bondLevel>=10)bond10Count++;if(isCompanionMastered(p))masteredCount++;if(p.originalEventReleaseYear)eventCompanionCount++;if(trialBossRewards.has(p.companionId))trialBossCompanionCount++;}return {totalOwned:Object.values(byRarity).reduce((a,b)=>a+b,0),byRarity,byOrigin,maxLevelCount,bond10Count,masteredCount,eventCompanionCount,trialBossCompanionCount,originsOwned:Object.keys(byOrigin).length};}
export function codexMilestoneSatisfied(def:CompanionCodexMilestoneDefinition,summary:CompanionCodexSummary){const r=def.requirement;switch(r.type){case 'owned_total':return summary.totalOwned>=r.count;case 'owned_rarity':return summary.byRarity[r.rarity]>=r.count;case 'bond_10':return summary.bond10Count>=r.count;case 'mastered':return summary.masteredCount>=r.count;case 'origins_owned':return summary.originsOwned>=r.count;case 'max_level':return summary.maxLevelCount>=r.count;case 'event_owned':return summary.eventCompanionCount>=r.count;case 'trial_boss_owned':return summary.trialBossCompanionCount>=r.count;}}
export function availableCompanionCodexMilestones(owned:Record<string,OwnedCompanionSnapshot>,profile:CompanionCodexProfileState){const summary=companionCodexSummary(owned),claimed=new Set(profile.claimedCodexMilestoneIds??[]);return COMPANION_CODEX_MILESTONES.map(def=>({definition:def,complete:codexMilestoneSatisfied(def,summary),claimed:claimed.has(def.id)}));}
export function claimCompanionCodexMilestone(input:{milestoneId:string;owned:Record<string,OwnedCompanionSnapshot>;profile:CompanionCodexProfileState;economy:CompanionEconomyState}){const def=COMPANION_CODEX_MILESTONES.find(x=>x.id===input.milestoneId);if(!def)throw new Error('unknown_companion_codex_milestone');const claimed=new Set(input.profile.claimedCodexMilestoneIds??[]);if(claimed.has(def.id))throw new Error('companion_codex_milestone_already_claimed');const summary=companionCodexSummary(input.owned);if(!codexMilestoneSatisfied(def,summary))throw new Error('companion_codex_milestone_not_complete');claimed.add(def.id);const rewardIds=[...new Set([...(input.profile.codexRewardIds??[]),...(def.reward.rewardIds??[])])],showcaseSlotsUnlocked=Math.max(1,Math.min(3,def.reward.showcaseSlots??input.profile.showcaseSlotsUnlocked??1));return {profile:{...input.profile,claimedCodexMilestoneIds:[...claimed],codexRewardIds:rewardIds,showcaseSlotsUnlocked},economy:{...input.economy,companionEssence:input.economy.companionEssence+(def.reward.companionEssence??0)},reward:def.reward,summary};}
export function sanitizeCompanionShowcase(profile:CompanionCodexProfileState,owned:Record<string,OwnedCompanionSnapshot>){const ownedIds=new Set(Object.keys(owned)),slots=Math.max(1,Math.min(3,profile.showcaseSlotsUnlocked??3)),favorite=profile.favoriteCompanionId&&ownedIds.has(profile.favoriteCompanionId)?profile.favoriteCompanionId:undefined,showcase=[...new Set(profile.showcaseCompanionIds??[])].filter(id=>ownedIds.has(id)&&!!companionServerDefinition(id)).slice(0,slots);return {...profile,favoriteCompanionId:favorite,showcaseCompanionIds:showcase,showcaseSlotsUnlocked:slots,discoveredCompanionIds:[...new Set([...(profile.discoveredCompanionIds??[]),...ownedIds])],claimedCodexMilestoneIds:[...new Set(profile.claimedCodexMilestoneIds??[])],codexRewardIds:[...new Set(profile.codexRewardIds??[])]};}
export function resolveCompanionVisualPresentation(companionId:string,progress?:OwnedCompanionSnapshot){const def=companionServerDefinition(companionId);if(!def)throw new Error('unknown_companion');const visual=def.visual??{rarityIcon:'?',rarityLabel:def.rarity,accessibilityLabel:`${def.rarity} combat companion`};return {...visual,masteryMarker:progress&&isCompanionMastered(progress)?visual.masteryMarker:undefined,isMastered:!!progress&&isCompanionMastered(progress),rarity:def.rarity};}
export function companionCodexDefinitions(){return COMPANION_SERVER_DEFINITIONS.map(x=>x.id);}
