import {COMPANION_SPECIAL_CHALLENGES,COMPANION_TRIAL_MITIGATION_CONSTANT,companionServerDefinition} from './content';
import {buildOwnedCompanionCombatant} from './combat-adapter';
import {companionUnlockRequirementsSatisfied} from './progression-v2';
import {totalCompanionHasteBonus,totalCompanionSynergyMultiplier,validateCompanionTrialTeam} from './team';
import type {CompanionCombatExecutor,CompanionCombatantDefinition,CompanionUnlockFacts,OwnedCompanionSnapshot} from './domain';

export const companionSpecialChallenge=(id:string)=>COMPANION_SPECIAL_CHALLENGES.find(x=>x.id===id);
function boss(id:string,power:number):CompanionCombatantDefinition{const scale=Math.max(.85,Math.min(1.15,power/4300));return {id,name:id.replace(/_/g,' '),team:'enemies',role:'enemy',level:35,stats:{maxHp:Math.round(1100*scale),attackPower:Number((65*scale).toFixed(2)),healingPower:0,defense:Number((50*scale).toFixed(2)),accuracy:.91,evasion:.05,critChance:.07,critMultiplier:1.55,haste:.12},basicAttackMs:2200,basicAttackCoeff:.76,abilities:[{id:`${id}_SIGNATURE`,name:'Companion Challenge Signature',cooldownMs:13000,castTimeMs:0,target:'current_target',effects:[{kind:'damage',coeff:1.20,tag:'companion_special_boss'}],priority:90,aiCondition:'always'}],boss:true,tags:['companion_special_boss']};}
export function validateSpecialCompanionChallenge(input:{challengeId:string;facts:CompanionUnlockFacts;teamIds:string[];owned:Record<string,OwnedCompanionSnapshot>;busyCompanionIds:ReadonlySet<string>}){const c=companionSpecialChallenge(input.challengeId);if(!c)return {ok:false as const,reason:'unknown_companion_special_challenge'};if(!companionUnlockRequirementsSatisfied(c.requirements,input.facts))return {ok:false as const,reason:'companion_special_requirements_not_met'};const team=validateCompanionTrialTeam({companionIds:input.teamIds,owned:input.owned,busyCompanionIds:input.busyCompanionIds});if(!team.ok)return team;if(team.power<c.recommendedTeamPower*.7)return {ok:false as const,reason:'companion_special_team_power_too_low'};return {ok:true as const,challenge:c,team};}
export function resolveSpecialCompanionChallenge(input:{challengeId:string;facts:CompanionUnlockFacts;teamIds:string[];owned:Record<string,OwnedCompanionSnapshot>;busyCompanionIds:ReadonlySet<string>;seed:string},executor:CompanionCombatExecutor){const checked=validateSpecialCompanionChallenge(input);if(!checked.ok)throw new Error(checked.reason);const synergy=checked.team.synergies,mult=totalCompanionSynergyMultiplier(synergy),haste=totalCompanionHasteBonus(synergy);const players=input.teamIds.map(id=>buildOwnedCompanionCombatant(input.owned[id],{mode:'companion_trial',teamSynergyMultiplier:mult,teamHasteBonus:haste}));const result=executor.simulate({seed:input.seed,players,enemies:[boss(checked.challenge.bossId,checked.challenge.recommendedTeamPower)],mitigationConstant:COMPANION_TRIAL_MITIGATION_CONSTANT});if(!result.victory)return {result,unlockedCompanionId:undefined};const target=companionServerDefinition(checked.challenge.rewardCompanionId);return {result,unlockedCompanionId:target?.id,completionKey:checked.challenge.id};}
