import {ImageSourcePropType} from 'react-native';
import {BodyPresentation,ClassId} from '../core/types';
export const startingAppearance:Record<ClassId,Record<BodyPresentation,Record<'front'|'back',ImageSourcePropType>>>={
IRONWARDEN:{male:{front:require('../../assets/character-runtime/ironwarden/male/front.png'),back:require('../../assets/character-runtime/ironwarden/male/back.png')},female:{front:require('../../assets/character-runtime/ironwarden/female/front.png'),back:require('../../assets/character-runtime/ironwarden/female/back.png')}},
BASTION:{male:{front:require('../../assets/character-runtime/bastion/male/front.png'),back:require('../../assets/character-runtime/bastion/male/back.png')},female:{front:require('../../assets/character-runtime/bastion/female/front.png'),back:require('../../assets/character-runtime/bastion/female/back.png')}},
DREADGUARD:{male:{front:require('../../assets/character-runtime/dreadguard/male/front.png'),back:require('../../assets/character-runtime/dreadguard/male/back.png')},female:{front:require('../../assets/character-runtime/dreadguard/female/front.png'),back:require('../../assets/character-runtime/dreadguard/female/back.png')}},
DAWNKEEPER:{male:{front:require('../../assets/character-runtime/dawnkeeper/male/front.png'),back:require('../../assets/character-runtime/dawnkeeper/male/back.png')},female:{front:require('../../assets/character-runtime/dawnkeeper/female/front.png'),back:require('../../assets/character-runtime/dawnkeeper/female/back.png')}},
WAYFINDER:{male:{front:require('../../assets/character-runtime/wayfinder/male/front.png'),back:require('../../assets/character-runtime/wayfinder/male/back.png')},female:{front:require('../../assets/character-runtime/wayfinder/female/front.png'),back:require('../../assets/character-runtime/wayfinder/female/back.png')}},
RAVAGER:{male:{front:require('../../assets/character-runtime/ravager/male/front.png'),back:require('../../assets/character-runtime/ravager/male/back.png')},female:{front:require('../../assets/character-runtime/ravager/female/front.png'),back:require('../../assets/character-runtime/ravager/female/back.png')}},
HEXWEAVER:{male:{front:require('../../assets/character-runtime/hexweaver/male/front.png'),back:require('../../assets/character-runtime/hexweaver/male/back.png')},female:{front:require('../../assets/character-runtime/hexweaver/female/front.png'),back:require('../../assets/character-runtime/hexweaver/female/back.png')}},
KNIFE_DANCER:{male:{front:require('../../assets/character-runtime/knife_dancer/male/front.png'),back:require('../../assets/character-runtime/knife_dancer/male/back.png')},female:{front:require('../../assets/character-runtime/knife_dancer/female/front.png'),back:require('../../assets/character-runtime/knife_dancer/female/back.png')}},
STONECALLER:{male:{front:require('../../assets/character-runtime/stonecaller/male/front.png'),back:require('../../assets/character-runtime/stonecaller/male/back.png')},female:{front:require('../../assets/character-runtime/stonecaller/female/front.png'),back:require('../../assets/character-runtime/stonecaller/female/back.png')}},
};
