import type {ImageSourcePropType} from 'react-native';

const art:Record<string,ImageSourcePropType>={
  'emotes/male_01':require('../features/chat-pilot/assets/emotes/male_01.png'),'emotes/male_02':require('../features/chat-pilot/assets/emotes/male_02.png'),'emotes/male_03':require('../features/chat-pilot/assets/emotes/male_03.png'),'emotes/male_04':require('../features/chat-pilot/assets/emotes/male_04.png'),'emotes/male_05':require('../features/chat-pilot/assets/emotes/male_05.png'),'emotes/male_06':require('../features/chat-pilot/assets/emotes/male_06.png'),'emotes/male_07':require('../features/chat-pilot/assets/emotes/male_07.png'),'emotes/male_08':require('../features/chat-pilot/assets/emotes/male_08.png'),'emotes/male_09':require('../features/chat-pilot/assets/emotes/male_09.png'),'emotes/male_10':require('../features/chat-pilot/assets/emotes/male_10.png'),'emotes/male_11':require('../features/chat-pilot/assets/emotes/male_11.png'),'emotes/male_12':require('../features/chat-pilot/assets/emotes/male_12.png'),'emotes/male_13':require('../features/chat-pilot/assets/emotes/male_13.png'),'emotes/male_14':require('../features/chat-pilot/assets/emotes/male_14.png'),'emotes/male_15':require('../features/chat-pilot/assets/emotes/male_15.png'),'emotes/male_16':require('../features/chat-pilot/assets/emotes/male_16.png'),'emotes/male_17':require('../features/chat-pilot/assets/emotes/male_17.png'),'emotes/male_18':require('../features/chat-pilot/assets/emotes/male_18.png'),'emotes/male_19':require('../features/chat-pilot/assets/emotes/male_19.png'),'emotes/male_20':require('../features/chat-pilot/assets/emotes/male_20.png'),
  'emotes/female_01':require('../features/chat-pilot/assets/emotes/female_01.png'),'emotes/female_02':require('../features/chat-pilot/assets/emotes/female_02.png'),'emotes/female_03':require('../features/chat-pilot/assets/emotes/female_03.png'),'emotes/female_04':require('../features/chat-pilot/assets/emotes/female_04.png'),'emotes/female_05':require('../features/chat-pilot/assets/emotes/female_05.png'),'emotes/female_06':require('../features/chat-pilot/assets/emotes/female_06.png'),'emotes/female_07':require('../features/chat-pilot/assets/emotes/female_07.png'),'emotes/female_08':require('../features/chat-pilot/assets/emotes/female_08.png'),'emotes/female_09':require('../features/chat-pilot/assets/emotes/female_09.png'),'emotes/female_10':require('../features/chat-pilot/assets/emotes/female_10.png'),'emotes/female_11':require('../features/chat-pilot/assets/emotes/female_11.png'),'emotes/female_12':require('../features/chat-pilot/assets/emotes/female_12.png'),'emotes/female_13':require('../features/chat-pilot/assets/emotes/female_13.png'),'emotes/female_14':require('../features/chat-pilot/assets/emotes/female_14.png'),'emotes/female_15':require('../features/chat-pilot/assets/emotes/female_15.png'),'emotes/female_16':require('../features/chat-pilot/assets/emotes/female_16.png'),'emotes/female_17':require('../features/chat-pilot/assets/emotes/female_17.png'),'emotes/female_18':require('../features/chat-pilot/assets/emotes/female_18.png'),'emotes/female_19':require('../features/chat-pilot/assets/emotes/female_19.png'),'emotes/female_20':require('../features/chat-pilot/assets/emotes/female_20.png'),
  'emotes/pet_set_a_01':require('../features/chat-pilot/assets/emotes/pet_set_a_01.png'),'emotes/pet_set_a_02':require('../features/chat-pilot/assets/emotes/pet_set_a_02.png'),'emotes/pet_set_a_03':require('../features/chat-pilot/assets/emotes/pet_set_a_03.png'),'emotes/pet_set_a_04':require('../features/chat-pilot/assets/emotes/pet_set_a_04.png'),'emotes/pet_set_a_05':require('../features/chat-pilot/assets/emotes/pet_set_a_05.png'),'emotes/pet_set_a_06':require('../features/chat-pilot/assets/emotes/pet_set_a_06.png'),'emotes/pet_set_a_07':require('../features/chat-pilot/assets/emotes/pet_set_a_07.png'),'emotes/pet_set_a_08':require('../features/chat-pilot/assets/emotes/pet_set_a_08.png'),'emotes/pet_set_a_09':require('../features/chat-pilot/assets/emotes/pet_set_a_09.png'),'emotes/pet_set_a_10':require('../features/chat-pilot/assets/emotes/pet_set_a_10.png'),'emotes/pet_set_a_11':require('../features/chat-pilot/assets/emotes/pet_set_a_11.png'),'emotes/pet_set_a_12':require('../features/chat-pilot/assets/emotes/pet_set_a_12.png'),
  'emotes/pet_set_b_01':require('../features/chat-pilot/assets/emotes/pet_set_b_01.png'),'emotes/pet_set_b_02':require('../features/chat-pilot/assets/emotes/pet_set_b_02.png'),'emotes/pet_set_b_03':require('../features/chat-pilot/assets/emotes/pet_set_b_03.png'),'emotes/pet_set_b_04':require('../features/chat-pilot/assets/emotes/pet_set_b_04.png'),'emotes/pet_set_b_05':require('../features/chat-pilot/assets/emotes/pet_set_b_05.png'),'emotes/pet_set_b_06':require('../features/chat-pilot/assets/emotes/pet_set_b_06.png'),'emotes/pet_set_b_07':require('../features/chat-pilot/assets/emotes/pet_set_b_07.png'),'emotes/pet_set_b_08':require('../features/chat-pilot/assets/emotes/pet_set_b_08.png'),'emotes/pet_set_b_09':require('../features/chat-pilot/assets/emotes/pet_set_b_09.png'),'emotes/pet_set_b_10':require('../features/chat-pilot/assets/emotes/pet_set_b_10.png'),'emotes/pet_set_b_11':require('../features/chat-pilot/assets/emotes/pet_set_b_11.png'),'emotes/pet_set_b_12':require('../features/chat-pilot/assets/emotes/pet_set_b_12.png'),
};

export function chatEmoteArtwork(id:string):ImageSourcePropType|undefined{
  return art['emotes/'+id];
}
