import type {ImageSourcePropType} from 'react-native';
export type CreationSlice={width:number;height:number;insets:{top:number;right:number;bottom:number;left:number};slices:Record<string,ImageSourcePropType>};
export const creationFrames={
character_card_selected_9slice:{width:144,height:192,insets:{"top":32,"right":32,"bottom":32,"left":32},slices:{top_left:require('../../assets/creation-ui-v2/character_card_selected_9slice/top_left.webp'),top_center:require('../../assets/creation-ui-v2/character_card_selected_9slice/top_center.webp'),top_right:require('../../assets/creation-ui-v2/character_card_selected_9slice/top_right.webp'),middle_left:require('../../assets/creation-ui-v2/character_card_selected_9slice/middle_left.webp'),middle_center:require('../../assets/creation-ui-v2/character_card_selected_9slice/middle_center.webp'),middle_right:require('../../assets/creation-ui-v2/character_card_selected_9slice/middle_right.webp'),bottom_left:require('../../assets/creation-ui-v2/character_card_selected_9slice/bottom_left.webp'),bottom_center:require('../../assets/creation-ui-v2/character_card_selected_9slice/bottom_center.webp'),bottom_right:require('../../assets/creation-ui-v2/character_card_selected_9slice/bottom_right.webp')}},
input_default_9slice:{width:160,height:40,insets:{"top":16,"right":24,"bottom":16,"left":24},slices:{top_left:require('../../assets/creation-ui-v2/input_default_9slice/top_left.webp'),top_center:require('../../assets/creation-ui-v2/input_default_9slice/top_center.webp'),top_right:require('../../assets/creation-ui-v2/input_default_9slice/top_right.webp'),middle_left:require('../../assets/creation-ui-v2/input_default_9slice/middle_left.webp'),middle_center:require('../../assets/creation-ui-v2/input_default_9slice/middle_center.webp'),middle_right:require('../../assets/creation-ui-v2/input_default_9slice/middle_right.webp'),bottom_left:require('../../assets/creation-ui-v2/input_default_9slice/bottom_left.webp'),bottom_center:require('../../assets/creation-ui-v2/input_default_9slice/bottom_center.webp'),bottom_right:require('../../assets/creation-ui-v2/input_default_9slice/bottom_right.webp')}},
input_focused_9slice:{width:160,height:40,insets:{"top":16,"right":24,"bottom":16,"left":24},slices:{top_left:require('../../assets/creation-ui-v2/input_focused_9slice/top_left.webp'),top_center:require('../../assets/creation-ui-v2/input_focused_9slice/top_center.webp'),top_right:require('../../assets/creation-ui-v2/input_focused_9slice/top_right.webp'),middle_left:require('../../assets/creation-ui-v2/input_focused_9slice/middle_left.webp'),middle_center:require('../../assets/creation-ui-v2/input_focused_9slice/middle_center.webp'),middle_right:require('../../assets/creation-ui-v2/input_focused_9slice/middle_right.webp'),bottom_left:require('../../assets/creation-ui-v2/input_focused_9slice/bottom_left.webp'),bottom_center:require('../../assets/creation-ui-v2/input_focused_9slice/bottom_center.webp'),bottom_right:require('../../assets/creation-ui-v2/input_focused_9slice/bottom_right.webp')}},
input_error_9slice:{width:160,height:40,insets:{"top":16,"right":24,"bottom":16,"left":24},slices:{top_left:require('../../assets/creation-ui-v2/input_error_9slice/top_left.webp'),top_center:require('../../assets/creation-ui-v2/input_error_9slice/top_center.webp'),top_right:require('../../assets/creation-ui-v2/input_error_9slice/top_right.webp'),middle_left:require('../../assets/creation-ui-v2/input_error_9slice/middle_left.webp'),middle_center:require('../../assets/creation-ui-v2/input_error_9slice/middle_center.webp'),middle_right:require('../../assets/creation-ui-v2/input_error_9slice/middle_right.webp'),bottom_left:require('../../assets/creation-ui-v2/input_error_9slice/bottom_left.webp'),bottom_center:require('../../assets/creation-ui-v2/input_error_9slice/bottom_center.webp'),bottom_right:require('../../assets/creation-ui-v2/input_error_9slice/bottom_right.webp')}},
input_disabled_9slice:{width:160,height:40,insets:{"top":16,"right":24,"bottom":16,"left":24},slices:{top_left:require('../../assets/creation-ui-v2/input_disabled_9slice/top_left.webp'),top_center:require('../../assets/creation-ui-v2/input_disabled_9slice/top_center.webp'),top_right:require('../../assets/creation-ui-v2/input_disabled_9slice/top_right.webp'),middle_left:require('../../assets/creation-ui-v2/input_disabled_9slice/middle_left.webp'),middle_center:require('../../assets/creation-ui-v2/input_disabled_9slice/middle_center.webp'),middle_right:require('../../assets/creation-ui-v2/input_disabled_9slice/middle_right.webp'),bottom_left:require('../../assets/creation-ui-v2/input_disabled_9slice/bottom_left.webp'),bottom_center:require('../../assets/creation-ui-v2/input_disabled_9slice/bottom_center.webp'),bottom_right:require('../../assets/creation-ui-v2/input_disabled_9slice/bottom_right.webp')}},
} satisfies Record<string,CreationSlice>;
export const creationControls={
carousel_back:require('../../assets/creation-ui-v2/carousel_back.webp'),
carousel_next:require('../../assets/creation-ui-v2/carousel_next.webp'),
carousel_dot_active:require('../../assets/creation-ui-v2/carousel_dot_active.webp'),
carousel_dot_inactive:require('../../assets/creation-ui-v2/carousel_dot_inactive.webp'),
};
