import type {ImageSourcePropType} from 'react-native';
/** Dedicated artwork for the remaining crafting ingredients. */
export const ingredientIcons={
 MOSS_FIBER:require('../../assets/ingredient-icons-v1/moss_fiber.png'),
 OATHGLASS_SHARD:require('../../assets/ingredient-icons-v1/oathglass_shard.png'),
 TORN_OATHCLOTH:require('../../assets/ingredient-icons-v1/torn_oathcloth.png'),
 SUNSTONE_ORE:require('../../assets/ingredient-icons-v1/sunstone_ore.png'),
 AMBERGLASS:require('../../assets/ingredient-icons-v1/amberglass.png'),
 ASTRAL_SCRIPT:require('../../assets/ingredient-icons-v1/astral_script.png'),
 FROSTIRON:require('../../assets/ingredient-icons-v1/frostiron.png'),
 RIMEGLASS:require('../../assets/ingredient-icons-v1/rimeglass.png'),
 CHOIR_BLOOM:require('../../assets/ingredient-icons-v1/choir_bloom.png'),
 WISP_DUST:require('../../assets/ingredient-icons-v1/wisp_dust.png'),
 THORN_SAP:require('../../assets/ingredient-icons-v1/thorn_sap.png'),
 TROLL_HIDE:require('../../assets/ingredient-icons-v1/troll_hide.png'),
 LANTERNSTEEL_SHARD:require('../../assets/ingredient-icons-v1/lanternsteel_shard.png'),
 FALLEN_RIVET:require('../../assets/ingredient-icons-v1/fallen_rivet.png'),
 ECHO_TOUCHED_PELT:require('../../assets/ingredient-icons-v1/echo_touched_pelt.png'),
 BANNER_ASH:require('../../assets/ingredient-icons-v1/banner_ash.png'),
 OATHGLASS_FRAGMENT:require('../../assets/ingredient-icons-v1/oathglass_fragment.png'),
 GLOAM_DUST:require('../../assets/ingredient-icons-v1/gloam_dust.png'),
 RUNEBOUND_CORE:require('../../assets/ingredient-icons-v1/runebound_core.png'),
 ECHO_BAT_WING:require('../../assets/ingredient-icons-v1/echo_bat_wing.png'),
 ROYAL_CHITIN:require('../../assets/ingredient-icons-v1/royal_chitin.png'),
 BOAR_HIDE:require('../../assets/ingredient-icons-v1/boar_hide.png'),
 WOLF_PELT:require('../../assets/ingredient-icons-v1/wolf_pelt.png'),
 IRONWOOD_FANG:require('../../assets/ingredient-icons-v1/ironwood_fang.png'),
 BLACKGLASS_CORE:require('../../assets/ingredient-icons-v1/blackglass_core.png'),
 CINDER_HEART:require('../../assets/ingredient-icons-v1/cinder_heart.png'),
 REGENT_SIGIL:require('../../assets/ingredient-icons-v1/regent_sigil.png'),
 EVENT_BONDBLOOM:require('../../assets/ingredient-icons-v1/event_bondbloom.png'),
 TRAVEL_RATION:require('../../assets/ingredient-icons-v1/travel_ration.png'),
 FALLEN_KNIGHT_SIGIL:require('../../assets/ingredient-icons-v1/fallen_knight_sigil.png'),
 TEMPERING_DUST:require('../../assets/ingredient-icons-v1/tempering_dust.png'),
 TEMPERING_CORE:require('../../assets/ingredient-icons-v1/tempering_core.png'),
} satisfies Record<string,ImageSourcePropType>;
