import type {ImageSourcePropType} from 'react-native';
/** Dedicated artwork for the remaining crafting ingredients. */
export const ingredientIcons={
 MOSS_FIBER:require('../../assets/ingredient-icons-v1/moss_fiber.webp'),
 OATHGLASS_SHARD:require('../../assets/ingredient-icons-v1/oathglass_shard.webp'),
 TORN_OATHCLOTH:require('../../assets/ingredient-icons-v1/torn_oathcloth.webp'),
 SUNSTONE_ORE:require('../../assets/ingredient-icons-v1/sunstone_ore.webp'),
 AMBERGLASS:require('../../assets/ingredient-icons-v1/amberglass.webp'),
 ASTRAL_SCRIPT:require('../../assets/ingredient-icons-v1/astral_script.webp'),
 FROSTIRON:require('../../assets/ingredient-icons-v1/frostiron.webp'),
 RIMEGLASS:require('../../assets/ingredient-icons-v1/rimeglass.webp'),
 CHOIR_BLOOM:require('../../assets/ingredient-icons-v1/choir_bloom.webp'),
 WISP_DUST:require('../../assets/ingredient-icons-v1/wisp_dust.webp'),
 THORN_SAP:require('../../assets/ingredient-icons-v1/thorn_sap.webp'),
 TROLL_HIDE:require('../../assets/ingredient-icons-v1/troll_hide.webp'),
 LANTERNSTEEL_SHARD:require('../../assets/ingredient-icons-v1/lanternsteel_shard.webp'),
 FALLEN_RIVET:require('../../assets/ingredient-icons-v1/fallen_rivet.webp'),
 ECHO_TOUCHED_PELT:require('../../assets/ingredient-icons-v1/echo_touched_pelt.webp'),
 BANNER_ASH:require('../../assets/ingredient-icons-v1/banner_ash.webp'),
 OATHGLASS_FRAGMENT:require('../../assets/ingredient-icons-v1/oathglass_fragment.webp'),
 GLOAM_DUST:require('../../assets/ingredient-icons-v1/gloam_dust.webp'),
 RUNEBOUND_CORE:require('../../assets/ingredient-icons-v1/runebound_core.webp'),
 ECHO_BAT_WING:require('../../assets/ingredient-icons-v1/echo_bat_wing.webp'),
 ROYAL_CHITIN:require('../../assets/ingredient-icons-v1/royal_chitin.webp'),
 BOAR_HIDE:require('../../assets/ingredient-icons-v1/boar_hide.webp'),
 WOLF_PELT:require('../../assets/ingredient-icons-v1/wolf_pelt.webp'),
 IRONWOOD_FANG:require('../../assets/ingredient-icons-v1/ironwood_fang.webp'),
 BLACKGLASS_CORE:require('../../assets/ingredient-icons-v1/blackglass_core.webp'),
 CINDER_HEART:require('../../assets/ingredient-icons-v1/cinder_heart.webp'),
 REGENT_SIGIL:require('../../assets/ingredient-icons-v1/regent_sigil.webp'),
 EVENT_BONDBLOOM:require('../../assets/ingredient-icons-v1/event_bondbloom.webp'),
 TRAVEL_RATION:require('../../assets/ingredient-icons-v1/travel_ration.webp'),
 FALLEN_KNIGHT_SIGIL:require('../../assets/ingredient-icons-v1/fallen_knight_sigil.webp'),
 TEMPERING_DUST:require('../../assets/ingredient-icons-v1/tempering_dust.webp'),
 TEMPERING_CORE:require('../../assets/ingredient-icons-v1/tempering_core.webp'),
} satisfies Record<string,ImageSourcePropType>;
