import {Platform} from 'react-native';

// Use native UI fonts so compact headings stay crisp alongside body text.
export const displayFont=Platform.select({ios:'System',android:'sans-serif',default:'system-ui'});
export const spacing={xs:4,sm:8,md:12,lg:16,xl:24};
export const radii={sm:6,md:10,lg:14};
export const typography={caption:{fontSize:12,lineHeight:16},body:{fontSize:14,lineHeight:20},bodyStrong:{fontSize:14,lineHeight:21,fontWeight:'600' as const},title:{fontFamily:displayFont,fontSize:19,lineHeight:25,fontWeight:'700' as const},hero:{fontFamily:displayFont,fontSize:26,lineHeight:33,fontWeight:'700' as const}};
export const touchTargetMin=44;
export const touchTargetPreferred=48;

export type UiThemeId='obsidian'|'ember'|'ivory';
export type ThemeColors={id:UiThemeId;name:string;dark:boolean;bg:string;panel:string;panel2:string;panelRaised:string;stage:string;line:string;lineStrong:string;text:string;muted:string;disabled:string;accent:string;accentSoft:string;accentSurface:string;selection:string;selectionLine:string;good:string;bad:string;warning:string;info:string;special:string;goodSurface:string;badSurface:string;warningSurface:string;infoSurface:string;specialSurface:string;notification:string;notificationText:string;navBg:string;inputBg:string;overlay:string;primaryButton:string;primaryButtonBorder:string;primaryButtonText:string;secondaryButton:string;secondaryButtonBorder:string;secondaryButtonText:string;dangerButton:string;dangerButtonBorder:string;dangerButtonText:string;};
export const UI_THEMES:Record<UiThemeId,ThemeColors>={
// Near-black canvas, neutral hairlines, restrained silver actions, and no gold tint.
obsidian:{id:'obsidian',name:'Blackout',dark:true,bg:'#030405',panel:'#0B0D0F',panel2:'#111417',panelRaised:'#171A1D',stage:'#080A0C',line:'#252A2F',lineStrong:'#3D4349',text:'#E8ECEF',muted:'#929AA2',disabled:'#686F76',accent:'#D5DADD',accentSoft:'#B7BEC4',accentSurface:'#1B1F23',selection:'#202428',selectionLine:'#B9C0C6',good:'#9BD0AD',bad:'#E58C96',warning:'#D8B476',info:'#A7C2D1',special:'#C3A8E8',goodSurface:'#14251B',badSurface:'#2C1A1F',warningSurface:'#2B2419',infoSurface:'#17242B',specialSurface:'#292139',notification:'#C13F53',notificationText:'#FFFFFF',navBg:'#080A0C',inputBg:'#07090A',overlay:'rgba(0,0,0,.84)',primaryButton:'#1B2024',primaryButtonBorder:'#B9C0C6',primaryButtonText:'#F1F4F5',secondaryButton:'#101214',secondaryButtonBorder:'#3D4349',secondaryButtonText:'#E8ECEF',dangerButton:'#27191D',dangerButtonBorder:'#E58C96',dangerButtonText:'#F6AAB2'},
ember:{id:'ember',name:'Ember',dark:true,bg:'#100909',panel:'#211313',panel2:'#2C1A1A',panelRaised:'#382020',stage:'#1A0E0F',line:'#553232',lineStrong:'#75443C',text:'#FFF3EE',muted:'#C9AAA2',disabled:'#896F6B',accent:'#FF9A72',accentSoft:'#FFC0A4',accentSurface:'#4B251D',selection:'#3D211C',selectionLine:'#FFB08F',good:'#9DE3A8',bad:'#F18B95',warning:'#EAC477',info:'#9EC5D9',special:'#D0A9E8',goodSurface:'#172B1D',badSurface:'#351D22',warningSurface:'#32291C',infoSurface:'#192B33',specialSurface:'#2C2237',notification:'#C13F53',notificationText:'#FFFFFF',navBg:'#160B0C',inputBg:'#0C0707',overlay:'rgba(0,0,0,.8)',primaryButton:'#54291F',primaryButtonBorder:'#FFB08F',primaryButtonText:'#FFE2D2',secondaryButton:'#211313',secondaryButtonBorder:'#75443C',secondaryButtonText:'#FFF3EE',dangerButton:'#2A181B',dangerButtonBorder:'#F18B95',dangerButtonText:'#F6AAB2'},
ivory:{id:'ivory',name:'Paper Mint',dark:false,bg:'#F2F7F4',panel:'#FFFFFF',panel2:'#E5F0EB',panelRaised:'#FBFDFC',stage:'#DCECE4',line:'#B7C9BF',lineStrong:'#6F9C8B',text:'#172722',muted:'#5C7168',disabled:'#8A9C94',accent:'#287967',accentSoft:'#4C9C88',accentSurface:'#D8EEE7',selection:'#D7ECE5',selectionLine:'#287967',good:'#28734D',bad:'#B4232B',warning:'#966B25',info:'#2F7184',special:'#7250A1',goodSurface:'#E3F3E9',badSurface:'#FDE9EA',warningSurface:'#F8EFD9',infoSurface:'#E4F1F4',specialSurface:'#EFE6F7',notification:'#B4232B',notificationText:'#FFFFFF',navBg:'#FFFFFF',inputBg:'#FFFFFF',overlay:'rgba(23,39,34,.32)',primaryButton:'#287967',primaryButtonBorder:'#1F6253',primaryButtonText:'#FFFFFF',secondaryButton:'#FFFFFF',secondaryButtonBorder:'#8EA99D',secondaryButtonText:'#172722',dangerButton:'#FFF0F0',dangerButtonBorder:'#B4232B',dangerButtonText:'#8D151B'}};
export const DEFAULT_UI_THEME:UiThemeId='obsidian';
export function resolveTheme(id?:UiThemeId){return UI_THEMES[id??DEFAULT_UI_THEME]??UI_THEMES.obsidian;}
export function equipmentTheme(C:ThemeColors){return {background:C.bg,stage:C.stage,panel:C.panel,panelRaised:C.panelRaised,line:C.lineStrong,lineStrong:C.lineStrong,gold:C.accent,goldSoft:C.accentSoft,selected:C.selection,selectedLine:C.selectionLine};}
export const C={bg:UI_THEMES.obsidian.bg,panel:UI_THEMES.obsidian.panel,panel2:UI_THEMES.obsidian.panel2,line:UI_THEMES.obsidian.line,text:UI_THEMES.obsidian.text,muted:UI_THEMES.obsidian.muted,disabled:UI_THEMES.obsidian.disabled,accent:UI_THEMES.obsidian.accent,good:UI_THEMES.obsidian.good,bad:UI_THEMES.obsidian.bad,warning:UI_THEMES.obsidian.warning,info:UI_THEMES.obsidian.info};
export const equipmentColors=equipmentTheme(UI_THEMES.obsidian);
