import {Platform} from 'react-native';

// Use native UI fonts so compact headings stay crisp alongside body text.
export const displayFont=Platform.select({ios:'System',android:'sans-serif',default:'system-ui'});
export const spacing={xs:4,sm:8,md:12,lg:16,xl:24};
export const radii={sm:6,md:10,lg:14};
export const typography={caption:{fontSize:12,lineHeight:16},body:{fontSize:14,lineHeight:20},bodyStrong:{fontSize:14,lineHeight:21,fontWeight:'600' as const},title:{fontFamily:displayFont,fontSize:19,lineHeight:25,fontWeight:'700' as const},hero:{fontFamily:displayFont,fontSize:26,lineHeight:33,fontWeight:'700' as const}};
export const touchTargetMin=44;
export const touchTargetPreferred=48;

export type UiThemeId='obsidian'|'ivory';
export type ThemeColors={id:UiThemeId;name:string;dark:boolean;bg:string;panel:string;panel2:string;panelRaised:string;stage:string;line:string;lineStrong:string;text:string;muted:string;disabled:string;accent:string;accentSoft:string;accentSurface:string;selection:string;selectionLine:string;good:string;bad:string;warning:string;info:string;special:string;goodSurface:string;badSurface:string;warningSurface:string;infoSurface:string;specialSurface:string;notification:string;notificationText:string;navBg:string;inputBg:string;overlay:string;primaryButton:string;primaryButtonBorder:string;primaryButtonText:string;secondaryButton:string;secondaryButtonBorder:string;secondaryButtonText:string;dangerButton:string;dangerButtonBorder:string;dangerButtonText:string;};
export const UI_THEMES:Record<UiThemeId,ThemeColors>={
// Charcoal-slate surfaces, sea-glass actions, and warm gold for value/progression.
obsidian:{id:'obsidian',name:'Obsidian Tide',dark:true,bg:'#0B0F14',panel:'#171E28',panel2:'#1E2834',panelRaised:'#24313E',stage:'#0E141C',line:'#303D4C',lineStrong:'#60798C',text:'#EDF2F7',muted:'#AAB7C6',disabled:'#748395',accent:'#E4B876',accentSoft:'#F0D4A9',accentSurface:'#302719',selection:'#183B3C',selectionLine:'#65D6C5',good:'#73D5A0',bad:'#F18B95',warning:'#EAC477',info:'#85BDF1',special:'#C8ABEC',goodSurface:'#152D25',badSurface:'#342029',warningSurface:'#322B1D',infoSurface:'#182D40',specialSurface:'#2B243B',notification:'#C13F53',notificationText:'#FFFFFF',navBg:'#10161E',inputBg:'#0B1119',overlay:'rgba(0,0,0,.78)',primaryButton:'#101F24',primaryButtonBorder:'#65D6C5',primaryButtonText:'#85E5D6',secondaryButton:'#171E28',secondaryButtonBorder:'#718193',secondaryButtonText:'#EDF2F7',dangerButton:'#271A22',dangerButtonBorder:'#F18B95',dangerButtonText:'#F6AAB2'},
ivory:{id:'ivory',name:'Ivory Steel',dark:false,bg:'#F5F2E9',panel:'#FFFFFF',panel2:'#EAE6DC',panelRaised:'#FDFBF5',stage:'#E6E0D3',line:'#9AA4AE',lineStrong:'#9A6B12',text:'#17202A',muted:'#52606D',disabled:'#87919B',accent:'#8A5C0A',accentSoft:'#704C08',accentSurface:'#FFF2D0',selection:'#DCEFF8',selectionLine:'#176B9C',good:'#16784A',bad:'#B4232B',warning:'#8B5A00',info:'#176B9C',special:'#6F3F8F',goodSurface:'#E3F4EA',badSurface:'#FDE9EA',warningSurface:'#FFF1D2',infoSurface:'#E4F1F8',specialSurface:'#F0E4F7',notification:'#B4232B',notificationText:'#FFFFFF',navBg:'#FFFFFF',inputBg:'#FFFFFF',overlay:'rgba(20,28,36,.42)',primaryButton:'#176B9C',primaryButtonBorder:'#0C527B',primaryButtonText:'#FFFFFF',secondaryButton:'#FFFFFF',secondaryButtonBorder:'#75818C',secondaryButtonText:'#17202A',dangerButton:'#FFF0F0',dangerButtonBorder:'#B4232B',dangerButtonText:'#8D151B'}};
export const DEFAULT_UI_THEME:UiThemeId='obsidian';
export function resolveTheme(id?:UiThemeId){return UI_THEMES[id??DEFAULT_UI_THEME]??UI_THEMES.obsidian;}
export function equipmentTheme(C:ThemeColors){return {background:C.bg,stage:C.stage,panel:C.panel,panelRaised:C.panelRaised,line:C.lineStrong,lineStrong:C.lineStrong,gold:C.accent,goldSoft:C.accentSoft,selected:C.selection,selectedLine:C.selectionLine};}
export const C={bg:UI_THEMES.obsidian.bg,panel:UI_THEMES.obsidian.panel,panel2:UI_THEMES.obsidian.panel2,line:UI_THEMES.obsidian.line,text:UI_THEMES.obsidian.text,muted:UI_THEMES.obsidian.muted,disabled:UI_THEMES.obsidian.disabled,accent:UI_THEMES.obsidian.accent,good:UI_THEMES.obsidian.good,bad:UI_THEMES.obsidian.bad,warning:UI_THEMES.obsidian.warning,info:UI_THEMES.obsidian.info};
export const equipmentColors=equipmentTheme(UI_THEMES.obsidian);
