import type {ImageSourcePropType} from 'react-native';
import type {QuickNavDestination} from '../core/quick-navigation';

/** Shared, literal Metro imports. Each destination keeps the same symbol across menus. */
export const uiIcons={
  character:require('../../assets/ui-icons-v2/character.webp'),
  skills:require('../../assets/ui-icons-v2/skills.webp'),
  world:require('../../assets/ui-icons-v2/world.webp'),
  inventory:require('../../assets/ui-icons-v2/inventory.webp'),
  account:require('../../assets/ui-icons-v2/account.webp'),
  settings:require('../../assets/navigation-icons-v4/settings.webp'),
  search:require('../../assets/ui-icons-v2/search.webp'),
  filter:require('../../assets/ui-icons-v2/filter.webp'),
  back:require('../../assets/ui-icons-v2/back.webp'),
  next:require('../../assets/ui-icons-v2/next.webp'),
  events:require('../../assets/ui-icons-v2/events.webp'),
  home:require('../../assets/ui-icons-v2/home.webp'),
  quests:require('../../assets/navigation-icons-v4/quests.webp'),
  friends:require('../../assets/navigation-icons-v4/friends.webp'),
  guild:require('../../assets/navigation-icons-v4/guild.webp'),
  party:require('../../assets/ui-icons-v2/party.webp'),
  companions:require('../../assets/navigation-icons-v4/companions.webp'),
  training:require('../../assets/navigation-icons-v4/training.webp'),
  sanctuary:require('../../assets/navigation-icons-v4/sanctuary.webp'),
  trials:require('../../assets/navigation-icons-v4/trials.webp'),
  calendar:require('../../assets/navigation-icons-v4/calendar.webp'),
  chat:require('../../assets/ui-icons-v2/chat.webp'),
  close:require('../../assets/ui-icons-v2/close.webp'),
  dungeon:require('../../assets/navigation-icons-v4/dungeon.webp'),
  ward:require('../../assets/navigation-icons-v4/sanctuary.webp'),
  rewards:require('../../assets/ui-icons-v2/events.webp'),
} satisfies Record<string,ImageSourcePropType>;
export const uiSmallIcons={
  character:require('../../assets/ui-icons-v2/small/character.webp'),
  skills:require('../../assets/ui-icons-v2/small/skills.webp'),
  world:require('../../assets/ui-icons-v2/small/world.webp'),
  inventory:require('../../assets/ui-icons-v2/small/inventory.webp'),
  account:require('../../assets/ui-icons-v2/small/account.webp'),
  settings:require('../../assets/navigation-icons-v4/settings.webp'),
  search:require('../../assets/ui-icons-v2/small/search.webp'),
  filter:require('../../assets/ui-icons-v2/small/filter.webp'),
  back:require('../../assets/ui-icons-v2/small/back.webp'),
  next:require('../../assets/ui-icons-v2/small/next.webp'),
  events:require('../../assets/ui-icons-v2/small/events.webp'),
  home:require('../../assets/ui-icons-v2/small/home.webp'),
  quests:require('../../assets/navigation-icons-v4/quests.webp'),
  friends:require('../../assets/navigation-icons-v4/friends.webp'),
  guild:require('../../assets/navigation-icons-v4/guild.webp'),
  party:require('../../assets/ui-icons-v2/small/party.webp'),
  companions:require('../../assets/navigation-icons-v4/companions.webp'),
  training:require('../../assets/navigation-icons-v4/training.webp'),
  sanctuary:require('../../assets/navigation-icons-v4/sanctuary.webp'),
  trials:require('../../assets/navigation-icons-v4/trials.webp'),
  calendar:require('../../assets/navigation-icons-v4/calendar.webp'),
  chat:require('../../assets/ui-icons-v2/small/chat.webp'),
  close:require('../../assets/ui-icons-v2/small/close.webp'),
  dungeon:require('../../assets/navigation-icons-v4/dungeon.webp'),
  ward:require('../../assets/navigation-icons-v4/sanctuary.webp'),
  rewards:require('../../assets/ui-icons-v2/small/events.webp'),
} satisfies Record<keyof typeof uiIcons,ImageSourcePropType>;
export type UiIconName=keyof typeof uiIcons;
export const navigationIcons:Record<QuickNavDestination,ImageSourcePropType>={
  Home:uiIcons.home,Skills:uiIcons.skills,Character:uiIcons.character,World:uiIcons.world,
  Inventory:uiIcons.inventory,Account:uiIcons.account,More:uiIcons.account,Quests:uiIcons.quests,Events:uiIcons.events,
  Friends:uiIcons.friends,Guild:uiIcons.guild,Settings:uiIcons.settings,Social:uiIcons.chat,Party:uiIcons.party,Dungeon:require('../../assets/navigation-icons-v4/dungeon.webp'),Companions:uiIcons.companions,Empty:uiIcons.home,
};
