import type {CombatStatsV20,DamagePacketPolicyV20} from './combat-stat-contract-v20';
import {mechanicDamagePolicyV20,validateCombatStatsV20} from './combat-stat-contract-v20';

export type FrostmarchZoneId='ZONE_011'|'ZONE_012'|'ZONE_013'|'ZONE_014'|'ZONE_015';
export type FrostmarchDamageType='physical'|'ice'|'nature'|'arcane'|'shadow'|'holy';
export interface FrostmarchZoneV21{id:FrostmarchZoneId;name:string;levelMin:number;levelMax:number;identity:string;hazards:readonly string[];gathering:readonly string[];}
export interface FrostmarchEnemyV21{id:string;name:string;level:number;zoneId:FrostmarchZoneId;role:string;damageTypes:readonly FrostmarchDamageType[];stats:CombatStatsV20;signatureMechanic:string;mechanicPolicy:DamagePacketPolicyV20;drops:readonly string[];}
export interface FrostmarchBossV21{id:string;name:string;level:number;zoneId:FrostmarchZoneId;damageTypes:readonly FrostmarchDamageType[];stats:CombatStatsV20;phases:readonly {id:string;startsAtHpFraction:number;name:string;mechanics:readonly string[]}[];telegraphedMechanics:readonly string[];rewardHooks:readonly string[];equipmentRewardsFinalized:false;}
export interface FrostmarchResourceV21{id:string;name:string;source:string;skill:string;requiredLevel:number;rarity:'common'|'uncommon'|'rare'|'epic';sinks:readonly string[];}
export interface FrostmarchQuestV21{id:string;order:number;name:string;zoneId:FrostmarchZoneId;level:number;objective:string;unlocks:readonly string[];}
export interface FrostmarchEchoV21{id:string;name:string;zoneIds:readonly FrostmarchZoneId[];effects:Readonly<Record<string,number|boolean|string>>;positiveTradeoff:string;}
export interface FrostmarchRelicV21{id:string;name:string;profileFit:string;mechanic:string;source:string;pity:number;tuningStatus:'mechanic_hook_needs_final_numeric_tuning';}
export interface FrostmarchCollectibleV21{id:string;kind:'pet'|'companion';name:string;rarity:'common'|'rare'|'epic'|'mythic';source:string;identity:string;roleHint?:'damage'|'tank'|'support';tuningStatus:'source_hook_only';}
const stats=(v:CombatStatsV20)=>{const e=validateCombatStatsV20(v);if(e.length)throw new Error(e.join(','));return v;}; const mech=mechanicDamagePolicyV20;
export const FROSTMARCH_ZONES_V21:readonly FrostmarchZoneV21[]=[
{id:'ZONE_011',name:'Thawgate',levelMin:45,levelMax:50,identity:'Fortified northern gate and last dependable shelter before the deep winter.',hazards:['black ice','cold gusts'],gathering:['Frostiron']},
{id:'ZONE_012',name:'Whitepine Reach',levelMin:48,levelMax:56,identity:'Snow forest where false tracks, frozen treants and predators punish careless routing.',hazards:['whiteout trails','root lanes'],gathering:['Whitepine Log','Rime Resin','Wintermint']},
{id:'ZONE_013',name:'Shiverlake',levelMin:52,levelMax:60,identity:'Frozen lake with under-ice ruins, trapped memories and resonant fish.',hazards:['thin ice','under-ice pressure'],gathering:['Icefin','Bellfin Scale','Memory Shards']},
{id:'ZONE_014',name:'Choir Caverns',levelMin:57,levelMax:67,identity:'Singing ice caves where enemy casts harmonize if not interrupted in order.',hazards:['resonance stacks','shatter zones'],gathering:['Rimeglass','Choir Bloom']},
{id:'ZONE_015',name:'Wyrmspine',levelMin:62,levelMax:70,identity:'High mountain lair of the Frost Wyrm and its guardians.',hazards:['breath lines','ice prison','wind shear'],gathering:['Wyrm Scale','Frozen Heart']},] as const;
const base=(hp:number,p:number,a:number,arm:number,ward:number,ev:number,crit:number,cd:number,haste:number,ten:number,heal=0,shield=0)=>stats({maxHp:hp,power:p,accuracy:a,armor:arm,ward,evasion:ev,critChance:crit,critDamage:cd,haste,tenacity:ten,healingPower:heal,shieldingPower:shield});
export const FROSTMARCH_ENEMIES_V21:readonly FrostmarchEnemyV21[]=[
{id:'FRMON_001',name:'Snowhorn Hare',level:45,zoneId:'ZONE_011',role:'skirmisher',damageTypes:['physical'],stats:base(1250,96,108,58,42,34,.09,1.55,.10,.18),signatureMechanic:'Evasion Hop: sidesteps a marked strike and gains brief Evasion.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['snowhorn_fur']},
{id:'FRMON_002',name:'Rime Wolf',level:47,zoneId:'ZONE_011',role:'striker',damageTypes:['ice'],stats:base(1420,103,112,64,52,26,.11,1.6,.08,.22),signatureMechanic:'Chill Bite: repeated basics build a capped slow stack.',mechanicPolicy:mech({telegraphed:false,avoidable:false,basicAttack:true}),drops:['rime_fur','fang']},
{id:'FRMON_003',name:'Frostbound Raider',level:50,zoneId:'ZONE_011',role:'bruiser',damageTypes:['physical'],stats:base(1780,110,110,82,56,14,.08,1.55,.03,.28),signatureMechanic:'Shield Break: telegraphed overhead hit reduces Armor briefly if it lands.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['FRRES_003','frostcloth']},
{id:'FRMON_004',name:'Whitepine Treant',level:50,zoneId:'ZONE_012',role:'tank',damageTypes:['nature','ice'],stats:base(2250,104,102,104,78,6,.04,1.45,-.04,.36,0,38),signatureMechanic:'Bark Shield: break the shield before the root field closes.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['FRRES_001','FRRES_002']},
{id:'FRMON_005',name:'Needlefang Lynx',level:52,zoneId:'ZONE_012',role:'assassin',damageTypes:['physical'],stats:base(1500,119,120,66,54,38,.15,1.7,.12,.24),signatureMechanic:'Ambush Crit: warning tell before an empowered strike; the telegraph itself cannot randomly crit.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['needlefang_pelt']},
{id:'FRMON_006',name:'Rimecap Spirit',level:54,zoneId:'ZONE_012',role:'caster',damageTypes:['ice'],stats:base(1580,122,116,48,92,24,.08,1.6,.09,.28),signatureMechanic:'Slow Field: places a readable frost patch that reduces Haste.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['FRRES_005','rime_essence']},
{id:'FRMON_007',name:'Winter Elk',level:56,zoneId:'ZONE_012',role:'bruiser',damageTypes:['physical'],stats:base(2150,126,114,86,64,16,.08,1.55,.02,.32),signatureMechanic:'Charge Lane: commits to a straight lane and is vulnerable after missing.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['winter_antler','hide']},
{id:'FRMON_008',name:'Underice Serpent',level:54,zoneId:'ZONE_013',role:'hunter',damageTypes:['ice'],stats:base(1700,124,122,64,88,30,.10,1.6,.10,.30),signatureMechanic:'Submerge Strike: disappears under ice, then erupts from a marked crack.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['serpent_scale','FRRES_007']},
{id:'FRMON_009',name:'Bellfin',level:57,zoneId:'ZONE_013',role:'support',damageTypes:['arcane','ice'],stats:base(1650,112,118,58,98,24,.05,1.45,.10,.34,58,24),signatureMechanic:'Resonance Buff: empowers nearby monsters unless interrupted.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['FRRES_008']},
{id:'FRMON_010',name:'Frozen Memory',level:60,zoneId:'ZONE_013',role:'disruptor',damageTypes:['shadow','ice'],stats:base(1820,136,128,62,108,30,.09,1.65,.08,.38),signatureMechanic:'Memory Echo: copies the last minor ability used against it at reduced strength.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['memory_shard']},
{id:'FRMON_011',name:'Choir Acolyte',level:59,zoneId:'ZONE_014',role:'caster',damageTypes:['holy','ice'],stats:base(1780,139,130,64,112,18,.08,1.6,.09,.38),signatureMechanic:'Interruptible Hymn: completing the cast adds a resonance stack.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['choir_crystal']},
{id:'FRMON_012',name:'Icebound Golem',level:62,zoneId:'ZONE_014',role:'tank',damageTypes:['ice'],stats:base(2920,132,118,134,118,4,.04,1.45,-.03,.48,0,58),signatureMechanic:'Breakable Armour: armor plates expose a damage window when shattered.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['resonant_ice','FRRES_004']},
{id:'FRMON_013',name:'Hollow Chorister',level:64,zoneId:'ZONE_014',role:'support',damageTypes:['shadow'],stats:base(2100,126,126,72,122,16,.05,1.5,.08,.44,76,34),signatureMechanic:'Channel Heal: heals the lowest-health ally and can be interrupted.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['relic_fragment']},
{id:'FRMON_014',name:'Rimeglass Bat',level:66,zoneId:'ZONE_014',role:'swarm',damageTypes:['ice'],stats:base(1850,148,136,66,102,42,.10,1.6,.16,.34),signatureMechanic:'Shatter Stacks: rapid hits build stacks that detonate at a visible cap.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['FRRES_004']},
{id:'FRMON_015',name:'Wyrm Broodling',level:67,zoneId:'ZONE_015',role:'striker',damageTypes:['ice'],stats:base(2380,156,140,94,118,22,.10,1.65,.08,.46),signatureMechanic:'Breath Cone: committed cone with a safe flank.',mechanicPolicy:mech({telegraphed:true,avoidable:true}),drops:['FRRES_009']},
{id:'FRMON_016',name:'Frostscale Guardian',level:69,zoneId:'ZONE_015',role:'guardian',damageTypes:['ice'],stats:base(3320,151,132,148,132,8,.05,1.5,.01,.56,0,72),signatureMechanic:'Protective Wing: redirects damage from a nearby Broodling until the guard is broken.',mechanicPolicy:mech({telegraphed:true,avoidable:false}),drops:['FRRES_009','frost_core']},] as const;
export const FROSTMARCH_BOSSES_V21:readonly FrostmarchBossV21[]=[
{id:'FROBOSS_DUN_001',name:'Needlefang Matriarch',level:52,zoneId:'ZONE_012',damageTypes:['physical','ice'],stats:base(18500,154,142,126,94,30,.10,1.65,.10,.55),phases:[{id:'trail',startsAtHpFraction:1,name:'False Trails',mechanics:['track the true scent','ambush lanes']},{id:'pack',startsAtHpFraction:.62,name:'Pack Call',mechanics:['lynx adds','protect support']},{id:'whiteout',startsAtHpFraction:.28,name:'Whiteout Hunt',mechanics:['limited vision','committed pounce']}],telegraphedMechanics:['Matriarch Pounce','Raking Trail','Whiteout Ambush'],rewardHooks:['whitepine_cache','companion_progress_UNIT_017','generic_equipment_reward_hook'],equipmentRewardsFinalized:false},
{id:'BOSS_EXP_BELLBEAST',name:'The Bellbeast Below',level:58,zoneId:'ZONE_013',damageTypes:['ice','arcane'],stats:base(23800,171,148,118,146,16,.07,1.6,.06,.60,0,58),phases:[{id:'dive',startsAtHpFraction:1,name:'Under the Ice',mechanics:['oxygen route','crack tells']},{id:'bell',startsAtHpFraction:.64,name:'Buried Bell',mechanics:['resonance pulses','Bellfin adds']},{id:'breakthrough',startsAtHpFraction:.30,name:'Breakthrough',mechanics:['ice collapse','safe plates']}],telegraphedMechanics:['Bell Pulse','Ice Break','Submerge Rush'],rewardHooks:['FRRES_007','FRRES_008','relic_pity_frostmarch','generic_equipment_reward_hook'],equipmentRewardsFinalized:false},
{id:'BOSS_EXP_CANTOR',name:'The Hollow Cantor',level:64,zoneId:'ZONE_014',damageTypes:['holy','shadow','ice'],stats:base(30600,191,154,132,172,10,.07,1.65,.08,.65,82,50),phases:[{id:'verse',startsAtHpFraction:1,name:'First Verse',mechanics:['ordered interrupts','choir stacks']},{id:'harmony',startsAtHpFraction:.66,name:'False Harmony',mechanics:['three voices','support cleanse']},{id:'silence',startsAtHpFraction:.28,name:'Final Silence',mechanics:['rapid cast order','shatter floor']}],telegraphedMechanics:['Hollow Refrain','Shatter Note','Final Cadence'],rewardHooks:['FRRES_004','FRRES_006','choir_cosmetic_cache','generic_equipment_reward_hook'],equipmentRewardsFinalized:false},
{id:'BOSS_003',name:'Frost Wyrm',level:70,zoneId:'ZONE_015',damageTypes:['ice','physical'],stats:base(42000,225,166,190,168,12,.08,1.65,.04,.72,0,90),phases:[{id:'ground',startsAtHpFraction:1,name:'Frozen Roost',mechanics:['breath lines','tail lanes']},{id:'air',startsAtHpFraction:.68,name:'Airborne Hunt',mechanics:['dive markers','ice prisons']},{id:'storm',startsAtHpFraction:.32,name:'Wyrmstorm',mechanics:['moving safe lane','prison break','final breath']}],telegraphedMechanics:['Frost Breath','Wyrm Dive','Ice Prison Collapse'],rewardHooks:['FRRES_010','frostmarch_regional_chest','ashlands_unlock','generic_equipment_reward_hook'],equipmentRewardsFinalized:false},] as const;
export const FROSTMARCH_RESOURCES_V21:readonly FrostmarchResourceV21[]=[
{id:'FRRES_001',name:'Whitepine Log',source:'Whitepine Reach',skill:'Woodcutting',requiredLevel:48,rarity:'common',sinks:['future equipment','housing cosmetics','Guild Projects']},{id:'FRRES_002',name:'Rime Resin',source:'Whitepine Reach',skill:'Woodcutting',requiredLevel:53,rarity:'uncommon',sinks:['Enchanting','Alchemy','future staves']},{id:'FRRES_003',name:'Frostiron',source:'Thawgate',skill:'Mining',requiredLevel:46,rarity:'common',sinks:['future equipment','tools','upgrades']},{id:'FRRES_004',name:'Rimeglass',source:'Choir Caverns',skill:'Mining',requiredLevel:60,rarity:'rare',sinks:['gems','relics','future weapons']},{id:'FRRES_005',name:'Wintermint',source:'Whitepine Reach',skill:'Herbalism',requiredLevel:49,rarity:'common',sinks:['food','cleanse potion','buffs']},{id:'FRRES_006',name:'Choir Bloom',source:'Choir Caverns',skill:'Herbalism',requiredLevel:61,rarity:'rare',sinks:['resource potions','relic craft']},{id:'FRRES_007',name:'Icefin',source:'Shiverlake',skill:'Fishing',requiredLevel:52,rarity:'common',sinks:['food','Pet path']},{id:'FRRES_008',name:'Bellfin Scale',source:'Shiverlake',skill:'Fishing',requiredLevel:57,rarity:'rare',sinks:['future support equipment','Collection']},{id:'FRRES_009',name:'Wyrm Scale',source:'Wyrmspine',skill:'Combat',requiredLevel:67,rarity:'rare',sinks:['future equipment','regional progression']},{id:'FRRES_010',name:'Frozen Heart',source:'Frost Wyrm',skill:'Boss',requiredLevel:70,rarity:'epic',sinks:['relic fallback','Ashlands preparation','cosmetics']},] as const;
export const FROSTMARCH_QUESTLINE_V21:readonly FrostmarchQuestV21[]=[
{id:'FRQ_001',order:1,name:'Thawgate',zoneId:'ZONE_011',level:45,objective:'Reach the fortress and restore the northern supply line.',unlocks:['Frostmarch core activities','ZONE_011']},{id:'FRQ_002',order:2,name:'Tracks in White',zoneId:'ZONE_012',level:49,objective:'Follow hunters lost among impossible circular tracks.',unlocks:['ZONE_012','COP_007']},{id:'FRQ_003',order:3,name:'The Forest Holds Its Breath',zoneId:'ZONE_012',level:53,objective:'Investigate treants frozen while still alive.',unlocks:['Frostmarch Echoes']},{id:'FRQ_004',order:4,name:'Below Shiverlake',zoneId:'ZONE_013',level:55,objective:'Recover memories trapped beneath clear ice.',unlocks:['under-ice gathering']},{id:'FRQ_005',order:5,name:'The Bell Beneath',zoneId:'ZONE_013',level:58,objective:'Trace the buried bell resonating beneath Shiverlake.',unlocks:['COP_008','ZONE_014']},{id:'FRQ_006',order:6,name:'A Choir Without Breath',zoneId:'ZONE_014',level:61,objective:'Discover how the Hollow Choir sustains the endless winter.',unlocks:['COP_009']},{id:'FRQ_007',order:7,name:'Break the Hymn',zoneId:'ZONE_014',level:65,objective:'Silence three ritual chambers in the correct sequence.',unlocks:['ZONE_015']},{id:'FRQ_008',order:8,name:'Wings over Wyrmspine',zoneId:'ZONE_015',level:67,objective:'Survive the Wyrmspine approach and break the guardians.',unlocks:['BOSS_003 access']},{id:'FRQ_009',order:9,name:'The Frost Wyrm',zoneId:'ZONE_015',level:70,objective:'Defeat the Frost Wyrm.',unlocks:['combat/skill cap raise','Ashlands access']},{id:'FRQ_010',order:10,name:'Black Snow',zoneId:'ZONE_011',level:70,objective:'Investigate ash beginning to fall over Thawgate.',unlocks:['Ashlands transition']},] as const;
export const FROSTMARCH_ECHOES_V21:readonly FrostmarchEchoV21[]=[
{id:'FRECHO_001',name:'Whiteout Memory',zoneIds:['ZONE_012'],effects:{enemyEvasionAdditive:.03,trackingRewardMultiplier:1.08},positiveTradeoff:'Harder target tracking, better hunting/exploration rewards.'},
{id:'FRECHO_002',name:'Bell Resonance',zoneIds:['ZONE_013'],effects:{supportEnemyHasteAdditive:.04,rareFishRelativeMultiplier:1.06},positiveTradeoff:'Faster resonance pressure with improved rare fishing.'},
{id:'FRECHO_003',name:'Choir Refrain',zoneIds:['ZONE_014'],effects:{interruptWindowMultiplier:.90,relicPityProgressMultiplier:1.10},positiveTradeoff:'Tighter interrupt timing with faster relic pity progress.'},
{id:'FRECHO_004',name:"Wyrm's Wake",zoneIds:['ZONE_015'],effects:{eliteChanceAdditive:.05,enemyPowerAdditive:.04},positiveTradeoff:'More dangerous Wyrmspine activity with more elite opportunities.'},] as const;
export const FROSTMARCH_RELICS_V21:readonly FrostmarchRelicV21[]=[
{id:'FROREL_001',name:'Bellglass Chime',profileFit:'Support / rhythm',mechanic:'Interrupting or cleansing a major effect grants a short capped Haste pulse.',source:'Shiverlake / Bellbeast',pity:40,tuningStatus:'mechanic_hook_needs_final_numeric_tuning'},
{id:'FROREL_002',name:'Whitepine Heartwood',profileFit:'Tank / sustain',mechanic:'After receiving a large hit, gain a short Ward/Armor sidegrade with internal cooldown.',source:'Whitepine Hunt',pity:35,tuningStatus:'mechanic_hook_needs_final_numeric_tuning'},
{id:'FROREL_003',name:'Memory Under Ice',profileFit:'Utility / timing',mechanic:'Correctly resolving a telegraph modestly refunds resource on an internal cooldown.',source:'Shiverlake Echo',pity:40,tuningStatus:'mechanic_hook_needs_final_numeric_tuning'},
{id:'FROREL_004',name:'Wyrmheart Shard',profileFit:'Any / boss mastery',mechanic:'After breaking an Ice Prison or similar control mechanic, gain brief Tenacity.',source:'Frost Wyrm',pity:50,tuningStatus:'mechanic_hook_needs_final_numeric_tuning'},] as const;
export const FROSTMARCH_COLLECTIBLES_V21:readonly FrostmarchCollectibleV21[]=[
{id:'PET_024',kind:'pet',name:'Snowpuff Hare',rarity:'common',source:'Snowhorn mastery',identity:'Hunting utility collectible.',tuningStatus:'source_hook_only'},{id:'PET_025',kind:'pet',name:'Rimecap',rarity:'rare',source:'Rare Wintermint/Rimecap gathering',identity:'Herbalism utility collectible.',tuningStatus:'source_hook_only'},{id:'PET_026',kind:'pet',name:'Bellfin Fry',rarity:'rare',source:'Shiverlake rare fishing',identity:'Fishing utility collectible.',tuningStatus:'source_hook_only'},{id:'PET_027',kind:'pet',name:'Choir Pebble',rarity:'epic',source:'Choir Caverns meta',identity:'Enchanting utility collectible.',tuningStatus:'source_hook_only'},{id:'PET_028',kind:'pet',name:'Wyrmling Flake',rarity:'mythic',source:'Frost Wyrm prestige',identity:'Lore utility collectible.',tuningStatus:'source_hook_only'},{id:'UNIT_017',kind:'companion',name:'Rime Wolf Pup',rarity:'rare',source:'Rime Wolf mastery 20',identity:'Striker / chill setup.',roleHint:'damage',tuningStatus:'source_hook_only'},{id:'UNIT_018',kind:'companion',name:'Bell Sprite',rarity:'epic',source:'Shiverlake achievements',identity:'Support / cooldown rhythm.',roleHint:'support',tuningStatus:'source_hook_only'},{id:'UNIT_019',kind:'companion',name:'Choir Golem',rarity:'epic',source:'Choir Caverns 20 clears',identity:'Guardian / armour break.',roleHint:'tank',tuningStatus:'source_hook_only'},{id:'UNIT_020',kind:'companion',name:'Wyrm Echo',rarity:'mythic',source:'Frostmarch meta',identity:'Champion / telegraph reward sidegrade.',tuningStatus:'source_hook_only'},] as const;
export const FROSTMARCH_EQUIPMENT_POLICY_V21={equipmentSetsAuthored:false,regionalWeaponsAuthored:false,regionalArmorAuthored:false,existingSpreadsheetFrostmarchGearStatus:'draft_do_not_implement',reason:'Regional equipment remains deferred until the richer-stat equipment budget/rework pass.'} as const;
for(const e of FROSTMARCH_ENEMIES_V21){if(validateCombatStatsV20(e.stats).length)throw new Error(`bad:${e.id}`);} for(const b of FROSTMARCH_BOSSES_V21){if(validateCombatStatsV20(b.stats).length)throw new Error(`bad:${b.id}`);}
