"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ArenaScreen = ArenaScreen;
const react_native_1 = require("react-native");
const GameButton_1 = require("../components/GameButton");
const Panel_1 = require("../components/Panel");
const classes_1 = require("../content/classes");
const account_roster_1 = require("../core/account-roster");
const arena_squad_1 = require("../core/arena-squad");
const theme_1 = require("../theme/theme");
function ArenaScreen({ state, onChange }) {
    const entries = (0, account_roster_1.accountCharacters)(state), status = (0, arena_squad_1.arenaSquadStatus)(state);
    return <react_native_1.ScrollView contentContainerStyle={s.root}>
    <react_native_1.Text style={s.kicker}>THREE-CHARACTER MODE</react_native_1.Text><react_native_1.Text style={s.heading}>Arena</react_native_1.Text>
    <Panel_1.Panel><react_native_1.Text style={s.title}>Build your squad</react_native_1.Text><react_native_1.Text style={s.copy}>Choose three characters from this account for Front, Middle, and Back. Any role mix is valid. Ranked matches remain disabled until the authenticated Arena service is enabled.</react_native_1.Text><react_native_1.Text style={status.ready ? s.good : s.warning}>{status.ready ? 'Formation ready' : status.reason}</react_native_1.Text><react_native_1.Text style={s.note}>{status.selectedCount}/3 selected · minimum level {arena_squad_1.ARENA_MIN_LEVEL}</react_native_1.Text></Panel_1.Panel>
    {arena_squad_1.ARENA_POSITIONS.map((position, index) => { const selected = entries.find(entry => entry.character.id === status.ids[index]); return <Panel_1.Panel key={position}><react_native_1.Text style={s.position}>{index + 1} · {position.toUpperCase()}</react_native_1.Text>{selected ? <><react_native_1.Text style={s.member}>{selected.character.name}</react_native_1.Text><react_native_1.Text style={s.note}>{classes_1.CLASSES.find(def => def.id === selected.character.classId)?.name} · Level {selected.character.level}</react_native_1.Text><GameButton_1.GameButton title="Clear slot" tone="secondary" onPress={() => onChange((0, arena_squad_1.setArenaSquadSlot)(state, index))}/></> : <react_native_1.Text style={s.note}>No character selected.</react_native_1.Text>}<react_native_1.View style={s.choices}>{entries.map(entry => { const used = status.ids.includes(entry.character.id) && entry.character.id !== selected?.character.id; const low = entry.character.level < arena_squad_1.ARENA_MIN_LEVEL; return <GameButton_1.GameButton key={entry.character.id} title={`${entry.character.name} · Lv ${entry.character.level}`} tone={entry.character.id === selected?.character.id ? 'primary' : 'secondary'} disabled={used || low} onPress={() => onChange((0, arena_squad_1.setArenaSquadSlot)(state, index, entry.character.id))}/>; })}</react_native_1.View></Panel_1.Panel>; })}
    <Panel_1.Panel><react_native_1.Text style={s.title}>Arena integrity</react_native_1.Text><react_native_1.Text style={s.copy}>The server will freeze and verify each character’s loadout before a ranked duel. Client saves only the account-owned slot selection.</react_native_1.Text></Panel_1.Panel>
  </react_native_1.ScrollView>;
}
const s = react_native_1.StyleSheet.create({ root: { padding: theme_1.spacing.lg, gap: theme_1.spacing.md }, kicker: { ...theme_1.typography.caption, color: theme_1.C.accent, fontWeight: '900', letterSpacing: 1 }, heading: { ...theme_1.typography.hero, color: theme_1.C.text }, title: { ...theme_1.typography.title, color: theme_1.C.text }, member: { ...theme_1.typography.bodyStrong, color: theme_1.C.text, marginTop: theme_1.spacing.xs }, copy: { ...theme_1.typography.body, color: theme_1.C.muted, lineHeight: 21 }, note: { ...theme_1.typography.caption, color: theme_1.C.muted, marginTop: theme_1.spacing.xs }, warning: { ...theme_1.typography.bodyStrong, color: theme_1.C.warning, marginTop: theme_1.spacing.sm }, good: { ...theme_1.typography.bodyStrong, color: theme_1.C.good, marginTop: theme_1.spacing.sm }, position: { ...theme_1.typography.caption, color: theme_1.C.accent, fontWeight: '900' }, choices: { gap: theme_1.spacing.xs, marginTop: theme_1.spacing.sm } });
