"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.InventoryScreen = InventoryScreen;
const SearchField_1 = require("../components/SearchField");
const react_1 = require("react");
const react_native_1 = require("react-native");
const items_1 = require("../content/items");
const inventory_view_1 = require("../core/inventory-view");
const game_1 = require("../core/game");
const ItemCard_1 = require("../components/ItemCard");
const ConfirmModal_1 = require("../components/ConfirmModal");
const EmptyState_1 = require("../components/EmptyState");
const GameButton_1 = require("../components/GameButton");
const Panel_1 = require("../components/Panel");
const theme_1 = require("../theme/theme");
const EquipmentPreview_1 = require("../components/EquipmentPreview");
const equipment_preview_1 = require("../core/equipment-preview");
const item_rarity_1 = require("../core/item-rarity");
const number_format_1 = require("../core/number-format");
const i18n_1 = require("../i18n");
const equipment_enhancement_1 = require("../core/equipment-enhancement");
function InventoryScreen({ state, onEquip, onFood, onEat, onSell, onSalvage, onDeposit, onDepositMaterials, onUpgradeStorage, onWithdraw, onOverflow }) {
    const [pending, setPending] = (0, react_1.useState)(null), [location, setLocation] = (0, react_1.useState)('inventory');
    const [query, setQuery] = (0, react_1.useState)(''), [filter, setFilter] = (0, react_1.useState)('all'), [sort, setSort] = (0, react_1.useState)('name');
    const [quantity, setQuantity] = (0, react_1.useState)(1);
    const [error, setError] = (0, react_1.useState)('');
    const [expandedItem, setExpandedItem] = (0, react_1.useState)(null);
    const [previewId, setPreviewId] = (0, react_1.useState)(null);
    const [showStorage, setShowStorage] = (0, react_1.useState)(false), [showFilters, setShowFilters] = (0, react_1.useState)(false);
    const run = (action) => { try {
        action();
        setError('');
    }
    catch (e) {
        setError(e instanceof Error ? e.message : 'Action failed. Please try again.');
    } };
    const confirm = () => { if (!pending)
        return; run(() => pending.kind === 'deposit' ? onDeposit(pending.item.id, pending.quantity) : pending.kind === 'sell' ? onSell(pending.item.id) : onSalvage(pending.item.id)); setPending(null); };
    const stacks = (0, inventory_view_1.visibleStacks)(state[location].stacks, query, filter, sort);
    const renderStack = (stack) => {
        const item = (0, items_1.itemDef)(stack.itemId), equippedId = item.slot ? state.character?.equipment[item.slot] : undefined, carried = location === 'inventory';
        const amount = (0, inventory_view_1.transferAmount)(stack.quantity, quantity), selectedFood = state.character?.equippedFoodId === item.id, enhancement = item.type === 'gear' ? (0, equipment_enhancement_1.gearEnhancement)(state, item.id) : undefined, enhancementProtected = item.type === 'gear' && (0, equipment_enhancement_1.hasEnhancement)(state, item.id);
        return <ItemCard_1.ItemCard expanded={expandedItem === location + ':' + item.id} onToggle={() => setExpandedItem(value => value === location + ':' + item.id ? null : location + ':' + item.id)} key={`${location}:${item.id}`} item={item} quantity={stack.quantity} equipped={equippedId ? (0, items_1.itemDef)(equippedId) : undefined} upgradeRank={enhancement?.rank} socketed={enhancement?.gemIds.length} socketCapacity={item.type === 'gear' ? (0, equipment_enhancement_1.gemSocketCapacity)(item.id) : 0} enhancementProtected={enhancementProtected} displayStats={item.type === 'gear' ? (0, equipment_enhancement_1.enhancedGearStats)(state, item.id) : undefined} equippedDisplayStats={equippedId ? (0, equipment_enhancement_1.enhancedGearStats)(state, equippedId) : undefined} selectedFood={selectedFood} healAmount={(0, inventory_view_1.recoveryAmount)(state, item.id)} transferQuantity={amount} transferIssue={(0, inventory_view_1.transferError)(state, item.id, amount, location)} numberMode={state.settings.numberMode} onPreview={item.type === 'gear' ? () => run(() => { (0, equipment_preview_1.previewEquipment)(state, item.id); setPreviewId(item.id); }) : undefined} onEquip={carried && item.type === 'gear' ? () => run(() => onEquip(item.id)) : undefined} onSelectFood={carried && item.type === 'food' ? () => run(() => onFood(item.id)) : undefined} onEat={carried && item.type === 'food' ? () => run(() => onEat(item.id)) : undefined} onSell={carried && item.value > 0 && !enhancementProtected ? () => setPending({ kind: 'sell', item, quantity: 1 }) : undefined} onSalvage={carried && item.salvage && !enhancementProtected ? () => setPending({ kind: 'salvage', item, quantity: 1 }) : undefined} onDeposit={carried ? () => selectedFood ? setPending({ kind: 'deposit', item, quantity: amount }) : run(() => onDeposit(item.id, amount)) : undefined} onWithdraw={!carried ? () => run(() => onWithdraw(item.id, amount)) : undefined}/>;
    };
    const foodWarning = pending?.item.id === state.character?.equippedFoodId ? ' This is your selected auto-eat food. Only food carried in Inventory can be consumed in combat.' : '';
    const message = pending?.kind === 'sell' ? `Sell 1 for ${pending.item.value} gold. This cannot be undone.${foodWarning}` : pending?.kind === 'deposit' ? `Move ${pending.quantity}× ${pending.item.name} to Bank?${foodWarning}` : pending?.item.salvage ? `Destroy 1 item for ${pending.item.salvage.quantity}× ${(0, items_1.itemDef)(pending.item.salvage.itemId).name}.` : '';
    const remaining = (0, game_1.claimOverflowToBank)(state).overflow.stacks.reduce((sum, item) => sum + item.quantity, 0);
    const overflowCount = state.overflow.stacks.reduce((sum, item) => sum + item.quantity, 0);
    const inventoryUpgrade = (0, game_1.storageUpgradePreview)(state, 'inventory'), bankUpgrade = (0, game_1.storageUpgradePreview)(state, 'bank');
    return <><EquipmentPreview_1.EquipmentPreview state={state} itemId={previewId} onClose={() => setPreviewId(null)}/><react_native_1.ScrollView contentContainerStyle={s.root} keyboardShouldPersistTaps="handled">
    <react_native_1.Text style={s.h}>Inventory</react_native_1.Text>
    <react_native_1.View style={s.recovery}><react_native_1.Text style={s.label}>RECOVERY</react_native_1.Text><react_native_1.Text style={s.sub}>Health {state.character.currentHp}/{(0, game_1.effectiveStats)(state).hp} · Auto-eat: {state.character?.equippedFoodId ? (0, items_1.itemDef)(state.character.equippedFoodId).name : 'None'}</react_native_1.Text><react_native_1.Text style={s.sub}>Carried auto-eat portions: {state.inventory.stacks.find(item => item.itemId === state.character?.equippedFoodId)?.quantity ?? 0}</react_native_1.Text></react_native_1.View>
    <react_native_1.View style={s.row}>{['inventory', 'bank'].map(value => <react_native_1.View style={s.flex} key={value}><GameButton_1.GameButton title={`${value === 'inventory' ? 'Inventory' : 'Bank'} ${(0, game_1.usedSlots)(state[value].stacks)}/${state[value].capacity}`} selected={location === value} tone={location === value ? 'primary' : 'secondary'} onPress={() => setLocation(value)}/></react_native_1.View>)}</react_native_1.View>
    <react_native_1.Pressable accessibilityRole="button" accessibilityState={{ expanded: showStorage }} onPress={() => setShowStorage(value => !value)} style={s.disclosure}><react_native_1.View style={s.flex}><react_native_1.Text style={s.disclosureTitle}>STORAGE MANAGEMENT</react_native_1.Text><react_native_1.Text style={s.sub}>Bulk deposit and capacity upgrades</react_native_1.Text></react_native_1.View><react_native_1.Text style={s.disclosureMark}>{showStorage ? '−' : '+'}</react_native_1.Text></react_native_1.Pressable>
    {showStorage && <Panel_1.Panel><react_native_1.Text style={s.sub}>Inventory travels with this character. Bank storage is shared by every character on the account.</react_native_1.Text>{location === 'inventory' && <GameButton_1.GameButton title="Deposit all materials" tone="secondary" disabled={!state.inventory.stacks.some(entry => (0, items_1.itemDef)(entry.itemId).type === 'material')} onPress={() => run(onDepositMaterials)}/>}<react_native_1.View style={s.row}><react_native_1.View style={s.flex}><react_native_1.Text style={s.upgradeLabel}>INVENTORY · {state.inventory.capacity} SLOTS</react_native_1.Text><GameButton_1.GameButton title={inventoryUpgrade ? `Upgrade to ${inventoryUpgrade.capacity} · ${(0, number_format_1.formatGameNumber)(inventoryUpgrade.cost, state.settings.numberMode)}g` : 'Inventory maxed'} disabled={!inventoryUpgrade} tone="secondary" onPress={() => run(() => onUpgradeStorage('inventory'))}/></react_native_1.View><react_native_1.View style={s.flex}><react_native_1.Text style={s.upgradeLabel}>BANK · {state.bank.capacity} SLOTS</react_native_1.Text><GameButton_1.GameButton title={bankUpgrade ? `Upgrade to ${bankUpgrade.capacity} · ${(0, number_format_1.formatGameNumber)(bankUpgrade.cost, state.settings.numberMode)}g` : 'Bank maxed'} disabled={!bankUpgrade} tone="secondary" onPress={() => run(() => onUpgradeStorage('bank'))}/></react_native_1.View></react_native_1.View></Panel_1.Panel>}
    <react_native_1.Text style={s.sub}>{location === 'inventory' ? 'Carried items available during adventures.' : 'Bank materials are available for crafting, but food must be withdrawn for combat.'}</react_native_1.Text>
    <SearchField_1.SearchField accessibilityLabel="Search stored items" placeholder="Search items…" placeholderTextColor={theme_1.C.muted} value={query} onChangeText={setQuery}/>
    <react_native_1.Pressable accessibilityRole="button" accessibilityState={{ expanded: showFilters }} onPress={() => setShowFilters(value => !value)} style={s.disclosure}><react_native_1.View style={s.flex}><react_native_1.Text style={s.disclosureTitle}>FILTERS & DISPLAY</react_native_1.Text><react_native_1.Text style={s.sub}>{filter === 'all' ? 'All items' : filter} · sorted by {sort} · transfer {quantity}</react_native_1.Text></react_native_1.View><react_native_1.Text style={s.disclosureMark}>{showFilters ? '−' : '+'}</react_native_1.Text></react_native_1.Pressable>
    {showFilters && <Panel_1.Panel><react_native_1.ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.rarityLegend}>{item_rarity_1.GEAR_RARITIES.map(rarity => <react_native_1.View key={rarity.id} style={[s.rarityKey, { borderColor: rarity.color, backgroundColor: rarity.surface }]}><react_native_1.Text style={[s.rarityKeyText, { color: rarity.color }]}>{rarity.symbol} {rarity.label}</react_native_1.Text></react_native_1.View>)}</react_native_1.ScrollView><react_native_1.ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{['all', 'gear', 'tool', 'food', 'material'].map(value => <GameButton_1.GameButton key={value} title={value} selected={filter === value} tone={filter === value ? 'primary' : 'secondary'} onPress={() => setFilter(value)}/>)}</react_native_1.ScrollView><react_native_1.Text style={s.label}>SORT BY</react_native_1.Text><react_native_1.View style={s.row}>{['name', 'quantity', 'value'].map(value => <react_native_1.View style={s.flex} key={value}><GameButton_1.GameButton title={value === 'value' ? 'Unit value' : value} selected={sort === value} tone={sort === value ? 'primary' : 'secondary'} onPress={() => setSort(value)}/></react_native_1.View>)}</react_native_1.View><react_native_1.Text style={s.label}>TRANSFER QUANTITY</react_native_1.Text><react_native_1.View style={s.row}>{[1, 10, 'all'].map(value => <react_native_1.View key={value} style={s.flex}><GameButton_1.GameButton title={String(value)} selected={quantity === value} tone={quantity === value ? 'primary' : 'secondary'} onPress={() => setQuantity(value)}/></react_native_1.View>)}</react_native_1.View></Panel_1.Panel>}
    {!!error && <react_native_1.Text accessibilityRole="alert" style={s.warning}>{error}</react_native_1.Text>}
    <react_native_1.Text style={s.sub}>{stacks.length} matching stacks · {Math.max(0, state[location].capacity - (0, game_1.usedSlots)(state[location].stacks))} free slots</react_native_1.Text>
    {stacks.length ? stacks.map(renderStack) : <><EmptyState_1.EmptyState title="No items to show" message="Try another storage tab or clear the search and category filter."/><GameButton_1.GameButton title="Clear filters" tone="secondary" onPress={() => { setQuery(''); setFilter('all'); }}/></>}
    {overflowCount > 0 && <Panel_1.Panel><react_native_1.Text style={s.title}>{(0, i18n_1.ot)(state.settings.language, 'overflow.title')} · {overflowCount}</react_native_1.Text><react_native_1.Text style={s.warning}>{(0, i18n_1.ot)(state.settings.language, 'overflow.body')}</react_native_1.Text>{state.overflow.stacks.map((stack, index) => <react_native_1.Text key={`${stack.itemId}:${index}`} style={s.sub}>{stack.quantity}× {(0, items_1.itemDef)(stack.itemId).name}</react_native_1.Text>)}{state.overflow.expiresAtMs !== null && <react_native_1.Text style={s.warning}>Recorded expiry: {new Date(state.overflow.expiresAtMs).toLocaleString()}</react_native_1.Text>}<GameButton_1.GameButton title={(0, i18n_1.ot)(state.settings.language, 'overflow.move', { count: overflowCount - remaining })} disabled={remaining === overflowCount} onPress={() => run(onOverflow)}/>{remaining > 0 && <react_native_1.Text style={s.sub}>{(0, i18n_1.ot)(state.settings.language, 'overflow.remain', { count: remaining })}</react_native_1.Text>}</Panel_1.Panel>}
  </react_native_1.ScrollView><ConfirmModal_1.ConfirmModal visible={pending !== null} title={`${pending?.kind === 'deposit' ? 'Bank' : pending?.kind === 'sell' ? 'Sell' : 'Salvage'} ${pending?.item.name ?? 'item'}?`} message={message} confirmLabel={pending?.kind === 'deposit' ? 'Deposit' : pending?.kind === 'sell' ? 'Sell 1' : 'Salvage 1'} danger={pending?.kind !== 'deposit'} onConfirm={confirm} onCancel={() => setPending(null)}/></>;
}
const s = react_native_1.StyleSheet.create({ recovery: { gap: 4, paddingVertical: 8, paddingHorizontal: 4 }, root: { padding: theme_1.spacing.lg, gap: theme_1.spacing.md }, h: { ...theme_1.typography.hero, color: theme_1.C.text }, title: { ...theme_1.typography.title, color: theme_1.C.text }, sub: { ...theme_1.typography.body, color: theme_1.C.muted }, warning: { ...theme_1.typography.body, color: theme_1.C.warning }, label: { ...theme_1.typography.caption, color: theme_1.C.accent, fontWeight: '700' }, upgradeLabel: { ...theme_1.typography.caption, color: theme_1.C.muted, fontWeight: '700', marginBottom: theme_1.spacing.xs }, disclosure: { minHeight: 60, flexDirection: 'row', alignItems: 'center', gap: theme_1.spacing.sm, paddingHorizontal: theme_1.spacing.md, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: 10, backgroundColor: theme_1.C.panel }, disclosureTitle: { ...theme_1.typography.caption, color: theme_1.C.accent, fontWeight: '700', letterSpacing: .8 }, disclosureMark: { width: 28, color: theme_1.C.accent, fontSize: 25, textAlign: 'center' }, rarityLegend: { gap: theme_1.spacing.sm, paddingRight: theme_1.spacing.md }, rarityKey: { minHeight: 32, justifyContent: 'center', borderWidth: 1, borderRadius: 99, paddingHorizontal: theme_1.spacing.sm }, rarityKeyText: { ...theme_1.typography.caption, fontWeight: '700' }, row: { flexDirection: 'row', gap: theme_1.spacing.sm }, flex: { flex: 1 }, input: { minHeight: 48, paddingHorizontal: theme_1.spacing.md, borderRadius: 10, borderWidth: 1, borderColor: theme_1.C.line, color: theme_1.C.text, backgroundColor: theme_1.C.panel, fontSize: 16 } });
