"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SkillsScreen = SkillsScreen;
const RecipeCard_1 = require("../components/RecipeCard");
const SearchField_1 = require("../components/SearchField");
const ActivityArtwork_1 = require("../components/ActivityArtwork");
const react_1 = require("react");
const react_native_1 = require("react-native");
const skills_1 = require("../content/skills");
const herbalism_1 = require("../content/herbalism");
const items_1 = require("../content/items");
const playability_1 = require("../core/playability");
const game_1 = require("../core/game");
const world_weather_1 = require("../core/world-weather");
const Panel_1 = require("../components/Panel");
const GameButton_1 = require("../components/GameButton");
const theme_1 = require("../theme/theme");
const NoviceWorkshop_1 = require("../components/NoviceWorkshop");
const number_format_1 = require("../core/number-format");
const i18n_1 = require("../i18n");
const gathering_tools_1 = require("../content/gathering-tools");
const gathering_tools_2 = require("../core/gathering-tools");
const permanent_boosts_1 = require("../core/permanent-boosts");
const GatheringToolArtwork_1 = require("../components/GatheringToolArtwork");
const world_map_1 = require("../content/world-map");
const combat_region_1 = require("../core/combat-region");
const ResourceArtwork_1 = require("../components/ResourceArtwork");
const FaithPanel_1 = require("../components/FaithPanel");
const class_skills_1 = require("../content/class-skills");
const class_skills_2 = require("../core/class-skills");
const class_emblem_assets_1 = require("../theme/class-emblem-assets");
const ui_icons_1 = require("../theme/ui-icons");
function SkillsScreen({ state, onGather, onCraft, onEquipTool, onCharacter, onInventory, onViewToolRecipes, onSelectSkill, onCommand = async () => { }, initialMode = 'gathering', initialSkill }) {
    const gatheringDefs = [...skills_1.GATHERING, ...herbalism_1.HERB_NODES];
    const [mode, setMode] = (0, react_1.useState)(initialMode);
    const [readyOnly, setReadyOnly] = (0, react_1.useState)(false), [recipeQuery, setRecipeQuery] = (0, react_1.useState)(''), [recipeLimits, setRecipeLimits] = (0, react_1.useState)({});
    const [openTools, setOpenTools] = (0, react_1.useState)({});
    const offlineCap = (0, game_1.offlineCapBreakdown)(state);
    const region = world_map_1.WORLD_ZONES.find(zone => zone.id === (0, combat_region_1.currentRegionId)(state)) ?? world_map_1.WORLD_ZONES[0];
    if (!initialSkill)
        return <SkillHub state={state} onSelect={onSelectSkill ?? (() => { })}/>;
    return <react_native_1.ScrollView contentContainerStyle={s.root}>
    <react_native_1.Text style={s.h}>{initialSkill ? initialSkill.charAt(0).toUpperCase() + initialSkill.slice(1) : (0, i18n_1.ot)(state.settings.language, 'craft.screen')}</react_native_1.Text>
    {mode === 'gathering' && <react_native_1.View style={[s.region, { borderColor: region.accent }]}><react_native_1.View style={s.flex}><react_native_1.Text style={s.regionLabel}>CURRENT REGION</react_native_1.Text><react_native_1.Text style={s.regionName}>{region.symbol} {region.name}</react_native_1.Text><react_native_1.Text style={s.sub}>Only gathering nodes in this region are shown.</react_native_1.Text></react_native_1.View></react_native_1.View>}
    {!initialSkill && <react_native_1.View style={s.row}>{['gathering', 'crafting', 'novice', 'faith'].map(value => <react_native_1.View style={s.flex} key={value}><GameButton_1.GameButton title={value === 'faith' ? 'Faith' : (0, i18n_1.ot)(state.settings.language, value === 'gathering' ? 'craft.gathering' : value === 'novice' ? 'craft.novice' : 'craft.crafting')} selected={mode === value} tone={mode === value ? 'primary' : 'secondary'} onPress={() => setMode(value)}/></react_native_1.View>)}</react_native_1.View>}
    {(mode === 'faith' || initialSkill === 'faith') && <FaithPanel_1.FaithPanel state={state} onCommand={onCommand}/>}
    {mode === 'novice' && <NoviceWorkshop_1.NoviceWorkshop state={state} onCraft={onCraft} onCharacter={onCharacter}/>}
    {mode === 'crafting' && <><react_native_1.Text style={s.sub}>Materials are taken from Inventory first, then Bank. Expand a recipe to inspect ingredients and craft.</react_native_1.Text><GameButton_1.GameButton title={readyOnly ? 'Craftable only · Show all' : 'Show only craftable'} tone="secondary" onPress={() => setReadyOnly(!readyOnly)}/><SearchField_1.SearchField accessibilityLabel="Search recipes" value={recipeQuery} onChangeText={value => { setRecipeQuery(value); setRecipeLimits({}); }} placeholder="Search recipes…"/></>}
    {mode !== 'novice' && mode !== 'faith' && initialSkill !== 'faith' && state.skills.filter(sk => (!initialSkill || sk.skillId === initialSkill) && (mode === 'gathering' ? gatheringDefs.some(g => g.skillId === sk.skillId) : skills_1.RECIPES.some(r => r.skillId === sk.skillId && !r.noviceSetId))).map(sk => {
            const recipes = skills_1.RECIPES.filter(r => r.skillId === sk.skillId && !r.noviceSetId).sort((a, b) => a.level - b.level || a.name.localeCompare(b.name)).map(recipe => ({ recipe, status: (0, playability_1.recipeAvailability)(state, recipe.id) })).filter(({ recipe, status }) => (!readyOnly || status.ready) && (!recipeQuery.trim() || (recipe.name + ' ' + (0, items_1.itemDef)(recipe.output.itemId).name).toLowerCase().includes(recipeQuery.trim().toLowerCase())));
            const gatheringSkill = sk.skillId, equippedTool = mode === 'gathering' ? (0, gathering_tools_2.equippedGatheringTool)(state, gatheringSkill) : undefined;
            return <react_native_1.View key={sk.skillId} style={s.group}><react_native_1.View style={s.toolHeading}><ActivityArtwork_1.ActivityArtwork id={sk.skillId}/><react_native_1.View style={s.flex}><react_native_1.Text style={s.name}>{sk.skillId.charAt(0).toUpperCase() + sk.skillId.slice(1)} · Level {sk.level}</react_native_1.Text><react_native_1.Text style={s.sub}>{(0, number_format_1.formatGameNumber)(sk.xp, state.settings.numberMode)} XP</react_native_1.Text></react_native_1.View></react_native_1.View>
        {mode === 'gathering' && <Panel_1.Panel><react_native_1.Pressable accessibilityRole="button" accessibilityState={{ expanded: !!openTools[sk.skillId] }} onPress={() => setOpenTools(value => ({ ...value, [sk.skillId]: !value[sk.skillId] }))} style={s.toolHeading}>{equippedTool ? <GatheringToolArtwork_1.GatheringToolArtwork itemId={equippedTool.id} size={64}/> : <react_native_1.View style={s.emptyTool}><ActivityArtwork_1.ActivityArtwork id={gatheringSkill}/></react_native_1.View>}<react_native_1.View style={s.flex}><react_native_1.Text style={s.name}>{equippedTool?.name ?? 'No tool equipped'}</react_native_1.Text><react_native_1.Text style={s.sub}>{equippedTool ? `Tier ${equippedTool.tier} · ${Math.round((1 - equippedTool.actionTimeMultiplier) * 100)}% shorter action time` : 'No tool · 15% slower gathering'}</react_native_1.Text><react_native_1.Text style={s.manageHint}>Tap to {openTools[sk.skillId] ? 'hide' : 'manage'} tool tiers</react_native_1.Text></react_native_1.View><react_native_1.Text style={s.disclosureMark}>{openTools[sk.skillId] ? '−' : '+'}</react_native_1.Text></react_native_1.Pressable>{openTools[sk.skillId] && (0, gathering_tools_1.gatheringToolsFor)(gatheringSkill).map(tool => { const equipped = equippedTool?.id === tool.id, carried = state.inventory.stacks.some(stack => stack.itemId === tool.id && stack.quantity > 0), banked = state.bank.stacks.some(stack => stack.itemId === tool.id && stack.quantity > 0), levelReady = sk.level >= tool.unlockLevel; const title = equipped ? 'Equipped' : carried && !levelReady ? `Lv ${tool.unlockLevel}` : carried ? 'Equip' : banked ? 'Withdraw' : 'Recipe'; const disabled = equipped || (carried && !levelReady); const action = carried ? () => onEquipTool(tool.id) : banked ? onInventory : onViewToolRecipes; return <react_native_1.View key={tool.id} style={s.toolRow}><GatheringToolArtwork_1.GatheringToolArtwork itemId={tool.id} size={48}/><react_native_1.View style={s.flex}><react_native_1.Text style={s.toolName}>T{tool.tier} · {tool.name}</react_native_1.Text><react_native_1.Text style={s.toolEffect}>{Math.round((1 - tool.actionTimeMultiplier) * 100)}% faster · skill level {tool.unlockLevel}{banked ? ' · in Bank' : carried ? ' · ready' : ''}</react_native_1.Text></react_native_1.View><react_native_1.View style={s.toolButton}><GameButton_1.GameButton title={title} disabled={disabled} selected={equipped} tone={equipped ? 'primary' : 'secondary'} onPress={action}/></react_native_1.View></react_native_1.View>; })}</Panel_1.Panel>}
        {mode === 'gathering' && gatheringDefs.filter(g => g.skillId === sk.skillId && g.zoneId === region.id).map(g => { const active = state.activity?.targetId === g.id; const environment = (0, world_weather_1.environmentForZone)(g.zoneId); const effect = (0, world_weather_1.environmentEffect)(g.skillId, environment); const pacing = (0, gathering_tools_2.gatheringPacing)(state, g); const permanent = (0, permanent_boosts_1.characterPermanentMultipliers)(state); const cycle = g.seconds * game_1.GATHER_TIME_SCALE * pacing.timeMultiplier * effect.actionTimeMultiplier / permanent.gatheringSpeedMultiplier; const capActions = Math.floor(offlineCap.hours * 3600 / cycle); const baselineItems = Math.floor(capActions * g.min * effect.itemMultiplier); const capXp = Math.floor(capActions * g.xp * effect.xpMultiplier * permanent.skillXpMultiplier); return <Panel_1.Panel key={g.id}><react_native_1.View style={s.toolHeading}><ResourceArtwork_1.ResourceArtwork itemId={g.itemId} size={64}/><react_native_1.View style={s.flex}><react_native_1.Text style={s.name}>{g.name}</react_native_1.Text><react_native_1.Text style={s.sub}>{(0, items_1.itemDef)(g.itemId).name} · every {cycle.toFixed(1)}s · {g.xp} base skill XP/action</react_native_1.Text></react_native_1.View><react_native_1.View style={[s.tierBadge, pacing.atRecommendedTier ? s.tierReady : s.tierSlow]}><react_native_1.Text style={s.tierText}>T{g.recommendedToolTier}</react_native_1.Text></react_native_1.View></react_native_1.View><react_native_1.Text style={pacing.atRecommendedTier ? s.readyText : s.slowText}>{pacing.atRecommendedTier ? `${pacing.tool?.name} offsets this resource's ×${g.difficultyMultiplier.toFixed(2)} difficulty.` : `Recommended: ${pacing.recommended?.name}. Current pace is ×${pacing.timeMultiplier.toFixed(2)} before weather.`}</react_native_1.Text><react_native_1.Text style={s.pacing}>At your {offlineCap.hours}h AFK cap: {(0, number_format_1.formatGameNumber)(capActions, state.settings.numberMode)} actions · {(0, number_format_1.formatGameNumber)(baselineItems, state.settings.numberMode)}+ {(0, items_1.itemDef)(g.itemId).name} · {(0, number_format_1.formatGameNumber)(capXp, state.settings.numberMode)} XP</react_native_1.Text><GameButton_1.GameButton disabled={sk.level < g.unlockLevel || active} title={active ? 'Currently gathering' : sk.level < g.unlockLevel ? `Requires ${g.skillId} level ${g.unlockLevel}` : `Gather ${g.name}`} onPress={() => onGather(g.id)}/></Panel_1.Panel>; })}
        {mode === 'gathering' && gatheringDefs.every(g => g.skillId !== sk.skillId || g.zoneId !== region.id) && <react_native_1.Text style={s.unavailable}>No {sk.skillId} activity is available in {region.name}. Travel to another region from World.</react_native_1.Text>}
        {mode === 'crafting' && recipes.slice(0, recipeLimits[sk.skillId] ?? 12).map(({ recipe, status }) => <RecipeCard_1.RecipeCard key={recipe.id} state={state} recipe={recipe} status={status} onCraft={onCraft}/>)}
        {mode === 'crafting' && recipes.length > (recipeLimits[sk.skillId] ?? 12) && <GameButton_1.GameButton title={`Show more recipes (${recipes.length - (recipeLimits[sk.skillId] ?? 12)} remaining)`} tone="secondary" onPress={() => setRecipeLimits(value => ({ ...value, [sk.skillId]: (value[sk.skillId] ?? 12) + 12 }))}/>}
        {mode === 'crafting' && recipes.length === 0 && <react_native_1.Text style={s.sub}>{recipeQuery.trim() ? 'No recipes match your search.' : readyOnly ? 'No recipes are ready. Show all to see requirements.' : 'No recipes available.'}</react_native_1.Text>}
      </react_native_1.View>;
        })}
  </react_native_1.ScrollView>;
}
const s = react_native_1.StyleSheet.create({ root: { padding: theme_1.spacing.lg, gap: theme_1.spacing.md }, h: { ...theme_1.typography.hero, color: theme_1.C.text }, name: { ...theme_1.typography.title, color: theme_1.C.text }, sub: { ...theme_1.typography.body, color: theme_1.C.muted }, weather: { ...theme_1.typography.caption, fontWeight: '900' }, pacing: { ...theme_1.typography.caption, color: theme_1.C.info }, row: { flexDirection: 'row', gap: theme_1.spacing.sm }, flex: { flex: 1 }, group: { gap: theme_1.spacing.md }, output: { ...theme_1.typography.bodyStrong, color: theme_1.C.accent }, met: { ...theme_1.typography.caption, color: theme_1.C.good }, missing: { ...theme_1.typography.caption, color: theme_1.C.warning }, toolHeading: { minHeight: 68, flexDirection: 'row', alignItems: 'center', gap: theme_1.spacing.sm }, manageHint: { ...theme_1.typography.caption, color: theme_1.C.accent }, disclosureMark: { width: 28, color: theme_1.C.accent, fontSize: 25, textAlign: 'center' }, emptyTool: { width: 64, height: 64, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: theme_1.C.line, borderRadius: 8, backgroundColor: '#09121a' }, emptyToolText: { fontSize: 28, color: theme_1.C.muted }, toolRow: { flexDirection: 'row', alignItems: 'center', gap: theme_1.spacing.sm, paddingTop: theme_1.spacing.sm, borderTopWidth: 1, borderTopColor: theme_1.C.line }, toolName: { ...theme_1.typography.bodyStrong, color: theme_1.C.text }, toolEffect: { ...theme_1.typography.caption, color: theme_1.C.info }, toolButton: { width: 96 }, tierBadge: { minWidth: 42, height: 38, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderRadius: 8 }, tierReady: { borderColor: theme_1.C.good, backgroundColor: '#172b24' }, tierSlow: { borderColor: theme_1.C.warning, backgroundColor: '#332515' }, tierText: { ...theme_1.typography.bodyStrong, color: theme_1.C.text }, readyText: { ...theme_1.typography.caption, color: theme_1.C.good, fontWeight: '800' }, slowText: { ...theme_1.typography.caption, color: theme_1.C.warning, fontWeight: '800' }, region: { minHeight: 86, flexDirection: 'row', alignItems: 'center', padding: theme_1.spacing.md, backgroundColor: '#0c1d2e', borderWidth: 1, borderRadius: 10 }, regionLabel: { ...theme_1.typography.caption, color: theme_1.C.muted, fontWeight: '900', letterSpacing: .8 }, regionName: { ...theme_1.typography.title, color: theme_1.C.accent }, unavailable: { ...theme_1.typography.body, color: theme_1.C.muted, padding: theme_1.spacing.md, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: 8, backgroundColor: theme_1.C.panel } });
const hubStyles = react_native_1.StyleSheet.create({ hub: { padding: theme_1.spacing.lg, gap: theme_1.spacing.md }, hubTitle: { ...theme_1.typography.hero, color: theme_1.C.text }, hubSub: { ...theme_1.typography.body, color: theme_1.C.muted }, hubTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: theme_1.spacing.sm }, hubTab: { width: '48%', minWidth: 140 }, sectionLabel: { ...theme_1.typography.caption, color: theme_1.C.muted, fontWeight: '900' }, cardGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme_1.spacing.sm }, skillCard: { width: '48%', minWidth: 145, minHeight: 154, padding: theme_1.spacing.md, borderWidth: 1, borderColor: theme_1.C.line, borderRadius: 12, backgroundColor: theme_1.C.panel, gap: 5 }, skillIcon: { width: 44, height: 44, alignSelf: 'center', marginBottom: 2 }, cardPressed: { opacity: .72 }, skillName: { ...theme_1.typography.bodyStrong, color: theme_1.C.text }, skillKind: { ...theme_1.typography.caption, color: theme_1.C.info }, skillLevel: { ...theme_1.typography.title, color: theme_1.C.accent }, skillTrack: { height: 6, backgroundColor: theme_1.C.bg, borderRadius: 3, overflow: 'hidden', marginTop: 'auto' }, skillFill: { height: '100%', backgroundColor: theme_1.C.good }, skillHint: { ...theme_1.typography.caption, color: theme_1.C.muted } });
function SkillHub({ state, onSelect }) {
    const classRows = state.character ? (0, class_skills_2.characterClassSkills)(state.character) : [];
    const cards = (rows) => <react_native_1.View style={hubStyles.cardGrid}>{rows.map(card => { const icon = card.id === 'companion' ? ui_icons_1.uiIcons.party : card.id.startsWith('class:') ? class_emblem_assets_1.classEmblemIconArtwork[state.character.classId] : null; return <react_native_1.Pressable key={card.id} accessibilityRole="button" onPress={() => onSelect(card.id)} style={({ pressed }) => [hubStyles.skillCard, pressed && hubStyles.cardPressed]}>{icon ? <react_native_1.Image source={icon} resizeMode="contain" style={hubStyles.skillIcon}/> : <ActivityArtwork_1.ActivityArtwork id={card.id} size={42}/>}<react_native_1.Text style={hubStyles.skillName}>{card.name}</react_native_1.Text><react_native_1.Text style={hubStyles.skillKind}>{card.kind}</react_native_1.Text><react_native_1.Text style={hubStyles.skillLevel}>Level {card.level}</react_native_1.Text><react_native_1.View style={hubStyles.skillTrack}><react_native_1.View style={[hubStyles.skillFill, { width: `${Math.max(4, Math.min(100, card.level))}%` }]}/></react_native_1.View><react_native_1.Text style={hubStyles.skillHint}>Tap to open</react_native_1.Text></react_native_1.Pressable>; })}</react_native_1.View>;
    const combat = [...classRows.map((row, i) => ({ id: `class:${row.skillId}`, name: (0, class_skills_1.classSkillsFor)(state.character.classId)[i]?.name ?? row.skillId, level: row.level, kind: 'Class skill' })), { id: 'companion', name: 'Companions', level: state.account.companionSanctuary?.trainingGroundLevel ?? 1, kind: 'Companion skill' }];
    const skilling = state.skills.filter(sk => ['mining', 'woodcutting', 'fishing', 'herbalism', 'hunting', 'exploration'].includes(sk.skillId)).map(sk => ({ id: sk.skillId, name: sk.skillId.charAt(0).toUpperCase() + sk.skillId.slice(1), level: sk.level, kind: 'Skilling' }));
    const crafting = state.skills.filter(sk => ['smithing', 'cooking', 'alchemy', 'tailoring', 'enchanting', 'faith'].includes(sk.skillId)).map(sk => ({ id: sk.skillId, name: sk.skillId.charAt(0).toUpperCase() + sk.skillId.slice(1), level: sk.level, kind: 'Crafting' }));
    return <react_native_1.ScrollView contentContainerStyle={hubStyles.hub}><react_native_1.Text style={hubStyles.hubTitle}>Skills</react_native_1.Text><react_native_1.Text style={hubStyles.hubSub}>Choose a skill to train or inspect.</react_native_1.Text><react_native_1.Text style={hubStyles.sectionLabel}>COMBAT SKILLS</react_native_1.Text>{cards(combat)}<react_native_1.Text style={hubStyles.sectionLabel}>SKILLING</react_native_1.Text>{cards(skilling)}<react_native_1.Text style={hubStyles.sectionLabel}>CRAFTING &amp; OTHER SKILLS</react_native_1.Text>{cards(crafting)}</react_native_1.ScrollView>;
}
