import type {CombatCompanionRarity,CompanionAbilityDefinition,CompanionDefinition,CompanionEffectDefinition,CompanionSanctuaryUpgrade} from '../core/combat-companion-types';
import {EVENT_COMPANIONS} from './event-companions-v2';

/**
 * Rarity is a TOTAL companion power budget, never a second stat multiplier.
 * 1.09 means a fully invested Rare companion targets ~109% of a comparable Standard.
 */
export const COMPANION_RARITY_CONFIG:Record<CombatCompanionRarity,{
  maxLevel:number;targetPowerMultiplier:number;levelCostMultiplier:number;xpRequiredMultiplier:number;label:string;
}>={
  standard:{maxLevel:20,targetPowerMultiplier:1,levelCostMultiplier:1,xpRequiredMultiplier:1,label:'Standard'},
  rare:{maxLevel:25,targetPowerMultiplier:1.09,levelCostMultiplier:1.18,xpRequiredMultiplier:1.08,label:'Rare'},
  elite:{maxLevel:30,targetPowerMultiplier:1.12,levelCostMultiplier:1.38,xpRequiredMultiplier:1.16,label:'Elite'},
  prestige:{maxLevel:35,targetPowerMultiplier:1.155,levelCostMultiplier:1.62,xpRequiredMultiplier:1.25,label:'Prestige'},
};

/** Current level cap by completed Ascension tier. */
export const COMPANION_STAGE_CAPS:Record<CombatCompanionRarity,readonly [number,number,number,number]>={
  standard:[10,20,20,20],
  rare:[10,20,25,25],
  elite:[10,20,25,30],
  prestige:[10,20,25,35],
};

export const COMPANION_LEVEL_CURVE={baseXp:65,xpGrowth:1.16,goldBase:38,goldGrowth:1.24,essenceBase:4,essenceGrowth:1.19} as const;
export const COMPANION_BOND_CONFIG={
  maxLevel:10,
  // cumulative XP required for Bond Levels 1-10
  xpThresholds:[0,90,210,370,580,840,1160,1540,1990,2520] as const,
  rewards:{2:'Small progression reward',4:'Companion profile icon',6:'Passive improvement',8:'Companion title/profile reward',10:'Bond Trait'} as Record<number,string>,
  sourceXp:{battle:4,boss:60,dungeon:32,companion_objective:45,future_activity:12} as const,
} as const;

export const COMPANION_ASCENSION_BASE_COST={
  1:{gold:650,companionEssence:90,bondstones:1,materialQuantity:4},
  2:{gold:1900,companionEssence:240,bondstones:3,materialQuantity:9},
  3:{gold:4800,companionEssence:560,bondstones:7,materialQuantity:16},
  mastery:{gold:9000,companionEssence:950,bondstones:12,materialQuantity:24},
} as const;

export const COMPANION_SANCTUARY_CONFIG:Record<CompanionSanctuaryUpgrade,{
  maxLevel:number;goldCosts:number[];essenceCosts:number[];materialId?:string;materialCosts?:number[];description:string;
}>={
  trainingGround:{maxLevel:3,goldCosts:[1800,5200,12000],essenceCosts:[120,320,720],materialId:'ASTER_IRON_INGOT',materialCosts:[8,16,28],description:'Provides passive Companion XP on long-timer claims.'},
  essenceBasin:{maxLevel:3,goldCosts:[2200,6500,14500],essenceCosts:[80,220,520],materialId:'ECHO_QUARTZ',materialCosts:[5,10,18],description:'Generates a small weekly Companion Essence claim.'},
  bondHall:{maxLevel:3,goldCosts:[2500,7200,16000],essenceCosts:[160,420,900],materialId:'OATHGLASS_SHARD',materialCosts:[6,12,20],description:'Increases earned Bond XP by +5%, +10%, then +15%.'},
  expeditionPens:{maxLevel:3,goldCosts:[8500,16000,28000],essenceCosts:[650,1150,1900],materialId:'RUNEBOUND_CORE',materialCosts:[6,12,20],description:'Unlocks 1, 2, then 3 simultaneous Sanctuary Companion Expeditions.'},
  masteryChamber:{maxLevel:1,goldCosts:[18000],essenceCosts:[1400],materialId:'OATHGLASS_FRAGMENT',materialCosts:[18],description:'Required for Prestige Mastery and highest companion progression.'},
};
export const COMPANION_SANCTUARY_BOND_BONUS=[0,.05,.10,.15] as const;
export const COMPANION_SANCTUARY_TRAINING_XP_PER_DAY=[0,24,52,84] as const;
export const COMPANION_SANCTUARY_WEEKLY_ESSENCE=[0,20,48,80] as const;

const ability=(id:string,name:string,description:string,cooldownSeconds:number,target:string,kind:CompanionEffectDefinition['kind'],baseValue:number,perLevel:number,extra:Partial<CompanionEffectDefinition>={}):CompanionAbilityDefinition=>({
  id,name,description,cooldownSeconds,target,
  effect:{kind,value:baseValue,description,...extra},
  scaling:{baseValue,perLevel,maxValue:kind==='damage'?baseValue+.28:undefined},
});
const passive=(kind:CompanionEffectDefinition['kind'],value:number,description:string,condition?:string):CompanionEffectDefinition=>({kind,value,description,condition});
const req=(type:CompanionDefinition['unlockRequirements'][number]['type'],description:string,target?:string,amount?:number)=>({type,description,target,amount});
const origin=(id:string,name:string,type:CompanionDefinition['origin']['type']='region')=>({id,name,type});
const trait=(id:string,name:string,kind:CompanionEffectDefinition['kind'],value:number,description:string,condition?:string)=>({id,name,description,effect:passive(kind,value,description,condition)});

const ASTER=origin('REG_001','Asterfall');
const SUNSCAR=origin('REG_SUNSCAR','Sunscar');
const FROST=origin('REG_FROSTMARCH','Frostmarch');
const ASH=origin('REG_ASHLANDS','Ashlands');

/**
 * Asterfall units come directly from the Combat Units design family.
 * Old Utility/Flexible role tags are deliberately collapsed into Support because
 * the active system now permits exactly Damage/Tank/Support.
 */
const ASTERFALL_COMPANIONS:CompanionDefinition[]=[
  {id:'UNIT_001',name:'Ironwood Hound',description:'Fast finisher for farming.',archetype:'Striker',role:'damage',rarity:'standard',origin:ASTER,unlockRequirements:[req('quest','Complete Ironwood introduction','QST_005',1)],baseStats:{hp:180,power:22,defense:12,attackSpeed:2},activeAbility:ability('UABL_001','Hamstring Pounce','Damage + 8% slow',14,'Lowest-HP enemy','damage',1,.006,{secondaryValue:.08,durationSeconds:4}),passiveAbility:passive('execute',.04,'Pack Instinct: +4% damage against enemies below 35% HP.','target_hp_below_35'),bondTrait:trait('BOND_001','Relentless Chase','cooldown_reduction',.08,'Hamstring Pounce recharges 8% faster after defeating a weakened target.','target_defeated_below_35'),ascensionMaterialId:'IRONWOOD_FANG'},
  {id:'UNIT_002',name:'Runebound Sentry',description:'Smooths solo and boss damage spikes.',archetype:'Guardian',role:'tank',rarity:'standard',origin:ASTER,unlockRequirements:[req('achievement','Defeat 250 Old Mines enemies','OLD_MINES_KILLS',250)],baseStats:{hp:260,power:14,defense:24,attackSpeed:2.6},activeAbility:ability('UABL_002','Rune Brace','6% damage reduction to next 2 hits',18,'Owner','damage_reduction',.06,.001,{secondaryValue:2,durationSeconds:5}),passiveAbility:passive('damage_reduction',.06,'Runic Guard: every 12s, owner takes 6% less damage from the next hit.','every_12_seconds'),bondTrait:trait('BOND_002','Carved Shelter','shield',.025,'Rune Brace also grants a small follow-up shield after its second protected hit.','rune_brace_consumed'),ascensionMaterialId:'RUNEBOUND_CORE'},
  {id:'UNIT_003',name:'Silverbrook Sprite',description:'Small tempo and class-resource support.',archetype:'Support',role:'support',rarity:'standard',origin:ASTER,unlockRequirements:[req('skill_level','Reach Fishing 15','fishing',15),req('collection','Discover all Silverbrook nodes','SILVERBROOK_NODES')],baseStats:{hp:150,power:12,defense:10,attackSpeed:2.2},activeAbility:ability('UABL_003','Silver Current','Restore 4% class resource + 3% Haste',20,'Owner','resource_restore',.04,.001,{secondaryValue:.03,durationSeconds:5}),passiveAbility:passive('cooldown_reduction',.05,"Flowing Current: owner's first ability after combat starts has 5% shorter cooldown.",'first_owner_ability'),bondTrait:trait('BOND_003','Deep Current','haste',.025,'Silver Current grants an additional short Haste pulse after restoring class resource.','silver_current_used'),ascensionMaterialId:'WISP_DUST'},
  {id:'UNIT_004',name:'Briarhorn Cub',description:'Durable-target pressure through mild defense shred.',archetype:'Bruiser',role:'damage',rarity:'rare',origin:ASTER,unlockRequirements:[req('monster_mastery','Reach Forest Troll Mastery 20','FOREST_TROLL',20)],baseStats:{hp:230,power:25,defense:18,attackSpeed:2.4},activeAbility:ability('UABL_004','Briar Charge','Damage + -5% Defence',16,'Highest-Defence enemy','damage',1.2,.006,{secondaryValue:.05,durationSeconds:5}),passiveAbility:passive('defense_shred',.03,'Barkbreaker: attacks have a 12% chance to apply -3% Defence for 5s; non-stacking.','12_percent_proc'),bondTrait:trait('BOND_004','Rootbreaker','damage',.06,'Deals 6% more companion damage to targets currently affected by defense reduction.','target_defense_reduced'),ascensionMaterialId:'THORN_SAP'},
  {id:'UNIT_005',name:'Lantern Wisp',description:'Interrupt-focused co-op helper.',archetype:'Disruptor',role:'support',rarity:'rare',origin:ASTER,unlockRequirements:[req('monster_mastery','Reach Lantern Wretch Mastery 20','LANTERN_WRETCH',20)],baseStats:{hp:145,power:18,defense:11,attackSpeed:2},activeAbility:ability('UABL_005','Lantern Snuff','Damage + interrupt',22,'Casting enemy','interrupt',.55,.004),passiveAbility:passive('accuracy',.08,'Flicker Sense: +8% unit accuracy against enemies currently casting.','enemy_casting'),bondTrait:trait('BOND_005','Afterglow','cooldown_reduction',.1,'A successful interrupt shortens the next Lantern Snuff cooldown by 10%.','successful_interrupt'),ascensionMaterialId:'LANTERNSTEEL_SHARD'},
  {id:'UNIT_006',name:'Oathbound Page',description:'Boss-progression defensive companion.',archetype:'Guardian',role:'tank',rarity:'rare',origin:ASTER,unlockRequirements:[req('boss_kills','Defeat The Fallen Knight once','FALLEN_KNIGHT',1)],baseStats:{hp:290,power:16,defense:25,attackSpeed:2.8},activeAbility:ability('UABL_006',"Page's Vow",'Shield for 5% owner max HP',24,'Owner','shield',.05,.001),passiveAbility:passive('damage_reduction',.08,'Oathkeeper: once per encounter, intercepts 8% of one hit dealt to owner.','once_per_encounter'),bondTrait:trait('BOND_006','Renewed Vow','damage_reduction',.025,'After the shield breaks, the owner gains brief mitigation.','shield_broken'),ascensionMaterialId:'OATHGLASS_SHARD'},
  {id:'UNIT_007',name:'Gloamknife Shade',description:'Fast rare-target cleanup and execute pressure.',archetype:'Assassin',role:'damage',rarity:'elite',origin:ASTER,unlockRequirements:[req('achievement','Reach Knife Dancer class skill total 80','KNIFE_DANCER_SKILL_TOTAL',80)],baseStats:{hp:155,power:29,defense:10,attackSpeed:1.7},activeAbility:ability('UABL_007','Gloamstep','Damage; +20% coefficient under 25% HP',18,'Lowest-HP enemy','damage',1.45,.005,{secondaryValue:.2}),passiveAbility:passive('execute',.10,'Veiled Edge: first unit hit against a new target has +10% crit chance.','new_target'),bondTrait:trait('BOND_007','Final Shadow','execute',.08,'Gloamstep gains an additional execute bonus against critically wounded targets.','target_hp_below_25'),ascensionMaterialId:'GLOAM_DUST'},
  {id:'UNIT_008',name:'Dawnwing',description:'Long-form group sustain.',archetype:'Support',role:'support',rarity:'elite',origin:ASTER,unlockRequirements:[req('skill_level','Reach Faith 30','faith',30)],baseStats:{hp:180,power:14,defense:14,attackSpeed:2.3},activeAbility:ability('UABL_008','Dawn Pinion','4% max-HP shield + cleanse minor debuff',24,'Lowest-HP ally','shield',.04,.001,{secondaryValue:1,durationSeconds:5}),passiveAbility:passive('shield',.02,'Warm Light: every 15s the lowest-HP party member gains a 2% max-HP shield.','every_15_seconds'),bondTrait:trait('BOND_008','Second Dawn','cleanse',1,'Dawn Pinion may remove one additional minor debuff when used below 35% HP.','target_hp_below_35'),ascensionMaterialId:'OATHGLASS_FRAGMENT'},
  {id:'UNIT_009',name:'Echo Stalker',description:'Coordinated damage companion that rewards debuffs.',archetype:'Hunter',role:'damage',rarity:'elite',origin:ASTER,unlockRequirements:[req('monster_mastery','Reach Echo Bat Mastery 20','ECHO_BAT',20)],baseStats:{hp:175,power:27,defense:13,attackSpeed:1.9},activeAbility:ability('UABL_009','Echo Rend','Damage; +10% coefficient if 2+ debuffs',17,'Debuffed enemy','damage',1.25,.006,{secondaryValue:.1}),passiveAbility:passive('damage',.05,'Echo Hunter: +5% damage against enemies with any player-applied debuff.','target_debuffed'),bondTrait:trait('BOND_009','Resonant Hunt','cooldown_reduction',.08,'Echo Rend recharges faster while the priority target has multiple debuffs.','target_has_2_debuffs'),ascensionMaterialId:'ECHO_QUARTZ'},
  {id:'UNIT_010',name:'Forge Automaton',description:'Slow armor-pressure artillery companion.',archetype:'Artillery',role:'damage',rarity:'rare',origin:ASTER,unlockRequirements:[req('achievement','Craft 500 equipment pieces','EQUIPMENT_CRAFTS',500),req('skill_level','Reach Smithing 30','smithing',30)],baseStats:{hp:205,power:26,defense:20,attackSpeed:2.9},activeAbility:ability('UABL_010','Siege Bolt','Damage + ignores 8% Defence',20,'Highest-HP enemy','damage',1.35,.005,{secondaryValue:.08}),passiveAbility:passive('armor_pierce',.05,'Calibrated Shot: every 4th attack ignores 5% of target Defence.','every_4th_attack'),bondTrait:trait('BOND_010','Perfect Calibration','armor_pierce',.03,'Siege Bolt ignores an additional 3% Defence against high-HP targets.','target_hp_above_60'),ascensionMaterialId:'FALLEN_RIVET'},
  {id:'UNIT_011',name:"Veyren's Memory",description:'Tactical utility that rewards active targeting.',archetype:'Tactician',role:'support',rarity:'elite',origin:ASTER,unlockRequirements:[req('boss_kills','Defeat the Fallen Knight 3 times','FALLEN_KNIGHT',3)],baseStats:{hp:190,power:21,defense:16,attackSpeed:2.4},activeAbility:ability('UABL_011','Memory Command','Damage + owner +2% Accuracy vs target',22,'Priority target','damage',.85,.004,{secondaryValue:.02,durationSeconds:6}),passiveAbility:passive('haste',.12,'Remembered Route: first manual target swap each encounter gives unit +12% Haste for 4s.','first_manual_target_swap'),bondTrait:trait('BOND_011','Perfect Recall','accuracy',.03,'Memory Command grants a slightly stronger accuracy window after a manual target swap.','manual_target_swap'),ascensionMaterialId:'TORN_OATHCLOTH'},
  {id:'UNIT_012',name:'Oathglass Knightling',description:'Prestige tactical companion with balanced utility.',archetype:'Champion',role:'support',rarity:'prestige',origin:ASTER,unlockRequirements:[req('event_challenge','Complete the Oathglass Reflection Trial','CHALLENGE_OATHGLASS_KNIGHTLING',1)],baseStats:{hp:220,power:23,defense:21,attackSpeed:2.2},activeAbility:ability('UABL_012','Oathglass Reflection','Damage + copy one eligible self-buff duration at 25%',26,'Priority target','utility',.25,.002,{secondaryValue:.95,durationSeconds:4}),passiveAbility:passive('utility',.25,"Reflected Oath: copies 25% of owner's current non-ultimate self-buff duration onto itself.",'eligible_owner_buff'),bondTrait:trait('BOND_012','True Reflection','cooldown_reduction',.1,'A successful copied buff shortens the next Reflection cooldown without copying stat magnitude.','eligible_buff_copied'),ascensionMaterialId:'OATHGLASS_FRAGMENT'},
];

/** Regional companions are hand-authored so later regions do not collapse into one generic role template. */
const regional=(input:{
  id:string;name:string;rarity:CombatCompanionRarity;role:CompanionDefinition['role'];region:CompanionDefinition['origin'];
  description:string;archetype:string;activeName:string;activeDescription:string;activeTarget:string;effect:CompanionEffectDefinition['kind'];activeValue:number;cooldown:number;
  passive:CompanionEffectDefinition;bondName:string;bond:CompanionEffectDefinition;materialId:string;unlockRequirements:CompanionDefinition['unlockRequirements'];
  ascensionMaterialCosts?:CompanionDefinition['ascensionMaterialCosts'];
}):CompanionDefinition=>({
  id:input.id,name:input.name,description:input.description,archetype:input.archetype,role:input.role,rarity:input.rarity,origin:input.region,
  unlockRequirements:input.unlockRequirements,
  baseStats:{hp:input.rarity==='prestige'?225:input.rarity==='elite'?205:190,power:input.role==='damage'?27:18,defense:input.role==='tank'?25:15,attackSpeed:2.2},
  activeAbility:ability(`${input.id}_ACTIVE`,input.activeName,input.activeDescription,input.cooldown,input.activeTarget,input.effect,input.activeValue,input.effect==='damage'?.005:.001),
  passiveAbility:input.passive,
  bondTrait:{id:`${input.id}_BOND`,name:input.bondName,description:input.bond.description,effect:input.bond},
  ascensionMaterialId:input.materialId,ascensionMaterialCosts:input.ascensionMaterialCosts,visual:{pixelSize:'96x96'}
});
const REGIONAL_COMPANIONS:CompanionDefinition[]=[
 regional({id:'UNIT_013',name:'Dune Stalker',rarity:'rare',role:'damage',region:SUNSCAR,archetype:'Assassin',description:'A venomous ambusher that rewards sustained pressure on one target.',activeName:'Venom Ambush',activeDescription:'Strike the priority target and exploit wounded enemies.',activeTarget:'Priority target',effect:'damage',activeValue:1.10,cooldown:18,passive:passive('execute',.05,'Venom Hunter: deals more damage to enemies below 35% HP.','target_hp_below_35'),bondName:'Virulent Pursuit',bond:passive('damage',.05,'Bond 10 strengthens damage while the same target remains engaged.','same_target'),materialId:'AMBERGLASS',unlockRequirements:[req('monster_mastery','Reach Sunscar Scorpion Mastery 20','SUNSCAR_SCORPION',20)],ascensionMaterialCosts:[{tier:1,itemId:'AMBERGLASS',quantity:4},{tier:2,itemId:'SUNSTONE_ORE',quantity:9}]}),
 regional({id:'UNIT_014',name:'Oasis Djinnling',rarity:'elite',role:'support',region:SUNSCAR,archetype:'Restorer',description:'A resource and recovery specialist built for long fights.',activeName:'Oasis Pulse',activeDescription:'Restore the most pressured ally and grant a short tempo window.',activeTarget:'Lowest-HP ally',effect:'resource_restore',activeValue:.05,cooldown:22,passive:passive('haste',.035,'Mirage Flow: the first support action in combat grants brief Haste.','first_support_action'),bondName:'Deep Oasis',bond:passive('resource_restore',.04,'Bond 10 improves the Djinnling’s restorative pulse.','oasis_pulse'),materialId:'ASTRAL_SCRIPT',unlockRequirements:[req('achievement','Complete 3 Sunscar Echoes','SUNSCAR_ECHOES',3)],ascensionMaterialCosts:[{tier:1,itemId:'AMBERGLASS',quantity:4},{tier:2,itemId:'ASTRAL_SCRIPT',quantity:9},{tier:3,itemId:'SUNSTONE_ORE',quantity:16}]}),
 regional({id:'UNIT_015',name:'Solar Scarab',rarity:'elite',role:'tank',region:SUNSCAR,archetype:'Reflector',description:'A shield specialist that turns absorbed pressure back on attackers.',activeName:'Solar Carapace',activeDescription:'Gain a strong solar barrier for the next damage window.',activeTarget:'Self',effect:'shield',activeValue:.055,cooldown:24,passive:passive('damage_reduction',.04,'Sun-Hardened Shell: reduces periodic incoming pressure.','every_12_seconds'),bondName:'Radiant Reprisal',bond:passive('damage',.04,'Bond 10 empowers counter-pressure after the Scarab’s barrier is consumed.','shield_broken'),materialId:'SUNSTONE_ORE',unlockRequirements:[req('dungeon_clears','Complete all Sunscar co-op dungeons','SUNSCAR_DUNGEONS',3)],ascensionMaterialCosts:[{tier:1,itemId:'SUNSTONE_ORE',quantity:4},{tier:2,itemId:'AMBERGLASS',quantity:9},{tier:3,itemId:'ASTRAL_SCRIPT',quantity:16}]}),
 regional({id:'UNIT_016',name:"Tyrant's Heir",rarity:'prestige',role:'tank',region:SUNSCAR,archetype:'Champion',description:'A prestigious defensive sidegrade earned through the buried tyrant challenge.',activeName:"Tyrant's Aegis",activeDescription:'Raise an imposing shield that stabilizes dangerous boss pressure.',activeTarget:'Self',effect:'shield',activeValue:.065,cooldown:22,passive:passive('damage_reduction',.05,'Royal Bearing: reduces heavy incoming hits.','heavy_hit'),bondName:'Unbroken Crown',bond:passive('shield',.05,'Bond 10 strengthens Aegis recovery after critical pressure.','low_hp'),materialId:'ASTRAL_SCRIPT',unlockRequirements:[req('meta',"Defeat the Crown of the Buried Tyrant companion challenge",'CHALLENGE_TYRANTS_HEIR',1)],ascensionMaterialCosts:[{tier:1,itemId:'SUNSTONE_ORE',quantity:4},{tier:2,itemId:'AMBERGLASS',quantity:9},{tier:3,itemId:'ASTRAL_SCRIPT',quantity:16},{tier:'mastery',itemId:'ASTRAL_SCRIPT',quantity:24}]}),
 regional({id:'UNIT_017',name:'Rime Wolf Pup',rarity:'rare',role:'damage',region:FROST,archetype:'Striker',description:'A fast hunter that sets up finishing windows through chill pressure.',activeName:'Rimefang',activeDescription:'Lunge at the priority target and capitalize on low-health openings.',activeTarget:'Priority target',effect:'damage',activeValue:1.10,cooldown:18,passive:passive('execute',.05,'Winter Hunt: gains finishing pressure against weakened targets.','target_hp_below_35'),bondName:'Shatterfang',bond:passive('damage',.05,'Bond 10 strengthens Rimefang against chilled or weakened enemies.','target_debuffed'),materialId:'RIMEGLASS',unlockRequirements:[req('monster_mastery','Reach Frostwolf Mastery 20','FROSTWOLF',20)],ascensionMaterialCosts:[{tier:1,itemId:'FROSTIRON',quantity:4},{tier:2,itemId:'RIMEGLASS',quantity:9}]}),
 regional({id:'UNIT_018',name:'Bell Sprite',rarity:'elite',role:'support',region:FROST,archetype:'Tempo Support',description:'A rhythm-based support companion focused on recovery and cooldown tempo.',activeName:'Resonant Chime',activeDescription:'Ring a restorative bell for the lowest-HP ally and accelerate the next support window.',activeTarget:'Lowest-HP ally',effect:'cooldown_reduction',activeValue:.05,cooldown:21,passive:passive('haste',.035,'Bell Rhythm: periodic support effects gain a small tempo boost.','support_cycle'),bondName:'Grand Resonance',bond:passive('haste',.04,'Bond 10 strengthens the Chime’s tempo effect.','resonant_chime'),materialId:'CHOIR_BLOOM',unlockRequirements:[req('achievement','Complete 3 Frostmarch Echoes','FROSTMARCH_ECHOES',3)],ascensionMaterialCosts:[{tier:1,itemId:'FROSTIRON',quantity:4},{tier:2,itemId:'RIMEGLASS',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16}]}),
 regional({id:'UNIT_019',name:'Choir Golem',rarity:'elite',role:'tank',region:FROST,archetype:'Guardian',description:'A resonant guardian that absorbs pressure and creates armour-breaking openings.',activeName:'Choir Bastion',activeDescription:'Raise a resonant defensive stance that blunts incoming damage.',activeTarget:'Self',effect:'damage_reduction',activeValue:.055,cooldown:23,passive:passive('defense_shred',.025,'Cracking Hymn: repeated contact weakens enemy defenses.','sustained_target'),bondName:'Stone Chorus',bond:passive('shield',.045,'Bond 10 improves the Bastion’s protective follow-up.','choir_bastion'),materialId:'FROSTIRON',unlockRequirements:[req('dungeon_clears','Complete all Frostmarch co-op dungeons','FROSTMARCH_DUNGEONS',3)],ascensionMaterialCosts:[{tier:1,itemId:'FROSTIRON',quantity:4},{tier:2,itemId:'RIMEGLASS',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16}]}),
 regional({id:'UNIT_020',name:'Wyrm Echo',rarity:'prestige',role:'damage',region:FROST,archetype:'Champion',description:'A prestigious damage companion that rewards reading dangerous telegraphs.',activeName:"Wyrm's Echo",activeDescription:'Release a heavy frost strike into the current priority target.',activeTarget:'Priority target',effect:'damage',activeValue:1.18,cooldown:18,passive:passive('damage',.045,'Predator Echo: gains damage after surviving major enemy abilities.','boss_telegraph'),bondName:'Wyrm Memory',bond:passive('execute',.08,'Bond 10 gives Wyrm’s Echo stronger finishing pressure.','target_hp_below_30'),materialId:'RIMEGLASS',unlockRequirements:[req('meta','Defeat the Echo of the Wyrmspine companion challenge','CHALLENGE_WYRM_ECHO',1)],ascensionMaterialCosts:[{tier:1,itemId:'FROSTIRON',quantity:4},{tier:2,itemId:'RIMEGLASS',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16},{tier:'mastery',itemId:'CHOIR_BLOOM',quantity:24}]}),
 regional({id:'UNIT_021',name:'Obsidian Drakelet',rarity:'rare',role:'damage',region:ASH,archetype:'Hunter',description:'A blackglass hunter focused on piercing durable targets.',activeName:'Obsidian Fang',activeDescription:'Strike the priority target with an armour-piercing bite.',activeTarget:'Priority target',effect:'armor_pierce',activeValue:.08,cooldown:18,passive:passive('armor_pierce',.045,'Blackglass Teeth: basic attacks periodically ignore part of enemy Defence.','every_4th_attack'),bondName:'Drake Pursuit',bond:passive('damage',.05,'Bond 10 improves pressure against armored targets.','high_defense_target'),materialId:'BANNER_ASH',unlockRequirements:[req('monster_mastery','Reach Blackglass Mireling Mastery 20','BLACKGLASS_MIRELING',20)],ascensionMaterialCosts:[{tier:1,itemId:'BANNER_ASH',quantity:4},{tier:2,itemId:'ASTRAL_SCRIPT',quantity:9}]}),
 regional({id:'UNIT_022',name:'Forge Custodian',rarity:'elite',role:'tank',region:ASH,archetype:'Barrier Guardian',description:'A forge-built defender that creates durable barriers under sustained pressure.',activeName:'Forge Barrier',activeDescription:'Create a heavy barrier around itself before dangerous enemy cycles.',activeTarget:'Self',effect:'shield',activeValue:.055,cooldown:23,passive:passive('damage_reduction',.04,'Tempered Frame: reduces repeated incoming damage.','sustained_damage'),bondName:'Overheat Reprisal',bond:passive('damage',.04,'Bond 10 adds counter-pressure when the barrier expires.','shield_broken'),materialId:'BANNER_ASH',unlockRequirements:[req('dungeon_clears','Complete all Ashlands co-op dungeons','ASHLANDS_DUNGEONS',3)],ascensionMaterialCosts:[{tier:1,itemId:'BANNER_ASH',quantity:4},{tier:2,itemId:'ASTRAL_SCRIPT',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16}]}),
 regional({id:'UNIT_023',name:'Primal Spark',rarity:'elite',role:'damage',region:ASH,archetype:'Artillery',description:'A volatile elemental artillery companion built around rapid chained pressure.',activeName:'Primal Arc',activeDescription:'Release a volatile arc into the priority target.',activeTarget:'Priority target',effect:'chain_damage',activeValue:1.14,cooldown:19,passive:passive('haste',.035,'Static Charge: successful attacks build short bursts of tempo.','attack_chain'),bondName:'Forked Spark',bond:passive('damage',.055,'Bond 10 strengthens Primal Arc’s burst profile.','primal_arc'),materialId:'BANNER_ASH',unlockRequirements:[req('achievement','Complete 3 Ashlands Echoes','ASHLANDS_ECHOES',3)],ascensionMaterialCosts:[{tier:1,itemId:'BANNER_ASH',quantity:4},{tier:2,itemId:'ASTRAL_SCRIPT',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16}]}),
 regional({id:'UNIT_024',name:'Regent Shade',rarity:'prestige',role:'support',region:ASH,archetype:'Champion',description:'A prestigious tactical support companion that adapts to the state of the fight.',activeName:"Regent's Decree",activeDescription:'Issue a tactical decree that stabilizes the most pressured ally.',activeTarget:'Lowest-HP ally',effect:'utility',activeValue:.06,cooldown:22,passive:passive('haste',.04,'Measured Rule: support tempo rises while allies remain healthy.','ally_hp_above_60'),bondName:'Empty Throne',bond:passive('resource_restore',.04,'Bond 10 improves the Decree’s adaptive utility.','regent_decree'),materialId:'BANNER_ASH',unlockRequirements:[req('meta','Defeat The Empty Throne companion challenge','CHALLENGE_REGENT_SHADE',1)],ascensionMaterialCosts:[{tier:1,itemId:'BANNER_ASH',quantity:4},{tier:2,itemId:'ASTRAL_SCRIPT',quantity:9},{tier:3,itemId:'CHOIR_BLOOM',quantity:16},{tier:'mastery',itemId:'CHOIR_BLOOM',quantity:24}]}),
];

export const COMBAT_COMPANIONS:CompanionDefinition[]=[...ASTERFALL_COMPANIONS,...REGIONAL_COMPANIONS,...EVENT_COMPANIONS];
export const combatCompanionDef=(id:string)=>COMBAT_COMPANIONS.find(entry=>entry.id===id);
