import type {CompanionDefinition,CompanionEffectKind,CombatCompanionRarity,CombatCompanionRole} from '../core/combat-companion-types';

type EventCompanionSeed={id:string;name:string;rarity:CombatCompanionRarity;role:CombatCompanionRole;event:string;description:string};
const seeds:EventCompanionSeed[]=[
  {id:'EVT_UNIT_001',name:'Keeper of First Dawn',rarity:'elite',role:'support',event:'turning_of_the_age',description:'Periodically grants Haste and a small shield to the most pressured ally.'},
  {id:'EVT_UNIT_002',name:'Vowbound Cherub',rarity:'prestige',role:'support',event:'heartbond_festival',description:'Links to the lowest-HP ally, reducing incoming damage and periodically healing them.'},
  {id:'EVT_UNIT_003',name:'Bloomwarden',rarity:'elite',role:'tank',event:'bloomwake',description:'Builds a stacking bark shield over time and periodically heals nearby allies.'},
  {id:'EVT_UNIT_004',name:'Suncrest Champion',rarity:'prestige',role:'damage',event:'suncrest_games',description:'Builds Momentum while attacking, then unleashes a radiant strike.'},
  {id:'EVT_UNIT_005',name:'Astral Wayfarer',rarity:'elite',role:'damage',event:'starfall_nights',description:'Attacks build Star Marks; marked targets periodically take an Arcane burst.'},
  {id:'EVT_UNIT_006',name:'Harvest Guardian',rarity:'elite',role:'tank',event:'harvestwake',description:'Stores part of damage received, then converts it into a temporary barrier.'},
  {id:'EVT_UNIT_007',name:'Veil Hound',rarity:'elite',role:'damage',event:'veilbreak',description:'Deals bonus Shadow damage against enemies affected by player-applied debuffs.'},
  {id:'EVT_UNIT_008',name:'Hollow Knightling',rarity:'prestige',role:'tank',event:'veilbreak',description:'Gains defensive scaling as HP falls and a spectral barrier at critical HP.'},
  {id:'EVT_UNIT_009',name:'Frostbell Herald',rarity:'elite',role:'support',event:'frostfall_festival',description:'Rotates between Haste, Ward, and regeneration bell auras.'},
  {id:'EVT_UNIT_010',name:'Caravan Sentinel',rarity:'elite',role:'support',event:'merchant_guild_festival',description:'Adaptive Support: the active buff changes according to party composition.'},
];
const effectFor=(role:CombatCompanionRole):CompanionEffectKind=>role==='damage'?'damage':role==='tank'?'damage_reduction':'haste';
const baseStats=(role:CombatCompanionRole,rarity:CombatCompanionRarity)=>({hp:rarity==='prestige'?225:205,power:role==='damage'?(rarity==='prestige'?28:25):18,defense:role==='tank'?(rarity==='prestige'?27:24):15,attackSpeed:2.2});
export const EVENT_COMPANIONS:readonly CompanionDefinition[]=seeds.map(seed=>{const effect=effectFor(seed.role),amount=effect==='damage'?1.08:effect==='damage_reduction'?.06:.05;return {id:seed.id,name:seed.name,description:seed.description,archetype:`Event ${seed.role}`,role:seed.role,rarity:seed.rarity,origin:{id:`EVENT_${seed.event.toUpperCase()}`,name:seed.event.replaceAll('_',' '),type:'event'},unlockRequirements:[{type:'event_challenge',target:seed.event,description:`Earn ${seed.name} from the ${seed.event.replaceAll('_',' ')} event.`}],baseStats:baseStats(seed.role,seed.rarity),activeAbility:{id:`${seed.id}_ACTIVE`,name:`${seed.name} Signature`,description:seed.description,cooldownSeconds:seed.rarity==='prestige'?24:20,target:seed.role==='support'?'Lowest-HP ally':'Priority target',effect:{kind:effect,value:amount,description:seed.description,durationSeconds:5},scaling:{baseValue:amount,perLevel:effect==='damage'?.004:.001,maxValue:effect==='damage'?1.35:undefined}},passiveAbility:{kind:effect,value:effect==='damage'?.035:.025,description:`${seed.name} reinforces its event identity.`},bondTrait:{id:`${seed.id}_BOND`,name:`${seed.name} Bond`,description:`Bond mastery strengthens the ${seed.name} signature interaction.`,effect:{kind:effect,value:effect==='damage'?.05:.03,description:`Bond mastery strengthens ${seed.name}.`}},ascensionMaterialId:'EVENT_BONDBLOOM',availability:{eventSource:seed.event,recurringAvailability:'annual',veteranCosmeticEligibility:true},visual:{portraitId:seed.id,pixelSize:'96x96',accessibilityLabel:seed.name}}});
