import type {CompanionDefinition,CompanionEffectDefinition,CompanionEffectKind,CombatCompanionRarity,CombatCompanionRole} from '../core/combat-companion-types';

type EventCompanionSeed={
  id:string;name:string;rarity:CombatCompanionRarity;role:CombatCompanionRole;event:string;description:string;archetype:string;
  activeName:string;activeDescription:string;activeKind:CompanionEffectKind;activeValue:number;cooldown:number;target:string;
  passive:CompanionEffectDefinition;bondName:string;bond:CompanionEffectDefinition;
};
const eventNames:Record<string,string>={turning_of_the_age:'Turning of the Age',heartbond_festival:'Heartbond Festival',bloomwake:'Bloomwake',suncrest_games:'Suncrest Games',starfall_nights:'Starfall Nights',harvestwake:'Harvestwake',veilbreak:'The Veilbreak',frostfall_festival:'Frostfall Festival',merchant_guild_festival:'Merchant / Guild Festival'};
const passive=(kind:CompanionEffectKind,value:number,description:string,condition?:string):CompanionEffectDefinition=>({kind,value,description,condition});

const seeds:EventCompanionSeed[]=[
  {id:'EVT_UNIT_001',name:'Keeper of First Dawn',rarity:'elite',role:'support',event:'turning_of_the_age',archetype:'Tempo Support',description:'A dawn herald that protects the most pressured ally while accelerating the party’s opening rhythm.',activeName:'First Dawn Benediction',activeDescription:'Grant a short Haste window and a light protective blessing to the most pressured ally.',activeKind:'haste',activeValue:.05,cooldown:21,target:'Lowest-HP ally',passive:passive('shield',.025,'First Light: the first ally to fall below half HP receives a small protective ward.','ally_below_50'),bondName:'New Year Promise',bond:passive('cooldown_reduction',.05,'Bond 10 shortens the next Benediction after its ward is consumed.','ward_consumed')},
  {id:'EVT_UNIT_002',name:'Vowbound Cherub',rarity:'prestige',role:'support',event:'heartbond_festival',archetype:'Linked Guardian',description:'A ceremonial guardian that links itself to the weakest ally and converts danger into recovery.',activeName:'Vowbound Link',activeDescription:'Link to the lowest-HP ally, reducing incoming pressure and restoring them during the link.',activeKind:'damage_reduction',activeValue:.055,cooldown:22,target:'Lowest-HP ally',passive:passive('resource_restore',.03,'Shared Promise: helping the linked ally restores a small amount of class resource.','linked_ally'),bondName:'Unbroken Vow',bond:passive('shield',.05,'Bond 10 grants the linked ally a small barrier when the link begins.','vowbound_link')},
  {id:'EVT_UNIT_003',name:'Bloomwarden',rarity:'elite',role:'tank',event:'bloomwake',archetype:'Regrowth Tank',description:'A living bulwark that layers bark protection and turns endurance into gradual recovery.',activeName:'Barkheart Ward',activeDescription:'Raise a stacking bark barrier before incoming pressure.',activeKind:'shield',activeValue:.055,cooldown:22,target:'Self',passive:passive('damage_reduction',.04,'Regrowth: repeated damage strengthens the Warden’s defensive rhythm.','sustained_damage'),bondName:'Ancient Bloom',bond:passive('shield',.05,'Bond 10 strengthens the follow-up barrier after Barkheart Ward breaks.','shield_broken')},
  {id:'EVT_UNIT_004',name:'Suncrest Champion',rarity:'prestige',role:'damage',event:'suncrest_games',archetype:'Momentum Striker',description:'A tournament champion that builds pressure through repeated attacks before delivering a radiant finisher.',activeName:'Suncrest Momentum',activeDescription:'Release accumulated tournament momentum as a powerful radiant strike.',activeKind:'damage',activeValue:1.12,cooldown:18,target:'Priority target',passive:passive('haste',.035,'Crowd Momentum: successful attacks briefly increase combat tempo.','attack_chain'),bondName:'Victory Lap',bond:passive('execute',.08,'Bond 10 strengthens the finishing strike against weakened enemies.','target_hp_below_30')},
  {id:'EVT_UNIT_005',name:'Astral Wayfarer',rarity:'elite',role:'damage',event:'starfall_nights',archetype:'Marking Caster',description:'A celestial hunter that marks a target and rewards sustained focus on the same enemy.',activeName:'Starfall Mark',activeDescription:'Strike the priority target and mark it for follow-up astral pressure.',activeKind:'damage',activeValue:1.10,cooldown:19,target:'Priority target',passive:passive('damage',.04,'Constellation Hunter: deals more damage while maintaining the same target.','same_target'),bondName:'Falling Star',bond:passive('execute',.07,'Bond 10 turns marked targets into stronger finishing opportunities.','target_debuffed')},
  {id:'EVT_UNIT_006',name:'Harvest Guardian',rarity:'elite',role:'tank',event:'harvestwake',archetype:'Barrier Tank',description:'A harvest sentinel that stores part of incoming pressure and returns it as a protective barrier.',activeName:'Harvest Bulwark',activeDescription:'Convert stored pressure into a temporary harvest barrier.',activeKind:'damage_reduction',activeValue:.055,cooldown:22,target:'Self',passive:passive('shield',.03,'Stored Harvest: sustained damage prepares a small follow-up barrier.','sustained_damage'),bondName:'Full Granary',bond:passive('shield',.05,'Bond 10 increases the barrier created after heavy pressure.','heavy_hit')},
  {id:'EVT_UNIT_007',name:'Veil Hound',rarity:'elite',role:'damage',event:'veilbreak',archetype:'Debuff Hunter',description:'A spectral hunter that becomes more dangerous when allies have already weakened the target.',activeName:'Veil Rend',activeDescription:'Rend the priority target, gaining extra pressure when it is already debuffed.',activeKind:'damage',activeValue:1.10,cooldown:19,target:'Debuffed enemy',passive:passive('damage',.05,'Veil Hunter: deals increased damage to enemies with a player-applied debuff.','target_debuffed'),bondName:'Deep Veil',bond:passive('execute',.07,'Bond 10 strengthens Veil Rend against critically weakened targets.','target_hp_below_30')},
  {id:'EVT_UNIT_008',name:'Hollow Knightling',rarity:'prestige',role:'tank',event:'veilbreak',archetype:'Last-Stand Tank',description:'A void-forged knight that becomes harder to break as its health falls.',activeName:'Hollow Last Stand',activeDescription:'Gain a spectral mitigation barrier, with the strongest value at low HP.',activeKind:'damage_reduction',activeValue:.065,cooldown:22,target:'Self',passive:passive('damage_reduction',.05,'Hollow Resolve: mitigation increases during critical-health windows.','low_hp'),bondName:'Last Lantern',bond:passive('shield',.055,'Bond 10 grants a stronger once-per-fight emergency barrier.','critical_hp')},
  {id:'EVT_UNIT_009',name:'Frostbell Herald',rarity:'elite',role:'support',event:'frostfall_festival',archetype:'Rhythm Support',description:'A winter herald that cycles supportive bell effects instead of repeating one generic heal.',activeName:'Frostbell Chorus',activeDescription:'Ring the next bell in the Chorus, providing Haste, Ward, or recovery support.',activeKind:'haste',activeValue:.05,cooldown:21,target:'Lowest-HP ally',passive:passive('resource_restore',.03,'Winter Rhythm: every support cycle restores a small amount of class resource.','support_cycle'),bondName:'Grand Chorus',bond:passive('cooldown_reduction',.05,'Bond 10 speeds the next bell after helping a critically wounded ally.','ally_below_35')},
  {id:'EVT_UNIT_010',name:'Caravan Sentinel',rarity:'elite',role:'support',event:'merchant_guild_festival',archetype:'Adaptive Support',description:'A caravan guardian whose utility shifts toward defense or tempo depending on the party around it.',activeName:'Caravan Formation',activeDescription:'Adopt a formation that stabilizes the priority ally and improves party tempo.',activeKind:'utility',activeValue:.055,cooldown:21,target:'Lowest-HP ally',passive:passive('defense',.035,'Loaded for Anything: gains extra defensive value in mixed-role parties.','mixed_party'),bondName:'Long Road',bond:passive('haste',.04,'Bond 10 improves Formation tempo after long encounters.','long_encounter')},
];

const baseStats=(role:CombatCompanionRole,rarity:CombatCompanionRarity)=>({hp:rarity==='prestige'?225:205,power:role==='damage'?(rarity==='prestige'?28:25):18,defense:role==='tank'?(rarity==='prestige'?27:24):15,attackSpeed:2.2});
const ascensionCosts=(rarity:CombatCompanionRarity):CompanionDefinition['ascensionMaterialCosts']=>rarity==='prestige'
 ?[{tier:1,itemId:'EVENT_BONDBLOOM',quantity:4},{tier:2,itemId:'EVENT_BONDBLOOM',quantity:8},{tier:3,itemId:'EVENT_BONDBLOOM',quantity:12},{tier:'mastery',itemId:'EVENT_BONDBLOOM',quantity:18}]
 :[{tier:1,itemId:'EVENT_BONDBLOOM',quantity:4},{tier:2,itemId:'EVENT_BONDBLOOM',quantity:8},{tier:3,itemId:'EVENT_BONDBLOOM',quantity:12}];

export const EVENT_COMPANIONS:readonly CompanionDefinition[]=seeds.map(seed=>({
  id:seed.id,name:seed.name,description:seed.description,archetype:seed.archetype,role:seed.role,rarity:seed.rarity,
  origin:{id:`EVENT_${seed.event.toUpperCase()}`,name:eventNames[seed.event]??seed.event.replaceAll('_',' '),type:'event'},
  unlockRequirements:[{type:'event_challenge',target:seed.event,description:`Earn ${seed.name} from ${eventNames[seed.event]??seed.event.replaceAll('_',' ')}.`}],
  baseStats:baseStats(seed.role,seed.rarity),
  activeAbility:{id:`${seed.id}_ACTIVE`,name:seed.activeName,description:seed.activeDescription,cooldownSeconds:seed.cooldown,target:seed.target,effect:{kind:seed.activeKind,value:seed.activeValue,description:seed.activeDescription,durationSeconds:5},scaling:{baseValue:seed.activeValue,perLevel:seed.activeKind==='damage'?.004:.001,maxValue:seed.activeKind==='damage'?1.35:undefined}},
  passiveAbility:seed.passive,
  bondTrait:{id:`${seed.id}_BOND`,name:seed.bondName,description:seed.bond.description,effect:seed.bond},
  ascensionMaterialId:'EVENT_BONDBLOOM',ascensionMaterialCosts:ascensionCosts(seed.rarity),
  availability:{eventSource:eventNames[seed.event]??seed.event,originalReleaseYear:2026,recurringAvailability:'annual',veteranCosmeticEligibility:true},
  visual:{portraitId:seed.id,pixelSize:'96x96',accessibilityLabel:seed.name}
}));
