export type GuildSkillNode={id:string;major:string;name:string;scope:string;summary:string;label:string;perTier:number;costs:Array<Record<string,number>>};
export const GUILD_SKILL_NODES:GuildSkillNode[]=[
 {id:'professions_gathering',major:'Professions',name:'Gathering',scope:'NON-COMBAT',summary:'Gathering speed and yield from regional activities.',label:'Gathering speed',perTier:2,costs:[{MOSS_FIBER:300,GREENWOOD_LOG:150},{IRONWOOD_LOG:350,ASTER_IRON_INGOT:40},{IRONWOOD_LOG:700,ASTER_IRON_INGOT:110}]},
 {id:'professions_crafting',major:'Professions',name:'Crafting',scope:'NON-COMBAT',summary:'Crafting speed and production efficiency.',label:'Crafting speed',perTier:2,costs:[{MOSS_FIBER:400,GREENWOOD_LOG:200},{IRONWOOD_LOG:400,ASTER_IRON_INGOT:60},{IRONWOOD_LOG:800,ASTER_IRON_INGOT:150}]},
 {id:'professions_mastery',major:'Professions',name:'Skilling Mastery',scope:'NON-COMBAT',summary:'Experience earned from skilling and processing.',label:'Skill XP',perTier:2,costs:[{MOSS_FIBER:500,GREENWOOD_LOG:250},{IRONWOOD_LOG:500,ASTER_IRON_INGOT:80},{IRONWOOD_LOG:900,ASTER_IRON_INGOT:180}]},
 {id:'fellowship_membership',major:'Fellowship',name:'Membership',scope:'GUILD SYSTEMS',summary:'Member capacity, roles and recruitment tools.',label:'Member capacity',perTier:1,costs:[{MOSS_FIBER:500,GREENWOOD_LOG:250},{IRONWOOD_LOG:600,ASTER_IRON_INGOT:80},{IRONWOOD_LOG:1100,ASTER_IRON_INGOT:180}]},
 {id:'fellowship_quests',major:'Fellowship',name:'Guild Quests',scope:'GUILD SYSTEMS',summary:'Rewards and variety from cooperative Guild Quests.',label:'Guild Quest rewards',perTier:2,costs:[{MOSS_FIBER:500,GREENWOOD_LOG:250},{IRONWOOD_LOG:500,ASTER_IRON_INGOT:80},{IRONWOOD_LOG:900,ASTER_IRON_INGOT:180}]},
 {id:'fellowship_projects',major:'Fellowship',name:'Projects & Cooperation',scope:'GUILD SYSTEMS',summary:'Project choices, contribution efficiency and shared unlocks.',label:'Project efficiency',perTier:2,costs:[{MOSS_FIBER:600,GREENWOOD_LOG:300},{IRONWOOD_LOG:700,ASTER_IRON_INGOT:100},{IRONWOOD_LOG:1200,ASTER_IRON_INGOT:225}]},
 {id:'vanguard_boss',major:'Vanguard',name:'Guild Boss',scope:'GUILD CONTENT ONLY',summary:'Damage and reward contribution against Guild Bosses.',label:'Guild PvE damage',perTier:2,costs:[{IRONWOOD_LOG:400,ASTER_IRON_INGOT:100},{ASTER_IRON_INGOT:225,OATHGLASS_SHARD:40},{OATHSTONE_INGOT:120,OATHGLASS_SHARD:80}]},
 {id:'vanguard_defence',major:'Vanguard',name:'Defensive Doctrine',scope:'GUILD CONTENT ONLY',summary:'Guild defence, mitigation and support during group PvE.',label:'Guild defence',perTier:2,costs:[{IRONWOOD_LOG:450,ASTER_IRON_INGOT:110},{ASTER_IRON_INGOT:250,OATHGLASS_SHARD:50},{OATHSTONE_INGOT:140,OATHGLASS_SHARD:90}]},
 {id:'vanguard_support',major:'Vanguard',name:'Battle Support',scope:'GUILD CONTENT ONLY',summary:'Support effects and shared contribution in guild encounters.',label:'Guild support',perTier:2,costs:[{IRONWOOD_LOG:500,ASTER_IRON_INGOT:120},{ASTER_IRON_INGOT:275,OATHGLASS_SHARD:60},{OATHSTONE_INGOT:160,OATHGLASS_SHARD:100}]},
];
export const GUILD_MAJOR_BRANCHES=['Professions','Fellowship','Vanguard'] as const;
