import { ClassId,GatheringSkillId,GearSlot,GemEffectId,GemSocketKind,GemStat } from '../core/types';
import {ItemRarity} from '../core/item-rarity';
import {NOVICE_ITEMS} from './novice-sets';
import {TOOL_ITEMS} from './gathering-tools';
import {HERB_ITEMS} from './herbalism';
import {POTION_ITEMS} from './alchemy';
import {EQUIPMENT_ITEMS_V33} from './equipment-items-v33';
import {GEM_ITEMS_V1,type MobileGemGradeV1} from './gems-v1';
export interface ItemDef {
  id:string; name:string; type:'material'|'gear'|'quest'|'food'|'tool'|'gem'|'potion'; slot?:GearSlot;
  attack?:number; defense?:number; hp?:number; heal?:number; readiness?:number;
  toolSkillId?:GatheringSkillId;toolTier?:number;actionTimeMultiplier?:number;
  rarity?:ItemRarity; passive?:string;
  value:number; salvage?:{itemId:string;quantity:number};
  classRestriction?:ClassId; requiredLevel?:number; noviceSetId?:string; equipmentSetId?:string;
  gemStat?:GemStat; gemPercent?:number; gemTier?:MobileGemGradeV1; gemKind?:GemSocketKind; gemEffect?:GemEffectId; gemEffectValue?:number;
  /** Canonical five-grade gem identity. Legacy shards/sigils omit these fields and remain migration-compatible. */
  gemFamilyId?:string; gemGrade?:MobileGemGradeV1;
}

const COMPLETE_SET_SLOTS:GearSlot[]=['helmet','legs','boots','weapon','offhand','amulet'];
const COMPLETE_SET_CONFIG:Array<{id:string;prefix:string;label:string;classId:ClassId;rarity:ItemRarity;readiness:number;value:number;weapon:string;offhand:string}>=[
  {id:'rootbound_covenant',prefix:'STONEHEART',label:'Stoneheart',classId:'IRONWARDEN',rarity:'rare',readiness:13,value:520,weapon:'Rootbound Blade',offhand:'Rootbound Shield'},
  {id:'lastwall_panoply',prefix:'LASTWALL',label:'Lastwall',classId:'BASTION',rarity:'rare',readiness:13,value:530,weapon:'Lastwall Mace',offhand:'Lastwall Tower Shield'},
  {id:'mournchain_harness',prefix:'MOURNCHAIN',label:'Mournchain',classId:'DREADGUARD',rarity:'rare',readiness:14,value:540,weapon:'Mournchain Flail',offhand:'Mournchain Shield'},
  {id:'thread_of_dawn',prefix:'QUICKPRAYER',label:'Quickprayer',classId:'DAWNKEEPER',rarity:'rare',readiness:13,value:520,weapon:'Dawn Mace',offhand:'Sun Reliquary'},
  {id:'regretwalker',prefix:'TRACKER',label:'Regretwalker',classId:'WAYFINDER',rarity:'rare',readiness:14,value:530,weapon:'Tracker Bow',offhand:'Tracker Knife'},
  {id:'lanternsteel_array',prefix:'BLOODRUSH',label:'Lanternsteel',classId:'RAVAGER',rarity:'rare',readiness:14,value:540,weapon:'Lanternsteel Greataxe',offhand:'Lanternsteel War Charm'},
  {id:'glassbound_script',prefix:'SPELLGLASS',label:'Glassbound',classId:'HEXWEAVER',rarity:'rare',readiness:14,value:530,weapon:'Spellglass Wand',offhand:'Glassbound Tome'},
  {id:'gloamstep_regalia',prefix:'NIGHTFANG',label:'Gloamstep',classId:'KNIFE_DANCER',rarity:'rare',readiness:14,value:530,weapon:'Nightfang Dagger',offhand:'Nightfang Off-Dagger'},
  {id:'resonant_tempest',prefix:'STORMCARVED',label:'Stormcarved',classId:'STONECALLER',rarity:'rare',readiness:14,value:530,weapon:'Tempest Staff',offhand:'Resonant Totem'},
  {id:'glassward_covenant',prefix:'SUNSCORED_STONEHEART',label:'Glassward',classId:'IRONWARDEN',rarity:'epic',readiness:27,value:1180,weapon:'Glassward Blade',offhand:'Glassward Shield'},
  {id:'sunvault_panoply',prefix:'SUNSCORED_LASTWALL',label:'Sunvault',classId:'BASTION',rarity:'epic',readiness:27,value:1190,weapon:'Sunvault Mace',offhand:'Sunvault Tower Shield'},
  {id:'cinderchain_harness',prefix:'SUNSCORED_MOURNCHAIN',label:'Cinderchain',classId:'DREADGUARD',rarity:'epic',readiness:28,value:1200,weapon:'Cinderchain Flail',offhand:'Cinderchain Shield'},
  {id:'dawn_of_saffron',prefix:'SUNSCORED_QUICKPRAYER',label:'Saffron Dawn',classId:'DAWNKEEPER',rarity:'epic',readiness:27,value:1180,weapon:'Saffron Mace',offhand:'Saffron Sun Reliquary'},
  {id:'mirage_hunter',prefix:'SUNSCORED_TRACKER',label:'Mirage Hunter',classId:'WAYFINDER',rarity:'epic',readiness:29,value:1190,weapon:'Mirage Bow',offhand:'Mirage Knife'},
  {id:'scorchblood_array',prefix:'SUNSCORED_BLOODRUSH',label:'Scorchblood',classId:'RAVAGER',rarity:'epic',readiness:29,value:1200,weapon:'Scorchblood Greataxe',offhand:'Scorchblood War Charm'},
  {id:'astral_script',prefix:'SUNSCORED_SPELLGLASS',label:'Astral Script',classId:'HEXWEAVER',rarity:'epic',readiness:28,value:1190,weapon:'Astral Wand',offhand:'Astral Tome'},
  {id:'dunestep_regalia',prefix:'SUNSCORED_NIGHTFANG',label:'Dunestep',classId:'KNIFE_DANCER',rarity:'epic',readiness:30,value:1190,weapon:'Dunestep Dagger',offhand:'Dunestep Off-Dagger'},
  {id:'oasis_resonance',prefix:'SUNSCORED_STORMCARVED',label:'Oasis Resonance',classId:'STONECALLER',rarity:'epic',readiness:28,value:1190,weapon:'Oasis Staff',offhand:'Oasis Totem'},
  {id:'rimewall_oath',prefix:'RIMEBOUND_STONEHEART',label:'Rimewall',classId:'IRONWARDEN',rarity:'epic',readiness:34,value:2100,weapon:'Rimewall Blade',offhand:'Rimewall Shield'},
];
const FROSTMARCH_SET_CONFIG:Array<{id:string;prefix:string;label:string;classId:ClassId;weapon:string;offhand:string}>=[
  {id:'frostbell_panoply',prefix:'RIMEBOUND_LASTWALL',label:'Frostbell',classId:'BASTION',weapon:'Frostbell Mace',offhand:'Frostbell Tower Shield'},
  {id:'winterchain_harness',prefix:'RIMEBOUND_MOURNCHAIN',label:'Winterchain',classId:'DREADGUARD',weapon:'Winterchain Flail',offhand:'Winterchain Shield'},
  {id:'aurora_vespers',prefix:'RIMEBOUND_QUICKPRAYER',label:'Aurora Vespers',classId:'DAWNKEEPER',weapon:'Aurora Mace',offhand:'Aurora Sun Focus'},
  {id:'whiteout_stalker',prefix:'RIMEBOUND_TRACKER',label:'Whiteout Stalker',classId:'WAYFINDER',weapon:'Whiteout Bow',offhand:'Whiteout Hunting Knife'},
  {id:'glacierblood_array',prefix:'RIMEBOUND_BLOODRUSH',label:'Glacierblood',classId:'RAVAGER',weapon:'Glacierblood Greataxe',offhand:'Frozen War Charm'},
  {id:'rimeglass_script',prefix:'RIMEBOUND_SPELLGLASS',label:'Rimeglass',classId:'HEXWEAVER',weapon:'Rimeglass Wand',offhand:'Rimeglass Tome'},
  {id:'snowveil_regalia',prefix:'RIMEBOUND_NIGHTFANG',label:'Snowveil',classId:'KNIFE_DANCER',weapon:'Snowveil Dagger',offhand:'Snowveil Off-Dagger'},
  {id:'choirfrost_resonance',prefix:'RIMEBOUND_STORMCARVED',label:'Choirfrost',classId:'STONECALLER',weapon:'Choirfrost Staff',offhand:'Choir-Stone Totem'},
];
const slotLabel:Record<GearSlot,string>={helmet:'Helm',chest:'Chest',gloves:'Gloves',legs:'Legguards',boots:'Boots',weapon:'Weapon',offhand:'Offhand',cape:'Cape',amulet:'Amulet',ring:'Ring'};
const COMPLETE_SET_ADDITIONAL_ITEMS:ItemDef[]=COMPLETE_SET_CONFIG.flatMap(set=>COMPLETE_SET_SLOTS.map(slot=>{
  const tank=set.classId==='IRONWARDEN'||set.classId==='BASTION'||set.classId==='DREADGUARD';
  const stats=slot==='helmet'?{defense:tank?11:7,hp:tank?58:38}:slot==='legs'?{defense:tank?12:8,hp:tank?68:46}:slot==='boots'?{defense:tank?8:5,hp:tank?42:28}:slot==='weapon'?{attack:tank?16:19,defense:tank?2:0}:slot==='offhand'?{attack:tank?2:8,defense:tank?11:3,hp:tank?54:24}:{attack:6,defense:5,hp:34};
  const name=slot==='weapon'?set.weapon:slot==='offhand'?set.offhand:`${set.label} ${slotLabel[slot]}`;
  return {id:`${set.prefix}_${slot.toUpperCase()}`,name,type:'gear' as const,slot,...stats,readiness:set.readiness,value:set.value,rarity:set.rarity,classRestriction:set.classId,equipmentSetId:set.id};
}));
const FROSTMARCH_SET_ITEMS:ItemDef[]=FROSTMARCH_SET_CONFIG.flatMap(set=>(Object.keys(slotLabel) as GearSlot[]).map(slot=>{
  const tank=set.classId==='BASTION'||set.classId==='DREADGUARD';
  const stats=slot==='helmet'?{attack:tank?3:6,defense:tank?15:10,hp:tank?82:54}:slot==='chest'?{attack:tank?5:10,defense:tank?21:14,hp:tank?132:84}:slot==='gloves'?{attack:tank?3:8,defense:tank?12:8,hp:tank?58:38}:slot==='legs'?{attack:tank?3:7,defense:tank?17:11,hp:tank?94:62}:slot==='boots'?{attack:tank?2:6,defense:tank?11:7,hp:tank?55:36}:slot==='weapon'?{attack:tank?23:29,defense:tank?4:1}:slot==='offhand'?{attack:tank?4:12,defense:tank?17:5,hp:tank?78:34}:slot==='cape'?{attack:tank?5:10,defense:tank?12:8,hp:tank?72:48}:slot==='amulet'?{attack:9,defense:7,hp:44}:{attack:8,defense:6,hp:36};
  const name=slot==='weapon'?set.weapon:slot==='offhand'?set.offhand:`${set.label} ${slotLabel[slot]}`;
  const salvage={itemId:slot==='cape'?'CHOIR_BLOOM':'RIMEGLASS',quantity:slot==='chest'?4:slot==='legs'||slot==='weapon'||slot==='offhand'?3:2};
  return {id:`${set.prefix}_${slot.toUpperCase()}`,name,type:'gear' as const,slot,...stats,readiness:34,value:slot==='chest'?2420:slot==='weapon'||slot==='offhand'?2280:2100,rarity:'epic',classRestriction:set.classId,equipmentSetId:set.id,salvage};
}));
const BASE_ITEMS:ItemDef[]=[
...NOVICE_ITEMS,
{id:'HOLY_WATER',name:'Holy Water',type:'material',value:0,rarity:'uncommon'},
...COMPLETE_SET_ADDITIONAL_ITEMS,
...FROSTMARCH_SET_ITEMS,
...TOOL_ITEMS,
...HERB_ITEMS,
...POTION_ITEMS,
// Enhancement economy. Gems are intentionally scarce drops; tempering materials are universal.
{id:'GEM_DUST',name:'Gem Dust',type:'material',value:18,rarity:'uncommon'},
{id:'REGIONAL_CATALYST',name:'Regional Catalyst',type:'material',value:650,rarity:'epic'},
{id:'RADIANT_CATALYST',name:'Radiant Catalyst',type:'material',value:2400,rarity:'mythic'},
...GEM_ITEMS_V1,
{id:'TEMPERING_DUST',name:'Tempering Dust',type:'material',value:22,rarity:'uncommon'},
{id:'TEMPERING_CORE',name:'Tempering Core',type:'material',value:180,rarity:'rare'},
{id:'EMBER_SHARD',name:'Ember Shard',type:'gem',gemStat:'attack',gemPercent:.02,gemTier:1,value:320,rarity:'rare'},
{id:'EMBERHEART_GEM',name:'Emberheart Gem',type:'gem',gemStat:'attack',gemPercent:.05,gemTier:2,value:1900,rarity:'legendary'},
{id:'WARD_SHARD',name:'Ward Shard',type:'gem',gemStat:'defense',gemPercent:.02,gemTier:1,value:320,rarity:'rare'},
{id:'WARDHEART_GEM',name:'Wardheart Gem',type:'gem',gemStat:'defense',gemPercent:.05,gemTier:2,value:1900,rarity:'legendary'},
{id:'VITALITY_SHARD',name:'Vitality Shard',type:'gem',gemStat:'hp',gemPercent:.02,gemTier:1,value:320,rarity:'rare'},
{id:'VITALITY_HEART_GEM',name:'Vitality Heart Gem',type:'gem',gemStat:'hp',gemPercent:.05,gemTier:2,value:1900,rarity:'legendary'},
// Effect Gems occupy the dedicated Effect socket. They modify combat behavior rather than primary stats.
{id:'SWIFT_SIGIL',name:'Swift Sigil',type:'gem',gemKind:'effect',gemEffect:'combat_speed',gemEffectValue:.02,gemTier:1,value:520,rarity:'rare',passive:'+2% combat speed while equipped'},
{id:'BOSSBANE_SIGIL',name:'Bossbane Sigil',type:'gem',gemKind:'effect',gemEffect:'boss_power',gemEffectValue:.03,gemTier:1,value:620,rarity:'rare',passive:'+3% combat power against bosses'},
{id:'BULWARK_SIGIL',name:'Bulwark Sigil',type:'gem',gemKind:'effect',gemEffect:'damage_reduction',gemEffectValue:.02,gemTier:1,value:620,rarity:'rare',passive:'-2% incoming combat damage'},
{id:'RENEWAL_SIGIL',name:'Renewal Sigil',type:'gem',gemKind:'effect',gemEffect:'recovery',gemEffectValue:.10,gemTier:1,value:560,rarity:'rare',passive:'+10% between-kill recovery'},
// Runtime pack weapon identities; numeric budgets retained from the prior primary weapons.
{id:'basic_sword',name:'Basic Sword',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'basic_tower_shield',name:'Basic Tower Shield',type:'gear',slot:'weapon',attack:3,defense:1,readiness:1,value:10},
{id:'basic_chained_weapon',name:'Basic Chained Weapon',type:'gear',slot:'weapon',attack:5,readiness:1,value:10},
{id:'basic_mace',name:'Basic Mace',type:'gear',slot:'weapon',attack:3,defense:1,readiness:1,value:10},
{id:'basic_bow',name:'Basic Bow',type:'gear',slot:'weapon',attack:5,readiness:1,value:10},
{id:'basic_two_handed_weapon',name:'Basic Two-Handed Weapon',type:'gear',slot:'weapon',attack:6,defense:-1,readiness:1,value:10},
{id:'basic_wand',name:'Basic Wand',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'basic_main_hand_blade',name:'Basic Main-Hand Blade',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'basic_staff',name:'Basic Staff',type:'gear',slot:'weapon',attack:4,hp:5,readiness:1,value:10},
{id:'START_IRON_SWORD',name:'Recruit Sword',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'START_KITE_SHIELD',name:'Recruit Kite Shield',type:'gear',slot:'offhand',defense:3,hp:8,readiness:1,value:10},
{id:'START_BASTION_MACE',name:'Recruit Mace',type:'gear',slot:'weapon',attack:3,defense:1,readiness:1,value:10},
{id:'START_TOWER_SHIELD',name:'Recruit Tower Shield',type:'gear',slot:'offhand',defense:4,hp:10,readiness:1,value:10},
{id:'START_DREAD_AXE',name:'Dread Iron Axe',type:'gear',slot:'weapon',attack:5,readiness:1,value:10},
{id:'START_SPIKED_SHIELD',name:'Spiked Recruit Shield',type:'gear',slot:'offhand',attack:1,defense:2,hp:6,readiness:1,value:10},
{id:'START_DAWN_MACE',name:'Dawn Acolyte Mace',type:'gear',slot:'weapon',attack:3,defense:1,readiness:1,value:10},
{id:'START_HOLY_FOCUS',name:'Acolyte Sun Focus',type:'gear',slot:'offhand',hp:10,readiness:1,value:10},
{id:'START_SHORTBOW',name:'Greenwood Shortbow',type:'gear',slot:'weapon',attack:5,readiness:1,value:10},
{id:'START_RAVAGER_AXE',name:'Rough Two-Handed Axe',type:'gear',slot:'weapon',attack:6,defense:-1,readiness:1,value:10},
{id:'START_HEX_WAND',name:'Apprentice Hex Wand',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'START_HEX_TOME',name:'Faded Hex Tome',type:'gear',slot:'offhand',attack:1,hp:5,readiness:1,value:10},
{id:'START_DAGGER',name:'Practice Dagger',type:'gear',slot:'weapon',attack:4,readiness:1,value:10},
{id:'START_OFF_DAGGER',name:'Practice Off-Dagger',type:'gear',slot:'offhand',attack:2,readiness:1,value:10},
{id:'START_STONE_STAFF',name:'Carved Stone Staff',type:'gear',slot:'weapon',attack:4,hp:5,readiness:1,value:10},
{id:'START_STONE_TOTEM',name:'Pebble Totem',type:'gear',slot:'offhand',attack:1,defense:1,readiness:1,value:10},

{id:'TRAVEL_RATION',name:'Travel Ration',type:'food',heal:35,readiness:1,value:5},
{id:'COOKED_SILVERFIN',name:'Cooked Silverfin',type:'food',heal:55,readiness:3,value:15},
{id:'SEARED_RIVER_EEL',name:'Seared River Eel',type:'food',heal:95,readiness:5,value:34},
{id:'IRONWOOD_STEW',name:'Ironwood Hunter Stew',type:'food',heal:145,readiness:7,value:62},

{id:'COPPER_ORE',name:'Copper Ore',type:'material',value:5},

{id:'OATHSTONE_ORE',name:'Oathstone Ore',type:'material',value:32},
{id:'CROWNWOOD_LOG',name:'Crownwood Log',type:'material',value:30},
{id:'OATHSCALE_PIKE',name:'Oathscale Pike',type:'material',value:32},
{id:'COPPER_INGOT',name:'Copper Ingot',type:'material',value:28},
{id:'ASTER_IRON_INGOT',name:'Aster-Iron Ingot',type:'material',value:64},
{id:'OATHSTONE_INGOT',name:'Oathstone Ingot',type:'material',value:145},
{id:'REINFORCED_FITTING',name:'Reinforced Fitting',type:'material',value:155},
{id:'ROASTED_OATHSCALE',name:'Roasted Oathscale Pike',type:'food',heal:175,readiness:8,value:90},
{id:'OATHSTONE_HELM',name:'Oathstone Greathelm',type:'gear',slot:'helmet',defense:11,hp:62,readiness:12,value:520,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:3}},
{id:'OATHSTONE_WARDPLATE',name:'Oathstone Wardplate',type:'gear',slot:'chest',defense:15,hp:105,readiness:16,value:680,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:5},passive:'Stonewall: +4% damage mitigation.'},
{id:'OATHSTONE_GAUNTLETS',name:'Oathstone Gauntlets',type:'gear',slot:'gloves',defense:8,hp:42,readiness:12,value:460,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:3}},
{id:'OATHSTONE_LEGPLATES',name:'Oathstone Legplates',type:'gear',slot:'legs',defense:12,hp:74,readiness:14,value:590,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:4}},
{id:'OATHSTONE_GREAVES',name:'Oathstone Greaves',type:'gear',slot:'boots',defense:8,hp:46,readiness:12,value:470,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:3}},
{id:'OATHSTONE_BLADE',name:'Oathstone Runeblade',type:'gear',slot:'weapon',attack:19,defense:3,readiness:14,value:650,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:4}},
{id:'OATHSTONE_TOWER_SHIELD',name:'Oathstone Tower Shield',type:'gear',slot:'offhand',defense:14,hp:70,readiness:15,value:640,rarity:'epic',salvage:{itemId:'OATHSTONE_INGOT',quantity:4}},
{id:'OATHSTONE_MANTLE',name:'Oathstone Mantle',type:'gear',slot:'cape',attack:3,defense:7,hp:48,readiness:13,value:560,rarity:'epic',salvage:{itemId:'OATHGLASS_SHARD',quantity:3}},
{id:'OATHSTONE_AMULET',name:'Oathstone Ward Amulet',type:'gear',slot:'amulet',attack:4,defense:5,hp:38,readiness:13,value:540,rarity:'epic',salvage:{itemId:'OATHGLASS_SHARD',quantity:3}},
{id:'OATHSTONE_SIGNET',name:'Oathstone Signet',type:'gear',slot:'ring',attack:4,defense:4,hp:30,readiness:12,value:510,rarity:'epic',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},

{id:'STONEHEART_CHEST',name:'Stoneheart Chest',type:'gear',slot:'chest',defense:14,hp:88,readiness:14,value:610,rarity:'rare',classRestriction:'IRONWARDEN',equipmentSetId:'rootbound_covenant',salvage:{itemId:'OATHSTONE_INGOT',quantity:4}},
{id:'STONEHEART_GLOVES',name:'Stoneheart Gloves',type:'gear',slot:'gloves',defense:7,hp:36,readiness:12,value:455,rarity:'rare',classRestriction:'IRONWARDEN',equipmentSetId:'rootbound_covenant',salvage:{itemId:'OATHSTONE_INGOT',quantity:2}},
{id:'STONEHEART_CAPE',name:'Stoneheart Cape',type:'gear',slot:'cape',defense:6,hp:46,readiness:13,value:520,rarity:'rare',classRestriction:'IRONWARDEN',equipmentSetId:'rootbound_covenant',salvage:{itemId:'THORN_SAP',quantity:5}},
{id:'STONEHEART_RING',name:'Stoneheart Ring',type:'gear',slot:'ring',defense:4,hp:32,readiness:12,value:480,rarity:'rare',classRestriction:'IRONWARDEN',equipmentSetId:'rootbound_covenant',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
{id:'LASTWALL_CHEST',name:'Lastwall Chestguard',type:'gear',slot:'chest',defense:16,hp:100,readiness:13,value:625,rarity:'rare',classRestriction:'BASTION',equipmentSetId:'lastwall_panoply',salvage:{itemId:'OATHSTONE_INGOT',quantity:4}},
{id:'LASTWALL_GLOVES',name:'Lastwall Gauntlets',type:'gear',slot:'gloves',defense:8,hp:42,readiness:11,value:470,rarity:'rare',classRestriction:'BASTION',equipmentSetId:'lastwall_panoply',salvage:{itemId:'LANTERNSTEEL_SHARD',quantity:2}},
{id:'LASTWALL_CAPE',name:'Lastwall Mantle',type:'gear',slot:'cape',defense:7,hp:54,readiness:12,value:540,rarity:'rare',classRestriction:'BASTION',equipmentSetId:'lastwall_panoply',salvage:{itemId:'TORN_OATHCLOTH',quantity:4}},
{id:'LASTWALL_RING',name:'Lastwall Signet',type:'gear',slot:'ring',defense:5,hp:38,readiness:11,value:500,rarity:'rare',classRestriction:'BASTION',equipmentSetId:'lastwall_panoply',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
{id:'MOURNCHAIN_CHEST',name:'Mournchain Cuirass',type:'gear',slot:'chest',attack:4,defense:12,hp:82,readiness:15,value:650,rarity:'rare',classRestriction:'DREADGUARD',equipmentSetId:'mournchain_harness',salvage:{itemId:'LANTERNSTEEL_SHARD',quantity:4}},
{id:'MOURNCHAIN_GLOVES',name:'Mournchain Grips',type:'gear',slot:'gloves',attack:4,defense:6,hp:30,readiness:14,value:490,rarity:'rare',classRestriction:'DREADGUARD',equipmentSetId:'mournchain_harness',salvage:{itemId:'FALLEN_RIVET',quantity:3}},
{id:'MOURNCHAIN_CAPE',name:'Mournchain Shroud',type:'gear',slot:'cape',attack:5,defense:5,hp:38,readiness:15,value:560,rarity:'rare',classRestriction:'DREADGUARD',equipmentSetId:'mournchain_harness',salvage:{itemId:'TORN_OATHCLOTH',quantity:5}},
{id:'MOURNCHAIN_RING',name:'Mournchain Loop',type:'gear',slot:'ring',attack:4,defense:3,hp:24,readiness:15,value:525,rarity:'rare',classRestriction:'DREADGUARD',equipmentSetId:'mournchain_harness',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
{id:'QUICKPRAYER_CHEST',name:'Quickprayer Chest',type:'gear',slot:'chest',attack:3,defense:8,hp:64,readiness:13,value:600,rarity:'rare',classRestriction:'DAWNKEEPER',equipmentSetId:'thread_of_dawn',salvage:{itemId:'WISP_DUST',quantity:6}},
{id:'QUICKPRAYER_GLOVES',name:'Quickprayer Gloves',type:'gear',slot:'gloves',attack:3,defense:4,hp:28,readiness:12,value:450,rarity:'rare',classRestriction:'DAWNKEEPER',equipmentSetId:'thread_of_dawn',salvage:{itemId:'WISP_DUST',quantity:4}},
{id:'QUICKPRAYER_CAPE',name:'Quickprayer Cape',type:'gear',slot:'cape',attack:4,defense:4,hp:38,readiness:13,value:525,rarity:'rare',classRestriction:'DAWNKEEPER',equipmentSetId:'thread_of_dawn',salvage:{itemId:'WISP_DUST',quantity:5}},
{id:'QUICKPRAYER_RING',name:'Quickprayer Ring',type:'gear',slot:'ring',attack:4,defense:2,hp:30,readiness:12,value:490,rarity:'rare',classRestriction:'DAWNKEEPER',equipmentSetId:'thread_of_dawn',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
{id:'TRACKER_CHEST',name:'Tracker Chest',type:'gear',slot:'chest',attack:11,defense:7,hp:52,readiness:17,value:760,rarity:'rare',classRestriction:'WAYFINDER',equipmentSetId:'regretwalker',salvage:{itemId:'ECHO_TOUCHED_PELT',quantity:3}},
{id:'TRACKER_GLOVES',name:'Tracker Gloves',type:'gear',slot:'gloves',attack:6,defense:3,hp:24,readiness:15,value:570,rarity:'rare',classRestriction:'WAYFINDER',equipmentSetId:'regretwalker',salvage:{itemId:'ECHO_TOUCHED_PELT',quantity:2}},
{id:'TRACKER_CAPE',name:'Tracker Cape',type:'gear',slot:'cape',attack:8,defense:3,hp:32,readiness:16,value:690,rarity:'rare',classRestriction:'WAYFINDER',equipmentSetId:'regretwalker',salvage:{itemId:'TORN_OATHCLOTH',quantity:4}},
{id:'TRACKER_RING',name:'Tracker Ring',type:'gear',slot:'ring',attack:7,defense:1,hp:18,readiness:16,value:720,rarity:'rare',classRestriction:'WAYFINDER',equipmentSetId:'regretwalker',salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
{id:'BLOODRUSH_CHEST',name:'Bloodrush Chest',type:'gear',slot:'chest',attack:12,defense:8,hp:52,readiness:17,value:740,rarity:'rare',classRestriction:'RAVAGER',equipmentSetId:'lanternsteel_array',salvage:{itemId:'LANTERNSTEEL_SHARD',quantity:3}},
{id:'BLOODRUSH_GLOVES',name:'Bloodrush Gloves',type:'gear',slot:'gloves',attack:8,defense:4,hp:22,readiness:16,value:560,rarity:'rare',classRestriction:'RAVAGER',equipmentSetId:'lanternsteel_array',salvage:{itemId:'LANTERNSTEEL_SHARD',quantity:2}},
{id:'BLOODRUSH_CAPE',name:'Bloodrush Cape',type:'gear',slot:'cape',attack:9,defense:3,hp:28,readiness:16,value:680,rarity:'rare',classRestriction:'RAVAGER',equipmentSetId:'lanternsteel_array',salvage:{itemId:'BANNER_ASH',quantity:4}},
{id:'BLOODRUSH_RING',name:'Bloodrush Ring',type:'gear',slot:'ring',attack:8,defense:1,hp:16,readiness:16,value:700,rarity:'rare',classRestriction:'RAVAGER',equipmentSetId:'lanternsteel_array',salvage:{itemId:'FALLEN_RIVET',quantity:2}},
{id:'SPELLGLASS_CHEST',name:'Spellglass Chest',type:'gear',slot:'chest',attack:9,defense:4,hp:38,readiness:16,value:730,rarity:'rare',classRestriction:'HEXWEAVER',equipmentSetId:'glassbound_script',salvage:{itemId:'ECHO_QUARTZ',quantity:3}},
{id:'SPELLGLASS_GLOVES',name:'Spellglass Gloves',type:'gear',slot:'gloves',attack:4,defense:2,hp:16,readiness:15,value:545,rarity:'rare',classRestriction:'HEXWEAVER',equipmentSetId:'glassbound_script',salvage:{itemId:'ECHO_QUARTZ',quantity:2}},
{id:'SPELLGLASS_CAPE',name:'Spellglass Cape',type:'gear',slot:'cape',attack:5,defense:2,hp:24,readiness:16,value:670,rarity:'rare',classRestriction:'HEXWEAVER',equipmentSetId:'glassbound_script',salvage:{itemId:'OATHGLASS_FRAGMENT',quantity:2}},
{id:'SPELLGLASS_RING',name:'Spellglass Ring',type:'gear',slot:'ring',attack:3,defense:1,hp:14,readiness:16,value:690,rarity:'rare',classRestriction:'HEXWEAVER',equipmentSetId:'glassbound_script',salvage:{itemId:'OATHGLASS_FRAGMENT',quantity:2}},
{id:'NIGHTFANG_CHEST',name:'Nightfang Chest',type:'gear',slot:'chest',attack:10,defense:4,hp:34,readiness:18,value:745,rarity:'rare',classRestriction:'KNIFE_DANCER',equipmentSetId:'gloamstep_regalia',salvage:{itemId:'GLOAM_DUST',quantity:4}},
{id:'NIGHTFANG_GLOVES',name:'Nightfang Gloves',type:'gear',slot:'gloves',attack:7,defense:2,hp:14,readiness:18,value:565,rarity:'rare',classRestriction:'KNIFE_DANCER',equipmentSetId:'gloamstep_regalia',salvage:{itemId:'GLOAM_DUST',quantity:3}},
{id:'NIGHTFANG_CAPE',name:'Nightfang Cape',type:'gear',slot:'cape',attack:7,defense:2,hp:20,readiness:19,value:685,rarity:'rare',classRestriction:'KNIFE_DANCER',equipmentSetId:'gloamstep_regalia',salvage:{itemId:'LANTERNSTEEL_SHARD',quantity:2}},
{id:'NIGHTFANG_RING',name:'Nightfang Ring',type:'gear',slot:'ring',attack:6,defense:1,hp:12,readiness:19,value:705,rarity:'rare',classRestriction:'KNIFE_DANCER',equipmentSetId:'gloamstep_regalia',salvage:{itemId:'ECHO_QUARTZ',quantity:2}},
{id:'STORMCARVED_CHEST',name:'Stormcarved Chest',type:'gear',slot:'chest',attack:5,defense:7,hp:48,readiness:16,value:735,rarity:'rare',classRestriction:'STONECALLER',equipmentSetId:'resonant_tempest',salvage:{itemId:'RUNEBOUND_CORE',quantity:2}},
{id:'STORMCARVED_GLOVES',name:'Stormcarved Gloves',type:'gear',slot:'gloves',attack:3,defense:4,hp:20,readiness:15,value:555,rarity:'rare',classRestriction:'STONECALLER',equipmentSetId:'resonant_tempest',salvage:{itemId:'ECHO_QUARTZ',quantity:2}},
{id:'STORMCARVED_CAPE',name:'Stormcarved Cape',type:'gear',slot:'cape',attack:4,defense:4,hp:30,readiness:16,value:675,rarity:'rare',classRestriction:'STONECALLER',equipmentSetId:'resonant_tempest',salvage:{itemId:'ECHO_BAT_WING',quantity:3}},
{id:'STORMCARVED_RING',name:'Stormcarved Ring',type:'gear',slot:'ring',attack:3,defense:2,hp:18,readiness:16,value:695,rarity:'rare',classRestriction:'STONECALLER',equipmentSetId:'resonant_tempest',salvage:{itemId:'RUNEBOUND_CORE',quantity:1}},
{id:'SUNSCORED_STONEHEART_CHEST',name:'Sunscored Stoneheart Chest',type:'gear',slot:'chest',defense:19,hp:126,readiness:25,value:1320,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'glassward_covenant',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_STONEHEART_GLOVES',name:'Sunscored Stoneheart Gloves',type:'gear',slot:'gloves',defense:10,hp:52,readiness:23,value:940,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'glassward_covenant',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_STONEHEART_CAPE',name:'Sunscored Stoneheart Cape',type:'gear',slot:'cape',defense:9,hp:70,readiness:24,value:1160,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'glassward_covenant',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_STONEHEART_RING',name:'Sunscored Stoneheart Ring',type:'gear',slot:'ring',defense:7,hp:44,readiness:24,value:1100,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'glassward_covenant',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_LASTWALL_CHEST',name:'Sunscored Lastwall Chestguard',type:'gear',slot:'chest',defense:21,hp:140,readiness:24,value:1340,rarity:'epic',classRestriction:'BASTION',equipmentSetId:'sunvault_panoply',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_LASTWALL_GLOVES',name:'Sunscored Lastwall Gauntlets',type:'gear',slot:'gloves',defense:11,hp:58,readiness:23,value:955,rarity:'epic',classRestriction:'BASTION',equipmentSetId:'sunvault_panoply',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_LASTWALL_CAPE',name:'Sunscored Lastwall Mantle',type:'gear',slot:'cape',defense:10,hp:76,readiness:24,value:1180,rarity:'epic',classRestriction:'BASTION',equipmentSetId:'sunvault_panoply',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_LASTWALL_RING',name:'Sunscored Lastwall Signet',type:'gear',slot:'ring',defense:8,hp:50,readiness:24,value:1120,rarity:'epic',classRestriction:'BASTION',equipmentSetId:'sunvault_panoply',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_MOURNCHAIN_CHEST',name:'Sunscored Mournchain Cuirass',type:'gear',slot:'chest',attack:7,defense:17,hp:118,readiness:27,value:1360,rarity:'epic',classRestriction:'DREADGUARD',equipmentSetId:'cinderchain_harness',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_MOURNCHAIN_GLOVES',name:'Sunscored Mournchain Grips',type:'gear',slot:'gloves',attack:6,defense:8,hp:44,readiness:26,value:970,rarity:'epic',classRestriction:'DREADGUARD',equipmentSetId:'cinderchain_harness',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_MOURNCHAIN_CAPE',name:'Sunscored Mournchain Shroud',type:'gear',slot:'cape',attack:7,defense:7,hp:60,readiness:27,value:1200,rarity:'epic',classRestriction:'DREADGUARD',equipmentSetId:'cinderchain_harness',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_MOURNCHAIN_RING',name:'Sunscored Mournchain Loop',type:'gear',slot:'ring',attack:6,defense:5,hp:38,readiness:27,value:1140,rarity:'epic',classRestriction:'DREADGUARD',equipmentSetId:'cinderchain_harness',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_QUICKPRAYER_CHEST',name:'Sunscored Quickprayer Chest',type:'gear',slot:'chest',attack:6,defense:12,hp:88,readiness:26,value:1300,rarity:'epic',classRestriction:'DAWNKEEPER',equipmentSetId:'dawn_of_saffron',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_QUICKPRAYER_GLOVES',name:'Sunscored Quickprayer Gloves',type:'gear',slot:'gloves',attack:5,defense:6,hp:38,readiness:25,value:925,rarity:'epic',classRestriction:'DAWNKEEPER',equipmentSetId:'dawn_of_saffron',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_QUICKPRAYER_CAPE',name:'Sunscored Quickprayer Cape',type:'gear',slot:'cape',attack:6,defense:6,hp:54,readiness:26,value:1140,rarity:'epic',classRestriction:'DAWNKEEPER',equipmentSetId:'dawn_of_saffron',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_QUICKPRAYER_RING',name:'Sunscored Quickprayer Ring',type:'gear',slot:'ring',attack:6,defense:3,hp:34,readiness:26,value:1085,rarity:'epic',classRestriction:'DAWNKEEPER',equipmentSetId:'dawn_of_saffron',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_TRACKER_CHEST',name:'Sunscored Tracker Chest',type:'gear',slot:'chest',attack:17,defense:10,hp:72,readiness:27,value:1340,rarity:'epic',classRestriction:'WAYFINDER',equipmentSetId:'mirage_hunter',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_TRACKER_GLOVES',name:'Sunscored Tracker Gloves',type:'gear',slot:'gloves',attack:10,defense:5,hp:32,readiness:26,value:955,rarity:'epic',classRestriction:'WAYFINDER',equipmentSetId:'mirage_hunter',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_TRACKER_CAPE',name:'Sunscored Tracker Cape',type:'gear',slot:'cape',attack:12,defense:5,hp:44,readiness:27,value:1180,rarity:'epic',classRestriction:'WAYFINDER',equipmentSetId:'mirage_hunter',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_TRACKER_RING',name:'Sunscored Tracker Ring',type:'gear',slot:'ring',attack:10,defense:2,hp:24,readiness:27,value:1120,rarity:'epic',classRestriction:'WAYFINDER',equipmentSetId:'mirage_hunter',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_BLOODRUSH_CHEST',name:'Sunscored Bloodrush Chest',type:'gear',slot:'chest',attack:18,defense:11,hp:70,readiness:28,value:1360,rarity:'epic',classRestriction:'RAVAGER',equipmentSetId:'scorchblood_array',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_BLOODRUSH_GLOVES',name:'Sunscored Bloodrush Gloves',type:'gear',slot:'gloves',attack:12,defense:6,hp:30,readiness:27,value:970,rarity:'epic',classRestriction:'RAVAGER',equipmentSetId:'scorchblood_array',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_BLOODRUSH_CAPE',name:'Sunscored Bloodrush Cape',type:'gear',slot:'cape',attack:14,defense:5,hp:40,readiness:28,value:1200,rarity:'epic',classRestriction:'RAVAGER',equipmentSetId:'scorchblood_array',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_BLOODRUSH_RING',name:'Sunscored Bloodrush Ring',type:'gear',slot:'ring',attack:12,defense:2,hp:22,readiness:28,value:1140,rarity:'epic',classRestriction:'RAVAGER',equipmentSetId:'scorchblood_array',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_SPELLGLASS_CHEST',name:'Sunscored Spellglass Chest',type:'gear',slot:'chest',attack:17,defense:7,hp:56,readiness:27,value:1350,rarity:'epic',classRestriction:'HEXWEAVER',equipmentSetId:'astral_script',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_SPELLGLASS_GLOVES',name:'Sunscored Spellglass Gloves',type:'gear',slot:'gloves',attack:9,defense:4,hp:24,readiness:26,value:965,rarity:'epic',classRestriction:'HEXWEAVER',equipmentSetId:'astral_script',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_SPELLGLASS_CAPE',name:'Sunscored Spellglass Cape',type:'gear',slot:'cape',attack:11,defense:4,hp:34,readiness:27,value:1190,rarity:'epic',classRestriction:'HEXWEAVER',equipmentSetId:'astral_script',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_SPELLGLASS_RING',name:'Sunscored Spellglass Ring',type:'gear',slot:'ring',attack:9,defense:2,hp:18,readiness:27,value:1130,rarity:'epic',classRestriction:'HEXWEAVER',equipmentSetId:'astral_script',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_NIGHTFANG_CHEST',name:'Sunscored Nightfang Chest',type:'gear',slot:'chest',attack:18,defense:7,hp:52,readiness:29,value:1370,rarity:'epic',classRestriction:'KNIFE_DANCER',equipmentSetId:'dunestep_regalia',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_NIGHTFANG_GLOVES',name:'Sunscored Nightfang Gloves',type:'gear',slot:'gloves',attack:12,defense:4,hp:22,readiness:29,value:980,rarity:'epic',classRestriction:'KNIFE_DANCER',equipmentSetId:'dunestep_regalia',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_NIGHTFANG_CAPE',name:'Sunscored Nightfang Cape',type:'gear',slot:'cape',attack:13,defense:4,hp:30,readiness:30,value:1210,rarity:'epic',classRestriction:'KNIFE_DANCER',equipmentSetId:'dunestep_regalia',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_NIGHTFANG_RING',name:'Sunscored Nightfang Ring',type:'gear',slot:'ring',attack:11,defense:2,hp:16,readiness:30,value:1150,rarity:'epic',classRestriction:'KNIFE_DANCER',equipmentSetId:'dunestep_regalia',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_STORMCARVED_CHEST',name:'Sunscored Stormcarved Chest',type:'gear',slot:'chest',attack:10,defense:12,hp:78,readiness:27,value:1360,rarity:'epic',classRestriction:'STONECALLER',equipmentSetId:'oasis_resonance',salvage:{itemId:'AMBERGLASS',quantity:4}},
{id:'SUNSCORED_STORMCARVED_GLOVES',name:'Sunscored Stormcarved Gloves',type:'gear',slot:'gloves',attack:6,defense:7,hp:34,readiness:26,value:970,rarity:'epic',classRestriction:'STONECALLER',equipmentSetId:'oasis_resonance',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'SUNSCORED_STORMCARVED_CAPE',name:'Sunscored Stormcarved Cape',type:'gear',slot:'cape',attack:8,defense:7,hp:48,readiness:27,value:1200,rarity:'epic',classRestriction:'STONECALLER',equipmentSetId:'oasis_resonance',salvage:{itemId:'ASTRAL_SCRIPT',quantity:1}},
{id:'SUNSCORED_STORMCARVED_RING',name:'Sunscored Stormcarved Ring',type:'gear',slot:'ring',attack:6,defense:4,hp:28,readiness:27,value:1140,rarity:'epic',classRestriction:'STONECALLER',equipmentSetId:'oasis_resonance',salvage:{itemId:'AMBERGLASS',quantity:2}},
{id:'RIMEBOUND_STONEHEART_CHEST',name:'Rimebound Stoneheart Chest',type:'gear',slot:'chest',attack:6,defense:18,hp:115,readiness:34,value:2420,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'rimewall_oath',salvage:{itemId:'RIMEGLASS',quantity:4}},
{id:'RIMEBOUND_STONEHEART_GLOVES',name:'Rimebound Stoneheart Gloves',type:'gear',slot:'gloves',attack:4,defense:10,hp:50,readiness:33,value:1740,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'rimewall_oath',salvage:{itemId:'RIMEGLASS',quantity:2}},
{id:'RIMEBOUND_STONEHEART_CAPE',name:'Rimebound Stoneheart Cape',type:'gear',slot:'cape',attack:5,defense:11,hp:70,readiness:34,value:2160,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'rimewall_oath',salvage:{itemId:'CHOIR_BLOOM',quantity:1}},
{id:'RIMEBOUND_STONEHEART_RING',name:'Rimebound Stoneheart Ring',type:'gear',slot:'ring',attack:4,defense:8,hp:42,readiness:34,value:2050,rarity:'epic',classRestriction:'IRONWARDEN',equipmentSetId:'rimewall_oath',salvage:{itemId:'RIMEGLASS',quantity:2}},

{id:'ASTER_IRON_ORE',name:'Aster-Iron Ore',type:'material',value:14},
{id:'SUNSTONE_ORE',name:'Sunstone Ore',type:'material',value:65},
{id:'AMBERGLASS',name:'Amberglass',type:'material',value:180,rarity:'uncommon'},
{id:'ASTRAL_SCRIPT',name:'Astral Script',type:'material',value:420,rarity:'rare'},
{id:'FROSTIRON',name:'Frostiron',type:'material',value:150},
{id:'RIMEGLASS',name:'Rimeglass',type:'material',value:430,rarity:'rare'},
{id:'CHOIR_BLOOM',name:'Choir Bloom',type:'material',value:480,rarity:'rare'},
// V33 regional resource identities. Source/drop wiring is authoritative on the backend.
{id:'SAFFRON_REED',name:'Saffron Reed',type:'material',value:95,rarity:'uncommon'},
{id:'MIRAGE_BLOOM',name:'Mirage Bloom',type:'material',value:160,rarity:'uncommon'},
{id:'DUNEWOOD',name:'Dunewood',type:'material',value:85,rarity:'uncommon'},
{id:'CHARBARK',name:'Charbark',type:'material',value:140,rarity:'uncommon'},
{id:'OASIS_CARP',name:'Oasis Carp',type:'material',value:100,rarity:'uncommon'},
{id:'GLASSFIN',name:'Glassfin',type:'material',value:170,rarity:'rare'},
{id:'SCORPION_VENOM',name:'Scorpion Venom',type:'material',value:130,rarity:'uncommon'},
{id:'ROYAL_CHITIN',name:'Royal Chitin',type:'material',value:300,rarity:'rare'},
{id:'TYRANT_SEAL',name:'Tyrant Seal',type:'material',value:620,rarity:'rare'},
{id:'WHITEPINE_LOG',name:'Whitepine Log',type:'material',value:120,rarity:'uncommon'},
{id:'RIME_RESIN',name:'Rime Resin',type:'material',value:190,rarity:'uncommon'},
{id:'WINTERMINT',name:'Wintermint',type:'material',value:170,rarity:'uncommon'},
{id:'ICEFIN',name:'Icefin',type:'material',value:180,rarity:'rare'},
{id:'BELLFIN_SCALE',name:'Bellfin Scale',type:'material',value:260,rarity:'rare'},
{id:'WYRMSCALE',name:'Wyrm Scale',type:'material',value:520,rarity:'rare'},
{id:'FROZEN_HEART',name:'Frozen Heart',type:'material',value:900,rarity:'legendary'},
{id:'GREENWOOD_LOG',name:'Greenwood Log',type:'material',value:4},
{id:'IRONWOOD_LOG',name:'Ironwood Log',type:'material',value:13},
{id:'SILVERFIN',name:'Silverfin',type:'material',value:6},
{id:'RIVER_EEL',name:'River Eel',type:'material',value:15},

{id:'COPPER_BLADE',name:'Copper Blade',type:'gear',slot:'weapon',attack:7,readiness:4,value:75},
{id:'ASTER_IRON_BLADE',name:'Aster-Iron Blade',type:'gear',slot:'weapon',attack:13,readiness:8,value:220,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:4}},
{id:'ASTER_IRON_HELM',name:'Aster-Iron Helm',type:'gear',slot:'helmet',defense:7,hp:38,readiness:6,value:195,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:3}},
{id:'ASTER_IRON_CHEST',name:'Aster-Iron Cuirass',type:'gear',slot:'chest',defense:11,hp:72,readiness:9,value:310,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:5}},
{id:'ASTER_IRON_LEGS',name:'Aster-Iron Legguards',type:'gear',slot:'legs',defense:8,hp:48,readiness:7,value:245,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:4}},
{id:'ASTER_IRON_BOOTS',name:'Aster-Iron Greaves',type:'gear',slot:'boots',defense:5,hp:30,readiness:6,value:205,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:3}},
{id:'ASTER_IRON_GLOVES',name:'Aster-Iron Gauntlets',type:'gear',slot:'gloves',defense:5,hp:24,readiness:6,value:195,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:3}},
{id:'ASTER_IRON_OFFHAND',name:'Aster-Iron Guard',type:'gear',slot:'offhand',defense:8,hp:38,readiness:7,value:225,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:3}},
{id:'ASTER_IRON_CAPE',name:'Aster-Iron Mantle',type:'gear',slot:'cape',attack:2,defense:5,hp:30,readiness:7,value:215,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:2}},
{id:'ASTER_IRON_AMULET',name:'Aster-Iron Star Amulet',type:'gear',slot:'amulet',attack:3,defense:3,hp:24,readiness:7,value:210,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:2}},
{id:'ASTER_IRON_RING',name:'Aster-Iron Signet',type:'gear',slot:'ring',attack:3,defense:2,hp:18,readiness:7,value:205,rarity:'rare',salvage:{itemId:'ASTER_IRON_INGOT',quantity:2}},
{id:'IRONWOOD_GUARD',name:'Ironwood Guard',type:'gear',slot:'offhand',defense:7,hp:34,readiness:6,value:185},
{id:'IRONWOOD_LONGBOW',name:'Ironwood Longbow',type:'gear',slot:'weapon',attack:12,readiness:8,value:220},
{id:'IRONWOOD_STAFF',name:'Ironwood Runestaff',type:'gear',slot:'weapon',attack:10,hp:28,readiness:8,value:220},
{id:'IRONWOOD_DAGGERS',name:'Ironwood Twin Daggers',type:'gear',slot:'weapon',attack:12,readiness:8,value:220},
{id:'IRONWOOD_GREATAXE',name:'Ironwood Great-Axe',type:'gear',slot:'weapon',attack:14,defense:-1,readiness:8,value:220},

{id:'MOSS_FIBER',name:'Moss Fiber',type:'material',value:3},
{id:'WISP_DUST',name:'Wisp Dust',type:'material',value:7},
{id:'BOAR_HIDE',name:'Boar Hide',type:'material',value:8},
{id:'WOLF_PELT',name:'Wolf Pelt',type:'material',value:13},
{id:'IRONWOOD_FANG',name:'Ironwood Fang',type:'material',value:28},
{id:'THORN_SAP',name:'Thorn Sap',type:'material',value:20},
{id:'TROLL_HIDE',name:'Troll Hide',type:'material',value:42},
{id:'OATHGLASS_SHARD',name:'Oathglass Shard',type:'material',value:85},
{id:'ECHO_TOUCHED_PELT',name:'Echo-Touched Pelt',type:'material',value:140},
{id:'TORN_OATHCLOTH',name:'Torn Oathcloth',type:'material',value:95},
{id:'LANTERNSTEEL_SHARD',name:'Lanternsteel Shard',type:'material',value:125},
{id:'BANNER_ASH',name:'Banner Ash',type:'material',value:75},
{id:'BLACKGLASS_CORE',name:'Blackglass Core',type:'material',value:260,rarity:'rare'},
{id:'CINDER_HEART',name:'Cinder Heart',type:'material',value:420,rarity:'rare'},
{id:'REGENT_SIGIL',name:'Regent Sigil',type:'material',value:850,rarity:'legendary'},
{id:'FALLEN_RIVET',name:'Fallen Rivet',type:'material',value:90},
{id:'ECHO_QUARTZ',name:'Echo Quartz',type:'material',value:85},
{id:'OATHGLASS_FRAGMENT',name:'Oathglass Fragment',type:'material',value:130},
{id:'GLOAM_DUST',name:'Gloam Dust',type:'material',value:105},
{id:'EVENT_BONDBLOOM',name:'Event Bondbloom',type:'material',value:175},
{id:'RUNEBOUND_CORE',name:'Runebound Core',type:'material',value:150},
{id:'ECHO_BAT_WING',name:'Echo Bat Wing',type:'material',value:80},
{id:'FALLEN_KNIGHT_SIGIL',name:'Fallen Knight Sigil',type:'quest',value:0},

{id:'WORN_BLADE',name:'Worn Blade',type:'gear',slot:'weapon',attack:4,readiness:2,value:35,salvage:{itemId:'MOSS_FIBER',quantity:2}},
{id:'MOSSWRAP_GLOVES',name:'Mosswrap Gloves',type:'gear',slot:'gloves',defense:2,hp:8,readiness:3,value:55,salvage:{itemId:'MOSS_FIBER',quantity:3}},
{id:'WISP_CHARM',name:'Wisp Charm',type:'gear',slot:'amulet',attack:2,hp:12,readiness:3,value:80,salvage:{itemId:'WISP_DUST',quantity:2}},
{id:'BOARHIDE_BOOTS',name:'Boarhide Boots',type:'gear',slot:'boots',defense:3,hp:15,readiness:4,value:95,salvage:{itemId:'BOAR_HIDE',quantity:3}},
{id:'IRONWOOD_BLADE',name:'Ironwood Blade',type:'gear',slot:'weapon',attack:9,readiness:5,value:120,salvage:{itemId:'IRONWOOD_FANG',quantity:1}},
{id:'HIDE_VEST',name:'Hide Vest',type:'gear',slot:'chest',defense:5,hp:28,readiness:4,value:90,salvage:{itemId:'BOAR_HIDE',quantity:4}},
{id:'THORN_RING',name:'Thorn Ring',type:'gear',slot:'ring',attack:4,defense:1,readiness:5,value:155,salvage:{itemId:'THORN_SAP',quantity:3}},
{id:'TROLLGUARD_HELM',name:'Trollguard Helm',type:'gear',slot:'helmet',defense:8,hp:55,readiness:7,value:260,salvage:{itemId:'TROLL_HIDE',quantity:2}},
{id:'OATHGLASS_CAPE',name:'Oathglass Cape',type:'gear',slot:'cape',attack:5,defense:5,hp:35,readiness:8,value:420,salvage:{itemId:'OATHGLASS_SHARD',quantity:2}},
];
export const ITEMS:ItemDef[]=[...BASE_ITEMS,...EQUIPMENT_ITEMS_V33];
export function itemDef(id:string){const x=ITEMS.find(i=>i.id===id); if(!x) throw new Error(`Unknown item ${id}`); return x;}
