export interface MonsterDef {id:string;name:string;level:number;hp:number;attack:number;defense:number;xp:number;gold:number;secondsPerKill:number;unlockLevel:number;zone:string;boss?:boolean;drops:{itemId:string;chance:number;min:number;max:number}[];}

const MONSTERS_RAW:MonsterDef[]=[
{id:'MOSS_RAT',name:'Moss Rat',level:1,hp:28,attack:5,defense:2,xp:14,gold:1,secondsPerKill:7,unlockLevel:1,zone:'Greenfields',drops:[{itemId:'MOSS_FIBER',chance:.55,min:1,max:2},{itemId:'MOSSWRAP_GLOVES',chance:.025,min:1,max:1}]},
{id:'FIELD_WISP',name:'Field Wisp',level:2,hp:36,attack:6,defense:2,xp:18,gold:1,secondsPerKill:8,unlockLevel:2,zone:'Greenfields',drops:[{itemId:'WISP_DUST',chance:.36,min:1,max:1},{itemId:'WISP_CHARM',chance:.020,min:1,max:1}]},
{id:'ROADSIDE_BOAR',name:'Roadside Boar',level:4,hp:58,attack:8,defense:4,xp:29,gold:2,secondsPerKill:10,unlockLevel:4,zone:'Greenfields',drops:[{itemId:'BOAR_HIDE',chance:.50,min:1,max:2},{itemId:'BOARHIDE_BOOTS',chance:.018,min:1,max:1},{itemId:'HIDE_VEST',chance:.012,min:1,max:1}]},
{id:'SILVERFIN_SWARM',name:'Silverfin Swarm',level:5,hp:66,attack:9,defense:4,xp:34,gold:2,secondsPerKill:10,unlockLevel:5,zone:'Silverbrook',drops:[{itemId:'SILVERFIN',chance:.60,min:1,max:2},{itemId:'WISP_DUST',chance:.12,min:1,max:1}]},
{id:'IRONWOOD_WOLF',name:'Ironwood Wolf',level:7,hp:96,attack:12,defense:7,xp:48,gold:3,secondsPerKill:12,unlockLevel:7,zone:'Ironwood Forest',drops:[{itemId:'WOLF_PELT',chance:.48,min:1,max:1},{itemId:'IRONWOOD_FANG',chance:.14,min:1,max:1},{itemId:'IRONWOOD_BLADE',chance:.011,min:1,max:1}]},
{id:'VENOM_WEAVER',name:'Venom Weaver',level:8,hp:108,attack:14,defense:6,xp:55,gold:4,secondsPerKill:13,unlockLevel:8,zone:'Ironwood Forest',drops:[{itemId:'THORN_SAP',chance:.30,min:1,max:1},{itemId:'MOSS_FIBER',chance:.28,min:1,max:2}]},
{id:'THORNLING',name:'Thornling',level:10,hp:138,attack:16,defense:9,xp:72,gold:4,secondsPerKill:15,unlockLevel:10,zone:'Ironwood Forest',drops:[{itemId:'THORN_SAP',chance:.42,min:1,max:2},{itemId:'THORN_RING',chance:.012,min:1,max:1}]},
{id:'BRIAR_HUSK',name:'Briar Husk',level:11,hp:154,attack:18,defense:10,xp:82,gold:5,secondsPerKill:16,unlockLevel:11,zone:'Ironwood Forest',drops:[{itemId:'THORN_SAP',chance:.38,min:1,max:2},{itemId:'GREENWOOD_LOG',chance:.24,min:1,max:2}]},
{id:'MIRE_HERON',name:'Mire Heron',level:12,hp:166,attack:19,defense:9,xp:91,gold:5,secondsPerKill:16,unlockLevel:12,zone:'Silverbrook',drops:[{itemId:'RIVER_EEL',chance:.35,min:1,max:1},{itemId:'WISP_DUST',chance:.22,min:1,max:1}]},
{id:'FOREST_TROLL',name:'Forest Troll',level:14,hp:215,attack:23,defense:13,xp:118,gold:7,secondsPerKill:19,unlockLevel:14,zone:'Ironwood Forest',drops:[{itemId:'TROLL_HIDE',chance:.32,min:1,max:1},{itemId:'TROLLGUARD_HELM',chance:.010,min:1,max:1}]},
{id:'ANCIENT_TREANT',name:'Ancient Treant',level:15,hp:242,attack:24,defense:15,xp:132,gold:8,secondsPerKill:20,unlockLevel:15,zone:'Ironwood Forest',drops:[{itemId:'IRONWOOD_LOG',chance:.52,min:1,max:2},{itemId:'THORN_SAP',chance:.30,min:1,max:1}]},
{id:'CAVE_SKITTER',name:'Cave Skitter',level:16,hp:255,attack:26,defense:14,xp:145,gold:8,secondsPerKill:20,unlockLevel:16,zone:'Old Mines',drops:[{itemId:'COPPER_ORE',chance:.44,min:1,max:2},{itemId:'ASTER_IRON_ORE',chance:.16,min:1,max:1}]},
{id:'IRONBACK_MOLE',name:'Ironback Mole',level:17,hp:280,attack:27,defense:18,xp:158,gold:9,secondsPerKill:21,unlockLevel:17,zone:'Old Mines',drops:[{itemId:'ASTER_IRON_ORE',chance:.40,min:1,max:2},{itemId:'COPPER_ORE',chance:.30,min:1,max:2}]},
{id:'ECHO_BAT',name:'Echo Bat',level:18,hp:290,attack:29,defense:14,xp:170,gold:10,secondsPerKill:21,unlockLevel:18,zone:'Old Mines',drops:[{itemId:'WISP_DUST',chance:.35,min:1,max:2},{itemId:'OATHGLASS_SHARD',chance:.05,min:1,max:1},{itemId:'ECHO_BAT_WING',chance:.28,min:1,max:2}]},
{id:'RUNEBOUND_MINER',name:'Runebound Miner',level:19,hp:320,attack:31,defense:18,xp:185,gold:11,secondsPerKill:22,unlockLevel:19,zone:'Old Mines',drops:[{itemId:'ASTER_IRON_ORE',chance:.42,min:1,max:2},{itemId:'OATHGLASS_SHARD',chance:.08,min:1,max:1},{itemId:'ECHO_QUARTZ',chance:.12,min:1,max:1},{itemId:'RUNEBOUND_CORE',chance:.08,min:1,max:1}]},
{id:'GLOAM_MITE',name:'Gloam Mite',level:20,hp:335,attack:33,defense:18,xp:198,gold:12,secondsPerKill:23,unlockLevel:20,zone:'Greenfields',drops:[{itemId:'WISP_DUST',chance:.32,min:1,max:2},{itemId:'MOSS_FIBER',chance:.28,min:1,max:2},{itemId:'GLOAM_DUST',chance:.24,min:1,max:1}]},
{id:'LANTERN_WRETCH',name:'Lantern Wretch',level:21,hp:365,attack:35,defense:19,xp:216,gold:13,secondsPerKill:24,unlockLevel:21,zone:"King's Road",drops:[{itemId:'WISP_DUST',chance:.40,min:1,max:2},{itemId:'OATHGLASS_SHARD',chance:.10,min:1,max:1},{itemId:'LANTERNSTEEL_SHARD',chance:.18,min:1,max:1},{itemId:'BLOODRUSH_CHEST',chance:.00875,min:1,max:1},{itemId:'BLOODRUSH_GLOVES',chance:.00875,min:1,max:1},{itemId:'BLOODRUSH_CAPE',chance:.00875,min:1,max:1},{itemId:'BLOODRUSH_RING',chance:.00875,min:1,max:1}]},
{id:'DROWNED_PILGRIM',name:'Drowned Pilgrim',level:22,hp:390,attack:36,defense:21,xp:232,gold:14,secondsPerKill:25,unlockLevel:22,zone:'Silverbrook',drops:[{itemId:'RIVER_EEL',chance:.28,min:1,max:1},{itemId:'OATHGLASS_SHARD',chance:.12,min:1,max:1}]},
{id:'OATHBOUND_SQUIRE',name:'Oathbound Squire',level:22,hp:405,attack:37,defense:22,xp:240,gold:14,secondsPerKill:25,unlockLevel:22,zone:"King's Road",drops:[{itemId:'OATHGLASS_SHARD',chance:.18,min:1,max:1},{itemId:'TORN_OATHCLOTH',chance:.20,min:1,max:1},{itemId:'FALLEN_RIVET',chance:.20,min:1,max:1},{itemId:'HIDE_VEST',chance:.008,min:1,max:1}]},
{id:'BANNER_SHADE',name:'Banner Shade',level:23,hp:435,attack:39,defense:22,xp:258,gold:15,secondsPerKill:26,unlockLevel:23,zone:"King's Road",drops:[{itemId:'OATHGLASS_SHARD',chance:.22,min:1,max:1},{itemId:'TORN_OATHCLOTH',chance:.28,min:1,max:1},{itemId:'BANNER_ASH',chance:.28,min:1,max:2},{itemId:'LANTERNSTEEL_SHARD',chance:.10,min:1,max:1},{itemId:'GLOAM_DUST',chance:.18,min:1,max:1},{itemId:'THORN_RING',chance:.006,min:1,max:1},{itemId:'NIGHTFANG_CHEST',chance:.00875,min:1,max:1},{itemId:'NIGHTFANG_GLOVES',chance:.00875,min:1,max:1},{itemId:'NIGHTFANG_CAPE',chance:.00875,min:1,max:1},{itemId:'NIGHTFANG_RING',chance:.00875,min:1,max:1}]},
{id:'FALLEN_SENTINEL',name:'Fallen Sentinel',level:24,hp:475,attack:42,defense:25,xp:282,gold:17,secondsPerKill:28,unlockLevel:24,zone:"King's Road",drops:[{itemId:'OATHGLASS_SHARD',chance:.28,min:1,max:1},{itemId:'ECHO_TOUCHED_PELT',chance:.12,min:1,max:1},{itemId:'TORN_OATHCLOTH',chance:.32,min:1,max:2},{itemId:'LANTERNSTEEL_SHARD',chance:.18,min:1,max:1},{itemId:'FALLEN_RIVET',chance:.28,min:1,max:2},{itemId:'RUNEBOUND_CORE',chance:.12,min:1,max:1},{itemId:'OATHGLASS_CAPE',chance:.008,min:1,max:1},{itemId:'STORMCARVED_CHEST',chance:.00875,min:1,max:1},{itemId:'STORMCARVED_GLOVES',chance:.00875,min:1,max:1},{itemId:'STORMCARVED_CAPE',chance:.00875,min:1,max:1},{itemId:'STORMCARVED_RING',chance:.00875,min:1,max:1}]},
{id:'OATHGLASS_REVENANT',name:'Oathglass Revenant',level:25,hp:540,attack:45,defense:28,xp:315,gold:18,secondsPerKill:30,unlockLevel:25,zone:"King's Road",drops:[{itemId:'OATHGLASS_SHARD',chance:.34,min:1,max:2},{itemId:'OATHGLASS_FRAGMENT',chance:.20,min:1,max:1},{itemId:'ECHO_QUARTZ',chance:.15,min:1,max:1},{itemId:'ECHO_TOUCHED_PELT',chance:.18,min:1,max:1},{itemId:'TORN_OATHCLOTH',chance:.35,min:1,max:2},{itemId:'OATHGLASS_CAPE',chance:.006,min:1,max:1},{itemId:'SPELLGLASS_CHEST',chance:.00875,min:1,max:1},{itemId:'SPELLGLASS_GLOVES',chance:.00875,min:1,max:1},{itemId:'SPELLGLASS_CAPE',chance:.00875,min:1,max:1},{itemId:'SPELLGLASS_RING',chance:.00875,min:1,max:1}]},
{id:'SUNSCAR_SCORPION',name:'Sunscar Scorpion',level:28,hp:610,attack:52,defense:31,xp:350,gold:21,secondsPerKill:31,unlockLevel:26,zone:'Sunscar',drops:[{itemId:'SUNSTONE_ORE',chance:.42,min:1,max:2},{itemId:'AMBERGLASS',chance:.08,min:1,max:1}]},
{id:'DUNE_ORACLE',name:'Dune Oracle',level:33,hp:760,attack:61,defense:36,xp:438,gold:27,secondsPerKill:35,unlockLevel:31,zone:'Sunscar',drops:[{itemId:'AMBERGLASS',chance:.36,min:1,max:2},{itemId:'ASTRAL_SCRIPT',chance:.08,min:1,max:1},{itemId:'SWIFT_SIGIL',chance:.003,min:1,max:1}]},
{id:'GLASSBOUND_SENTINEL',name:'Glassbound Sentinel',level:40,hp:980,attack:74,defense:45,xp:560,gold:35,secondsPerKill:40,unlockLevel:38,zone:'Sunscar',drops:[{itemId:'SUNSTONE_ORE',chance:.50,min:1,max:2},{itemId:'AMBERGLASS',chance:.28,min:1,max:1},{itemId:'ASTRAL_SCRIPT',chance:.12,min:1,max:1}]},
{id:'FROSTWOLF',name:'Frostwolf',level:48,hp:1220,attack:88,defense:55,xp:710,gold:43,secondsPerKill:44,unlockLevel:46,zone:'Frostmarch',drops:[{itemId:'FROSTIRON',chance:.42,min:1,max:2},{itemId:'RIMEGLASS',chance:.08,min:1,max:1}]},
{id:'BELLWRAITH',name:'Bellwraith',level:56,hp:1580,attack:106,defense:68,xp:920,gold:55,secondsPerKill:50,unlockLevel:53,zone:'Frostmarch',drops:[{itemId:'RIMEGLASS',chance:.36,min:1,max:2},{itemId:'CHOIR_BLOOM',chance:.10,min:1,max:1}]},
{id:'CHOIR_HUNTER',name:'Choir Hunter',level:66,hp:2050,attack:132,defense:82,xp:1180,gold:70,secondsPerKill:58,unlockLevel:63,zone:'Frostmarch',drops:[{itemId:'FROSTIRON',chance:.50,min:1,max:2},{itemId:'RIMEGLASS',chance:.28,min:1,max:1},{itemId:'CHOIR_BLOOM',chance:.12,min:1,max:1},{itemId:'BULWARK_SIGIL',chance:.003,min:1,max:1}]},
{id:'BLACKGLASS_MIRELING',name:'Blackglass Mireling',level:72,hp:2480,attack:154,defense:96,xp:1450,gold:86,secondsPerKill:63,unlockLevel:71,zone:'Ashlands',drops:[{itemId:'BANNER_ASH',chance:.42,min:1,max:2},{itemId:'BLACKGLASS_CORE',chance:.08,min:1,max:1},{itemId:'RIMEGLASS',chance:.12,min:1,max:1}]},
{id:'CINDER_TITAN',name:'Cinder Titan',level:80,hp:3200,attack:185,defense:118,xp:1840,gold:108,secondsPerKill:72,unlockLevel:78,zone:'Ashlands',drops:[{itemId:'SUNSTONE_ORE',chance:.34,min:1,max:2},{itemId:'CINDER_HEART',chance:.08,min:1,max:1},{itemId:'ASTRAL_SCRIPT',chance:.20,min:1,max:1},{itemId:'CHOIR_BLOOM',chance:.16,min:1,max:1},{itemId:'BOSSBANE_SIGIL',chance:.0025,min:1,max:1}]},
{id:'ASHEN_REVENANT',name:'Ashen Revenant',level:88,hp:4100,attack:224,defense:142,xp:2320,gold:136,secondsPerKill:82,unlockLevel:86,zone:'Ashlands',drops:[{itemId:'BANNER_ASH',chance:.55,min:1,max:2},{itemId:'CINDER_HEART',chance:.10,min:1,max:1},{itemId:'REGENT_SIGIL',chance:.04,min:1,max:1},{itemId:'ASTRAL_SCRIPT',chance:.28,min:1,max:1},{itemId:'RIMEGLASS',chance:.22,min:1,max:1},{itemId:'RENEWAL_SIGIL',chance:.0025,min:1,max:1}]},
{id:'FALLEN_KNIGHT',name:'Fallen Knight',level:25,hp:180000,attack:68,defense:36,xp:3000,gold:180,secondsPerKill:75,unlockLevel:25,zone:"King's Road",boss:true,drops:[{itemId:'FALLEN_KNIGHT_SIGIL',chance:1,min:1,max:1},{itemId:'ECHO_TOUCHED_PELT',chance:1,min:2,max:4},{itemId:'TORN_OATHCLOTH',chance:1,min:4,max:6},{itemId:'TRACKER_CHEST',chance:.01,min:1,max:1},{itemId:'TRACKER_GLOVES',chance:.01,min:1,max:1},{itemId:'TRACKER_CAPE',chance:.01,min:1,max:1},{itemId:'TRACKER_RING',chance:.01,min:1,max:1}]},
];
const MONSTER_TIME_SCALE=1.95;
const MONSTER_STAT_SCALE=1.07;

const enhancementDrops=(monster:MonsterDef):MonsterDef['drops']=>{
  if(monster.boss)return [{itemId:'TEMPERING_DUST',chance:1,min:8,max:14},{itemId:'TEMPERING_CORE',chance:1,min:1,max:2},{itemId:'EMBERHEART_GEM',chance:.001,min:1,max:1},{itemId:'WARDHEART_GEM',chance:.001,min:1,max:1},{itemId:'VITALITY_HEART_GEM',chance:.001,min:1,max:1}];
  if(monster.level>=20)return [{itemId:'TEMPERING_DUST',chance:.18,min:1,max:2},{itemId:'TEMPERING_CORE',chance:.025,min:1,max:1},{itemId:monster.attack>=monster.defense*1.7?'EMBER_SHARD':monster.defense>=monster.attack*.65?'WARD_SHARD':'VITALITY_SHARD',chance:.004,min:1,max:1}];
  if(monster.level>=10)return [{itemId:'TEMPERING_DUST',chance:.10,min:1,max:1},{itemId:'TEMPERING_CORE',chance:.01,min:1,max:1}];
  return monster.level>=4?[{itemId:'TEMPERING_DUST',chance:.05,min:1,max:1}]:[];
};
export const MONSTERS:MonsterDef[]=MONSTERS_RAW.map(monster=>({...monster,
  drops:[...monster.drops,...(monster.id==='FIELD_WISP'?[{itemId:'HOLY_WATER',chance:.12,min:1,max:1}]:monster.id==='DROWNED_PILGRIM'?[{itemId:'HOLY_WATER',chance:.30,min:1,max:1}]:monster.id==='OATHBOUND_SQUIRE'?[{itemId:'HOLY_WATER',chance:.24,min:1,max:1}]:[]),...enhancementDrops(monster)],
  secondsPerKill:Math.ceil(monster.secondsPerKill*MONSTER_TIME_SCALE),
  hp:Math.ceil(monster.hp*MONSTER_STAT_SCALE),
  attack:Math.ceil(monster.attack*MONSTER_STAT_SCALE),
  defense:Math.ceil(monster.defense*MONSTER_STAT_SCALE),
}));
