import {SkillId} from '../core/types';

export type QuestKind='kills'|'item'|'equip'|'level'|'skillLevel'|'craft'|'boss';
export type QuestAct=1|2|3;
export interface QuestActDef{act:QuestAct;name:string;subtitle:string;}
export const QUEST_ACTS:Record<QuestAct,QuestActDef>={
  1:{act:1,name:'Whispers in the Green',subtitle:'Earn a name beyond the safety of the first road.'},
  2:{act:2,name:'Roots, River & Ruin',subtitle:'Follow the spreading echoes through forest, river and mine.'},
  3:{act:3,name:'The Broken Oath',subtitle:'Walk the King’s Road and confront what Asterfall buried.'},
};
export interface QuestDef{
  id:string;name:string;description:string;kind:QuestKind;targetId?:string;skillId?:SkillId;required:number;
  rewardGold:number;rewardItemId?:string;rewardItemQty?:number;
  act:QuestAct;location:string;story:string;
}
export const QUESTS:QuestDef[]=[
{id:'QST_001',name:'A Name in the Ledger',description:'Defeat 5 Moss Rats.',kind:'kills',targetId:'MOSS_RAT',required:5,rewardGold:40,rewardItemId:'MOSS_FIBER',rewardItemQty:5,act:1,location:'Greenfields',story:'The local ledger has more missing names than living ones. A simple rat cull is hardly heroic, but it is the first chance to prove you can return from the road.'},
{id:'QST_002',name:'First Blood, First Skill',description:'Reach level 2 in any guided gathering skill.',kind:'skillLevel',required:2,rewardGold:60,rewardItemId:'COPPER_ORE',rewardItemQty:4,act:1,location:'Greenfields Camp',story:'Steel alone will not carry you through Asterfall. The camp quartermaster sends you to learn the land, gather what it gives, and stop depending on supplies brought from safer places.'},
{id:'QST_003',name:"A Hound's Trail",description:'Defeat 6 Ironwood Wolves.',kind:'kills',targetId:'IRONWOOD_WOLF',required:6,rewardGold:90,rewardItemId:'WOLF_PELT',rewardItemQty:3,act:1,location:'Ironwood Verge',story:'Wolves are leaving the deep wood and following old patrol trails toward the farms. Their tracks circle something farther inside, but first the road has to be made safe.'},
{id:'QST_004',name:'Tools of the Trade',description:'Equip at least 2 pieces of gear.',kind:'equip',required:2,rewardGold:110,rewardItemId:'GREENWOOD_LOG',rewardItemQty:6,act:1,location:'Asterfall Workshop',story:'The smith laughs at the state of your equipment and refuses to call luck a fighting style. If you intend to push deeper, you will need a kit built for more than field vermin.'},
{id:'QST_005',name:'Into Ironwood',description:'Reach character level 10.',kind:'level',required:10,rewardGold:160,rewardItemId:'IRONWOOD_LOG',rewardItemQty:4,act:1,location:'Ironwood Gate',story:'Rumours from the forest no longer sound like frightened farmers exaggerating. Something beneath the roots is stirring, and the wardens will only open the deeper paths to adventurers who have survived long enough to matter.'},
{id:'QST_006',name:'Thorn Beneath',description:'Defeat 8 Thornlings.',kind:'kills',targetId:'THORNLING',required:8,rewardGold:210,rewardItemId:'THORN_SAP',rewardItemQty:5,act:2,location:'Ironwood Deep',story:'Thornlings are gathering around trees marked with old oath-runes. Their growth is too deliberate to be natural, as if the forest is remembering a command nobody living can hear.'},
{id:'QST_007',name:'Silver on the Water',description:'Collect 6 River Eels.',kind:'item',targetId:'RIVER_EEL',required:6,rewardGold:240,rewardItemId:'SILVERFIN',rewardItemQty:6,act:2,location:'Silverbrook',story:'Silverbrook’s ferrymen report pale lights moving beneath the current at night. The village needs food, but the catch may also reveal why the river has begun carrying fragments of echo-touched debris downstream.'},
{id:'QST_008',name:'Old Mine Bell',description:'Defeat 10 Cave Skitters.',kind:'kills',targetId:'CAVE_SKITTER',required:10,rewardGold:300,rewardItemId:'ASTER_IRON_ORE',rewardItemQty:5,act:2,location:'Old Mines',story:'A bell rings below the abandoned mine despite its rope having rotted decades ago. Skitters flood the upper shafts whenever it sounds. Clearing them is the only way to reach the sealed workings below.'},
{id:'QST_009',name:'Rootbound Vault',description:'Defeat 6 Ancient Treants.',kind:'kills',targetId:'ANCIENT_TREANT',required:6,rewardGold:360,rewardItemId:'TROLL_HIDE',rewardItemQty:2,act:2,location:'Ancient Grove',story:'The oldest treants have rooted themselves around a buried stone vault. Their bark carries the same oath-marks found deeper in Ironwood, turning a forest mystery into a trail toward something deliberately hidden.'},
{id:'QST_010',name:'Lanterns in Fog',description:'Defeat 10 Lantern Wretches.',kind:'kills',targetId:'LANTERN_WRETCH',required:10,rewardGold:430,rewardItemId:'WISP_DUST',rewardItemQty:8,act:2,location:"King's Road Fogline",story:'Lanterns appear along the abandoned royal road after sunset. Travelers who follow them vanish. The things carrying those lights wear scraps of an army that should have died with the old oath.'},
{id:'QST_011',name:'Place Among Guilds',description:'Reach character level 20.',kind:'level',required:20,rewardGold:500,rewardItemId:'OATHGLASS_SHARD',rewardItemQty:2,act:3,location:'Asterfall Guildhall',story:'The guilds stop treating you as a passing sword. Reports from the King’s Road now carry your name, and older adventurers begin speaking openly of the oathbound host gathering beyond the fog.'},
{id:'QST_012',name:'Fallen Procession',description:'Defeat 8 Oathbound Squires.',kind:'kills',targetId:'OATHBOUND_SQUIRE',required:8,rewardGold:600,rewardItemId:'OATHGLASS_SHARD',rewardItemQty:3,act:3,location:"King's Road",story:'Armoured dead march in formation toward Asterfall, still obeying an order issued generations ago. Breaking the procession may reveal who—or what—has called the old soldiers back to duty.'},
{id:'QST_013',name:'Oathglass Road',description:'Defeat 10 Fallen Sentinels.',kind:'kills',targetId:'FALLEN_SENTINEL',required:10,rewardGold:750,rewardItemId:'OATHGLASS_SHARD',rewardItemQty:5,act:3,location:'Oathglass Causeway',story:'Fallen Sentinels guard the causeway in disciplined silence. Beyond them stands the shattered command post where the last royal defense made its final oath and where its commander never truly left.'},
{id:'QST_014',name:'Fallen Knight',description:'Defeat the Fallen Knight.',kind:'boss',targetId:'FALLEN_KNIGHT',required:1,rewardGold:1000,rewardItemId:'OATHGLASS_SHARD',rewardItemQty:5,act:3,location:'Ruined Oathgate',story:'The echoes finally have a face. The Fallen Knight still holds the gate as though the kingdom behind him survives, bound to an oath that has outlived everyone it was meant to protect.'},
{id:'QST_015',name:'Beyond the Green',description:'Claim victory over the Fallen Knight and reach level 25.',kind:'level',required:25,rewardGold:1250,rewardItemId:'OATHGLASS_CAPE',rewardItemQty:1,act:3,location:'Eastern Oathgate',story:'With the Knight defeated, the sealed routes beyond Asterfall begin to open. The victory ends one chapter, but the echoes carried on the wind make it clear the broken oath was never confined to the green lands.'},
];
