import type {ClassId} from '../core/types';
import {NOVICE_RECIPES} from './novice-sets';
import {ITEMS} from './items';
import {TOOL_RECIPES} from './gathering-tools';
import {ALCHEMY_RECIPES} from './alchemy';
import {V33_EQUIPMENT_RECIPES} from './equipment-recipes-v33';
export interface GatherDef{id:string;skillId:'mining'|'woodcutting'|'fishing'|'herbalism';name:string;unlockLevel:number;seconds:number;xp:number;itemId:string;min:number;max:number;zoneId:string;difficultyMultiplier:number;recommendedToolTier:number;}
export const GATHERING:GatherDef[]=([
{id:'COPPER_VEIN',skillId:'mining',name:'Copper Vein',unlockLevel:1,seconds:15,xp:9,itemId:'COPPER_ORE',min:1,max:2,zoneId:'OLD_MINES'},
{id:'ASTER_IRON_VEIN',skillId:'mining',name:'Aster-Iron Vein',unlockLevel:8,seconds:24,xp:18,itemId:'ASTER_IRON_ORE',min:1,max:2,zoneId:'OLD_MINES'},
{id:'OATHSTONE_SEAM',skillId:'mining',name:'Oathstone Seam',unlockLevel:16,seconds:36,xp:29,itemId:'OATHSTONE_ORE',min:1,max:1,zoneId:'OLD_MINES'},
{id:'ECHO_QUARTZ_GEODE',skillId:'mining',name:'Echo Quartz Geode',unlockLevel:20,seconds:38,xp:42,itemId:'ECHO_QUARTZ',min:1,max:1,zoneId:'OLD_MINES'},

{id:'GREENWOOD_TREE',skillId:'woodcutting',name:'Greenwood Tree',unlockLevel:1,seconds:14,xp:8,itemId:'GREENWOOD_LOG',min:1,max:2,zoneId:'GREENFIELDS'},
{id:'IRONWOOD_TREE',skillId:'woodcutting',name:'Ironwood Tree',unlockLevel:7,seconds:24,xp:17,itemId:'IRONWOOD_LOG',min:1,max:2,zoneId:'IRONWOOD'},
{id:'CROWNWOOD_TREE',skillId:'woodcutting',name:'Crownwood Tree',unlockLevel:15,seconds:36,xp:27,itemId:'CROWNWOOD_LOG',min:1,max:1,zoneId:'IRONWOOD'},

{id:'SILVERBROOK_SHOAL',skillId:'fishing',name:'Silverbrook Shoal',unlockLevel:1,seconds:17,xp:9,itemId:'SILVERFIN',min:1,max:2,zoneId:'SILVERBROOK'},
{id:'RIVER_EEL_POOL',skillId:'fishing',name:'River Eel Pool',unlockLevel:8,seconds:29,xp:18,itemId:'RIVER_EEL',min:1,max:1,zoneId:'SILVERBROOK'},
{id:'OATHSCALE_POOL',skillId:'fishing',name:'Oathscale Pool',unlockLevel:16,seconds:41,xp:28,itemId:'OATHSCALE_PIKE',min:1,max:1,zoneId:'SILVERBROOK'},
// The 24-hour AFK window is generous; each gathering cycle is therefore
// stretched by a noticeable amount to avoid rapid early skill acceleration.
] as Omit<GatherDef,'difficultyMultiplier'|'recommendedToolTier'>[]).map(activity=>{
  const difficultyMultiplier=activity.unlockLevel>=15?1.5:activity.unlockLevel>=7?1.2:1;
  const recommendedToolTier=activity.unlockLevel>=15?3:activity.unlockLevel>=7?2:1;
  return {...activity,seconds:Math.ceil(activity.seconds*2),difficultyMultiplier,recommendedToolTier};
});

export interface Recipe{id:string;name:string;skillId:'smithing'|'cooking'|'alchemy';level:number;xp:number;gold:number;seconds:number;repeatableTraining?:boolean;inputs:{itemId:string;quantity:number}[];output:{itemId:string;quantity:number};classId?:ClassId;noviceSetId?:string;characterLevel?:number;requiresCraftedItemId?:string;v33EquipmentTier?:string;v33Region?:string;v33SetId?:string;v33Path?:string;}
const frostCompleteSetIds=new Set(['frostbell_panoply','winterchain_harness','aurora_vespers','whiteout_stalker','glacierblood_array','rimeglass_script','snowveil_regalia','choirfrost_resonance']);
const generatedSetSlots=new Set(['helmet','legs','boots','weapon','offhand','amulet']);
const GENERATED_COMPLETE_SET_RECIPES:Recipe[]=ITEMS.filter(item=>item.type==='gear'&&item.slot&&item.equipmentSetId&&!/^T[1-9]_/.test(item.equipmentSetId)&&(frostCompleteSetIds.has(item.equipmentSetId)||generatedSetSlots.has(item.slot))).map(item=>{
  const frost=item.id.startsWith('RIMEBOUND_'),sunscar=item.id.startsWith('SUNSCORED_');
  const inputs=frost?[{itemId:'FROSTIRON',quantity:item.slot==='chest'?20:12},{itemId:'RIMEGLASS',quantity:item.slot==='ring'?3:5},{itemId:'CHOIR_BLOOM',quantity:1}]:sunscar?[{itemId:'SUNSTONE_ORE',quantity:8},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}]:[{itemId:'OATHSTONE_INGOT',quantity:18},{itemId:'OATHGLASS_SHARD',quantity:9},{itemId:'TORN_OATHCLOTH',quantity:6}];
  return {id:`CRAFT_${item.id}`,name:item.name,skillId:'smithing',level:frost?59:sunscar?35:22,xp:frost?2050:sunscar?1450:850,gold:frost?7900:sunscar?5000:2300,seconds:frost?840:sunscar?570:330,inputs,output:{itemId:item.id,quantity:1},classId:item.classRestriction,characterLevel:frost?62:sunscar?38:21};
});
export const RECIPES:Recipe[]=([
...ALCHEMY_RECIPES as Recipe[],
...NOVICE_RECIPES,
...GENERATED_COMPLETE_SET_RECIPES,
...(V33_EQUIPMENT_RECIPES as Recipe[]),
...(TOOL_RECIPES as Recipe[]),
{id:'SMELT_COPPER_INGOT',name:'Smelt Copper Batch',skillId:'smithing',level:1,xp:80,gold:30,seconds:36,repeatableTraining:true,inputs:[{itemId:'COPPER_ORE',quantity:10}],output:{itemId:'COPPER_INGOT',quantity:5}},
{id:'SMELT_ASTER_IRON_INGOT',name:'Smelt Aster-Iron Batch',skillId:'smithing',level:8,xp:140,gold:50,seconds:42,repeatableTraining:true,inputs:[{itemId:'ASTER_IRON_ORE',quantity:8}],output:{itemId:'ASTER_IRON_INGOT',quantity:4}},
{id:'FORGE_REINFORCED_FITTING',name:'Forge Reinforced Fitting',skillId:'smithing',level:12,xp:180,gold:50,seconds:48,repeatableTraining:true,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:2},{itemId:'IRONWOOD_LOG',quantity:2}],output:{itemId:'REINFORCED_FITTING',quantity:1}},
{id:'SMELT_OATHSTONE_INGOT',name:'Smelt Oathstone Batch',skillId:'smithing',level:16,xp:230,gold:80,seconds:54,repeatableTraining:true,inputs:[{itemId:'OATHSTONE_ORE',quantity:6}],output:{itemId:'OATHSTONE_INGOT',quantity:3}},

{id:'SMITH_COPPER_BLADE',name:'Copper Blade',skillId:'smithing',level:3,xp:120,gold:180,seconds:84,inputs:[{itemId:'COPPER_INGOT',quantity:12},{itemId:'GREENWOOD_LOG',quantity:24}],output:{itemId:'COPPER_BLADE',quantity:1}},
{id:'SMITH_ASTER_IRON_BLADE',name:'Aster-Iron Blade',skillId:'smithing',level:9,xp:260,gold:550,seconds:126,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:28},{itemId:'IRONWOOD_LOG',quantity:50},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'ASTER_IRON_BLADE',quantity:1}},
{id:'SMITH_ASTER_IRON_HELM',name:'Aster-Iron Helm',skillId:'smithing',level:10,xp:300,gold:620,seconds:132,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:30},{itemId:'IRONWOOD_LOG',quantity:40},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'ASTER_IRON_HELM',quantity:1}},
{id:'SMITH_IRONWOOD_GUARD',name:'Ironwood Guard',skillId:'smithing',level:11,xp:320,gold:660,seconds:138,inputs:[{itemId:'IRONWOOD_LOG',quantity:80},{itemId:'ASTER_IRON_INGOT',quantity:20},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'IRONWOOD_GUARD',quantity:1}},
{id:'SMITH_IRONWOOD_LONGBOW',name:'Ironwood Longbow',skillId:'smithing',level:12,xp:340,gold:700,seconds:144,inputs:[{itemId:'IRONWOOD_LOG',quantity:90},{itemId:'ASTER_IRON_INGOT',quantity:18},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'IRONWOOD_LONGBOW',quantity:1}},
{id:'SMITH_IRONWOOD_STAFF',name:'Ironwood Runestaff',skillId:'smithing',level:12,xp:340,gold:700,seconds:144,inputs:[{itemId:'IRONWOOD_LOG',quantity:85},{itemId:'WISP_DUST',quantity:24},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'IRONWOOD_STAFF',quantity:1}},
{id:'SMITH_IRONWOOD_DAGGERS',name:'Ironwood Twin Daggers',skillId:'smithing',level:12,xp:340,gold:700,seconds:144,inputs:[{itemId:'IRONWOOD_LOG',quantity:65},{itemId:'ASTER_IRON_INGOT',quantity:24},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'IRONWOOD_DAGGERS',quantity:1}},
{id:'SMITH_IRONWOOD_GREATAXE',name:'Ironwood Great-Axe',skillId:'smithing',level:12,xp:340,gold:700,seconds:144,inputs:[{itemId:'IRONWOOD_LOG',quantity:65},{itemId:'ASTER_IRON_INGOT',quantity:30},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'IRONWOOD_GREATAXE',quantity:1}},
{id:'SMITH_ASTER_IRON_LEGS',name:'Aster-Iron Legguards',skillId:'smithing',level:13,xp:420,gold:950,seconds:174,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:42},{itemId:'IRONWOOD_LOG',quantity:60},{itemId:'REINFORCED_FITTING',quantity:4}],output:{itemId:'ASTER_IRON_LEGS',quantity:1}},
{id:'SMITH_ASTER_IRON_BOOTS',name:'Aster-Iron Greaves',skillId:'smithing',level:11,xp:360,gold:820,seconds:156,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:30},{itemId:'IRONWOOD_LOG',quantity:42},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'ASTER_IRON_BOOTS',quantity:1}},
{id:'SMITH_ASTER_IRON_GLOVES',name:'Aster-Iron Gauntlets',skillId:'smithing',level:11,xp:360,gold:820,seconds:156,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:28},{itemId:'IRONWOOD_LOG',quantity:36},{itemId:'REINFORCED_FITTING',quantity:3}],output:{itemId:'ASTER_IRON_GLOVES',quantity:1}},
{id:'SMITH_ASTER_IRON_CHEST',name:'Aster-Iron Cuirass',skillId:'smithing',level:15,xp:520,gold:1250,seconds:216,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:55},{itemId:'IRONWOOD_LOG',quantity:80},{itemId:'REINFORCED_FITTING',quantity:5}],output:{itemId:'ASTER_IRON_CHEST',quantity:1}},
{id:'SMITH_OATHSTONE_HELM',name:'Oathstone Greathelm',skillId:'smithing',level:17,xp:620,gold:1520,seconds:252,inputs:[{itemId:'OATHSTONE_INGOT',quantity:20},{itemId:'ASTER_IRON_INGOT',quantity:22},{itemId:'OATHGLASS_SHARD',quantity:5}],output:{itemId:'OATHSTONE_HELM',quantity:1}},
{id:'SMITH_OATHSTONE_WARD',name:'Oathstone Wardplate',skillId:'smithing',level:18,xp:700,gold:1850,seconds:288,inputs:[{itemId:'OATHSTONE_INGOT',quantity:28},{itemId:'ASTER_IRON_INGOT',quantity:32},{itemId:'CROWNWOOD_LOG',quantity:48},{itemId:'OATHGLASS_SHARD',quantity:8}],output:{itemId:'OATHSTONE_WARDPLATE',quantity:1}},
{id:'SMITH_OATHSTONE_GAUNTLETS',name:'Oathstone Gauntlets',skillId:'smithing',level:18,xp:650,gold:1580,seconds:258,inputs:[{itemId:'OATHSTONE_INGOT',quantity:18},{itemId:'ASTER_IRON_INGOT',quantity:18},{itemId:'OATHGLASS_SHARD',quantity:5}],output:{itemId:'OATHSTONE_GAUNTLETS',quantity:1}},
{id:'SMITH_OATHSTONE_GREAVES',name:'Oathstone Greaves',skillId:'smithing',level:19,xp:680,gold:1640,seconds:264,inputs:[{itemId:'OATHSTONE_INGOT',quantity:20},{itemId:'ASTER_IRON_INGOT',quantity:20},{itemId:'OATHGLASS_SHARD',quantity:5}],output:{itemId:'OATHSTONE_GREAVES',quantity:1}},
{id:'SMITH_OATHSTONE_LEGPLATES',name:'Oathstone Legplates',skillId:'smithing',level:20,xp:760,gold:1980,seconds:300,inputs:[{itemId:'OATHSTONE_INGOT',quantity:26},{itemId:'ASTER_IRON_INGOT',quantity:28},{itemId:'OATHGLASS_SHARD',quantity:7}],output:{itemId:'OATHSTONE_LEGPLATES',quantity:1}},
{id:'SMITH_OATHSTONE_BLADE',name:'Oathstone Runeblade',skillId:'smithing',level:20,xp:780,gold:2050,seconds:306,inputs:[{itemId:'OATHSTONE_INGOT',quantity:24},{itemId:'CROWNWOOD_LOG',quantity:30},{itemId:'OATHGLASS_SHARD',quantity:7}],output:{itemId:'OATHSTONE_BLADE',quantity:1}},
{id:'SMITH_OATHSTONE_TOWER_SHIELD',name:'Oathstone Tower Shield',skillId:'smithing',level:21,xp:820,gold:2180,seconds:324,inputs:[{itemId:'OATHSTONE_INGOT',quantity:28},{itemId:'CROWNWOOD_LOG',quantity:38},{itemId:'REINFORCED_FITTING',quantity:8}],output:{itemId:'OATHSTONE_TOWER_SHIELD',quantity:1}},
{id:'SMITH_OATHSTONE_MANTLE',name:'Oathstone Mantle',skillId:'smithing',level:22,xp:860,gold:2280,seconds:336,inputs:[{itemId:'OATHSTONE_INGOT',quantity:18},{itemId:'CROWNWOOD_LOG',quantity:42},{itemId:'OATHGLASS_SHARD',quantity:9}],output:{itemId:'OATHSTONE_MANTLE',quantity:1}},
{id:'SMITH_OATHSTONE_AMULET',name:'Oathstone Ward Amulet',skillId:'smithing',level:23,xp:900,gold:2400,seconds:348,inputs:[{itemId:'OATHSTONE_INGOT',quantity:14},{itemId:'OATHGLASS_SHARD',quantity:12},{itemId:'REINFORCED_FITTING',quantity:5}],output:{itemId:'OATHSTONE_AMULET',quantity:1}},
{id:'SMITH_OATHSTONE_SIGNET',name:'Oathstone Signet',skillId:'smithing',level:24,xp:940,gold:2550,seconds:360,inputs:[{itemId:'OATHSTONE_INGOT',quantity:12},{itemId:'OATHGLASS_SHARD',quantity:14},{itemId:'REINFORCED_FITTING',quantity:5}],output:{itemId:'OATHSTONE_SIGNET',quantity:1}},
{id:'CRAFT_STONEHEART_CHEST',name:'Stoneheart Chest',skillId:'smithing',level:18,xp:760,gold:1900,seconds:300,inputs:[{itemId:'OATHSTONE_INGOT',quantity:34},{itemId:'THORN_SAP',quantity:22},{itemId:'TROLL_HIDE',quantity:12}],output:{itemId:'STONEHEART_CHEST',quantity:1},classId:'IRONWARDEN'},
{id:'CRAFT_STONEHEART_GLOVES',name:'Stoneheart Gloves',skillId:'smithing',level:19,xp:700,gold:1650,seconds:270,inputs:[{itemId:'OATHSTONE_INGOT',quantity:22},{itemId:'THORN_SAP',quantity:16},{itemId:'TROLL_HIDE',quantity:8}],output:{itemId:'STONEHEART_GLOVES',quantity:1},classId:'IRONWARDEN'},
{id:'CRAFT_STONEHEART_CAPE',name:'Stoneheart Cape',skillId:'smithing',level:20,xp:820,gold:2100,seconds:330,inputs:[{itemId:'CROWNWOOD_LOG',quantity:42},{itemId:'THORN_SAP',quantity:28},{itemId:'TROLL_HIDE',quantity:14}],output:{itemId:'STONEHEART_CAPE',quantity:1},classId:'IRONWARDEN'},
{id:'CRAFT_STONEHEART_RING',name:'Stoneheart Ring',skillId:'smithing',level:22,xp:900,gold:2400,seconds:360,inputs:[{itemId:'OATHSTONE_INGOT',quantity:18},{itemId:'OATHGLASS_SHARD',quantity:15},{itemId:'THORN_SAP',quantity:12}],output:{itemId:'STONEHEART_RING',quantity:1},classId:'IRONWARDEN'},
{id:'CRAFT_LASTWALL_CHEST',name:'Lastwall Chestguard',skillId:'smithing',level:20,xp:850,gold:2250,seconds:330,inputs:[{itemId:'OATHSTONE_INGOT',quantity:36},{itemId:'LANTERNSTEEL_SHARD',quantity:5},{itemId:'TORN_OATHCLOTH',quantity:8}],output:{itemId:'LASTWALL_CHEST',quantity:1},classId:'BASTION',characterLevel:21},
{id:'CRAFT_LASTWALL_GLOVES',name:'Lastwall Gauntlets',skillId:'smithing',level:20,xp:740,gold:1950,seconds:300,inputs:[{itemId:'OATHSTONE_INGOT',quantity:24},{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'TORN_OATHCLOTH',quantity:5}],output:{itemId:'LASTWALL_GLOVES',quantity:1},classId:'BASTION',characterLevel:21},
{id:'CRAFT_LASTWALL_CAPE',name:'Lastwall Mantle',skillId:'smithing',level:21,xp:880,gold:2350,seconds:348,inputs:[{itemId:'OATHSTONE_INGOT',quantity:20},{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'TORN_OATHCLOTH',quantity:12}],output:{itemId:'LASTWALL_CAPE',quantity:1},classId:'BASTION',characterLevel:21},
{id:'CRAFT_LASTWALL_RING',name:'Lastwall Signet',skillId:'smithing',level:22,xp:950,gold:2650,seconds:378,inputs:[{itemId:'OATHSTONE_INGOT',quantity:16},{itemId:'LANTERNSTEEL_SHARD',quantity:3},{itemId:'OATHGLASS_SHARD',quantity:14}],output:{itemId:'LASTWALL_RING',quantity:1},classId:'BASTION',characterLevel:21},
{id:'CRAFT_MOURNCHAIN_CHEST',name:'Mournchain Cuirass',skillId:'smithing',level:21,xp:890,gold:2400,seconds:348,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:7},{itemId:'FALLEN_RIVET',quantity:8},{itemId:'TORN_OATHCLOTH',quantity:8}],output:{itemId:'MOURNCHAIN_CHEST',quantity:1},classId:'DREADGUARD',characterLevel:21},
{id:'CRAFT_MOURNCHAIN_GLOVES',name:'Mournchain Grips',skillId:'smithing',level:21,xp:770,gold:2100,seconds:318,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:5},{itemId:'FALLEN_RIVET',quantity:6},{itemId:'TORN_OATHCLOTH',quantity:5}],output:{itemId:'MOURNCHAIN_GLOVES',quantity:1},classId:'DREADGUARD',characterLevel:21},
{id:'CRAFT_MOURNCHAIN_CAPE',name:'Mournchain Shroud',skillId:'smithing',level:22,xp:920,gold:2550,seconds:366,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:5},{itemId:'FALLEN_RIVET',quantity:6},{itemId:'TORN_OATHCLOTH',quantity:12}],output:{itemId:'MOURNCHAIN_CAPE',quantity:1},classId:'DREADGUARD',characterLevel:21},
{id:'CRAFT_MOURNCHAIN_RING',name:'Mournchain Loop',skillId:'smithing',level:23,xp:990,gold:2820,seconds:396,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'FALLEN_RIVET',quantity:8},{itemId:'OATHGLASS_SHARD',quantity:12}],output:{itemId:'MOURNCHAIN_RING',quantity:1},classId:'DREADGUARD',characterLevel:21},
{id:'CRAFT_QUICKPRAYER_CHEST',name:'Quickprayer Chest',skillId:'smithing',level:18,xp:740,gold:1880,seconds:294,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:28},{itemId:'WISP_DUST',quantity:38},{itemId:'OATHGLASS_SHARD',quantity:10}],output:{itemId:'QUICKPRAYER_CHEST',quantity:1},classId:'DAWNKEEPER'},
{id:'CRAFT_QUICKPRAYER_GLOVES',name:'Quickprayer Gloves',skillId:'smithing',level:19,xp:690,gold:1620,seconds:264,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:18},{itemId:'WISP_DUST',quantity:28},{itemId:'OATHGLASS_SHARD',quantity:7}],output:{itemId:'QUICKPRAYER_GLOVES',quantity:1},classId:'DAWNKEEPER'},
{id:'CRAFT_QUICKPRAYER_CAPE',name:'Quickprayer Cape',skillId:'smithing',level:20,xp:810,gold:2080,seconds:324,inputs:[{itemId:'CROWNWOOD_LOG',quantity:30},{itemId:'WISP_DUST',quantity:42},{itemId:'OATHGLASS_SHARD',quantity:12}],output:{itemId:'QUICKPRAYER_CAPE',quantity:1},classId:'DAWNKEEPER'},
{id:'CRAFT_QUICKPRAYER_RING',name:'Quickprayer Ring',skillId:'smithing',level:22,xp:890,gold:2380,seconds:354,inputs:[{itemId:'ASTER_IRON_INGOT',quantity:14},{itemId:'WISP_DUST',quantity:34},{itemId:'OATHGLASS_SHARD',quantity:16}],output:{itemId:'QUICKPRAYER_RING',quantity:1},classId:'DAWNKEEPER'},
{id:'CRAFT_TRACKER_CHEST',name:'Tracker Chest',skillId:'smithing',level:25,xp:1080,gold:3100,seconds:420,inputs:[{itemId:'ECHO_TOUCHED_PELT',quantity:6},{itemId:'TORN_OATHCLOTH',quantity:8},{itemId:'OATHGLASS_SHARD',quantity:10}],output:{itemId:'TRACKER_CHEST',quantity:1},classId:'WAYFINDER',characterLevel:25},
{id:'CRAFT_TRACKER_GLOVES',name:'Tracker Gloves',skillId:'smithing',level:25,xp:940,gold:2750,seconds:390,inputs:[{itemId:'ECHO_TOUCHED_PELT',quantity:4},{itemId:'TORN_OATHCLOTH',quantity:6},{itemId:'OATHGLASS_SHARD',quantity:7}],output:{itemId:'TRACKER_GLOVES',quantity:1},classId:'WAYFINDER',characterLevel:25},
{id:'CRAFT_TRACKER_CAPE',name:'Tracker Cape',skillId:'smithing',level:26,xp:1120,gold:3300,seconds:450,inputs:[{itemId:'ECHO_TOUCHED_PELT',quantity:5},{itemId:'TORN_OATHCLOTH',quantity:10},{itemId:'OATHGLASS_SHARD',quantity:11}],output:{itemId:'TRACKER_CAPE',quantity:1},classId:'WAYFINDER',characterLevel:25},
{id:'CRAFT_TRACKER_RING',name:'Tracker Ring',skillId:'smithing',level:27,xp:1180,gold:3600,seconds:480,inputs:[{itemId:'ECHO_TOUCHED_PELT',quantity:3},{itemId:'TORN_OATHCLOTH',quantity:5},{itemId:'OATHGLASS_SHARD',quantity:14}],output:{itemId:'TRACKER_RING',quantity:1},classId:'WAYFINDER',characterLevel:25},
{id:'CRAFT_BLOODRUSH_CHEST',name:'Bloodrush Chest',skillId:'smithing',level:21,xp:900,gold:2500,seconds:360,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:6},{itemId:'BANNER_ASH',quantity:8},{itemId:'FALLEN_RIVET',quantity:6}],output:{itemId:'BLOODRUSH_CHEST',quantity:1},classId:'RAVAGER',characterLevel:21},
{id:'CRAFT_BLOODRUSH_GLOVES',name:'Bloodrush Gloves',skillId:'smithing',level:21,xp:780,gold:2200,seconds:330,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'BANNER_ASH',quantity:6},{itemId:'FALLEN_RIVET',quantity:4}],output:{itemId:'BLOODRUSH_GLOVES',quantity:1},classId:'RAVAGER',characterLevel:21},
{id:'CRAFT_BLOODRUSH_CAPE',name:'Bloodrush Cape',skillId:'smithing',level:22,xp:940,gold:2700,seconds:390,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:5},{itemId:'BANNER_ASH',quantity:10},{itemId:'FALLEN_RIVET',quantity:5}],output:{itemId:'BLOODRUSH_CAPE',quantity:1},classId:'RAVAGER',characterLevel:21},
{id:'CRAFT_BLOODRUSH_RING',name:'Bloodrush Ring',skillId:'smithing',level:23,xp:1000,gold:2950,seconds:420,inputs:[{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'BANNER_ASH',quantity:6},{itemId:'FALLEN_RIVET',quantity:8}],output:{itemId:'BLOODRUSH_RING',quantity:1},classId:'RAVAGER',characterLevel:21},
{id:'CRAFT_SPELLGLASS_CHEST',name:'Spellglass Chest',skillId:'smithing',level:22,xp:920,gold:2550,seconds:372,inputs:[{itemId:'ECHO_QUARTZ',quantity:7},{itemId:'OATHGLASS_FRAGMENT',quantity:5},{itemId:'WISP_DUST',quantity:10}],output:{itemId:'SPELLGLASS_CHEST',quantity:1},classId:'HEXWEAVER',characterLevel:21},
{id:'CRAFT_SPELLGLASS_GLOVES',name:'Spellglass Gloves',skillId:'smithing',level:22,xp:800,gold:2250,seconds:342,inputs:[{itemId:'ECHO_QUARTZ',quantity:5},{itemId:'OATHGLASS_FRAGMENT',quantity:3},{itemId:'WISP_DUST',quantity:8}],output:{itemId:'SPELLGLASS_GLOVES',quantity:1},classId:'HEXWEAVER',characterLevel:21},
{id:'CRAFT_SPELLGLASS_CAPE',name:'Spellglass Cape',skillId:'smithing',level:23,xp:960,gold:2750,seconds:402,inputs:[{itemId:'ECHO_QUARTZ',quantity:6},{itemId:'OATHGLASS_FRAGMENT',quantity:5},{itemId:'WISP_DUST',quantity:12}],output:{itemId:'SPELLGLASS_CAPE',quantity:1},classId:'HEXWEAVER',characterLevel:21},
{id:'CRAFT_SPELLGLASS_RING',name:'Spellglass Ring',skillId:'smithing',level:24,xp:1020,gold:3050,seconds:432,inputs:[{itemId:'ECHO_QUARTZ',quantity:6},{itemId:'OATHGLASS_FRAGMENT',quantity:6},{itemId:'WISP_DUST',quantity:8}],output:{itemId:'SPELLGLASS_RING',quantity:1},classId:'HEXWEAVER',characterLevel:21},
{id:'CRAFT_NIGHTFANG_CHEST',name:'Nightfang Chest',skillId:'smithing',level:22,xp:930,gold:2600,seconds:378,inputs:[{itemId:'GLOAM_DUST',quantity:8},{itemId:'LANTERNSTEEL_SHARD',quantity:5},{itemId:'ECHO_QUARTZ',quantity:4}],output:{itemId:'NIGHTFANG_CHEST',quantity:1},classId:'KNIFE_DANCER',characterLevel:21},
{id:'CRAFT_NIGHTFANG_GLOVES',name:'Nightfang Gloves',skillId:'smithing',level:22,xp:810,gold:2280,seconds:348,inputs:[{itemId:'GLOAM_DUST',quantity:6},{itemId:'LANTERNSTEEL_SHARD',quantity:3},{itemId:'ECHO_QUARTZ',quantity:3}],output:{itemId:'NIGHTFANG_GLOVES',quantity:1},classId:'KNIFE_DANCER',characterLevel:21},
{id:'CRAFT_NIGHTFANG_CAPE',name:'Nightfang Cape',skillId:'smithing',level:23,xp:970,gold:2800,seconds:408,inputs:[{itemId:'GLOAM_DUST',quantity:10},{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'ECHO_QUARTZ',quantity:4}],output:{itemId:'NIGHTFANG_CAPE',quantity:1},classId:'KNIFE_DANCER',characterLevel:21},
{id:'CRAFT_NIGHTFANG_RING',name:'Nightfang Ring',skillId:'smithing',level:24,xp:1030,gold:3100,seconds:438,inputs:[{itemId:'GLOAM_DUST',quantity:7},{itemId:'LANTERNSTEEL_SHARD',quantity:4},{itemId:'ECHO_QUARTZ',quantity:6}],output:{itemId:'NIGHTFANG_RING',quantity:1},classId:'KNIFE_DANCER',characterLevel:21},
{id:'CRAFT_STORMCARVED_CHEST',name:'Stormcarved Chest',skillId:'smithing',level:21,xp:910,gold:2520,seconds:366,inputs:[{itemId:'ECHO_QUARTZ',quantity:7},{itemId:'RUNEBOUND_CORE',quantity:4},{itemId:'ECHO_BAT_WING',quantity:8}],output:{itemId:'STORMCARVED_CHEST',quantity:1},classId:'STONECALLER',characterLevel:21},
{id:'CRAFT_STORMCARVED_GLOVES',name:'Stormcarved Gloves',skillId:'smithing',level:21,xp:790,gold:2220,seconds:336,inputs:[{itemId:'ECHO_QUARTZ',quantity:5},{itemId:'RUNEBOUND_CORE',quantity:3},{itemId:'ECHO_BAT_WING',quantity:6}],output:{itemId:'STORMCARVED_GLOVES',quantity:1},classId:'STONECALLER',characterLevel:21},
{id:'CRAFT_STORMCARVED_CAPE',name:'Stormcarved Cape',skillId:'smithing',level:22,xp:950,gold:2720,seconds:396,inputs:[{itemId:'ECHO_QUARTZ',quantity:6},{itemId:'RUNEBOUND_CORE',quantity:4},{itemId:'ECHO_BAT_WING',quantity:10}],output:{itemId:'STORMCARVED_CAPE',quantity:1},classId:'STONECALLER',characterLevel:21},
{id:'CRAFT_STORMCARVED_RING',name:'Stormcarved Ring',skillId:'smithing',level:23,xp:1010,gold:3020,seconds:426,inputs:[{itemId:'ECHO_QUARTZ',quantity:6},{itemId:'RUNEBOUND_CORE',quantity:5},{itemId:'ECHO_BAT_WING',quantity:6}],output:{itemId:'STORMCARVED_RING',quantity:1},classId:'STONECALLER',characterLevel:21},
{id:'CRAFT_SUNSCORED_STONEHEART_CHEST',name:'Sunscored Stoneheart Chest',skillId:'smithing',level:35,xp:1660,gold:5600,seconds:660,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STONEHEART_CHEST',quantity:1},classId:'IRONWARDEN',characterLevel:38},
{id:'CRAFT_SUNSCORED_STONEHEART_GLOVES',name:'Sunscored Stoneheart Gloves',skillId:'smithing',level:35,xp:1380,gold:4450,seconds:540,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STONEHEART_GLOVES',quantity:1},classId:'IRONWARDEN',characterLevel:38},
{id:'CRAFT_SUNSCORED_STONEHEART_CAPE',name:'Sunscored Stoneheart Cape',skillId:'smithing',level:35,xp:1510,gold:5000,seconds:600,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STONEHEART_CAPE',quantity:1},classId:'IRONWARDEN',characterLevel:38},
{id:'CRAFT_SUNSCORED_STONEHEART_RING',name:'Sunscored Stoneheart Ring',skillId:'smithing',level:35,xp:1420,gold:4700,seconds:570,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STONEHEART_RING',quantity:1},classId:'IRONWARDEN',characterLevel:38},
{id:'CRAFT_SUNSCORED_LASTWALL_CHEST',name:'Sunscored Lastwall Chestguard',skillId:'smithing',level:35,xp:1660,gold:5650,seconds:660,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_LASTWALL_CHEST',quantity:1},classId:'BASTION',characterLevel:38},
{id:'CRAFT_SUNSCORED_LASTWALL_GLOVES',name:'Sunscored Lastwall Gauntlets',skillId:'smithing',level:35,xp:1380,gold:4480,seconds:540,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_LASTWALL_GLOVES',quantity:1},classId:'BASTION',characterLevel:38},
{id:'CRAFT_SUNSCORED_LASTWALL_CAPE',name:'Sunscored Lastwall Mantle',skillId:'smithing',level:35,xp:1510,gold:5040,seconds:600,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_LASTWALL_CAPE',quantity:1},classId:'BASTION',characterLevel:38},
{id:'CRAFT_SUNSCORED_LASTWALL_RING',name:'Sunscored Lastwall Signet',skillId:'smithing',level:35,xp:1420,gold:4740,seconds:570,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_LASTWALL_RING',quantity:1},classId:'BASTION',characterLevel:38},
{id:'CRAFT_SUNSCORED_MOURNCHAIN_CHEST',name:'Sunscored Mournchain Cuirass',skillId:'smithing',level:35,xp:1700,gold:5750,seconds:666,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_MOURNCHAIN_CHEST',quantity:1},classId:'DREADGUARD',characterLevel:38},
{id:'CRAFT_SUNSCORED_MOURNCHAIN_GLOVES',name:'Sunscored Mournchain Grips',skillId:'smithing',level:35,xp:1420,gold:4580,seconds:546,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_MOURNCHAIN_GLOVES',quantity:1},classId:'DREADGUARD',characterLevel:38},
{id:'CRAFT_SUNSCORED_MOURNCHAIN_CAPE',name:'Sunscored Mournchain Shroud',skillId:'smithing',level:35,xp:1550,gold:5160,seconds:606,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_MOURNCHAIN_CAPE',quantity:1},classId:'DREADGUARD',characterLevel:38},
{id:'CRAFT_SUNSCORED_MOURNCHAIN_RING',name:'Sunscored Mournchain Loop',skillId:'smithing',level:35,xp:1460,gold:4860,seconds:576,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_MOURNCHAIN_RING',quantity:1},classId:'DREADGUARD',characterLevel:38},
{id:'CRAFT_SUNSCORED_QUICKPRAYER_CHEST',name:'Sunscored Quickprayer Chest',skillId:'smithing',level:35,xp:1660,gold:5500,seconds:648,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_QUICKPRAYER_CHEST',quantity:1},classId:'DAWNKEEPER',characterLevel:38},
{id:'CRAFT_SUNSCORED_QUICKPRAYER_GLOVES',name:'Sunscored Quickprayer Gloves',skillId:'smithing',level:35,xp:1380,gold:4380,seconds:534,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_QUICKPRAYER_GLOVES',quantity:1},classId:'DAWNKEEPER',characterLevel:38},
{id:'CRAFT_SUNSCORED_QUICKPRAYER_CAPE',name:'Sunscored Quickprayer Cape',skillId:'smithing',level:35,xp:1510,gold:4920,seconds:594,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_QUICKPRAYER_CAPE',quantity:1},classId:'DAWNKEEPER',characterLevel:38},
{id:'CRAFT_SUNSCORED_QUICKPRAYER_RING',name:'Sunscored Quickprayer Ring',skillId:'smithing',level:35,xp:1420,gold:4620,seconds:564,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_QUICKPRAYER_RING',quantity:1},classId:'DAWNKEEPER',characterLevel:38},
{id:'CRAFT_SUNSCORED_TRACKER_CHEST',name:'Sunscored Tracker Chest',skillId:'smithing',level:35,xp:1660,gold:5700,seconds:654,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_TRACKER_CHEST',quantity:1},classId:'WAYFINDER',characterLevel:38},
{id:'CRAFT_SUNSCORED_TRACKER_GLOVES',name:'Sunscored Tracker Gloves',skillId:'smithing',level:35,xp:1380,gold:4520,seconds:540,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_TRACKER_GLOVES',quantity:1},classId:'WAYFINDER',characterLevel:38},
{id:'CRAFT_SUNSCORED_TRACKER_CAPE',name:'Sunscored Tracker Cape',skillId:'smithing',level:35,xp:1510,gold:5080,seconds:600,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_TRACKER_CAPE',quantity:1},classId:'WAYFINDER',characterLevel:38},
{id:'CRAFT_SUNSCORED_TRACKER_RING',name:'Sunscored Tracker Ring',skillId:'smithing',level:35,xp:1420,gold:4780,seconds:570,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_TRACKER_RING',quantity:1},classId:'WAYFINDER',characterLevel:38},
{id:'CRAFT_SUNSCORED_BLOODRUSH_CHEST',name:'Sunscored Bloodrush Chest',skillId:'smithing',level:35,xp:1660,gold:5800,seconds:660,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_BLOODRUSH_CHEST',quantity:1},classId:'RAVAGER',characterLevel:38},
{id:'CRAFT_SUNSCORED_BLOODRUSH_GLOVES',name:'Sunscored Bloodrush Gloves',skillId:'smithing',level:35,xp:1380,gold:4600,seconds:546,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_BLOODRUSH_GLOVES',quantity:1},classId:'RAVAGER',characterLevel:38},
{id:'CRAFT_SUNSCORED_BLOODRUSH_CAPE',name:'Sunscored Bloodrush Cape',skillId:'smithing',level:35,xp:1510,gold:5160,seconds:606,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_BLOODRUSH_CAPE',quantity:1},classId:'RAVAGER',characterLevel:38},
{id:'CRAFT_SUNSCORED_BLOODRUSH_RING',name:'Sunscored Bloodrush Ring',skillId:'smithing',level:35,xp:1420,gold:4860,seconds:576,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_BLOODRUSH_RING',quantity:1},classId:'RAVAGER',characterLevel:38},
{id:'CRAFT_SUNSCORED_SPELLGLASS_CHEST',name:'Sunscored Spellglass Chest',skillId:'smithing',level:35,xp:1660,gold:5750,seconds:654,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_SPELLGLASS_CHEST',quantity:1},classId:'HEXWEAVER',characterLevel:38},
{id:'CRAFT_SUNSCORED_SPELLGLASS_GLOVES',name:'Sunscored Spellglass Gloves',skillId:'smithing',level:35,xp:1380,gold:4560,seconds:540,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_SPELLGLASS_GLOVES',quantity:1},classId:'HEXWEAVER',characterLevel:38},
{id:'CRAFT_SUNSCORED_SPELLGLASS_CAPE',name:'Sunscored Spellglass Cape',skillId:'smithing',level:35,xp:1510,gold:5120,seconds:600,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_SPELLGLASS_CAPE',quantity:1},classId:'HEXWEAVER',characterLevel:38},
{id:'CRAFT_SUNSCORED_SPELLGLASS_RING',name:'Sunscored Spellglass Ring',skillId:'smithing',level:35,xp:1420,gold:4820,seconds:570,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_SPELLGLASS_RING',quantity:1},classId:'HEXWEAVER',characterLevel:38},
{id:'CRAFT_SUNSCORED_NIGHTFANG_CHEST',name:'Sunscored Nightfang Chest',skillId:'smithing',level:35,xp:1660,gold:5850,seconds:660,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_NIGHTFANG_CHEST',quantity:1},classId:'KNIFE_DANCER',characterLevel:38},
{id:'CRAFT_SUNSCORED_NIGHTFANG_GLOVES',name:'Sunscored Nightfang Gloves',skillId:'smithing',level:35,xp:1380,gold:4640,seconds:546,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_NIGHTFANG_GLOVES',quantity:1},classId:'KNIFE_DANCER',characterLevel:38},
{id:'CRAFT_SUNSCORED_NIGHTFANG_CAPE',name:'Sunscored Nightfang Cape',skillId:'smithing',level:35,xp:1510,gold:5200,seconds:606,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_NIGHTFANG_CAPE',quantity:1},classId:'KNIFE_DANCER',characterLevel:38},
{id:'CRAFT_SUNSCORED_NIGHTFANG_RING',name:'Sunscored Nightfang Ring',skillId:'smithing',level:35,xp:1420,gold:4900,seconds:576,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_NIGHTFANG_RING',quantity:1},classId:'KNIFE_DANCER',characterLevel:38},
{id:'CRAFT_SUNSCORED_STORMCARVED_CHEST',name:'Sunscored Stormcarved Chest',skillId:'smithing',level:35,xp:1660,gold:5700,seconds:654,inputs:[{itemId:'SUNSTONE_ORE',quantity:12},{itemId:'AMBERGLASS',quantity:5},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STORMCARVED_CHEST',quantity:1},classId:'STONECALLER',characterLevel:38},
{id:'CRAFT_SUNSCORED_STORMCARVED_GLOVES',name:'Sunscored Stormcarved Gloves',skillId:'smithing',level:35,xp:1380,gold:4520,seconds:540,inputs:[{itemId:'SUNSTONE_ORE',quantity:6},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STORMCARVED_GLOVES',quantity:1},classId:'STONECALLER',characterLevel:38},
{id:'CRAFT_SUNSCORED_STORMCARVED_CAPE',name:'Sunscored Stormcarved Cape',skillId:'smithing',level:35,xp:1510,gold:5080,seconds:600,inputs:[{itemId:'SUNSTONE_ORE',quantity:7},{itemId:'AMBERGLASS',quantity:3},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STORMCARVED_CAPE',quantity:1},classId:'STONECALLER',characterLevel:38},
{id:'CRAFT_SUNSCORED_STORMCARVED_RING',name:'Sunscored Stormcarved Ring',skillId:'smithing',level:35,xp:1420,gold:4780,seconds:570,inputs:[{itemId:'SUNSTONE_ORE',quantity:5},{itemId:'AMBERGLASS',quantity:2},{itemId:'ASTRAL_SCRIPT',quantity:1}],output:{itemId:'SUNSCORED_STORMCARVED_RING',quantity:1},classId:'STONECALLER',characterLevel:38},
{id:'CRAFT_RIMEBOUND_STONEHEART_CHEST',name:'Rimebound Stoneheart Chest',skillId:'smithing',level:59,xp:2320,gold:8920,seconds:960,inputs:[{itemId:'FROSTIRON',quantity:20},{itemId:'RIMEGLASS',quantity:8},{itemId:'CHOIR_BLOOM',quantity:1}],output:{itemId:'RIMEBOUND_STONEHEART_CHEST',quantity:1},classId:'IRONWARDEN',characterLevel:62},
{id:'CRAFT_RIMEBOUND_STONEHEART_GLOVES',name:'Rimebound Stoneheart Gloves',skillId:'smithing',level:59,xp:1920,gold:7140,seconds:780,inputs:[{itemId:'FROSTIRON',quantity:10},{itemId:'RIMEGLASS',quantity:4},{itemId:'CHOIR_BLOOM',quantity:1}],output:{itemId:'RIMEBOUND_STONEHEART_GLOVES',quantity:1},classId:'IRONWARDEN',characterLevel:62},
{id:'CRAFT_RIMEBOUND_STONEHEART_CAPE',name:'Rimebound Stoneheart Cape',skillId:'smithing',level:59,xp:2110,gold:8060,seconds:870,inputs:[{itemId:'FROSTIRON',quantity:12},{itemId:'RIMEGLASS',quantity:5},{itemId:'CHOIR_BLOOM',quantity:1}],output:{itemId:'RIMEBOUND_STONEHEART_CAPE',quantity:1},classId:'IRONWARDEN',characterLevel:62},
{id:'CRAFT_RIMEBOUND_STONEHEART_RING',name:'Rimebound Stoneheart Ring',skillId:'smithing',level:59,xp:1990,gold:7560,seconds:825,inputs:[{itemId:'FROSTIRON',quantity:8},{itemId:'RIMEGLASS',quantity:3},{itemId:'CHOIR_BLOOM',quantity:1}],output:{itemId:'RIMEBOUND_STONEHEART_RING',quantity:1},classId:'IRONWARDEN',characterLevel:62},

{id:'COOK_SILVERFIN',name:'Cook Silverfin Batch',skillId:'cooking',level:1,xp:100,gold:50,seconds:36,repeatableTraining:true,inputs:[{itemId:'SILVERFIN',quantity:5}],output:{itemId:'COOKED_SILVERFIN',quantity:5}},
{id:'COOK_RIVER_EEL',name:'Sear River Eel Batch',skillId:'cooking',level:8,xp:180,gold:80,seconds:44,repeatableTraining:true,inputs:[{itemId:'RIVER_EEL',quantity:4}],output:{itemId:'SEARED_RIVER_EEL',quantity:4}},
{id:'COOK_OATHSCALE',name:'Roast Oathscale Batch',skillId:'cooking',level:16,xp:260,gold:130,seconds:54,repeatableTraining:true,inputs:[{itemId:'OATHSCALE_PIKE',quantity:3}],output:{itemId:'ROASTED_OATHSCALE',quantity:3}},
{id:'COOK_IRONWOOD_STEW',name:'Ironwood Hunter Stew',skillId:'cooking',level:15,xp:105,gold:140,seconds:66,inputs:[{itemId:'RIVER_EEL',quantity:2},{itemId:'THORN_SAP',quantity:1}],output:{itemId:'IRONWOOD_STEW',quantity:1}},
] as Recipe[]).map(recipe=>recipe.skillId==='smithing'&&!recipe.repeatableTraining&&!recipe.noviceSetId&&!recipe.v33SetId?{...recipe,inputs:recipe.inputs.map(input=>({...input,quantity:input.quantity*2}))}:recipe);
