"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ClassHeroCarousel = ClassHeroCarousel;
const UiIcon_1 = require("../UiIcon");
const react_1 = require("react");
const react_native_1 = require("react-native");
const class_emblem_assets_1 = require("../../theme/class-emblem-assets");
const class_creation_art_1 = require("../../theme/class-creation-art");
const CreationChrome_1 = require("./CreationChrome");
function ClassHeroCarousel({ selected, classes, index, body, onBody, onChange, onIndex, panHandlers }) {
    const presentation = class_creation_art_1.classCreationPresentation[selected.id], art = (0, class_creation_art_1.classCreationArt)(selected.id);
    const { height: windowHeight } = (0, react_native_1.useWindowDimensions)();
    const heroHeight = Math.round(Math.max(240, Math.min(324, windowHeight * .36)));
    const strip = (0, react_1.useRef)(null), fade = (0, react_1.useRef)(new react_native_1.Animated.Value(1)).current;
    const [reducedMotion, setReducedMotion] = (0, react_1.useState)(true);
    (0, react_1.useEffect)(() => { let live = true; void react_native_1.AccessibilityInfo.isReduceMotionEnabled().then(value => { if (live)
        setReducedMotion(value); }); const subscription = react_native_1.AccessibilityInfo.addEventListener('reduceMotionChanged', setReducedMotion); return () => { live = false; subscription.remove(); }; }, []);
    (0, react_1.useEffect)(() => { strip.current?.scrollTo({ x: Math.max(0, index * 64 - 96), animated: !reducedMotion }); fade.stopAnimation(); fade.setValue(reducedMotion ? 1 : .25); const animation = react_native_1.Animated.timing(fade, { toValue: 1, duration: 180, useNativeDriver: true }); if (!reducedMotion)
        animation.start(); return () => animation.stop(); }, [selected.id, body, index, reducedMotion, fade]);
    return <react_native_1.View style={s.root}>
    <react_native_1.View style={s.frame}>
      <react_native_1.View style={[s.heroStage, { height: heroHeight }]} {...panHandlers}>
        <react_native_1.Animated.View style={[react_native_1.StyleSheet.absoluteFill, { opacity: fade }]}>
          <react_native_1.Image accessibilityLabel={`${selected.name}, ${body} class equipment illustration`} source={art[body].front} fadeDuration={0} resizeMode="contain" style={s.hero}/>
        </react_native_1.Animated.View>
        <react_native_1.View pointerEvents="none" style={s.heroTop}><react_native_1.View style={[s.roleBadge, { borderColor: presentation.accent }]}><react_native_1.Text style={[s.role, { color: presentation.accent }]}>{selected.role.toUpperCase()}</react_native_1.Text></react_native_1.View><react_native_1.Image accessible={false} source={class_emblem_assets_1.classEmblemIconArtwork[selected.id]} style={s.crest}/></react_native_1.View>
        <react_native_1.View style={[s.arrows, { top: Math.round((heroHeight - 48) / 2) }]}>{[-1, 1].map(direction => <react_native_1.Pressable key={direction} accessibilityRole="button" accessibilityLabel={direction < 0 ? 'Previous class' : 'Next class'} disabled={classes.length < 2} accessibilityState={{ disabled: classes.length < 2 }} onPress={() => onChange(direction)} style={({ pressed }) => [s.arrow, { opacity: classes.length < 2 ? .35 : pressed ? .65 : 1 }]}><UiIcon_1.UiIcon name={direction < 0 ? 'back' : 'next'} size={24}/></react_native_1.Pressable>)}</react_native_1.View>
      </react_native_1.View>
      <react_native_1.View style={s.nameplate} accessibilityLiveRegion="polite"><react_native_1.Text style={s.className}>{selected.name}</react_native_1.Text><react_native_1.Text style={[s.traits, { color: presentation.accent }]}>{presentation.traits}</react_native_1.Text></react_native_1.View>
    </react_native_1.View>
    <react_native_1.View style={s.browseMeta}><react_native_1.Text style={s.hint}>{index + 1} / {classes.length} · Swipe or select a crest</react_native_1.Text><react_native_1.View style={s.presentation}>{['male', 'female'].map(value => <react_native_1.Pressable key={value} accessibilityRole="button" accessibilityLabel={`Preview ${value} presentation`} accessibilityState={{ selected: body === value }} onPress={() => onBody(value)} style={[s.bodyChoice, body === value && s.bodySelected]}><react_native_1.Text style={[s.bodyLabel, body === value && s.bodyLabelSelected]}>{value === 'male' ? 'Male' : 'Female'}</react_native_1.Text></react_native_1.Pressable>)}</react_native_1.View></react_native_1.View>
    <react_native_1.ScrollView ref={strip} horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.strip}>{classes.map((item, i) => <react_native_1.Pressable key={item.id} accessibilityRole="button" accessibilityLabel={`Select ${item.name}`} accessibilityState={{ selected: item.id === selected.id }} onPress={() => onIndex(i)} style={[s.thumb, item.id === selected.id && s.thumbSelected]}><react_native_1.Image accessible={false} source={class_emblem_assets_1.classEmblemIconArtwork[item.id]} style={s.thumbArt}/><react_native_1.View style={[s.thumbMark, item.id === selected.id && s.thumbMarkSelected]}/></react_native_1.Pressable>)}</react_native_1.ScrollView>
    <react_native_1.Text style={s.description}>{selected.description}</react_native_1.Text>
    <react_native_1.View accessibilityLabel={`${selected.name} role ratings`} style={s.stats}>{[['TANK', selected.roleRatings.tank, '#8BAFC2'], ['DAMAGE', selected.roleRatings.damage, '#D58B72'], ['SUPPORT', selected.roleRatings.support, '#C9A7E8']].map(([label, value, color]) => <react_native_1.View key={label} style={s.stat}><react_native_1.Text style={s.statLabel}>{label}</react_native_1.Text><react_native_1.Text accessibilityLabel={`${label} ${value} out of 5`} style={[s.gems, { color }]}>{'◆'.repeat(value)}<react_native_1.Text style={s.gemEmpty}>{'◇'.repeat(5 - value)}</react_native_1.Text></react_native_1.Text></react_native_1.View>)}</react_native_1.View>
  </react_native_1.View>;
}
const s = react_native_1.StyleSheet.create({
    root: { gap: 16 }, frame: { backgroundColor: 'transparent' }, heroStage: { position: 'relative', backgroundColor: '#020303', borderTopLeftRadius: 84, borderTopRightRadius: 84, borderBottomLeftRadius: 24, borderBottomRightRadius: 24, overflow: 'hidden' }, hero: { width: '100%', height: '100%' }, heroTop: { position: 'absolute', left: 20, right: 20, top: 22, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, roleBadge: { paddingHorizontal: 8, paddingVertical: 6 }, role: { fontSize: 10, fontWeight: '600', letterSpacing: 1.8 }, crest: { width: 44, height: 44 }, arrows: { position: 'absolute', left: 2, right: 2, flexDirection: 'row', justifyContent: 'space-between' }, arrow: { width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }, arrowGlyph: { fontSize: 42, lineHeight: 46, fontWeight: '300', color: '#E2C58F', includeFontPadding: false, textAlignVertical: 'center' },
    nameplate: { alignItems: 'center', paddingTop: 14, paddingBottom: 2, paddingHorizontal: 8, gap: 6 }, className: { color: '#F0DCB3', fontFamily: react_native_1.Platform.OS === 'ios' ? 'Georgia' : 'serif', fontSize: 30, lineHeight: 38, fontWeight: '500', textAlign: 'center' }, traits: { fontSize: 11, lineHeight: 18, textAlign: 'center', fontWeight: '400' }, browseMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8, flexWrap: 'wrap' }, hint: { color: CreationChrome_1.creationColors.muted, fontSize: 11 }, presentation: { flexDirection: 'row', gap: 10 }, bodyChoice: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8, borderBottomWidth: 1, borderColor: 'transparent' }, bodySelected: { borderColor: '#8BAFC2' }, bodyLabel: { fontSize: 12, color: CreationChrome_1.creationColors.muted }, bodyLabelSelected: { color: '#D6E9F1', fontWeight: '600' },
    strip: { gap: 8, paddingVertical: 4 }, thumb: { width: 56, height: 62, alignItems: 'center', justifyContent: 'center', borderRadius: 28 }, thumbSelected: { backgroundColor: 'rgba(110,175,209,.12)' }, thumbArt: { width: 48, height: 48 }, thumbMark: { width: 4, height: 4, borderRadius: 2, backgroundColor: 'transparent', marginTop: 3 }, thumbMarkSelected: { backgroundColor: CreationChrome_1.creationColors.gold }, description: { color: '#B7C3CF', fontSize: 14, lineHeight: 23, textAlign: 'center', paddingHorizontal: 12 }, stats: { flexDirection: 'row', gap: 10, paddingVertical: 6 }, stat: { flex: 1, alignItems: 'center', paddingVertical: 4, gap: 4 }, statLabel: { color: CreationChrome_1.creationColors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1 }, gems: { fontSize: 13, lineHeight: 20, letterSpacing: 1 }, gemEmpty: { color: '#33414D' },
});
