import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(path.join(root,'backend/package.json'));
await require('esbuild').build({entryPoints:[path.join(root,'backend/online/edge.ts')],outfile:path.join(root,'backend/supabase/functions/gameplay/index.ts'),bundle:true,format:'esm',platform:'neutral',external:['node:crypto'],target:'es2022',legalComments:'none',banner:{js:'// GENERATED by tools/build-online.mjs from the shared, tested game engine. Do not edit.'},logLevel:'info'});
await require('esbuild').build({entryPoints:[path.join(root,'backend/online/coop-edge.ts')],outfile:path.join(root,'backend/supabase/functions/coop/index.ts'),bundle:true,format:'esm',platform:'neutral',external:['node:crypto'],target:'es2022',legalComments:'none',banner:{js:'// GENERATED by tools/build-online.mjs from the existing co-op engine. Do not edit.'},logLevel:'info'});
