import {assert} from './test-assert';
const {readFileSync}=require('fs') as {readFileSync(path:string,encoding:'utf8'):string};
const creation=readFileSync('src/screens/ClassSelectScreen.tsx','utf8');
const carousel=readFileSync('src/components/creation/ClassHeroCarousel.tsx','utf8');
const app=readFileSync('App.tsx','utf8');
const welcome=readFileSync('src/components/AsterfallWelcomeModal.tsx','utf8');
const shell=readFileSync('src/components/OnboardingModalShell.tsx','utf8');
assert.ok(creation.includes('PLAY STYLE'));
assert.ok(creation.includes('playStyle[selected.id]'),'class identity is more specific than its role');
assert.ok(!creation.includes('RoleFilter')&&!creation.includes('chooseRole')&&!creation.includes('filterRow'),'class choice must not add a role-filter row above the selector');
assert.ok(!carousel.includes('heroStage')&&!carousel.includes('class equipment illustration'),'class choice must defer the character-art stage until Identity');
assert.ok(carousel.includes("description:{color:'#E1EAF4'")&&carousel.includes("fontWeight:'500'"),'class description must retain high-contrast, readable copy');
assert.ok(carousel.includes("hint:{color:'#C8D6E6'")&&carousel.includes("statLabel:{color:'#D1DCE8'"),'class selector metadata must remain brighter than muted supporting text');
assert.ok(creation.includes('Choose your character presentation in the next step.'),'class choice must direct appearance selection to Identity');
assert.ok(creation.includes('WHAT HAPPENS NEXT'));
assert.ok(!creation.includes('Your first crafting goal:'));
assert.ok(!creation.includes('Full equipment-set appearances become permanent skin unlocks later.'));
assert.ok(creation.includes('showNameIdeas&&'),'name suggestions are optional, not a permanent strip');
assert.ok(creation.includes('onSubmitEditing={next}'));
assert.ok(creation.includes('const error=characterNameError(name)'),'revalidate the final submission');
assert.ok(creation.includes('Simple outfit · No armor or off-hand equipped'),'do not imply starting armor is granted');
assert.ok(creation.indexOf('step===\'review\'?\'Enter Asterfall\'')>creation.indexOf('<View style={s.footer}>'),'the final action stays in the footer');
assert.ok(creation.includes("step==='class'&&onCancel"),'extra-character flow has no three-button footer');
assert.ok(welcome.includes('WELCOME TO ASTERFALL'));
assert.ok(welcome.includes("row.id==='QST_001'"),'first objective copy follows the quest catalog');
assert.ok(welcome.includes("firstObjective?.description"));
assert.ok(shell.includes('ScrollView')&&shell.includes('useSafeAreaInsets'));
assert.ok(shell.includes('accessibilityViewIsModal'));
assert.ok(shell.includes('reduceMotion=true'),'explanations default to no animation');
assert.ok(!shell.includes('setTimeout'),'explanations are never auto-dismissed');
assert.ok(app.includes('setCreationWelcome({name,classId:id})'));
assert.ok(app.includes('<FirstSessionTutorialPopup step={!creationWelcome&&'), 'welcome must close before first-hunt guidance appears');
assert.ok(app.includes("setCurrentTab('World')"));
console.log('PASS character creation hierarchy and welcome source contract (not native rendering)');
