import {MONSTERS} from '../src/content/monsters';
import {combatPresentation,combatReadiness} from '../src/core/combat-presentation';
import {combatMotionProfile} from '../src/core/combat-motion';
import {encounterIdentity,encounterProfileCoverage} from '../src/core/encounter-identity';
import {createCharacter,newGame,startCombat} from '../src/core/game';
import {COMBAT_TACTICS} from '../src/core/combat-tactics';
import {itemRarity} from '../src/core/item-rarity';
import {itemDef} from '../src/content/items';
import {simulateFallenKnightStoryBattle} from '../src/core/story-boss';
import {challengeFallenKnight} from '../src/core/game';
import {regionalEnemySecondaryStats,regionalSecondaryExchange} from '../src/core/regional-enemy-stats';
const state=createCharacter(newGame(0),'BASTION','Tester');
const monster=MONSTERS[0],start=combatPresentation(state,monster,0,monster.secondsPerKill),late=combatPresentation(state,monster,6,monster.secondsPerKill);
if(start.enemyHp!==monster.hp||late.enemyHp>=start.enemyHp)throw new Error('Enemy health cycle must visibly fall');
if(start.playerHit<1||start.enemyHit<1)throw new Error('Presented damage must remain positive');
const assaultReadiness=combatReadiness(state,monster,undefined,undefined,'assault'),balancedReadiness=combatReadiness(state,monster,undefined,undefined,'balanced'),guardedReadiness=combatReadiness(state,monster,undefined,undefined,'guarded');
if(!(assaultReadiness.recommendedPower>balancedReadiness.recommendedPower&&guardedReadiness.recommendedPower<balancedReadiness.recommendedPower))throw new Error('Combat tactics should visibly trade safety');
if(COMBAT_TACTICS.assault.speedMultiplier<=1||COMBAT_TACTICS.guarded.damageTakenMultiplier>=1)throw new Error('Combat tactic identities drifted');
const assaultState=startCombat(state,'MOSS_RAT',1000,undefined,'assault');if(assaultState.activity?.combatTacticId!=='assault')throw new Error('Combat tactic must snapshot on hunt start');
const motion=combatMotionProfile(monster.secondsPerKill,false),reduced=combatMotionProfile(monster.secondsPerKill,true),fast=combatMotionProfile(.2,false),slow=combatMotionProfile(99,false);
if(!motion.enabled||motion.playerAttackAtMs>=motion.enemyAttackAtMs||motion.enemyAttackAtMs>=motion.cycleMs)throw new Error('Combat motion timing order invalid');
if(reduced.enabled||reduced.playerLungePx!==0||reduced.shakePx!==0)throw new Error('Reduced motion must disable combat transforms');
if(fast.cycleMs!==1800||slow.cycleMs!==5200)throw new Error('Combat motion cadence must stay within UI-safe bounds');
const coverage=encounterProfileCoverage(MONSTERS);if(coverage.authored!==coverage.total||coverage.missing.length)throw new Error(`Encounter identity coverage missing: ${coverage.missing.join(', ')}`);
if(encounterIdentity(MONSTERS.find(row=>row.id==='VENOM_WEAVER')!).archetype!=='Venom Ambush')throw new Error('Venom Weaver encounter identity drifted');
if(encounterIdentity(MONSTERS.find(row=>row.id==='FALLEN_KNIGHT')!).mechanics.length<3)throw new Error('Fallen Knight boss identity needs multi-mechanic presentation');
const stalker=MONSTERS.find(row=>row.id==='MIRE_HERON')!,bulwark=MONSTERS.find(row=>row.id==='IRONBACK_MOLE')!,brute=MONSTERS.find(row=>row.id==='FOREST_TROLL')!;
const stalkerSecondary=regionalEnemySecondaryStats(stalker),bulwarkSecondary=regionalEnemySecondaryStats(bulwark);
if(!(stalkerSecondary.evasion>bulwarkSecondary.evasion&&stalkerSecondary.haste>bulwarkSecondary.haste))throw new Error('Regional enemy archetypes must produce distinct secondary stats');
const baselinePlayer={accuracy:.84,evasion:.04,critChance:.05,critMultiplier:1.5,haste:.05};
const stalkerExchange=regionalSecondaryExchange(baselinePlayer,stalker),bulwarkExchange=regionalSecondaryExchange(baselinePlayer,bulwark),bruteExchange=regionalSecondaryExchange(baselinePlayer,brute);
if(!(stalkerExchange.playerOutputMultiplier<bulwarkExchange.playerOutputMultiplier))throw new Error('Enemy evasion must reduce expected idle-hunt output');
if(!(bruteExchange.enemyCritExpected>bulwarkExchange.enemyCritExpected))throw new Error('Brute crit profile must create higher expected crit pressure');
if(itemRarity(itemDef('MOSS_FIBER'))!=='common'||itemRarity(itemDef('OATHGLASS_CAPE'))!=='epic')throw new Error('Rarity classification failed');
const strongBoss=simulateFallenKnightStoryBattle({name:'Prepared',classId:'WAYFINDER',maxHp:900,currentHp:900,attack:95,defense:95,power:760,accuracy:.96,evasion:.18,critChance:.28,critMultiplier:1.75,haste:.20,damageMultiplier:1.25,actionSpeedMultiplier:1.2,incomingDamageMultiplier:.72,foodHeal:120,foodQuantity:8,autoEatThresholdPct:45},'strong-boss');
if(!strongBoss.won||!strongBoss.phasesReached.includes(2)||!strongBoss.phasesReached.includes(3))throw new Error('Prepared story boss build must visibly reach both phases and win');
if(!strongBoss.events.some(event=>event.type==='telegraph')||!strongBoss.events.some(event=>event.type==='player_hit'&&event.amount&&event.amount>0))throw new Error('Story boss battle must emit telegraphs and damage events for playback');
const oneShotBoss=simulateFallenKnightStoryBattle({name:'Overpowered',classId:'RAVAGER',maxHp:5000,currentHp:5000,attack:5000,defense:1200,power:12000,accuracy:.99,evasion:.35,critChance:.75,critMultiplier:2.2,haste:.45,damageMultiplier:1.8,actionSpeedMultiplier:1.5,incomingDamageMultiplier:.4,foodHeal:0,foodQuantity:0,autoEatThresholdPct:40},'one-shot-boss','rematch');
if(!oneShotBoss.won||oneShotBoss.events.filter(event=>event.type==='player_hit').length!==1||oneShotBoss.phasesReached.length!==1)throw new Error('Sufficiently strong rematch players must be allowed to one-shot the Fallen Knight without phase HP locks');
const weakBoss=simulateFallenKnightStoryBattle({name:'Unprepared',classId:'WAYFINDER',maxHp:105,currentHp:105,attack:18,defense:8,power:95,accuracy:.80,evasion:.02,critChance:.03,critMultiplier:1.5,haste:0,damageMultiplier:.85,actionSpeedMultiplier:.9,incomingDamageMultiplier:1.2,foodHeal:0,foodQuantity:0,autoEatThresholdPct:40},'weak-boss');
if(weakBoss.won||weakBoss.finalPlayerHp>0)throw new Error('Unprepared story boss build must be able to lose through combat rather than a readiness roll');
const storyState={...state,character:{...state.character!,level:25,currentHp:state.character!.hp},quests:state.quests.map(q=>q.questId==='QST_014'?{...q,status:'active' as const}:q)};
const storyAttempt=challengeFallenKnight(storyState,123456);
if(!storyAttempt.battle||storyAttempt.won!==storyAttempt.battle.won)throw new Error('Fallen Knight story command must return the deterministic battle it settled');
const storyWinState={...storyState,character:{...storyState.character!,level:100,hp:5000,currentHp:5000,attack:5000,defense:1200}};
const storyWin=challengeFallenKnight(storyWinState,222222);
if(!storyWin.won||!storyWin.battle)throw new Error('Prepared first story clear must settle through cinematic battle playback');
if(!storyWin.state.inventory.stacks.some(row=>row.itemId==='FALLEN_KNIGHT_SIGIL'&&row.quantity>=1))throw new Error('First Fallen Knight clear must settle the guaranteed story Sigil from the boss drop table');
const repeatReady={...storyWin.state,character:{...storyWin.state.character!,currentHp:storyWin.state.character!.hp}};
const repeat=challengeFallenKnight(repeatReady,222223);
if(!repeat.won||repeat.battle)throw new Error('Post-story Fallen Knight rematches must resolve quickly without replaying the cinematic phase timeline');
if(repeat.state.inventory.stacks.filter(row=>row.itemId==='FALLEN_KNIGHT_SIGIL').reduce((sum,row)=>sum+row.quantity,0)!==1)throw new Error('Weekly rematches must not repeat the unique story Sigil');
console.log(JSON.stringify({status:'PASS',start,late}));
