import {createCharacter,newGame,claimActivity,claimQuest,startCombat,previewActivityReward} from '../src/core/game';
import {executeGameCommand,validateGameCommand} from '../src/core/game-commands';
import {unlockCombatCompanion,equipCombatCompanion,companionCombatContribution,companionLevelCost,applyCompanionBondXp,claimSanctuaryTraining,claimSanctuaryEssence} from '../src/core/combat-companions';
import {refreshCompanions,companionOwned,companionCombatExecutor,recordCompanionActivity} from '../src/core/companion-runtime';
import {migrateSave} from '../src/core/save-migrations';
import {createSaveBackup,parseSaveBackup} from '../src/core/save-transfer';
import {characterPermanentMultipliers} from '../src/core/permanent-boosts';
import {PET_PERMANENT_BOOSTS} from '../src/content/permanent-boosts';
import {COMBAT_COMPANIONS} from '../src/content/combat-companions';
import {companionServerDefinition,companionTechniques} from '../../../backend/src/server/companions/content';
import {buildOwnedCompanionCombatant} from '../../../backend/src/server/companions/combat-adapter';
import {buildCompanionTrialEncounter} from '../../../backend/src/server/companions/trials';
import type {GameState} from '../src/core/types';
let checks=0;function ok(v:unknown,label:string){checks++;if(!v)throw new Error(label);}
function rejects(f:()=>unknown,label:string){let caught=false;try{f();}catch{caught=true;}ok(caught,label);}
const now=Date.UTC(2026,8,13),ids=['UNIT_001','UNIT_002','UNIT_003'];
function fixture(){let s=createCharacter(newGame(now),'IRONWARDEN','Companion Test');for(const id of ids)s=unlockCombatCompanion(s,id,now);s.character!.gold=100000;s.account.companionEssence=10000;s.account.bondstones=100;s.account.companionMaterials={IRONWOOD_FANG:100,RUNEBOUND_CORE:100,WISP_DUST:100,ASTER_IRON_INGOT:100,ECHO_QUARTZ:100,OATHGLASS_SHARD:100,OATHGLASS_FRAGMENT:100};return refreshCompanions(s,now);}
const command=(s:GameState,type:string,args?:Record<string,unknown>,time=now)=>executeGameCommand(s,{type,args},time).state;
const permanentCompanions=COMBAT_COMPANIONS.filter(def=>def.origin.type!=='event'),eventCompanions=COMBAT_COMPANIONS.filter(def=>def.origin.type==='event');
ok(COMBAT_COMPANIONS.length===34,'roster contains 24 permanent and 10 event companions');
ok(permanentCompanions.length===24,'permanent companion count remains 24');
ok(eventCompanions.length===10,'event companion count is 10');
ok(new Set(COMBAT_COMPANIONS.map(def=>def.id)).size===COMBAT_COMPANIONS.length,'companion ids are unique');
ok(eventCompanions.map(def=>def.id).join(',')===Array.from({length:10},(_,index)=>`EVT_UNIT_${String(index+1).padStart(3,'0')}`).join(','),'event companion ids remain EVT_UNIT_001 through EVT_UNIT_010');
let s=fixture();
for(const d of COMBAT_COMPANIONS){ok(companionServerDefinition(d.id)?.role===d.role,`${d.id} role agrees`);ok(companionServerDefinition(d.id)?.rarity===d.rarity,`${d.id} rarity agrees`);}
rejects(()=>command(s,'companion_equip',{id:'UNIT_002'}),'same role rejected');
rejects(()=>command(s,'companion_equip',{id:'UNIT_024'}),'unowned rejected');
s=command(s,'companion_equip',{id:'UNIT_001'});ok(s.character!.equippedCombatCompanionId==='UNIT_001','equip persists');
ok(companionCombatContribution(s).outputMultiplier>1,'assist output applied');
const beforeGold=s.character!.gold,cost=companionLevelCost('standard',1);s=command(s,'companion_level',{id:'UNIT_001'});ok(s.account.combatCompanionProgress!.UNIT_001.level===2&&s.character!.gold===beforeGold-cost.gold,'level and cost atomic');
for(let i=2;i<10;i++)s=command(s,'companion_level',{id:'UNIT_001'});
rejects(()=>command(s,'companion_level',{id:'UNIT_001'}),'ascension gate');
let poor=structuredClone(s);poor.account.bondstones=0;const poorBefore=JSON.stringify(poor);rejects(()=>command(poor,'companion_ascend',{id:'UNIT_001'}),'missing resources rejected');ok(JSON.stringify(poor)===poorBefore,'failure leaves original intact');
s=command(s,'companion_ascend',{id:'UNIT_001'});ok(s.account.combatCompanionProgress!.UNIT_001.ascensionTier===1,'ascend works using companion materials');
s=command(s,'companion_level',{id:'UNIT_001'});ok(s.account.combatCompanionProgress!.UNIT_001.level===11,'higher level unlocked');
const bond=applyCompanionBondXp(s.account.combatCompanionProgress!.UNIT_001,2520);ok(bond.bondLevel===10&&bond.bondXp===2520&&bond.bondTraitUnlocked,'cumulative Bond 10');
s.account.combatCompanionProgress!.UNIT_001=bond;
const technique=companionTechniques('UNIT_001')[0].id;
rejects(()=>command(s,'companion_technique',{id:'UNIT_001',technique}),'technique requires second ascension');
for(let i=11;i<20;i++)s=command(s,'companion_level',{id:'UNIT_001'});
s=command(s,'companion_ascend',{id:'UNIT_001'});
s=command(s,'companion_technique',{id:'UNIT_001',technique});
ok(s.account.combatCompanionProgress!.UNIT_001.selectedTechniqueId===technique,'technique saved');
const backup=parseSaveBackup(createSaveBackup(s));ok(backup.character!.equippedCombatCompanionId==='UNIT_001'&&backup.account.companionEssence===s.account.companionEssence,'save retains equip and currency');
const legacy=createCharacter(newGame(now),'IRONWARDEN','Legacy');legacy.character!.ownedPetIds=['pet_harvest_fox'];legacy.account.unlockedCosmeticPetIds=['pet_harvest_fox'];
const upgraded=migrateSave(legacy);ok(!upgraded.account.unlockedCombatCompanionIds?.length&&upgraded.account.unlockedCosmeticPetIds?.includes('pet_harvest_fox'),'passive pets migrate to account ownership and never become Combat Companions');
legacy.account.unlockedCosmeticPetIds=['pet_harvest_fox','pet_field_mouse'];legacy.character!.ownedPetIds=['pet_harvest_fox','pet_harvest_fox','pet_field_mouse'];
let mult=characterPermanentMultipliers(legacy);const fox=PET_PERMANENT_BOOSTS.pet_harvest_fox,mouse=PET_PERMANENT_BOOSTS.pet_field_mouse;
ok(Math.abs(mult.gatheringSpeedMultiplier-(1+(fox.gatheringSpeedMultiplier!-1)*.25)*(1+(mouse.gatheringSpeedMultiplier!-1)*.25))<1e-10,'inactive collections use 25%, no duplicates');
legacy.character!.selectedCosmeticPetId='pet_harvest_fox';mult=characterPermanentMultipliers(legacy);ok(Math.abs(mult.gatheringSpeedMultiplier-fox.gatheringSpeedMultiplier!*(1+(mouse.gatheringSpeedMultiplier!-1)*.25))<1e-10,'selected pet 100%, others 25%');
legacy.character!.selectedCosmeticPetId='pet_amber_owl';ok(Math.abs(characterPermanentMultipliers(legacy).incomingDamageMultiplier-(1+(fox.incomingDamageMultiplier!-1)*.25))<1e-10,'unowned selected pet cannot grant perk');
let quest=createCharacter(newGame(now),'IRONWARDEN','Quest Hero');quest.quests=quest.quests.map(q=>q.questId==='QST_005'?{...q,status:'complete'}:q);quest=claimQuest(quest,'QST_005');ok(quest.account.unlockedCombatCompanionIds?.includes('UNIT_001'),'existing quest unlock hook');
const killState=recordCompanionActivity(createCharacter(newGame(now),'WAYFINDER','Mine Hero'),'combat','CAVE_SKITTER',250,now);ok(killState.account.unlockedCombatCompanionIds?.includes('UNIT_002'),'mine kills unlock sentry');
let hunt=command(fixture(),'companion_equip',{id:'UNIT_001'});hunt=startCombat(hunt,'MOSS_RAT',now);const oldXp=hunt.account.combatCompanionProgress!.UNIT_001.xp;const claimed=claimActivity(hunt,now+60000);ok(claimed.reward.kills>0&&claimed.state.account.combatCompanionProgress!.UNIT_001.bondXp>0,'real hunting awards progression');
const solo=structuredClone(hunt);solo.character!.equippedCombatCompanionId=undefined;ok(previewActivityReward(hunt,now+600000).kills>=previewActivityReward(solo,now+600000).kills,'companion helps hunt');ok(!!oldXp||claimed.state.account.combatCompanionProgress!.UNIT_001.xp!==oldXp,'XP changes');
let trial=fixture();for(const id of ids)trial.account.combatCompanionProgress![id]={...trial.account.combatCompanionProgress![id],level:20,ascensionTier:2,bondLevel:10,bondXp:2520,bondTraitUnlocked:true};
trial=command(trial,'companion_trial_start',{ids});const run=trial.account.companionTrialProgress!.season.activeRun!;
rejects(()=>command(trial,'companion_level',{id:ids[0]}),'active team cannot level');rejects(()=>command(trial,'companion_trial_start',{ids}),'only one active trial');
trial=parseSaveBackup(createSaveBackup(trial));ok(trial.account.companionTrialProgress!.season.activeRun!.runId===run.runId,'active run survives reload');
trial=command(trial,'companion_trial_floor',{id:run.runId,floor:1});ok(trial.account.companionLastBattle!.won,'actual combat resolves first floor');ok(trial.account.companionTrialProgress!.season.firstClearFloors.includes(1),'first clear recorded');
rejects(()=>command(trial,'companion_trial_floor',{id:run.runId,floor:1}),'same floor cannot settle twice');
const rolled=command(trial,'claim',undefined,Date.UTC(2026,9,1));ok(rolled.account.companionTrialProgress!.season.currentSeasonHighestFloor===0&&!rolled.account.companionTrialProgress!.season.activeRun,'UTC month resets Trial');ok(rolled.account.combatCompanionProgress!.UNIT_001.level===20,'month retains permanent progress');
let missionState=fixture();missionState.account.combatCompanionProgress!.UNIT_001.level=5;missionState.account.companionSanctuary!.expeditionPensLevel=1;
missionState=command(missionState,'companion_assignment_start',{id:'MISSION_SCOUT_2H',ids:['UNIT_001']});let assignment=missionState.account.companionAssignments![0];
rejects(()=>command(missionState,'companion_equip',{id:'UNIT_001'}),'assigned companion cannot equip');rejects(()=>command(missionState,'companion_assignment_claim',{id:assignment.assignmentId}),'early claim rejected');
missionState=parseSaveBackup(createSaveBackup(missionState));ok(missionState.account.companionAssignments![0].seed===assignment.seed,'mission seed retained');
const finish=Date.parse(assignment.endsAt);missionState=command(missionState,'companion_assignment_claim',{id:assignment.assignmentId},finish);ok(missionState.account.companionAssignments![0].status==='claimed','completed assignment paid');
rejects(()=>command(missionState,'companion_assignment_claim',{id:assignment.assignmentId},finish),'duplicate assignment claim rejected');
for(const payload of [{type:'companion_level',args:{id:'UNIT_001',gold:0}},{type:'companion_trial_floor',args:{id:'x',floor:1,victory:true}},{type:'companion_unlock',args:{id:'UNIT_024'}}])rejects(()=>validateGameCommand(payload),'forged reward authority blocked');
let capped=fixture();capped.account.companionSanctuary={...capped.account.companionSanctuary!,trainingGroundLevel:1,essenceBasinLevel:1,lastTrainingClaimAtMs:0,lastEssenceClaimAtMs:0};
capped=claimSanctuaryTraining(capped,now);capped=claimSanctuaryEssence(capped,now);
ok(JSON.stringify(claimSanctuaryTraining(capped,now))===JSON.stringify(capped),'training offline cap cannot be repeatedly harvested');
ok(JSON.stringify(claimSanctuaryEssence(capped,now))===JSON.stringify(capped),'basin offline cap cannot be repeatedly harvested');
ok(fixture().account.companionPhase2Profile?.showcaseSlotsUnlocked===1,'new collection starts with one showcase slot');
const busy=command(command(fixture(),'companion_equip',{id:'UNIT_001'}),'companion_trial_start',{ids});
ok(companionCombatContribution(busy).outputMultiplier===1,'trial companion cannot assist simultaneous hunt');
const busyXp=busy.account.combatCompanionProgress!.UNIT_001.xp;
ok(recordCompanionActivity(busy,'combat','MOSS_RAT',10,now).account.combatCompanionProgress!.UNIT_001.xp===busyXp,'trial companion cannot gain simultaneous hunt XP');
let supplies=fixture();rejects(()=>command(supplies,'companion_supplies'),'supplies require pens');supplies.account.companionSanctuary!.expeditionPensLevel=1;
const suppliesGold=supplies.character!.gold;supplies=command(supplies,'companion_supplies');ok(supplies.account.companionMaterials!.SUPPLIES===5&&supplies.character!.gold===suppliesGold-250,'supply purchase pays configured cost');
supplies.character!.gold=249;rejects(()=>command(supplies,'companion_supplies'),'insufficient supply gold rejected');
let bondReward=fixture();rejects(()=>command(bondReward,'companion_bond_reward',{id:'UNIT_001'}),'bond reward needs real progression');bondReward.account.combatCompanionProgress!.UNIT_001=applyCompanionBondXp(bondReward.account.combatCompanionProgress!.UNIT_001,90);
const bondEssence=bondReward.account.companionEssence!;bondReward=command(bondReward,'companion_bond_reward',{id:'UNIT_001'});ok(bondReward.account.companionEssence===bondEssence+20,'bond milestone paid');
bondReward=parseSaveBackup(createSaveBackup(bondReward));rejects(()=>command(bondReward,'companion_bond_reward',{id:'UNIT_001'}),'bond reward cannot replay after reload');
let monthly=fixture();rejects(()=>command(monthly,'companion_monthly',{id:'NO_PRESTIGE_15'}),'monthly incomplete cannot claim');monthly.account.companionTrialProgress!.season.monthlyChallengeCompletion.NO_PRESTIGE_15=true;
monthly=command(monthly,'companion_monthly',{id:'NO_PRESTIGE_15'});ok(monthly.account.companionEssence===10120,'monthly reward paid');monthly=parseSaveBackup(createSaveBackup(monthly));rejects(()=>command(monthly,'companion_monthly',{id:'NO_PRESTIGE_15'}),'monthly claim survives reload');
rejects(()=>command(monthly,'companion_monthly',{id:'NO_PRESTIGE_15'},Date.UTC(2026,9,1)),'expired monthly completion cannot pay next season');
const recoveryTrial=parseSaveBackup(createSaveBackup(trial));ok(recoveryTrial.account.companionBattleReadyAtMs!>now,'battle recovery persists');rejects(()=>command(recoveryTrial,'companion_trial_floor',{id:run.runId,floor:2}),'consecutive rewards respect simulated combat duration');
let rematch=fixture();rejects(()=>command(rematch,'companion_boss_rematch'),'rematch requires first story clear');rematch.character!.level=25;rematch.defeatedBossIds=['FALLEN_KNIGHT'];
rematch=command(rematch,'companion_boss_rematch');ok(rematch.account.companionBossRematchReadyAtMs===now+86400000,'daily rematch attempt consumed on either outcome');ok(rematch.account.companionLastBattle?.title==='Fallen Knight rematch','rematch result is visible');
rematch=parseSaveBackup(createSaveBackup(rematch));rejects(()=>command(rematch,'companion_boss_rematch'),'rematch cannot replay after reload');command(rematch,'companion_boss_rematch',undefined,now+86400000);ok(true,'next UTC day permits next attempt');
const loadedQuest=parseSaveBackup(createSaveBackup({...quest,account:{...quest.account,unlockedCombatCompanionIds:[],combatCompanionProgress:{}}}));ok(loadedQuest.account.unlockedCombatCompanionIds?.includes('UNIT_001'),'legacy completed quest reconciles on load');
for(const payload of [{type:'companion_supplies',args:{gold:0}},{type:'companion_monthly',args:{id:'NO_PRESTIGE_15',complete:true}},{type:'companion_boss_rematch',args:{won:true}}])rejects(()=>validateGameCommand(payload),'new reward actions reject forged authority');
let trained=fixture();for(const id of ids)trained.account.combatCompanionProgress![id]={...trained.account.combatCompanionProgress![id],level:20,ascensionTier:2};
trained.account.companionSanctuary={...trained.account.companionSanctuary!,trainingGroundLevel:1,lastTrainingClaimAtMs:now-7*86400000};
trained=command(trained,'companion_training');ok(trained.account.companionEssence===10048,'max-level Sanctuary training converts XP using shared weekly cap');
ok(command(trained,'companion_training').account.companionEssence===10048,'training conversion cannot be repeatedly claimed');
const bondBase=command(fixture(),'companion_equip',{id:'UNIT_001'}),bondBoost=structuredClone(bondBase);bondBoost.account.companionSanctuary!.bondHallLevel=3;
ok(recordCompanionActivity(bondBoost,'combat','MOSS_RAT',100,now).account.combatCompanionProgress!.UNIT_001.bondXp===460,'Bond Hall applies exactly once to hunting');
console.log(`PASS companion integration: ${checks} checks`);
