import {createCharacter,newGame} from '../src/core/game';
import {weeklyOrderCandidatesFromCurrentContent} from '../src/core/launch-readiness-v47';
import {applyTrustedLongTermProgression,reconcileWeeklyOrderRollover,weeklyOrderBoardForState} from '../src/core/long-term-progression-runtime';
import {applyWeeklyOrderProgress,generateWeeklyOrders} from '../src/core/weekly-orders-v41';
import {weeklyOrderDestination,weeklyOrderGoal,weeklyOrderIdleRule,weeklyOrderQueueActivity} from '../src/core/weekly-order-integrations-v41';
import {contractBoardSummary} from '../src/core/contract-board-summary';
import type {GameState} from '../src/core/types';

function ok(value:unknown,message:string){if(!value)throw new Error(message)}
const now=Date.UTC(2026,8,21,12,0,0),accountId='contract-board-test';
let state=createCharacter(newGame(now),'WAYFINDER','Contract Tester');
const candidates=weeklyOrderCandidatesFromCurrentContent(state);
ok(candidates.some(row=>row.kind==='hunt'),'Contract Board needs Hunt Order candidates');
ok(candidates.some(row=>row.kind==='profession'),'Contract Board needs Work Order candidates');
const postStory={...state,character:{...state.character!,level:25},defeatedBossIds:['FALLEN_KNIGHT'],currentRegionId:'KINGS_ROAD'};
const postStoryCandidates=weeklyOrderCandidatesFromCurrentContent(postStory),bossBountyCandidate=postStoryCandidates.find(row=>row.kind==='hunt'&&row.boss&&row.monsterId==='FALLEN_KNIGHT');
ok(!!bossBountyCandidate&&bossBountyCandidate.reward?.label==='Oathglass Bounty Cache','Defeating the story boss should unlock the weekly Contract Board boss bounty');
const regionalCandidates=candidates.filter(row=>row.kind==='regional');
ok(regionalCandidates.length>0&&regionalCandidates.every(row=>row.regionId),'Contract Board needs real Regional Problem candidates');
ok(regionalCandidates.length>=2&&regionalCandidates.every(row=>row.brief&&row.brief.length>40),'Unlocked regions should offer multiple authored Regional Problem scenarios');
ok(new Set(regionalCandidates.map(row=>row.title)).size===regionalCandidates.length,'Regional Problem scenario titles must remain distinct');
ok(!candidates.some(row=>row.kind==='threat'),'Threat Bounties should not appear before Challenge Hunts are mastered');
let mastered={...state,character:{...state.character!,monsterMasteryPoints:{MOSS_RAT:500}}};const masteredCandidates=weeklyOrderCandidatesFromCurrentContent(mastered),threatCandidates=masteredCandidates.filter(row=>row.kind==='threat');ok(threatCandidates.length===3,'Mastery 20 Moss Rat should expose all three Threat Bounty tiers');

const generated=generateWeeklyOrders(accountId,now,candidates);
const bossBoard=generateWeeklyOrders(accountId+'-boss',now,postStoryCandidates),bossOrder=bossBoard.orders.find(row=>row.kind==='hunt'&&row.targetId==='FALLEN_KNIGHT');
ok(!!bossOrder&&bossOrder.target===1,'Fallen Knight Contract Board bounty should require exactly one rewarded weekly victory');
ok(weeklyOrderQueueActivity(bossOrder!)===undefined,'Boss bounty must remain a manual boss action rather than entering the idle hunt queue');
ok(weeklyOrderDestination(bossOrder!).button==='Open weekly boss','Boss bounty should deep-link to the weekly boss encounter');
ok(generated.orders.filter(row=>row.kind==='hunt').length===Math.min(2,candidates.filter(row=>row.kind==='hunt'&&row.available&&row.source.available).length),'default board should fill available Hunt Order slots');
ok(generated.orders.filter(row=>row.kind==='profession').length===Math.min(2,candidates.filter(row=>row.kind==='profession'&&row.available&&row.source.available).length),'default board should fill available Work Order slots');
ok(generated.orders.filter(row=>row.kind==='regional').length===1,'default board should have one Regional Problem');
const huntOrder=generated.orders.find(row=>row.kind==='hunt')!,workOrder=generated.orders.find(row=>row.kind==='profession')!;
const huntDestination=weeklyOrderDestination(huntOrder),workDestination=weeklyOrderDestination(workOrder),regionalDestination=weeklyOrderDestination(generated.orders.find(row=>row.kind==='regional')!);
ok(huntDestination.kind==='combat'&&huntDestination.monsterId===huntOrder.targetId,'Hunt Order should deep-link to its exact monster');
ok(workDestination.kind==='skills'&&(workDestination.actionId===workOrder.targetId||workDestination.recipeId===workOrder.targetId),'Work Order should deep-link to its exact activity or recipe');
ok(regionalDestination.kind==='world'&&regionalDestination.regionId===generated.orders.find(row=>row.kind==='regional')!.regionId,'Regional Problem should deep-link to its exact region');
const huntQueue=weeklyOrderQueueActivity(huntOrder);ok(huntQueue?.kind==='combat'&&huntQueue.targetId===huntOrder.targetId,'Hunt Order should be directly queueable');
const pinnedGoal=weeklyOrderGoal(huntOrder,state.character!.id,now);ok(pinnedGoal.kind==='weekly_order'&&pinnedGoal.orderId===huntOrder.id&&pinnedGoal.targetProgress===huntOrder.target,'Contract Board pin should track the exact weekly job target');
const stopRule=weeklyOrderIdleRule(huntOrder,state.character!.id);ok(stopRule.conditions.length===1&&stopRule.conditions[0].kind==='weekly_order_progress'&&stopRule.conditions[0].targetId===huntOrder.id&&stopRule.conditions[0].value===huntOrder.target,'Contract Board completion stop should use the exact weekly-order target');ok(stopRule.stopIfOutOfFood&&stopRule.stopIfRewardsWouldOverflow&&stopRule.finishCurrentCycle,'Contract completion stop must preserve safety and finish the current cycle');
const generatedRegional=generated.orders.find(row=>row.kind==='regional');ok(!!generatedRegional?.brief&&generatedRegional.reward.label.includes('Relief Cache'),'Generated Regional Problem should preserve authored brief and regional reward identity');
const masteredBoard=generateWeeklyOrders(accountId+'-mastered',now,masteredCandidates),threat=masteredBoard.orders.find(row=>row.kind==='threat');ok(!!threat&&!!threat.challengeId&&threat.reward.label.includes('Bounty Cache'),'Mastered board should generate one tier-specific Threat Bounty');
const threatDestination=weeklyOrderDestination(threat!),threatQueue=weeklyOrderQueueActivity(threat!);ok(threatDestination.kind==='combat'&&threatDestination.monsterId===threat!.targetId.split(':')[0],'Threat Bounty should open its exact monster');ok(threatQueue?.kind==='combat'&&threatQueue.combatChallengeId===threat!.challengeId,'Threat Bounty queue must preserve its exact Challenge Hunt tier');

const staleOrder=generated.orders[0],staleGoal=weeklyOrderGoal(staleOrder,state.character!.id,now),generatedStop=weeklyOrderIdleRule(staleOrder,state.character!.id);
const mixedRule={id:'mixed-weekly-rule',characterId:state.character!.id,name:'Mixed safety rule',conditions:[{id:'old-week',kind:'weekly_order_progress' as const,targetId:staleOrder.id,value:staleOrder.target,enabled:true},{id:'duration',kind:'duration_seconds' as const,value:3600,enabled:true}],stopIfOutOfFood:true,stopIfRewardsWouldOverflow:true,finishCurrentCycle:true};
const pendingReceipt={claimKey:'old-week-reward',rewardRef:'weekly_order_hunt_standard',label:'Old reward',weekKey:generated.weekKey,orderId:staleOrder.id};
const rolloverInput={...state,character:{...state.character!,progressionGoals:[staleGoal],idleRulesV40:[generatedStop,mixedRule],activeIdleRuleIdV40:generatedStop.id},account:{...state.account,longTermAccountScopeId:accountId,weeklyOrders:structuredClone(generated),weeklyOrderPendingRewards:[pendingReceipt]}};
const rollover=reconcileWeeklyOrderRollover(rolloverInput,now+7*86400_000);
ok(rollover.changed&&rollover.previousWeekKey===generated.weekKey&&rollover.weekKey!==generated.weekKey,'Monday rollover should replace the expired Contract Board');
ok(rollover.removedGoals===1&&rollover.removedRules===1&&rollover.removedConditions===2,'Rollover should report stale weekly goal, generated rule and condition cleanup');
ok(!(rollover.state.character?.progressionGoals??[]).some(goal=>goal.kind==='weekly_order'),'Expired Contract Board goals should be removed');
ok(!rollover.state.character?.idleRulesV40?.some(rule=>rule.id===generatedStop.id)&&!rollover.state.character?.activeIdleRuleIdV40,'Expired generated Contract stop rule should be removed and deactivated');
const preservedMixed=rollover.state.character?.idleRulesV40?.find(rule=>rule.id===mixedRule.id);ok(preservedMixed?.conditions.length===1&&preservedMixed.conditions[0].kind==='duration_seconds','Custom Idle Rules should keep unrelated conditions when stale weekly conditions are stripped');
ok(rollover.state.account.weeklyOrderPendingRewards?.[0]?.claimKey===pendingReceipt.claimKey,'Weekly rollover must preserve pending reward receipts from prior weeks');

const summaryState={...state,account:{...state.account,longTermAccountScopeId:accountId,weeklyOrders:generated}};
const initialSummary=contractBoardSummary(summaryState,now);
ok(initialSummary.total===generated.orders.length&&initialSummary.complete===0,'Home Contract Board summary should mirror the weekly board');
ok(!!initialSummary.nextOrder,'Home Contract Board summary should recommend an incomplete job');
if(initialSummary.nextOrder?.regionId)ok(initialSummary.nextOrder.regionId===summaryState.currentRegionId||!generated.orders.some(row=>row.progress<row.target&&row.regionId===summaryState.currentRegionId),'Home Contract Board summary should prefer an incomplete current-region job when available');
const completedBoard=structuredClone(generated);for(const row of completedBoard.orders)row.progress=row.target;completedBoard.completionClaimed=true;
const completedSummary=contractBoardSummary({...summaryState,account:{...summaryState.account,weeklyOrders:completedBoard,weeklyOrderPendingRewards:[{claimKey:'weekly-summary-test',rewardRef:'weekly_orders_completion',label:'Weekly Orders completion reward',weekKey:completedBoard.weekKey}]}},now);
ok(completedSummary.complete===completedSummary.total&&!completedSummary.nextOrder,'Completed Contract Board summary should have no next job');
ok(completedSummary.pendingRewards===1&&completedSummary.completionRewardQueued,'Home Contract Board summary should surface queued weekly rewards and completion state');

const regional=generated.orders.find(row=>row.kind==='regional')!;
const direct=applyWeeklyOrderProgress(generated,{eventId:'regional-progress',characterId:state.character!.id,kind:'regional',targetId:regional.targetId,amount:3,completedAtMs:now});
ok(direct.updated.length===1&&regional.progress===3,'Regional Problem progress should use the weekly order engine');

state={...state,account:{...state.account,longTermAccountScopeId:accountId,weeklyOrders:weeklyOrderBoardForState({...state,account:{...state.account,longTermAccountScopeId:accountId}},now)}};
const before=state.account.weeklyOrders!.orders.find(row=>row.kind==='regional');
ok(before?.targetId==='GREENFIELDS','level-one board should target the available Greenfields region');
const settled=applyTrustedLongTermProgression(state,[{kind:'combat',contentId:'MOSS_RAT',units:4,startedAtMs:now-60_000}],undefined,now,{accountId,eventId:'hunt-settlement'}).state;
const after=settled.account.weeklyOrders!.orders.find(row=>row.kind==='regional');
ok((after?.progress??0)>=4,'trusted Greenfields combat should advance the Greenfields Regional Problem');
mastered={...mastered,account:{...mastered.account,longTermAccountScopeId:accountId+'-mastered',weeklyOrders:masteredBoard}};const threatBefore=threat!.progress;let threatState=applyTrustedLongTermProgression(mastered,[{kind:'combat',contentId:'MOSS_RAT',units:4,startedAtMs:now-60_000}],undefined,now,{accountId:accountId+'-mastered',eventId:'normal-hunt'}).state;ok(threatState.account.weeklyOrders!.orders.find(row=>row.id===threat!.id)!.progress===threatBefore,'Normal hunt kills must not advance a Threat Bounty');const wrongTier=threat!.challengeId==='ferocious'?'hardened':'ferocious';threatState=applyTrustedLongTermProgression(threatState,[{kind:'combat',contentId:'MOSS_RAT',units:4,challengeId:wrongTier,startedAtMs:now-30_000}],undefined,now,{accountId:accountId+'-mastered',eventId:'wrong-tier'}).state;ok(threatState.account.weeklyOrders!.orders.find(row=>row.id===threat!.id)!.progress===threatBefore,'Wrong Challenge Hunt tier must not advance a Threat Bounty');threatState=applyTrustedLongTermProgression(threatState,[{kind:'combat',contentId:'MOSS_RAT',units:4,challengeId:threat!.challengeId,startedAtMs:now-10_000}],undefined,now,{accountId:accountId+'-mastered',eventId:'correct-tier'}).state;ok(threatState.account.weeklyOrders!.orders.find(row=>row.id===threat!.id)!.progress===Math.min(threat!.target,threatBefore+4),'Exact Challenge Hunt tier should advance its Threat Bounty');
let bossProgressState:GameState={...postStory,account:{...postStory.account,longTermAccountScopeId:accountId+'-boss',weeklyOrders:bossBoard}};
const storyOnly=applyTrustedLongTermProgression(bossProgressState,[{kind:'boss',contentId:'FALLEN_KNIGHT',units:1,weeklyEligible:false}],undefined,now,{accountId:accountId+'-boss',eventId:'story-boss'}).state;
ok(storyOnly.account.weeklyOrders!.orders.find(row=>row.targetId==='FALLEN_KNIGHT')!.progress===0,'One-time story clear must not complete the weekly boss bounty');
bossProgressState=applyTrustedLongTermProgression(storyOnly,[{kind:'boss',contentId:'FALLEN_KNIGHT',units:1}],undefined,now,{accountId:accountId+'-boss',eventId:'weekly-boss'}).state;
ok(bossProgressState.account.weeklyOrders!.orders.find(row=>row.targetId==='FALLEN_KNIGHT')!.progress===1,'Verified rewarded weekly boss clear must complete the Oathglass Bounty');
console.log('PASS: Contract Board Hunt Orders, Work Orders, Regional Problems and Threat Bounties validate');
