import {liveAffordances,parseCoopEncounterPreview,validateCoopRunView} from '../src/core/coop-presentation';
function equal(actual:unknown,expected:unknown,message='values differ'){if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error(message);}
equal(liveAffordances('qmode'),{ready:false,votes:false,chat:false});equal(liveAffordances('live'),{ready:true,votes:true,chat:true});
validateCoopRunView({runId:'q',mode:'qmode',phase:'awaiting_choice',syncedLevel:25,roleSlots:[{role:'tank',name:'T',echo:true,classId:'IRONWARDEN',companionId:'UNIT_002',currentHp:100,maximumHp:100},{role:'damage',name:'D1',echo:false,classId:'WAYFINDER',companionId:'UNIT_001',currentHp:90,maximumHp:100},{role:'damage',name:'D2',echo:true,classId:'RAVAGER',currentHp:88,maximumHp:100},{role:'support',name:'S',echo:true,classId:'DAWNKEEPER',companionId:'UNIT_008',currentHp:95,maximumHp:100}],options:[{nodeId:'a',title:'A',kind:'battle',risk:'steady',reward:'boon',encounterPreview:{archetypes:[{id:'assassin',label:'Assassin'}],mechanics:[{id:'focus',label:'Focus',description:'Can pressure a non-tank party member.'}],summary:'Assassin · Focus'}},{nodeId:'b',title:'B',kind:'camp',risk:'safe',reward:'recovery'},{nodeId:'c',title:'C',kind:'event',risk:'unknown',reward:'unknown'}]});
validateCoopRunView({runId:'boss',mode:'qmode',phase:'completed',syncedLevel:45,roleSlots:[{role:'tank',name:'T',echo:false},{role:'damage',name:'D1',echo:true},{role:'damage',name:'D2',echo:true},{role:'support',name:'S',echo:true}],options:[],bossMechanic:{label:'Champion Reception',summary:'Objective-aware duel.',tone:'mixed',telegraph:{bossName:'Aureon',phases:[{id:'p',label:'Pressure Break',hpPct:50,objectiveSensitive:false}],castAbilities:[{id:'nova',label:'Solar Nova',castMs:1450,cooldownMs:10800,interruptible:true,objectiveSensitive:false}],suppressedAbilities:[]}},bossRecap:{durationMs:12300,downs:0,phasesTriggered:['Pressure Break'],abilitiesCast:['Solar Nova']}});
let invalid='';try{validateCoopRunView({runId:'x',mode:'live',phase:'choice',syncedLevel:25,roleSlots:[{role:'tank',name:'T',echo:false},{role:'damage',name:'D',echo:false},{role:'damage',name:'D',echo:false},{role:'support',name:'S',echo:false}],options:[{nodeId:'a',title:'A',kind:'battle',risk:'x',reward:'x'},{nodeId:'b',title:'B',kind:'battle',risk:'x',reward:'x'}]});}catch(error){invalid=error instanceof Error?error.message:String(error);}equal(invalid,'insufficient_route_options');
let duplicate='';try{validateCoopRunView({runId:'x',mode:'live',phase:'choice',syncedLevel:25,roleSlots:[{role:'tank',name:'T',echo:false},{role:'damage',name:'D1',echo:false},{role:'damage',name:'D2',echo:false},{role:'support',name:'S',echo:false}],options:[{nodeId:'a',title:'A',kind:'battle',risk:'x',reward:'x'},{nodeId:'a',title:'B',kind:'camp',risk:'x',reward:'x'},{nodeId:'c',title:'C',kind:'event',risk:'x',reward:'x'}]});}catch(error){duplicate=error instanceof Error?error.message:String(error);}equal(duplicate,'invalid_route_options');
let duplicateClass='';try{validateCoopRunView({runId:'x',mode:'qmode',phase:'awaiting_choice',syncedLevel:25,roleSlots:[{role:'tank',name:'T',echo:false,classId:'IRONWARDEN'},{role:'damage',name:'D1',echo:false,classId:'WAYFINDER'},{role:'damage',name:'D2',echo:true,classId:'WAYFINDER'},{role:'support',name:'S',echo:true,classId:'DAWNKEEPER'}],options:[]});}catch(error){duplicateClass=error instanceof Error?error.message:String(error);}equal(duplicateClass,'duplicate_damage_class');
let invalidAssist='';try{validateCoopRunView({runId:'x',mode:'qmode',phase:'awaiting_choice',syncedLevel:25,roleSlots:[{role:'tank',name:'T',echo:false,companionId:' '},{role:'damage',name:'D1',echo:false},{role:'damage',name:'D2',echo:true},{role:'support',name:'S',echo:true}],options:[]});}catch(error){invalidAssist=error instanceof Error?error.message:String(error);}equal(invalidAssist,'invalid_companion_assist');
equal(parseCoopEncounterPreview({archetypes:[{id:'caster',label:'Caster'}],mechanics:[{id:'interrupt',label:'Interrupt',description:'Dangerous casts can be interrupted.'}],summary:'Caster · Interrupt'})?.summary,'Caster · Interrupt');
let badPreview='';try{parseCoopEncounterPreview({archetypes:[],mechanics:Array.from({length:5},(_,index)=>({id:'m'+index,label:'M',description:'D'})),summary:'Too many'});}catch(error){badPreview=error instanceof Error?error.message:String(error);}equal(badPreview,'invalid_encounter_preview');
console.log('coop presentation OK');
