import {createCharacter,newGame} from '../src/core/game';
import {LayerAsset,LayerRegistry,layerRegistryErrors,previewEquipment,resolveEquipmentLayers} from '../src/core/equipment-layers';
function ok(value:boolean,message:string){if(!value)throw new Error(message)}
const state=createCharacter(newGame(1000),'IRONWARDEN');
function layer(id:string,slot:LayerAsset['slot'],itemId?:string):LayerAsset{return {id,slot,itemId,classId:'IRONWARDEN',body:'male',front:`${id}-front`,back:`${id}-back`,width:128,height:160,approved:true}}
function registry(layers:LayerAsset[]):LayerRegistry{return {layers,availableSources:layers.flatMap(l=>[l.front,l.back])}}
const base=layer('base','body'),hair=layer('hair','hair'),weapon=layer('sword','weapon','basic_sword');
const initial=registry([weapon,hair,base]);
ok(layerRegistryErrors(initial).length===0,'Valid fixture accepted');
const front=resolveEquipmentLayers(state,initial,'front');
ok(front.ready&&front.layers[0].id==='base'&&front.layers[2].id==='sword','Stable front order');
ok(front.layers.every(l=>l.source.endsWith('-front')),'Front sources selected');
ok(resolveEquipmentLayers(state,initial,'back').layers.every(l=>l.source.endsWith('-back')),'Back sources selected');
const chest=layer('armor','chest','NOVICE_IRONWARDEN_CHEST');
const snapshot=JSON.stringify(state);
const tryOn=previewEquipment(state,chest.itemId!);
ok(JSON.stringify(state)===snapshot,'Try-on never mutates save');
ok(tryOn.character!.equipment.chest===chest.itemId,'Preview changes requested slot');
const missing=resolveEquipmentLayers(tryOn,initial,'front');
ok(!missing.ready&&missing.layers.length===0,'Missing gear refuses partial rendering');
ok(resolveEquipmentLayers(tryOn,registry([base,hair,weapon,chest]),'front').layers.length===4,'Added armor changes layer stack');
const helmet={...layer('helmet','helmet','NOVICE_IRONWARDEN_HELMET'),hidesHair:true};
const helmetState=previewEquipment(state,helmet.itemId!);
ok(!resolveEquipmentLayers(helmetState,registry([base,hair,weapon,helmet]),'front').layers.some(l=>l.id==='hair'),'Helmet hides hair only');
ok(resolveEquipmentLayers(helmetState,registry([base,weapon,helmet]),'front').ready,'Hidden hair does not require asset');
const cape=layer('cape','cape','OATHGLASS_CAPE');
const withCape=previewEquipment(tryOn,cape.itemId!);
const capeRegistry=registry([base,hair,weapon,chest,cape]);
const f=resolveEquipmentLayers(withCape,capeRegistry,'front').layers.map(l=>l.id),b=resolveEquipmentLayers(withCape,capeRegistry,'back').layers.map(l=>l.id);
ok(f.indexOf('cape')<f.indexOf('armor')&&b.indexOf('cape')>b.indexOf('armor'),'Cape ordering changes by view');
ok(!resolveEquipmentLayers(createCharacter(newGame(1),'IRONWARDEN','Test','female'),initial,'front').ready,'Never use wrong presentation assets');
ok(!resolveEquipmentLayers(createCharacter(newGame(1),'BASTION'),initial,'front').ready,'Never use wrong class assets');
ok(layerRegistryErrors(registry([base,{...base}])).length>0,'Duplicate bindings rejected');
ok(layerRegistryErrors(registry([{...base,width:120}])).length>0,'Canvas mismatch rejected');
ok(layerRegistryErrors(registry([{...base,approved:false}])).length>0,'Unapproved layer rejected');
ok(layerRegistryErrors({...initial,availableSources:[]}).length>0,'Missing image sources rejected');
ok(layerRegistryErrors(registry([{...weapon,slot:'chest'}])).length>0,'Wrong item-slot mapping rejected');
ok(layerRegistryErrors(registry([{...weapon,hidesHair:true}])).length>0,'Weapon cannot hide hair');
let rejected=false;try{previewEquipment(state,'NOVICE_BASTION_CHEST')}catch{rejected=true}ok(rejected,'Wrong-class try-on rejected');
ok(resolveEquipmentLayers(state,{layers:[],availableSources:[]},'front').layers.length===0,'Production empty registry cannot pretend to render');
console.log('PASS: layer validation, view ordering, hair rules, strict fallback and non-mutating try-on');
const sharedBase:LayerAsset={...base,id:'shared-base',classId:'shared'};
const sharedHair:LayerAsset={...hair,id:'shared-hair',classId:'shared'};
const sharedRegistry=registry([sharedBase,sharedHair,weapon]);
ok(resolveEquipmentLayers(state,sharedRegistry,'front').ready,'Shared anatomy works with class equipment');
const bastion=createCharacter(newGame(1),'BASTION');
const unarmedBastion={...bastion,character:{...bastion.character!,equipment:{}}};
ok(resolveEquipmentLayers(unarmedBastion,sharedRegistry,'back').ready,'Same shared body works for another class');
ok(!resolveEquipmentLayers(bastion,sharedRegistry,'front').ready,'Shared body does not allow wrong-class weapons');
ok(layerRegistryErrors(registry([{...weapon,classId:'shared'}])).length>0,'Gear cannot use shared anatomy binding');
ok(!resolveEquipmentLayers(createCharacter(newGame(1),'IRONWARDEN','Test','female'),sharedRegistry,'front').ready,'Shared male anatomy never substitutes for female');
ok(resolveEquipmentLayers(state,registry([sharedBase,sharedHair,base,weapon]),'front').layers[0].id==='base','Explicit class anatomy takes precedence during migration');
console.log('PASS: shared anatomy, presentation isolation and class-bound equipment');
