import {enqueueActivity} from '../src/core/activity-queue';
import {regionalCombatFixture} from '../src/core/regional-combat-fixtures';
import {startCombat,startNextQueuedActivity,effectiveStats,previewActivityReward} from '../src/core/game';
import {executeGameCommand} from '../src/core/game-commands';
import {guildPveBalance,guildPveView,type GuildPveEncounter} from '../src/core/guild-pve-encounters';
const check=(value:unknown,message:string)=>{if(!value)throw Error(message)};
const at=Date.UTC(2026,9,5);
let state=regionalCombatFixture({regionId:'IRONWOOD',regionName:'Ironwood Forest',monsterId:'THORNLING',level:10,tier:'T2',foodId:'ROASTED_ROOTSTREAM_TROUT'},'prepared');
state.character!.currentHp=effectiveStats(state).hp;state.inventory.stacks=[{itemId:'ROASTED_ROOTSTREAM_TROUT',quantity:2000}];state=startCombat(state,'THORNLING',at);
const short=executeGameCommand(state,{type:'claim'},at+1000);
check(short.reward?.kills===0,'Fixture should not complete a kill in one second');
check(short.reward?.combatEffort?.endsAtMs===at+1000,'Sub-kill claims retain actual combat effort');
const next=executeGameCommand(short.state,{type:'claim'},at+600000);
check(next.reward?.combatEffort?.startsAtMs===at+1000,'Consecutive effort intervals do not overlap');
check(next.reward?.combatEffort?.endsAtMs===at+600000,'Sustained combat earns elapsed time');
const starving={...state,inventory:{...state.inventory,stacks:[]}};
const exhausted=previewActivityReward(starving,at+8*3600000);
check(!!exhausted.stoppedReason,'No-food fixture must stop');
check(exhausted.combatEffort!.endsAtMs<at+8*3600000,'Time after injury earns no effort');
check(guildPveBalance(5).maxHp===75000&&guildPveBalance(8).maxHp===120000,'Small-guild brackets');
check(guildPveBalance(12).maxHp===180000&&guildPveBalance(20).maxHp===300000,'Full-guild brackets');
check(guildPveBalance(20,14).maxHp===600000&&guildPveBalance(20,14).personalCap===60000,'Event duration scales totals');
const row:GuildPveEncounter={...guildPveBalance(5),id:'test',kind:'weekly',name:'test',startsAt:new Date(at).toISOString(),endsAt:new Date(at+7*86400000).toISOString(),claimEndsAt:new Date(at+14*86400000).toISOString(),damage:75000,personalDamage:0,allowanceUsed:0,dailyUsed:0,contributors:3,claimed:[],eligible:true};
check(guildPveView(row,at+3600000).canContribute,'Original roster can qualify after defeat');
check(!guildPveView({...row,eligible:false},at+3600000).canContribute,'New arrivals wait for next encounter');
check(!guildPveView({...row,dailyUsed:6000},at+3600000).canContribute,'Daily allowance shown correctly');
let queued:typeof state={...state,activity:null};
queued=enqueueActivity(queued,{kind:'combat',targetId:'THORNLING',goal:{kind:'duration_seconds',value:60}});
queued=startNextQueuedActivity(queued,at);
const queueClaim=executeGameCommand(queued,{type:'claim'},at+180000);
const segments=queueClaim.reward?.activityResults??[];
check(segments.length>1,'Queue fixture should cross a goal boundary');
const intervals=segments.flatMap(segment=>segment.reward.combatEffort?[segment.reward.combatEffort]:[]);
check(intervals.reduce((sum,e)=>sum+e.endsAtMs-e.startsAtMs,0)===180000,'Queue effort counted once across handoff');
for(let i=1;i<intervals.length;i++)check(intervals[i].startsAtMs>=intervals[i-1].endsAtMs,'Queue intervals must not overlap');
console.log('PASS guild PvE combat effort, sub-kill collection, injury stop, brackets, event scaling and late eligibility');
