import {createCharacter,newGame,effectiveStats} from '../src/core/game';
import {visibleStacks,transferAmount,transferError,recoveryAmount} from '../src/core/inventory-view';
function ok(value:boolean,message:string){if(!value)throw new Error(message)}
const state=createCharacter(newGame(1000),'IRONWARDEN');
const stacks=[{itemId:'COPPER_ORE',quantity:12},{itemId:'TRAVEL_RATION',quantity:3},{itemId:'EMBER_SHARD',quantity:2},{itemId:'FALLEN_KNIGHT_SIGIL',quantity:1}];
const original=JSON.stringify(stacks);
ok(visibleStacks(stacks,' copper ','all','name').length===1,'Search trims and ignores case');
ok(visibleStacks(stacks,'','food','name')[0].itemId==='TRAVEL_RATION','Food filter');
ok(visibleStacks(stacks,'','gear','name').length===0,'Empty category');
ok(visibleStacks(stacks,'','gem','name')[0].itemId==='EMBER_SHARD','Gem filter');
ok(visibleStacks(stacks,'','quest','name')[0].itemId==='FALLEN_KNIGHT_SIGIL','Quest filter');
ok(visibleStacks(stacks,'','all','quantity')[0].quantity===12,'Descending quantity');
ok(JSON.stringify(stacks)===original,'Sorting does not mutate save stacks');
ok(transferAmount(3,10)===3,'Quantity clamps to owned count');
ok(transferAmount(25,'all')===25,'All transfer');
ok(transferAmount(25,1)===1,'Single transfer');
ok(recoveryAmount(state,'TRAVEL_RATION')===0,'No healing at full HP');
ok(recoveryAmount({...state,character:{...state.character!,currentHp:effectiveStats(state).hp-2}},'TRAVEL_RATION')===2,'Healing clamps to missing HP');
ok(transferError(state,'TRAVEL_RATION',10,'inventory')==='','Valid transfer');
ok(!!transferError({...state,bank:{stacks:[],capacity:0}},'TRAVEL_RATION',1,'inventory'),'Full destination rejected');
ok(!!transferError(state,'TRAVEL_RATION',100,'inventory'),'Insufficient quantity rejected');
ok(!!transferError(state,'TRAVEL_RATION',1,'bank'),'Empty bank cannot withdraw');
console.log('PASS: inventory search, filters, sorting, transfer preflight and healing previews');
