import {createCharacter,newGame,effectiveStats,salvageItem,sellItem} from '../src/core/game';
import {acknowledgeAllInventoryItems,acknowledgeInventoryItem,inventoryFavoriteIds,inventoryNewItemIds,recoveryAmount,storageCapacityStatus,toggleInventoryFavorite,transferAmount,transferError,visibleStacks} from '../src/core/inventory-view';
import {validateGameCommand,validateGameSettings} from '../src/core/game-commands';
import {bulkSalvageSelected,bulkSelectionSummary,bulkSellSelected,bulkTransferSelected} from '../src/core/inventory-bulk';
import {normalizeSave} from '../src/core/save-normalization';
function ok(value:boolean,message:string){if(!value)throw new Error(message)}
const state=createCharacter(newGame(1000),'IRONWARDEN');
const stacks=[{itemId:'COPPER_ORE',quantity:12},{itemId:'TRAVEL_RATION',quantity:3},{itemId:'EMBER_SHARD',quantity:2},{itemId:'FALLEN_KNIGHT_SIGIL',quantity:1}];
const original=JSON.stringify(stacks);
ok(visibleStacks(stacks,' copper ','all','name').length===1,'Search trims and ignores case');
ok(visibleStacks(stacks,'','food','name')[0].itemId==='TRAVEL_RATION','Food filter');
ok(visibleStacks(stacks,'','gear','name').length===0,'Empty category');
ok(visibleStacks(stacks,'','gem','name')[0].itemId==='EMBER_SHARD','Gem filter');
ok(visibleStacks(stacks,'','quest','name')[0].itemId==='FALLEN_KNIGHT_SIGIL','Quest filter');
ok(visibleStacks(stacks,'','all','quantity')[0].quantity===12,'Descending quantity');
ok(state.settings.seenItemIds?.includes('TRAVEL_RATION')===true,'Starter ration begins acknowledged');
let newItemState={...state,inventory:{...state.inventory,stacks:[...state.inventory.stacks,{itemId:'COPPER_ORE',quantity:2},{itemId:'EMBER_SHARD',quantity:1}]}};
ok(inventoryNewItemIds(newItemState).includes('COPPER_ORE')&&inventoryNewItemIds(newItemState).includes('EMBER_SHARD'),'First-time stored item types are marked new');
ok(visibleStacks(stacks,'','new','name',[],['EMBER_SHARD'])[0].itemId==='EMBER_SHARD','New item filter');
ok(visibleStacks(stacks,'','all','new',[],['EMBER_SHARD'])[0].itemId==='EMBER_SHARD','New-first sort');
newItemState=acknowledgeInventoryItem(newItemState,'COPPER_ORE');
ok(!inventoryNewItemIds(newItemState).includes('COPPER_ORE')&&inventoryNewItemIds(newItemState).includes('EMBER_SHARD'),'Acknowledging one item clears only that item type');
newItemState=acknowledgeAllInventoryItems(newItemState);
ok(inventoryNewItemIds(newItemState).length===0,'Mark all seen clears current Inventory and Bank new items');
const legacySave:any=JSON.parse(JSON.stringify({...state,inventory:{...state.inventory,stacks:[...state.inventory.stacks,{itemId:'COPPER_ORE',quantity:4}]}}));delete legacySave.settings.seenItemIds;
const normalizedLegacy=normalizeSave(legacySave);
ok(!!normalizedLegacy.settings.seenItemIds?.includes('TRAVEL_RATION')&&!!normalizedLegacy.settings.seenItemIds?.includes('COPPER_ORE'),'Existing old-save storage is migrated as already seen');
const postMigrationDrop={...normalizedLegacy,inventory:{...normalizedLegacy.inventory,stacks:[...normalizedLegacy.inventory.stacks,{itemId:'EMBER_SHARD',quantity:1}]}};
ok(inventoryNewItemIds(postMigrationDrop).length===1&&inventoryNewItemIds(postMigrationDrop)[0]==='EMBER_SHARD','Items obtained after migration still become NEW');
let favoriteState=toggleInventoryFavorite(state,'TRAVEL_RATION');
ok(inventoryFavoriteIds(favoriteState).includes('TRAVEL_RATION'),'Favorite persists in settings');
ok(visibleStacks(stacks,'','favorites','name',inventoryFavoriteIds(favoriteState))[0].itemId==='TRAVEL_RATION','Favorites filter');
ok(visibleStacks(stacks,'','all','favorite',inventoryFavoriteIds(favoriteState))[0].itemId==='TRAVEL_RATION','Favorites-first sort');
favoriteState=toggleInventoryFavorite(favoriteState,'TRAVEL_RATION');
ok(!inventoryFavoriteIds(favoriteState).includes('TRAVEL_RATION'),'Favorite toggles off cleanly');
const validatedSettings=validateGameSettings({...state.settings,favoriteItemIds:['TRAVEL_RATION','TRAVEL_RATION']});
ok(validatedSettings.favoriteItemIds?.length===1&&validatedSettings.favoriteItemIds[0]==='TRAVEL_RATION','Settings validator deduplicates favorites');
const validatedSeen=validateGameSettings({...state.settings,seenItemIds:['COPPER_ORE','COPPER_ORE']});
ok(validatedSeen.seenItemIds?.length===1&&validatedSeen.seenItemIds[0]==='COPPER_ORE','Settings validator deduplicates seen item history');
const nearCapacity=storageCapacityStatus(Array.from({length:9},(_,index)=>({itemId:'STACK_'+index,quantity:1})),10);
ok(nearCapacity.level==='near'&&nearCapacity.free===1&&nearCapacity.percent===90,'Near-full storage status');
const fullCapacity=storageCapacityStatus(Array.from({length:10},(_,index)=>({itemId:'STACK_'+index,quantity:1})),10);
ok(fullCapacity.level==='full'&&fullCapacity.free===0,'Full storage status');
const favoriteProtected={...state,settings:{...state.settings,favoriteItemIds:['WORN_BLADE']},inventory:{...state.inventory,stacks:[{itemId:'WORN_BLADE',quantity:1}]}};
let favoriteSellBlocked=false;try{sellItem(favoriteProtected,'WORN_BLADE')}catch(error){favoriteSellBlocked=error instanceof Error&&error.message.includes('Favorite item is protected')}
ok(favoriteSellBlocked,'Favorite items cannot be sold through core logic');
let favoriteSalvageBlocked=false;try{salvageItem(favoriteProtected,'WORN_BLADE')}catch(error){favoriteSalvageBlocked=error instanceof Error&&error.message.includes('Favorite item is protected')}
ok(favoriteSalvageBlocked,'Favorite items cannot be salvaged through core logic');
const bulkBase={...state,inventory:{...state.inventory,stacks:[{itemId:'TRAVEL_RATION',quantity:20},{itemId:'COPPER_ORE',quantity:4},{itemId:'WORN_BLADE',quantity:1},{itemId:'HOLY_WATER',quantity:2}]},bank:{stacks:[],capacity:10}};
const bulkIds=['TRAVEL_RATION','COPPER_ORE','WORN_BLADE','HOLY_WATER'];
const bulkSummary=bulkSelectionSummary(bulkBase,bulkIds,'inventory');
ok(bulkSummary.selectedStackCount===4&&bulkSummary.transferableStackCount===3&&bulkSummary.transferProtectedCount===1,'Bulk transfer keeps selected auto-eat food safe');
ok(bulkSummary.sellableStackCount===2&&bulkSummary.sellGold===55,'Bulk sell includes only eligible stack value');
const movedBulk=bulkTransferSelected(bulkBase,bulkIds,'inventory');
ok(movedBulk.inventory.stacks.length===1&&movedBulk.inventory.stacks[0].itemId==='TRAVEL_RATION','Bulk deposit leaves protected auto-eat stack carried');
ok(movedBulk.bank.stacks.some(stack=>stack.itemId==='COPPER_ORE')&&movedBulk.bank.stacks.some(stack=>stack.itemId==='WORN_BLADE'),'Bulk deposit moves eligible full stacks');
const tooSmall={...bulkBase,bank:{stacks:[],capacity:1}},tooSmallBefore=JSON.stringify(tooSmall);
let atomicTransferBlocked=false;try{bulkTransferSelected(tooSmall,['COPPER_ORE','WORN_BLADE'],'inventory')}catch(error){atomicTransferBlocked=error instanceof Error&&error.message.includes('Bank is full')}
ok(atomicTransferBlocked&&JSON.stringify(tooSmall)===tooSmallBefore,'Bulk transfer failure is atomic and does not partially mutate state');
const bulkFavorite={...bulkBase,settings:{...bulkBase.settings,favoriteItemIds:['WORN_BLADE']}};
const soldBulk=bulkSellSelected(bulkFavorite,bulkIds);
ok(soldBulk.character!.gold===bulkFavorite.character!.gold+20,'Bulk sell totals only eligible non-protected stacks');
ok(soldBulk.inventory.stacks.some(stack=>stack.itemId==='WORN_BLADE')&&soldBulk.inventory.stacks.some(stack=>stack.itemId==='TRAVEL_RATION'),'Bulk sell keeps favorite gear and auto-eat food');
const salvagedBulk=bulkSalvageSelected(bulkBase,['WORN_BLADE']);
ok(!salvagedBulk.inventory.stacks.some(stack=>stack.itemId==='WORN_BLADE')&&salvagedBulk.inventory.stacks.some(stack=>stack.itemId==='MOSS_FIBER'&&stack.quantity===2),'Bulk salvage processes eligible equipment');
ok(validateGameCommand({type:'bulk_transfer',args:{location:'inventory',ids:['COPPER_ORE']}}).type==='bulk_transfer','Bulk transfer command validates for online execution');
let invalidBulkCommand=false;try{validateGameCommand({type:'bulk_sell',args:{ids:Array.from({length:101},(_,index)=>'ITEM_'+index)}})}catch{invalidBulkCommand=true}
ok(invalidBulkCommand,'Bulk commands cap selections at 100 stacks');
ok(JSON.stringify(stacks)===original,'Sorting does not mutate save stacks');
ok(transferAmount(3,10)===3,'Quantity clamps to owned count');
ok(transferAmount(25,'all')===25,'All transfer');
ok(transferAmount(25,1)===1,'Single transfer');
ok(recoveryAmount(state,'TRAVEL_RATION')===0,'No healing at full HP');
ok(recoveryAmount({...state,character:{...state.character!,currentHp:effectiveStats(state).hp-2}},'TRAVEL_RATION')===2,'Healing clamps to missing HP');
ok(transferError(state,'TRAVEL_RATION',10,'inventory')==='','Valid transfer');
ok(!!transferError({...state,bank:{stacks:[],capacity:0}},'TRAVEL_RATION',1,'inventory'),'Full destination rejected');
ok(!!transferError(state,'TRAVEL_RATION',100,'inventory'),'Insufficient quantity rejected');
ok(!!transferError(state,'TRAVEL_RATION',1,'bank'),'Empty bank cannot withdraw');
console.log('PASS: inventory search, NEW tracking, favorites, safe bulk actions, capacity status, sorting, transfer preflight and healing previews');
