import {createCharacter,newGame,effectiveStats,salvageItem,sellItem} from '../src/core/game';
import {acknowledgeAllInventoryItems,acknowledgeInventoryItem,inventoryFavoriteIds,inventoryNewItemIds,recoveryAmount,storageCapacityStatus,toggleInventoryFavorite,transferAmount,transferError,visibleStacks} from '../src/core/inventory-view';
import {validateGameSettings} from '../src/core/game-commands';
function ok(value:boolean,message:string){if(!value)throw new Error(message)}
const state=createCharacter(newGame(1000),'IRONWARDEN');
const stacks=[{itemId:'COPPER_ORE',quantity:12},{itemId:'TRAVEL_RATION',quantity:3},{itemId:'EMBER_SHARD',quantity:2},{itemId:'FALLEN_KNIGHT_SIGIL',quantity:1}];
const original=JSON.stringify(stacks);
ok(visibleStacks(stacks,' copper ','all','name').length===1,'Search trims and ignores case');
ok(visibleStacks(stacks,'','food','name')[0].itemId==='TRAVEL_RATION','Food filter');
ok(visibleStacks(stacks,'','gear','name').length===0,'Empty category');
ok(visibleStacks(stacks,'','gem','name')[0].itemId==='EMBER_SHARD','Gem filter');
ok(visibleStacks(stacks,'','quest','name')[0].itemId==='FALLEN_KNIGHT_SIGIL','Quest filter');
ok(visibleStacks(stacks,'','all','quantity')[0].quantity===12,'Descending quantity');
ok(state.settings.seenItemIds?.includes('TRAVEL_RATION')===true,'Starter ration begins acknowledged');
let newItemState={...state,inventory:{...state.inventory,stacks:[...state.inventory.stacks,{itemId:'COPPER_ORE',quantity:2},{itemId:'EMBER_SHARD',quantity:1}]}};
ok(inventoryNewItemIds(newItemState).includes('COPPER_ORE')&&inventoryNewItemIds(newItemState).includes('EMBER_SHARD'),'First-time stored item types are marked new');
ok(visibleStacks(stacks,'','new','name',[],['EMBER_SHARD'])[0].itemId==='EMBER_SHARD','New item filter');
ok(visibleStacks(stacks,'','all','new',[],['EMBER_SHARD'])[0].itemId==='EMBER_SHARD','New-first sort');
newItemState=acknowledgeInventoryItem(newItemState,'COPPER_ORE');
ok(!inventoryNewItemIds(newItemState).includes('COPPER_ORE')&&inventoryNewItemIds(newItemState).includes('EMBER_SHARD'),'Acknowledging one item clears only that item type');
newItemState=acknowledgeAllInventoryItems(newItemState);
ok(inventoryNewItemIds(newItemState).length===0,'Mark all seen clears current Inventory and Bank new items');
let favoriteState=toggleInventoryFavorite(state,'TRAVEL_RATION');
ok(inventoryFavoriteIds(favoriteState).includes('TRAVEL_RATION'),'Favorite persists in settings');
ok(visibleStacks(stacks,'','favorites','name',inventoryFavoriteIds(favoriteState))[0].itemId==='TRAVEL_RATION','Favorites filter');
ok(visibleStacks(stacks,'','all','favorite',inventoryFavoriteIds(favoriteState))[0].itemId==='TRAVEL_RATION','Favorites-first sort');
favoriteState=toggleInventoryFavorite(favoriteState,'TRAVEL_RATION');
ok(!inventoryFavoriteIds(favoriteState).includes('TRAVEL_RATION'),'Favorite toggles off cleanly');
const validatedSettings=validateGameSettings({...state.settings,favoriteItemIds:['TRAVEL_RATION','TRAVEL_RATION']});
ok(validatedSettings.favoriteItemIds?.length===1&&validatedSettings.favoriteItemIds[0]==='TRAVEL_RATION','Settings validator deduplicates favorites');
const validatedSeen=validateGameSettings({...state.settings,seenItemIds:['COPPER_ORE','COPPER_ORE']});
ok(validatedSeen.seenItemIds?.length===1&&validatedSeen.seenItemIds[0]==='COPPER_ORE','Settings validator deduplicates seen item history');
const nearCapacity=storageCapacityStatus(Array.from({length:9},(_,index)=>({itemId:'STACK_'+index,quantity:1})),10);
ok(nearCapacity.level==='near'&&nearCapacity.free===1&&nearCapacity.percent===90,'Near-full storage status');
const fullCapacity=storageCapacityStatus(Array.from({length:10},(_,index)=>({itemId:'STACK_'+index,quantity:1})),10);
ok(fullCapacity.level==='full'&&fullCapacity.free===0,'Full storage status');
const favoriteProtected={...state,settings:{...state.settings,favoriteItemIds:['WORN_BLADE']},inventory:{...state.inventory,stacks:[{itemId:'WORN_BLADE',quantity:1}]}};
let favoriteSellBlocked=false;try{sellItem(favoriteProtected,'WORN_BLADE')}catch(error){favoriteSellBlocked=error instanceof Error&&error.message.includes('Favorite item is protected')}
ok(favoriteSellBlocked,'Favorite items cannot be sold through core logic');
let favoriteSalvageBlocked=false;try{salvageItem(favoriteProtected,'WORN_BLADE')}catch(error){favoriteSalvageBlocked=error instanceof Error&&error.message.includes('Favorite item is protected')}
ok(favoriteSalvageBlocked,'Favorite items cannot be salvaged through core logic');
ok(JSON.stringify(stacks)===original,'Sorting does not mutate save stacks');
ok(transferAmount(3,10)===3,'Quantity clamps to owned count');
ok(transferAmount(25,'all')===25,'All transfer');
ok(transferAmount(25,1)===1,'Single transfer');
ok(recoveryAmount(state,'TRAVEL_RATION')===0,'No healing at full HP');
ok(recoveryAmount({...state,character:{...state.character!,currentHp:effectiveStats(state).hp-2}},'TRAVEL_RATION')===2,'Healing clamps to missing HP');
ok(transferError(state,'TRAVEL_RATION',10,'inventory')==='','Valid transfer');
ok(!!transferError({...state,bank:{stacks:[],capacity:0}},'TRAVEL_RATION',1,'inventory'),'Full destination rejected');
ok(!!transferError(state,'TRAVEL_RATION',100,'inventory'),'Insufficient quantity rejected');
ok(!!transferError(state,'TRAVEL_RATION',1,'bank'),'Empty bank cannot withdraw');
console.log('PASS: inventory search, NEW tracking, favorites, capacity status, sorting, transfer preflight and healing previews');
