import {GEAR_RARITIES,rarityMeta,rarityNameColor,rollGearRarity} from '../src/core/item-rarity';
import {itemDef} from '../src/content/items';
if(GEAR_RARITIES.find(x=>x.id==='uncommon')!.chance!==.07||GEAR_RARITIES.find(x=>x.id==='mythic')!.chance!==.0005)throw new Error('Requested rarity odds missing');
if(itemDef('ASTER_IRON_CHEST').rarity!=='rare'||itemDef('OATHSTONE_WARDPLATE').rarity!=='epic')throw new Error('Gear rarity tiers missing');
if(rarityMeta('mythic').statMultiplier<=rarityMeta('legendary').statMultiplier)throw new Error('Mythic stats must exceed Legendary');
if(rarityNameColor('common',false,'#17202A')!=='#17202A')throw new Error('Common names should use theme text');
if(rarityNameColor('rare',true,'#17202A')!==rarityMeta('rare').color)throw new Error('Dark themes should use canonical rarity color');
if(rarityNameColor('rare',false,'#17202A')!==rarityMeta('rare').lightTextColor)throw new Error('Light theme rarity name color missing');
if(!['common','uncommon','rare','epic','legendary','mythic'].includes(rollGearRarity('stable-seed')))throw new Error('Rarity roll invalid');
console.log('PASS: rarity odds, borders, accessible name colors, stat multipliers and deterministic roll API');
