import {createCharacter,newGame,previewActivityReward,startCombat} from '../src/core/game';
import {liveEventDef} from '../src/content/live-events';
import {acceptEventContract,activeLiveEvent,applyEventDiscoveries,applyEventDrops,availableEventRepeatCaches,chooseEventProject,claimAllEventMilestones,claimEventCommunityMilestone,claimEventDailyGift,claimEventDiscovery,claimEventObjective,claimEventRepeatCache,claimEventReward,claimEventWeeklyObjective,contributeEventCurrency,eventCollectionJournal,eventCommunityMilestones,eventContractBoard,eventCurrencyBalance,eventDailyGift,eventDiscoveryBoard,eventLifecycle,eventShopOffers,eventObjectiveClaimed,eventOfferPurchaseCount,eventPrestigeBalance,eventProgress,eventRewardClaimed,eventWeeklyBoard,grantEventActivity,purchaseEventOffer,setLocalEventEnabled} from '../src/core/live-events';

function ok(condition:boolean,message:string){if(!condition)throw new Error(message);}
const t0=2_000_000;
let state=createCharacter(newGame(t0),'IRONWARDEN','EventTester');
state=startCombat(state,'MOSS_RAT',t0);
ok(!activeLiveEvent(state,t0),'Events must be inactive by default');
ok((previewActivityReward(state,t0+3_600_000).eventDrops?.length??0)===0,'Inactive events cannot add drops');
let scheduled={...state,account:{...state.account,liveEvent:{eventId:'EVT_ANNUAL_009_2026',enabled:true,startsAtMs:t0+86400_000,endsAtMs:t0+8*86400_000}}};
ok(eventLifecycle(scheduled,t0)?.phase==='upcoming','Scheduled events should be visible before they begin');

ok(liveEventDef('EVT_ANNUAL_009_2027')?.id==='EVT_ANNUAL_009_2027','A future annual season should reuse the matching content template under its own runtime ID');
ok(liveEventDef('EVT_ANNUAL_009_2027')?.name==='Harvestwake','Seasonal runtime IDs should preserve the event template identity');
let seasonalState:typeof state={...state,account:{...state.account,eventProgressById:{...(state.account.eventProgressById??{}),EVT_ANNUAL_009_2026:777},liveEvent:{eventId:'EVT_ANNUAL_009_2027',enabled:true,startsAtMs:t0-1000,endsAtMs:t0+86400_000}}};
ok(activeLiveEvent(seasonalState,t0)?.definition.id==='EVT_ANNUAL_009_2027','The active seasonal definition must keep the new year-specific ID');
ok(eventProgress(seasonalState,'EVT_ANNUAL_009_2027')===0,'A new annual season must start with separate progress');
seasonalState=grantEventActivity(seasonalState,'crafting',t0+1);
ok(eventProgress(seasonalState,'EVT_ANNUAL_009_2027')===30,'New-season activity should credit the new seasonal event ID');
ok(eventProgress(seasonalState,'EVT_ANNUAL_009_2026')===777,'New-season activity must not change the prior season progress');
state=setLocalEventEnabled(state,true,t0);
ok(activeLiveEvent(state,t0)?.definition.name==='Harvestwake','Developer switch should enable Harvestwake');
const gift=eventDailyGift(state,t0)!;const giftProgressBefore=eventProgress(state,'EVT_ANNUAL_009_2026');state=claimEventDailyGift(state,t0);
ok(eventProgress(state,'EVT_ANNUAL_009_2026')===giftProgressBefore+gift.gift.rewardCurrency,'Daily festival gift should grant reputation and spendable currency');
let duplicateGiftRejected=false;try{claimEventDailyGift(state,t0)}catch{duplicateGiftRejected=true}ok(duplicateGiftRejected,'Festival gift can only be claimed once per UTC day');
ok(eventDailyGift(state,t0+86400_000)?.claimed===false,'The next UTC day should offer a fresh festival gift');
state=applyEventDiscoveries(state,[{eventId:'EVT_ANNUAL_009_2026',discoveryId:'golden_field_feather',name:'Golden Field Feather',quantity:5}]);
ok(eventDiscoveryBoard(state,t0).find(entry=>entry.discovery.id==='golden_field_feather')?.ready===true,'Discovery fragments should accumulate to their collection target');
state=claimEventDiscovery(state,'golden_field_feather',t0);
ok(state.account.unlockedCosmeticPetIds?.includes('EVT_PET_012')===true,'Golden Field Feather discovery should grant Golden Sheafling');
let duplicateDiscoveryRejected=false;try{claimEventDiscovery(state,'golden_field_feather',t0)}catch{duplicateDiscoveryRejected=true}ok(duplicateDiscoveryRejected,'Discovery rewards cannot be claimed twice');
state=applyEventDrops(state,[{eventId:'EVT_ANNUAL_009_2026',currencyId:'HARVEST_MARK',name:'Harvest Marks',quantity:0,source:'combat',units:3,recordedAtMs:t0}]);
ok(state.account.eventActivityById?.EVT_ANNUAL_009_2026?.combat===3,'Activity must count even when its currency roll awards zero');
const preview=previewActivityReward(state,t0+3_600_000);
ok((preview.eventDrops?.[0]?.quantity??0)>0,'Active combat should produce event currency');
state=applyEventDrops(state,preview.eventDrops??[]);
const afterCombat=eventProgress(state,'EVT_ANNUAL_009_2026');
ok(afterCombat>0,'Collected event currency should persist as progress');

state=grantEventActivity(state,'crafting',t0+1);
ok(eventProgress(state,'EVT_ANNUAL_009_2026')===afterCombat+30,'Crafting should grant configured marks');
state=applyEventDrops(state,[{eventId:'EVT_ANNUAL_009_2026',currencyId:'HARVEST_MARK',name:'Harvest Marks',quantity:10000}]);
state=claimEventReward(state,'emote_harvest_cheer',t0+2);
ok(state.account.unlockedEmoteIds?.includes('emote_harvest_cheer')===true,'Claimed emote should enter the account collection');
ok(eventRewardClaimed(state,'EVT_ANNUAL_009_2026','emote_harvest_cheer'),'Claim receipt should persist');
let duplicateRejected=false;try{claimEventReward(state,'emote_harvest_cheer',t0+2)}catch{duplicateRejected=true}ok(duplicateRejected,'A milestone cannot be claimed twice');
state=claimEventReward(state,'skin_harvestwake_ironwarden',t0+2);
ok(state.account.unlockedEventSkinIds?.includes('skin_harvestwake_ironwarden')===true,'Class event skin should unlock permanently');
state=claimAllEventMilestones(state,t0+2);
ok(state.account.unlockedCosmeticPetIds?.includes('EVT_PET_011')===true,'Claim all should collect Pumpkin Piglet from the Harvestwake milestone');
const weekly=eventWeeklyBoard(state,t0+2)[0];state=applyEventDrops(state,[{eventId:'EVT_ANNUAL_009_2026',currencyId:'HARVEST_MARK',name:'Harvest Marks',quantity:0,source:weekly.objective.source,units:weekly.objective.required,recordedAtMs:t0+2}]);
state=claimEventWeeklyObjective(state,weekly.objective.id,t0+2);ok(eventWeeklyBoard(state,t0+2)[0].claimed,'Weekly challenge claim should be scoped to its UTC week');
const offered=eventContractBoard(state,t0+2)[0];state=acceptEventContract(state,offered.objective.id,t0+2);
ok(eventContractBoard(state,t0+2)[0].progress===0,'Contract progress must start from its acceptance baseline');
const prestigeBeforeContract=eventPrestigeBalance(state,'EVT_ANNUAL_009_2026');
const priorTotal=state.account.eventActivityById?.EVT_ANNUAL_009_2026?.[offered.objective.source]??0;
state={...state,account:{...state.account,eventActivityById:{...(state.account.eventActivityById??{}),EVT_ANNUAL_009_2026:{...(state.account.eventActivityById?.EVT_ANNUAL_009_2026??{}),[offered.objective.source]:priorTotal+offered.objective.required}}}};
state=claimEventObjective(state,offered.objective.id,t0+2);
ok(eventObjectiveClaimed(state,'EVT_ANNUAL_009_2026',offered.objective.id,t0+2),'Completed daily contract should persist its dated claim');
ok(eventPrestigeBalance(state,'EVT_ANNUAL_009_2026')===prestigeBeforeContract+offered.objective.rewardPrestige,'Contracts should award their configured prestige currency');
const remainingContracts=eventContractBoard(state,t0+2).slice(1);state=acceptEventContract(state,remainingContracts[0].objective.id,t0+2);
let thirdRejected=false;try{acceptEventContract(state,remainingContracts[1].objective.id,t0+2)}catch{thirdRejected=true}ok(thirdRejected,'Daily board must enforce its two-contract acceptance limit');
ok(eventContractBoard(state,t0+86400_000+2).every(contract=>!contract.accepted),'A new UTC day should provide fresh contract acceptance slots');
const progressBeforePurchase=eventProgress(state,'EVT_ANNUAL_009_2026');
const market=eventShopOffers(state,t0+2),prestigeOfferCount=market.filter(offer=>offer.currency==='prestige').length;ok(market.filter(offer=>offer.currency==='common').length===2,'Event Shop should show exactly two rotating common offers');ok(prestigeOfferCount===2,'Harvestwake should expose both prestige offers');const purchaseOffer=market.find(offer=>offer.currency==='common')!;
state=purchaseEventOffer(state,purchaseOffer.id,t0+2);
ok(eventOfferPurchaseCount(state,'EVT_ANNUAL_009_2026',purchaseOffer.id)===1,'Event Shop purchase limit should persist');
const cosmeticIds=[...(state.account.unlockedProfileBackgroundIds??[]),...(state.account.unlockedProfileBorderIds??[]),...(state.account.unlockedCosmeticPetIds??[])];ok(cosmeticIds.includes(purchaseOffer.reward.id),'Event Shop reward should enter the matching cosmetic collection');
ok(eventProgress(state,'EVT_ANNUAL_009_2026')===progressBeforePurchase,'Spending currency must not reduce reputation');
state={...state,account:{...state.account,eventPrestigeBalanceById:{...(state.account.eventPrestigeBalanceById??{}),EVT_ANNUAL_009_2026:8}}};
const guardianOffer=eventShopOffers(state,t0+2).find(offer=>offer.id==='pantry_harvest_guardian');ok(!!guardianOffer,'Harvest Guardian should be available from Harvestwake prestige stock');
state=purchaseEventOffer(state,'pantry_harvest_guardian',t0+2);
ok(state.account.unlockedCombatCompanionIds?.includes('EVT_UNIT_006')===true,'Event companion purchase should unlock the combat companion');
ok(!!state.account.combatCompanionProgress?.EVT_UNIT_006,'Event companion purchase should initialize companion progression');

let bonusState=chooseEventProject(state,'guild_pantry',t0+2);const bonusProgressBefore=eventProgress(bonusState,'EVT_ANNUAL_009_2026');bonusState=grantEventActivity(bonusState,'boss',t0+3);
ok(eventProgress(bonusState,'EVT_ANNUAL_009_2026')===bonusProgressBefore+300,'Guild Pantry should apply its 20% boss-currency bonus');
bonusState=applyEventDrops(bonusState,[{eventId:'EVT_ANNUAL_009_2026',currencyId:'HARVEST_MARK',name:'Harvest Marks',quantity:100}]);
const contributionBalance=eventCurrencyBalance(bonusState,'EVT_ANNUAL_009_2026');
bonusState=contributeEventCurrency(bonusState,100,t0+3);
ok(eventCurrencyBalance(bonusState,'EVT_ANNUAL_009_2026')===contributionBalance-100,'Harvestwake community contribution should spend Harvest Marks');
ok(bonusState.account.eventContributionById?.EVT_ANNUAL_009_2026===125,'Guild Pantry should turn 100 spent Marks into 125 verified contribution value');
state=chooseEventProject(state,'preserved_supplies',t0+2);
let choiceLocked=false;try{chooseEventProject(state,'guild_pantry',t0+2)}catch{choiceLocked=true}ok(choiceLocked,'Winter project choice should lock for the event');
state={...state,account:{...state.account,liveEvent:{eventId:'EVT_ANNUAL_009_2026',enabled:true,startsAtMs:t0-10*86400_000,endsAtMs:t0+3600_000},eventCommunityProgressById:{...(state.account.eventCommunityProgressById??{}),EVT_ANNUAL_009_2026:100}}};
ok(eventCommunityMilestones(state,t0+2).length===4,'Harvestwake should expose four shared Storehouse milestones');
ok(eventCommunityMilestones(state,t0+2).find(entry=>entry.milestone.percent===100)?.ready===true,'Verified 100% community progress should unlock the final Storehouse milestone');
ok(eventCollectionJournal(state,t0+2).some(entry=>entry.reward.id==='title_storehouse_builder'),'Community cosmetic should appear in the active Harvestwake collection journal');
state=claimEventCommunityMilestone(state,100,t0+2);
ok(state.account.unlockedTitleIds?.includes('title_storehouse_builder')===true,'Final Storehouse milestone should grant its permanent community title');
const cachesBeforeThreshold=availableEventRepeatCaches(state,'EVT_ANNUAL_009_2026');
const reputationBeforeThreshold=eventProgress(state,'EVT_ANNUAL_009_2026');
const nextCacheThreshold=10000+(Math.floor(Math.max(0,reputationBeforeThreshold-10000)/1000)+1)*1000;
state=applyEventDrops(state,[{eventId:'EVT_ANNUAL_009_2026',currencyId:'HARVEST_MARK',name:'Harvest Marks',quantity:nextCacheThreshold-reputationBeforeThreshold}]);
ok(availableEventRepeatCaches(state,'EVT_ANNUAL_009_2026')===cachesBeforeThreshold+1,'Post-cap reputation should unlock repeat caches every 1,000 points');
const prestigeBeforeCache=eventPrestigeBalance(state,'EVT_ANNUAL_009_2026');state=claimEventRepeatCache(state,t0+2);
ok(eventPrestigeBalance(state,'EVT_ANNUAL_009_2026')===prestigeBeforeCache+1,'Repeat cache should grant prestige currency');
const eventEnd=state.account.liveEvent!.endsAtMs,graceTime=eventEnd+60_000;
ok(eventLifecycle(state,graceTime)?.phase==='claiming','Ended events should enter their reward-claim grace period');
ok(!activeLiveEvent(state,graceTime),'Claim-period events must not generate new activity drops');
ok(eventShopOffers(state,graceTime).map(offer=>offer.id).join(',')===eventShopOffers(state,eventEnd-1).map(offer=>offer.id).join(','),'Event Shop stock should freeze to the final event-day rotation during grace');
let graceContributionRejected=false;try{contributeEventCurrency(state,100,graceTime)}catch{graceContributionRejected=true}ok(graceContributionRejected,'Community contributions remain unavailable during the claim period');
ok(eventLifecycle(state,eventEnd+8*86400_000)===null,'Event should archive after the seven-day claim period');
const explicitGraceEnd=eventEnd+2*86400_000;
state={...state,account:{...state.account,liveEvent:{...state.account.liveEvent!,graceEndsAtMs:explicitGraceEnd}}};
ok(eventLifecycle(state,explicitGraceEnd-1)?.phase==='claiming','Explicit server grace should keep claims open until its exact boundary');
ok(eventLifecycle(state,explicitGraceEnd)===null,'Explicit server grace should override the definition fallback boundary');
state=setLocalEventEnabled(state,false,t0+3);
ok(!activeLiveEvent(state,t0+3),'Developer switch should fully disable event drops and claims');
console.log(JSON.stringify({status:'PASS',afterCombat,finalProgress:eventProgress(state,'EVT_ANNUAL_009_2026')},null,2));
