import {createCharacter,newGame,offlineCapBreakdown,offlineCapSeconds,previewActivityReward} from '../src/core/game';
import {noviceItemId,noviceSetFor} from '../src/content/novice-sets';
let state=createCharacter(newGame(0),'BASTION','Tester');
if(offlineCapBreakdown(state).hours!==24)throw new Error('Fresh account must start with 24 hours');
state={...state,activity:{kind:'combat',targetId:'MOSS_RAT',startedAtMs:0,lastClaimAtMs:0}};
if(previewActivityReward(state,40*60*60*1000).elapsedSeconds!==24*60*60)throw new Error('Reward preview must use base cap');
state={...state,character:{...state.character!,craftedNoviceItemIds:noviceSetFor('BASTION').slots.map(slot=>noviceItemId('BASTION',slot))},account:{createdCharacterCount:3,guildMember:true,patronTier:'crown'},defeatedBossIds:['FALLEN_KNIGHT'],quests:state.quests.map(q=>q.questId==='QST_005'?{...q,status:'claimed'}:q)};
const full=offlineCapBreakdown(state);
if(full.hours!==36||offlineCapSeconds(state)!==36*60*60)throw new Error(`AFK upgrades must clamp to 36h, got ${full.hours}`);
console.log(`PASS: AFK reserve scales ${full.baseHours}h to ${full.hours}h and clamps at ${full.maxHours}h`);
