import {GATHERING,RECIPES} from '../src/content/skills';
import {MONSTERS} from '../src/content/monsters';
import {characterXpForNextLevel,skillXpForNextLevel} from '../src/core/progression';
import {migrateSave} from '../src/core/save-migrations';
import {newGame} from '../src/core/game';
if(characterXpForNextLevel(1)!==Math.floor((90*Math.pow(1,1.42)+35)*43.2))throw new Error('Character XP scaling missing');
if(skillXpForNextLevel(1)!==Math.floor((90*Math.pow(1,1.42)+35)*4.3))throw new Error('Skill XP scaling missing');
if(MONSTERS.find(m=>m.id==='MOSS_RAT')!.secondsPerKill!==14)throw new Error('Current combat action pacing missing');
if(GATHERING.find(g=>g.id==='COPPER_VEIN')!.seconds!==30)throw new Error('Gathering pacing missing');
if(RECIPES.find(r=>r.id==='SMITH_COPPER_BLADE')!.inputs.find(i=>i.itemId==='COPPER_INGOT')!.quantity!==44)throw new Error('Gear materials were not doubled');
const old={...newGame(0),version:5,account:undefined,settings:{numberMode:'abbreviated',reduceMotion:false,textScale:1,autoEatThresholdPct:40,stopCombatWhenOutOfFood:true}};
const migrated=migrateSave(old);
if(migrated.version!==6||migrated.settings.language!=='en'||migrated.account.createdCharacterCount!==1)throw new Error('v5 migration failed');
console.log('PASS: v6 pacing, requirements, language and account migration');
