import {createCharacter,newGame,claimQuest,refreshQuests} from '../src/core/game';
import {journalActionSummary,journalEntries,questDestination} from '../src/core/quest-journal';
import {QUESTS,QUEST_ACTS} from '../src/content/quests';
import {questPresentationMeta,questPresentationTier} from '../src/core/quest-presentation';
function ok(value:boolean,message:string){if(!value)throw new Error(message)}
const state=createCharacter(newGame(1000),'IRONWARDEN');
ok(journalEntries(state,'current','').length===1,'One current chapter initially');
ok(journalEntries(state,'locked','').length===14,'Remaining chapters locked');
ok(journalEntries(state,'all',' MOSS ').length===1,'Search descriptions, trim and ignore case');
ok(journalEntries(state,'all',' oathgate ').length===2,'Search includes authored quest locations');
ok(journalEntries(state,'all',' ferrymen ').length===1,'Search includes authored story text');
ok(journalEntries(state,'claimed','').length===0,'Empty completed filter');
const initialSummary=journalActionSummary(state);
ok(initialSummary.active===1&&initialSummary.ready===0&&initialSummary.locked===14&&initialSummary.claimed===0,'Journal action summary reflects the initial story state');
ok(questDestination(QUESTS[0]).zoneId==='GREENFIELDS','Rat quest navigates to region');
ok(questDestination(QUESTS[3]).tab==='Inventory','Equip quest destination');
ok(questDestination(QUESTS[6]).tab==='Skills','Gatherable item destination');
ok(questDestination(QUESTS[13]).zoneId==='KINGS_ROAD','Boss destination');
for(const def of QUESTS)ok(!!questDestination(def).label&&!!questDestination(def).hint,'Every quest has guidance');
for(const def of QUESTS)ok(def.act>=1&&def.act<=3&&!!def.location.trim()&&def.story.trim().length>=40,'Every quest has an act, location and substantive story beat');
ok(QUESTS.slice(0,5).every(def=>def.act===1)&&QUESTS.slice(5,10).every(def=>def.act===2)&&QUESTS.slice(10).every(def=>def.act===3),'Asterfall acts remain ordered 5 / 5 / 5');
ok(QUEST_ACTS[1].name==='Whispers in the Green'&&QUEST_ACTS[3].name==='The Broken Oath','Campaign act identity remains authored');
ok(questPresentationTier(QUESTS[0])==='standard'&&questPresentationTier(QUESTS[4])==='rare','Act I tier curve should build from standard to rare');
ok(questPresentationTier(QUESTS[9])==='epic'&&questPresentationTier(QUESTS[13])==='legendary'&&questPresentationTier(QUESTS[14])==='epic','Major campaign beats keep stronger presentation tiers');
ok(QUESTS.filter(def=>questPresentationTier(def)==='legendary').every(def=>def.kind==='boss'),'Legendary campaign presentation is reserved for boss-scale chapters');
const themeFixtures=[{accent:'#gold',accentSurface:'#gold-bg',special:'#violet',specialSurface:'#violet-bg',info:'#blue',infoSurface:'#blue-bg',good:'#green',goodSurface:'#green-bg',muted:'#muted',panel2:'#panel'} as any,{accent:'#bronze',accentSurface:'#cream',special:'#purple',specialSurface:'#lilac',info:'#navy',infoSurface:'#ice',good:'#forest',goodSurface:'#mint',muted:'#slate',panel2:'#ivory'} as any];
for(const theme of themeFixtures){for(const def of QUESTS){const meta=questPresentationMeta(def,theme);ok(!!meta.color&&!!meta.surface&&!!meta.label,'Every quest tier resolves theme-safe presentation metadata')}}
const completed=refreshQuests(state,'MOSS_RAT',5);
ok(journalEntries(completed,'current','')[0].remaining===0,'Ready quest has no remainder');
ok(journalActionSummary(completed).ready===1,'Journal action summary exposes reward-ready chapters');
const mixed={...state,quests:state.quests.map((quest,index)=>index===0?{...quest,status:'active' as const,progress:1}:index===1?{...quest,status:'complete' as const,progress:QUESTS[1].required}:quest)};
ok(journalEntries(mixed,'current','')[0].def.id==='QST_002','Current journal view prioritizes reward-ready chapters before merely active chapters');
const claimed=claimQuest(completed,'QST_001');
ok(journalEntries(claimed,'claimed','').length===1,'Claimed chapter archived');
ok(journalEntries(claimed,'current','')[0].def.id==='QST_002','Claim advances journal');
ok(journalEntries(claimed,'locked','')[0].previous===QUESTS[1].name,'Locked prerequisite uses source order');
const finished={...state,quests:state.quests.map(q=>({...q,status:'claimed' as const}))};
ok(journalEntries(finished,'current','').length===0,'Completed campaign has no current quests');
ok(journalEntries(finished,'claimed','').length===15,'All chapters remain browsable');
console.log('PASS: quest story acts, filters, search, destinations, claim advancement and finished campaign');
