import React from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {CrisisSummary} from '../core/shared-world-v19';
import {crisisStatusLabel,formatCompact,fraction} from '../core/shared-world-v19';

export function RegionalCrisisPanel({crisis,onViewRewards,onOpenRegion}:{crisis:CrisisSummary;onViewRewards?:()=>void;onOpenRegion?:()=>void}){
 const progress=fraction(crisis.creditedPoints,crisis.targetPoints);
 return <ScrollView contentContainerStyle={s.wrap}>
  <View style={s.hero}><View style={{flex:1}}><Text style={s.eyebrow}>REGIONAL CRISIS · {crisis.regionId.toUpperCase()}</Text><Text style={s.title}>{crisis.name}</Text><Text style={s.status}>{crisisStatusLabel(crisis)}</Text></View><View style={s.badge}><Text style={s.badgeText}>{Math.round(progress*100)}%</Text></View></View>
  <View style={s.panel}><View style={s.row}><Text style={s.section}>SERVER RESPONSE</Text><Text style={s.value}>{formatCompact(crisis.creditedPoints)} / {formatCompact(crisis.targetPoints)}</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.round(progress*100)}%`}]} /></View><Text style={s.copy}>Normal eligible activities in this region contribute automatically. Harder or longer actions earn proportionally more effort points.</Text></View>
  <View style={s.grid}><View style={s.stat}><Text style={s.statLabel}>YOUR IMPACT</Text><Text style={s.statValue}>{formatCompact(crisis.yourPoints)}</Text></View><View style={s.stat}><Text style={s.statLabel}>PARTY</Text><Text style={s.statValue}>{formatCompact(crisis.partyPoints||0)}</Text></View><View style={s.stat}><Text style={s.statLabel}>GUILD</Text><Text style={s.statValue}>{formatCompact(crisis.guildPoints||0)}</Text></View></View>
  <View style={s.panel}><Text style={s.section}>WHAT HELPS</Text><Text style={s.copy}>Continue normal Combat, Gathering, Processing, Crafting or other eligible regional activities. You do not need to queue into a special synchronized instance.</Text><View style={s.actions}><Pressable style={s.primary} onPress={onOpenRegion}><Text style={s.primaryText}>Open Region</Text></Pressable><Pressable style={s.secondary} onPress={onViewRewards}><Text style={s.secondaryText}>Milestones & Rewards</Text></Pressable></View></View>
 </ScrollView>
}
const s=StyleSheet.create({wrap:{padding:12,gap:10},hero:{flexDirection:'row',gap:12,backgroundColor:'#111a22',borderWidth:1,borderColor:'#485969',borderRadius:12,padding:14},eyebrow:{color:'#a3b6c4',fontSize:9,fontWeight:'900',letterSpacing:1},title:{color:'#f1dd9b',fontSize:22,fontWeight:'900'},status:{color:'#d6e1e7',fontSize:12,marginTop:4},badge:{width:62,height:62,borderRadius:12,borderWidth:1,borderColor:'#b4924e',backgroundColor:'#2a261b',alignItems:'center',justifyContent:'center'},badgeText:{color:'#f2d88c',fontSize:18,fontWeight:'900'},panel:{backgroundColor:'#101923',borderWidth:1,borderColor:'#334657',borderRadius:10,padding:12,gap:8},row:{flexDirection:'row',justifyContent:'space-between',gap:8},section:{color:'#c9b574',fontSize:10,fontWeight:'900',letterSpacing:.8},value:{color:'#e9eef1',fontSize:11,fontWeight:'900'},track:{height:10,borderRadius:5,backgroundColor:'#263541',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#b59a59'},copy:{color:'#9fb0bb',fontSize:11,lineHeight:16},grid:{flexDirection:'row',gap:7},stat:{flex:1,backgroundColor:'#15222c',borderWidth:1,borderColor:'#314757',borderRadius:9,padding:10},statLabel:{color:'#8298a7',fontSize:8,fontWeight:'900'},statValue:{color:'#edf1f3',fontSize:16,fontWeight:'900',marginTop:2},actions:{flexDirection:'row',gap:7,flexWrap:'wrap'},primary:{backgroundColor:'#8d7138',borderRadius:7,paddingVertical:9,paddingHorizontal:12},primaryText:{color:'#fff4cf',fontWeight:'900',fontSize:11},secondary:{backgroundColor:'#192a35',borderWidth:1,borderColor:'#3b5364',borderRadius:7,paddingVertical:9,paddingHorizontal:12},secondaryText:{color:'#d7e1e6',fontWeight:'900',fontSize:11}});
