import React from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import type {WorldBossSummary} from '../core/shared-world-v19';
import {bossAttemptsRemaining,formatCompact,fraction} from '../core/shared-world-v19';

export function WorldBossPanel({boss,onFight,onRewards,onLeaderboard}:{boss:WorldBossSummary;onFight?:()=>void;onRewards?:()=>void;onLeaderboard?:()=>void}){
 const hp=fraction(boss.remainingHp,boss.maxHp),remaining=bossAttemptsRemaining(boss),defeated=boss.state==='defeated'||boss.remainingHp<=0;
 return <ScrollView contentContainerStyle={s.wrap}>
  <View style={s.hero}><Text style={s.eyebrow}>WORLD BOSS · {boss.regionId.toUpperCase()}</Text><Text style={s.title}>{boss.name}</Text><Text style={s.phase}>{defeated?'DEFEATED':boss.phaseName}</Text><View style={s.bossPortrait}><Text style={s.silhouette}>◆</Text><Text style={s.portraitText}>BOSS ART / SPRITE</Text></View><View style={s.hpLine}><Text style={s.hpLabel}>GLOBAL HP</Text><Text style={s.hpValue}>{formatCompact(boss.remainingHp)} / {formatCompact(boss.maxHp)}</Text></View><View style={s.track}><View style={[s.fill,{width:`${Math.round(hp*100)}%`}]} /></View></View>
  <View style={s.grid}><View style={s.stat}><Text style={s.statLabel}>ATTEMPTS LEFT</Text><Text style={s.statValue}>{remaining} / {boss.dailyAttemptCap}</Text></View><View style={s.stat}><Text style={s.statLabel}>YOUR RAID IMPACT</Text><Text style={s.statValue}>{formatCompact(boss.yourRaidImpact)}</Text></View><View style={s.stat}><Text style={s.statLabel}>APPLIED DAMAGE</Text><Text style={s.statValue}>{formatCompact(boss.yourAppliedDamage)}</Text></View></View>
  <View style={s.panel}><Text style={s.section}>HOW IT WORKS</Text><Text style={s.copy}>Each attempt is your own short combat window. The server converts valid damage, mitigation, healing and combat utility into role-aware Raid Impact, then applies it to the shared boss HP. You never need all players online together.</Text><Text style={s.copy}>Score-bearing attempts are limited daily and cannot be purchased. If the boss dies early, the post-defeat Echo window still allows eligible late players to make a participation attempt.</Text></View>
  <View style={s.actions}><Pressable disabled={!remaining&&!defeated} onPress={onFight} style={[s.primary,(!remaining&&!defeated)&&s.disabled]}><Text style={s.primaryText}>{defeated?'Enter Echo Encounter':remaining?`Fight · ${remaining} left`:'Attempts Used'}</Text></Pressable><Pressable onPress={onRewards} style={s.secondary}><Text style={s.secondaryText}>Rewards</Text></Pressable><Pressable onPress={onLeaderboard} style={s.secondary}><Text style={s.secondaryText}>Prestige Ranks</Text></Pressable></View>
 </ScrollView>
}
const s=StyleSheet.create({wrap:{padding:12,gap:10},hero:{backgroundColor:'#111820',borderWidth:1,borderColor:'#584b45',borderRadius:12,padding:14},eyebrow:{color:'#b0a39b',fontSize:9,fontWeight:'900',letterSpacing:1},title:{color:'#f0d6a2',fontSize:23,fontWeight:'900'},phase:{color:'#d38366',fontSize:10,fontWeight:'900',marginTop:2},bossPortrait:{height:150,marginTop:10,borderWidth:1,borderColor:'#493f3a',borderRadius:9,backgroundColor:'#201d1d',alignItems:'center',justifyContent:'center'},silhouette:{fontSize:48,color:'#9e6d5f'},portraitText:{color:'#806f68',fontSize:9,fontWeight:'900',marginTop:6},hpLine:{flexDirection:'row',justifyContent:'space-between',marginTop:10},hpLabel:{color:'#a98d83',fontSize:9,fontWeight:'900'},hpValue:{color:'#f0e7df',fontSize:10,fontWeight:'900'},track:{height:12,borderRadius:6,backgroundColor:'#352725',overflow:'hidden',marginTop:5},fill:{height:'100%',backgroundColor:'#9e4e42'},grid:{flexDirection:'row',gap:7},stat:{flex:1,backgroundColor:'#15212a',borderWidth:1,borderColor:'#344553',borderRadius:9,padding:9},statLabel:{color:'#8399a8',fontSize:7.5,fontWeight:'900'},statValue:{color:'#edf0f2',fontSize:14,fontWeight:'900',marginTop:3},panel:{backgroundColor:'#101923',borderWidth:1,borderColor:'#334657',borderRadius:10,padding:12,gap:7},section:{color:'#c9b574',fontSize:10,fontWeight:'900',letterSpacing:.7},copy:{color:'#9fb0bb',fontSize:11,lineHeight:16},actions:{flexDirection:'row',gap:7,flexWrap:'wrap'},primary:{backgroundColor:'#8d4f40',borderRadius:8,paddingVertical:11,paddingHorizontal:15},disabled:{opacity:.45},primaryText:{color:'#fff0e6',fontWeight:'900',fontSize:11},secondary:{backgroundColor:'#192a35',borderWidth:1,borderColor:'#3b5364',borderRadius:8,paddingVertical:11,paddingHorizontal:12},secondaryText:{color:'#d7e1e6',fontWeight:'900',fontSize:11}});
